### ISSUE TITLE
[QA]Redeem screen is not opening, blocked by CORS policy error

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1000]
Preconditions:
1. Metamask wallet connected at sending From section
2. Solflare wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-907--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 APT from Moonbase to Solana
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction is not moving forward, error `Access to XMLHttpRequest at 'https://rpc.ankr.com/premium-http/aptos_testnet/de829957773bb0fa9e0aaeab57d988707e60eb06ae36be0658b778072d94979d/v1/accounts/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f/resource/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f::state::State' from origin 'https://deploy-preview-907--wormhole-connect.netlify.app' has been blocked by CORS policy` is shown in the console

Expected result: Transaction moves forward and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/14c9b025-f94f-4fcf-b15e-e22292995326

**Comment by tsadovska** [comment]
Rechecked on https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet].
Reproducible when:
* sending 0.01 APT from Goerli (Metamask) to Aptos (Rise)
* sending 0.01 APT from Goerli (Metamask) to Aptos (Spika)
* sending 0.002 APT from Mumbai (Metamask) to BSC (Metamask) 
* sending 0.001 APT from Moonbase (Metamask) to Solana (Phantom)

Transaction is displayed as Successful in Explorer, but the Redeem screen is not displayed. Transaction is displayed as loading. Funds are deducted, but not received.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3ad5b493-ee48-4bf1-b8ae-bf47390346df

Transactions can't be found with Menu -> Resume transaction. Error is displayed: "Bridge transaction not found, check that you have the correct chain and transaction ID". Transactions:
* [Etherscan](https://goerli.etherscan.io/tx/0x3aad3242868bed6bcafa4a948dd4cb74cbbe9cc1b05146cc8cc68a9b05a886a2) , 0x3aad3242868bed6bcafa4a948dd4cb74cbbe9cc1b05146cc8cc68a9b05a886a2
* [Etherscan](https://goerli.etherscan.io/tx/0x8fa5bf0bf408ebd4e08a4013c1ab5728e950c82b573c1d4bcdfa1e1a7149e414) , 0x8fa5bf0bf408ebd4e08a4013c1ab5728e950c82b573c1d4bcdfa1e1a7149e414
* [Mumbai](https://mumbai.polygonscan.com/tx/0xe10fa5e8184684459a757731a96b912d733f8a57667c73962ea23de446682a9f) , 0xe10fa5e8184684459a757731a96b912d733f8a57667c73962ea23de446682a9f
* [Moonbase](https://moonbase.moonscan.io/tx/0x3ecbccda5bcb4b1fb8d8f7692a86925a8494ef9acd1996d2a696c574b8cbb3a3) , 0x3ecbccda5bcb4b1fb8d8f7692a86925a8494ef9acd1996d2a696c574b8cbb3a3


![Screenshot 2023-09-21 at 11 25 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bb381b13-100a-4b21-a136-a14dc6a57d98)

Error is displayed in Console:

`Access to XMLHttpRequest at 'https://rpc.ankr.com/premium-http/aptos_testnet/de829957773bb0fa9e0aaeab57d988707e60eb06ae36be0658b778072d94979d/v1/accounts/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f/resource/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f::state::State' from origin 'https://deploy-preview-1015--wormhole-connect.netlify.app' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by AigaD** [comment]
The same error: `Access to XMLHttpRequest at 'https://rpc.ankr.com/premium-http/aptos_testnet/de829957773bb0fa9e0aaeab57d988707e60eb06ae36be0658b778072d94979d/v1/accounts/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f/resource/0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f::state::State' from origin 'https://wormhole-connect.netlify.app' has been blocked by CORS policy: ` is shown at Claim for transaction Alfajores -> Aptos
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

<img width="1324" alt="Screenshot 2023-10-03 at 12 45 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b36fd2e-cec0-456c-b5ab-326110d56d2a">

**Comment by AigaD** [comment]
Closing this ticket.
Tested from: https://wormhole-connect.netlify.app/
- Transaction APT from Moonbase to Solana Tested OK
- Transaction APT from Goerli to Aptos Tested OK for this ticket, redeem screen was opened. TX failed at Claim (Issue reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/1051 )
- Transaction APT from BSC to Fantom Tested OK

Attachment:
![Screenshot 2023-10-12 at 10 08 57](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/596e04ba-978a-4e43-bc72-4625358f6592)
