### ISSUE TITLE
[QA] Asset balance is not updated after changing wallet account

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1001]
## Describe the current behavior in detail
Asset balance is not updated after changing wallet account.

Checked on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Goerli network
2. Connect Metamask wallet with Account 1
3. Open Assets list
4. Change wallet account in Metamask extension
5. Connect Metamask wallet with Account 2
6. Open Assets list

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a833c83f-4994-4819-8646-6a2646001b78

## What is the expected/desired behavior
Asset balance is updated after changing wallet account.

**Comment by tsadovska** [comment]
Issue is also reproducible on:
- https://latest--wormhole-connect.netlify.app/
- https://portalbridge.com/cosmos/

**Comment by AigaD** [comment]
Issue also reproducible from: https://deploy-preview-1014--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8207823-f433-47cf-9593-9f74fdd59daf

**Comment by tonyjin** [comment]
Should be addressed by #1015
