### ISSUE TITLE
[QA] Assets are displayed in "All tokens" tab and are not present in "Available tokens" tab

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1002]
## Describe the current behavior in detail
USDC (Goerli) and USDC (Fuji) are displayed in "All tokens" tab and are not present in "Available tokens" list. 

Checked on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Solana network
2. Connect Phantom wallet
3. Open Assets list
4. Observe if USDC (Goerli) or USDC (Fuji) are displayed in "Available tokens" tab **(actual result: only USDC Solana is present)**
5. Switch to "All tokens" tab
6. Observe if USDC (Goerli) or USDC (Fuji) are displayed in "All tokens" tab **(actual result: assets are displayed)**

![Screenshot 2023-09-18 at 15 21 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1a4b2a0a-8186-42a9-a724-f6e701fece5d)

Note: User can send USDC (Goerli) / USDC (Fuji) from Solana. Asset is received as USDC (Goerli) / USDC (Fuji) on the destination chain.
* Send from tx: [Solana](https://explorer.solana.com/tx/4TDydEUHYUAot6P8crFixu8VM1E6caqzsyDSXz7TGEiWdjiwNRtok7vVEK1TxRPz5PBuUeqa1B2xKcaMcmuTHjmE?cluster=devnet)
* Send to tx: [Mumbai](https://mumbai.polygonscan.com/tx/0xc9aa575f63b7272a7f1310e0b0650a03dcf65b080438974bdfbbdd6390ab1960)

![Screenshot 2023-09-18 at 15 27 36](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f9512209-fe6c-482c-8260-ad50213e9166)

## What is the expected/desired behavior
USDC (Goerli) and USDC (Fuji) are displayed in "Available tokens" tab.

**Comment by tsadovska** [comment]
Build: https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]
Sent 0.1 USDC from Solana (Phantom) to Osmosis (Leap). From tx: [Solana explorer](https://explorer.solana.com/tx/4dMP4NMUw5PqzvsZLkWi2X8ipfVzDsEzUwBjcauNjCnThZE2YmiVaEoySCtvfsSq5PFgGUvvAJ9cRf7DwJdYFrdQ).
The received asset is shown in "All tokens" tab and is not shown in "Available tokens" tab.  



![Screenshot 2023-09-19 at 21 05 33](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bec80a2c-abb3-42de-9cc5-05d2caafeb1b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when Osmosis network is selected and Leap wallet is connected. USDC (Goerli), USDC (Mumbai), USDC (Fuji) assets are not present in "Available tokens" tab (balance: 0.02). 

![Screenshot 2023-09-25 at 15 03 20](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/feabe8db-74a1-4929-896f-a0aa7f377a9a)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/ [Mainnet]. USDC asset is displayed in "All tokens" tab and is not displayed in "Available tokens" tab.


Steps:
1. Send 0.001 USDC from Solana (Phantom) to Ethereum (Metamask)
2. Click "Add USDC to your wallet" link when bridge is completed
3. Observe that asset is received in the wallet
4. Observe asset in "Available tokens" list
5. Observe asset in "All tokens" list

Send from tx: [Solana explorer](https://explorer.solana.com/tx/47V5oDgd5Gk71RwomQafHXQZkEA7d58Tc8kFhzsDVrFgTfzNUD4dWKtSyPkhSqTy4X2c1LbFCxAHmd3vbyez9pir)
Send to tx: [Etherscan](https://etherscan.io/tx/0x291851365ff7fe907391dd977795c7a66b19b8f650f343d740fceaa602f38b6f)


![Screenshot 2023-10-04 at 13 38 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/50767367-6544-4364-8b33-ecb64ec82f3b)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
USDC (Arbitrum Goerli) is not shown for Cosmoshub in Available tokens tab, only in All Tokens tab.
Attachment:
Transaction from Arbitrum Goerli USDC (Arbitrum) to Cosmoshub:

![Screenshot 2023-10-18 at 16 43 07](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/12109755-3d65-4865-9fba-4571a40334a0)

Cosmoshub asset list:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/24d4a21c-1f3b-4b7c-9e25-d6be1449e73d

**Comment by tsadovska** [comment]
Reopening the ticket, because it is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:
1. Send 0.01 USDC (Solana) from Solana (Phantom) to Base (Metamask)
2. Click "Bridge more assets" button when transaction is completed
3. Select Base network in From section
4. Connect Metamask in From section
5. Open Assets list
6. Observe if USDC (Solana) asset is present in "Available tokens" tab
7. Observe if USDC (Solana) asset is present in "All tokens" tab

Actual result: USDC (Solana) asset is present in "All tokens" tab and is not present in "Available tokens" tab.

![Screenshot 2023-10-26 at 13 00 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e361b22f-4f86-41a1-8361-1984ad42e68a)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 USDC (Goerli) from BSC (Metamask) to Optimism Goerli (Metamask). 
* Send from tx: [BscScan](https://testnet.bscscan.com/tx/0xfb7e468de4e33dcff50f0359a3fe19fe45e214650682441a243f8134481a9013)
* Send to tx: [Optimism Goerli explorer](https://goerli-optimism.etherscan.io/tx/0x0bd0b743a0cc414112d6baacf827a24e0c12fd37ee79e1f35db1095b1362972c)

The received USDC Goerli asset (0x0786...a37f) is shown in "All tokens" tab, but is not present in "Available tokens" tab.

![Screenshot 2023-11-02 at 11 10 16](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/946e6423-28d0-44c2-8e47-d1343f3f3afc)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f9f4196f-c4d6-478a-b5c3-fe65a6e9735f)

**Comment by tsadovska** [comment]
USDC (Mumbai) asset is shown in "All tokens" tab and is not displayed in "Available tokens" list on Fuji.
Checked on https://wormhole-connect.netlify.app/ [Testnet].

Steps:
1. Send 0.1 USDC (Mumbai) from Fantom (Metamask) to Fuji (Metamask)
2. Observe that asset is received and shown in "Available tokens" list

Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0xdd42e71ddc77360f4dc293f8b3db5ce061c04a84dfc47fbab3a65b5a281148a7)
Send to tx: [Snowtrace](https://testnet.snowtrace.io/tx/0x05e1c1418f5bdf5c1807f1e36260946a23b0168607201c022248d32fea60b725 )

**Comment by tsadovska** [comment]
USDC (Ethereum) and USDC (Solana) are shown in "All tokens" tab and are not displayed in "Available tokens" list on Base.
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Steps:
1. Send 0.00001 USDC (Ethereum) from BSC (Metamask) to Base (Metamask)
2. Observe that asset is received and shown in "Available tokens" list

Send from tx: [BSCScan](https://bscscan.com/tx/0x5e6ec2b373ccfab7d90b55b93ae5d44e5c0630f582718ec75d0cce7a5be8120c)
Send to tx: [BaseScan](https://basescan.org/tx/0x117a308597b4dcd19e42477d833db993bdc7500edba28a9e0e213b022717c764)

**Comment by tsadovska** [comment]
USDC (Goerli) is shown shown in "All tokens" tab and is not shown in "Available tokens" list on Base. Checked on https://testnet.portalbridge.com/df5df83982/ [Testnet].

Steps:
1. Send 0.0001 USDC (Goerli) from Mumbai (Metamask) to Base Goerli (Metamask)
2. Observe that asset is received and is shown in "Available tokens" list


Send from tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x1151834a3d2b7b792c95257a7d456c73114c428ff8d9c4e0a65063273d4ad641)
Send to tx: [BaseScan](https://goerli.basescan.org/tx/0xe74e4152924084e20e93e648cb6a530c8deb2000a2beb99c684d6bfb0f018731)

**Comment by tsadovska** [comment]
USDC (Solana) is not shown in "Available tokens" list on Avalanche. Asset balance is >0. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 


![Screenshot 2024-01-05 at 15 31 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1bd25aaa-e98d-4cbf-a31e-b4d05c439cc2)

**Comment by tsadovska** [comment]
USDC (Base) is not shown in "Available tokens" list on Avalanche. Asset balance is >0. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4cad0838-ea18-4b5e-aa4c-7bac5cef5668)

**Comment by tsadovska** [comment]
USDC (BSC) is not displayed in "Available tokens" list on Polygon. Asset balance is >0.  Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/19c68af3-64ed-4764-93d6-eec0d2d6f7c6)

**Comment by tsadovska** [comment]
USDC (BSC) is not displayed in "Available tokens" list on Base. Asset balance is >0. Checked on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6). 

![Screenshot 2024-04-02 at 16 27 00](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c26018dd-623e-4b41-9e2e-f38832ac06de)

**Comment by tsadovska** [comment]
USDC (BSC) is not displayed in "Available tokens" list on Arbitrum. Asset balance is >0. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![Screenshot 2024-05-15 at 11 04 35](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0f23d5b7-641e-4d03-84d7-5a4dfbb9603b)

**Comment by agodlevska** [comment]
After the redesign, the 'All tokens' tab is no longer available. 
Closing the ticket.
