### ISSUE TITLE
[QA]Token not registered, transaction fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1006]
Preconditions:
1. Metamask wallet connected at sending From section
2. Solflare wallet connected at sending To section
3. Associated token account was not created for the wallet
4. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1005--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 ETH (Optimism) from Optimism to Solana
2. Observe if Create Account message is shown, click Create account
3. When account is created click Approve and proceed with transaction
4. Observe

Actual result: Transaction fails, error `Error: token not registered` shown in the console, message that token needs to be registered was not shown

Expected result: Message that token registration is needed is shown after account is created

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf53210e-6407-4ce2-b8f0-ac8d82220307

<img width="1316" alt="Screenshot 2023-09-19 at 15 02 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ace0cb09-b506-4a69-9422-0e684582f321">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/95e68155-d417-4090-b75a-b2531c2b6f8c

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Warning message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown to the user. Ticket is closed.
