### ISSUE TITLE
[QA]Fails to create associated token account

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1007]
Preconditions:
1. Sui wallet (0x94e1012fedb84ff3831e0ad94503efce6ea9f1650e2bdce3ccbdcaa65c0d53ed ) connected at sending From section
2. Solong wallet (Fn5poqMsyVAtVfJbjpSC3hHki76cPsSSHRFauWZXGidL) connected at sending To section
3. Associated token account was not created for the wallet
4. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1005--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 SUI from Sui to Solana
2. Observe if Create Account message is shown, click Create account
3. Observe

Actual result: Create associated account fails "Encountered an error, please try again.", error in console `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.`

Expected result: Token associated account is created

Attachment:

<img width="1303" alt="Screenshot 2023-09-19 at 16 43 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5d0ab64d-0c25-4e92-85c9-7fc55dbe3fd3">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5256673c-2528-4e53-8478-ea7af3717e79

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/66af2843-c64b-4af4-8408-11796735a03c

**Comment by AigaD** [comment]
Closing as duplicate https://github.com/wormhole-foundation/wormhole-connect/issues/593#issue-1701998142

**Comment by AigaD** [comment]
Re-opening the ticket. Failing to create associated account from mobile.
Tested from: https://wormhole-connect.netlify.app/
Environment: Samsung Galaxy S22+, OS12
Steps:
1. Connect Metamask wallet through WalletConnect option
2. Connect Solflare wallet using web wallet
3. Prepare to send 0.01 USDC from Fuji to Solana
4. Observe that No associated token account is created
5. Click on Create account
6. Approve the action on the window opened
7. Observe

Actual result: Associated account creation encountered an error

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e4a5cdf8-9153-4a0a-938c-160796feaa17

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] when sending 0.0001 WMATIC from Base (Metamask) to Solana (Phantom). 

Error:
```
WalletSendTransactionError: Unexpected error
    at v4.solana.phantom.sendTransaction (main.js:37:220062)
    at async d4.sendTransaction (main.js:37:160210)
    at async I4 (main.js:37:280736)
    at async Object.createAssociatedTokenAccount (main.js:137:153855)
    at async onClick (main.js:137:152568)
```
<img width="1162" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/485d27c4-163a-4d1c-b0b6-b1dad04375d3">

**Comment by AigaD** [comment]
Closing.
This has no longer been reproduced. User is able to Create associated account for Solana 
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://wormhole-connect.netlify.app/#
Attachment:

![Screenshot 2024-02-14 at 09 35 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/95ca510b-dc99-46a8-9fc3-5d8e9666ee8b)
