### ISSUE TITLE
[QA] Different gas fees shown opening explorer link and in resume transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1012]
Preconditions:
Metamask wallet connected 

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/#

Steps:
1. Prepare to send 0.02 USDC from Optimism to Ethereum
2. Click Approve and proceed with transaction
3. Observe Gas fees
4. Open Source chain explorer link
5. Observe Gas fee shown
6. Copy TX hash
7. On https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/# click Menu and Resume Transaction
8. Paste in the TX hash copied
9. Observe Gas fees shown

Actual result: Gas fees do not match with fees shown at the explorer link and resume transaction 

Expected result: Gas fees match

Comments: Here is the link for transactions where with red are marked gas fees that do not match - https://docs.google.com/spreadsheets/d/128zHVbllDoayKv9srzk9tIZSlYiIuCYmGKYNqQH16zk/edit?pli=1#gid=344426897

Attachment:

TX: https://optimistic.etherscan.io/tx/0x540d4b104ef6add759416f07433bee6a440150d9702599e29bdb49255c26ee2b

<img width="720" alt="Screenshot 2023-09-20 at 15 06 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6865641-767a-4375-aabf-812a4e7189c9">

<img width="1078" alt="Screenshot 2023-09-20 at 15 16 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6c9ab644-773d-41a5-b873-21d862dc69a5">

[Test Cases - 09_20 Portal Bridge.pdf](https://github.com/wormhole-foundation/wormhole-connect/files/12672898/Test.Cases.-.09_20.Portal.Bridge.pdf)

**Comment by AigaD** [comment]
Reproduced also from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Gas fees are different at explorer link and at resume transfer screen
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d4d9f90e-4f91-465a-8e5c-033e5bd15abd

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Different gas fee is shown on bridge screen and when opening explorer links
Attachment:
Bridge screen:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/68480a70-e330-487a-83c3-db9da01f5990

Redeem screen:
<img width="1214" alt="Screenshot 2023-09-27 at 11 33 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4580e479-89a4-4d6a-885b-d7a38dfcf249">

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/
Gas estimate instead of gas fee is shown at redeem screen ( TX hash from Solana - 5CDDz3C3ZDXF9vGvfxD8irJtWKNQSVSL8YrcpMuobQ3XsQnKb4UtTfwKef8n8uJ8yohW5AEfckHrFT9HYPNi86CC )
Attachment:
<img width="1162" alt="Screenshot 2023-10-04 at 09 57 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ff832cc1-838b-45d6-92a9-9d36be14e558">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Gas estimate not gas fee are shown on resume transaction screen.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a8da6c5d-ce95-4c01-8a0d-5445c1dc05b3

**Comment by tsadovska** [comment]
Re-checked the issue on https://portalbridge.com/.

Issue is no longer reproducible with following scenarios:
*  0.01 DAI transfer from [Osmosis](https://www.mintscan.io/osmosis/transactions/BF06FABEE9608CF5A22242717AE145BF10B09DD624EC6E71F28E7CC45B4489D5) (Leap) to [Solana](https://explorer.solana.com/tx/55WZowNQbWx43gdUnqodBsgfNjYMJkMhmFW3Sum3qt5gAaiDat4q5DFgx7a9vh4KmCZ9Vouu8wNgKUbdxaEchQeR) (Phantom) 
* 0.001 SOL transfer from [Solana](https://explorer.solana.com/tx/2s9DyqMsKMUCuasHtqhjVxxvHCtskeHUGHTFNHMipXeXJ1TZPx3jn21itGNHXq7EHm2doMKnqBRBmgAL11Q6BYsK) (Phantom) to [Sui](https://suivision.xyz/txblock/CNGV8b4X8qMCkfSoUL8oJPNnrs2jAmTJgEpuyza5AUBZ) (Sui wallet) 
* 0.0001 APT transfer from [BSC](https://bscscan.com/tx/0xa35ce9179f676cd7c75c50a217172810d5f7d5cec3905042b549d407facd9de7) (MetaMask) to [Fantom](https://ftmscan.com/tx/0xcbb0955706a4f7a2c524b43e5a7b33d60c8bec58ffe5e4426304563dcd0406e9) (MetaMask) 


Remaining issue:  https://github.com/wormhole-foundation/wormhole-connect/issues/2293, 0 ETH (Optimism) is shown as gas fee in "Send from" section when sending 0.02 USDC from [Optimism](https://optimistic.etherscan.io/tx/0xaf7c1a998723a7b31fd11717c1fc73770c6fa8668b81233b72e6cc43560e178a) (MetaMask) to [Ethereum](https://etherscan.io/tx/0xf77ed323038fb24bd6169f84f31779f7cca617455c9adbb005bd826c4c283bce) (MetaMask). 

Closing the ticket.
