### ISSUE TITLE
[Bug] - error recovering wstETH transfer from Osmosis to Ethereum

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1013]
## Describe the issue in detail

 - Add step-by-step repro instructions
see https://github.com/XLabs/portal-bridge-ui/issues/389

 - Add information about your environment: OS, browser, browser version, Connect package version
see https://github.com/XLabs/portal-bridge-ui/issues/389

 - Add information about your toolchain: package manager, package bundler
see https://github.com/XLabs/portal-bridge-ui/issues/389

 - If possible, add a screenshot of the issue, raw debug output, and/or a screenshot of the console log
see https://github.com/XLabs/portal-bridge-ui/issues/389

## What is the expected/desired behavior

The user should be able to recover the transfer

## Aditional comments

- as per the analysis on at portal bridge ticket, it seems the memo is not getting populated

**Comment by nik-suri** [comment]
I believe this should be closed @sebastianscatularo ?

**Comment by tsadovska** [comment]
Closing the ticket, because all subtasks were completed and Cosmos chains are no longer displayed on https://portalbridge.com/.
