### ISSUE TITLE
[QA]Wallets are not shown in wallet list before network is selected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1016]
Preconditions:
Wallets are not connected
Keplr wallet extension enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1014--wormhole-connect.netlify.app/#

Steps:
1. Click on Connect wallet
2. Search Keplr/Leap
3. Observe
4. Close the Connect Wallet window
5. Click on Select Network
6. Select Osmosis
7. Click on Connect Wallet 
8. Search Keplr/Leap

Actual result: Osmosis wallets are not shown if Connect Wallet if Network is not connected, wallets are shown if first Osmosis Network is chosen. Transaction to Osmosis is available (https://mumbai.polygonscan.com/tx/0x34105ee07865f1e314422f791ef945a0adc06bf7cf4d24dce41ad4936cb3f208)

Expected result: Supported wallets are shown in connect wallet list before network is selected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e8d301cc-df2e-4811-b068-67464e9f5a4a

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Click "Connect wallet" button and observe Cosmos wallets (actual result: Keplr, Leap, Fin and Compass wallets are shown)
2. Close Wallets screen
3. Select Cosmoshub/ Evmos network and open Wallets screen again (actual result: Coin98, Falcon, Leap, Keplr and OneKey wallets are present). 

Issues:
* Fin and Compass wallets are shown on Wallets screen when network is not selected and are not shown when Cosmoshub/ Evmos network is selected.
* Coin98, Falcon, OneKey wallets are shown when Cosmoshub/ Evmos network is selected and are not shown when network is not selected.

**Comment by M-Picco** [comment]
There was a bug which showed the wrong wallets for Cosmos chains. Should be fixed by #1144.
