### ISSUE TITLE
[QA] Warning message “Amount cannot exceed balance” is not shown when wallet is changed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1021]
## Describe the current behavior in detail
Warning message “Amount cannot exceed balance” is not shown when wallet is changed.

Checked on https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 117.0.5938.88 (Official Build) (x86_64).

Preconditions:
- User has 1 SOL in Backpack wallet
- User doesn't have SOL in Exodus wallet.

Steps:
1. Prepare to send 0.1 SOL from Solana (Backpack) to Fuji (Metamask)
2. Click "Approve and proceed with transaction" button
3. Click Deny button in Backpack notification
4. Change Backpack wallet to Exodus 
5. Observe if warning message is displayed.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aaf77be0-7368-4817-add6-a9997e190d56

## What is the expected/desired behavior
Warning message “Amount cannot exceed balance” is shown.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by AigaD** [comment]
Tested OK.
Warning message: "Amount cannot exceed balance" is shown when changing wallets.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1bce52be-26e8-4e7c-8032-262115cddb76
