### ISSUE TITLE
[QA][Mainnet]Balance not loaded when Networks are switched places

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1022]
Preconditions:
Metamask wallets connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 ETH from Goerli to BSC
2. Click on switch button to switch Network places
3. Open Asset list
4. Observe

Actual result: BNB asset balance is shown as loading

Expected result: Network asset balance is loaded

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3046f2df-fd29-411f-8963-28329bc577ee

**Comment by AigaD** [comment]
Same behaviour reproduced from: https://deploy-preview-1029--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d6181cc1-2b0c-47a9-ac88-1f5eb667db51

**Comment by AigaD** [comment]
Issue reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/839390ba-32e6-470a-941c-f22b107a34ca

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4ec986cd-cf19-4178-b0d5-5a2494c3179b

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
When switching network places balance for Asset at from section is not shown
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/53b0ff3e-2770-4c59-8d44-c012bc2fb1c8

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/
Balance is not loading for Selected network Native asset.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4356bb3f-8239-487b-90fc-511e6d84c30e

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Balance is not loading when user returns from Resume transaction screen and then click on switch places.
[Transaction from Base -> Moonbeam ](https://basescan.org/tx/0x2c395568a87bf6ba5ac72cc92ac87c2172a209569c31824b9d36fe5a2566ac7d)
Steps: 
1. Click on Resume transaction
2. Paste transaction hash 0x2c395568a87bf6ba5ac72cc92ac87c2172a209569c31824b9d36fe5a2566ac7d 
3. Select Base
4. Click Search
5. Click on "Bridge more assets"
6. Click on Switch places button
7. Open asset list for Moonbeam Network
8. Observe
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/310ee12d-060f-4281-b71b-90bde6e60595

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
Native Network balance is not loading when switching Network places
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae5fe97b-8de1-46cf-b9db-af9368a472da

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/
Balance for Native asset is not loading when switching Networks places.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/04a8be7f-ae38-41ab-9faf-40919e7ccaa2

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
When switching network places balance is not loaded, but all required fields for transaction are active and user can continue with transaction witch returns as failed, reason `Error: missing revert data in call exception; Transaction reverted without a reason string `
Raising priority
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e8fee200-8b2b-465d-a8f3-2782890bd08b

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/ [Mainnet]. Balance is not loaded with following scenario:
1. Select Sui as source chain
2. Select Klaytn as destination chain
3. Connect Sui MetaMask Snap wallet in "From" section
4. Connect MetaMask wallet in "To" section 
5. Click on "Swap" button
6. Open Assets list


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/17a7224c-97b5-4bd9-bcce-21498df5c713

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
When switching network places, balance is not loading for Native asset for the network
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1ac37050-834b-40f0-b5a5-46af6e0ad595

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Balance is loaded correctly in "From" section and on "Select asset" screen. 

Ticket is closed.
