### ISSUE TITLE
[QA] Improvement: Show small amount that is being sent

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1023]
Preconditions:
Metamask wallets connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.0000001 ETH from Goerli to Moonbase
2. Click Approve and proceed with transaction
3. Observe the amount that was sent and received

Actual result: Amount send and received shows as 0 WETH

Improvement: Amount should be displayed even if small values are sent

Attachment:
TX - https://goerli.etherscan.io/tx/0xb158ad4654c9e22e16c46a8a6f1e49b3539138dc20b6875b3eb0223e5217675e

<img width="788" alt="Screenshot 2023-09-25 at 09 50 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cc179c5b-b6ea-4f0d-9605-317b0612e157">

<img width="963" alt="Screenshot 2023-09-25 at 09 51 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c9b262ba-b055-4a1d-a760-66933d0767ce">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with the scenario from the description.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0000001 FTM from Fantom (Metamask) to Avalanche (Metamask). Small amount is rounded on Redeem screen. 

* Send from tx: [FTMScan](https://ftmscan.com/tx/0x83733c0caf47840d75625e7e4f1aefcc4cf02a4de9e07fe452e1c7de7d9eacd1)
* Send to tx: [Snowtrace](https://snowtrace.io/tx/0xcc005f08933770e67ba830016eff9069231c2fac3906331a6117721f9a8f5435)


![Screenshot 2023-11-08 at 11 49 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/75ca77e2-1e7c-4dfb-b62f-92d4dae3b916)


![Screenshot 2023-11-08 at 11 50 36](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/62e20b95-8f8f-4b9d-88b1-1a36ad40a13f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0000001 AVAX from Fuji (Metamask) to Sei (Leap). Small amount is rounded on Redeem screen.
* Send from tx: [AvaScan](https://testnet.avascan.info/blockchain/c/tx/0xf301b28713689de9b600dea272de715d1a7af0a1663e162b2b00cd8fe1a39df8)
* Send from tx: [Wormholescan](https://wormholescan.io/#/tx/0xf301b28713689de9b600dea272de715d1a7af0a1663e162b2b00cd8fe1a39df8?network=TESTNET)

<img width="612" alt="Screenshot 2024-01-10 at 15 23 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/12c0e96a-905a-4d5c-b191-ce81821729e2">

**Comment by agodlevska** [comment]
Still reproducible on https://wormhole-connect.netlify.app/ (connect v2), when sending 0.0000001 BNB from BSC (MetaMask) to Fantom (MetaMask). Small amount is rounded on Redeem screen.

Attachment:
<img width="580" alt="Screenshot 2024-09-10 at 16 43 27" src="https://github.com/user-attachments/assets/d6fc5d7e-16da-4230-91d9-ea9bca347301">

**Comment by tsadovska** [comment]
Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2557.
