### ISSUE TITLE
[QA] FTM transfer is stuck on Step 2, tx Fantom -> Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1025]
## Describe the current behavior in detail
Transaction is not completed (stuck on Step 2) when sending FTM from Fantom (Metamask) to Sui (Sui) with Automatic deposit. 

Checked from https://wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 117.0.5938.92 (Official Build) (x86_64).

Steps:
1. Open Menu -> Resume transaction
2. Search for tx hash `0xe9ef879075d04b4d64e8770114a71adc25869f00c60cbabd0c54775bce38d7f2` in Fantom network
3. Observe if transaction is completed

Error is displayed in Console:
```
Uncaught (in promise) Error: Unknown RPC Error
    at ha.requestWithType (main.624ce4e7.js:37:4694169)
    at async mi.getObject (main.624ce4e7.js:37:4721070)

```
Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0xe9ef879075d04b4d64e8770114a71adc25869f00c60cbabd0c54775bce38d7f2)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d4baac1d-6ea6-4335-8748-0dfa83241036)

## What is the expected/desired behavior
User can successfully send and receive assets.

**Comment by tsadovska** [comment]
Issue will be rechecked after #942 is resolved. User is not able to select "Automatic Deposit, One transaction" option in Route section. It switches back to "Bridge, Two transactions".

**Comment by AigaD** [comment]
Tested OK. 
Tested from: https://wormhole-connect.netlify.app/#
[Fantom explorer](https://testnet.ftmscan.com/tx/0x4bdb20d944c666cbe58a47f536a3b587598cdf7a890803d0b7034830d3559157)

Attachment:
<img width="1153" alt="Screenshot 2023-10-30 at 11 01 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/de217e87-0be6-406a-b0c2-3a464d1ac97b">
