### ISSUE TITLE
[QA] Some WalletConnect wallet options opens an empty link

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#103]
Preconditions:
Wallet is not connected

Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on "Connect wallet"
2. On pop-up window click WalletConnect
3. Click Desktop
4. Click on one of these wallets - Ledger, Crypto.com, Wallet3, Bobablocks, Verso (returns - 404), Exodus, Nufinetes
5. Observe

Actual result: WalletConnect - Ledger, Crypto.com, Wallet3, Bobablocks, Verso (returns - 404), Exodus, Nufinetes leads to empty links.

Expected result: Link should be opened with option to either open the wallet or download it.

Attachments:

https://user-images.githubusercontent.com/91047061/220317571-69a72d8c-f7af-48d7-9bb7-1ec46da94113.mov

**Comment by tsadovska** [comment]
Closing the ticket as it has status "wontfix".
