### ISSUE TITLE
[QA] Amount is not updated on tooltip when user changes slider position

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1031]
## Describe the current behavior in detail
0 ETH (Base) is shown on tooltip when user changes slider position. Amount should have more decimals after comma. 

Checked on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] with macOS version 12.6.7 and Google Chrome Version 117.0.5938.92 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.55 SOL from Solana (Phantom) to Base (Metamask)
2. Change slider position in Native gas section

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1b265dca-a783-41b6-bafd-f70fcdcd0556

## What is the expected/desired behavior
ETH (Base) amount is updated when user changes slider position.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 2.3 SUI from Sui (Sui wallet) to Solana (Nightly). "0 SOL" is shown on tooltip when user changes slider position.




https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5de72768-6a4f-4c83-a4a1-75f75c5b4bc7

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0005 ETH from Ethereum (Metamask) to Solana (Phantom). "0 ETH" is shown on tooltip when user changes slider position.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/033ab8be-7648-4a21-be14-2f50c4684df2

**Comment by agodlevska** [comment]
Issue no longer reproducible on https://wormhole-connect.netlify.app/ and https://wormhole-connect.netlify.app/.
Now the tooltip does not have text but percentages.

Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/4f7e7368-42ba-49aa-9200-539e95a242a9
