### ISSUE TITLE
[QA] Incorrect amount shown in Native Gas section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1032]
Preconditions:
Metamask wallets connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 2.9 MATIC from Polygon to Base
2. Observe total amount in One transaction Route
3. Observe total amount in Native Gas section
4. Observe total amount in Preview

Actual result: Total amount in Native gas section is lower by 0.000001 MATIC than in Preview

Expected result: Native Gas section shows the same amount as in preview

Attachment:

<img width="1117" alt="Screenshot 2023-09-26 at 12 26 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/866bed93-66e6-496b-90ee-5059b51ee9cd">

<img width="1134" alt="Screenshot 2023-09-26 at 13 08 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3c96ed55-fa7c-4c7d-879b-89aafe7a73da">

<img width="1174" alt="Screenshot 2023-09-26 at 12 24 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/21710e6d-81df-45af-8855-e47c1177d2fc">

**Comment by tsadovska** [comment]
Issue will be rechecked on https://wormhole-connect.netlify.app/ [Testnet] after #1079 is resolved.

**Comment by AigaD** [comment]
Closing. Tested OK. 
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

<img width="1150" alt="Screenshot 2023-10-30 at 10 39 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91960d4a-2ee7-48d0-86ce-6580f01bba65">
