### ISSUE TITLE
[QA] SUI transfer is stuck on Step 2, tx Sui -> Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1037]
## Describe the current behavior in detail
Transaction is not completed (stuck on Step 2) when sending SUI from Sui (Sui wallet) to Solana (Phantom) with Automatic deposit.

Checked on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] with macOS 12.6.7 and Google Chrome Version 117.0.5938.92 (Official Build) (x86_64).

Steps:
1. Open Menu -> Resume transaction
2. Search for transaction hash `Bgyn4NNYWkXERJqoLb9A61m6n7DJ1EGnjFom95bcMoAR` in Sui network
3. Observe if transaction is completed

Send from transactions:
- [Sui explorer 1](https://suiexplorer.com/txblock/Bgyn4NNYWkXERJqoLb9A61m6n7DJ1EGnjFom95bcMoAR)
- [Sui explorer 2](https://suiexplorer.com/txblock/7JDWdVs3YzA9d38zYMPtkJUfxrn6eCL6JvyoUVvD3om7)

Linked issues: #1024, #1025 (not able to receive asset on Sui)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/160513eb-6cbf-4963-9f6f-1405adeba390)

## What is the expected/desired behavior
User can successfully send and receive asset.

**Comment by kev1n-peters** [comment]
Addressed in https://github.com/wormhole-foundation/wormhole-connect/pull/1040

**Comment by AigaD** [comment]
Issue is no longer reproduced, transaction SUI from Sui to Solana is successful.
Tested from: https://wormhole-connect-mainnet.netlify.app/
https://suiexplorer.com/txblock/8PALFkrCV4f72ypghFAebmTUzrveTjNcF9amZ2mTqe1n 

<img width="1344" alt="Screenshot 2023-10-03 at 16 47 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b2a545c0-2858-40fd-863d-8834f4687040">

However noticed that in the initial ticket and transaction made now the receiving wallet number is not correct. In both screenshots they match, but different wallet accounts were used for tests. Adding this observation to this ticket #978 
<img width="1235" alt="Screenshot 2023-10-03 at 16 46 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a4aea087-d8ab-4e4a-8476-775425ee0c7f">
