### ISSUE TITLE
[QA] "Native token on destination" value is not updated if slider for Extra native gas is moved all the way to the end

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#104]
Preconditions: Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Microsoft Edge Version 110.0.1587.50 (Official build) (arm64)

Steps:
1. Prepare to send 2 ETH from “Goerli” network to “Mumbai”
2. Expand “Extra native gas” section
3. Move slider to position “0.047846 MATIC”
4. Observe "Preview" - "Native token on destination" if it shows “0.047846 MATIC”
5. Move slider all the way to the end "0.100395 MATIC"
6. Observe "Preview" - "Native token on destination" if it shows "0.100395 MATIC"

Actual result: If slider is moved to the very end "Native token on destination" in Preview section is not updated with correct MATIC numbers.

Expected result: Correct MATIC values are shown at "Native token on destination"

Comments: Linked issue- https://github.com/wormhole-foundation/wormhole-connect/issues/93#issue-1591759728
Attachments:

https://user-images.githubusercontent.com/91047061/220354062-c898e7d3-450b-4724-bb31-6e9b18062079.mov

**Comment by anondev2323** [comment]
This was fixed.  Double checked on the current netlify deployment

https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/aaeeb10c-052c-40fa-8cd7-3fb6cf19a8c9

**Comment by AigaD** [comment]
Tested OK
Scenario: Verify that preview section is updated accordingly to Native gas slider position.
Tested from: https://wormhole-connect.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/292db022-4bf8-4edf-9c49-204d41c65f7a
