### ISSUE TITLE
[QA] [Mainnet] Balances of wrapped assets are not loading 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1042]
## Describe the current behavior in detail
Builds:
* https://wormhole-connect.netlify.app/ - Tested OK
* https://wormhole-connect-mainnet.netlify.app/ - NOK

Checked on macOS 12.6.7 with Google Chrome Version 117.0.5938.92 (Official Build) (x86_64)

Steps:
1. Select Ethereum network as source chain
2. Connect Metamask wallet
3. Open Assets list

Only native asset balance is loaded.

Note: Issue is also reproducible with BSC, Polygon, Avalanche and other networks.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/49e2e629-4ad4-4750-8089-deab35970820)

## What is the expected/desired behavior
Balances of wrapped assets are loaded.

**Comment by evan-gray** [comment]
There were two issues with the new build - one was a netlify configuration issue which I fixed, the other is with wormhole.rpcpool.com, which I'm waiting on. This should now work, except for Solana.

**Comment by tsadovska** [comment]
Thank you @evan-gray ! Rechecked that balances are shown for following networks: Ethereum, BSC, Polygon, Avalanche, Fantom, Celo, Moonbeam, Sui, Base, Optimism.

Balances are not shown for Solana, Aptos, Osmosis, Arbitrum. Balance for Arbitrum network is shown only for a brief moment. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/779fe281-cd9c-47ac-842f-b6accecd51ec

**Comment by evan-gray** [comment]
Just checked on this - I'm seeing
- Solana - fixed
- Aptos - something is up with the ankr endpoint, @tonyjin investigating
- Osmosis - allow list issue, @tonyjin will follow up
- Arbitrum - I think this is due to a double request that happens with requests, should be fixed with upcoming rpc request improvements.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect-mainnet.netlify.app/
Balance for wrapped assets are loaded.
Checked from: Solana, Aptos, Arbitrum, Optimism, Osmosis
Closing the ticket.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a8baa028-074e-43be-803c-ed7e96fd22c2
