### ISSUE TITLE
[QA] Fields are not shown after switching Network places

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1046]
Preconditions:
Metamask wallets connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Select Moonbase Network at Sending from section
2. Select Alfajores Network at sending To section
3. Now click on "Switch" button to switch Network places
4. Open Assets and select Celo
5. Enter amount 0.1
6. Observe

Actual result: Route, Native gas and Preview fields are not shown after switching Network places. In order to show user has to change the amount again

Expected result: Route, Native gas, Preview field and Approve and proceed with transaction button is shown when all fields are filled in on first try

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b1c57bea-2053-4afa-9848-c44e69f178ef

**Comment by AigaD** [comment]
Issue reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
Same behaviour reproduced where fields are not shown when first entering the amount after returning from Resume transaction screen.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/eca3171d-e222-48b9-8476-86617cc8eb06

**Comment by tsadovska** [comment]
Rechecked scenario:
1. Select Moonbase/Moonbeam as source chain
2. Select Alfajores/Celo as destination chain
3. Connect Metamask wallets
4. Click Swap button
5. Select CELO asset
6. Select Amount 0.1 

Tested OK on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
Testned NOK on https://wormhole-connect.netlify.app/ [Testnet]

**Comment by tsadovska** [comment]
Linked to #868.

**Comment by AigaD** [comment]
Tested OK, closing the ticket.
Tested from: https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ab2a351d-c9b7-4fbf-9417-682efa10904d
