### ISSUE TITLE
[QA] [Testnet] Automatic deposit transactions are stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1047]
## Describe the current behavior in detail
Build: https://wormhole-connect.netlify.app/ [Testnet]

Checked on macOS 12.7 with Google Chrome Version 117.0.5938.132 (Official Build) (x86_64). 

Steps:
1. Open Menu > Resume transaction
2. Search for tx hash `0xe6169a39440b773d2d2adf2339bc81f804d1a75e039ad0667bea4561f6b84e54` in Fuji network (sent 0.01 AVAX from Fuji to Fantom)
3. Observe if transaction is completed

Transaction is not completed, stuck on Step 2. 

Notes:
* Issue is also reproducible when searching for tx hash `0x2a6896b1ed71735f0b84cc0990cb4493a64df30b3cc207f93ab12661e2d4bd1f` in BSC network (sent 0.01 BNB from BSC to Fantom)
* Send from tx (Fuji): [Snowtrace](https://testnet.snowtrace.io/tx/0xe6169a39440b773d2d2adf2339bc81f804d1a75e039ad0667bea4561f6b84e54)
* Send from tx (BSC): [BscScan](https://testnet.bscscan.com/tx/0x2a6896b1ed71735f0b84cc0990cb4493a64df30b3cc207f93ab12661e2d4bd1f)

<img width="1398" alt="Screenshot 2023-09-29 at 17 58 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/74aa9cec-4179-4243-aaf7-558a49bd2113">

<img width="1395" alt="Screenshot 2023-09-29 at 17 58 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/92cf448b-202f-4afe-94bc-ec6b4e732df8">

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by AigaD** [comment]
The same behaviour observed for transaction Fantom -> Solana (TX hash - 0xc7cb1e81cf1b20d7ad0c149fea5bed0a9d74575d356a7f2b80f130931e2be6f8 )
Transaction is stuck on Step 2.
Tested from: https://wormhole-connect.netlify.app/
Attachment:
<img width="851" alt="Screenshot 2023-10-02 at 11 16 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c872fc18-4a22-4bb7-82c3-a0586d2907ba">

**Comment by tsadovska** [comment]
Checked on https://wormhole-connect.netlify.app/ [Testnet]

Scenarios - Tested NOK:
* Send 0.001 ETH from Goerli (Metamask) to BSC (Metamask) with automatic deposit. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x012743e6f107f7e6cb84a48920d80edbbdb819cfef8138f735d3fa45cc17ac32), `0x012743e6f107f7e6cb84a48920d80edbbdb819cfef8138f735d3fa45cc17ac32`
* Send 0.01 AVAX from Fuji (Metamask) to Alfajores (Metamask) with automatic deposit. Send from tx: [Snowtrace](https://testnet.snowtrace.io/tx/0xd03a67eb615891f82e0289120760c3fafc0db6df294ca8f0aac810b5e4cb0444), `0xd03a67eb615891f82e0289120760c3fafc0db6df294ca8f0aac810b5e4cb0444`

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fadafe38-57d4-4ff0-b4b5-5b75b5137155)

Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending FTM from Fantom (Metamask) to Fuji (Metamask) with automatic deposit.
* Send from tx: [FTMScan](https://ftmscan.com/tx/0x467adabc8fe9aa4b7439f09e159f3871059466fbabfcfc723cc901bf17ff8393)
* Send to tx: [Snowtrace](https://snowtrace.io/tx/0x529a56b3a85f6c69d3074c9e750d4d9ff3e9bd0c22b89d0876930b713c29b873)

**Comment by AigaD** [comment]
Transaction BNB from BSC to Osmosis not moving forward Step 2
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

![Screenshot 2023-10-11 at 10 04 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/58f27638-f4e4-4433-a6fa-4c1de58b1229)

**Comment by tsadovska** [comment]
Rechecked the mentioned scenarios on https://wormhole-connect.netlify.app/ [Testnet]:
* Send 0.0106 AVAX from Fuji to Fantom with automatic deposit - Tested OK ([Snowtrace](https://testnet.snowtrace.io/tx/0xc6ff346119a484dc58f7f11c8a48001bdd4588bac01b3dc9804a0a4ac03088e8), [FTMScan](https://testnet.ftmscan.com/tx/0xb5592b33af6ae2aa418c907ed263fe35573de976bffea42509b9d70570cb5455))
* Send 0.01 BNB from BSC (Metamask) to Fuji (Metamask) with automatic deposit - Tested OK ([BSCScan](https://testnet.bscscan.com/tx/0x32d35a59ac185676f31733587f9ddc8f1179d75a2b79626c4d64ecc16097b4c9), [Snowtrace](https://testnet.snowtrace.io/tx/0x2154824a9bce8e97ef7230966be215c6baafaf62b5d92195330f5b49af783274))
* Send 4.9 FTM from Fantom (Metamask) to Solana (Phantom) with automatic deposit - Tested OK ([FTMScan](https://testnet.ftmscan.com/tx/0x8837fccaefd21e6603f8a555c3af8f5691a52cb34829c0da9b654ea08e801542), [Solana explorer](https://explorer.solana.com/tx/5BC2ZbjnXQ5BECZn7mt86RzSnx7hcMZFuMXeVdJq4Zvdm1MCJvrLF4D8wMV6sWFeRzgjJJQSxmBVhsatR6LhdXT?cluster=devnet))
* Send 0.001 ETH from Goerli (Metamask) to BSC (Metamask) with automatic deposit - Tested OK ([Etherscan](https://goerli.etherscan.io/tx/0xfed95ed29d5bb6e0ff5817fa5c92031c98cc5361053e57a0070324cf3b742c1e), [BSCScan](https://testnet.bscscan.com/tx/0xad37f73a98403f89c52f05adc2d4899835e319942425e40b5e79906bab44dd2b))
* Send 0.01 AVAX from Fuji (Metamask) to Alfajores (Metamask) with automatic deposit - Tested OK ([Snowtrace](https://testnet.snowtrace.io/tx/0x2a81bfbc95b0ddead92e05e180982a896be1a8db3ad7076279718cc699e0b599), [Celo explorer](https://explorer.celo.org/alfajores/tx/0x798ca8eff5c0cf951fcce089555c0a83e71859c68162ee0967b987e6da04b7c8))

Remaining issues:
* https://github.com/wormhole-foundation/wormhole-connect/issues/1145
* https://github.com/wormhole-foundation/wormhole-connect/issues/1146
* https://github.com/wormhole-foundation/wormhole-connect/issues/1147
* https://github.com/wormhole-foundation/wormhole-connect/issues/1148

Ticket is closed.

**Comment by AigaD** [comment]
Re-opening the ticket. Multiple transactions with automatic deposit are not moving forward than Step 2, although Wormhole scan shows that the transaction is completed.
Tested from: https://wormhole-connect.netlify.app/
[Transaction](https://testnet.bscscan.com/tx/0xbbd723058f7796aab7585a0812e5baeb3862999db0bf279ac6ec0471cfd9a9a9) from BSC to Cosmoshub
[Transaction](https://testnet.snowtrace.io/tx/0xe871066e23fe17cf58a1a5ba6f3636acdbe38235320f44d29ea1e20fe7b22d0e) Fuji to Cosmoshub
[Transaction](https://testnet.ftmscan.com/tx/0xa23d19ff2fa02d1dca0f5b60c7b9d657fb003fc19dd3709bf4079fb13d1eeaba) Fantom to Cosmoshub
Linking together and closing #1145 [Transaction](https://testnet.bscscan.com/tx/0xbbd723058f7796aab7585a0812e5baeb3862999db0bf279ac6ec0471cfd9a9a9) 0.1 WFTM from BSC to Cosmoshub

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/50172f22-d35a-4938-8cf8-0aaf3cbc4e5e

**Comment by aadam-10** [comment]
Closing as the new batch of issues in the most recent comment are related to Cosmos testnet issues, and they're already captured in 

* https://github.com/wormhole-foundation/wormhole-connect/issues/1146
* https://github.com/wormhole-foundation/wormhole-connect/issues/1147
* https://github.com/wormhole-foundation/wormhole-connect/issues/1148

**Comment by tsadovska** [comment]
Reopening the ticket. Automatic deposit transactions are stuck on Step 2 on https://wormhole-connect.netlify.app/ [Testnet].
1) Scenario "Send 0.01 WETH with automatic deposit from Goerli (Metamask) to Fuji (Metamask)"
Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xefdb7864b1cda2cb17ea3fc44302abb79bca22870815d394e590b0c92444e686)

 
![Screenshot 2024-01-02 at 09 59 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bf521406-ecb5-4c0b-9c18-e8f3b83bb812)


2) Scenario "Send 0.5 WMATIC with automatic deposit from Mumbai (Metamask) to Alfajores (Metamask)"
Send from tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x2005e261415d7c6307cf2ae0693aa8ba67ff967c795077aac95942558ccb55d9)


![Screenshot 2024-01-02 at 10 01 25](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ec87a3ef-bce0-4b4d-95e2-98784c2cf28e)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 
Scenarios - Tested OK:
* Send 0.01 ETH from Goerli (Metamask) to Fuji (Metamask) with automatic deposit (without native gas on destination) - [Etherscan](https://goerli.etherscan.io/tx/0x945807cbe7ffd43a729cffc54cf18cc1a70010a8c97cd9a2f0e36162babd4df1), [Avanscan](https://testnet.avascan.info/blockchain/c/tx/0x245e63efefc771a1c9a6df171acaa2b9fde0488d86f652256f190fdc80894368)
* Send 0.01 ETH from Goerli (Metamask) to Fuji (Metamask) with automatic deposit (with native gas on destination) - [Etherscan](https://goerli.etherscan.io/tx/0x6845aa209c323007465c655aa97e6f93b8fdb9c8fd1e41be77364bd87bafe4a5), [Avanscan](https://testnet.avascan.info/blockchain/c/tx/0x93f89f38ebaa8db8eb084e9a6442a13faf653d803bb4e12ba1c5e8bf89e03228)
* Send 0.4 MATIC from Mumbai (Metamask) to Alfajores (Metamask) with automatic deposit (with native gas on destination) - [Polygonscan](https://mumbai.polygonscan.com/tx/0x81bf884965bd97e7f605e1ecd96647f1b478ce69deaa12df7cac1422a37ca4ec), [Celo explorer](https://explorer.celo.org/alfajores/tx/0x8514be92b99b10d0f36da074847e1b5c54481e888cb9525a74415dcb491cd8e0)

Ticket is closed.
