### ISSUE TITLE
[QA] Clicking on the blank space in the window closes it

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1048]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 117.0.5938.132 (Official Build) (x86_64).

Steps:
1. Click "Connect wallet" button
2. Click on the blank space inside the window

Window closes when user clicks on the blank space inside it. 

Note:
Issue is reproducible with Networks list window and Assets list window. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c72dd1aa-ac00-4821-a902-f9e21933c5e5

## What is the expected/desired behavior
Window closes when user clicks on Close button.

**Comment by anondev2323** [comment]
This was a request and is desired behavior. Going to close this issue
