### ISSUE TITLE
[QA] Claiming on Aptos fails

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1051]
## Describe the current behavior in detail
Checked https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 117.0.5938.132 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 ETH from Goerli (Metamask) to Aptos (Spika)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen

Error is displayed n Console:
```
Error: Transaction failed
    at i.<anonymous> (main.85265285.js:37:4431192)
    at Generator.next (<anonymous>)
    at i (main.85265285.js:37:4427893)
```

Send from tx: [Etherscan]( https://goerli.etherscan.io/tx/0xa75e51da06e570066268f77ae947b4216cc0ec23d3edc6f1618a45f45fcf8a18)

![Screenshot 2023-10-03 at 11 23 22](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8c3e54ed-a0e3-48e7-8ce1-7c0747d29d4a)

## What is the expected/desired behavior
Claiming on Aptos is successful.

**Comment by AigaD** [comment]
Issue is reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
Claim on Aptos fails when sending SOL from Solana to Aptos
Attachment:
<img width="1314" alt="Screenshot 2023-10-04 at 12 34 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bad0c9e7-6443-4244-9dcc-d7c1ad1613b8">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c47a72ea-cb73-4e13-b73d-37340a861361

**Comment by AigaD** [comment]
Issue reproducible from: https://wormhole-connect.netlify.app/
Transaction 0.001 APT from Goerli to Aptos fails at Claim.
Attachment:
![Screenshot 2023-10-12 at 10 02 04](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bd8e4751-1849-4573-920b-3d9168504385)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenarios:
* Send 0.01 ETH from Goerli (Metamask) to Aptos (Spika): [Etherscan](https://goerli.etherscan.io/tx/0x9cef02400135558a200a80c72c1dea9e2a55e2987cda88f602196e5cf0d6f04c), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x1b898c0e1d0f55825f86ddaac3d28e03203660ab3e049c902093071593d36865?network=testnet)
* Send 0.001 APT from Goerli (Metamask) to Aptos (Spika):  [Etherscan](https://goerli.etherscan.io/tx/0x324ad30b792fe9077351b6fa55103b270db60c95cf291cc3653f2402d8ad21db),  [Aptos explorer](https://explorer.aptoslabs.com/txn/0xfe4a460b6b8f0000b70f3d8659faf09e942834958bd82cb911faeaaf3bfc5a30?network=testnet)

Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenarios:
* Send 0.0001 WSOL from Sui (Sui walllet) to Aptos (Spika): [Sui explorer](https://suiexplorer.com/txblock/AkrcNHDcqbe1b58mfoRyiAgtVF3G14JNYDKHYS7rEqPu), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x1ec697e02b6b8aa57ca5ca7cbb198a541f61efba567e79e2eed87fd8029b7a4e)
* Send 0.01 SOL from Solana (Phantom) to Aptos (Spika): [Solana explorer](https://explorer.solana.com/tx/2Z1ngBVWiZqQjyckCxAkbehNpf7qxofSHg8awK4PxZbxvPb69xs2a7G4cPHEa3ymMTr4Fuf2KCLsGUyogyknGf1j), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x52c100031799a93d2bfe59851a29d95aaeae1239595f7d54d00b00a8df40996c)

Ticket is closed.
