### ISSUE TITLE
[QA] Glitch in Route section when sending to Moonbase

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1052]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 117.0.5938.132 (Official Build) (x86_64).

Steps:
1. Prepare to send FTM from Fantom (Metamask) to Moonbase (Metamask)
2. Enter Amount 4 FTM
3. Observe Route section

"One transaction" and "Two transactions" options are swapped several times. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a46c8667-8400-41bb-a921-79c0fac6108c

Issue is also reproducible when:
* 2 BNB from BSC to Moonbase
* 1 AVAX from Fuji to Moonbase
* 1 CELO from Alfajores to Moobase

Error is displayed in Console:
```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x9563a59C15842a6f322B10f69d1dD88b41f2E97B","data":"0x8e151dd10000000000000000000000002e8afecc19842229358f3650cc3f091908dcbab40000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"VM Exception while processing transaction: revert swap rate not set\",\"data\":\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000\"},\"id\":140}","error":{"code":-32603,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x9563a59c15842a6f322b10f69d1dd88b41f2e97b\",\"data\":\"0x8e151dd10000000000000000000000002e8afecc19842229358f3650cc3f091908dcbab40000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":140,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.api.moonbase.moonbeam.network"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.85265285.js:37:3857993)
    at l.throwError (main.85265285.js:37:3858113)
    at y (main.85265285.js:37:3915009)
    at c.<anonymous> (main.85265285.js:37:3925193)
    at Generator.throw (<anonymous>)
    at s (main.85265285.js:37:3914340)
```

## What is the expected/desired behavior
"One transaction" and "Two transactions" options are not swapped.

**Comment by aadam-10** [comment]
discussed in one of the meetings: the route options should only update when the input field loses focus (e.g. is clicked out of)

**Comment by AigaD** [comment]
Tested OK. Testing from: https://wormhole-connect.netlify.app/#
Tested scenarios:
- 4 FTM from Fantom to Moonbase
- 2 CELO from Alfajores to Moonbase
- 2 BNB from BSC to Moonbase
- 1 AVAX from Fuji to Moonbase

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4b4e045c-ce60-4c7f-8199-cbc0e2276d9d
