### ISSUE TITLE
[QA] Transaction from Sui Fewcha Move wallet fails after confirming

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1054]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 with Google Chrome Version 117.0.5938.132 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SUI from Sui (Fewcha Move) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Observe if Redeem screen is displayed

Redeem screen is not opening. To complete the transaction, user has to find the transaction in the wallet and resume it. 

Send from tx: [Sui explorer](https://suiexplorer.com/txblock/4JAma9HgqPi2h5TiFAoqihx4SaASrhAF4PUUFSkCJFAT?network=testnet)
Send to tx: [Solana explorer](https://explorer.solana.com/tx/4o8nkerBnZsawGXmPuESbnvi6UDePoXgwvWyJLuXSyEy2aUyfCrWqTXuYxP1vLwLGdM1xcwD3jdogNJgvCoDqBLC?cluster=devnet)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a75c1b8b-37ba-49bf-b20e-500b08fdcfa2

Notes:
Issue is not reproducible when sending 0.01 SUI from:
* Sui (Sui wallet) to Solana (Phantom)
* Sui (Nightly) to Solana (Phantom)
* Sui (Martian Sui) to Solana (Phantom)

Issue is reproducible when sending 0.01 SUI from Sui (Fewcha Move) to Solana (Solflare)

## What is the expected/desired behavior
Redeem screen is opening.

**Comment by AigaD** [comment]
Will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1178 is solved

**Comment by AigaD** [comment]
This is still reproducible
Tested from: https://portalbridge.com/#
In order to continue transaction user has to resume the transaction, then the redeem screen is opened for transaction from [Sui ](https://suiexplorer.com/txblock/G2FyozbZ9Csk8aQo3Lkk43Vh7ruGtL47MyWDdkd9J81r?network=mainnet)(Fewcha Move) to Solana (Phantom)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/46dd0251-6f01-4f12-8b86-7c73ac13e827

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.01 SUI from Sui (Fewcha Move) to Solana (Phantom) is not starting, console shows `Error: Invalid Transaction digest at JsonRpcProvider.getTransactionBlock `
Attachment:

![Screenshot 2024-02-29 at 16 57 26](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f88c41ba-d46e-42e2-9707-e7068dc221ed)

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk6NhXyEIKYZJQz5i9MI4toLNQLCa5MRQGUAqgEkzYAL4gXQA%3D%3D%3D). 

```
Error: Invalid Transaction digest
    at JsonRpcProvider.getTransactionBlock (main-wban9g4X.js:454:34054)
    at SuiContext.getMessage (main-wban9g4X.js:481:214548)
    at WormholeContext.getMessage (main-wban9g4X.js:484:628877)
    at BridgeRoute.getMessage (main-wban9g4X.js:486:24702)
    at Operator.getMessage (main-wban9g4X.js:489:132669)
    at Object.er [as onClick] (main-wban9g4X.js:524:31492)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f1915064-f5dd-43ee-bb57-c92187b893a0)

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ with the same scenario, when sending SUI from Sui (Fewcha Move) to Solana (Phantom). TransactionID in the link is undefined.  

![image](https://github.com/user-attachments/assets/3b917e73-64b8-431f-b3b1-2c9c504a6775)

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2).

Error appears in Console after confirming the transfer:
```
Wormhole Connect: error completing transfer Error: No provider passed to Transaction#build, but transaction data was not sufficient to build offline.
    at Be (index-CkRfk35P.js:5:19069)
    at Tt.Hr (index-CkRfk35P.js:5:24464)
    at Tt.St (index-CkRfk35P.js:5:26982)
    at Tt.build (index-CkRfk35P.js:5:22452)
    at sui-inpage.ee54170c.js?id=421e9d4b-906e-4b0d-a4d0-fada11f52f02:3:3898
    at async si.signAndSendTransaction (sui-B8NXEFlF.js:1:61020)
    at async ai (sui-B8NXEFlF.js:1:62821)
    at async signAndSendTransaction (main-CLT_sUf6.js:273:57984)
    at async SDKv2Signer.signAndSend (main-CLT_sUf6.js:273:60766)
    at async ssw (main-CLT_sUf6.js:245:7760)
```

![image](https://github.com/user-attachments/assets/0bf74bcf-3e0b-4719-b0df-d4f26608705e)

**Comment by agodlevska** [comment]
Issue is no longer relevant after redesign. Sui Fewcha Move wallet not listed for Sui network. 
Closing the ticket.
