### ISSUE TITLE
[QA] [Testnet, Mainnet] Native gas section cannot be enabled

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1068]
## Describe the current behavior in detail
Builds - Tested NOK:
https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/ [Mainnet]

Checked on macOS 12.7 with Google Chrome Version 117.0.5938.132 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.000647 ETH from Ethereum (Metamask) to Solana (Phantom)
2. Try to enable "Native gas" section by clicking on the switch button 

![Screenshot 2023-10-04 at 17 17 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/da25331f-ad2a-4eb6-a526-e6810bbb9365)

## What is the expected/desired behavior
"Native gas" section can be enabled.

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
Native gas section is shown, but cannot be enabled if the sum is the minimum allowed for One transaction route.
In example transaction for 2.1 USDC from Arbitrum to Base
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a12e0fb-3b00-48a1-b0b9-7950d91d37ab

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] when sending 52.5 USDC from Polygon (Metamask through WalletConnect) to Ethereum (Metamask through WalletConnect). Native gas section cannot be enabled.

![Screenshot 2023-12-18 at 10 35 19](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9b715569-e878-4083-9626-6edbb575cc54)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 2.625 USDC (Arbitrum) from Arbitrum (Metamask) to Base (Metamask). Native gas section cannot be enabled.



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/85e013a8-db5d-43ee-813a-6414afa659de

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 1.229 MATIC from Polygon (Metamask) to Solana (Phantom). Native gas section cannot be enabled.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001019 ETH from Goerli (Metamask) to Fuji (Metamask). Native gas section cannot be enabled.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000647 ETH from Ethereum (MetaMask) to Solana (Phantom).

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.003 SOL from Solana (Phantom) to Sui (Sui wallet). 

Steps:
1. Select Solana as source chain and Sui as destination chain
2. Connect Phantom wallet in From section and Sui wallet in To section
3. Try to enable "Native gas" section


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f5297248-58e4-427a-a24f-628500ed2d95

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
If user wished to send 1.26 USDC from Polygon to Avalanche using automatic rout, the Native gas section cannot be enabled, and there is no information that the amount should be increased. If user changes the amount to 1.27 USDC then the Native gas section can be enabled

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae915676-be15-4508-a2b0-ac7e1192ad87

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Now, if the amount is not enough for the Circle CCTP automatic route, a message about this appears. There are no problems with the Native gas section. 

Attachments:
<img width="542" alt="Screenshot 2024-06-11 at 11 21 29" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/88a397a4-d511-453b-abbe-8fda1e249153">
<img width="559" alt="Screenshot 2024-06-11 at 11 22 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/742dae9f-6cfa-4f5b-a4e8-5ecdeb24c1d4">
