### ISSUE TITLE
[QA] User is able to input “@£$%^&*()!=” symbols in the Amount field on iPhone and on Desktop Safari

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#107]
#### Precondition:
Wallet is connected

#### Steps:
1. Select network, for example “Goerli”
2. Choose a token, for example “ETH”
3. Type symbols is the transaction field “@£$%^&*()!=”

#### Actual result:
User is able to type symbols “@£$%^&*()!=” in the Amount field.

#### Expected result:
User is not able to type symbols “@£$%^&*()!=” in the Amount field.

#### Issue is reproducible on:
* iPhone 11 (iOS 15.4.1), Safari
* iPhone 11 (iOS 15.4.1), Chrome Version 110.0.5481.83
* MacBook Pro, macOS Monterey 12.6.1, Safari Version 16.1 (17614.2.9.1.13, 17614)

#### Issue is not reproducible on:
* Samsung S20 (Android 12), Chrome Version: 110.0.5481.63
* MacBook Pro, macOS Monterey 12.6.1, Chrome Version: 109.0.5414.119 (Official Build) (x86_64)

#### Comments:
Linked issue - #90 : [QA] User is able to input +/- symbols in the Amount field

#### Attachments:
<img width="1416" alt="desktop" src="https://user-images.githubusercontent.com/10746654/220411554-20935f1c-6fab-4500-b44e-2c81e93689f1.png">

![mobile](https://user-images.githubusercontent.com/10746654/220411821-08b1a909-4863-4d57-a657-bad6658d4f74.png)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Closing this as user is no longer able to enter symbols other than "." in the amount field.
Issue regarding being able to enter multiple "." is still open - https://github.com/wormhole-foundation/wormhole-connect/issues/427
Tested from: https://wormhole-connect.netlify.app/
Environment: iPhone 14, iOS 16, Safari
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ae06e56-1dfd-42af-9fb0-5db37691d4ce
