### ISSUE TITLE
[QA]Missing explorer link when transaction is completed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1078]
Preconditions: Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Tested from:
https://wormhole-connect.netlify.app/ 

Steps:
1. Prepare to send 0.1 WFTM from BSC to Moonbase
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe 

Actual result: When transaction is completed, explorer link at Step 2 (for Moonbase) is not shown

Expected result: Explorer link is shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e8c01ec1-531b-4318-904d-3e04bad12ddf

**Comment by AigaD** [comment]
The same for transaction USDC from Goerli to BSC
<img width="1175" alt="Screenshot 2023-10-05 at 17 35 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/37bdb99b-c634-4807-a025-e44d898e4625">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 ETH from Goerli (Metamask) to BSC (Metamask). "Pay with 2 transactions" option was selected in Route section. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x0eb9ffd09014c9bbb6fa06300a27fff41a515b24130b5440b23da0fa7e53f2d5).

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 ETH from Goerli (Metamask) to Moonbase (Metamask). "Pay with 2 transactions" option was selected in Route section. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xcad299d40bc9a9de2a6d3353e23deb4256ec83277269e457411c37be7913b515).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Missing explorer link for transaction Solana -> Sei / Solana -> BSC when transaction is completed.
Attachment:
![Screenshot 2023-10-16 at 13 12 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/462cfef3-9df0-4671-9556-8d057abd2952)

![Screenshot 2023-10-16 at 13 57 31](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3e852375-6c68-48c8-b0c5-8c4acaba6f77)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when:
* sending 4.89 FTM from Fantom (Metamask) to Solana (Phantom) with automatic deposit. Link to Solana explorer is not displayed when transaction is completed. Link to Solana explorer is displayed after transaction is resumed. 

Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x8837fccaefd21e6603f8a555c3af8f5691a52cb34829c0da9b654ea08e801542)
Send to tx: [Solana explorer](https://explorer.solana.com/tx/5BC2ZbjnXQ5BECZn7mt86RzSnx7hcMZFuMXeVdJq4Zvdm1MCJvrLF4D8wMV6sWFeRzgjJJQSxmBVhsatR6LhdXT?cluster=devnet)

<img width="1047" alt="Screenshot 2023-10-23 at 12 08 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4187ab18-92ed-4def-a6fa-55b34ec14f3d">




* sending  0.001 ETH from Goerli (Metamask) to BSC (Metamask) with automatic deposit. Link to BSCScan is not displayed when transaction is completed. Link to BSC is not displayed even after transaction is resumed.

Send from tx: [Etherscan]( https://goerli.etherscan.io/tx/0xfed95ed29d5bb6e0ff5817fa5c92031c98cc5361053e57a0070324cf3b742c1e)
Send to tx: [BSCScan](https://testnet.bscscan.com/tx/0xad37f73a98403f89c52f05adc2d4899835e319942425e40b5e79906bab44dd2b
)

<img width="1118" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a09ca9e8-f419-4ad4-8973-df799acf0f30">

**Comment by AigaD** [comment]
Missing explorer link for Sei Network, when transaction Arbitrum Goerli -> Sei is completed.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1117" alt="Screenshot 2023-10-23 at 18 07 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/12d5aa5c-cf8a-4a95-a65c-3ac8e59df7a0">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Link to BscScan is not displayed when sending 4 SUI from Sui (Sui wallet) to BSC (Metamask). "One transaction" option was selected in "Route" section. 

Link to BSCScan is displayed after transaction is resumed. 

Send from tx: [Sui explorer](https://suiexplorer.com/txblock/GiqfhgKdsYyxiRw1F4EGPsFw5gWyRREpo2DytxvwvmAt)
Send to tx: [BscScan](https://bscscan.com/tx/0x156fb7f865c7c32dfcc45f912602a23807d3d5e55fda4de18d3431a70d61f9d2)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/05513258-6302-4adf-accc-fea7b2235910)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/df5df83982/usdc-bridge/ [Mainnet] when sending 1.2 USDC from Optimism (Metamask) to Arbitrum (Metamask). Link on destination chain is not displayed. "One transaction" option was selected in Route section. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b57a6fdc-a077-4404-b79a-828b31bef905)

**Comment by tsadovska** [comment]
Issue is reproducible on https://testnet.portalbridge.com/df5df83982/ [Testnet] when sending 0.0001 tBTC from Goerli (Metamask) to Moonbase (Metamask). Link on destination chain is not displayed. Asset is received.

* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xeb81f4f4f2e16dc73c394f20912bed6c511bc8ab73f9faf5fa3e991b62faab47)
* Send to tx: [Moonscan](https://moonbase.moonscan.io/tx/0x05123a9fb867782d601cf60e73af6bb7e1e821a49b98a4880ecf4ee9b0192683) (found through explorer)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction san link is not shown at sending To section when transaction Solana -> BSC is completed
Attachment:
![Screenshot 2023-12-01 at 09 43 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f1bd1537-2f77-4347-8ad6-e35353a7cb53)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Missing BSC explorer link when transaction was completed. Asset was received.
Metamask wallet connected for [Moonbase](https://moonbase.moonscan.io/tx/0xa8e5ae93e50c66d5bb2b0534338905c120ee4fb76a4f3b28b38df121b101d54a) Network
WalletConnect - Metamask was connected to BSC Network
Attachment:
![Screenshot 2023-12-14 at 14 55 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0d64eeeb-4b55-4617-b793-932f7638683a)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/#
Link to Arbitrum scan was missing when transaction USDC from [Polygo](https://polygonscan.com/tx/0x02fefcfa44f851647087f757a6f6e2a7000e8a161cc9fd86c2fe437e675a1ed2)n to Arbitrum was completed.
Attachement:
![Screenshot 2023-12-15 at 11 00 36](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/acd58673-e857-4554-a0b2-7ed92af1cc97)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 wstETH from Goerli (Metamask) to Mumbai (Metamask). Link to Polygonscan is missing. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xe18d4b38af1495d9a8b09b70db5ae8d87084df1237d06806979eaf14ad2a244c)

![Screenshot 2023-12-28 at 12 14 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2916ddee-e9ca-437a-8d52-e5f1382a3f70)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
Explorer link for BSC was not shown when transaction was completed.
Transaction WSOL from [Alfajores](https://explorer.celo.org/alfajores/tx/0x1726fa2679d1e62a7c691c2cd384ee1b73b91cc3c022155dc9a6d707a60c206a) to BSC
Attachment:

![Screenshot 2024-01-10 at 12 57 50](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6c125463-75f7-4cb9-a364-31916b9d32a1)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.1 AVAX from Fuji (Metamask) to Sei (Leap). 
* Send from tx: [AvaScan](https://testnet.avascan.info/blockchain/c/tx/0x8bb3bdbe547728c5ef451714fa5d27e9bc3d964b9c1906e20a106a18ee43deea)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x8bb3bdbe547728c5ef451714fa5d27e9bc3d964b9c1906e20a106a18ee43deea?network=TESTNET)

<img width="635" alt="Screenshot 2024-01-10 at 14 43 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/99ea2e74-e633-45e4-aebf-c702baf6decf">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet] when sending 0.0001 CELO from Evmos (Leap) to Solana (Phantom). Link to Solana explorer is not displayed in "Send to" section. Issue is also reproducible after transaction is resumed. Send from tx: [MintScan](https://www.mintscan.io/evmos/tx/5FD577E91516F4B884BE17AA88C82C5E9E7C62C138B9852FE343871EC6176ADB). Asset is received.

**Comment by AigaD** [comment]
Tested from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/
Reproduced for transaction 0.001 SOL from Solana (OKX Wallet Solana) to Sui (Fewcha Move wallet), link to Sui explorer was not shown when transaction was completed.

Attachment:
<img width="700" alt="Screenshot 2024-01-26 at 10 13 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5dc3a713-a836-42f9-acd1-7f8c19197192">

**Comment by AigaD** [comment]
Reproduced also from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Attachment:

<img width="979" alt="Screenshot 2024-01-26 at 15 40 13" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3600c317-9739-4476-b111-5db68e96adb5">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 2 WKLAY from Klaytn (Metamask) to Solana (Phantom). Link to Solana Explorer is not displayed after transaction is completed. Link to Solana Explorer does not appear after transaction is resumed. Asset is received. Send from tx: [Klaytn Scope](https://klaytnscope.com/tx/0xdecc1ffda3469f0367f1530c28390a34ce414e9f9688d6dfd2a9e96802b91379?tabId=inputData).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Issue reproduced for transaction Osmosis to Solana
Attachment:
![Screenshot 2024-02-06 at 10 54 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ed2b6be5-87f5-4067-a922-890bbc28a88b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/749d45da9e/ [Mainnet] when sending 0.0001 APT from Aptos (Pontem) to Optimism (Metamask). Asset is received. 
* Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x3498157c9cdf406bd0639557901f184ef96678d0244dcf6093f2a4e79adb9bf3?network=mainnet)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/22/0000000000000000000000000000000000000000000000000000000000000001/141773)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/33e2d0bd-93ab-4ffa-b2e9-e221d07eed5d)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Reproduced for transaction USDC (Base) from [Base](https://basescan.org/tx/0xad897ccf796cae7b1d480bca4979e25381036a4a9653678c4288245d54c53a41) to Solana. Missing Solana explorer link
Attachment:
<img width="1174" alt="Screenshot 2024-02-19 at 10 42 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1ca63013-e90c-4c28-9a96-70abda003cd9">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Missing explorer link when transaction 0.01 KLAY rom Klaytn to Sui is completed. Asset is received 
Attachment:
<img width="1343" alt="Screenshot 2024-02-20 at 10 06 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6c2371a-7a25-402f-bd04-b08ad53c8be3">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 2.5 CELO from Alfajores (MetaMask) to BSC (MetaMask) with automatic route. Link to BscScan is not displayed. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/49f4d9d4-e44c-4c3f-a1be-b7834e4b5cde)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Reproduced for transaction 0.001 WSOL from Ethereum to Solana, missing explorer link for Solana when transaction was completed.
Attachment:

![Screenshot 2024-03-08 at 14 16 04](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b7d7757a-ddcf-419d-a450-5df1106b278e)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Missing explorer link when transaction is completed for Aptos (Fewcha) to Solana (Phantom)

Attachment:

![Screenshot 2024-03-11 at 11 08 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7658081-f586-4fc1-8a65-db0c20ee8d95)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/#
Missing Solana (Solflare) explorer link when transaction is completed.
Attachment:

<img width="1103" alt="Screenshot 2024-03-15 at 10 15 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e4ab5961-df9f-44e9-ac55-bd9571eafe6b">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
Attachment:
<img width="1089" alt="Screenshot 2024-03-20 at 17 59 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d5ac17fe-0b5e-493f-bd7c-f35d83d5efed">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/ 
Attachment:

<img width="1116" alt="Screenshot 2024-03-25 at 09 23 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1f14818b-7d2c-48f8-8a6d-4442537d7db0">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/
For transaction 0.01 BONK from [Osmosis](https://www.mintscan.io/osmosis/tx/550AFC46819F5F8DB2C2A3E028E5FACCE7525DB35F43D30FCF58508CF15C172D) (Leap) to Solana (Solflare), missing Solana explorer link

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 4 WFTM from [Fantom](https://testnet.ftmscan.com/tx/0xe66af1e4e0c2a2e5d787a40fde0e962605d8214c32637b9c4334b00ce4f919ad) (MetaMask) to [BSC](https://testnet.bscscan.com/tx/0xc0cd1266233a5583c2bf1d316e36837184b75858308c70ad78e50898189bfe63) (MetaMask) with automatic route. Link to BscScan is not displayed. Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xe66af1e4e0c2a2e5d787a40fde0e962605d8214c32637b9c4334b00ce4f919ad?network=TESTNET).

![Screenshot 2024-04-08 at 11 07 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3c15e59f-7595-41b6-971b-535a1cad523d)

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Transaction 1.5 MATIC from [Polygon](https://polygonscan.com/tx/0x9bed1d4a23a70f91cff15ba614fc4823ac9e93388b5bc6558d47c8dd0dfb5987) to Celo completed, but link to Celo explorer was not shown.
Attachment:

<img width="1181" alt="Screenshot 2024-04-09 at 16 13 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f065456a-3e87-4d37-8b69-9286821b8c53">

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
For transaction 0.01 WSOL from Fantom to Solana (Phantom), missing explorer link when transaction is completed
Attachment:

<img width="746" alt="Screenshot 2024-04-12 at 10 30 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c772dddc-fb60-4d24-8cfa-f49aec69495d">

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/#

Attachment:
<img width="1068" alt="Screenshot 2024-04-15 at 20 02 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4f6951d9-0efa-4a2f-b9e2-ea5ff997d811">

**Comment by tsadovska** [comment]
Reproducible from https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development) when sending 0.001 Ws from Base Sepolia (MetaMask) to Solana (Phantom). 
* Send from tx: [Etherscan](https://base-sepolia.blockscout.com/tx/0x494f0047250a3e9ba97ef417df2658fb4e3630e76358af4ce2d633e0fe832864 )
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/22pZYpNVTSU1URTDqWKKVM9NNkpQBBsv8HSYAYSXKCXnqvyYST3i46sU1Pp3rxte4Amm5QP6zBLYj1cQEP9w26kG?cluster=devnet)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x494f0047250a3e9ba97ef417df2658fb4e3630e76358af4ce2d633e0fe832864?network=TESTNET)


![Screenshot 2024-04-17 at 16 20 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/57f254e2-6abc-4a9a-a471-f7c7fd658db7)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] (Portal Bridge: v0.2.13-Pfe79048439, Wormhole Connect: v0.3.8-beta.0-development) when sending 0.001 W from Arbitrum (MetaMask) to Solana (Phantom). 

* Send from tx: https://arbiscan.io/tx/0x89c1910b304b29920994d59fffcf2e4562d435bfe3ef598b13f126f96e47b307
* Link to Wormholescan: https://wormholescan.io/#/tx/0x89c1910b304b29920994d59fffcf2e4562d435bfe3ef598b13f126f96e47b307

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/73a0928c-332d-4b4e-8fe3-74db3c8c2e49)

**Comment by AigaD** [comment]
Reproduced from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGTTdIhYhFwjJuGfMVoKZDLgpsU6wWC1yYiy2AC%2BIR0A%3D%3D%3D#)
Mising Arbitrum explorer link, when transaction 1.3 USDC From [Base](https://basescan.org/tx/0x80f40c9822dd734bd9258cadc86a8179acab33afca4649b5c5e83c49efab6671) to Arbitrum (Automatic CCTP route) is completed
Attachment:
<img width="1066" alt="Screenshot 2024-05-15 at 16 11 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e46ec6a2-98a4-4c4e-b9e7-427e5d69fc08">

**Comment by agodlevska** [comment]
Reproduced on https://portalbridge.com/#

Transaction 0.001 W from [Solana](https://explorer.solana.com/tx/3Uk6ARkkzZvpfaw5NnhDJXKpYVbpALnr4ciBMbjsQ84nn2ZejEX5YzdBqwQSd3UP8b8eZwMWpgjo6FHJQ834QruL) (Phantom) to [Ethereum](https://etherscan.io/tx/0x9d6f58f5ed21b3da6b8565d17531b07f3d1e260468f241ece7384b2a97454672) (Metamask).

Attachment:
<img width="1440" alt="Screenshot 2024-05-24 at 09 36 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/35b16011-9880-40fd-ae8d-2c203d071382">

**Comment by agodlevska** [comment]
Reproduced on https://portalbridge.com/#

Transaction 1.5 USDC from [Optimism](https://optimistic.etherscan.io/tx/0x9effc7699400ee49360614a48f9ff7d2eca4d4a55825cb7b333ba852d73ece0d) (Metamask) to [Arbitrum](https://arbiscan.io/tx/0x12e4bd79758892b63b6b59e758dffc18f491907ab4dd241abf9a24c14733375e) (Metamask).

Attachment:
<img width="1440" alt="Screenshot 2024-05-31 at 13 07 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/38ed3942-8ff8-49c4-acb3-e3574e79c5c7">

**Comment by tsadovska** [comment]
1. Checked on https://wormhole-connect.netlify.app/ [Testnet]. 
Explorer links are shown for following transactions:

- Manual Bridge route

  - WFTM transfer from [BSC](https://testnet.bscscan.com/tx/0x52553f413f6cefa81560be72cd274e43eb366409614da5e0dd9dfe0b028fd681) to [Moonbase](https://moonbase.moonscan.io/tx/0x2167a060519b2b9b7b2774fad3e3f51e2644d259a7e78e2e115865cd0bc984ea) 
  - USDC transfer from [Sepolia](https://sepolia.etherscan.io/tx/0x0ff1edd7b064089c58f1c1f529d172bd9143b720b5f8bf2e3cf985f626656b93) to [BSC](https://testnet.bscscan.com/tx/0xcccd724bc9004d8a34ecd1cdfee81d2b845de0b042f37bfb5451f2029304831b) 
  - WFTM transfer from [Sepolia](https://sepolia.etherscan.io/tx/0x8f191e19982019fcec3c105068cf917f35fba0a8718f6b7f1d8060b4d30c88f4) to [Moonbase](https://moonbase.moonscan.io/tx/0x23a26b60b6e454eed22b5787d13983d0f1824031d0d31f19052646d5cb0bcc76)
  - SOL transfer from [Solana](https://explorer.solana.com/tx/y7eQEZszZxvU6QiMBFySiLhCr4QFdYy3ubttuDLNWuHKfou785XZG3G9wyUs1NdUqJxMb5NLJG1XjztZfHgD4SZ?cluster=devnet) to [BSC](https://testnet.bscscan.com/tx/0xfeab9e9cf399f31c8282d6397102297c4f059135d13e01b240fc26b01f7c04d9)
  - GLMR transfer from [Moonbase](https://moonbase.moonscan.io/tx/0x8718cce7fd8e8e4ead8f0c2cad389613532e5e5ef95ca57d4b9f46d927eabaec) to [BSC](https://testnet.bscscan.com/tx/0x8509303f2f8e6489c8ef54cb9dd72d32cd5c65d6071e4be1675f009e6748e5cc) 
  - WGLMR transfer from [Moonbase](https://moonbase.moonscan.io/tx/0x8336fcf10fed0d03d4fe750b34b1d9349fc12b9d658fbc2bc82ea87536d7aa8e) to [Solana](https://explorer.solana.com/tx/5dHb7n2DfvA7CnPK7WAidPX7d97B4WuJSkZc87fDnnK7FreeGyLCtAcKiTpeLxzkP9GzP7YHdLPNKcZcFViCZcHh?cluster=devnet)

- Automatic Bridge

  - FTM from [Fantom](https://testnet.ftmscan.com/tx/0x233aae06486d667b9b98103f4b616d22ca891a27378e3a9c749e8f2019ac2347) to [Solana](https://explorer.solana.com/tx/4SEREVs8SKR2Z55qXbuJxCRnELhmWanGS11WdnzHYp3Uha1Bd1U7huJP6kEMsWU5inWBY24ZhkyA5TNqxLUJiWiD?cluster=devnet)

2. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Explorer links are shown for following transactions:

- Circle CCTP Automatic

  - USDC transfer from [Optimism](https://optimistic.etherscan.io/tx/0x0b56bbfa1d0859d73661030d39600fe7780b509ab7e2f96be29bf959dd43e4de) to [Arbitrum](https://arbiscan.io/tx/0x609640f132a7758266ad7595196d59d8a6ebd46f572648fd97cf0bb3b467fb0f)

- Manual Bridge

  - SOL transfer from [Solana](https://explorer.solana.com/tx/5PTFcUtjCF2kP1H4mtwoj7tLdNLkhsfDbt9PHu7ZJckNC36NaWsPSW3uk2J2xAdtzPwKu86c9umP4fWHp7S73q9e) to [BSC](https://bscscan.com/tx/0x1e5dda7068dcff2263cc7b18797f2b100ff3e458cc57172ef70965fec66cac6e) 
  - CELO transfer from [Evmos](https://www.mintscan.io/evmos/tx/B6552501776791D566ADA271A2FE388FBB3AADD1732907022F31B7C93C4A7AE2) to [Solana](https://explorer.solana.com/tx/5Wjj6VTWQQ2i7F6Shh4KhwV1Hy4wM6L9Qj5B6eqDVUjXptAkVRM1NHAM16dNGvKhCJmNA5wSuLpuBmTum1YgzTji)
  - SOL transfer from [Solana](https://explorer.solana.com/tx/4EyHbXzwPt5LhLLUYeXiQbd4dmZjfeLKk6jz2C8VAp3UyniTkL4KzbUA4AS8s3aNmzCzWX55ktfJFVaDjtprkmkq) to [Sui](https://suiscan.xyz/tx/6csMuAZGrLMn7R29vm7BgPE7vWcGJt7DXc6CA5ReatrX) 
  - APT transfer from [Aptos](https://explorer.aptoslabs.com/txn/0xdb30bb12d473a32d2dd49cb4dbba09028cad7e77e687b630eb6b30d420b424a8?network=mainnet) to [Optimism](https://optimistic.etherscan.io/tx/0x41063163a8bc99d8057a2ac265b593780ba082016b4f40a11fe1fcdb0b8709ca) 
  - KLAY from [Klaytn](https://klaytnscope.com/tx/0xe36d8cb5903e065320555da868516500a3aae830de5a164ec871674aa9b2e238) to [Sui](https://suiscan.xyz/tx/6o1qJ2FmsuSuo8MWvn9HxN5gs1C9WmEe1kD9GZ2sgRt9) 

- Automatic Bridge

  - SOL transfer from [Solana](https://explorer.solana.com/tx/JF5Fmc7VbgpBpDVMQTbWDpQGYGJ8CLBf6Tr8HBGE1GDSigrGp7nY6MM5cGSd2dsnDaoHxXN3N5oGSQxapvmq5DX) to [BSC](https://bscscan.com/tx/0xb778d244988618ed6ca45924b0d977a217e73a998dbb20327e117e6db26ae7c8) with Automatic route 
  - Cosmos Gateway Manual
  - USDC transfer from [Osmosis](https://www.mintscan.io/osmosis/tx/FE11519226B87A25975EE40867ADD87FE6DE1027A58F0614BD08CF51F2A20F82) to [Solana](https://explorer.solana.com/tx/5RotUQbTSgFRSwRUT1bYQqpZD5tbqECbYcrdM9BDhr1bb5CLvYYYsHVxVKDkZJXxgu4Rgf8673L26yjLJFp7QjSZ)
  - USDC transfer from [Base](https://basescan.org/tx/0xa0ca7c4a6a847b6ca711fab6f3264ddc5ed51278f079c7feb28ebfb221ae4165) to [Solana](https://explorer.solana.com/tx/5LJzmVJDUYzfnS6PoNp5LF73xFNFe7SHNN13BXaWHigAP7bJHxwguXHhtaRxy7575xro41yf14qVgyBx14PaEWZZ)

3. Checked on https://portalbridge.com/ [Mainnet].
Explorer links are shown for following transactions:

- Manual  Bridge

  - WSOL from [Ethereum](https://etherscan.io/tx/0x3a109be343e386bd89d9842e83c836d94abe347a05a281fa6ef2cd7aad3db4e7) to Solana
  - WFTM from [Fantom](https://ftmscan.com/tx/0x27a4fca0b8af3ca49e4cf78e8fb21084895c355485f76e75af55ad62af793571) to [Solana](https://explorer.solana.com/tx/574xwR3kd53TaUwsyE8JwENaqSywvudNxQZy7MexmcKPqBGcY4jfL9o3arfsygvqhQVNa6GyikcfSHAEW2YJXAgN)

- CCTP Manual

  - USDC from [Polygon](https://polygonscan.com/tx/0x3136a8fc35e0400f016ed33d3e5538a9678cd1fc736a0ed5c8fabf2f003a086e) to [Solana](https://explorer.solana.com/tx/3eJkGSCEZzbx44DzVkEDPRh6cuh8C1KWxNfCjWRwkFzsVo4c6jBonzyAxsp6gXHxujMtApEWY5vTKxscbsbqb3jk)
  - CCTP Automatic

- Automatic Bridge

  - MATIC from [Polygon](https://polygonscan.com/tx/0x6b2243327458ad52ad9204814c211659b886c5dca6cf3c6f7be19085dba8d996) to [Celo](https://explorer.celo.org/mainnet/tx/0x02bbb96b510ca397ccc3e4f4cf46c2dc76fdb3976d70b24b2237c0c0e42d6190)
  - WSOL from [Fantom](https://ftmscan.com/tx/0x050fcc0112f07cb86a938c50b33ac1c070c88a658e8b2a2839953cd2d4a147cb) to [Solana](https://explorer.solana.com/tx/5CnXgXBnW7bJEf4CQ6mGRGxjP7k941wbaSnVAjzJJHKmcmh4RN4KYB4TVben1saN2urKV9zqHXdyVLgFPKNQEt4Q)

- Native Token Transfer Automatic

  - W transfer from [Solana](https://explorer.solana.com/tx/2TC24A5qGX4k9s7tXaaMPYi9yEZTrqZZcCt1SdLvrgfi6FkVr3EQ1KRazqBSbGwXZYqrhG44FhsjnjqF8fViz43i) to [Ethereum](https://etherscan.io/tx/0x3c2959bfe919eaa7ecc05156258f1a149415d12ba19a7e116dc41f5fef726034)

4. Remaining issues:

- [#1160](https://github.com/wormhole-foundation/wormhole-connect/issues/1160) [QA] [Testnet] Automatic deposit transactions from Sui are stuck on Step 2
- [#1152](https://github.com/wormhole-foundation/wormhole-connect/issues/1152) [QA] [Testnet] Transactions to Sei are stuck on Step 2
- [#2195](https://github.com/wormhole-foundation/wormhole-connect/issues/2195) [QA] Explorer link is not displayed when transaction is completed - Aptos Explorer
- [#2201](https://github.com/wormhole-foundation/wormhole-connect/issues/2201) [QA] Explorer link is not displayed when transaction is completed - BscScan
