### ISSUE TITLE
[QA] [Mumbai] Balances of wrapped assets are not loading 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1079]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 117.0.5938.149 (Official Build) (x86_64).

Steps:
1. Select Mumbai network as source chain
2. Connect Metamask wallet
3. Open Assets list

Only native asset balance is loaded.

Note: Issue is not reproducible with Goerli, BSC, Fuji, Fantom, Alfajores, Moonbase, Solana, Sui, Base, Osmosis, Arbitrum Goerli and Optimism Goerli networks.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6c9626a8-15e4-4099-9fad-09546af7d65e)

## What is the expected/desired behavior
Balances of wrapped assets are loaded.

**Comment by evan-gray** [comment]
Thanks for the write up! We and some other integrators have encountered significant issues with ankr's Polygon Mumbai (testnet) endpoints. This seems like another one. Once this next release is complete and the batch balance getter is added back in, I plan to drop these endpoints in favor of public ones. We should leave this issue open until then to remind us to re-check after that time.

**Comment by AigaD** [comment]
Issue still reproducible. Asset balance for Mumbai network are not loading.
Tested from: https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c596cc1-5284-486a-ab80-9794d38845de

**Comment by evan-gray** [comment]
confirmed the batch gets limited. 😿 
```
        "message": "max batch size limit exceeded (public 10, private 1000). "
```
will try switching default RPC providers.
