### ISSUE TITLE
[QA] [Mobile] Slider is not properly moving if the user presses directly on it

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#108]
Preconditions: Wallet is connected

Environment: Galaxy S22+, Android v12, Chrome 110.0.5481.65

Steps:
1. Prepare to send 2 ETH from “Goerli” network to “Mumbai”
2. Expand “Extra native gas” section
3. Click on the slider button and try to move it
4. Observe
5. Click on the slider itself and then move it to the intended position

Actual result: Slider does not move smoothly when user presses on the slider button, in order to move it user has to press on the slider itself.

Expected result: User can move the slider by pressing on the slider button.

Attachments:

https://user-images.githubusercontent.com/91047061/220551554-90e1dbfe-a89e-4678-b857-f7fa4759f0e2.mp4

**Comment by AigaD** [comment]
Issue is also reproducible from: https://wormhole-connect.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8d1d8046-fa62-4a98-8352-63f301c00c4b

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. User can move the slider by pressing on the slider button. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/917b6da8-3bea-4d39-8314-f8d7e26f3de3

Issue will be rechecked on mobile after #747 is resolved.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
For transaction 0.2 WFTM from Alfajores to Base Goerli, user can not move the slider if directly pressed on it.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b132d48d-6242-477a-b198-49fd91bf99e7

**Comment by AigaD** [comment]
Checked from: https://wormhole-connect.netlify.app/# with macOS Ventura 13.0.1, Chrome Version 119.0.6045.159. Emulated device: iPhone 12 Pro
Slider is not moving if pressing directly on it, it can be moved by tapping on the Native gas line and then without releasing moving it
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/719635ef-95af-4621-a0ef-b4aad29ae835

**Comment by AigaD** [comment]
Issue is still reproducible.
Tested from: https://wormhole-connect.netlify.app/
Environment: Samsung Galaxy S22+, Chrome
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ea9f389a-c8c3-48b0-850b-04e3baac73fc

**Comment by tsadovska** [comment]
Issue is still reproducible on iPhone 11 Pro. Checked on https://wormhole-connect.netlify.app/ [Testnet] when sending 1 AVAX from Fuji (MetaMask via WalletConnect) to Alfajores (MetaMask via WalletConnect). Slider is not properly moving when user taps directly on it and then moves it right/ left.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ after redesign.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. User can move the slider by pressing on the slider button. Checked from iPhone 11 Pro iOS 17.6.1.

https://github.com/user-attachments/assets/27e4950c-6b3f-42f1-8383-d015bd42a3f8

Closing the ticket.
