### ISSUE TITLE
[QA] User should not be able to change slider position after transaction was approved 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1110]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Version 117.0.5938.149 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 AVAX from Fuji (Metamask) to Fantom (Metamask)
2. Observe that "Automatic deposit, One transaction" option is selected in Route section
3. Click "Approve and proceed with transaction" button
4. Approve Metamask notification
5. Change slider position

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e6d85830-8b2f-421e-bad2-3b2298fa6104

## What is the expected/desired behavior
User should not be able to change slider position after transaction was approved.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] when sending 0.33 USDC from Base (Metamask) to Avalanche (Metamask). User can move the slider after the transaction was approved. 



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/19e9f43a-50e3-47b2-9413-3a94b6878b07

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the same scenario "Send 0.33 USDC from Base (Metamask) to Avalanche (Metamask)". User can move the slider after the transaction was approved.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending AVAX from Fuji (Metamask) to Fantom (Metamask).

**Comment by AigaD** [comment]
This is still reproducible.
Tested from: https://wormhole-connect.netlify.app/#
User is able to change Native gas slider after transaction is confirmed, the Native gas token is not transferred, but information regarding the Native Gas is included at target chain section when transaction is completed.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c4154bf9-db20-4359-88a7-483b7778b136


![Screenshot 2024-02-06 at 13 47 24](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6d2b91f2-2a4b-4d36-ac36-fbdf0032ab8b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet].

**Comment by tsadovska** [comment]
Issue is reproducible https://portalbridge.com/ [Mainnet] when sending 0.6 USDC from Base (MetaMask) to Avalanche (MetaMask).

**Comment by tsadovska** [comment]
Please see ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2395 to view behaviour after redesign.
