### ISSUE TITLE
[QA] [Testnet] Tokens are not shown for Osmosis network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1111]
## Describe the current behavior in detail
Builds:
https://wormhole-connect.netlify.app/ [Testnet] - Tested NOK 
https://wormhole-connect-mainnet.netlify.app/ [Mainnet] - Tested OK

Checked on macOS Monterey 12.7 with Google Chrome Version 117.0.5938.149 (Official Build) (x86_64)

Steps:
1. Select Osmosis network
2. Connect Leap wallet

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9b6b0e44-1aaa-4354-af62-8f7f602cb0ae

## What is the expected/desired behavior
Tokens are shown.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect.netlify.app/#
Tokens are not shown for Osmosis Network
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aab63370-758e-4b43-815e-cfe13c24a845

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/ [Testnet] and https://preview.portalbridge.com/df5df83982/ [Mainnet]
Balance for Osmosis Network is not loading
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4594a359-8cea-4731-80fb-55d7edc7b9d7

![Screenshot 2023-11-28 at 09 20 39](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2849b0ce-14d3-48ff-b775-db3bbd8e4dd8)

**Comment by AigaD** [comment]
Reproduced also from Firefox browser, Osmosis tokens are not loading
Tested from: https://wormhole-connect.netlify.app/#
Environment: Firefox Version 120.0.1

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when Osmosis network is selected and Keplr wallet is connected. 


![Screenshot 2024-01-02 at 13 13 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b969275-ca5f-43fa-b470-362a00d590d1)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Message "No balances detected" is shown for the user, when user has assets on Osmosis networks. Checked with Leap wallet.

**Comment by AigaD** [comment]
Tested from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# and https://wormhole-connect.netlify.app/#
Balance for Osmosis Network is not loading
Attachment:

<img width="927" alt="Screenshot 2024-01-26 at 17 22 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d33a3a3d-fe55-4e44-87e7-1e2c76dacd03">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Message "No balances detected" is shown for the user, when user has assets on Osmosis networks. Checked with Leap wallet.

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/
Tested with Leap and Keplr wallets.
Error: `Failed to get token balances`
Attachment: 
<img width="1440" alt="Screenshot 2024-05-28 at 10 29 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/c31f5873-460c-47ea-a25f-877511640830">
