### ISSUE TITLE
[QA] Cannot start second transaction in a row

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1113]
Preconditions:
Nightly wallet connected at sending From section
Metamask wallets connected at sending To section
User has just finished transaction from Aptos and clicked "Bridge more assets"

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. User is returned back to Bridge screen after transaction from Arbitrum has been finished
2. Select Network Arbitrum at sending From section
3. Select Network at sending to section (e.g. Goerli)
4. Select APT asset
5. Enter the amount
6. Click Approve and proceed with transaction
7. Observe
8. Refresh the page
9. Repeat steps 2-7

Actual result: User can not start second transaction in a row, transaction shows as failed. After page refresh and entering the same values in requested fields, user is able to start the transaction

Expected result: User can start second transaction in a row

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5927fa03-c90e-4632-bbd0-f8b40c5e01c7

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c9125a4e-06a3-4655-b56c-3c9740956a3b


Ticket is closed.
