### ISSUE TITLE
[QA] [Mainnet] Link to Snowtrace opens error page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1114]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Monterey 12.7 and Google Chrome Version 117.0.5938.149 (Official Build) (x86_64). 

Steps:
1. Send 0.0001 WMATIC from Aptos (Martian) to Avalanche (Metamask)
2. Click Claim button
3. Click Snowtrace link

Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x26139ef2262994fec7e5ebe84ea67e5063c09ca93c149f0ab65d228ce2ecf1b6), Martian wallet: 0xebbb42751860774b5251b57a44f82997418d4d054987f393fb092d55ea9ef2fc
Send to tx: [Snowtrace](https://snowtrace.io/tx/0x68902cc08d9cc0f39f20e1039ce13075311150e507f3b9059c72c61a4d831ffe), Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/db7028ee-a55f-4d21-a12f-ec6e22327846

## What is the expected/desired behavior
Transaction details page is opened.

**Comment by evan-gray** [comment]
This is strange... I don't see that transaction in the explorer, but I do see https://snowtrace.io/tx/0xe4da289dc5fb3743063e8405d05ffe59c549ea9b59705d66574c774254eaeeec for the same amount around the same time.

**Comment by AigaD** [comment]
Tested OK
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Link to Snowtrace opens transaction overview
[Snowtraca explorer](https://snowtrace.io/tx/0xc359646c9529ec3a28ee2e1c6542603c92360cedb1db79ac8fec0505a55a882f)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/047e857f-cbd3-43f9-8eeb-a0a044446063
