### ISSUE TITLE
[QA]Cannot connect Leap wallet to Mainnet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1119]
Preconditions:
Wallets are not connected
Leap wallet extension is enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect-mainnet.netlify.app/ - Tested NOK
https://wormhole-connect.netlify.app/ - Tested OK

Steps:
1. Click on Connect wallet
2. Search Leap
3. Click on Leap wallet

Actual result: User cannot connect to Leap wallet

Expected result: Leap wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f823b89-565e-48b7-ae3e-cd2cdbd08fb4

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Leap wallet is successfully connected. Checked with Google Chrome Version 118.0.5993.117 (Official Build) (x86_64) and Leap wallet 0.8.5. 


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/be84425b-6e62-415b-a537-b9e841745bab)

Ticket is closed.
