### ISSUE TITLE
[QA] "Invalid chain id" error when from when sending from Cosmoshub to Evmos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1121]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.70 (Official Build) (x86_64).

Steps:
1. Select Cosmoshub as source chain
2. Select Leap wallet in From section
3. Select Evmos as destination chain
4. Try to connect Falcon/ Keplr/ Leap wallet

Errors are displayed in Console:
```
Uncaught (in promise) Error: Invalid chain id
    at x.<anonymous> (injectLeap.js:42:15870)
    at Generator.next (<anonymous>)
    at Te (injectLeap.js:42:13637)
```
```
Uncaught (in promise) Error: There is no chain info for evmos_9000-4
    at r (injectedScript.bundle.js:2:51823)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/296b896b-de80-4112-a68f-36c7ee3cbd42)

## What is the expected/desired behavior
User can successfully connect wallet.

**Comment by AigaD** [comment]
Error: `Uncaught (in promise) Error: Query failed with (18): alloc::string::String not found: query wasm contract failed: invalid request`is shown in the console when trying to connect and send asset from Cosmoshub (Leap) to Evmos (Leap/Keplr)
Tested from: https://wormhole-connect.netlify.app/

Fields Route/Native gas/Preview or Approve transaction button are not shown when entering all required fields for transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/42781c7c-ba44-4784-b258-b9a46919aeb4

![Screenshot 2023-11-29 at 11 44 22](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/86963e13-5cc9-4ba6-9ef0-2bed32cf88c2)

**Comment by tsadovska** [comment]
Tested OK:
Original scenario is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet], user can successfully connect Keplr/ Leap wallet when Evmos network is selected. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d84c1d34-bf34-4cfe-ae32-22c0d7df9336

NOK:
* Neither Approve button nor Token registration warning are present when sending asset to Evmos/ Kujira, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1666. 
* Cannot connect Falcon for Cosmos wallet, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/866.

Ticket is closed.
