### ISSUE TITLE
[QA] Cannot connect OneKey wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1124]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS version 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64).

Steps:
1. Select Evmos network as source chain
2. Click "Connect wallet" button
3. Select OneKey option

Error is displayed in Console:
`Uncaught (in promise) {name: 'Error', message: 'No account found', stack: 'Error: No account found\n    at chrome-extension://…cj/9542.bundle.js?8ecaf45a6021ca255584:1:1373208)'}`

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/930ab4e2-0223-4bea-bb0e-08b7b0351b9a

## What is the expected/desired behavior
OneKey wallet is successfully connected

**Comment by M-Picco** [comment]
It seems that Onekey does not implement the [experimentalSuggestChain](https://github.com/OneKeyHQ/app-monorepo/blob/6a835bb35dfbdfa541f275439aab2f4b0b69d9e8/packages/kit-bg/src/providers/ProviderApiCosmos.ts#L233) method to add new chains, so I think it won't be possible to have Evmos for OneKey

**Comment by AigaD** [comment]
OneKey does not automatically create or connect to Evmos Network when selecting the wallet in Wormhole connect "Connect wallet", although Evmos chain has been added manually before. The wallet does not connect to Wormhole-connect.

Please advise if the ticket should be closed from testing observations and from the Martins' comment.

Tested from: https://wormhole-connect-mainnet.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/82cd1020-9e6e-484f-a14d-c4835f6b6f3d

**Comment by AigaD** [comment]
Closing the ticket, Evmos network not yet supported for OneKey wallet
Possible to connect to other Cosmos Networks
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2023-11-07 at 16 20 51](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9f22cc7c-eaa2-4a3e-bb3e-1eb1577cc6e4)
