### ISSUE TITLE
[QA] [Testnet] Transaction to Cosmoshub fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1125]
Preconditions:
Nightly wallet connected at sending from section
Leap wallet connected at sending to section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect.netlify.app/ 

Steps:
1. Prepare to send 0.1 APT from Aptos to Cosmoshub
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Cannot read properties of undefined (reading 'data')`

Expected result: Transaction moves forward and is completed

Attachment:

![Screenshot 2023-10-18 at 12 01 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/48852cb3-c006-4a4e-b6b7-64dd3e3b4aa9)

**Comment by tsadovska** [comment]
Transaction from Aptos (Nightly) to Cosmoshub (Leap) is started, but is stuck on Step 2 (ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1158).


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fa1d681c-cdef-406f-a340-76fd183c9a54

Ticket is closed.
