### ISSUE TITLE
[QA] OneKey wallet notification is opened when user connects Metamask wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1126]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64). OneKey extension version 4.14.0.

Preconditions:
OneKey and Metamask extensions are installed and are enabled
 
Steps:
1. Click "Connect wallet" button
2. Select Metamask option

Error is displayed in Console:
```
Uncaught (in promise) Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.7.0)
    at f.makeError (main.259db3b3.js:2:948879)
    at f.throwError (main.259db3b3.js:2:948999)
    at f.throwArgumentError (main.259db3b3.js:2:949054)
    at p (main.259db3b3.js:2:822824)
    at ZT.connect (main.259db3b3.js:2:17638106)
    at async M0.evm.metamask.connect (main.259db3b3.js:2:17631433)
    at async main.259db3b3.js:190:96577
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ca8bfb12-0fcd-41d2-9303-55bcd244cd39

## What is the expected/desired behavior
Metamask wallet notification is opened.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. "OneKey Wallet" option instead of "Metamask" option is shown on "Connect wallet" screen when Ethereum network is selected and user clicks on "Connect wallet" button. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2a1f3117-67b1-4664-94c1-c463b5671add)

**Comment by AigaD** [comment]
Closing as expected behaviour.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://portalbridge.com/
User can disable the feature in OneKey wallet. OneKey wallet can be switched to override multiple wallets, this feature can be switched off and Metamask wallet will be offered

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c7ad5fa-a0dd-4d7a-963a-754870ca0270
