### ISSUE TITLE
[QA] [Testnet] Cannot estimate gas for transaction to Cosmoshub

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1127]
Preconditions:
1. Metamask wallet connected at sending from section
2. Leap wallet connected at sending to section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 ETH (Arbitrum) from Arbitrum Goerli to Cosmoshub
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Error: cannot estimate gas; transaction may fail or may require manual gas limit`

Expected result: Transaction is moved to next step and transaction is completed

Comments: Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/546

Attachment:

![Screenshot 2023-10-18 at 14 27 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5381500a-d11d-4a54-a9a4-07508dae8e5c)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.00001 ETH (Arbitrum Goerli) from Arbitrum Goerli to Cosmoshub (Leap). 

Error is displayed in Console after clicking on "Approve and proceed with transaction" button:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x23908A62110e21C04F3A4e011d24F901F911744A","value":{"type":"BigNumber","hex":"0x09184e72a000"},"data":"0xbee9cdfc0000000000000000000000000000000000000000000000000000000000000c20c2e72b7bb32bfe2a3a4960e384e8c53d7a7c4a6c3b43b12f7f0e01532f3dea8d00000000000000000000000000000000000000000000000000000000b2700100000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000857b22676174657761795f7472616e73666572223a7b22636861696e223a343030302c226e6f6e6365223a313937392c22726563697069656e74223a225932397a6257397a4d58703163324671624467334d444e6d6547783664484a7765486c35637a517a616d64314d445a6c6344563365575a3362444232222c22666565223a2230227d7d000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at checkError$1 (main.js:178:125408)
    at Web3Provider$1.<anonymous> (main.js:178:136016)
    at Generator.throw (<anonymous>)
    at pn (main.js:178:124429)
```

**Comment by AigaD** [comment]
Closing. Transaction is moved forward to transaction screen, error in console is not shown.
Tested from: https://wormhole-connect.netlify.app/#
Linking to ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1158

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8a633b07-365c-4470-8fcb-884abd4f2a08
