### ISSUE TITLE
[QA] WSOL is not received on Evmos network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1133]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64).

Steps:
1. Send 0.1 SOL from Solana (Phantom) to Evmos (Keplr)
2. Wait until transaction completes
3. Click "Bridge more assets" button
4. Select Evmos network as source chain
5. Connect the same Keplr wallet
6. Check that WSOL is received

Actual result: WSOL is not received

Notes:
* Phantom wallet: 4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU
* Keplr wallet: evmos19905tt7sp23gzjperppke7s34ct3at9cqu78wq
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/4YsDfxCB6Kzas9u6NgV3BBvkddqhJYVKYpHYHBuEzgRYtmqEHUaQT6qdEbv4MQoHTkBaaJ7vXPJpApvzjbhPt2mP)
* Send to tx: [MintScan](https://www.mintscan.io/evmos/tx/3476B2F34DEE03641446E66F13466D367E663FD7E87CEF981276E157917C0C04)
* Issue is not reproducible when sending AVAX from Avalanche (Metamask) to Evmos (Keplr). WAVAX is received on Evmos. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/25e71698-4023-4694-b94e-8b2b19bda1a8

## What is the expected/desired behavior
Asset is received.

**Comment by tsadovska** [comment]
Issue will be rechecked on https://wormhole-connect.netlify.app/ [Testnet] after #1148 is resolved. 
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Scenario: "Send 0.0001 WSOL from Solana (Phantom) to Evmos (Keplr)".
* Send from tx: [Solana explorer](https://explorer.solana.com/tx/2xgdVEwPyfeypnawMTvT4AZgPxZKbwGY5xtcc2i2ZRsbMdZe6Z4ynw5MP9CQTmcF6XVxbSYLJW65aVPNrzjzv7Fq)
* Send to tx: [Mintscan](https://www.mintscan.io/evmos/tx/933054401BE839533262B440E1A41F50FB56E7EF42F2C8F573A0555D43FD0C67)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 SOL from Solana (Solflare) to Evmos (Leap). Transaction is shown as completed, but asset is not received in the wallet. 

* Send from tx: [Solana explorer](https://explorer.solana.com/tx/2M5L5cLDNaVXU89GKcVjHvqHXBF9dt1FtQjXjuDMqHwxVBv7fS2c4xbjXowGWktjQESRHtNJmPmcdGNGQV2MrnpC)
* Send to tx: [Mintscan](https://www.mintscan.io/evmos/tx/8CA8EF48FD69F18C460F672B0322E5330CC7756E2667A800EC0706FC4CD46FBA)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#
Was sending 0.001 WSOL and 0.02 WSOL from [Optimism](https://optimistic.etherscan.io/tx/0x9de6004ac5043d472187e6f57824cbb3e765e7e26274aefdd0a9afa1fdc26335) network to [Evmos](https://www.mintscan.io/evmos/tx/65F6C85575157AA0DE733745EB697D6DE9F32B0F297C54F26DA6BC30046B48D7) and Evmos network did not show any balance of WSOL asset

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe5563a6-cc49-4186-8f4a-2efd57a9ff3a

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/732 is resolved.

**Comment by AigaD** [comment]
Issue will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1689 is resolved

**Comment by tsadovska** [comment]
Inflows into Evmos are disabled (ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1681). 
Ticket is closed.
