### ISSUE TITLE
[QA] [Mainnet] Cannot connect "Keplr for Cosmos" wallet if network is not selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1134]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64).

Steps:
1. Click "Connect wallet" button
2. Select "Keplr for Cosmos" wallet

Error is displayed in Console:
```
Uncaught (in promise) Error: There is no chain info for pacific-1
    at r (injectedScript.bundle.js:2:51823)
```
Notes:
* Keplr wallet is successfully connected when Evmos network is selected first. 
* Keplr wallet option is not clickable on testnet, ticket #793.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5946967e-519e-41aa-be46-a5c51f6cbea4

## What is the expected/desired behavior
Keplr wallet is successfully connected.

**Comment by M-Picco** [comment]
@tsadovska Could you give this another try please?

**Comment by tsadovska** [comment]
Thank you! Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with Keplr and Leap wallets. 

Ticket is closed.
