### ISSUE TITLE
[QA] Wallet is not reset and balance is not loading when network is changed from Evmos to Osmosis

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1136]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64).

Steps:
1. Select Evmos network as source chain
2. Connect Keplr wallet
3. Change network to Osmosis
4. Open Assets list
5. Observe if balance is loading

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7f1905c9-06a5-429c-bdd0-8756e23dc616

## What is the expected/desired behavior
Balance is loading or wallet is reset.

**Comment by M-Picco** [comment]
@tsadovska Could you try replicating this issue on this [preview site](https://deploy-preview-1132--wormhole-connect-mainnet.netlify.app/)?

**Comment by tsadovska** [comment]
@M-Picco Thank you for the fix! Orinal scenario is no longer reproducible on [preview site](https://deploy-preview-1132--wormhole-connect-mainnet.netlify.app):
* evmos account is connected when Evmos network is selected
* osmo account is connected when network is changed to Osmosis
* balance is loaded when Evmos network is selected
* balance is loaded when Osmosis network is selected

Noticed that issue can be reproducible with another scenario:
1. Select Evmos network as source chain
2. Connect Keplr wallet
3. Open Keplr extension and Lock Wallet
4. Change network to Osmosis (actual result: Evmos network remains connected and Keplr wallet notification opens asking to enter password) 
5. Close Keplr notification
6. Open Networks list
7. Select Osmosis network again (actual result: Osmosis network is connected)
8. Observe wallet account (actual result: evmos account is connected)
9. Open Assets list (actual result: balance is not loading)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5079bca8-c373-44d8-8e4c-989e93c11103

**Comment by M-Picco** [comment]
@tsadovska Thanks for the thorough test! I think we can merge the fix (on #1132) and then change the issue to p2 since the new scenario doesn't sound like a regular occurrence. I'll let you know once it's merged so you can test on the main preview sites.

**Comment by M-Picco** [comment]
PR was merged. Changing it to p2
