### ISSUE TITLE
[QA] [Testnet] Broadcasting transaction failed when sending wrapped asset from Cosmoshub

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1137]
Preconditions:
Leap wallet connected at sending from and to section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 WBNB from Cosmoshub (Leap) to Osmosis (Leap)
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Error: Broadcasting transaction failed with code 32 (codespace: sdk). Log: account sequence mismatch, expected 14, got 13: incorrect account sequence`

Expected result: Transaction should move to the next step and be completed

Comments: Same behaviour also reproduced when sending wrapped asset from Cosmoshub (Leap) to BSC (Metamask)

Attachment:

![Screenshot 2023-10-20 at 10 50 44](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f22aa894-52fa-47c2-a9c9-9ee722b2a031)

![Screenshot 2023-10-20 at 10 54 28](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ff278682-cf30-4f95-91d6-021cb0a9b2fb)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/feaa1798-aa25-48b1-8ad1-e34ca02b65bc

**Comment by AigaD** [comment]
Will be re-checked again after https://github.com/wormhole-foundation/wormhole-connect/issues/1147 is resolved

**Comment by nik-suri** [comment]
This is often the result of an RPC issue.
Can you please check this issue again @AigaD ?

**Comment by AigaD** [comment]
Closing this.
User is able to start the transaction from Cosmoshub when sending a wrapped asset.
Tested from: https://wormhole-connect.netlify.app/
Relevant issue to this ticket is still open https://github.com/wormhole-foundation/wormhole-connect/issues/1147
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a5b5718f-6c73-400b-808b-e85c48f0ccd6
