### ISSUE TITLE
[QA] [Mainnet] Transaction stayed on first screen, but funds were already received

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1138]
Preconditions:
Sui wallet connected at sending From section
Leap wallet connected at sending to section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.1 SUI from Sui to Kujira
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction was not moving forward to next screen, showed as loading, but transaction showed as success at Sui wallet and the asset was received in Kujir network Leap wallet

Expected result: Transaction moves to next screen with three steps and shows as completed

Attachment:
Sui explorer - https://suiexplorer.com/txblock/6dbptquZkU67Gtp8QGEyGy1dcdJ7Yx3oENeVj7q4j5LX?deviceId=e0da162e-c591-4a16-bbe1-889b92358745&network=https%3A%2F%2Frpc.mainnet.sui.io%3A443
Kujir explorer - https://finder.kujira.network/kaiyo-1/tx/E9260476E25708087D0B0F3641B1BA2088F9BF7C9275FD4F20C0D7D47F7B0E51

![Screenshot 2023-10-20 at 11 52 52](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/031d8fe4-35d5-424c-bb81-6c9b8bb460af)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e19ab419-aa09-4b48-ab3b-25d6bd2c6c27

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1171--wormhole-connect-mainnet.netlify.app/
Tested NOK.
Transaction showed as completed in Kujira (Leap) wallet, funds were already received while transaction have not moved away from Bridge screen. 
Waited approximately 30min to see if transaction would move away from Bridge screen after funds were already received. 
[Kujira explorer](https://finder.kujira.network/kaiyo-1/tx/3B26496878EB717D965453B5525098520726F2A72B59B1B33E8C20573F8E9685)

Attachment:
Before 0.1 SUI were received:
![Screenshot 2023-10-27 at 08 43 30](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/82f63d3f-36fe-4c47-99f6-7d35cdf4c59f)

Funds already received, transaction has not moved further from Bridge screen:
![Screenshot 2023-10-27 at 08 45 28](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6d14ab21-8390-4ef3-89d4-f853216521a3)


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8c7e663e-a09c-4cae-b62c-287e954321fb

**Comment by tsadovska** [comment]
Recheked issue on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Transaction screen is displayed when sending asset from Sui/ Fantom to Kujira. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f23b7ada-ae1d-4867-9910-37a4b0d44fa4)




Remaining issue: [Mainnet] Transactions to Kujira are stuck (ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1501)

Ticket is closed.
