### ISSUE TITLE
[QA] [Mainnet] Redeem screen is opened only after "Send from" step is completed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1139]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 CELO from Kujira (Keplr) to Polygon (Metamask)
2. Click "Approve and proceed with transaction" button
3. Approve Keplr notification
4. Observe that loading takes some time
4. Observe that "Send from" step is completed when Redeem screen is opened.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bca25acd-5dc2-44d4-9247-c488a33222bb

Linked issue: #1138

## What is the expected/desired behavior
Redeem screen is opened immediately after Keplr notification is approved.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://deploy-preview-1171--wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 CELO from Kujira (Leap) to Polygon (Metamask) tested ok, transaction moved to next screen and Step 1 showed as loading
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c2595aa-9c34-48d6-842a-cdfd7156a990
