### ISSUE TITLE
[QA] [Testnet] Balance is not loading for Kujira

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1141]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Select Kujira network as source chain
2. Connect Keplr wallet 
3. Open Assets list

Note: Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dc310ccb-841b-411f-b7d6-979d38cf3e6b

## What is the expected/desired behavior
Balance is loaded.

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/ and https://preview.portalbridge.com/df5df83982/ [Mainnet]
Balance for Kujira network is not loading
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7b0b73ad-4b48-4cb0-a3c7-3c87c759b0fe

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Balance is not loading for Kujira. Checked with Keplr and Leap wallets.


![Screenshot 2024-01-09 at 11 00 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95d1fd20-b95a-4e4b-a230-2ba930e8d3d4)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Balance not loading for Kujira Network

**Comment by nik-suri** [comment]
This seems like an RPC issue.

Also, from the most recent screenshot, it looks like Wormhole Connect is still attempting to call `wormchain-testnet.jumpisolated.com` -- this endpoint was deprecated in mid-December.

The new testnet Gateway RPC endpoint is `gateway.testnet.xlabs.xyz`
