### ISSUE TITLE
[QA] [Testnet] Balance is not loading for Evmos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1143]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:

1. Select Evmos network as source chain
2. Connect Keplr wallet
3. Open Assets list

Note: Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/64839c77-368c-41c9-a49e-3a10fb033dd9

## What is the expected/desired behavior
Balance is loaded.

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/ and https://preview.portalbridge.com/df5df83982/
Balance is not loading from Evmos network
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0991ec15-c85f-4e3f-be15-65129156471e

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Balance is not loading for Evmos. Checked with Keplr and Leap wallets. 


![Screenshot 2024-01-09 at 10 36 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c22c7560-a24e-4a8b-af14-34ec5fafaf55)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Balance not loading for Evmos Network

**Comment by agodlevska** [comment]
Issue is still reproducible on Testnet - https://wormhole-connect.netlify.app/. Balance is not loading for Evmos with Keplr and Leap wallets.

<img width="1440" alt="Screenshot 2024-05-16 at 13 50 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/947e8bba-f3b1-40c7-aa95-b919ec5ecfc1">
