### ISSUE TITLE
[QA] [Testnet] Transactions to Kujira are stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1146]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Send 0.01 CELO from Alfajores (Metamask) to Kujira (Keplr)
2. Observe if transaction is completed

Transaction is not completed, stuck on Step 2.

Notes:
* Send from tx: [Celo explorer](https://explorer.celo.org/alfajores/tx/0xb955366049c9c2969ecea5faa72cc88d7aca0050f50fa7255eaa4b6cfbb959c1) (Scenario: Send 0.01 CELO from Alfajores (Metamask) to Kujira (Keplr))
* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x73741f687f874a4ccc8c7f457d17fb23e6c98e243d4b9fc18ede7467d521f482) (Scenario: Send 0.01 ETH from Goerli (Metamask) to Kujira (Keplr))

<img width="1418" alt="Screenshot 2023-10-23 at 10 42 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8d6b5d2e-7ccf-477f-9c62-a73fc1181104">

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1263--wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 SUI from Sui (Sui wallet) to Kujira (Leap). Transaction to Kujira is stuck on Step 2. Send from tx: [Sui explorer](https://suiexplorer.com/txblock/7Ra5QGTHk38etiqvFNyYxnYJzQRBbzHfM2JdKUsEebYu?network=testnet).

**Comment by AigaD** [comment]
Will be checked after https://github.com/wormhole-foundation/wormhole-connect/issues/868 is solved

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1666 is resolved.
