### ISSUE TITLE
[QA] [Testnet] Transactions to Osmosis are stuck on Step 2 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1147]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:

1. Send 0.01 ETH from Goerli (Metamask) to Osmosis (Keplr)
2. Observe if transaction is completed

Transaction is not completed, stuck on Step 2.

Notes:

* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xd7a7db04707a0371589295c193e2a5cd9e682780bb315043e358efd5f518080f ) (Send 0.01 ETH from Goerli (Metamask) to Osmosis (Keplr))
* Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x4c725df9e9a3f3ef2e65f3aa009e4c88c9865df2e9548f1136845f99d8aa717f) (Send 0.01 FTM from Fantom (Metamask) to Osmosis (Keplr))
* Send from tx: [BSCScan](https://testnet.bscscan.com/tx/0x7980d75c471e513f1733a50ef958d967c0c69edac57e6d2042ca968edd13b9a4) (Send 0.1 BNB from BSC (Metamask) to Osmosis (Keplr))

<img width="1372" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/63468e70-9344-439c-b60e-a03556148113">

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.001 APT from Solana (Solflare) to Osmosis (Keplr) not moving further than Step 2. 
Transaction shows as completed in Wormhole Explorer
[Solana explorer](https://explorer.solana.com/tx/3QkvhWNozXDc7nJKiWkVyc8zxprMeokHcrBm6c3cRu5crHLjiEBrx36sGnqPnR2MxSaJyadn3ybdLJeTw8U1EHAV?cluster=devnet)

Attachment:
<img width="1175" alt="Screenshot 2023-11-01 at 15 19 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1b657fbb-609d-48a6-b189-6df535f5f2db">
<img width="1163" alt="Screenshot 2023-11-01 at 15 19 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/828be397-b09a-4e2f-8597-b5895690c1b4">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect.netlify.app/#
Transaction from [Moonbase](https://moonbase.moonscan.io/tx/0x2f3e0ed6e3f82cfac105c96ba8fda53c7e1c540518a01cb2dc6b62efa5dec5b3) to Osmosis is not moving forward Step 2
Attachment:

![Screenshot 2023-11-16 at 14 40 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6ef50f7c-11a6-492a-9eb1-6fccdc14730c)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1263--wormhole-connect.netlify.app/ [Testnet] when sending 0.01 SUI from Sui (Sui wallet) to Osmosis (Leap). Transaction is stuck on Step 2. Send from tx: [Sui explorer](https://suiexplorer.com/txblock/DGqpv5fAaZeuz9tC91UYKsSsbWhHKAZ6KKhGj21fjtNs?network=testnet).

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WAVAX from Fuji (Metamask) to Osmosis (Keplr). Transaction is stuck on Step 2. Send from tx: [Avanscan](https://testnet.avascan.info/blockchain/c/tx/0xb95c00de5d1d568f89933225c7ed3a648c24cb548f723644e59c09155bcacd1f).

![Screenshot 2024-01-02 at 11 53 31](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/664d631f-e1ec-4960-b42f-da2d37fa5132)

**Comment by nik-suri** [comment]
These issues are most likely the result of IBC relayer downtime.
Can you please try again @tsadovska ?

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Still reproducible. Transaction to Osmosis not moving past Step 2
[Etherescan](https://goerli.etherscan.io/tx/0x35e2a604cbee85ee344e85d3914db4850cd2bd499258edb62669f4fc8657c2f0)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6445c5d-f6f9-4019-96c0-f05985baa403

![Screenshot 2024-02-02 at 09 28 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c6d84b44-d362-4ec4-80f4-bffebb9758c0)

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 WSOL from Solana (Phantom) to Osmosis (Leap). Transaction is stuck on Step 2. Send from tx: [Solana Explorer](https://explorer.solana.com/tx/BGNpgAQMCoWbMjM3BEKuLM8XGojomXbgGAc2JoL5d5scgFNftebUJ9wDpGfPF4dDfDX2mKQHsH4Y1phKGKRu1wh?cluster=devnet).
