### ISSUE TITLE
[QA] Send from section shows that wrapped tokens have been sent instead of Native

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#115]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps: 

1. Send 0.0121 FTM from Fantom to Goerli
2. Observe what type of token is shown at Send from section

Actual result: WFTM is shown instead of FTM at Send from section.

Expected result: FTM token is shown at Send from section if sending Native token.

Comments: Reproduced when also sending AVAX->WAVAX

Attachment:

https://user-images.githubusercontent.com/91047061/220839717-fcb4d5f3-71da-4da5-8642-14969bf14d23.mov

**Comment by AigaD** [comment]
This is still reproducible. Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1098" alt="Screenshot 2023-10-02 at 15 17 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/74676ef9-f069-42f3-8064-1e9643de7331">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 


![Screenshot 2024-06-10 at 15 05 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/29a212cb-009e-45f6-86b8-8dc4330cfef4)

**Comment by tsadovska** [comment]
Native asset is displayed on Redeem screen in "Send from" section. Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D#) (Connect v2).

Scenarios checked:
1) 0.0001 FTM from Fantom (MetaMask) to Celo (MetaMask) 
* Send from tx: [FTMScan](https://ftmscan.com/tx/0x98489607143858bfcf5a38d909273c382b0f132fc0ecf1e2ce67ca5576f311cf)
* Send to tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0x45bc13d117ceb3050c0554ab2781ede3cbea452ae74500608e82e3e8192abfec)

2) 0.0001 MATIC from Polygon (MetaMask) to Solana (Phantom)
* Send from tx: [Polygon](https://polygonscan.com/tx/0x0ae77c52f8e6b6a69aa67991897174fedbcc42ebff87bf9821a1039f7ae8db62)
* Send to tx: [Solana explorer](https://explorer.solana.com/tx/3suUwfrYayQpY84Pfy6C724i9MooVLFVAUELGhFjzih7SCu5eUVhoLKd6VgEd8pj5CjnFJbnZyxTg573raX18oTD)

Ticket is closed.
