### ISSUE TITLE
[QA] [Testnet] Transactions to Sei are stuck on Step 2 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1152]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Send 0.01 FTM from Fantom (Metamask) to Sei (Leap)
2. Observe if transaction is completed

Transaction is not completed, stuck on Step 2.

Error is displayed in Console:
`Access to fetch at 'https://rpc.atlantic-2.seinetwork.io/' from origin 'https://wormhole-connect.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Notes:
* Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0xe130e82c842ed86145f8943a95e0c53db5a7932c0278268a6e41bd906ee2a23c) (Scenario: Send 0.01 FTM from Fantom (Metamask) to Sei (Leap), timestamp: Oct-24-2023 09:55:03 AM +UTC)
* Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x52071be61cfb32dc6aa35cf04154d2d9f5d7eb683b2a0fbaead14edb8b39523b) (Scenario: Send 0.01 FTM from Fantom (Metamask) to Sei (Leap), timestamp: Oct-24-2023 10:46:40 AM +UTC)
 * Send from tx: [Sui explorer](https://suiexplorer.com/txblock/GKoAtT2GUmSNyye5byiMckeP9SoNNGCY7aPkCeEWcjPU?network=testnet ) (Scenario: Send 0.01 SUI from Sui (Sui wallet) to Sei (Leap))
* Issue is not reproducible when sending ETH from Goerli (Metamask) to Sei (Leap). Link to Sei explorer is not displayed in "Send to" section, but asset is received. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xefc3f9ca787912407911b7f33678d5173f76794a979ce4852cad7a6e5098a183)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/79bff067-0a36-425d-b53c-64c96183ea8f)

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by AigaD** [comment]
Linking to issue - https://github.com/wormhole-foundation/wormhole-connect/issues/661

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.00001 USDC from Moonbase [Metamask] to Sei (Leap).

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WGLMR from Moonbase (Metamask) to Sei (Keplr). Send from tx: [Moonbase](https://moonbase.moonscan.io/tx/0x74c3f5761d834b103b4e4ba06de3bcff923ef3bd38ad9d054b72b4af630e51bb). Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x74c3f5761d834b103b4e4ba06de3bcff923ef3bd38ad9d054b72b4af630e51bb?network=TESTNET).

**Comment by AigaD** [comment]
Reproduced for transaction [Sui](https://suiexplorer.com/txblock/3NPPHrgUUAn1rjBsaW3NbvqRsBqshftfSHVnzJ57q4W9?network=testnet) (Sui) to Sei (Fin) 
Tested from: https://wormhole-connect.netlify.app/#

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
For transaction KLAY from Klaytn (Metamask) to Sei (Leap) transaction is not moving past Step 2
Attachemnt:

![Screenshot 2024-02-07 at 14 02 36](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e80bab92-7bc9-4256-89ef-fb4fab5624a6)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ when sending FTM from Fantom (MetaMask) to Sei (Leap). Transaction to Sei is stuck on Step 2. Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x842dcd249263ce9e380a168ad1e6d2fc592437d357ad06e7fe2a24c319a60bfa).

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending WSOL from Fantom (MetaMask) to Sei. Transaction to Sei is stuck on Step 2. Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x7c8e4a7be25f408b2b30c5078436c82ef9eba681a6569482f10e977f1aa0bd83).

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/.
Sending BNB from [Fantom](https://testnet.ftmscan.com/tx/0x091d6c226f618119e1653e30b48cefe85b307b4d6a2224d79f61678921a3a0e2) (MetaMask) to Sei (Leap). Transaction to Sei is stuck on Step 2. 

Attachment:
<img width="1440" alt="Screenshot 2024-06-13 at 12 10 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/bbc7ef86-b4d3-4827-bbb5-de23c510ea3d">

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2394.
Closing the ticket.
