### ISSUE TITLE
[QA] OSMO, ATOM, EVMOS and KUJI assets should not be shown neither on From nor To sections

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1153]
## Describe the current behavior in detail
OSMO, ATOM, EVMOS and KUJI assets are shown in "All tokens" tab in To section and are not shown in From section.

Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Select Aptos network and connect Spika wallet in From section
2. Select Kujira network and connect Keplr wallet in To section
3. Open Assets list in From section and observe if OSMO, ATOM, EVMOS and KUJI assets are present in "All tokens" tab (actual result: assets are not displayed)
4. Open Assets list in To section and observe if OSMO, ATOM, EVMOS and KUJI assets are present in "All tokens" tab (actual result: assets are present)
5. Click on Swap button (actual result: Kujira network is in From section)
6. Open Assets list in From section and observe if OSMO, ATOM, EVMOS and KUJI assets are present in "All tokens" tab (actual result: assets are not displayed)
7. Open Assets list in To section and observe if OSMO, ATOM, EVMOS and KUJI assets are present in "All tokens" tab (actual result: assets are present)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bcde52af-c788-47d7-ade2-ec5658943dfd

## What is the expected/desired behavior
OSMO, ATOM, EVMOS and KUJI assets are shown in "All tokens" tab in From section.

**Comment by M-Picco** [comment]
Gateway does not currently support native cosmos chain tokens, so the expected behaviour is not to show them neither on the From nor To sections.
