### ISSUE TITLE
[QA][Testnet] Transaction to/from Cosmoshub not moving forward than Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1158]
Preconditions:
Solflare/Metamask wallet connected
Leap wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.01 SOL from Solana to Cosmoshub
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction not moving forward than Step 2

Expected result: Transaction is completed

Attachment:
Solana Explorer (transaction was started on 10/24) - https://explorer.solana.com/tx/myQDJQGFcupctmwvL672tsbbMYh6BKkWjCSvK6xGhcSMD341jm3Sw72GCbSewkyWbHUSHjWhSHnmqDtP8AHoyjP?cluster=devnet

<img width="1242" alt="Screenshot 2023-10-25 at 12 01 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/adee0440-7b47-4830-99ee-bda4f133b15f">

Mumbai explorer - https://mumbai.polygonscan.com/tx/0x053d43de3e9b1a1ba0ff18aaf3c8fb57829ad69689cfb961bd7a9ea0b3b6eb80

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1263--wormhole-connect.netlify.app/ [Testnet] when sending 0.001 SUI from Sui (Sui wallet) to Cosmoshub (Leap). Transaction is stuck on Step 2. Send from tx: [Sui explorer](https://suiexplorer.com/txblock/FgdQ4RbeBCYcHcpr8py2ttnbgyyKMukvDMnZ3Asv7JiZ?network=testnet).

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 WBNB from BSC (Metamask) to Cosmoshub (Leap). Transaction is stuck on Step 2. Send from tx: [BSCScan](https://testnet.bscscan.com/tx/0x311d3561b88b296ed74f9000cc95b2ec5b812d09089d4a1e2af3c36d9640227c).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction not moving forward than Step2 for transaction USDC from [Alfajores](https://explorer.celo.org/alfajores/tx/0xbfbbecddcd36a09a4f572539e3202f866e4b784055bed05e8f39717f28d878d3) to Cosmoshub
Attachment:

![Screenshot 2024-01-02 at 12 57 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2e9c6426-bb25-4a25-8a16-916e46f0b4f8)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction from [Cosmoshub](https://testnet.mintscan.io/cosmoshub-testnet/tx/EE3E4181DD3420B198B71A6C4C6DF0E3EC43396A7481C8AEB2DA98FE7E3B6DE6) to BSC not moving past Step 1, Waiting for Wormhole consensus
Attachment:
![Screenshot 2024-01-18 at 14 51 28](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4bde2405-96ab-4e07-80d0-f733a23f7490)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Transaction from [Aptos](https://explorer.aptoslabs.com/txn/0x01769972321849031816ccfed22da8ac4c0e732ec654f43442739aeb66cc5b8b?network=testnet) to Cosmoshub not moving past Step 2
Attachment:

<img width="994" alt="Screenshot 2024-01-26 at 17 43 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2cb41379-93d0-4806-b301-16242602ac19">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction from [BSC](https://testnet.bscscan.com/tx/0xd051947b593859af42f534bec0737ecbc0d0024cebb91cc98420c9ce291c73f1) to Comsoshub not moving past Step 2
Attachment:

![Screenshot 2024-03-01 at 12 58 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1f6fe18c-8771-464e-ad2c-b1c85630e0d8)

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect.netlify.app/.
Issue is still reproducible. Transaction from [BSC](https://testnet.bscscan.com/tx/0x80e53819afd29405be53252626bd971b2bea529d54d4fda386ac1cdefb43c2c4) to Comsoshub not moving past Step 2. 

Attachment:
<img width="1440" alt="Screenshot 2024-06-13 at 12 03 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/13782907-4927-47f8-bf26-e8fed1d87601">
