### ISSUE TITLE
[QA] [Testnet] Automatic deposit transactions from Sui are stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1160]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.96 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.1 SUI from Sui (Sui wallet) to Mumbai (Metamask)
2. Select One transaction option in Route section
3. Click "Approve and proceed with transaction" button
4. Observe if transaction is completed

Transaction is not completed, stuck on Step 2.

Notes:
1) Issue is not reproducible when "Two transactions" option is selected in Route section
2) Issue is reproducible with following scenarios:
* Send SUI from Sui to Mumbai with automatic deposit, send from tx: [Sui](https://suiexplorer.com/txblock/FBVBex5dSzv8bqca27vVGcyicvR4K4dNXDyHayRR7n4P?network=testnet)
* Send SUI from Sui to Goerli with automatic deposit, send from tx: [Sui](https://suiexplorer.com/txblock/9Lz1AtngbjSJT38P2KPu5o7r6mnscmpDLhRLMg6CHsZi?network=testnet)
* Send SUI from Sui to BSC with automatic deposit, send from tx: [Sui](https://suiexplorer.com/txblock/4KD4mb2fsy6adZuaMhZDPgntHXTo1EYo3vvfiJpM7uUQ?network=testnet)
* Send SUI from Sui to Fuji with automatic deposit, send from tx: [Sui](https://suiexplorer.com/txblock/2xDMNsySntuP1VeYrNELy5bTR6PcJFPDjhdps2ZyewV1?network=testnet)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/31427e65-279b-406b-ac15-3e7cd51941c0)

## What is the expected/desired behavior
Transaction is completed.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Transaction from Sui to Sei is not moving past Step 2, but Wormhole Explorer shows the transaction as completed.
[Sui Explorer ](https://suiexplorer.com/txblock/3HWd4Kjov3GeqoTVhUEcAcJRNgfPQ3VvpZMXKzrtC8bz?network=testnet)


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a4383aa-1d4b-4164-be3e-120ec01184d8

**Comment by aadam-10** [comment]
might be the same as https://github.com/wormhole-foundation/wormhole-connect/issues/1138

**Comment by tsadovska** [comment]
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Scenarios - Tested OK:
* Send 3 SUI from Sui to Polygon with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/BbP8VRMvBpmKE1ytaTk9UJe1Zk78TWmN63f1VNjw78d9), [Polygonscan](https://polygonscan.com/tx/0xc58ab6f264d393e7a78a262de2fad7185d6146ae491e0b38a9c902e8b90c67de))
* Send 4 SUI from Sui to BSC with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/GiqfhgKdsYyxiRw1F4EGPsFw5gWyRREpo2DytxvwvmAt), [BSCScan](https://bscscan.com/tx/0x156fb7f865c7c32dfcc45f912602a23807d3d5e55fda4de18d3431a70d61f9d2))
* Send 3 SUI from Sui to Avalanche with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/BoUSQciEWppZsKtdrPyPyv28neB94xyhfSkymrqPm7qN), [Snowtrace](https://snowtrace.io/tx/0x0f237b7536c75d6e5346eb460340afea4d5600d714bcc9f77cbc4a424ae15266))
* Send 2.9 SUI from Sui to Moonbeam with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/EaVVbTRJoCjHtRKLHXV13m1YHw6yG3z5Cnb2qWGrRhra), [Moonscan](https://moonscan.io/tx/0x78222877aae793eb3177a5f9dadb248ff7c6f2f843407a8dbc180d7f738faf51))

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/#
Transaction [SUI](https://suiexplorer.com/txblock/ERkXDanotTvYZ6iPrBdYQYaVzAyBX8cqVYFBXgi4N7y1?network=testnet) -> Mumbai with automatic deposit is not moving past Step 2
Attachment:
![Screenshot 2023-12-01 at 13 41 54](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/30917ab2-0ac0-491f-83b5-af21d6adb059)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 SUI from Sui (Sui wallet) to Sei (Leap). Send from tx: [Sui explorer](https://suiexplorer.com/txblock/GZaYiyzjQyLw1qn2nAfSsS7E9rCu8ECKQ9rCNQ8Rxyoc?network=testnet).

**Comment by AigaD** [comment]
Checked from: https://wormhole-connect.netlify.app/#
Transaction 0.1 SUI from [Sui](https://suiexplorer.com/txblock/7UK8NqbHgtPkPTVoKa7Wy6Z9UKKupf8fY2HAVo83uTaW?network=testnet) to Moonbase is not moving past Step 2

Attachment:

![Screenshot 2024-01-19 at 13 32 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2de84b5c-d48a-4261-b23a-80484d8723b6)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Issue still reproducible. Transaction from Moonbase to Sui not moving past Step 2, error shows in console `Error: Wormhole circle relayer contract for domain sui not found`
Attachment:

![Screenshot 2024-02-13 at 13 00 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/08232f6e-6622-4899-b89a-b4468a01fb4d)

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.3 SUI from Sui (Sui Wallet) to BSC (MetaMask) with Automatic route. 

- Send from tx: [Sui Explorer](https://suiscan.xyz/testnet/tx/EKbTgbATXYSdYxQVBrWtRfkLArYtgSghZFT6M363DcEr)
- Link to [Wormholescan](https://wormholescan.io/#/tx/21/40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9/674?network=TESTNET) 

```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":47,\"error\":{\"code\":-32005,\"message\":\"limit exceeded\"}}", error={"code":-32005}, requestBody="{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x2769fca\",\"toBlock\":\"latest\",\"address\":\"0x9563a59c15842a6f322b10f69d1dd88b41f2e97b\",\"topics\":[\"0xcaf280c8cfeba144da67230d9b009c8f868a75bac9a528fa0474be1ba317c169\",\"0x0000000000000000000000000000000000000000000000000000000000000015\",\"0x40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9\",\"0x00000000000000000000000000000000000000000000000000000000000002a2\"]}],\"id\":47,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://data-seed-prebsc-1-s3.binance.org:8545", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (main-B4sWFOrU.js:339:46683)
    at Logger.throwError (main-B4sWFOrU.js:339:46816)
    at main-B4sWFOrU.js:342:100881
    at Generator.next (<anonymous>)
    at Hn (main-B4sWFOrU.js:342:96208)
```

![Screenshot 2024-06-18 at 14 37 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bf048fa1-1dad-4720-b206-44b3cb6b2f0a)

**Comment by tsadovska** [comment]
Issue will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/2280 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet], transaction completed successfully ([Sui explorer](https://suivision.xyz/txblock/8HXn6r8Ru7S9FofpmCWDUwVobB4H8ubCGrrV4QASZnds), [BscScan](https://bscscan.com/tx/0xc51606953cfc6a195691bbe4a8a1db6fd01b47797cefa1ff457c5eefcd0f0bda))
SUI token balance is not loading on https://wormhole-connect.netlify.app/ [Testnet], ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2402.

Ticket is closed.
