### ISSUE TITLE
[QA] "Native gas on destination" field is not shown in Preview section when amount is too small

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1166]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.117 (Official Build) (x86_64).

Steps:
1. Prepare to send 2.11 USDC (Ethereum) from Ethereum (Metamask) to Base (Metamask)
2. Change slider position in "Native gas" section
3. Observe if "Native gas on destination" field is shown in Preview section

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9f1bfdc3-9c77-4f0d-93b1-bbf7ee6adc82

## What is the expected/desired behavior
"Native gas on destination" field should be shown in Preview section.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 2.632 USDC (Ethereum) from Ethereum (Metamask) to Base (Metamask). "Native gas on destination" field is not shown in Preview section when user changes slider position in "Native gas" section. 



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/834078a2-d40e-458a-80a6-53819274aa84

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/8228d00809/#
For transaction 6 USDC from Polygon to Arbitrum Native gas on destination information is not shown in Preview section

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/34e24249-e167-42cc-b6d5-4b456c4fd71e

**Comment by AigaD** [comment]
Reproduced from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKAwgFEAMgHkzYAL4g3QA)
Native gas on destination section is not shown in Preview section, for transaction1.1 USDC from Base to Arbitrum
Attachment:

<img width="733" alt="Screenshot 2024-04-30 at 11 08 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a800403a-52e2-40f5-b70f-6902a9c2d4c5">

**Comment by tsadovska** [comment]
Rechecked the scenarios mentioned in the ticket on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 

"Additional gas" field is shown during following transfers:
* USDC transfer from Ethereum to Base
* USDC transfer from Polygon to Arbitrum
* USDC transfer from Base to Arbitrum

Closing the ticket.
