### ISSUE TITLE
[QA] Token icon image shows as broken when adding token to wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1167]
Preconditions: Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#

Steps:
1. Prepare to send 0.2 USDC asset from Arbitrum to Base
2. Click Approve and proceed with transaction
3. When option is given click Claim
4. Click "Ass USDC to you wallet"
5. Observe the pop-up window

Actual result: USDC icon image shows as broken

Expected result: USDC icon is shown when adding token to wallet

Attachment:

![Screenshot 2023-10-26 at 09 23 49](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d581104-22b9-47c6-93db-028c9694cad0)

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2023-11-06 at 11 24 03](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/67d00d38-2fe7-41ea-9d3e-862e0f4c1115)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/usdc-bridge/#
USDC icon when adding token to network shows broken.
Attachment:
![Screenshot 2023-11-24 at 13 35 50](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/98f1fca6-38de-47ca-b45b-7f78f72f51da)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7102d8ccad/#
For transaction USDC from Arbitrum to Base
Attachment:
![Screenshot 2023-12-19 at 15 35 32](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/86238570-d5b5-4b99-aa8e-18fb15f6e02e)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/#
For transaction USDC from Arbitrum to Base, USDC icon when adding token shows broken
Attachment:
![Screenshot 2023-12-22 at 14 15 36](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/746c6477-c43f-471f-8d24-15e887d1e974)

**Comment by AigaD** [comment]
Same reproduced for tBTC icon when adding token to wallet, for transaction tBTC from Aptos to Base
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b8c41305-e41a-464f-bf33-67e4eaa66e24

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
WSOL icon for transaction Solana to Optimism when adding token to wallet shows as broken image.
Attachment:

<img width="1270" alt="Screenshot 2024-01-05 at 18 14 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8710a47d-c56c-4fd2-a8db-c9c8c9224c52">

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
When adding WETH token to Base network
Attachment:
![Screenshot 2024-01-15 at 12 41 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf0fc698-0b09-4d54-a168-8b0863b2973f)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2024-01-16 at 12 41 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7814675a-db9f-41fd-b746-5d1c40c0a1e4)

**Comment by tsadovska** [comment]
Checked following scenarios on https://portalbridge.com/:
* USDC transfer with Circle CCTP Manual route from [Arbitrum](https://arbiscan.io/tx/0x9757a883f121e87999971b89cf8f7e17475674794bec4ca62f9b6070562082b0) (MetaMask) to [Base](https://basescan.org/tx/0x2e2a11bb5592c9505afdad65f2c6a42c0902ed0d45bfd571a2c8e96269fc0831) (MetaMask)
* USDC transfer with Manual route from [Moonbeam](https://moonscan.io/tx/0xc9b4bb145cf21a39dd539fba3d23f633f22346e7ea430e5122c874a3fa3aadae) (MetaMask) to [Base](https://basescan.org/tx/0x2194798e3824cfd1da34c9d0de05b435fb572893c0a26e67c0123bdf8aedb0a8) (MetaMask)
* WETH transfer with ETH Bridge route from [BSC](https://bscscan.com/tx/0xd5c2f941d11bca227c173b1acbae3ece8bcd6dac531f6c57fb588f5c60861133) (MetaMask) to [Base](https://basescan.org/tx/0x9533374dccba9c3908c2a7f013a13788daf1ff59ac384b6aba6946868cd44519) (MetaMask)
* WETH transfer with ETH Bridge route from [Avalanche](https://avascan.info/blockchain/c/tx/0x006435bf75bf8ba6c8d96bcff7bd9555294cd7ccc1df834613030755ae939972) (MetaMask) to [Base](https://basescan.org/tx/0x23d210d795d68c490798af2dfdd5873d4b637af055471bb8ef1cfd9d09733be6) (MetaMask)

Token icon images are displayed in MetaMask notifications.
Closing the ticket.
