### ISSUE TITLE
[QA][USDC bridge]Automatic deposit transactions are stuck on Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1168]
Preconditions: Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#

Steps:
1. Prepare to send 2.2 USDC from Arbitrum/ Avalanache/ Optimism to Base
2. Select One transaction in Route
3. Add some Native gas
4. Click Approve and proceed with transaction
5. Observe

 
Actual result: Automatic transactions are not moving forward than Step 2, although when checking transaction on Wormhole explorer transaction shows as Completed when transaction is at Step 2

Expected result: Transaction completes

Attachment:
Transaction Avalanche to Base - https://snowtrace.io/tx/0xd7ffffe160f0c4f90473b00c81e82a4c2d86f8a240fd1012ca15685b9f5c91e9
Transaction Arbitrum to Base - https://arbiscan.io/tx/0x8d7cbb0f7c67af184fc9f29ff7d733e1ff3bde5d92b0c7c032f5251d0b20c458
Transaction Optimism to Base - https://optimistic.etherscan.io/tx/0x3b9aa3c4a5194d20deab6b2ef7af2aea7785b929945307dcb2f59d2a4f639f85

![Screenshot 2023-10-26 at 11 06 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9e564c59-d2ef-456f-a22f-46964818a718)
![Screenshot 2023-10-26 at 11 06 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b9558033-8f33-4379-99f8-33ad888813d9)

![Screenshot 2023-10-26 at 11 08 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e334a066-a27e-4466-80d1-4f87434dc53e)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] when sending assets from Base. Transactions are stuck on Step 2. 

Scenarios - Tested NOK:
* Send 0.33 USDC from Base (Metamask) to Avalanche (Metamask). Send from tx: [Basescan](https://basescan.org/tx/0xf6b2b357d73f426d2afbc00fc8dbda4f814c40b2e951ae498df10bbe73131d57)
* Send 1.8 USDC from Base (Metamask) to Arbitrum (Metamask). Send from tx: [Basescan](https://basescan.org/tx/0xa4abbc67fdc1c345c93e4d4c2da7051a32df97d1fb05069963990a3fb031cc71)
* Send 2.2 USDC from Base (Metamask) to Optimism (Metamask). Send from tx: [Basescan](https://basescan.org/tx/0xbe4f1daa47ca20f7f62ea0074afd7c16473ebab841f58996511011f5654f2e40)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
Tested OK for transactions:
2.2 USDC Arbitrum -> Base with One transaction Route (https://arbiscan.io/tx/0xf824a05d8c81af193981236d6fd515c305c22e043d67855e4edb9e9821d40703)
2.2 USDC Optimism -> Base with One transaction Route (https://optimistic.etherscan.io/tx/0xdaa890f4259d77dfbdd79d380fa6e40a7a2aa2d14e5120721a6da5de82449dec)
5 USDC Ethereum -> Base with One transaction Route (https://etherscan.io/tx/0x70e353cf25c6fb7cf91ad13750764885b629eea1299398ec76ec3fa8c8b5ddba)

Tested NOK:
Step 2 shows as loading, but Wormhole Explorer shows that the transaction is already completed

2.2 USDC Base -> Avalanche with One transaction Route ( https://basescan.org/tx/0x7156fda46e69d5cae8688e352dc02a0c07fa69ed726f8411529aee189b7634a5 )

1.1 USDC Base -> Arbitrum with One transaction Route ( https://basescan.org/tx/0x1e95808fc14c1487913037a313ad91059a40508823b99d9121dd3dabc1d317d0 )

2.2 USDC Base -> Avalanche with One transaction Route ( https://basescan.org/tx/0x142955ae4abc02765d68fe96e1b6e0ea05384b17c44234c541eac1eacd2f6f1d )


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/76842aa3-2113-42b2-b080-cee1d9ad5ff9

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
Transaction from Base -> Avalanche tested OK [Basescan](https://basescan.org/tx/0xb1087ad6774a06693ed1b38f2b3d0f5411da4b763283674f8d1ac66b87b1c390)

Transaction from Base -> Arbitrum tested OK [Basescan](https://basescan.org/tx/0x0bd3707479c6629bee1281c46690e30322223757415a1cd8aba407c39d0a9ca8)

Transaction from Base -> Optimism tested OK [Basescan](https://basescan.org/tx/0xe3b46c163bfa5e98896ec65a7e4e063ae29a1815f0d44c6a02c3b85d118d43d9)

![Screenshot 2023-10-26 at 22 59 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e25ddb9c-392f-4dc0-9dfe-a64e9db01116)
