### ISSUE TITLE
[QA] [Wormhole scan] Transaction details are not shown

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1169]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] with macOS 12.7 and Google Chrome Version 118.0.5993.117 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.33 USDC from Base (Metamask) to Avalanche (Metamask)
2. Select "One transaction" option in Route section
3. Click "Approve and proceed with transaction" button
4. Click "View on Wormhole Explorer" link on Redeem screen
5. Observe
6. Wait 10-15 minutes

Send from tx: [Basescan](https://basescan.org/tx/0xf6b2b357d73f426d2afbc00fc8dbda4f814c40b2e951ae498df10bbe73131d57)
Wormhole explorer: [Wormholescan](https://wormholescan.io/#/tx/0xf6b2b357d73f426d2afbc00fc8dbda4f814c40b2e951ae498df10bbe73131d57)

Linked issue: #894 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e58dd3b1-8a0a-4e34-ad15-0e463df3053f)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/34afda46-ab47-4568-bae9-9911936f5ce4

## What is the expected/desired behavior
Wormhole explorer opens transaction details page.

**Comment by mliu-xlabs** [comment]
@aadam-10 generally should only take about 10 seconds or less to start being able to show data in whscan, so this is an uncommon case.

**Comment by AigaD** [comment]
Reproduced for transaction 0.0001 USDC from Optimism to Fuji. Wormhole explorer shows - Search not found
Tested from: https://wormhole-connect.netlify.app/#
[Optimism explorer](https://goerli-optimism.etherscan.io/tx/0x2a072aa5978c5ed684bdbee832f0eca5ef7d59c29b96dfec19012b6edb9cf746)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7792f187-65e6-48b7-b17f-b0637bcf88bf

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Search not found when opening Wormhole explorer also reproduced fro transaction Base to Optimism

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6713495-1a8e-4e05-89ec-dc29b85badb5

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.33 USDC from Base (Metamask) to Avalanche (Metamask). Transaction details are not shown on Wormhole scan.

Send from tx: [BaseScan](https://basescan.org/tx/0x1b9c9f23754d4a02d1769bef02a42bc1dbf012027f22eb69d7fb8a9a7835b2b9)
Link to Wormhole explorer: [Wormhole scan](https://wormholescan.io/#/tx/0x1b9c9f23754d4a02d1769bef02a42bc1dbf012027f22eb69d7fb8a9a7835b2b9)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/97f06980-a03c-4c4d-aa0a-80cd30bf93ea

**Comment by AigaD** [comment]
Checked from: https://wormhole-connect.netlify.app/#
For transaction 0.1 SUI from Sui to Moonbase [Wormholescan](https://wormholescan.io/#/tx/21/40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9/236?network=TESTNET) information is not loading.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cb3c80b1-f447-41ae-b386-cc35da232dc9

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# - Tested OK
Transaction details are shown at [Wormholescan](https://wormholescan.io/#/tx/21/40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9/355?network=TESTNET) for transaction Sui -> Moonbase
Tested from: https://wormhole-connect-mainnet.netlify.app/# - Tested OK
For transaction USDC from Base to Avalanche, [Wormholescan](https://wormholescan.io/#/tx/0x5542923605fb71ce0efab0d681c9203bf6bc15fc094fb1aa2b414d2ecaba6cbd) showed necessary details of the transaction
Closing the ticket, will re-open if issue reappears.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d1648f51-26b8-4569-9f90-055b0c608f86
