### ISSUE TITLE
[QA] Transaction hash could not be located

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#117]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps: 

1. Send 0.0121 FTM from Fantom to Goerli
2. Click on Scan link for Send From section
3. Click on Scan link at Send to section

Actual result: Both links indicated that transaction hash has not been found. MetaMask wallet indicated that the transaction has been successful. 

Expected result: Transaction hash can be located.

Comments: Inconsistent issue, has happened three times for now during testing.

Attachment:

https://user-images.githubusercontent.com/91047061/220838571-c1899d2c-7f64-44a8-9529-41aee451ca62.mov

https://user-images.githubusercontent.com/91047061/220865650-bde2ce2f-b53e-468b-b90b-fb4f2327f1a4.mov

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction hash not found for transaction from [Alfajores](https://explorer.celo.org/alfajores/tx/0xff4bd613b3df9c62f37b383a37cd74c7bbc1bd7dd826e0ae13e598183c790cce) -> [Goeli ](https://goerli.etherscan.io/tx/0xdb1df077f6cca1e038ce41b3e9bd834666db8bdb9022e583f88be71936867d7a)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f7cd06f9-118f-4f78-af50-93149ed91e6c

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Arbitrum explorer link for transaction from Arbitrum (WalletConnect-Metamask) to Mumbai leads to error page.

Attachment:
https://testnet.arbiscan.io/error

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/15c60bbd-011f-4599-9254-19eccea7c4bf

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1312--wormhole-connect.netlify.app/#
Reproduced from transaction USDC from [Arbitrum](https://testnet.arbiscan.io/error.html?500) to Mumbai
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/859ad0b0-9b54-44f2-8545-8e518388e3d7

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Unable to locate [Optimism](https://goerli-optimism.etherscan.io/tx/0x4d54a440a8015cfd2580f50aafdf4a9744c4730b66a92acc808b95c8d2c16719) transaction hash

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9e6f6080-897a-4ba6-bc4f-c0279b4c1b9a

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 WFTM from Moonbeam (Rabby) to Celo (Rabby). 
* Send from tx: [Moonscan](https://moonscan.io/tx/0xd9a319646d2c7bbe132e5ec615aa045593f97dd8021606a5732b8ac5db0fb0a0)
* Send to tx: [Celo Exlorer](https://explorer.celo.org/mainnet/tx/0xc54c6fdc0eaa47598e1265b078ce9e08d6df4fc5fd959ae81ecd98a4e9ff3268)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d1629f63-4d38-420f-a0fe-b4ef18be069a)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Tested OK. Explorer links both for [Moonbase](https://moonscan.io/tx/0x3568b49ed653313005c64a073c8f0a0189b5f2148641869355e57b2b767cdc98) and [Celo](https://explorer.celo.org/mainnet/tx/0x06868881dd88df7fd6f9dba289335d43e556ee09470f5e34e86b464fcafc21c6) were working. Closing ticket, will re-open if issue reoccurs

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://preview.portalbridge.com/749d45da9e/ [Mainnet] when sending 0.001 APT from Aptos (Petra) to Celo (MetaMask). 
* Send from tx: [Aptos explorer](https://explorer.aptoslabs.com/txn/0x9fc775fc76f2794482bbf8e34541b8b37bc18f6c5700bcd5a72c929e99db554e?network=mainnet)
* Send to tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0xec195817072b19b71c99be10d474c4ba44cbe2f9abe371fb98b5f9309c7075c3)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ca54f025-38f5-4025-ad7f-66b5a11ca743)

**Comment by tsadovska** [comment]
Closing the ticket, [Celo Explorer](https://explorer.celo.org/mainnet/tx/0xec195817072b19b71c99be10d474c4ba44cbe2f9abe371fb98b5f9309c7075c3) link opens transaction details page.

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending 1 BONK from Solana (Backpack) to Celo (MetaMask). Link to Celo explorer opens error page. Asset is received. 

* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/5WZP2oC8P6LFbisPHZ9xVTbVpMJBmWHDpcWWWcorMw88EqC5vtzoEDrzBPhYEY5NpogCkVhL4b1PnSFjq46JXcit)
* Send to tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0x98e3f96f8e7d40439d0be7f2dd543f7e47b25f18d7d7978c56952b98fe8fb694)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/67b72911-433a-4758-b9d2-feca0f442b50)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet]. Link to Celo explorer opens transaction details page for transaction mentioned above (scenario: send BONK from [Solana](https://explorer.solana.com/tx/5WZP2oC8P6LFbisPHZ9xVTbVpMJBmWHDpcWWWcorMw88EqC5vtzoEDrzBPhYEY5NpogCkVhL4b1PnSFjq46JXcit) to [Celo](https://explorer.celo.org/mainnet/tx/0x98e3f96f8e7d40439d0be7f2dd543f7e47b25f18d7d7978c56952b98fe8fb694)) and for new transaction (scenario: send FTM from [Fantom](https://ftmscan.com/tx/0x348d3b9cf62bead26794dd7c2b1107e9d521c3cfa7747ce223f85dfeab26e298) to [Celo](https://explorer.celo.org/mainnet/tx/0xd4c468b0210325471b43ed263e49b02e2526af6d1e77cd825220a77860fd1c5f)). 

Ticket is closed.

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKzYAL4g7QA%3D%3D#)
Transaction details are not found at Celo explorer for tranaction 1.4 CELO from Celo to Fantom. Re-opening ticket
Attachment:
[Celo](https://explorer.celo.org/mainnet/tx/0xce21f15b7d2d01ce595b46cef5ab78f982e05b23f864cf205f70c474280d5302)
[Wormholescan](https://wormholescan.io/#/tx/0xce21f15b7d2d01ce595b46cef5ab78f982e05b23f864cf205f70c474280d5302)
<img width="1225" alt="Screenshot 2024-05-16 at 14 04 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/759f0ab4-ece7-4cdc-9bb1-465fac3bcb42">

**Comment by tsadovska** [comment]
Rechecked that [link](https://explorer.celo.org/mainnet/tx/0xce21f15b7d2d01ce595b46cef5ab78f982e05b23f864cf205f70c474280d5302) is working. Closing the ticket. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b9b56fe1-9d09-45e9-933b-50cf0164493c)



> Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKzYAL4g7QA%3D%3D#) Transaction details are not found at Celo explorer for tranaction 1.4 CELO from Celo to Fantom. Re-opening ticket Attachment: [Celo](https://explorer.celo.org/mainnet/tx/0xce21f15b7d2d01ce595b46cef5ab78f982e05b23f864cf205f70c474280d5302) [Wormholescan](https://wormholescan.io/#/tx/0xce21f15b7d2d01ce595b46cef5ab78f982e05b23f864cf205f70c474280d5302) <img alt="Screenshot 2024-05-16 at 14 04 03" width="1225" src="https://private-user-images.githubusercontent.com/91047061/331177574-759f0ab4-ece7-4cdc-9bb1-465fac3bcb42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDI3NTQsIm5iZiI6MTcxNjIwMjQ1NCwicGF0aCI6Ii85MTA0NzA2MS8zMzExNzc1NzQtNzU5ZjBhYjQtZWNlNy00Y2RjLTliYjEtNDY1ZmFjM2JjYjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEwNTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYWExYjUzZGQ3ZWMyYTVkMjJiOTJkNDg5MzYxMTc5MWMzNjY4Y2ZiZGZhMmFmZmQ1ZjVjMjJhYjU3ZmQyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JMsljyIuRVDDGZeupE1rKnheV9MzIre9ULol8t9ShMk">
