### ISSUE TITLE
[QA] [Testnet] Balance is not loading for Sei

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1176]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.117 (Official Build) (x86_64).

Steps:
1. Select Sei network as source chain
2. Connect Keplr wallet
3. Open Assets list

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2debf657-32c0-48e9-94a6-237890d29bd3

## What is the expected/desired behavior
Balance is loaded.

**Comment by AigaD** [comment]
No longer reproducible, closing the ticket.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/968912ba-db2e-4223-aa89-0ba771729f52

**Comment by tsadovska** [comment]
Reopening the ticket. Balance for Sei network is not loading on https://wormhole-connect.netlify.app/ [Testnet]. 

Error: `GET https://rest.atlantic-2.seinetwork.io/sei-protocol/seichain/tokenfactory/denoms_from_creator/sei1dkdwdvknx0qav5cp5kw68mkn3r99m3svkyjfvkztwh97dv2lm0ksj6xrak net::ERR_FAILED 403 (Forbidden)`


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3643f4f1-0b2b-4991-9b5c-43863dbd33a2

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect.netlify.app/
No longer reproducible. 
Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-06-11 at 12 09 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/aa9afb71-ec16-4787-aa5e-502fac17462c">
