### ISSUE TITLE
[QA] Negative gas fee shown

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1191]
Preconditions:
Sui wallet connected at sending From section
Metamask wallet connected at sending to section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 WFTM from Sui to Moonbase
2. Click Approve and proceed with transaction
3. Observe Gas fee paid from Sui wallet

Actual result: Negative value for gas fee paid from Sui is shown

Expected result: Gas fee without minus sign is shown as paid for the transaction

Attachment:
[Sui explorer](https://suiexplorer.com/txblock/8RE9uPGzieirJM9DjH8fVgCdqH34uz7wHiT74TuhKBHB?network=testnet)
<img width="1058" alt="Screenshot 2023-11-01 at 12 51 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/56a2ce15-8ce9-49ad-b38b-cb16a57c5969">

**Comment by M-Picco** [comment]
Sui transactions can sometimes have a negative fee (for more details see their [docs](https://docs.sui.io/concepts/tokenomics/gas-in-sui)). You can also see it on the transaction explorer link:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/11276821/19d11c07-f6cc-4c0a-9ac7-2bdae4aa0f79)
