### ISSUE TITLE
[QA]Cannot connect using Torus wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1192]
Preconditions:
User has valid email

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Click on Connect Wallet
2. Search "Torus" and click on it
3. Type in you email address
4. Open your email and confirm the passcode
5. Observe Torus wallet

Actual result: Torus walled is not connecting to Wormhole-connect, endless loading

Expected result: Torus wallet is connected after passcode is confirmed

Comments: Issue related - https://github.com/wormhole-foundation/wormhole-connect/issues/989

Attachment:

<img width="1178" alt="Screenshot 2023-11-02 at 09 26 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9258ef4c-37a6-48ee-bba7-9e84b2da9c76">

**Comment by AigaD** [comment]
Issue is still reproducible, endless loading after user confirms the email address to check in the wallet.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
![Screenshot 2023-12-05 at 16 02 15](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aea3f41b-14e8-43a9-ad09-2bfd6c93aa94)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
User cannot connect using Torus wallet
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d789547f-58a6-4246-accb-df56e9ec2ad0

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/749d45da9e/ 
Cannot connect using Torus wallet.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c89170c-7876-438a-96a8-548ae5d11155

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Error appears when user tries to connect Torus wallet:
```
Error: Openlogin instance/session not found
    at w.computeAccount (index.49b65868.js:1:923)
    at async Ce.requestAccounts (index.49b65868.js:1:68417)
    at async Ce.providerRequestAccounts (index.49b65868.js:1:65298)
    at async chunk-vendors.49b5a73e.js:150:168771
    at async chunk-vendors.49b5a73e.js:150:75002
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fd1689bc-83bb-48b2-96b9-7659bd8abc6c)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Torus wallet button is not reacting when clicking, console `Refused to load the stylesheet 'https://solana.tor.us/css/widget.css' because it violates the following Content Security Policy directive:`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0861a3b9-25c7-450d-81b5-66a8a939de4e

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D#) (Connect v2) and https://portalbridge.com/.

![image](https://github.com/user-attachments/assets/3f0a5c2f-3397-4b3c-92b5-2ed8e94207d6)


![image](https://github.com/user-attachments/assets/db414dd7-274a-41b5-aa32-0d20dc428031)

Ticket is closed.
