### ISSUE TITLE
[QA] Asset stays connected for Network where it is not available

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1194]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Select Moonbase Network at Sending From section
2. Select Base Goerli Network at sending To section
3. Select USDT asset
4. Enter 10 USDT in amount section
5. Switch Network to any other where asset is not available (e.g. Fantom)
6. Observe

Actual result: Asset that is not available for selected Network does not disconnect when Networks are changed. Reproduced also with WETH (Optimism)

Expected result: Asset is disconnected when changing Networks if it is not in Available token list

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7ba46e49-9e87-4841-bcc8-eea6c006a923

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
USDT asset is left connected to network where the asset is not available in the available token list
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7411ee23-a847-40f5-a141-919820766b41

**Comment by agodlevska** [comment]
Issue is no longer reproducible https://wormhole-connect-mainnet.netlify.app (old and new design). 
Asset is disconnected when changing networks if it is not in Available token list. 
Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/d387a8b9-0c11-4786-b7b0-c9061fc57a55
