### ISSUE TITLE
[QA]Missing Wormhole explorer link 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1199]
Preconditions:
Leap wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.0001 Celo from Moonbase to Alfajores
2. Click Approve and proceed with transaction
3. Observe if "View on Wormhole explorer" link is present

Actual result: Link "View on Wormhole explorer" is not shown

Attachment:

<img width="1070" alt="Screenshot 2023-11-03 at 12 40 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/575ca06a-05a9-477d-8d2d-3a03a1f3bd54">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2023-11-14 at 14 11 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8ae1452-2860-48b2-80f6-b66b326b3d9f)

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJCO4plGboWIRcIybhnzFeABaQKkNik2CwOuTEXWwAXxDOgA#)
Closing as this is no longer reproduced. Wormholescan link was shown.
Attachment:

<img width="1059" alt="Screenshot 2024-05-16 at 11 33 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ef2a4c42-d884-4187-b491-d3a09163e38b">

**Comment by agodlevska** [comment]
Reopening the ticket. 
Issue reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending to and from Sui network. 

Attachment:
<img width="1440" alt="Screenshot 2024-07-09 at 11 03 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/c0fa30ba-d9b6-4b89-aad9-68914edf6cf7">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D#) (Connect v2).

![image](https://github.com/user-attachments/assets/71bf9acc-f21a-4c86-945f-a822ce6c9eae)


Ticket is closed.
