### ISSUE TITLE
[QA] Improvement: Show a message to the user that wallet address has been copied

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#120]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on the wallet
2. On the drop down list press "Copy address"

Actual result: Address is copied, but user is not informed that the action was done.

Improvement: Show an indication to the user that Wallet address has been copied to the clipboard. 

Attachments:

https://user-images.githubusercontent.com/91047061/220904339-7a158ef1-9e81-45d8-b8e5-8b92ab63c962.mov

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
There is no indication that the wallet address has been copied.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b1dccd90-0933-478b-b10b-55c73e266032

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

https://github.com/user-attachments/assets/e7b0cc42-0c37-42ee-a5c0-38e82eb85875

Closing the ticket.
