### ISSUE TITLE
[QA] "Destination chain gas estimate"/ Relayer fee is not shown for transactions from Cosmos chains

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1200]
## Describe the current behavior in detail
Builds - Tested NOK:
- https://wormhole-connect.netlify.app/ [Testnet]
- https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Checked on macOS 12.7 and Google Chrome Version 119.0.6045.105 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.0001 WSOL from Kujira  (Leap) to Ethereum (Metamask)
2. Expand "Total fee estimate" in Preview section
3. Observe if "Destination chain gas estimate" is calculated

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/289e2caa-d77a-44b3-8cf5-755e45c409b8)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a7c20c7a-08bb-42c8-9fdc-ce36598c0ea4

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9298d7a1-cfb1-4841-89c3-ae1a980a9928)

## What is the expected/desired behavior
"Destination chain gas estimate" value is calculated.

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/651

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/
Attachment:

![Screenshot 2024-01-30 at 12 41 00](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0cc64c9d-95ca-4a1d-b8a6-77088ee172f7)

**Comment by AigaD** [comment]
Issue is still reproducible, gas estimates are shown as 0
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2024-03-01 at 16 23 52](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6c5064e5-720e-4608-a42f-9d991873ee83)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6). "Destination chain gas estimate" values are not shown when sending assets from Cosmos chains (Osmosis, Injective, Evmos, Kujira).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/050267f1-b0a5-49ab-9bca-3223ff722a45)

**Comment by agodlevska** [comment]
Issue is still reproducible, gas estimates are shown as 0
Tested on https://portalbridge.com/
Send 0.0001 WETH from Kujira (Leap) to Ethereum (Metamask)

Attachments:
<img width="1440" alt="Screenshot 2024-05-27 at 16 00 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/eb811131-4367-4ccd-adc0-cd9c064ce49b">

**Comment by agodlevska** [comment]
Reproducible on https://portalbridge.com/
Gas estimates are shown as 0.
Send 0.01 WMATIC from Injective (Leap) to X Layer (Metamask)

Attachments:
<img width="1439" alt="Screenshot 2024-05-30 at 16 00 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/4f1864f0-dc99-4aaf-8c5a-db96761c78bb">

**Comment by agodlevska** [comment]
Issue is still reproducible, checked on https://preview.portalbridge.com/b3b7091778/.
Gas estimates are shown as 0.
Sending 0.1 CELO from Injective (Leap) to Osmosis (Metamask).

Attachment:
<img width="667" alt="Screenshot 2024-08-27 at 12 16 16" src="https://github.com/user-attachments/assets/e08e09fa-a958-4e29-957a-2aaacc6f611f">

**Comment by tsadovska** [comment]
Cosmos chains are no longer displayed in Networks list. 

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Closing the ticket.
