### ISSUE TITLE
[QA] Balance in "Add suggested tokens" notification is not loaded

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1201]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.105 (Official Build) (x86_64).

Steps:
1. Send 0.00001 WETH (Base) from Fantom (Metamask) to Base (Metamask)
2. Click "Add WETH (Base) to your wallet" when transaction is completed
3. Observe Balance in "Add suggested tokens" notification

![Screenshot 2023-11-06 at 12 31 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/25ae6599-83b1-4a6f-acb8-8fa465ed2cd7)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/06355259-7431-4fd6-a1fb-86c20071407b

## What is the expected/desired behavior
Balance is loaded.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Firefox Version 115.0
For transaction 0.001 ETH from Goerli -> Mumbai add token balance is not shown
Attachment:

![Screenshot 2023-12-04 at 10 11 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/839106e4-077a-4e4f-abb7-7fc1d68d01a0)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0015 wstETH (Optimism) from Optimism (Metamask) to Arbitrum (Metamask). 
* Send from tx: [Etherscan](https://optimistic.etherscan.io/tx/0x67c357d687ba1ccb8c271dc5f594ca96fea7287ae5aa64df0718aafe363a4703)
* Send to tx: [Arbitrum explorer](https://arbiscan.io/tx/0xbd0565fdbf35f6cdc1851e39f32b97face1d94bbdc3ef35d5a5c83e16a43ecfa)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x67c357d687ba1ccb8c271dc5f594ca96fea7287ae5aa64df0718aafe363a4703)


![Screenshot 2024-01-15 at 14 53 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0f863952-9a14-4683-a9d1-f03cb030f2b6)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending WETH (Base) from Fantom (MetaMask) to Base (MetaMask). WETH (Base) balance is loaded in "Add suggested tokens" notification. 

Scenario from Jan 15 will rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1909 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://portalbridge.com/ [Mainnet].
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x7f9a6854495556ca47c8a1e9e0ca357632aed6779e80a54c44d7c2fdc4942f2d)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/0xeb0436d8065a06b013938a2159445584f7dc1a4527ea4b7403cc7b93ab128218)



![image](https://github.com/user-attachments/assets/98f888af-25f3-4b55-8b3c-8055fefde507)

Ticket is closed.
