### ISSUE TITLE
[QA] Not able to select Kujira or Evmos network when OneKey wallet is connected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1207]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.105 (Official Build) (x86_64).

Steps:
1. Connect OneKey
2. Select Kujira/ Evmos chain
3. Observe

Errors:
```
Uncaught (in promise) Error: No chain info found for evmos_9001-2
    at lM.addChain (main.41863c92.js:2:17649733)
    at lM.connect (main.41863c92.js:2:17649073)
    at async lM.switchChain (main.41863c92.js:2:17649946)
    at async H0 (main.41863c92.js:37:242075)
    at async b1 (main.41863c92.js:37:249361)
```
```
Uncaught (in promise) Error: No chain info found for kaiyo-1
    at lM.addChain (main.41863c92.js:2:17649733)
    at lM.connect (main.41863c92.js:2:17649073)
    at async lM.switchChain (main.41863c92.js:2:17649946)
    at async H0 (main.41863c92.js:37:242075)
    at async b1 (main.41863c92.js:37:249361)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5668b697-c7f4-43d1-9b21-21be4fecc22c

## What is the expected/desired behavior
User can connect Kujira or Evmos chains.

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Evmos Network can be selected in OneKey wallet, but can not connect to it when selecting Evmos Network
Kujira Network is not supported by OneKey according to [this list](https://onekey.so/cryptos/)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a01c7528-bb64-43d9-99f8-4d4363a9e0fb

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
User is not able to switch to Evmos Network using OneKey wallet
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/764dd812-1c50-4f76-9ed8-2f4c342c3c01

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet]. 
Network is not changed from Osmosis to Kujira/ Evmos if OneKey wallet is connected.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1957b694-a08e-4399-b545-cf7d81526dc5

**Comment by tsadovska** [comment]
Remaining issue https://github.com/wormhole-foundation/wormhole-connect/issues/1783
Ticket is closed.
