### ISSUE TITLE
[QA][Mainnet] Transactions to Evmos are not moving past Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1211]
Preconditions:
Metamask wallet connected at sending From section
Leap (Evmos Network) wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.1 MATIC from Polygon to Evmos
2. One transaction Route is selected
3. Click Approve and proceed with transaction
4. Observe if transaction is completed

Actual result: Transactions to Evmos are not moving past Step2 for more than 2 hours, console shows `GET https://wormhole-connect-mainnet.netlify.app/manifest.json 401 (Unauthorized)`

Expected result: Transaction is completed

Comments: Linking to issue https://github.com/wormhole-foundation/wormhole-connect/issues/1047 

Attachment:
Transaction [Polygon](https://polygonscan.com/tx/0x598fb206e080fc3612933893b50fb9d272a407c8476f78d8e075d01325a4fc8a) to Evmos
Transaction [Moonbeam](https://moonscan.io/tx/0xf63e45af6dfbd6dcf3d8ccb338ec60c876298d6a8810a22ffe41a3b1d85d810c) to Evmos
Transaction[ Solana](https://explorer.solana.com/tx/2SSKMyvGU31wedgVfy6qCa1Jr5TBF4QPQG9wPUZ8iTDuh3i24FTAUHtqMPtJ4mwjxPbk8Uujdbm3qEAtVHL7mU5y) to Evmos
Transaction [Avalanche](https://snowtrace.io/tx/0x3421e04d0088c6ac5b0887d5ea56705f71b4008915353adce27a10298a5d2e93) to Evmos

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f12b439e-a5ce-4d57-abc2-0583dc85da42

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Transactions - Tested OK:
* Send 0.01 WFTM from Avalanche (Metamask) to Evmos (Keplr): [Snowtrace](https://snowtrace.io/tx/0x208f5f1761ad33e76162ede4567fff1268ca651e52f368744d03aaeeb40bab0f), [Mintscan](https://www.mintscan.io/evmos/tx/1D3F8896F756EAA5F54080B1AB7D1EC3A7314890020E5E1489617E06A8EDF11A)
* Send 0.1 GLMR from Moonbeam (Metamask) to Evmos (Keplr): [Moonscan](https://moonscan.io/tx/0xef5b9e6ba40ba6f770aa721182a95a15d72998ad29f21f039176b7bbf30379b2), [Mintscan](https://www.mintscan.io/evmos/tx/548553816B3E8C26F4B064FE216727614FDD1523418010B999E8F60068E1C812)
* Send 0.0001 BNB from BSC (Metamask) to Evmos (Leap): [BSCScan](https://bscscan.com/tx/0x7e90d4d85ba3984df66efc333f9e12e1224add306fd6ec0be2d63b2dd27b28f2), [Evmos](https://www.mintscan.io/evmos/tx/1FD8A42F6807A4C9F1B650DABF5D4B4CD44BF6514101C609315F10FB7A485059)

Ticket is closed.
