### ISSUE TITLE
[QA] Balance in "Add suggested tokens" notification should have more decimals

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1216]
## Describe the current behavior in detail
Checked on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.0001 tBTC from Goerli (Metamask) to Mumbai (Metamask)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen
4. Click "Add tBTC to your wallet" link
5. Observe balance in "Add suggested tokens" notification

Actual result: Balance in "Add suggested tokens" notification is 0 tBTC.

![Screenshot 2023-11-10 at 10 30 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7778ecc2-df62-496a-97f0-07a6e88af764)

## What is the expected/desired behavior
Balance in "Add sugested tokens" notification is 0.0001 tBTC.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000001 tBTC from Solana (Phantom) to Arbitrum (Metamask). Balance in "Add suggested tokens" notification is 0 tBTC.

* Send from tx: [Solana explorer](https://explorer.solana.com/tx/2koiYRTudNZyTTJXWV6GYzMfv7i5vEXKq6cjwhL6oYyhKPerEEzes9L5vswYZA8pdfZ2sdZZ62ArStQPFUTGgRf4) 
* Send to tx: [Arbiscan](https://arbiscan.io/tx/0x602aba230d7d49965f5ae0e731ed1bf4bf6903d14a5b7ebd6d076bb72bb00a87)

![Screenshot 2023-11-13 at 09 54 02](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/db8c608c-587c-421f-b8b3-c50f7cfdf436)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 USDC from Solana (Phantom) to Polygon (Metamask). Balance in "Add suggested tokens" notification is 0 USDC. 
* Send from tx: [Solana explorer](https://explorer.solana.com/tx/4hUWyVTJHDz958nuEuR56EtubEGCUKxzEP3CQqYLr8hjyBENM5YD43ibiwZNmmMHA5rAz85VxmmHAoa51XeztLhh)
* Send to tx: [Polygonscan](https://polygonscan.com/tx/0xf620717d11b168cc221696eb3b254e3e0a4d672a4caafdef99cec2a159782cb9)

![Screenshot 2023-12-15 at 13 43 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8d4aaf3e-4a3c-4208-bf78-977f096c308d)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] when sending 0.0001 SUI from Osmosis (Keplr) to Celo (Metamask). Balance in "Add suggested tokens" notification is 0 SUI.

* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/tx/DA3E52D9EE76F3AE8C2AAA7B64314BB52CC1A61204127D0C6604694AE4120B60)
* Send to tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0xa72dc269447cbf2de1ce5ff21a9080f70e1f1356a63e21b19ce9e6acc44d4c77)


<img width="1154" alt="Screenshot 2023-12-20 at 18 06 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4b2b1350-ce85-4203-a5d0-e83457bfbde2">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] when sending 0.001 USDC (Polygon) from BSC (Metamask) to Polygon (Metamask).

<img width="1004" alt="Screenshot 2023-12-22 at 22 32 29" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f0142bc3-1306-44df-94ce-fd404ce225b3">

**Comment by AigaD** [comment]
Reproducible from: https://preview.portalbridge.com/bf7b5b43a8/#
For transaction from 0.001 ETH [Ethereum](https://etherscan.io/tx/0xbc989f0ae16c4c5339cba9f49ac649739c2f591b58755c1a8b77b2b4b12c544e) to [BSC](https://bscscan.com/tx/0x1bff334229fc46d1e621f87eb7084f53b82dffed2a45d3949d750618da24df52), added token is shown as 0 WETH

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b79dc90-4958-44f0-9bca-4c79be2aae67
![Screenshot 2024-01-11 at 11 22 46](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3ee1438e-c685-4fc0-9de5-8bae2b9337ce)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
For transaction WETH (Polygon) from Polygon to Arbitrum, when adding token, the added token amount is shown as o WETH

Attachment:

![Screenshot 2024-01-12 at 11 59 37](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a0f68ca9-6ce3-4758-8d15-96cd3955637f)

![Screenshot 2024-01-12 at 12 01 55](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a6427ba-6f7f-4a65-93b7-4b4d599939fe)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0023 WETH (Polygon) from Polygon (Metamask) to Ethereum (Metamask). 0 ETH is shown in Metamask notification to add suggested tokens. 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x47c116ded1f1a5c88e4de374ff51b5ca5d27fcc179a2d20d1df28a031b21caff)
* Send to tx: [Etherscan](https://etherscan.io/tx/0x1fa83b52c7f4421d89ccee1d3de3ed52d4d64b195784f46ab2d411c95de38beb)

<img width="355" alt="Screenshot 2024-01-12 at 12 29 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6f724378-9b90-4adf-bdf9-9d89455edae1">

**Comment by tsadovska** [comment]
Reproducible on https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development) when sending 0.001 W from Solana (Phantom) to Sepolia (MetaMask). 0 ETH is shown in MetaMask notification to add suggested tokens. 
Expected result: Balance in "Add suggested tokens" notification has more decimals. 

* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/2SFGKVn9fhMxGcBKXDYXvyeiF2JcmK1vtVfR4hkV8WiBz4V7DujrpL51wEpfmdAmF4vhokt7eLSMKDf7VwvLBTzV?cluster=devnet)
* Send to tx: [Etherscan](https://sepolia.etherscan.io/tx/0x8c2364cac92dc7630e3d7cc3f64318473222f1b728c0d8bdf5560c0cc543ff82)


![Screenshot 2024-04-17 at 09 59 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3f670247-c774-4b0b-8762-a59b993763fa)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.001 WAVAX from Blast (MetaMask) to Avalanche (MetaMask). 0 WAVAX is shown in MetaMask notification to add suggested tokens. 

Expected result: Balance in "Add suggested tokens" notification has more decimals.

* Send from tx: [Blastscan](https://blastscan.io/tx/0xff4a25778f7200e9e9bf72fb5a2a5f49f427490e8c65a2c6159caa9bba3acbf5)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0xd0f3ba71e2079bd0fc8e600bde58e2904b64d71c5c92af0a40242dc917a08f3a)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c6c869a7-c357-46bb-84e1-692f24c4f1ad)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. Balance is displayed correctly in "Add suggested tokens" notification.

Checked following scenarios:
* tBTC transfer from [Solana](https://explorer.solana.com/tx/5jBjfKR6c9UJL46bqznXdZ2nzwrtEuDvKbN4TDqo7RFMGzaV4Whx9BbkjDqyzZbD9D8mWq4Bqi2qH7hVMcgxz9o1) (Phantom) to [Arbitrum](https://arbiscan.io/tx/0x0dae822745f91f10c87077e4ed0b1d565fe58001b02dade792332d838751a8f7) (MetaMask)
* USDC transfer from [Solana](https://explorer.solana.com/tx/4hwKVamqioCq7e88W3nvLiUwQVayQtcA7o7jKcHtVChTPNk2FLpWPNC5aa1RTerX9qkCGyvBZYFKLkiZjh2KdEkU) (Phantom) to [Polygon](https://polygonscan.com/tx/0x3bb7fbd9ccd3a49e56b88b6d091a7555fcbaa25c346d5dad5a036d806011505d) (MetaMask)
* SUI transfer transfer from [Osmosis](https://www.mintscan.io/osmosis/transactions/521D68FDA1E882C12F310BE28957689975444016C1D81367905198D07999BF3C) (Leap) to [Celo](https://explorer.celo.org/mainnet/tx/0x60d91085a29343b3170f6bcfeae997308c0df514a270ba9121ce66e4eb001918) (MetaMask)
* USDC transfer from [BSC](https://bscscan.com/tx/0x2c600100437bae6392e34d1b6c6d50ca2842412d1185af1193aed4e218672111) (MetaMask) to [Polygon](https://polygonscan.com/tx/0x2ef42070fda7d2055a56f6453d4ae22c8443c2fab2eae43d6b970b5d8099db17) (MetaMask)
* WETH transfer from [Polygon](https://polygonscan.com/tx/0xa23d56820a5ad038988d5c3902a2cb1c2b5919d2867befd5f722974022dc9678) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x57c04f0898c2f45012b2a0291e8e2efe357559e19fbbda5545358c8fa7571074) (MetaMask)
* W transfer from [Solana](https://explorer.solana.com/tx/4QHQ9YWzvVXK4N2zGnfi7zC3wdMNModeLijve58S5KuxZAaFuDMhDgjPhNVrDKGkjnHKVfVw7Eg624AdBTT6fBtD) (Phantom) to [Ethereum](https://etherscan.io/tx/0xfc857efb0fd86325187ec389fc65fc462c6262586f1ed504b1d61be1b1d7f009) (MetaMask)

Ticket is closed.
