### ISSUE TITLE
[QA] "View on Wormhole Explorer" link opens error page, tx Sei -> Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1217]
## Describe the current behavior in detail
Checked on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SEI from Sei (Leap) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Click "View on Wormhole Explorer" link on Redeem screen

Link to [Wormhole scan](https://wormholescan.io/#/tx/32/9328673cb5de3fd99974cefbbd90fea033f4c59a572abfd7e1a4eebcc5d18157/23095?network=TESTNET)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/39f13f05-a809-4a74-8c7a-1c2663f781de)

## What is the expected/desired behavior
"View on Wormhole Explorer" opens transaction details page.

**Comment by AigaD** [comment]
Adding the observations to https://github.com/wormhole-foundation/wormhole-connect/issues/1150 
Closing this ticket as duplicate
