### ISSUE TITLE
[QA] Token picker shows the wrong contract address for tBTC on Fuji/ Avalanche

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1218]
## Describe the current behavior in detail
Checked on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 And Google Chrome Version 119.0.6045.123 (Official Build) (x86_64). 

Steps:
1. Send 0.00001 tBTC from Goerli (Metamask) to Fuji (Metamask)
2. Open Snowtrace link in "To" section
3. Observe asset contract
4. Click "Bridge more assets" button
5. Connect Fuji in "From" section
6. Connect Metamask wallet in "From" section
7. Observe tBTC token contract address

Actual result:
* Token contract address in wormhole-connect is 0x679874fBE6D4E7Cc54A59e315FF1eB266686a937
* Token contract address in Snowtrace is 0x7E1779F65B644E5f98DdC4D2cB0A0106a7E6d9e1
* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xc4916eb767796e266f4cd15f0f98a9bbff71076065bc0f6646847ea2f8a87f86)
* Send to tx: [Snowtrace](https://testnet.snowtrace.io/tx/0x2fe8b275b8f48f8a8a3be4c123cb18a06edeac62789b7ea4f04f68450b343251)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/802fee5c-050b-4d10-afc7-bd62dea1e410)

![Screenshot 2023-11-10 at 19 35 55](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/488e25f7-197a-4036-8076-69a610848158)

## What is the expected/desired behavior
Token picker shows contract address 0x7E1779F65B644E5f98DdC4D2cB0A0106a7E6d9e1 in wormhole-connect.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.00001 tBTC from Ethereum (Metamask) to Avalanche (Metamask). Token picker shows the wrong cotract address for tBTC on Avalanche.

* tBTC contact address in wormhole-connect: 0x18084fbA666a33d37592fA2633fD49a74DD93a88
* tBTC contact in Snowtrace: 0x3F531c038A0D2d9c7D19FC3554cd0439791526c4
* Send from tx: [Etherscan](https://etherscan.io/tx/0x65b23902fdce4ee6d74011ac58e96e46ff8aac104996e1009fbb8e21779b2fb2)
* Send to tx: [Snowtrace](https://snowtrace.io/tx/0xb2b958ca1adee5cfed6d70d227f0aae719cb5f838532c0c63e956da3560abab0)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/46d332dc-1e64-4cea-aaab-024c3f4aa067)

![Screenshot 2023-11-14 at 15 21 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/996a5779-1b32-47dd-bf4d-5be394631e11)

**Comment by aadam-10** [comment]
Expected behavior as in the token list, the contract that is supposed to be shown is the contract for that particular token on the chain that it lives on, before the transfer. In these two cases, the tBTC token that is issued on Goerli is [this contract](https://goerli.etherscan.io/address/0x679874fBE6D4E7Cc54A59e315FF1eB266686a937), which is shown in the UI properly. And in the second mainnet case, it's [this contract](https://etherscan.io/address/0x18084fba666a33d37592fa2633fd49a74dd93a88), so it's fine. These are the canonical tBTC contracts.
