### ISSUE TITLE
[QA][Mainnet] tBTC transfers fail due to "cannot estimate gas" error

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1222]
Preconditions:
Metamask wallet connected
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.00001 tBTC from Arbitrum to Ethereum
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Error: cannot estimate gas; transaction may fail or may require manual gas limit `

Expected result: Transaction continues to next screen and is completed

Comments: Similar issue on testnet from Arbitrum - https://github.com/wormhole-foundation/wormhole-connect/issues/1127

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/adbdae8c-aa59-48d1-8a7d-c0c8059c7e6e

![Screenshot 2023-11-14 at 10 57 57](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6de3daa0-beda-439a-aee3-741ae3bb3953)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] when:
* Sending 0.000002 tBTC from Optimism (Metamask) to Ethereum (Metamask)
* Sending 0.000002 tBTC from Base (Metamask) to Ethereum (Metamask)
* Sending 0.000001 tBTC from Base (Metamask) to Polygon (Metamask)
* Sending 0.000001 tBTC from Base (Metamask) to Arbitrum (Metamask)

Errors in Console:
`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}, stack: '{\n  "code": -32603,\n  "message": "Internal JSON-RP…hfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935'}`

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: insufficient allowance", method="estimateGas", transaction={"to":"0x09959798B95d00a3183d20FaC298E4594E599eab","data":"0xf69785f3000000000000000000000000000000000000000000000000000001d1a94a200000000000000000000000000000000000000000000000000000000000000000020000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc701200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: ERC20: insufficient allowance","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d45524332303a20696e73756666696369656e7420616c6c6f77616e6365000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: ERC20: insufficient allowance\",\n    \"data\": \"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d45524332303a20696e73756666696369656e7420616c6c6f77616e6365000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (main.23680ae7.js:2:948592)
    at f.throwError (main.23680ae7.js:2:948712)
    at v (main.23680ae7.js:2:1006887)
    at u.<anonymous> (main.23680ae7.js:2:1016841)
    at Generator.throw (<anonymous>)
    at s (main.23680ae7.js:2:1005988)
```

**Comment by kev1n-peters** [comment]
This issue should be resolved with https://github.com/wormhole-foundation/wormhole-connect/pull/1174/commits/e74ff2a5e69b12345b0708afe01a4625a9d850da

**Comment by AigaD** [comment]
Transaction tBTC from Arbitrum -> Ethereum tested OK
Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2023-11-14 at 17 37 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ca67cb4d-9f39-48e4-a758-3e104a8ca483)

**Comment by tsadovska** [comment]
Following scenarios are no longer reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* Send 0.000001 tBTC from Base (Metamask) to Polygon (Metamask): [BaseScan](https://basescan.org/tx/0xf440ccb9c3a8565f28e267883002e90ac42664f51279cf301971e57039db892b), [Polygonscan](https://polygonscan.com/tx/0x42abf4af81bfb4e0a0d6f5b2af900bf7e5409f854feff06eb084e9e5c2c6ed08)
* Send 0.000001 tBTC from Base (Metamask) to Arbitrum (Metamask): [BaseScan](https://basescan.org/tx/0x0cf1821ed4ed452e020801c81b3d6fdc210b0d1e3069152cf1acd8e5f89cca5d), [Optimism explorer](https://optimistic.etherscan.io/tx/0x001b1c25339ed3c35400fe45202cb7d0e055dc5ae50beed6193a3c8c32b8f96e)
