### ISSUE TITLE
[QA] [Mainnet] "No bridge or swap route available for selected tokens" for tx from Solana

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1224]
Preconditions:
Phantom/Solflare wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send e.g. Sui/ SOL/WFTM from Solana to e.g. Moonbeam/Fantom/Sui
2. Enter the amount
3. Observe

Actual result: Warning message "No bridge or swap route available for selected tokens" is shown and user cannot continue

Expected result: User is able to continue with the transaction

Attachment:
![Screenshot 2023-11-14 at 14 32 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c12c39b-bc20-44b7-a873-566dd3a40214)
![Screenshot 2023-11-14 at 14 31 50](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0b58a168-42a6-42dc-96c4-87738615754c)
![Screenshot 2023-11-14 at 14 30 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a2afe8c0-5ec4-401e-b43f-0030a81a6a36)
![Screenshot 2023-11-14 at 14 30 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/33107cb6-5dbd-4737-931d-0412a2e0e9fe)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet] for SOL transfer from Solana (Phantom) to Avalanche (Metamask).

**Comment by kev1n-peters** [comment]
Should be fixed with https://github.com/wormhole-foundation/wormhole-connect/pull/1174/commits/6ee8d9dd2b1d3007780b5582c06f609d61d8148b

**Comment by AigaD** [comment]
Tested OK. Closing the issue
Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
Attachment:
[Solana explorer](https://explorer.solana.com/tx/4tEHZvwTanNpwwPS9oVCxDfKTV92UPrMGSMYHU6BdP27qa1N7pfEuSFoypdbMyYH1DyXcSzxMEUJg4tECNg2XTRK)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/97a29bb2-f9ad-4928-b694-590696f66df5
