### ISSUE TITLE
[connect > portal] - remove 'token bridge' title

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1226]
**Task**
Remove 'Token Bridge' title from the main page for Portal Bridge version of connect

**Comment by sebastianscatularo** [comment]
this could be archived by setting `pageHeader` to empty string -> https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect-loader/src/types.ts#L76

**Comment by sebastianscatularo** [comment]
checked, this can be done by setting `pageHeader` to undefined or empty string
