### ISSUE TITLE
[QA][Mainnet] Cannot connect wallet to Claim transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1229]
Preconditions:
TX hash for transaction 0.001 CELO from [Osmosis (Leap)](https://www.mintscan.io/osmosis/tx/1940FFE483C332703AC498FB31196565CE5803FB72DF8F2FD9590B330F6C8EFA) to Solana (Solflare) - 1940FFE483C332703AC498FB31196565CE5803FB72DF8F2FD9590B330F6C8EFA

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Click on Menu and select Resume transaction
2. Paste in the provided transaction hash - 1940FFE483C332703AC498FB31196565CE5803FB72DF8F2FD9590B330F6C8EFA
3. Select Osmosis Network
4. Click Search
5. Observe the connect button ( #1212  )
6. Click on Connect
7. Select wallet
8. Observe

Actual result: Wallet is not connecting and it is not possible to Claim the transaction. Transaction from Osmosis to Solana is stuck at Claim, instead of Claim Connect Wallet is shown with incorrect wallet address and the connection does not happen

Expected result: Wallet is connected and user can Claim the transaction

Comments: 
[Mintscan](https://www.mintscan.io/osmosis/tx/5E5A9223D79BCDE9DD6441F9028DA1B5318CE80232B3E0005104746351F2708C)
[Mintscan](https://www.mintscan.io/osmosis/transactions/1940FFE483C332703AC498FB31196565CE5803FB72DF8F2FD9590B330F6C8EFA)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8fb63904-354a-43ba-86d3-b07f1e7a2bb2

**Comment by aadam-10** [comment]
Should be fixed in https://github.com/wormhole-foundation/wormhole-connect/pull/1227 , but the deploy-preview-1174 does not contain this fix. Can you verify on https://wormhole-connect-mainnet.netlify.app/ ? That should contain it.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Checked that it is possible to finish transaction that was started and from Resume transaction screen:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/eef37fa3-5986-44a4-bade-a639b813af04


![Screenshot 2023-11-17 at 11 29 28](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d05fbbda-a720-414f-8ff1-bbc7452eca07)
