### ISSUE TITLE
[connect > portal] - add warning message for all the transfer of USDC that does not use CCTP

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1233]
Add a warning message for users that attempt to transfer USDC using a different corridor than CCTP

- [ ] add a warning message for users that attempt to transfer USDC using a different corridor than CCTP
- [ ] add an option to enable this warning
- [ ] (optional) add an option to redirect the user to another site, for instance [USDC Bridge](https://www.portalbridge.com/usdc-bridge/)

**Comment by mliu-xlabs** [comment]
Additional requirements:
- User should still be able to natively use CCTP in supported chain pairs in the main flow

See warning below:

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/7c666803-e27d-494e-a318-385d7552e360)

- The warning should appear in the same location as the warning shown above.
- There are 2 other checks that will happen for potential warning messages that will appear here.
- List of priority of the checks:

1. Check whether the asset is registered on the dest chain
2. Check whether the user has an associated token account created for that asset
3. Check whether the chain pair supports CCTP (USDC only)


warning message as follows:

This transaction will transfer wrapped USDC (wUSDC) to the destination chain. If you want to transfer native USDC on chains supported by Circle's CCTP, use the [USDC Bridge](https://www.portalbridge.com/usdc-bridge/).
