### ISSUE TITLE
[QA] [Testnet] Cannot register SOL for transaction Solana -> Moonbase

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1237]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SOL from Solana (Phantom) to Moonbase (Metamask)
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in Warning message "This token is not registered..."
3. Select Solana network as source chain
4. Select SOL asset with contract `So11111111111111111111111111111111111111112`
5. Select Moonbeam in Step 2 "Target"
6. Click "Attest" button in Step 3 "Send attestation"

Errors:
`failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870`

```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870
    at ni.sendEncodedTransaction (connection.ts:5054:13)
    at async ni.sendRawTransaction (connection.ts:5017:5)
    at async ien (solana.ts:20:9)
    at async useHandleAttest.tsx:367:11
```

![Screenshot 2023-11-16 at 18 43 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a1156321-8e69-42c5-88fe-dc0fd22f8b7d)

## What is the expected/desired behavior
Token is successfully registered.

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1373 and  https://github.com/wormhole-foundation/wormhole-connect/issues/1482 are resolved.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-foundation.github.io/example-token-bridge-ui/#/register [Testnet]. 

Error appears in Console after clicking on "Attest" button:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 30.00 seconds. It is unknown if it succeeded or failed. Check signature 3QgzHisajFzZSJVhd2euuYnjMzPQHbRoikJvdTXCAPoXSNPUYqUrHraXeGguKtwAta1STdYFS3wvGHbkwV9mcpPz using the Solana Explorer or CLI tools.
    at ni.confirmTransaction (connection.ts:3461:17)
    at async ien (solana.ts:22:3)
    at async useHandleAttest.tsx:367:11
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/526af91e-f83a-4f28-b2d4-2ef9fff12f9f)

**Comment by AigaD** [comment]
Blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/1482

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Token is successfully registered. 

SOL transfer from Solana (Phantom) to Moonbase (MetaMask) was successful on https://wormhole-connect.netlify.app/ [Testnet]: [Solana explorer](https://explorer.solana.com/tx/53t7kpP829wvRjmbKPYdYB44vef5JTYGQabYbhQJRDZmURKZKw3Nh8D4387eWxRQ4Mku5t6P6qhJwiAUE4ANCuHn?cluster=devnet), [Moonscan](https://moonbase.moonscan.io/tx/0xd37e9debba5b8a4fe03cb4504b146477a917f54e71d1d8d15279a927aa42d10c).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/acf4996b-1055-4949-81ae-fb5127246868)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7a3bcf5a-bb49-415d-9e1e-4963458284e0)

Ticket is closed.
