### ISSUE TITLE
[QA] WalletConnect UI issues with app naming

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1241]
Preconditions:
None

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect-mainnet.netlify.app/
https://wormhole-connect.netlify.app/#

Steps:
1. Click on Connect wallet
2. Search WalletConnect
3. Open page 5
4. Observe

Actual result: There is some random UI overlapping

Expected results: Wallet names are displayed accurately 

Attachment:

![Screenshot 2023-11-17 at 15 07 32](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d358713-d090-4dbc-ad12-73ff55330cbd)

**Comment by tsadovska** [comment]
WalletConnect version was upgraded. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/546c96ca-b5cb-47f4-922c-05e7874f60e7)

Ticket is closed.

**Comment by AigaD** [comment]
Re-opening the ticket.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Steps
1. Click on Connect wallet
2. Select Wallet Connect (Solana)
3. Go to page 5

Attachment:
<img width="1060" alt="Screenshot 2024-01-23 at 20 09 27" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f61b840-3a10-4db5-8215-80d10feb632d">

**Comment by tsadovska** [comment]
"Desktop" tab is no longer available. 
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bef5e058-e9db-444b-80c5-12bdd7ffd503)

Ticket is closed.
