### ISSUE TITLE
[QA] Token registration fails with reason: "Cannot estimate gas"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1243]
Preconditions:
1. Metamask wallet connected at sending From section
2. Solflare wallet at sending To section
3. USDC asset available for the Base Goerli network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://deploy-preview-1174--wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Steps:
1. Prepare to send 0.001 USDC (Base Goerli) from Base Goerli to Solana
2. Observe that message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on button "register"
4. Enter Source chain Base Goerli
5. Connect Metamask wallet
6. Paste in the USDC contract address ( 0x861B5C16A2EcED022241072A7beA9D530b99EB6f )
7. Click Next
8. Select Solana Network\Connect Solflare wallet
9. Click Next
10. Click on Attest
11. Observe

Actual result: Error `cannot estimate gas; transaction may fail or may require manual gas limit` is shown and user cannot Attest the token

Expected result: Token is attested and registered

Attachment:

![Screenshot 2023-11-17 at 15 48 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/536f35ac-8b1c-44de-9b31-f3c3e164e99e)

![Screenshot 2023-11-17 at 15 32 26](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c958ea8e-ed9e-4bb1-a75b-3b987730c4f8)

**Comment by evan-gray** [comment]
Wondering where the `0x861B5C16A2EcED022241072A7beA9D530b99EB6f` came from? I think the registration error happened because that token doesn't exist on Base Goerli.

**Comment by tsadovska** [comment]
USDC (Base Goerli) is now successfully registered for transaction Base Goerli -> Solana on https://wormhole-foundation.github.io/example-token-bridge-ui/#/register. Correct contract: 0xF175520C52418dfE19C8098071a252da48Cd1C19. 

Link in Step 3 "Send attestation": [Basescan](https://goerli.basescan.org/tx/0x86907a74db0ba532bd7e825c41d2962ae135e4473087ba7b23bdb1fbb0e6827b)
Link to Step 4 "Create wrapped token": [Solscan](https://solscan.io/tx/5jC5dxfF3AZ2NUeE3PJ5719TVybyp7de54nJTkqPpwpjRy8BJjYCnoKHXU5yRvBx6AtePnVZ78jLjUaNBYdUVL5d?cluster=devnet)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/469d4f38-3855-4a12-8314-c9d9cf538907)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8400cf4d-9b0e-486d-b39b-6bc5c3cd28ed)

Closing the ticket.
