### ISSUE TITLE
[QA] [Testnet] Cannot register tBTC for transaction Solana -> Sei

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1246]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.0000001 tBTC from Solana (Phantom) to Sei (Leap)
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in warning "This token is not registered..."
3. Select Solana as source chain and connect Phantom wallet
4. Select tBTC asset (contract 6DNSN2BJsaPFdFFc1zP37kkeNe4Usc1Sqkzr9C9vPWcU)
5. Select Sei and connect Leap wallet
6. Click "Attest" button

Errors:
`failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870`

```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870
    at ni.sendEncodedTransaction (connection.ts:5054:13)
    at async ni.sendRawTransaction (connection.ts:5017:5)
    at async ien (solana.ts:20:9)
    at async useHandleAttest.tsx:367:11

```

![Screenshot 2023-11-17 at 19 21 05](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/621aed64-29eb-482e-8f0f-1e989b1f725d)

## What is the expected/desired behavior
Token is registered.

**Comment by AigaD** [comment]
Closing this and linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1248 token registration shows as success, but when returning to the transaction user is again asked to register the asset.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/855a866a-d2af-4736-9c61-90cd505a95f7
