### ISSUE TITLE
[QA] [Mainnet] Cannot register tBTC for transaction Arbitrum -> Celo

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1247]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.0000001 tBTC from Arbitrum (Metamask) to Celo (Metamask)
2. Click [register](https://www.portalbridge.com/#/register) link in warning "This token is not registered.."
3. Select Arbitrum as source chain and connect Metamask wallet
4. Select tBTC asset (contract 0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40)
5. Select Celo asset and connect Metamask wallet
6. Complete Step 3 "Send attestation"
7. Complete Step 4 "Create wrapped token"
8. Refresh https://wormhole-connect-mainnet.netlify.app/ page
9. Prepare to send 0.0000001 tBTC from Arbitrum (Metamask) to Celo (Metamask)
10. Observe if token registration warning is shown

Actual result: Warning "This token is not registered, you must [register](https://www.portalbridge.com/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown when token is already registered.

Notes:
* Link to Arbiscan in Step 1: [Arbiscan](https://arbiscan.io/token/0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40)
* Link to Arbiscan in Step 3: [Arbiscan](https://arbiscan.io/tx/0xf6a0ba7e5f341fc77dfa683e0d151ef3fc5d543726a6447f32c652a262c00dc9)
* Link to Celo explorer in Step 4: [Celo explorer](https://explorer.celo.org/mainnet/tx/0x8053d2ab8a1ff45e5e4b69e585ff0688210d741cdafb5b3bc80e0de5b9ac664b)
 
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c15c9794-d7c2-4fe7-872b-e4e53de39a9e)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/699e5f10-c5cc-4923-89aa-c288a4935056)

## What is the expected/desired behavior
Token is successfully registered. Warning to register token is not shown when token is registered.

**Comment by aadam-10** [comment]
The Ethereum 'flavor' of tBTC needs to be registered instead of the Arbitrum one because of the way tBTC works. We'll register it and let you know once it's ready to re-test.

**Comment by kev1n-peters** [comment]
Ethereum tBTC has been registered on Celo: https://explorer.celo.org/mainnet/tx/0x1b91d4507b6b71e2f28dfd2671d3e1bf83a1f4e1263ccc2b3ad9d6009d7e861d

**Comment by tsadovska** [comment]
Thank you! Also rechecked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] that tBTC transfer from Arbitrum (Metamask) to Celo (Metamask) is successful. 

Send from tx: [Arbiscan](https://arbiscan.io/tx/0x14fe7d3e2c37460a7a2046bc5ff2c8ddaa322a661a1bb355b09316773ba52a2a)
Send to tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0xee55ce5f5cf1960918ad5f6f74f5150ee8483bba3f2932f6f8bc10fcc91daeab)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c728af4f-4374-4da2-8d85-1043d8413868)

Ticket is closed.
