### ISSUE TITLE
[QA] Cannot register USDC for transaction Solana -> Base Goerli

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1249]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 USDC (Solana) from Solana (Phantom) to Base Goerli (Metamask)
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in warning "This token is not registered..."
3. Select Solana network and connect Phantom wallet 
4. Select asset 4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU
5. Select Base Goerli and connect Metamask wallet
6. Click "Attest" button

Error:
```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0xbc4
    at ni.sendEncodedTransaction (connection.ts:5054:13)
    at async ni.sendRawTransaction (connection.ts:5017:5)
    at async ien (solana.ts:20:9)
    at async useHandleAttest.tsx:367:11
```

![Screenshot 2023-11-21 at 15 38 36](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dff56ee4-7351-456a-b591-162bdb764678)

## What is the expected/desired behavior
USDC is successfully registered.

**Comment by AigaD** [comment]
Closing, no longer reproduced. USDC token is registered for transaction Solana (Phantom) to Base Goerli (Metamask)
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

Uploading Screen Recording 2024-01-23 at 10.17.50.mov…
