### ISSUE TITLE
[Design] UI/UX refresh for Connect Widget

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1254]
**WIP**
Goal for this ticket is to determine changes we will make to the connect widget. Categorically, we can split this up into two pieces: 1) Connect Widget changes and 2) Portal Bridge specific changes

**Goals**

1. Lightweight design system for connect 
2. connect widget specific changes
3. portal bridge specific changes

**Comment by Gpluv** [comment]
1. Lightweight design system for connect (DONE) @mliu-xlabs 
https://www.figma.com/file/lxWryHZnWh99VvGTbqgfDN/Portal-Token-Bridge---Connet?type=design&node-id=342-77&mode=design

**Comment by mliu-xlabs** [comment]
@Gpluv let's make sure that any changes that we make to the connect specific design is also coherent / makes sense for the widget version of connect as well.
