### ISSUE TITLE
[QA] [Testnet] Cannot register asset with Spika wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1256]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send USDC (Goerli) from Goerli (Metamask) to Aptos (Spika)
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in warning "This token is not registered.."
3. Select Ethereum (Goerli) network and connect Metamask wallet
4. Select USDC asset with contract 0x07865c6E87B9F70255377e024ace6630C1Eaa37F
5. Select Aptos network in Step 2 "Target"
6. Connect Spika wallet

Actual result: Warning "Wallet is not connected to Testnet." is shown when Spika wallet is connected to testnet. 
Note: Issue is not reproducible with Martian or Nightly wallet. 

![Screenshot 2023-11-22 at 16 38 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4c619dcc-9eed-4048-b41d-8e98b62f69bd)

## What is the expected/desired behavior
Wallet is successfully connected.

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register [Testnet].

- Link to Etherscan in Step 3 "Send attestation": [Etherscan](https://goerli.etherscan.io/tx/0xea5c1db6261c283954705aed7e31039d58c6df8ac654d84f7a78f75b80a97003). 
- USDC contract 0x07865c6E87B9F70255377e024ace6630C1Eaa37F

![Screenshot 2024-01-04 at 16 29 58](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1591b9c1-eb10-4870-bf35-916894401374)


![Screenshot 2024-01-04 at 16 30 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2c95ae57-1b73-40ff-a50e-579bff3bd02f)

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-foundation.github.io/example-token-bridge-ui/#/register [Testnet] during KLAY asset registration. 

![Screenshot 2024-02-02 at 16 39 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5520d146-cc83-4c31-92c4-3debd8156104)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Tested transaction USDC (0x07865c6E87B9F70255377e024ace6630C1Eaa37F) from Goerli (Metamask) Aptos (Spika), attestation stays on Step 3 "Waiting for Wormhole Network consensus..." and is not moving forward

Attachment:

![Screenshot 2024-03-04 at 09 26 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c4325e1-69aa-4211-a761-a174e2d16380)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9919eab8-76a7-4f70-b8b7-3e3abc19ef97

**Comment by tsadovska** [comment]
Scenario is no longer reproducible, because Goerli network is deprecated. 
Closing the ticket.
