### ISSUE TITLE
[QA]Some wallets are not shown for token registration

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1257]
Preconditions:
Metamask wallet connected at sending From section
Fin wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Steps:
1. Prepare to send 0.1 USDC from Base Goerli (Metamask) to Sei (Fin)
2. Observe that message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on button "register"
4. Enter Source chain Base Goerli
5. Connect Metamask wallet
6. Paste in the USDC contract address ( 0xF175520C52418dfE19C8098071a252da48Cd1C19 )
7. Click Next
8. As target network select Sei
9. Click on Connect
10. Search for Fin wallet

Actual result: Fin wallet is not shown in the wallet list

Expected result: Fin wallet is present

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fac2cb1c-2a95-4446-9222-6d848e38a02f

**Comment by tsadovska** [comment]
Sei network currently not displayed on https://wormhole-connect.netlify.app/ (Connect v2).
Closing the ticket.
