### ISSUE TITLE
Wallet number overlaps network switcher button

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1260]
Tip: test on iPhone SE, if it works there, it'll work everywhere

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/20446095/eae2109b-78fc-461c-8cbd-d84dc41979fb)

**Comment by tsadovska** [comment]
Issue is not reproducible on:
* https://deploy-preview-1264--wormhole-connect.netlify.app/
* https://preview.portalbridge.com/df5df83982/
* https://testnet.portalbridge.com/df5df83982/

Checked with following devices:
* iPhone SE (emulated device)
* iPhone 12 Pro (emulated device)
* Samsung Galaxy S8+ (emulated device)
* iPhone 11 when "Large Accessibility Sizes" and "Zoom" options are enabled
* Samsung Galaxy S20 when font size is set to maximum and screen zoom is set to maximum


![device-2023-11-23-170228](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/52f5183a-c504-4e57-998b-5239cea78657)
