### ISSUE TITLE
[Enhancement] Add support for 1-tx Solana USDC transfers via CCTP

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1262]
## Describe the issue in detail

- Users should be able to perform USDC transfers via 1 transactions (having a relayer automatically redeem the transaction on the destination side)
- Users should be able to receive native gas dropoff via the Circle relayer

This feature depends on the Circle relayer contract interfaces, which we expect to be ready by 12/4.

Target completion date 12/8.

**Comment by aadam-10** [comment]
will be the scope of the usdc LL
