### ISSUE TITLE
[QA] Cannot send SUI from Sui with Nightly wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1265]
## Describe the current behavior in detail
Checked on https://deploy-preview-1263--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome  Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.00001 SUI from Sui (Nightly) to Evmos (Leap)
2. Click "Approve and proceed with transaction" button
3. Approve Nightly wallet notification
4. Observe

Actual result: Action rejected. 
Note: Issue is not reproducible with Sui wallet. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/09aca792-f0ff-42ab-948f-4e3623c4d11b

## What is the expected/desired behavior
Transaction is approved.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the same scenario, when sending 0.00001 SUI from Sui (Nightly) to Evmos (Leap).

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 SUI from [Sui](https://suiexplorer.com/txblock/8gvfy72SBmBcdn4fwgCUf8JzgvzLZiW5gcpBrTC17bkp) (Nightly) to [Evmos](https://www.mintscan.io/evmos/tx/3F722FFDBDA8835A841B24E7598343DAF43B2DE6DE3193428FDE696DB314C337) (Leap) was completed.

Attachment:
<img width="1091" alt="Screenshot 2024-01-22 at 16 18 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fd07fece-5fcf-423d-8ed8-9f6061fdcefa">
