### ISSUE TITLE
[Enhancement] Add support for PYTH token

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1272]
1. Token contract: https://explorer.solana.com/address/HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3
2. Symbol: PYTH
3. Icon: https://pyth.network/token.svg
4. Coingecko id: `pyth-network`

**Comment by KemarTiti** [comment]
LGTM
