### ISSUE TITLE
[QA] Cannot start transaction from Optimism network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1275]
Preconditions:
Metamask wallet connected
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://preview.portalbridge.com/df5df83982/ / https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 0.001 ETH (Optimism) from Optimism to any other network (e.g. Mumbai)
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails to start, reason: `Error: missing revert data in call exception; Transaction reverted without a reason string`

Expected result: Transaction is starting

Attachment:

![Screenshot 2023-11-28 at 13 43 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e0158af3-9ea6-4e17-804a-5d9c4e5a6edb)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7b93520-a605-454f-87fe-45d98b9ec7f8

![Screenshot 2023-11-28 at 13 24 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/99ea15f1-dd52-4ae1-9299-79f21f7d5ed6)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/
Transaction Optimism Goeri -> Moonbase fails, shows error: `Error: call revert exception`
Attachment:
![Screenshot 2023-12-06 at 16 13 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/78e632c3-e617-4c0d-a707-114eb9e7c6e8)

**Comment by tsadovska** [comment]
Issue is reproducible on  https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:

Steps:
1. Select Optimism in From section
2. Select Solana in To section
3. Connect Metamask in From section
4. Connect Phantom in To section
5. Click "Approve and proceed with transaction" button

Actual: Transaction fails. Warning to register token is not shown.

Error in Console:
```
Error: Token not registered
    at SolanaContext.mustGetForeignAsset (/main.js:343:8861)
    at async SolanaContext.getAssociatedTokenAddress (/main.js:353:183485)
    at async getSolanaAssociatedTokenAccount (/main.js:481:20443)
    at async BridgeRoute.send (/main.js:481:21878)
    at async Operator.send (/main.js:483:65983)
    at async Object.sr [as onClick] (/main.js:649:95511)
```

![Screenshot 2024-01-05 at 12 38 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/02a35288-6553-48d3-b406-ecac62c20d4c)

**Comment by tsadovska** [comment]
Cannot start transactions from Optimism on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Loading does not finish after clicking on "Approve and proceed with transaction" button. Error "Sorry, We are unable to locate this TxnHash" is shown on Optimism explorer.

Scenarios - Tested NOK:
* Send 0.001 ETH (Optimism) from Optimism (Metamask) to Polygon (Metamask). Send from tx: [Optimistic etherscan](https://optimistic.etherscan.io/tx/0x5061aa6d92f402cc5ab2e42f5293af0144a5b102ee182538d8fc7248b2e92e49)
* Send 0.001 USDC (Optimism) from Optimism (Metamask) to Moonbeam (Metamask). Send from tx: [Optimistic etherscan](https://optimistic.etherscan.io/tx/0xdb56c6217839b979b98afe3df233a5b7262d3f6f83a1ff3eebd6f6aeef233264)


![Screenshot 2024-01-22 at 13 26 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5c1613b5-0760-465c-8fad-ba880b93a46b)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/70bbfb5f-0f3f-4d73-b9d5-958d1dbb4e85)

**Comment by AigaD** [comment]
Linking to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1526

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.0006 ETH (Optimism) from [Optimism](https://optimistic.etherscan.io/tx/0x876fdc3d6894ab5f89e04fbff2750a6c463b16dd8490e12ec0adcc2d452d3cef) to [Polygon](https://polygonscan.com/tx/0xdc7cd16bc37f2d87562e547eb5e44d1faa31e430c3e8b92d8d1eab98b72b0eae) was completed.
Transaction to check ETH (Optimism) from Optimism to Solana/Moonbeam is blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/1526
Attachment:

<img width="1065" alt="Screenshot 2024-01-23 at 14 46 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d90e24ba-ba95-4e7c-a29b-6accc8a2249d">

**Comment by tsadovska** [comment]
Tested OK:
* Checked ETH (Optimism) transfer from Optimism (MetaMask) to Polygon (MetaMask) (Send from tx: [Optimism Explorer](https://optimistic.etherscan.io/tx/0x749b20fe94700095df5aedf943b2a381c945466989d5112e774577b475cadad7), Send to tx: [Polygonscan](https://polygonscan.com/tx/0x61596f228b9824da5271c944a628db2bc60d41054c8da1f291f60263fb249e52))
* Checked WFTM transfer from Optimism (MetaMask) to Fantom (MetaMask) (Send from tx: [Optimism Explorer](https://optimistic.etherscan.io/tx/0x3f4124baa3de6b6b71eaf2d54719b85d87351b3df0c54c0b8cb8ec26373b9f12), Send to tx: [FTMScan](https://ftmscan.com/tx/0x188d127353e0050a9908c58b75e5c0974ed9f86c7f8952e8a52f5c9fac48b9f0))

Ticket is closed.
