### ISSUE TITLE
[QA]Balance not loading after returning from Resume transaction screen and switching network places

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1282]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://preview.portalbridge.com/df5df83982/ / https://wormhole-connect.netlify.app/# 

Steps:
1. Send 1 AVAX from Fuji to Fantom
2. Click Approve and proceed with transaction
3. Wait until transaction is finished
4. Open Avascan
5. Copy the transaction hash (tx: 0x937d1a45485b0d9f7bf6e897f4b3a830b8ad2ba769a1fab1590352438637f7fc)
6. Go back to Wormhole connect
7. Click on Bridge more assets
8. Then click on Resume transaction
9. Paste in the transaction hash
10. Select Fuji and click Search
11. Wait until transaction is found
12. Click on Bridge more assets
13. Connect any network at sending From section
14. Change Network places
15. Open asset list
16. Observe

Actual result: Balance is not loading when returning from Resume transaction screen and switching network places

Expected result: Balance is loading

Attachment:
![Screenshot 2023-11-29 at 10 12 17](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8586b3b8-e304-480f-ae70-b9d7ccafee11)
![Screenshot 2023-11-29 at 10 11 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0a158625-7d37-4f08-b148-184c6b707eaa)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/46e9e3fc-d11b-4d43-ba26-0787d5d6400f

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1312--wormhole-connect.netlify.app/#

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b1d072d1-6870-4446-9aea-906569b7749f

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Balance not loading after resuming transaction from [Solana](https://explorer.solana.com/tx/4EBRxb94Qerx9gfZZt5STRSzCSUoye1571BJsPvbNZtvhhrAgpgM1mPckYrqLmg55g19una39MNKY1SJZ2QFQXy?cluster=devnet) 4EBRxb94Qerx9gfZZt5STRSzCSUoye1571BJsPvbNZtvhhrAgpgM1mPckYrqLmg55g19una39MNKY1SJZ2QFQXy then retuning to Bridge screen and switching network places

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ca0fea47-9022-49d9-90d3-d5abdda3421a

**Comment by tsadovska** [comment]
Issue is no longer reproducible. 

Checked on https://portalbridge.com/:
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


https://github.com/user-attachments/assets/6e1c8962-969a-4b17-8d53-8b41387dbd73

Closing the ticket.
