### ISSUE TITLE
[QA] Amount in Route section should be right-aligned 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1283]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7.1 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64). Emulated device: Samsung Galaxy S8+.

Steps:
1. Prepare to send 3 AVAX from Fuji (Metamask) to Fantom (Metamask)
2. Observe "Automatic deposit" option in Route section 

![Screenshot 2023-11-29 at 16 23 07](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6b3ff70e-2730-4948-ae45-5f76d4271f5e)

## What is the expected/desired behavior
Amount in "Automatic Deposit" option should be right-aligned.

**Comment by hsnice16** [comment]
Hey, Hi @tsadovska 
If this issue is still open, then can I work on this issue?
It seems like the alignment issue is on other places too
<img width="323" alt="Screenshot 2023-11-30 at 12 36 34 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/56081584/8b6349c1-701e-436e-bbc5-efec5e3d7d4a">

**Comment by AigaD** [comment]
Checked from: https://wormhole-connect.netlify.app/# with macOS Ventura 13.0.1, Chrome Version 119.0.6045.159. Emulated device: iPhone 12 Pro
Alignment issues also noticed for a completed transaction
Attachment:

![Screenshot 2023-11-30 at 08 48 33](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/539e4198-8910-410f-8af7-545dd2fdd501)

**Comment by AigaD** [comment]
Linking issues: https://github.com/wormhole-foundation/wormhole-connect/issues/290

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] with iPhone 11 Pro iOS 16.5.1 and Google Chrome Version 114.0.5735.124.


<img width="317" alt="Screenshot 2023-12-20 at 14 24 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1926c154-22ff-4f8a-84bd-e20bcad90bc9">

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/290

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] when sending 0.00001 ETH (Optimism) from Optimism (Metamask) to Aptos (Martian). 


![Screenshot 2023-12-28 at 20 59 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9a595855-bb3a-42b0-a340-1899abc4af71)

**Comment by AigaD** [comment]
Reproducible from: https://wormhole-connect-mainnet.netlify.app/#
When sending wstETH from Arbitrum to Optimism
Attachment:

![Screenshot 2024-01-12 at 10 30 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a8a09acc-202b-4423-9fbf-61b81cd60030)

**Comment by tsadovska** [comment]
Reproducible from https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending 0.0003 wstETH (Ethereum) from Ethereum (MetaMask) to Optimism (MetaMask). 

![Screenshot 2024-03-19 at 16 34 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/39c14673-0ed4-476d-8aea-5655aa23b6ef)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/8228d00809/#
Reproduced when sending 0.001 wstETH (Optimism) from Optimism to Arbitrum
Attachment:
<img width="683" alt="Screenshot 2024-04-02 at 15 31 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/efcc6c32-0f54-4751-9b0e-6a353921e60d">

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/#
For transaction W (Sepolia) from Sepolia to Arbitrum Sepolia the amount in Preview section is not right-aligned 
Attachment:

<img width="1040" alt="Screenshot 2024-04-15 at 20 16 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1e910e08-7c34-4a10-8302-9d8bc62f80ed">

**Comment by agodlevska** [comment]
Reproducible on https://portalbridge.com/ when sending 0.001 ETH from Ethereum (Metamask) to Optimism (Metamask).
Attachment:
<img width="1440" alt="Screenshot 2024-05-27 at 15 32 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/e361956f-173d-4d00-beb4-9657bd694924">

**Comment by agodlevska** [comment]
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/#/ when sending 0.00014 wstETH from Polygon (Metamask) to Optimism (Metamask).
Attachment:
<img width="1390" alt="Screenshot 2024-05-30 at 12 52 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/9db21f36-4673-41ca-8e8d-f9636946dab5">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ac15114854/ [Mainnet] when sending 0.0000011 osETH from Arbitrum (MetaMask via WalletConnect) to Ethereum (MetaMask via WalletConnect) with NTT Automatic route. Checked with iPhone 11 Pro and Google Chrome 125.0.6422.80.



![Screenshot 2024-06-04 at 14 57 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1a390187-01ef-4871-9068-45a4b2797bf5)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/8b6491733c/ when sending 0.0003 ETH (Base) from Base (Metamask) to Avalanche (Metamask).

Attachment:
<img width="628" alt="Screenshot 2024-06-26 at 11 11 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/fa95aebf-4f7e-4328-ac9e-1b629d2692e6">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] when sending 0.0001 wstETH from Ethereum (MetaMask) to BSC (MetaMask). 


![Screenshot 2024-06-28 at 14 55 25](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/66294009-6696-44cc-93a0-9bcfd11472aa)

**Comment by tsadovska** [comment]
Issue is no longer reproducible after redesign. 

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Closing the ticket.
