### ISSUE TITLE
[UI] Show USD values for transfers and fees

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1284]
**User Story**
As a user, when I am transferring non-USD assets (SOL, AVAX, ETH, etc), I want to also see the USD equivalent in the display so I know what the relative value of my assets and associated fees are.

**Acceptance Criteria**
- show the relative USD value for both source and destination assets
- show the relative USD value for gas fee

**Design Option:

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/475f6ba1-d6f0-4956-91f1-84d477502c32)

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/1dc66617-82d2-47bf-9bf7-1e9595a67fff)

**Competitors**

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/ee1ef743-4844-438e-89ee-9e1f06df8cf6)

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/48c43b39-ca58-4b5e-b865-f87d0d0f4cf5)

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/df79bb18-67f0-4739-b63b-3fbd885a0802)

**Comment by aadam-10** [comment]
closing this in favor of https://github.com/wormhole-foundation/wormhole-connect/issues/1436
