### ISSUE TITLE
[Enhancement] Integrator-configurable arbitrary token bridging

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1287]
- Enable integrators to add tokens that they want to support in Connect. 
- In this iteration these tokens should use the 2-tx route.
- There needs to be validation to disallow duplicate tokens (among other things)

**Comment by rhlsthrm** [comment]
Subscribing to follow. Please reach out if you need beta testers, we are willing to pilot this feature.

**Comment by tradefortendies** [comment]
Subscribing to follow.

**Comment by tsadovska** [comment]
Results of BONK transactions on https://preview.portalbridge.com/7246284e5d/ [Mainnet]: 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d67111d-02c5-4f52-8d64-d956f0ffc1f0)
