### ISSUE TITLE
[Enhancement] Allow user to select token without connecting a wallet

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1288]
Users should be able to select tokens and fill out the transfer amounts without connecting a wallet first, to see what routes are available and what the quotes might be.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129
Attachment:
![Screenshot 2023-12-22 at 16 31 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a0dc5069-8890-4261-ba93-b39a0084a158)

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/4adb101c39/ [Mainnet] with Ethereum, BSC, Polygon, Avalanche, Fantom, Celo, Moonbeam, Solana, Sui, Aptos, Base, Osmosis, Arbitrum, Optimism, Evmos, Kujira.
