### ISSUE TITLE
[QA] [Testnet] Transaction from Solana fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1289]
Preconditions:
Solflare wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://testnet.portalbridge.com/df5df83982/# / https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SOL from Solana to BSC
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, "Error with transfer, please try again", error in console: `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x7d0
    at Y8.solana.solflare.sendTransaction`

Expected result: Transaction is taken to next screen and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b5aeb04-103b-487f-9fdc-fcdd782f60b7

**Comment by hsnice16** [comment]
Facing this issue with the Create account as well. 
`WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found`

<img width="1389" alt="Screenshot 2023-12-06 at 7 42 30 PM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/56081584/133efab6-b98d-42cb-97d4-32f74cd5288c">

**Comment by AigaD** [comment]
Linking issue with creating associated account to this ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/770

**Comment by hsnice16** [comment]
Relevant Issue in `solana-labs` - https://github.com/solana-labs/wallet-adapter/issues/858

**Comment by hsnice16** [comment]
@aadam-10 I would like to raise a PR for this issue. The issue is happening because of the incorrect Solana testnet RPC here - https://github.com/wormhole-foundation/wormhole-connect/blob/development/sdk/src/config/TESTNET.ts#L306

**Comment by AigaD** [comment]
Tested OK, closing the ticket.
Tested from: https://wormhole-connect.netlify.app/#
Transaction from [Solana](https://explorer.solana.com/tx/1XTjNHawGdrBJMvZNqcfSxaMmPrdEVSBfJDCibqGjuUZU9MtCqqMKDCW8znweNLYG6zGsYHUmS3ajntYRQZRxxp?cluster=devnet) network was completed.
Attachment:

![Screenshot 2023-12-08 at 13 21 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f5052484-3c57-4bba-b9d9-576384be2d9a)
