### ISSUE TITLE
[QA]Native gas section value does not revert back to initial state when changing network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1290]
Preconditions:
Solflare wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: 
https://testnet.portalbridge.com/df5df83982/#
https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SOL from Solana to BSC
2. Change the position of Native gas
3. Change the network at sending To section to a different network where wallet would disconnect (e.g. SUI)
4. Connect wallet at sending To section
5. Observe the Native gas section

Actual result: Native gas section does not revert to initial state, instead some value is left selected

Expected result: Native gas section is reverted to its initial state

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/76795d04-9f8b-4b3e-93ae-04d36a0d4fa8

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect-mainnet.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d46ba835-fb85-4d0e-94cb-47849bb4ae31

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1561--wormhole-connect-mainnet.netlify.app/
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb88c4e4-88a7-4fac-b7d7-51b96b46a103

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Native gas slider position does not revert back to initial state after changing network

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c692c24-19a0-4be4-9ebf-e76d63e73396

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Native gas slider position does not revert back to initial state after changing network. 

Attachment:

https://github.com/user-attachments/assets/5f75ff2d-7aa3-4079-a8b1-8f27a9ca4ff8

**Comment by tsadovska** [comment]
Issue is no longer reproducible after redesign. Checked on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziYAZngA2DaGAC%2BFCDyqxBmANqUIAOiMARAKIAxAIIBVADIAVAPoAlAPLX7pgMpqIYALJ4AJ54kM6ImtBkYPpgRgaQsLDhkQwAFKB%2BfrCIqNCQDHSxWVYAcvau%2Fo7WXsYAwrrFWWCZzW0AxkyEkJhYprBM0AJUOORNbfiQeJLIvQAMAB7QAEJiddAAnHgbAIwAzGIbACxzc6amAOwArNDSezvrABwARmJ7R0cAbABMxnM7eB27R2YzabRyeR62EWljmz0enw2u3aPx2Lz2n2BYh2G2MRzw302pmec3apgxc0%2BKyOj1BYKysGQoQY7WgBAAbkNGvS2q0ec08GIxAIhPMFlcrtILo9vnM9lcLlYdhdLDtTHVnjTTBsrrirqZPnsLs9zOYdZ8xJ9zHT%2BQyggAHaC9JDIHAsOTQG221TjZoAXV89J9%2FL5PM63V65lCOVGgZ5k2mXOhC0%2BjzEy2%2B0jmV0sBLEFwuZmkG0eO2kYm%2Bz2ge2%2Bn0%2B%2BxO7Q23xb5mWXvpEPyYu%2B5guez2cx1y0ec1hR2eexec2MO1JdUejyOV2%2B%2BIOQ%2FhGLwHbBjOZrI5Sb0tr8oZPguFgkKyZeRwuWcJF2gsuVR3aF0%2BeGLc8F7TmgsePAJzlI5MzfHd%2BVgB0nWwF03UQD0ILBYNbQDX0IBQto0PpWxxEQRx4AYWBTHsAAJbkeTPMFwyIXp%2BkGYZY3QvwExmMVnmOQCNinb4LktQCZXMT4rn2SxsWlDZPiOYwgMee9n2WYwNiQhlcm7ZN7z2DY6iuUtzF1K5liuPZ2iudpnhxZ4%2FknaQ00sTFuP1b46jwOYVOyJkCgPTlZjAY8TxaZi2gvEVrywGEdksOo6h2aAqTEPAMz06BXl2ckRKuIc9nMHYzD074zLcuMTygx1nRQeDEOKnlMJ5bCauqrIqI6LpaOwZYWXciBWKTcKUxLHZ9NRREHmWaRyWMMRjBXI4xEuOcP2eC4NnMMc5l42lGuaLsoT62tTOgf4ZorA1vlHSwaXMb5TLmaQhOMaAnxXbV6weLqwD3Ly2R8iiT2ankQqvdjqz7Q7Uwub5TDmMQhLqYxFXMeVlguPAgOWCyPk%2BeokQRd67TK2CKvdT0traWr6XqoMtsp5phF%2BsF%2FqyGjdq8BDQm3UmWPZtjsHKWBc0QYwACkmDyUjoDwAA1axSMgIImHgZ5OFKSxSk%2BYReGWe1SNQUjlnsFF83ZWwAGl3p23pHiuSXlnMABFAAtOoNnsB3UFke1YGWYQACt2WseALgATWeB2faCFd7JwH3YE4ABxH2iLtywcDt83PJZb6jyC08c6yQHRV5%2Bx%2BbwQWRbFiXpdl%2BXFeV1X1c17Xdf1w2LmNs3OfBaDytdYm8ZUTuwBp%2BkAEcqEQLRfKwUoR8tAANEfLEeWxngYOoqDjx5%2FFsYRhCoTgESuUpJc%2BH3nB2fxnjn6ATYWPFSNN4X3PJ5pGb8Zm6IGIZoBGd6eqnxYf4IbLEiqYO4GJoCTWgLqcckkkRgKONAR4UY9THAuptHOFtkzLFulGUcpxFxUgVOYBEQoVxSQ4rpSs3wxJyWeJWXY6d9xZ18v5P6ec%2FAFzCosYwzwJRHGbPmHEM4djPDwKYR4UVnhQy0jsB4RxySXFAuDUk%2FcIClRglgOCfdB4YUHsPZoL8mo5w%2FtgSwyBngEEZL%2FQe%2F8xTGQHGIMc7R7L4mXGOIUVpoB9ixljfY1w%2By1jqMsGkRxzZqV2osHBd08D4LmIQ6BipSFiHIROHUMp6G0ONAwkEg9PqZ0PKwjhb9gpClCmKWcsTLDLERIddadYkHI12ICQydQ7wiSODsYylhMrLjwJ8NRH1u6E17ghEmHCjH%2Bk5pMiAJSwCmKwK4T2BAcAEAYExE8djkwAiODlPAy1brfGytIDiBZviSUxDUxGFo6iWl0nKPY0B9jhMhGKaJeDTjxIRIkkhFoUm1jSVQzJYg6E5KYV9Qp9MQwcIgFwsUGwrIvGNCuC4dQLpxX7I8doilEowxEnUFsXxPjXE%2BHMfsYhBkaJ7pVcZAUB45wMVkGZgUTwLOWHgRQf9ua9UWA49clgXFSSAplMSlpzDeI%2FMYPxRoriBM%2BME0JLz1J9XebEz5CTiHJNSZQjJNCQXZI4rkzBGdvLZzpXM%2FOZSgbJkqZImpGw6m1ipI8JpAIunLDadcHYnTum9KuP0ylwytFEzGf3ZlEBGV%2BEmQY2qygACUvg0KUCoIoZw0AxCCAILwKE1ioggEoDtNeiBIDSCzUULIhFiJkVXu0ctzQ8hBGdEREipEa07gYEEHAzwEJNqraRHcUxYCHjqK1XaHV2g7h2mwMQdaWoRnap1LacLkz7RuEdVcJ0fjnUutdTKd0saPWgZDSSci6g7hfgQdoxbehMCSPaQoAB6B9HLFCwAYAYK9RBJDtFQIgD9iAcAPs%2FQUB9KzEwMAfWiR47wH1EVCAlZAYgH2VpbQYe0kBeA7mA3HaAP7EDTudEye0joxAAFoiJwCYFhhCKBegAGI9iWEsNla01UM3tDAwoTAaI4y1WEAwNmUxZ1%2BAbb0fjgmOZNA7V2nt2BhADrwEOzkI751YFZnIdmk6IkEZZdRUdvR1OaaXVawuWArY23tk7F2bsPZe19v7QOIcw4RxoZ8aOscE5JxTmnaqF6r27VvbAe96An0vrgO%2B4D37f3%2FsA8BiDYHJAQflPEi4sHYDwbwIh5DAHkDE0cHIPg%2BFpBUDkHIRwV6CvIEcMgXgzxHCylOPaBYjgIbEYII4E5H5PztCtngNDGGAD8yp4mpkeDqMJ1VsO4d%2FTp4NoyqpNHY5x68nxeNxmEJR7%2BIxhMQFE3JzbjF22du7XIMTCmlPQBU21PoX9DvVSnTO3Tc7rv0S2xssEy6VW4LVQQ75mq%2FnavSdQrJ9DDXnuqpe692BAvBdC0IcL%2F6v3Tb%2FVe2LiAiDxfwIlh9yW5JpYy1lpAOBctjPy4VjrJWysVZQNV2r9XPlNZa98NrHWlp1jwD1%2F1%2FXeBDYuCNxc43qNEBw3h2b2jQ1sdw8t7jjw1uxGEJlyx1icA7bAHtrACuLFWOQDYqTx3ZMa%2FO8O%2FTZitfK605CHT%2F0FnmKVzr97pTLymaid9uJGqkkA4BTq4H%2BrQeMN8xD%2FzN672PuffDt9iOMPI5i0B9HIGEuCBx5lPHcHIAIaQ0TknHoye8CK5T8rNGqs1bqw1uYjPWv2na519nnO%2BvoZ58NhEAurgTaaFN0Xj25s0p3Et%2FAXGwA8diHxxAyzVnrNV%2Br4QI%2Bh1j4d34aTJ2zvVUHcb1TSyZ9rLn%2Bo7Tj3rcm8WaPzfSFPsu5iW7v7HuyFe6B8C0FYOA9NEhwFkPIWw%2Bvoi3HqLKOAOx4x6BrHieuOqWqe6e2WxOeWBWueFOpWBelWtOJeDOzWFeVebO3WvW3OvO%2FOY2LeQukAIuM2ne4uC2bQve8g14g%2BTK62YiigE%2B0Ajacm1BtKzQC%2BBu8my%2Bimq%2B127KnK92O%2BquEAbKHKTBju5S2Cru6qF%2BvyV%2BFCN%2Beqd%2B%2FuTQfmUOWAMOoeYWEekW0eqOv%2B8eABSWyewB6WaemWGeOWEB5OxWMB1ORedOpe5ezOlerOXWHO6B9emBTe2BreHQce%2BB%2BGhBIaxBzQpB%2FeFBUavgPoygAA3CAEAA%3D). 


https://github.com/user-attachments/assets/fe599826-12e2-4bf8-9627-1d8bbcd7c608

Closing the ticket.
