### ISSUE TITLE
[QA][Mainnet] Transaction fields are not shown after switching network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1291]
Preconditions:
Solflare wallet connected at sending From section
Sui wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.1 SOL from Solana to SUI
2. Add some Native gas value
3. Change the SUI network to any Metamask network (e.g. Fantom)
4. Connect Metamask wallet
5. Observe

Actual result: Fields - Route, Native gas, Preview and Approve button are not shown

Expected result: Fields are shown user is able to continue with transaction

Comments: Linking to #868 similar to field not shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5af1fd31-500b-4e21-b4b8-b0f68a9593cf

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/7102d8ccad/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1394df80-c5cf-4cbd-bd6a-2628c9a88792

**Comment by tsadovska** [comment]
Issue is reproducible on  https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet] with following scenario:

1. Prepare to send 0.04 AVAX from Avalanche (Metamask) to Polygon (Metamask)
2. Move slider to right most position
3. Change network to Moonbeam


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de37184f-c8b7-47f4-850a-d09b7af7f773

**Comment by AigaD** [comment]
Reproduced also from testnet: https://wormhole-connect.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/16903f7e-2fe3-4929-8918-2148b4e1a78b

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Issue is still reproducible. 
After click on the manual route option when network is changed - everything appears and works.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/799f69e5-ef42-4842-b50f-4032cfcc5991

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 

https://github.com/user-attachments/assets/d6bdfaf2-8214-4dbf-bff1-bbbb9aa0f924

Closing the ticket.
