### ISSUE TITLE
[QA] Checksummed wallet address is not shown, font seems different

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1294]
Preconditions: 
Metamask wallet connected at sending From section
Rise wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Firefox Version 115.0

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 1 AVAX from Fuji to Aptos
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe the wallet addresses how they are written at the end of transaction

Actual result: Aptos Rise wallet address is shown differently than Metamask address, the "x" is showed higher up, also Rise wallet is not shown as checksummed address

Expected result: The address is shown as checksummed and using the same style

Attachment:
Firefox browser:

![Screenshot 2023-12-04 at 14 20 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2741b4a8-1908-41ae-a228-3fdc7ab6421c)

Chrome browser:
![Screenshot 2023-12-04 at 14 22 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cd10d942-4c11-4fea-86ec-b5dd81f0eef8)

**Comment by tsadovska** [comment]
Checked on https://wormhole-connect.netlify.app/ [Testnet] with Firefox 122.0. 
* WAVAX transfer from [Fuji](https://testnet.avascan.info/blockchain/c/tx/0x0f6142de7aa2e84ec27454682317a18b6d3843345e37df44611c0db8034806ca) (MetaMask thought WalletConnect) to [Aptos](https://explorer.aptoslabs.com/txn/0x7813805215c89eb9c6a16fd9d145b56b38aaf7488a64219f28d902ffb7eca277?network=testnet) (Rise) was successful. 
* The same font is used in "Send from" and "Send to" sections

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/099b04bd-eb64-4a52-92c2-67f2fb7abcb3)


Ticket is closed.
