### ISSUE TITLE
[feat] Add Klaytn as a supported network to Wormhole Connect

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1296]
## Description and context
From [steve-jeon-KF](https://github.com/steve-jeon-KF) (Klaytn Foundation)

Add Klaytn as a supported chain to Wormhole Connect. The wKLAY and KLAY tokens should support the 2trx Wormhole Token Bridge route in this iteration.

- Chain name: Klaytn
- Token symbol: wKLAY, KLAY
- RPC: https://rpc.ankr.com/klaytn
- Explorer: https://klaytnscope.com/

## Definition of done

- Klaytn appears in the list of available networks
- 2trx Wormhole Token Bridge transfers work

**Comment by mliu-xlabs** [comment]
@aadam-10 so this made more sense pre-migration, however it looks like Klaytn is not supported by connect in production, this should be changed to support Klaytn in Connect natively. Should we prioritize this then? cc @yuli-ferna

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Tested OK.
Klaytn Network is shown, KLAY token is present in the asset list. 
Native Klaytn token is indicated as - KLAY, wrapped Klaytn token is indicated as - wKLAY
Two transaction route is present for transactions, except to Cosmos chains where Automatic (Cosmo Gateway) is available.
Attachment:
![Screenshot 2024-02-08 at 17 15 11](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/45576ac2-47f5-489e-bbb9-efc8f5603b97)
![Screenshot 2024-02-08 at 17 11 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a22c632a-8f5a-411a-b82a-75b9077c9458)
![Screenshot 2024-02-08 at 17 11 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3900bd2-5db2-48f5-9b7f-993f7d1c6aad)
