### ISSUE TITLE
[QA] Transaction to Cosmos chains not moving past Step 2

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1297]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> User is stuck on Step 2, transaction does not move forward for more than 1hour10min
> 
> ### Expected Behavior
> Transaction is completed
> 
> ### Steps To Reproduce
> 1. Prepare to send 0.01 MATIC from Polygon to Osmosis
> 2. Click Approve and proceed with transaction
> 3. Observe
> 
> ### Environment
> ```
> Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159
> 
> Tested from: https://preview.portalbridge.com/df5df83982/
> 
> Wallet: Metamask and Leap wallet
> ```
> 
> ### Anything else?
> Transaction 0.01 AVAX from [Avalanche](https://avascan.info/blockchain/c/tx/0xbc03860313e4cad61e9afe0a7b36caf196004bf1f2b9d4fb001b373c129a14d8) to Evmos
> 
> [Polygon scan](https://polygonscan.com/tx/0xebc98450cb9c7b56f787dc7ba012e67735eb780d382a392b06bde73041acecbd)
> 
> ![Screenshot 2023-11-24 at 12 09 03](https://private-user-images.githubusercontent.com/91047061/285425964-559c986a-754f-485c-a67c-d38797ee86a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjU2MjksIm5iZiI6MTcwMTcyNTMyOSwicGF0aCI6Ii85MTA0NzA2MS8yODU0MjU5NjQtNTU5Yzk4NmEtNzU0Zi00ODVjLWE2N2MtZDM4Nzk3ZWU4NmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDIxMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOWFjMjg1YmU0ZjMyNTc2ZDI1ZTljZjljNzM2OGU5YTI5YTgzZTRmYTA4Mjk1ZDE4NjBhMjgxMmE1NDM4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t88S7UqQMHXo6kfSWORVQQdnl5Cyp93bg_sxFT-A--c)

**Comment by AigaD** [comment]
Linking issues: https://github.com/wormhole-foundation/wormhole-connect/issues/1147 , https://github.com/wormhole-foundation/wormhole-connect/issues/1158 , https://github.com/wormhole-foundation/wormhole-connect/issues/1148 , https://github.com/wormhole-foundation/wormhole-connect/issues/1146

**Comment by hsnice16** [comment]
Hey @kev1n-peters, why have we kept the wormchain RPC endpoint empty string [here](https://github.com/wormhole-foundation/wormhole-connect/blob/development/sdk/src/config/TESTNET.ts#L314)?

It throws this issue at this [check](https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/routes/cosmosGateway/utils/client.ts#L30) for RPC. And because of this, it's not moving past step 2.
```
could not fetch redeem event:
Error: 3104 RPC not configured
```

cc: @aadam-10

**Comment by hsnice16** [comment]
Hey, Sorry @aadam-10 to discuss this here
But, I have sent you an email (on adam@wormhole.foundation and hello@wormhole.foundation). Can you please check that?

Thanks a lot!

p.s. I will delete this comment, once you will tick on it. Or, if you can and want to delete it, you can do that also.

**Comment by hsnice16** [comment]
Hey, Hi @aadam-10  
Hoping you got the above message!
Let me know if you want me to delete that comment.

**Comment by aadam-10** [comment]
thank you @hsnice16 , received! we'll evaluate internally

**Comment by hsnice16** [comment]
Thanks a lot!
I am deleting the comments.

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/
Transaction tBTC from Aptos (Nightly) to Evmos (Leap) is not moving past Step 2 for approximately 40min
Transaction from [Aptos](https://explorer.aptoslabs.com/txn/0x94604e35284113d04e69c822ac854b31948373f5c4ba254d518390b551acb643?network=mainnet) (Nightly) to Osmosis also not moving further than Step 2

Attachment:
![Screenshot 2024-01-03 at 10 02 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/914db5f1-8b4e-469c-8916-427d2c86e5cb)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending asset to Kujira with Threshold route. 

Scenarios - Tested NOK:
* Send 0.000001 tBTC from Aptos (Spika) to Kujira (Keplr), send from tx: [Aptos explorer](https://explorer.aptoslabs.com/txn/0x7658695c5b4af5189d9b4dd239c5f4b7a88146428bf6a8f27759ebe48b10ca22?network=mainnet)
* Send 0.000001 tBTC from Aptos (Martian) to Kujira (Keplr), send from tx: [Aptos explorer](https://explorer.aptoslabs.com/txn/0xd63715410fbc0b1cf29cf46af772589e9fca7cfe02263e325807ffdc61a79f9d?network=mainnet)

Issue is not reproducible when sending asset with Cosmos Gateway/ Wormhole route.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
Transaction [Sui](https://suiexplorer.com/txblock/HvFirFKBQSjjRohvrawgKktUnLSr7JWMQ9htPBm1mywV?network=testnet) (Sui) to Osmosis (Leap) is not moving further than Step 2
Attachment:
![Screenshot 2024-01-08 at 13 37 30](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a0b3409-722c-40ca-9590-092c0f6888de)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Transaction tBTC from [Base](https://basescan.org/tx/0x194d30ca88dd5de46e2371bb69e88ab1dfe6fda580e8d99d5bffed5477f35f5d) (Metamask) to Osmosis (Leap) is not moving past Step 2 for ore than 16h

Attachment:

![Screenshot 2024-01-10 at 09 02 04](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3dbedc0f-2691-41e0-bb69-eed91655ecf3)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/bf7b5b43a8/#
Tested OK
Transactions to Cosmos chains (Osmosis, Evmos, Kujira) are completed

Attachment:
![Screenshot 2024-01-11 at 16 30 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7397d204-16f6-4148-9719-2789af2cbbb3)

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
* Transactions to Evmos and Osmosis are finished successfully.
Send FTM from Fantom (Metamask) to Evmos (Leap): [FTMScan](https://ftmscan.com/tx/0x0ca733f47987828d387382adf93277e1f3ed6f5bb39123fe9476242e9d734c2d), [Mintscan](https://www.mintscan.io/evmos/tx/EDEFD56F3DA58F979276DD43F66CC0697B1376B87CC85AFBC5F7A4048F2196D0)
Send CELO from Celo (Metamask) to Osmosis (Leap): [Celo explorer](https://explorer.celo.org/mainnet/tx/0x3c288cc324a7fb4dd1a7069777abb5972fa265e4ebda40bec4573c459f268279), [Osmosis](https://www.mintscan.io/osmosis/transactions/0067C4CFD5D4B196BF5C7D0419944054233A0EC7A6EBB274C72B840D740B6686)
* Transactions to Kujira are stuck on Step 2.
New ticket: #1501

Ticket is closed.
