### ISSUE TITLE
[Enhancemenet] Show automatic redemption route even if insufficient funds are available

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1299]
- Show routes for both 1tx automatic redeems and 2tx manual redeems, with the 1tx automatic redeem grayed out with a tooltip or warning if the transferred amount is below the minimum amount. E.g. "Not enough funds on the source chain for automatic redemption" or "X more <token> is needed on the source chain for automatic redemption"
- Cosmos routes: do not show 2tx options as currently
- If a CCTP route is available between the source and the destination, do not show the wormhole token bridge route to avoid liquidity fragmentation.

**Comment by yuli-ferna** [comment]
@aadam-10 @mliu-xlabs I have a question here, in many cases, to see this improvement the steps are the following:

1. Select network/asset and put an amount tower than the minimum
2. Select manual claim transfer
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/fbf48788-5001-405d-960d-0f4c216faf70)

3. See the disabled one transfer option
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/0e0201f3-8376-4675-b0c3-14abb5b95bac)


My question is: Is this behavior what we need? Or should we remove the warning?

**Comment by tsadovska** [comment]
Build: https://preview.portalbridge.com/4adb101c39/ [Mainnet].

1) Task: Show routes for both 1tx automatic redeems and 2tx manual redeems, with the 1tx automatic redeem grayed out with a tooltip or warning if the transferred amount is below the minimum amount. E.g. "Not enough funds on the source chain for automatic redemption" or "X more is needed on the source chain for automatic redemption" - Tested OK


<img width="1053" alt="Screenshot 2023-12-22 at 18 38 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2cb172e0-23d8-48b5-a2c4-6e6be4301f7b">

2) Cosmos routes: do not show 2tx options as currently - Tested OK, only "Cosmos Gateway Receive tokens automatically" option is shown between Osmosis, Evmos, Kujira chains. 


<img width="477" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d15571c5-369f-40b4-afc6-6118fc40df73">

3) If a CCTP route is available between the source and the destination, do not show the wormhole token bridge route to avoid liquidity fragmentation. - Tested OK, only Circle routes are available between Ethereum, Polygon, Avalanche, Arbitrum and Optimism networks. 

<img width="493" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d52690ab-dc23-4ec6-85a4-3479e49309f9">
