### ISSUE TITLE
[QA] Exodus wallet pop-up is shown instead of the one being selected at "Connect wallet"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1300]
Preconditions:
Wallets are not connected
Exodus and Metamask wallets available in extension

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Click on Connect wallet
2. Select Metamask
3. Observe

Actual result: Exodus wallet pop-up window is shown instead of Metamask

Expected result: Metamask pop-up window is shown when clicking on it at Connect wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/74b6e38e-71c8-4a01-9a69-dc52f1bef626

**Comment by tsadovska** [comment]
"Prioritize Exodus" option is enabled by default in Exodus extension. Metamask window appears when priotization option is disabled. 

Ticket is closed.
