### ISSUE TITLE
[Enhance] Improve governor limit messaging

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1305]
**User Story**
When I attempt to bridge a token amount that is greater than the governor limit, I want to be clearly notified what will happen when I reach the governor limit so that I can make a decision if I want to move forward with the transaction.

**Acceptance Criteria**
- **Small Transactions** When the transaction exceeds the governor limit, prompt the user with the following message modal: 

> "This transaction will take up to 24 hours to complete. This transaction will take up to 24 hours to process as Wormhole has reached the daily limit for `sourceBlockchain.` This is a normal and temporary security feature by the Wormhole network. [Learn more](https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0007_governor.md) about this temporary security measure.

-- option to Cancel (closes the modal)
-- option to continue the transaction
- **Large Amount** When the large amount, prompt the following message modal: 
> "This transaction requires 24 hours to complete. This transaction will take 24 hours to process, as it exceeds the Wormhole network's temporary transaction limit of `$` on `Solana` for security reasons. You may also split the transaction into smaller transactions less than `$`<governor limit> each to avoid the  24 hour security delay.  [Learn more](https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0007_governor.md) about this is a temporary security measure.

-- option to cancel (closes the modal)
-- option to continue the transaction
blocked by
- [ ] https://github.com/XLabs/portal-bridge-ui-issues/issues/17

**Comment by sebastianscatularo** [comment]
<img width="744" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/727718f7-01c7-47a7-b266-e3b34af32a4d">

Currently exist a warning message, the idea would be to prompt a stop-action modal, with a message and informational links at the same time the routing information appears if the current transaction size exceeds the notional limits

**Comment by Gpluv** [comment]
The design is here: https://www.figma.com/file/lxWryHZnWh99VvGTbqgfDN/Portal-Token-Bridge---Connet?type=design&node-id=441-2566&mode=design&t=hCMrfaPRnY7fmp3W-4

**Comment by yuli-ferna** [comment]
In the transfer limited warning component we have a third case (EXCEEDS_REMAINING_NOTIONAL), an example of the message is: "This transfer's estimated notional value may exceed the remaining notional value available for transfers on solana (0) and may be subject to a delay." 
Asking @mliu-xlabs  he says that this case would fall under "small amount" messaging.
