### ISSUE TITLE
Design UI/UX

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1308]
Suggestions for the warning to display with Call to Actions

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/5112c704-a38c-4d0d-8d8a-0d1409b649ec)

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/c240740c-bf30-4edf-98d9-a31ff948c106)

**Comment by sebastianscatularo** [comment]
move to https://github.com/XLabs/portal-bridge-ui-issues/issues/17

**Comment by Gpluv** [comment]
The design is here: https://www.figma.com/file/lxWryHZnWh99VvGTbqgfDN/Portal-Token-Bridge---Connet?type=design&node-id=441-2566&mode=design&t=hCMrfaPRnY7fmp3W-4
@sebastianscatularo
