### ISSUE TITLE
[QA] Cannot connect Blocto wallet 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1313]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]  with macOS 12.7.1 and Google Chrome Version 120.0.6099.71 (Official Build) (x86_64).

Steps:
1. Click "Connect wallet"
2. Select Blocto wallet

Error:
Please contact the website owner to upgrade wallet to v2. Check out [docs](https://docs.blocto.app/web-wallet-v1-sunset-notice-and-migration-guide) for more details. 

![Screenshot 2023-12-11 at 10 58 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/095c6493-51b0-4bd8-b0d5-21c58c2f4207)

## What is the expected/desired behavior
Blocto wallet is successfully connected.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Issue is still reproducible, user is not able to connect to Blocto wallet
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a077b2ec-d2d3-41ad-87d3-1b37bf735f34

**Comment by tsadovska** [comment]
"Blocto" wallet is no longer shown in "Connect wallet" window when Solana network is selected. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/87a4d05c-8232-4499-b49a-61bf620296e1)


Ticket is closed.
