### ISSUE TITLE
[QA][Firefox] Cannot connect to wallet, if account is logged out

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1314]
Preconditions:
Metamask wallet extension is enabled
User is logged out from Metamask wallet (password is required when logging in)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159 and Firefox Version 120.0.1

Tested from: https://wormhole-connect.netlify.app/#

Steps (from Firefox browser):

1. Click on Connect wallet
2. Select Metamask and click on it
3. Observe
4. Open Metamask wallet
5. Enter the wallet password
6. Refresh the Wormhole-connect page
7. Repeat steps 1-3

Actual result: If the Metamask wallet is logged out, there won't be a wallet pop-up when clicking on Metamask wallet to enter the password

Expected result: (Shown in the attachment section Chrome screen recording) If wallet is logged out, pop-up to enter the password will be shown and wallet will be connected to Wormhole-connect

Attachment:
Firefox:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a4527af-339d-40e9-853a-74afd00f82ae

Chrome:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/db820449-a662-46f6-8159-8db9e861558d

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ (Connect v2) and https://portalbridge.com/. Checked with Firefox version 126.0.1. 

https://github.com/user-attachments/assets/b3a883c5-4326-4d6b-abad-521e681e38e4


Closing the ticket.
