### ISSUE TITLE
[QA] [Improvement] Show SOL asset instead of WSOL in To section on Bridge screen when sending WSOL to Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1315]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.71 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 WSOL from BSC (Metamask) to Solana (Phantom)
2. Observe Asset in To section (actual result: WSOL)
3. Click "Approve and proceed with transaction" button
2. Check WSOL or SOL asset is received on Solana when transaction is completed (actual result: SOL)

![Screenshot 2023-12-11 at 13 57 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5144a88f-2452-41bc-b01b-d4b7fd28fbdf)

Notes:
* Send from tx: [BscScan](https://testnet.bscscan.com/tx/0xa9fcfcc714e25b3698caaba1b8e415f0937a64f6477a5d9681ae2c8b3341aa0a)
* Send to tx: [Solana explorer](https://explorer.solana.com/tx/5tKSvcz4qgVENJ2KXxFsFtFyVFfyKFFS3vf3pBcVgNMBMjUd13ZuyDpBxe7Q5KLPN7HsaeEa5oPQ5icghDTiYHzz?cluster=devnet)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xa9fcfcc714e25b3698caaba1b8e415f0937a64f6477a5d9681ae2c8b3341aa0a?network=TESTNET)

## What is the expected/desired behavior
SOL asset is shown in To section on Bridge screen when sending WSOL to Solana, because user receives unwrapped asset on Solana.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet]. WSOL asset and balance instead of SOL asset and balance is shown in "To" section on first screen.

Scenario checked: Send WSOL from BSC (MetaMask) to Solana (Phantom) (Send from tx: [BscScan](https://bscscan.com/tx/0x78242d53bf1e2e5dd9ac1ac2b25abbe6046715aa431d8e7030eabf5da576cb6a), Send to tx: [Solana Explorer](https://explorer.solana.com/tx/2gNChkZZMHN1MbrPVCziL8D6PtFy8fcnVFuaxucbwkhN6BaWMXWw8aQvMyyqSTwEUdNZpUroBcwkWmmM8VsDyF93)). Received asset: SOL.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/# [Mainnet]. WSOL asset and balance instead of SOL asset and balance is shown in "To" section on first screen.

Scenario checked: Send WSOL from Celo (MetaMask) to Solana (Phantom). 
Send from tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0x74468a05dd1f02f749b9c141ab7db019e2412a708d4191170aaaf3fca24dd7eb)
Send to tx: [Solana Explorer](https://explorer.solana.com/tx/4ce1Kb14Qf5e14r3McSwczy3h4jzZXqSb5r24VYybfrpXZyJE5dSogonTuhAzrHSue6psPXqHPhZk7GLfGBaxuEQ)
Received asset: SOL.

<img width="379" alt="Screenshot 2024-04-12 at 17 03 27" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/92906ca6-04f3-419a-ac82-e4d2870d39e6">

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/3b81f32422/. 
WSOL asset and balance instead of SOL asset and balance is shown in "To" section on first screen.

Attachment:
<img width="804" alt="Screenshot 2024-06-06 at 12 36 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/f5552328-d6dd-4b3f-80ca-985bae81e863">

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/.

* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


![image](https://github.com/user-attachments/assets/b36b3711-2132-4484-bd36-bdae06ca0862)

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://portalbridge.com/, but still reproducible on https://wormhole-connect-mainnet.netlify.app/. 
WSOL asset and balance instead of SOL asset and balance is shown in "To" section.
Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-10-21 at 10 59 20" src="https://github.com/user-attachments/assets/e1f49f50-ac69-4302-b9ba-e98127cff4d1">

**Comment by Wesleyleung** [comment]
this appears fixed in the latest builds. closing
