### ISSUE TITLE
[Bug] - [support] <Ticket 11814 Kujira -> SOL, unable to resume TX>

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source Chain: Kujira
Source Chain Wallet: kujira1s4y8w0df4c7357zw522qyjn79xz53cvdm6xq5m
Target Chain: Solana
Target Chain Wallet: FQKbZbJ8grgx8G85ocHGPAPbvEUosPJxmnDCjcQZdmi8
Asset Type: Wsol
Tx: 1C05D82AF3D6618436DB6986CFFD3CD0C04F2B0DBFDE1819C424AB6DDB5239D9
```

### Current Behavior

TX approval with HW wallet failed, using solflare wallet. Got stuck trying to claim wsol on solana.
Resume transaction (kujira source) -
"Bridge transaction not found, check that you have the correct chain and transaction ID"

### Expected Behavior

Able to resume TX without problems

### Steps To Reproduce

https://www.portalbridge.com/
Please resume your TX here
Click “Resume Transaction”
Select Source Chain: Kujira
Enter Source TXID: 1C05D82AF3D6618436DB6986CFFD3CD0C04F2B0DBFDE1819C424AB6DDB5239D9

**Comment by sleepycorgi1** [comment]
Hi - Would we be able to provide an update to the user please?

**Comment by yuli-ferna** [comment]
@sleepycorgi1 Could the user confirm if this is his/her tx? 
https://finder.kujira.network/kaiyo-1/tx/1434533E737F4BA49C116838256100E80F4A430C77FE66C6AE5DC2F015D64B68
