### ISSUE TITLE
[QA][Mobile] Not possible to scroll through asset list when keyboard is re-opened

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1321]
Preconditions: Metamask wallet connected through WalletConnect

Environment: iPhone 14, iOS 16, Safari 

Tested from: https://wormhole-connect.netlify.app/

Steps: 
1. Click on Select network
2. Select any Metamask supported Network (e.g. Mumbai)
3. Click on Asset
4. Scroll through the list
5. Observe
6. Click next to Select asset title to close the keyboard
7. Scroll through the asset list
8. Click inside the search window to re-open the keyboard
9. Try to scroll through the asset list

Actual result: Keyboard is left open even when user scrolls the list, when keyboard is re-opened asset list is not scrollable

Expected result: When user starts scrolling the asset list, hide the keyboard, when keyboard is re-opened user should be able to access all assets in the list

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3b1a1dde-e010-4a19-a1fc-4d4ddf25f854

**Comment by tsadovska** [comment]
Not possible to scroll Wallets screen on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] with following screnario:

1. Click "Connect wallet" button
2. Close keyboard
3. Scroll down 
4. Open keyboard
5. Close keyboard
6. Scroll down and then up
7. Check if screen is scrollable

Actual result: Screen is not scrollable. 

Checked with with iPhone 11 Pro iOS 16.5.1 and Google Chrome Version 114.0.5735.124.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7ed0c43c-52ae-4ec9-91e6-08b1c3538ab3

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2300 [QA] [Redesign] Some options from "Select a network" dropdown cannot be selected on small screens

Closing the ticket.
