### ISSUE TITLE
[QA] Wallet shows as connected when connection is removed from desktop app

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1322]
Preconditions: Wallet connected through WalletConnect ->Desktop app ( during test Zerion desktop app was connected)

Environment: Zerion desktop app v 2.13.0
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect.netlify.app/#

Steps: 
1. Open connect sites from Zerion desktop app
2. Click on Disconnect from Wormhole-connect
3. Observe https://wormhole-connect.netlify.app/# 

Actual result: Wallet is not showing as disconnected from Wormhole-connect

Expected result: If wallet is disconnected from the app, wallet connection should be removed from Wormhole-connect

Comments: Zerion desktop app, quits unexpectedly in about 10-15min, but wallet still shows as connected from Wormhole-connect
 
 Linking to previously reported similar issue - https://github.com/wormhole-foundation/wormhole-connect/issues/96 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7b882b9-58c4-4be5-a37f-3c565be66919

![Screenshot 2023-12-12 at 12 22 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/19620e31-fbe1-4e6e-93dd-78148f84d44a)

**Comment by tsadovska** [comment]
Cannot connect Zerion Desktop app wallet, please view the ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1495.
