### ISSUE TITLE
[QA] [Testnet] Automatic deposit transactions to Sui are stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1326]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.71 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 BNB from BSC (Metamask) to Sui (Sui wallet)
2. Select "Automatic deposit" option in Route section
4. Enable "Native gas" section
5. Change slider position
6. Click "Approve and proceed with transaction" button
7. Observe

Issue is also reproducible when:
* sending 1 CELO from Alfajores (Metamask) to Sui (Sui wallet) with automatic deposit
* sending 2 WGLMR from Moonbase (Metamask) to Sui (Sui wallet) with automatic deposit

Send from transactions:
* [BscScan](https://testnet.bscscan.com/tx/0xca9b06c7737ad7029b861fac722e9d19db0c670102d754c2b0b52901cf4eae70)
* [Celo explorer](https://explorer.celo.org/alfajores/tx/0x6b51acadcd958221159d8ea8318c4a83e83ed2725a420174549f02ecd0e3b430)
* [Moonscan](https://moonbase.moonscan.io/tx/0x7f99c56c3ff355940848c9b32513375a30e383414300bdb0819b8eb84ae92673)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/721ce385-c8b9-4b99-93f2-b215cdf1a022)

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by AigaD** [comment]
Linking to this issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1160

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Automatic route transaction 1 CELO from [Alfajores](https://explorer.celo.org/alfajores/tx/0xa8a33ab99b9e84c32300f4777aa4a67bddd464ba62b24ad2bceb4bcbe3b09412) to [Sui](https://suiexplorer.com/txblock/AiYdLsy3QkYaH2RQisTK3YvHUiFwsVeH9fSALvwJsA3v?network=testnet) was completed
Transaction BNB from [BSC](https://testnet.bscscan.com/tx/0x86153148ad50eb3de7d6e725c8e9366433a24b1ce52bc0a1766d756d95c16320) to [Sui](https://suiexplorer.com/txblock/4pbSwgZagsfQkcvgvVJotZw6Qx8gcN5rM7GbensfYKoR?network=testnet) was completed

Attachment:

![Screenshot 2024-02-13 at 12 50 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4514b630-f0a2-426d-b81b-3aa1699eb67a)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b5a84811-f3cd-4d98-9063-415f4c5c0cad
