### ISSUE TITLE
[QA][Mobile] User is not able to connect other wallets if wallet connected using Solflare app

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1328]
Preconditions: Metamask app and Solflare app installed

Environment: Samsung Galaxy S22+, OS12, Solflare v1.35.0

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Click on Connect at sending To section
2. Search Solflare and select it
3. Window "How do you want to connect?" should be opened
4. Click on Open Solflare option
5. Observe the opened window
6. Click again on Connect
7. Select Solflare and confirm
8. Click on Connect at sending From section
9. Select WalletConnect
10. Observe

Actual result: User is not able to connect both Solflare and WalletConnect wallet when clicking on Open Solflare, when trying to connect with WalletConnect -page is not found

Expected result: Solflare app is opened with request to connect wallet, approving the request user is returned to Wormhole-connect app

Comments: User is able to connect to Solflare wallet if choosing "Use Web wallet" option

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4bc15cd6-aeb8-496d-93f8-26d1e5e66fb4

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://wormhole-connect-mainnet.netlify.app/ with iPhone 11 Pro 17.5.1 and Solflare app Version 1.46.3.

![Screenshot 2024-08-26 at 16 28 17](https://github.com/user-attachments/assets/d8371171-141f-4fb4-b587-67dfa9103c53)


Closing the ticket.
