### ISSUE TITLE
[QA][Mobile] Wallet disconnects when approving the transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1329]
Preconditions: 
Metamask wallet connected at sending From section
Solflare wallet connected at sending To section

Environment: Samsung Galaxy S22+, OS12, Solflare v1.35.0

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 AVAX from Fuji to Solana
2. Click Approve and proceed with transaction
3. Click Approve on the transaction on the pop-up window
4. Observe sending To sections wallet

Actual result: Wallet at sending To section (Solflare) gets disconnected when transaction is confirmed, when user is taken to Bridge screen he is asked to Connect Solflare wallet again

Expected result: Wallet is left connected while transaction is in progress

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a6d7303-7ae6-470e-9a39-73313df7a3f7

![Screenshot_20231213-113508_Chrome](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/73eee6bf-f72a-4e93-8792-d3c4b72db95c)

**Comment by tsadovska** [comment]
Scenario is not longer reproducible on https://wormhole-connect.netlify.app/, Solflare wallet does not disconnect after approving the transfer. 

Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1930.
Closing the ticket.
