### ISSUE TITLE
[QA] [iOS] [Safari] Preview section is not updated when changing slider position for Extra Native gas

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#133]
Preconditions: Wallet is connected

Environment: iPhone 14, iOS 16,0, Safari browser

Steps:
1. Prepare to send 5 Celo from Alfajores to Goerli
2. Expand the drop down for Extra Native Gas
3. Change the slider
4. Observe the "Preview" section for Amount and Native token on destination

Actual result: Amount and Native token on destination is not changing from initial state even if slider for Extra Native gas is changed.

Expected result: Changing slider for Extra Native gas updates the numbers in Preview section are updated.

Attachment:

https://user-images.githubusercontent.com/91047061/222107976-61a798a7-985b-4f11-8d19-3583dc172a6a.MP4

**Comment by anondev2323** [comment]
https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/4b4fe061-6d52-48e4-ad75-e613a78f8cbd

**Comment by AigaD** [comment]
Tested OK.
Scenario: Verify that Preview section is updated when changing slider for Native Gas.
Environment: iPhone 14, iOS 16,0, Safari browser
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/958eb6a2-e7d2-472a-bbf0-61cfa97ba5ed
