### ISSUE TITLE
[QA] Missing revert data in call exception for transaction from WalletConnect

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1337]
Preconditions:
Wallet at sending From section is connected through WalletConnect -> Metamask app
Metamask wallet connected at sending To section
Console is open on desktop Wormhole-connect

Environment: iPhone 14, iOS 16.0, Metamask v7.12.2
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 MATIC from Mumbai to Alfajores
2. Click Approve and proceed with transaction
3. Observe

Actual result: Metamask app will either show that Network needs to be switched or will not show anything, but the transaction fails with reason: `Error: missing revert data in call exception; Transaction reverted without a reason string`

Expected result: Transaction is confirmed from mobile Metamask app and moves to bridge screen

Attachment:

![Screenshot 2023-12-14 at 12 34 13](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/531965fb-5154-45f1-9869-da0f1dcd38e8)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b0d1a9d0-2999-4852-9c46-72aae18b3660

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction from Mumbai (WalletConnect) to Alfajores (Metamask) is not starting, console shoes error `Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)`

Attachment:

![Screenshot 2024-02-12 at 10 31 59](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/20beb61f-9db4-4855-ad04-3b63a904cce7)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) when sending AVAX from Fuji (MetaMask through WalletConnect) to Alfajores (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0xf59f580762f15d06d6cd0945bbfe10403a0c95156df39d70ba40787eff12efb5?network=TESTNET).
Closing the ticket.
