### ISSUE TITLE
[QA][Mainnet] Cannot move Native gas slider position

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1340]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 6 USDC asset from Ethereum to Polygon
2. Open section Native gas
3. Try to move the slider

Actual result: User is not able to change the Native gas slider position

Expected result: Native gas slider is responsive

Comments: Linking to perviously opened issue - https://github.com/wormhole-foundation/wormhole-connect/issues/950

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/23b50ab9-8932-4574-806f-e9ef864e5708

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 4 USDC from Avalanche (Metamask) to Polygon (Metamask). User is not able to change the Native gas slider position.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending USDC from:
* Ethereum -> Polygon
* Avalanche -> Polygon
* Arbitrum -> Polygon
* Optimism -> Polygon

Ticket is closed.
