### ISSUE TITLE
[Perf] Wallet code should load dynamically using import()

### ISSUE THREAD

**Issue by artursapek** [wormhole-foundation/wormhole-connect#1343]
## Proposed change

The Connect widget's "Choose Wallet" button will be disabled until the user selects a Network first

## Why?

- For the end user, seeing every one of the 33 supported wallets all at once isn't really that useful to begin with
- It will make it much easier to achieve a small bundle size via dynamic loading

## Dynamic loading

If we made this change, we'd be able to load wallet code only for the selected network, after the user selects it. This achieves two things:

1. Reduces initial bundle size by not including wallet code at all (which appears to be roughly 50% of total bundle size)
2. Reduces total code loaded by never loading wallet code for networks that the user doesn't select

Opening issue for discussion!

**Comment by hsnice16** [comment]
Hey, Hi @artursapek 
I have added the code for disabling Connect Wallet till we have a network value.
For the dynamic import, I am also doing that, but there are some webpack configuration changes required that I am looking into.

**Comment by hsnice16** [comment]
Also, can you review the draft PR #1346 if this is what you had suggested.

**Comment by tsadovska** [comment]
Checked on https://preview.portalbridge.com/7246284e5d/ [Mainnet].

Tested OK:
* User can connect wallet only after user has selected the network.
* User can connect wallet on Redeem screen when transaction was resumed.
