### ISSUE TITLE
[Feature] Add support for Rabby wallet

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1344]

**Comment by tsadovska** [comment]
Tested OK:
* User can successfully connect Rabby wallet when new account is created in the wallet and when Metamask account is imported in the wallet
* User can successfully proceed transactions with Rabby wallet 
* Metamask and Rabby wallets do not conflict

Checked following scenarios on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* Send AVAX from Avalanche (Rabby wallet) to Fantom (Rabby wallet): [Avascan](https://avascan.info/blockchain/c/tx/0x224792d8656b0dc37bdc796b32a4c53885f2758674579fe17da8dfdc9d7223e2), [FTMScan](https://ftmscan.com/tx/0xfcdc51bf1a389030d4533286ff4bc695c2c301583e9f116e58033aa9570e1381)
* Send WSOL from Osmosis (Keplr) to BSC (Rabby wallet): [Mintscan](https://www.mintscan.io/osmosis/transactions/636C9B17828AE0CAC9484AC663FA77394B2636241440A566BA716EE93683E91B), [BSC](https://bscscan.com/tx/0x13a3c5add5454cc0b5f01ef68adc6d5e060cbc4279e0b47320023efc776eccce)
* Send WFTM from Kujira (Keplr) to Moonbeam (Rabby): [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/DDFA1A505D6C34CD35C9B284246ED47495FE1689394685BB41EB055237A39503), [Moonscan](https://moonscan.io/tx/0x4a7366a467be50248d613be22a612ca5590c5dba02cbb6e05bd034b1e9933ad7) 
* Send WFTM from Moonbeam (Rabby) to Celo (Rabby): [Moonscan](https://moonscan.io/tx/0xd9a319646d2c7bbe132e5ec615aa045593f97dd8021606a5732b8ac5db0fb0a0), [Celo explorer](https://explorer.celo.org/mainnet/tx/0xc54c6fdc0eaa47598e1265b078ce9e08d6df4fc5fd959ae81ecd98a4e9ff3268)
