### ISSUE TITLE
[QA] Cannot send USDC from Arbitrum to Polygon

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1351]
## Describe the current behavior in detail
Checked on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (x86_64).

Steps:
1. Prepare to send 1 USDC (Arbitrum) from Arbitrum (Metamask) to Polygon (Metamask)
2. Select "One transaction" option in Route section
3. Change slider position
4. Click "Approve and proceed with transaction" button
5. Approve Metamask notification

Error is displayed in Console:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: insufficient amountReceived", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x4cb69FaE7e7Af841e44E1A1c30Af640739378bb2","data":"0x59b87d8e000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000e7ee600000000000000000000000000000000000000000000000000000000000000050000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001b696e73756666696369656e7420616d6f756e7452656365697665640000000000","message":"execution reverted: insufficient amountReceived","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at f.makeError (main.73d22bf0.js:2:2343439)
    at f.throwError (main.73d22bf0.js:2:2343559)
    at v (main.73d22bf0.js:2:2401734)
    at u.<anonymous> (main.73d22bf0.js:2:2411688)
    at Generator.throw (<anonymous>)
    at s (main.73d22bf0.js:2:2400835)
```

Note: I could reproduce only once. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d2f13726-dee7-4673-93bb-dbaef09e46e7

## What is the expected/desired behavior
Transaction is successfully started.

**Comment by kev1n-peters** [comment]
The contract was reverting here: https://github.com/wormhole-foundation/example-circle-relayer/blob/189becd8d3935decb17383bd2e61b4909cbddc89/evm/src/circle-relayer/CircleRelayer.sol#L104

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet].
* Send from tx: [Arbiscan](https://arbiscan.io/tx/0x35d920f128e2c9c8d57157d1879c2304ae866d6900b03fb07910e69d6056cafe)
* Send to tx: [Polygonscan](https://polygonscan.com/tx/0x59dabf89cd93651fd689fc8adbd0992495bb9dc3787d3a252338ef199cb2b949)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cd3fa156-f9b9-41f4-8267-b767b5caddb6)

Ticket is closed.
