### ISSUE TITLE
[QA]One of the assets fields are left selected when other gets unselected 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1357]
Preconditions:
Solflare wallet connected at sending From section
Sui wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://preview.portalbridge.com/7102d8ccad/#

Steps:
1. Select Solana Network
2. Select SOL asset
3. Change the Solana network to any other Network
4. Observe assets that are left connected

Actual result: WSOL asset is left connected at sending To section, although SOL asset was disconnected when the Network was changed

Expected result: Assets fields are disconnected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/183f7ce6-1628-4311-9629-7eaecc7d0b40

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2023-12-19 at 12 02 04](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f44c2725-0cf9-4d0d-a5d3-d17f3c1e0c02)

**Comment by tsadovska** [comment]
Closing as expected behaviour.

Checked on https://portalbridge.com/: 
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
