### ISSUE TITLE
[QA] [Mainnet] Missing revert data in call exception for transaction from Optimism to Aptos

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1367]
Preconditions:
Metamask wallet connected at sending From section
Nightly wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portalbridge.com/7102d8ccad/#

Steps:
1. Prepare to send 0.0001 ETH (Optimism) from Optimism to Aptos
2. Click Approve and proceed with transaction
3. Observe

Actual result:  Transaction fails, reason: `Error: missing revert data in call exception; Transaction reverted without a reason string `

Expected result: Transaction is completed

Attachment:

![Screenshot 2023-12-19 at 17 23 31](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c5f3d9da-64cb-4f4c-a1c2-e0160d957bfb)
![Screenshot 2023-12-19 at 17 20 44](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a81aa69-d1a3-48c5-9ba1-8210b27db42e)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] with following scenario:
Steps:

1. Prepare to send 0.0001 ETH (Optimism) from Optimism (Metamask) to BSC (Metamask)
2. Click "Approve and proceed with transaction" button

Error:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x1D68124e65faFC907325e3EDbF8c4d84499DAa8b","value":{"type":"BigNumber","hex":"0x5af3107a4000"},"data":"0x9981509f00000000000000000000000000000000000000000000000000000000000000040000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a6670000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","cause":null}}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at f.makeError (main.js:2:2341430)
    at f.throwError (main.js:2:2341550)
    at v (main.js:2:2399495)
    at u.<anonymous> (main.js:2:2409679)
    at Generator.throw (<anonymous>)
    at s (main.js:2:2398826)
```

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Error `main.js:649 Error: missing revert data in call exception; Transaction reverted without a reason string ` is shown when trying to send ETH (Optimism) from Optimism to Moonbeam

Attachment:

![Screenshot 2024-01-18 at 09 19 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f1fd8b0-c795-4f21-9502-254f170cd085)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d54940c-d158-4b66-a294-0ce88e33020b

**Comment by AigaD** [comment]
Issue still reproducible.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.0001 ETH (Optimism) from Optimism to Aptos fails, reason: `Error: missing revert data in call exception`
Transaction 0.0001 ETH (Optimism) from Optimism to Base fails, reason: `Error: missing revert data in call exception`

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6f66955-e025-4dfc-83f3-4af167b341f9

<img width="1177" alt="Screenshot 2024-01-22 at 12 24 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d2383603-ea47-4af8-aade-9446a30067aa">

**Comment by tsadovska** [comment]
Following routes are no longer available:
* Send ETH (Optimism) from Optimism (MetaMask) to Aptos (Spika)
* Send ETH (Optimism) from Optimism (MetaMask) to Moonbeam (MetaMask)

Scenarios - Tested OK:
* Send ETH (Optimism) from Optimism (MetaMask) to BSC (MetaMask). Received asset: WETH (BSC). Send from tx: [Etherscan](https://optimistic.etherscan.io/tx/0x22ba20d60bfbe94f5ef6bdc5d22cdead79a21687c9abd1b603ff10f7c5fe9224), Send to tx: [BscScan](https://bscscan.com/tx/0x303a66a745c1d108d754e51415717cd3527df039ad4eb8d0342333d98815215c)
* Send ETH (Optimism) from Optimism (MetaMask) to Base (MetaMask). Received asset: ETH (Base). Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x128208fa35f82af098f74b2d406c68d0376569a5132a64f32cd24e4af4fc5f7f), Send to tx: [BaseScan](https://basescan.org/tx/0x472f6f8241061ef6e012059c9d048a6d8f6c46fbf5f6896f6d3c2db0996a87b1)

Ticket is closed.
