### ISSUE TITLE
[Improvement] Allow self-distribution of Connect

### ISSUE THREAD

**Issue by artursapek** [wormhole-foundation/wormhole-connect#1369]
Today, the only [official way of integrating Connect](https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect) into an application requires it be downloaded from the unpkg.com CDN. This kind of centralization is bad for multiple reasons:

- unpkg.com infrastructure is a single point of failure
- everyone using Wormhole Connect is exposed to supply chain attacks on our NPM package. Such an attack happened to Ledger [literally last week](https://news.ycombinator.com/item?id=38640999).

Given Connect's role as a wallet aggregator, it's especially attractive as an attack target. Developers should be able to host their own copies of Connect and not rely on the unpkg.com CDN.

## Open questions:

- What is the ideal way to let people bundle Connect into their own applications?
- How do we deal with the fact that the current NPM package is published from `wormhole-connect-loader`, yet the actual source code lives inside `wormhole-connect`?

**Comment by aadam-10** [comment]
covered in https://github.com/wormhole-foundation/wormhole-connect/issues/1715
