### ISSUE TITLE
[QA][Testnet] Balance not loading for Cosmoshub

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1371]
Preconditions:
Leap (Cosmo testnet) wallet connected at sending From section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from:
https://wormhole-connect.netlify.app/ 

Steps:
1. Click on Select Network
2. From the list select Cosmoshub
3. Click on Asset
4. Observe

Actual result: Balance for Cosmoshub network is not loading

Expected result: Balance is loaded

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b1e00ee-4e10-480a-aca8-82c60b5edfb4

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Balance is not loading for Cosmoshub. Checked with Keplr and Leap wallets. 


![Screenshot 2024-01-09 at 10 52 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3b4956eb-ab47-4c45-8dd1-2fe8cda26409)

**Comment by AigaD** [comment]
Closing, tested OK
Balance is loading for Comsoshub network
Tested from: https://wormhole-connect.netlify.app/#

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fada15b2-5d9b-4bc1-8fdc-dddaa0da3aa1
