### ISSUE TITLE
[QA]Cannot connect Solana wallet to register asset

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1373]
Preconditions: 
Slope wallet connected at sending from section
Metamask wallet connected at sending To section

Environment:  MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect.netlify.app/# and  https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Steps:
1. Prepare to send 0.1 SOL from Solana to Moonbase
2. Observe that message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on register
4. Observe that Solana Network is already selected
5. Click on Connect
6. Try to connect the Slope wallet

Actual result: Wallet is not reacting, cannot connect the source wallet

Expected result: Source wallet is connected, user can continue with token registration

Comments: Linking to issue https://github.com/wormhole-foundation/wormhole-connect/issues/1237

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3768037e-9d5c-43ed-a16d-fbffee1b5137

**Comment by AigaD** [comment]
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1409 is resolved

**Comment by AigaD** [comment]
Slope wallet is not shown in the wallet list https://github.com/wormhole-foundation/wormhole-connect/issues/1580

**Comment by tsadovska** [comment]
Slope option is no longer displayed on "Connect wallet" screen.

SOL transfer from Solana (Phantom) to Moonbeam (MetaMask) was successful. Checked on https://portalbridge.com/ [Mainnet].
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/3ed1ChA5Gm5YPMYHBFUJyCi7sFRmGqDEhS6hnXhgWYV9mVp53e71B71gC4n8ybn1pB4rZJTbjekY6QHUaGcd9eAh)
* Send to tx: [Moonscan](https://moonscan.io/tx/0x04fa378c42ff9404a98f415a3e0724deaaac2d69bba54dfd882378aad78001ae)

Ticket is closed.
