### ISSUE TITLE
Don't show illiquid USDC banner warning if a token bridge routed transfer wouldn't result in a wrapped asset

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1374]
Scenario:
1. Have some USDC(ethereum) on a non-cctp chain like Moonbeam
2. Try to bridge it to Ethereum mainnet

Experienced:
- The "This transaction will transfer wrapped USDC [...]" warning banner is shown

Desired:
- The warning isn't shown

**Comment by evan-gray** [comment]
This checks seems to be incorrect. Not sure about the `cctpWarningFlag` part, but I think this shouldn't be shown when the token is returning to it's native chain.
https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/views/Bridge/Inputs/TokenWarnings.tsx#L220-L226

**Comment by evan-gray** [comment]
A little more on `cctpWarningFlag`...
```jsx
export const USDC_BRIDGE_URL = config.cctpWarning?.href || '';
...
const cctpWarningFlag = !!USDC_BRIDGE_URL;
```

It pulls from the config, which by default is empty, so it's possible this is only tripped in Portal (assuming that's the only folks setting that config).

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129
No USDC warning banner is shown for CCTP/ non-CCTP transactions

Attachment:
![Screenshot 2023-12-22 at 16 37 23](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bcd092d7-4ba6-4ca4-86b3-57e17ca4f588)

![Screenshot 2023-12-22 at 16 36 46](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e0238ff8-6e90-4f49-8c38-19d026534f69)

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/4adb101c39/ [Mainnet].

* Send USDC from BSC -> Ethereum
<img width="383" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ce51bbb2-b6a2-42b2-b80f-bb26724faf50">


* Send USDC from Solana -> Ethereum
<img width="369" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/51e526fd-2762-4fa5-a47d-7f8431134260">
