### ISSUE TITLE
Add temporary banner for illiquid markets

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1379]
Currently connect does not have any mention of illiquid markets for all corridors. While we are working on a more robust UX for illiquid markets, we will adopt some short term messaging that already exists in Portal bridge.

- Match connect design
- use same conditions as Portal Bridge

example:

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/ff5c98e7-b1d1-4756-a634-00ff6ae3f78d)

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/#
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129
Attachment:

![Screenshot 2023-12-22 at 16 33 05](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6bf8ec69-7e86-4dd8-a703-c65a6d42584a)

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/4adb101c39/ [Mainnet] on following networks:  Ethereum, BSC, Polygon, Avalanche, Fantom, Celo, Moonbeam, Solana, Sui, Aptos, Base, Osmosis, Arbitrum, Optimism, Evmos, Kujira.
* Banner is displayed on Assets screen for all network
* Link in the banner is valid
* Banner is well displayed on small screens

Text "You should always check for markets and liquidity before sending tokens. [Click here to see available markets for wrapped tokens.](https://portalbridge.com/docs/faqs/liquid-markets/)".
