### ISSUE TITLE
[QA] Assets screen should not have 2 vertical scrollbars

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1386]
## Describe the current behavior in detail
Checked on https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.109 (Official Build) (arm64).

Steps:
1. Select Ethereum network in From section
2. Connect Metamask wallet
3. Open Assets list

Actual result: There are 2 scrollbars on Assets screen. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/665732e5-5883-4cf5-9b19-a0eca9bbab6d

## What is the expected/desired behavior
There is 1 scrollbar on Asset screen.

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is no longer reproducible after redesign.

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


https://github.com/user-attachments/assets/f010f4b9-428a-4c14-8565-d1c941ec13f2

Ticket is closed.
