### ISSUE TITLE
[Bug] Connect warns about custom RPCs not being provided when they are

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1392]
## Describe the issue in detail

- Visit portalbridge.com and open the console
- Note log messages for `Wormhole Connect: No custom rpcs endpoint provided for polygon. We recommended that you provide your own rpcs endpoint for the best performance.` and others
- Select Polygon chain and connect wallet
- Note that custom Ankr RPC is actually being used

## What is the expected/desired behavior

- No log warning messages should be shown when custom RPCs are provided

**Comment by sebastianscatularo** [comment]
Updated portalbridge.com with private rpcs, the issue is no longer reproducible 

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/9c9e523d-a493-459f-be1d-58fd3c1cca6a)
