### ISSUE TITLE
Provide artifacts per branch in ci

### ISSUE THREAD

**Issue by elee1766** [wormhole-foundation/wormhole-connect#1397]
@artursapek follow up to my comment/request earlier.

currently the portal-bridge rebuilds wormhole-connect in its build process.

https://github.com/XLabs/portal-bridge-ui/blob/main/.github/workflows/build.yml#L152-L177

it then takes these hashes and uses them for verification integrity. 

i assume it does this because portal bridge might want to access a specific branch of wormhole-connect to test features? 

there's a few problems that i noticed with this though...

1. the production build https://github.com/XLabs/portal-bridge-ui/blob/main/.github/workflows/production.yml seems to just consume the builds downstream and trusts that? this seems to indicate that the production portal bridge site doesn't use a manually confirmed hash to a valid WHC build, it just hopes that it built WHC correctly. trying to maintain two different production ci for building wormhole connect seems like a security problem waiting to happen. 

2. there's no real reason that the portal bridge should be rebuilding whc every single time anyways, it doesn't change. the build used to take ~8 minutes, (now its probably closer to 3-4 with rollup), but it's still non trivial when it doesn't need to be done, and ci minutes can be saved. 99% of the time when changes are made to the portal bridge code, whc does not change at all.

the solution i think is simple.

1. add a workflow on each pr to upload the completed whc build as an artifact, and use https://github.com/dawidd6/action-download-artifact to download it on other repositories, such as the portal-bridge. 

2.  add a workflow to releases and tags which publishes the built wormhole-connect artifact along with hashes which can be optionally copied manually to downstream repos to make sure that production build integrity matches. 

happy to do all these things if you guys think it's worth it - just something i noticed when working with the site and I was trying to setup the ci on my own accounts.

**Comment by sebastianscatularo** [comment]
@elee1766 that's the long-term solution that we want to apply, this first solution was a mind term solution to be able to roll out portal bridge without waiting on connect for a release, and due to our available bandwidth

**Comment by sebastianscatularo** [comment]
and, we do not want to use 3rd party actions, apart from GitHub official actions, if it is necessary, we will build our own actions

**Comment by elee1766** [comment]
sound good :)


let me know if there's any way I can help
