### ISSUE TITLE
[QA] Cannot send tBTC from Goerli to Solana/ Mumbai/ BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1402]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome  Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 tBTC from Goerli (Metamask) to Solana (Phantom)
2. Check if "No bridge or swap route available for selected tokens" warning is shown

Actual result: Warning "No bridge or swap route available for selected tokens" is shown on https://wormhole-connect.netlify.app/ [Testnet] and is not shown on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet].

![Screenshot 2023-12-27 at 13 29 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1c3be829-2ddb-4825-a239-bebb058be5d8)

## What is the expected/desired behavior
User can send tBTC from Goerli to Solana/ Mumbai/ BSC.

**Comment by kev1n-peters** [comment]
Should be resolved in https://github.com/wormhole-foundation/wormhole-connect/pull/1401

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
Transactions tested OK:
tBTC from [Ethereum](https://etherscan.io/tx/0x4753b57c34abcf5170625f08527180b72b73e1d26be139e87f5d3d2400891fef) to [Solana](https://explorer.solana.com/tx/5swQ6gDrn5yivJhdigytRgZK5rwxCi4kBTUTVHXehW1E1udQktpTzJtzr5TzktgHF8SitcK8U4Y4tyEYbQQqLkgC) 
tBTC from [Ethereum](https://etherscan.io/tx/0xf7654a86a05b10b9e3ed1a81fbba2bb4d6a915c254e30ad903a3d8b877aa1407) to [Mumbai](https://polygonscan.com/tx/0x67434f9f13a606033e5a28adca33420d7e9c5ded81de8964eae04c52ecf96e7a)
tBTC from [Ethereum](https://etherscan.io/tx/0x7e576713e978fa21b7c51058e9195819875cb8587b52cf59009da9ed575df957) to [BSC](https://bscscan.com/tx/0xc3b5669714229c7068cadea1af32af0ac4cd3283ad452194f2f65f53f44d3c1b)
Attachment:
<img width="1142" alt="Screenshot 2024-01-05 at 20 21 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a3e5acb4-f837-427f-9bea-5301e5a893b1">
