### ISSUE TITLE
[Improvement] Resume transaction feature

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1403]
**User Story**
As a user I want to know when my transfer is ready to redeem, and be able to redeem my transactions with no issues

**Acceptance Criteria**
- during normal transfer flow, nothing ever happened to indicate the transfer was ready to be redeemed. 
- during recovery, metamask was not recognized as being installed

**Comment by chase-45** [comment]
It would be good to associate this issue to the issues associated with:
- Be able to redeem transactions which were originally requested for relay
- Be able to redeem transactions on behalf of other users

**Comment by mliu-xlabs** [comment]
@sebastianscatularo lets brainstorm this when you get back
