### ISSUE TITLE
[QA] [Mainnet] Testnet networks are shown in mainnet build

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1406]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Click "Select network" button

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/42761bb4-51cf-48a1-b82d-86e6b37a519e)

## What is the expected/desired behavior
Mainnet networks are shown.

**Comment by kev1n-peters** [comment]
Should be resolved with this PR https://github.com/wormhole-foundation/wormhole-connect/pull/1393

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
Ticket is closed.
