### ISSUE TITLE
[QA] [Mainnet] Cannot send tBTC asset from Solana

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1414]
Preconditions:
Solflare/Phantom wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 0.00001 tBTC asset from Solana to Ethereum/Arbitrum
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x7d6
    at SolflareWalletAdapter.sendTransaction`

Expected result: Transaction is confirmed and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/424b1abd-8be2-4bb2-9498-cc2f18a3ba93

![Screenshot 2024-01-03 at 12 53 39](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/463c4b60-a3da-4301-a145-e0f27e3917aa)

**Comment by kev1n-peters** [comment]
I did not encounter an issue when sending tBTC from Solana to Arbitrum https://explorer.solana.com/tx/5sqBdTeDk3LrgyHjUntZKzhndcd3mKtdFfhu51NoQe3Ut4CABpvhP9JwbUCoswSP5XMQA1j8wZ6T2P5bTBAvvRNq

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
Issue is still reproducible, the same error message is shown as described in the main ticket.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f302abc0-6525-4389-aa8f-b03d5ef10be7

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Cannot send tBTC from Solana (Solflare) Network to Aptos (Nightly)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bbf7f3a6-d392-482e-bc4a-4ef3faa9434f

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when:
* sending tBTC from Solana (Phantom) to Moonbeam (Metamask)
* sending tBTC from Solana (Phantom) to Celo (Metamask)

Error:
```
WalletSendTransactionError: Unexpected error
    at PhantomWalletAdapter.sendTransaction (main.js:443:213027)
    at async SolanaWallet.sendTransaction (main.js:477:299960)
    at async signSolanaTransaction (main.js:477:313783)
    at async signAndSendTransaction (main.js:477:315225)
    at async TBTCRoute.send (main.js:483:59851)
    at async Operator.send (main.js:483:65963)
    at async Object.sr [as onClick] (main.js:649:95375)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/94f9aeba-fd4b-43eb-8ea4-c5a71782cd77




![Screenshot 2024-01-10 at 10 48 25](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/04fe5e0b-0d9e-4176-9500-e8ded116ddbb)

**Comment by AigaD** [comment]
Issue reproduced from: https://wormhole-connect-mainnet.netlify.app/#
When sending tBTC asset from Solana to Moonbeam, console shows error: `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3ae1ce0-2962-4dde-a8d0-eb519dd9c329

**Comment by AigaD** [comment]
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1689 is solved

**Comment by AigaD** [comment]
Tested from: Mainnet
Transaction 0.00001 tBTC from [Solana](https://explorer.solana.com/tx/ZZav1AjdfMNoBY5XXp74fYm4cSbTYo2GEZVkEg3dYZEfgsvm6zPoLmukSHMbsBdmWt6YqiRSLRVf4zZxJ44Fvt2) (Solflare) to [Moonbeam](https://moonscan.io/tx/0x60b1da055b305025ca845c3cc65c11caf45feed50847cc61348319f2b890180c) (Metamask) was completed.
Closing the ticket.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0e28d47c-9102-4f54-922b-c70af0a513ed

<img width="807" alt="Screenshot 2024-05-22 at 14 56 50" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/561eaf09-a050-4b2b-aa8f-b70a1136d8fe">
