### ISSUE TITLE
[QA][Mainnet] Two automatic route options are given when sending tBTC asset to Cosmo chains

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1415]
Preconditions:
1. Metamask wallet or Aptos/Sui supported wallets connected at sending From section
2. Cosmos supported wallet connected at sending To section
3. tBTC asset available

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/

Steps:
1. Select any Metamask network in sending From section (e.g. Ethereum)
2. Select Cosmo network in sending To section (e.g. Osmosis)
3. Select tBTC asset
4. Observe given options in Route section

Actual result: Cosmos Gateway and tBTC automatic routes are both offered when sending tBTC asset to any Cosmo chain

Expected result: tBTC automatic route should not be offered

Attachment:

![Screenshot 2024-01-03 at 15 20 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/22d7c6a6-7997-4d09-bae0-7a4937c0d064)

![Screenshot 2024-01-03 at 15 18 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/67c217b5-ff59-4394-a80a-d579e69fe2bf)

**Comment by kev1n-peters** [comment]
Should be fixed with https://github.com/wormhole-foundation/wormhole-connect/pull/1401

**Comment by AigaD** [comment]
Tested OK
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
tBTC automatic route is no longer present for transactions to Cosmo chains
Attachment:
<img width="1176" alt="Screenshot 2024-01-05 at 20 25 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cd82694a-4453-4906-a464-68a6eebecda3">
