### ISSUE TITLE
[QA] tBTC asset is not automatically selected in "To" section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1418]
## Describe the current behavior in detail
Сhecked on https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Select Optimism network as source chain
2. Select Aptos network as destination chain
3. Connect Metamask wallet in From section
4. Connect Spika wallet in To section
5. Select tBTC asset
6. Check if asset in To section is shown

Actual result: Asset in To section is not automatically selected.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/04517ae9-20b1-474f-a1f7-022d928b3653

## What is the expected/desired behavior
tBTC (Ethereum) asset should be automatically selected, because this is the asset that user will receive. 

For example, tBTC asset is automatically selected when user sends tBTC (Ethereum) from Ethereum (Metamask) to Aptos (Spika).

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
Reproduced also when sending tBTC asset from and to other chains, it is not automatically selected at sending To section. In attachment tBTC asset is transferred from Arbitrum to Celo
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a2451698-86aa-4539-8a2d-7fbeb7fb179a

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending tBTC from Optimism Goerli (Metamask) to Sei (Leap). 

Steps:
1. Prepare to send asset from Optimism Goerli (Metamask) to Sei (Leap)
2. Select tBTC (Optimism Goerli) asset
3. Check if asset is automatically selected in "To" section

 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/13405b2c-659d-4ef8-ba6c-ab47add4daab

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://wormhole-connect.netlify.app/ [Testnet].


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ef675d23-c9a6-4c83-a5ff-03fa7daf96ad

Ticket is closed.
