### ISSUE TITLE
[QA] Network image is not displayed on iPhone and Desktop Safari

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#142]
SCENARIO 1
#### Steps:
1. Select Goerli network in “Sending from” section
2. Select Mumbai network in “Sending to” section
3. Select WETH from Token dropdown

#### Actual result:
Mumbai network image is not displayed in “Sending to” section

#### Expected result:
Mumbai network image is displayed.

SCENARIO 2
#### Steps:
1. Select Solana network in “Sending from” section

#### Actual result:
Solana network image is not displayed.

#### Expected result:
Solana network image is displayed.

#### Tested devices:
* MacBook Pro, macOS Monterey 12.6.1, Safari version: 16.1 (17614.2.9.1.13, 17614)
* iPhone 11 (iOS 15.4.1), Safari
* iPhone 11 (iOS 15.4.1), Chrome Version 110.0.5481.83

#### Attachments:
* Scenario 1: MacBook Pro, macOS Monterey 12.6.1, Safari version: 16.1 (17614.2.9.1.13, 17614)

https://user-images.githubusercontent.com/10746654/222671451-7f977f66-0d39-449e-99a6-ba1d49518093.mov

* Scenario 2: iPhone 11 (iOS 15.4.1), Safari

![Screenshot 2023-03-03 at 10 31 36](https://user-images.githubusercontent.com/10746654/222671494-53588964-cb87-4826-85b0-db2c592972e7.png)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Environment: iPhone 14, iOS 16, Safari
Both Network icon and asset icons are not present at sending ~From section
Attachment:

![IMG_0099](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e292e242-41bd-469d-92b8-a5a333b651b5)

**Comment by tsadovska** [comment]
Klaytn network icon and KLAY asset icon are not displayed on iPhone 11 Pro iOS 16.5.1. Checked on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![Screenshot 2024-02-01 at 11 16 39](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9b9e30a6-69aa-438b-b9f7-b5b964ebaa6b)

**Comment by tsadovska** [comment]
Injective network icon is not displayed on iPhone 11 Pro iOS 16.5.1. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Linked to #1763.


![Screenshot 2024-03-12 at 14 37 41](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/51658733-cc9a-4398-9ee6-aa65f89742d0)

**Comment by tsadovska** [comment]
Some scenarios are no longer reproducible.
Remaining issue on https://wormhole-connect-mainnet.netlify.app/ (Connect v2): https://github.com/wormhole-foundation/wormhole-connect/issues/2370.
Ticket is closed.
