### ISSUE TITLE
[QA][Mainnet] Bridge transaction not found in resume transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1420]
Preconditions:
Valid transaction hash
[Moonbeam](https://moonscan.io/tx/0xafe0c204b63e7def59504e0dd136d0627938857b45aa2a0fcb47fb75c22ba4c4) - 0xafe0c204b63e7def59504e0dd136d0627938857b45aa2a0fcb47fb75c22ba4c4
[Celo](https://explorer.celo.org/mainnet/tx/0xe0486de6edd9e4fc7004458e594395e9b49fa8d632ce2c0fdada5e53d4a6868c) - 0xe0486de6edd9e4fc7004458e594395e9b49fa8d632ce2c0fdada5e53d4a6868c
[Avalanche](https://avascan.info/blockchain/c/tx/0x077678d7d560d24f1c0b24a5046307095567eb6568547f5dc6f55a3f7e66f27d) - 0x077678d7d560d24f1c0b24a5046307095567eb6568547f5dc6f55a3f7e66f27d
[Arbitrum](https://arbiscan.io/tx/0xef3b4a4acff292cfc43eb4b507c8bd57923aea07a7f4c7ff7cd5575ce0a3faeb) - 0xef3b4a4acff292cfc43eb4b507c8bd57923aea07a7f4c7ff7cd5575ce0a3faeb

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/

Steps:
1. Click on Menu
2. Open Resume transaction
3. In search field paste transaction hash (e.g - 0xafe0c204b63e7def59504e0dd136d0627938857b45aa2a0fcb47fb75c22ba4c4 )
4. Select Network (e.g. Moonbeam)
5. Click Search

Actual result: Message "Bridge transaction not found, check that you have the correct chain and transaction ID " is shown when resuming transaction

Expected result: Transaction is found

Comments: User is able to resume transaction from Aptos, Base, Ethereum, Polygon, Fantom, Solana, Sui, Optimism, Evmos and Kujira

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/13072c6f-a90f-46bc-9362-cb5483779683

![Screenshot 2024-01-04 at 15 55 50](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cb58629d-900e-43ef-9089-0619e13ac2d8)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
[Goerli scan](https://goerli.etherscan.io/tx/0x987b72ffd795b9f3e67187462f56375eee8ff7c3d8a9d12b64832dee3d43d243) -  TX hash 0x987b72ffd795b9f3e67187462f56375eee8ff7c3d8a9d12b64832dee3d43d243

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/048a64ff-41e8-46bf-91cc-fa66bd4daac8

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bf7b5b43a8/#
Cannot locate transaction from [Ethereum](https://etherscan.io/tx/0x807c79a346c2e552a5d60053a9a589bf505b76fc21c395af6ac5bdba5476c783) to Polygon 0x807c79a346c2e552a5d60053a9a589bf505b76fc21c395af6ac5bdba5476c783

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/85b61396-48cf-46ca-a4e7-8eb27205903a

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from [Ethereum](https://etherscan.io/tx/0xdb844df0f9994ce39c01d71d5469e0403ed75249875584ccfea5d5403bb7e840) to Polygon
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/81a79106-0eef-447d-b099-2c92cd07d84b

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 ETH (Base) from Base (Metamask) to BSC (Metamask). Bridge is found only after user refreshes the page. Send from tx: [BaseScan](https://basescan.org/tx/0xcc0ab912b9135040707082c3f145a3791df8c8f1d9cfb7628db4f1addd3ac450)



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e78e69eb-eb40-4f28-af70-1b41adeb1288

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#
Cannot find bridge transaction after finishing the transaction.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7889692e-c33d-4360-a462-ba7ac99fb88f

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Transaction 0.001 WFTM from [Base](https://basescan.org/tx/0x857b0a2ac5a211f91405492d5d378ef32cdf04781df036b8349245cc0d0dccf5) to Injective is not found by Transaction ID (0x857b0a2ac5a211f91405492d5d378ef32cdf04781df036b8349245cc0d0dccf5) in resume transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1963ea6e-02e0-4b39-9cc3-75845004220b

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#) and https://portalbridge.com/
Transactions are found by transaction hash.
Closing the ticket
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fd381309-3d3b-440b-a472-e75b8c11aac8


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/27b3724e-92d4-4951-98cb-0ed3bf3081db
