### ISSUE TITLE
[QA] "Native gas on destination" field is shown  when "Native gas" section is not displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1425]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Prepare to send 0.08 SOL from Solana (Phantom) to Avalanche (Metamask)
2. Change slider position in "Native gas" section
3. Change asset to WAVAX
4. Check if "Native gas on destination" field is displayed in Preview section

Actual: 
* "Native gas on destination" field is displayed in Preview section
* "Native gas" section is not displayed

![Screenshot 2024-01-05 at 15 05 23](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/58702285-483c-4b4d-a759-60d1c648b07d)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f3ad054d-e393-4846-a5cc-b2384ec232a9

## What is the expected/desired behavior
* "Native gas on destination" field is not displayed in Preview section when "Native gas" section is not shown
* "Native gas on destination" field is displayed in Preview section when "Native gas" section is shown

**Comment by AigaD** [comment]
Tested OK. Closing the ticket, issue is no longer reproduced.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://portalbridge.com/
Attachment:

![Screenshot 2024-03-06 at 10 10 48](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dda97c7e-cdef-4d81-b2b3-b0c188cce8bc)
