### ISSUE TITLE
[QA] [Nightly] Sui (Wormhole) asset icon is missing 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1426]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.129 (Official Build) (arm64).

Steps:
1. Prepare to send 0.01 SUI from Solana (Nightly) to Sui (Nightly)
2. Click "Approve and proceed with transaction" button
3. Check Nightly wallet notification

![Screenshot 2024-01-05 at 16 46 05](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8df617a6-e723-45ab-aba4-5608a71a7dac)

## What is the expected/desired behavior
Sui (Wormhole) icon is displayed.

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] with the same scenario. Sui (Wormhole) icon is missing on Nightly wallet notification.

![Screenshot 2024-02-05 at 16 44 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/09d42b8e-7294-4792-a4b3-3a644486af7c)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/ with the same scenario. 

Attachment: 
<img width="381" alt="Screenshot 2024-06-12 at 12 15 39" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/9f320bbf-b10a-4234-8dc7-d696eda0b3c7">

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ with the same scenario, when sending 0.01 SUI from Solana (Nightly) to Sui (Sui wallet). Sui icon is not displayed in Nightly wallet notification. 
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
