### ISSUE TITLE
[QA] [Mainnet] Confirmation numbers are dropping from higher to lower

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1433]
Preconditions:
Solflare wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.5 SOL from Solana to Base
2. Choose automatic route
3. Add some Native gas
4. Click Approve and proceed with transaction
5. Observe confirmation count

Actual result: Confirmation numbers while loading are jumping from higher number to lower number multiple times

Expected result: Confirmations are counting up

Comments: Have noticed this behaviour twice in testing

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/614f549a-5120-4de2-a2d9-f34b8971ce8b

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Issue is still reproduced. Confirmations are dropping from higher to lower.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/22eae094-379c-425d-b021-d1b1fb0f8520

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Reproduced from transaction Solana to Osmosis
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c6cf8a94-8bf6-4f5e-99b6-02137324eece

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/caab316c7d/
For transaction 0.001 SOL from Solana (Solflare) to Base (Metamask) confirmation numbers dropped from higher to lower

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/7246284e5d/
Reproduced for transaction 1 BONK from Solana to Sui
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/45e9fa16-6254-42c5-a211-1018e3070442

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
For transaction 0.001 WAVAX from Solana (Backpack) to Celo (Metamask) Confirmation count was dropping from higher to lower numbers

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 
Closing the ticket.
