### ISSUE TITLE
[QA] [iOS] [Testnet, Mainnet] Cannot claim asset - Metamask app is opened for a brief moment and then claiming fails on wormhole-connect

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1434]
## Describe the current behavior in detail
Builds - Tested NOK:
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Checked with iOS 11 iOS 16.5.1, Google Chrome 114.0.5735.124 and Metamask v7.12.3 (1230)

Steps:
1. Open https://wormhole-connect.netlify.app/ [Testnet] / https://wormhole-connect-mainnet.netlify.app/ [Mainnet] / on mobile
2. Prepare to send 0.0001 BNB from BSC (Metamask through WalletConnect) to Goerli/ Ethereum (Metamask through WalletConnect)
3. Click "Claim" button

Actual result: Claiming fails.

Notes:
* Send from tx: [BSCScan](https://testnet.bscscan.com/tx/0x1f6b60eb1813448f449ce784e147e63683e3afe5a1da26ab42b455e8004c29f6) (Testnet)
* Send from tx: [BSCScan](https://bscscan.com/tx/0xfd744f46e8ab2db60cd10c7f223419743e8d6754629b782dc07e82d8b5804dc7) (Mainnet)
* Issue is not reproducible when sending 0.0001 BNB from BSC (Metamask) to Ethereum (Metamask) from computer.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/794c9af0-59ff-4e09-9215-53f13d3225e1

## What is the expected/desired behavior
Claiming is successful.

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)
Transaction 0.001 BNB from [BSC](https://bscscan.com/tx/0xc0b3bf7bc851da34c43f3e92484c746d74590c8d5d6315583e939a1b808295d5) (WalletConnect - Metamask) to Ethereum (WalletConnect - Metamask) fails at Claim `
{code: 5000, message: '{"code":-32602,"message":"May not specify default MetaMask chain."}'}`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7de82cda-8d7b-44f9-ac3d-07d7d10de989
