### ISSUE TITLE
Display the USD equivalent of all fees regardless of designated currency

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1436]
## Description and context
Display USD values next to tokens so that the user has an idea of the value transferred. Truncate to 2 decimals and add a ~ before the value in case the original value isn't 0.

- $1.23456 -> ~$1.23
- $0.23456 -> ~$0.23
- $0.00456 -> ~$0.00
- $0.000000 -> $0.00

## Definition of done
USD values are shown as below

- https://github.com/wormhole-foundation/wormhole-connect/assets/20446095/a0e65706-0794-4fc8-b0b5-dc9a8673eddb
- https://github.com/wormhole-foundation/wormhole-connect/assets/20446095/42ffec09-5950-46d9-9756-3eb5c81db8bc

**Comment by aakashthumaty** [comment]
Duplicate ticket with design mocks: https://github.com/wormhole-foundation/wormhole-connect/issues/1284

**Comment by kev1n-peters** [comment]
There should probably be a hook, like `useFetchTokenPrices` that fetches the USD values of all the tokens in the config file once at startup (maybe we could also update them in the hook periodically, like every 5 minutes or something? not sure..). I think we should store a map of token ID -> price in a map in the redux store.

**Comment by sebastianscatularo** [comment]
would be good to also allow integrators to configure their quote service for each ticker/asset, a default provider for the quotes.

**Comment by yuli-ferna** [comment]
@aakashthumaty @aadam-10 I have a doubt about this issue, should I only put the dollar value of the fees? Or also the other balances shown in the app?

This is how it looks for now:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/2ad70eed-b8e3-4336-8034-3f2fd6497f4f)

**Comment by aakashthumaty** [comment]
Dollar value for all balances/amounts shown in the UI - ty for the clarification.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect-mainnet.netlify.app/#

Attachment:

![Screenshot 2024-02-09 at 17 42 03](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ca64de74-083a-4999-bc5e-574c37e4893b)
![Screenshot 2024-02-09 at 17 40 19](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/63df898e-b8ff-47de-b550-26f8ff7c5914)

If more that two 0 are behind comma the value is shown as ~$0.00:

![Screenshot 2024-02-09 at 17 51 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/43083254-ba0b-451d-84f7-df276f9262ad)

![Screenshot 2024-02-09 at 18 33 49](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d1cb69b1-ae1f-4c7c-b520-c64adf493130)
