### ISSUE TITLE
[QA][Testnet] Arbitrum explorer site can not be reached

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1441]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.00001 tBTC from Arbitrum to Optimism
2. Click on Approve and proceed with transaction
3. When option is given click on Arbitrum Goerli Explorer
4. Observe

Actual result: "This site can't be reached" is shown when clicking on Arbitrum Goerli Explorer link

Expected result: Arbitrum Goerli Explorer link leads to transaction result page

Attachment:
[Arbitrum scan](https://testnet.arbiscan.io/tx/0xc09d5e22061f49bf4f09b8ca10963aef4c4332331f4fd9a1039257da165e609e)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/92bfbd50-1f88-4d2b-9bab-a141ce57032a

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
[Arbiscan](https://testnet.arbiscan.io/tx/0xf779ba8ce8c0ccf87b7e079eb7ec591687e15a5f8d30de59b8ebcec83b15cf09)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3bb2fd08-8298-4407-948a-6c00bf01e1f6

**Comment by tsadovska** [comment]
Arbitrum Goerli network is deprecated and cannot be selected on Arbirum explorer website. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7a0687c8-272a-48e0-9c87-3779d671a7e5)

Closing the ticket.
