### ISSUE TITLE
[QA] Token registration warning does not appear after user swaps From/ To sections several times

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1442]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.199 (Official Build) (arm64).

Steps:
1. Prepare to send 0.000001 tBTC from Optimism (Goerli) to Sei (Leap)
2. Check if token registration warning is displayed
3. Click on "Swap" button
4. Click on "Swap" button again
5. Check if Token registration warning is displayed

Note: Linked issue https://github.com/wormhole-foundation/wormhole-connect/issues/868 `[QA] Neither Approve button nor token registration warning are present when transaction details are entered`

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/379b068c-6f8f-4094-b522-3b8f87cba55d

## What is the expected/desired behavior
Token registration warning is displayed.

**Comment by AigaD** [comment]
Tested from: [Testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk%2BQhBTDJKGfMXKBYNXJg6CEAL4hTQA%3D#)
Issue reproduced from transaction from Sei (Leap) to Klaytn (Metamask) token registration message disappears after swapping networks places
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c381b4cb-327b-4ac7-ba65-d4014a80adff

**Comment by tsadovska** [comment]
Closing the ticket, because Optimism (Goerli) and Sei networks are no longer available on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).
Closing the ticket.
