### ISSUE TITLE
[QA] Some transactions offer only one route to choose from

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1444]
Preconditions:
Metamask wallet connected at sending From section
Leap wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: 
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/ - Tested NOK

Steps:
1. Prepare to send 0.001 ETH from Ethereum to Sei
2. Observe route section

Actual result: Only automatic route is shown for the transaction

Expected result: Both Manual and automatic  routes should be shown to the user https://github.com/wormhole-foundation/wormhole-connect/issues/1422

Attachment:

![Screenshot 2024-01-09 at 13 51 07](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32867529-fb3c-4657-83fb-cc2ff828b4b8)

![Screenshot 2024-01-09 at 14 59 52](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6b8c3b35-39d0-4426-80fb-719075684614)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
For transaction from Sui to Solana, only manual redeem route is offered.
Attachment:

![Screenshot 2024-01-09 at 14 24 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/78c4182f-0635-4878-b38b-a5a391556370)

**Comment by AigaD** [comment]
Tested from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# and https://wormhole-connect.netlify.app/#
Transaction from Alfajores to Arbitrum/Optimism only manual route is shown
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9324c2b0-078b-4fb4-bcce-3da56edb9c36

**Comment by tsadovska** [comment]
Closing as expected behavior.
