### ISSUE TITLE
[QA] [Testnet] Token registration warning is shown after token is registered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1445]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.199 (Official Build) (arm64).

Steps:
1. Prepare to send 0.00001 tBTC (Optimism Goerli) from Optimism Goerli (Metamask) to Sei (Leap)
2. Click on [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link on token registration warning "This token is not registered..."
3. Select Optimism Goerli as source chain and connect Metamask wallet
4. Enter asset contract 0x1a53759DE2eADf73bd0b05c07a4F1F5B7912dA3d (view tBTC on [Optimism](https://goerli-optimism.etherscan.io/token/0x1a53759DE2eADf73bd0b05c07a4F1F5B7912dA3d))
5. Select Sei network in Step 2 "Target" and connect Leap wallet
6. Complete Step 3 "Send attestation"
7. Complete Step 4 "Create wrapped token"
8. Refresh wormhole-connect
9. Prepare to send 0.00001 tBTC (Optimism Goerli) from Optimism Goerli (Metamask) to Sei (Leap)
10. Check if token registration warning is shown

Actual result: Token registration warning is shown after token is registered.

Notes: 
* Step 1 "Source": [Optimism etherscan](https://goerli-optimism.etherscan.io/token/0x1a53759DE2eADf73bd0b05c07a4F1F5B7912dA3d)
* Step 3 "Send attestation": [Optimism etherscan](https://goerli-optimism.etherscan.io/tx/0xeac5432589b49bc88fe7ac03aed0dd66f31028a838c2bf726a355feec3492f96)
* Step 4 "Create wrapped token": 58A107269F7DD7503652317251F81049AA12348BC95CFC1052E3938FA7049724

![Screenshot 2024-01-09 at 13 58 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f69db206-e5ad-4343-b3f4-9f8f1ac7da7c)

![Screenshot 2024-01-09 at 14 01 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/da25a1ad-ab90-4278-9bf3-e7dbb8e84f76)

## What is the expected/desired behavior
Token registration warning is no longer displayed.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Tested OK. Issue is no longer reproduced, token registration message is no longer shown after token is registered
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/72341b02-af70-491c-8d4d-d52e42e55586

![Screenshot 2024-02-13 at 17 01 00](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c20d3cd2-9a9d-40ed-899c-6ad5e00549d7)
