### ISSUE TITLE
[QA] [Mainnet] tBTC (Ethereum) is received instead of tBTC (Arbitrum)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1449]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.199 (Official Build) (arm64).

Steps:
1. Select Osmosis in From section
2. Select Arbitrum in To section
3. Connect Leap wallet in From
4. Connect Metamask wallet in To section
5. Enter amount 0.000001 tBTC (Ethereum)
6. Click "Approve and proceed with transaction" button
7. Click "Claim" button
8. Check if tBTC (Arbitrum) is received

Actual: tBTC (Ethereum) is received instead of tBTC (Arbitrum).

Notes:
* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/416CBB5C3FF22D7509D4AB63687E7F03E75222115750852DD1936CA787357B18)
* Send to tx: [Arbiscan](https://arbiscan.io/tx/0xb3d19f89d74cd05d20684bdbf32f19a28955ccd3d7b2ac72b1466283a422ca3d)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b7a1407c-fcef-4332-ab52-7629c777a576

## What is the expected/desired behavior
tBTC (Arbitrum) is received.

**Comment by kev1n-peters** [comment]
Transfer with payload is not currently supported in Connect for CosmosGateway so users currently will always receive the wormhole wrapped version of tBTC. Transfer with payload should be implemeted for CosmosGateway and supported in the tBTC route.

**Comment by aadam-10** [comment]
potential stopgap measure is disabling transfers of tBTC from CosmosGateway chains to canonical chains until transfer with payload support is added to the CosmosGateway route

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet] with the same scenario.
* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/4746317FA0A500BDE2AFBDE714EC82368FB89DBF8DABBD0D87DE13DD2938D47F)
* Send to tx: [Arbiscan](https://arbiscan.io/tx/0x975f89225e0468723bbc786d5024ff626a0e926dd153047db31154b68f5b5997)

**Comment by tsadovska** [comment]
Rechecked the issue, it is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the same scenario "Send 0.000001 tBTC from Osmosis to Arbitrum".
* Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/CF5A7840F6282665678D845F423C12060BFC9F0C2CA2E2049B597AFEAE6B0E70)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/0x5129c6c30f463b08c8715badfb087ad2368352337e08a04b4e2a85cb36b1b066)

**Comment by agodlevska** [comment]
Rechecked the issue, it is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the same scenario "Send 0.000001 tBTC from Osmosis to Arbitrum".

Send from tx: [MintScan](https://www.mintscan.io/osmosis/tx/173AEA44ADFB1E1ED01F312C789D9C1F63E030C7D1C87E90CDEF80F17FC70272)
Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/0xc5a2b2e8fa1c04124cabb9aceab8e48cae0919879c3dd4fb0dd00bad4c902e63)

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ with the same scenario "Send 0.00001 tBTC from Osmosis to Arbitrum".

* Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/57388ECD14D0B9EA2E4C8AF5704C1C88D16E4DEC478342F860AC0603C9EDCD51)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/0x470a833e1dd237eb7a01b2e6f5ab4df1c39ff203e9eb1e6dd302e56de92a5d75)

**Comment by tsadovska** [comment]
Closing the ticket, because Cosmos chains are no longer available on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
