### ISSUE TITLE
[UX] Remove connected recipient check

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#1450]
When redeeming a transfer a check is performed to make sure the connected wallet is the same as the transfer recipient. While it makes sense for 99% of the cases, some users might want to use a different wallet to perform the redeem, which the check prevents them of.

A UX improvement for these cases is to straight out remove the validation.

### Open Questions

Should we still keep the check, but only as a warning, and let the user skip it?

**Comment by aadam-10** [comment]
should be considered as part of the redesign
