### ISSUE TITLE
[QA] Cannot register tBTC asset for transaction from Aptos

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1453]
Preconditions:
Nightly wallet connected at sending From section
Leap wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.00001 tBTC asset from Aptos to Sei
2. Observe that token need to be [registered ](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register)
3. Click on[ register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) button
4. Select Aptos as source chain and connect Nightly wallet
5. Paste in the tBTC address ( 0x6e2d5d1a6d6d0e0c5db506ce64ead0530847a48b96516abbb08cdebe43fe3036::coin::T )
6. Click Next
7. Select as destination chain Sei network
8. Connect leap wallet
9. Click Next
10. Click Attest
11. Observe

Actual result: Token registration fails, message `invalid hex string (argument="value", value="0xNaN", code=INVALID_ARGUMENT, version=bytes/5.7.0)` is shown

Expected result: tBTC token is registered for transaction Aptos to Sei

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2baf6e86-3819-4d44-ad2a-a43e4218c0a7

**Comment by AigaD** [comment]
Will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1668 is solved

**Comment by AigaD** [comment]
Cannot connect to Nightly wallet: https://github.com/wormhole-foundation/wormhole-connect/issues/1821

**Comment by tsadovska** [comment]
Closing the ticket, because Sei network currently is not displayed in the networks list on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).
