### ISSUE TITLE
[QA] [Testnet] Incorrect text on Route option when sending asset to Sei

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1455]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.199 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001 ETH from Goerli (Metamask) to Sei (Leap)
2. Check text on Route option

Actual result: Text "Manual Bridge "Receive tokens automatically"" is displayed on Route option.

<img width="593" alt="Screenshot 2024-01-10 at 17 35 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c091c8e7-4384-4929-9a66-deb8103f980f">

## What is the expected/desired behavior
"Manual Bridge "Approve transfer with destination wallet"" and/ or "Automatic Bridge "Receive tokens automatically"" options/ option is/ are shown.

<img width="528" alt="Screenshot 2024-01-10 at 17 34 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/53df4f10-5df4-43f8-af30-ef1e6feeef7e">

**Comment by AigaD** [comment]
Preconditions:
Exodus wallet connected at sending From section
Keplr wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# and https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SOL from Solana to Sei
2. Observe Route section

Actual result: Route section shows Manual bridge, but color identification and text "Receive tokens automatically" suggest that it is automatic bridge

Expected result: Should be automatic bridge identification 

Attachment:

<img width="903" alt="Screenshot 2024-01-26 at 14 17 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a462085e-e5d7-4209-84b6-c52a1d28ee44">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced for transaction when sending KLAY from Klaytn to Sei
Attachment:

![Screenshot 2024-02-07 at 13 47 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b1765147-6e63-4266-aa5c-773422f6590c)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Incorrect Route section when sending asset from Fantom to Sei
Attachment:

<img width="1159" alt="Screenshot 2024-04-09 at 13 41 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9e47648f-ffa7-4990-8d0b-ef09f01c5713">

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect.netlify.app/
Incorrect Route section when sending asset from BSC to Sei
Attachment:
<img width="712" alt="Screenshot 2024-06-12 at 09 58 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/c79f6e28-7e3c-468c-a285-868be6d0fc0b">

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect.netlify.app/
Incorrect Route section when sending asset from Avalanche (and any other network) to Sei
Attachment:
<img width="686" alt="Screenshot 2024-07-02 at 13 23 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/38b90208-bb12-436f-b3c9-faa558287aa9">

**Comment by agodlevska** [comment]
Still reproducible on https://wormhole-connect.netlify.app/.
Incorrect Route section when sending asset from Moonbase (and any other network) to Sei.
Attachment:
<img width="655" alt="Screenshot 2024-07-25 at 11 17 59" src="https://github.com/user-attachments/assets/1b1923a1-19e4-4f4b-9daf-70fd711eaae9">

**Comment by tsadovska** [comment]
Closing the ticket, because Sei network is currently not displayed on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).
