### ISSUE TITLE
[QA] Link <Add token to your wallet> suggests to add unrelated token

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1459]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.216 (Official Build) (arm64).

1. Send 0.0017 ETH from Ethereum (Metamask) to Arbitrum (Metamask) with ETH Bridge
2. Check that ETH (Arbitrum) on Arbitrum is received
3. Click on link "Add token to your wallet"
4. Check what token is suggested to be added

Actual result: Unrelated token WETH (Arbitrum) is suggested to be added.

<img width="1151" alt="Screenshot 2024-01-11 at 11 29 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ec3641f1-7f38-42b3-8b10-3f8de6d6cd4b">

## What is the expected/desired behavior
Link "Add ETH(Arbitrum) to your wallet" is shown or link is not displayed.

**Comment by kev1n-peters** [comment]
Should be resolved in https://github.com/wormhole-foundation/wormhole-connect/pull/1457

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0023 WETH (Polygon) from Polygon (Metamask) to Ethereum (Metamask). Unrelated token WETH is suggested to be added. User receives 0.000174 ETH (Native).
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x47c116ded1f1a5c88e4de374ff51b5ca5d27fcc179a2d20d1df28a031b21caff)
* Send to tx: [Etherscan](https://etherscan.io/tx/0x1fa83b52c7f4421d89ccee1d3de3ed52d4d64b195784f46ab2d411c95de38beb)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x47c116ded1f1a5c88e4de374ff51b5ca5d27fcc179a2d20d1df28a031b21caff)

**Comment by AigaD** [comment]
For transaction ETH (Base) from Base to Optimism, WETH token is suggested to be added when ETH (Optimism) token is received.
Attachment:
![Screenshot 2024-01-12 at 17 35 52](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ea6d84a9-fc2d-4fc9-9bfc-1f75400055e1)

**Comment by AigaD** [comment]
Transaction ETH (Optimism) from [Optimism](https://optimistic.etherscan.io/tx/0xe597ad89b11eff838946fc3de12ecd2f9fbbd97dea51df94d2161607e34448f4) to [Ethereum](https://etherscan.io/tx/0x7c3ed183aa0996d3e144040b1e0fbd4e9dbdfab7fa73bef8ff4a521c39e926bf), adds incorrect token and balance.
User received 0.00030293 ETH (Ethereum), but added token suggest a total sum of the added token - 
0.00001 WETH

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/828699cd-4df8-4973-a1e2-3c8e04f80abe

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Link "Add token to your wallet" is not displayed when sending:
* ETH (Ethereum) from Ethereum to Arbitrum. User receives ETH (Arbitrum). [Etherscan](https://etherscan.io/tx/0xec3ba9ae78afc352ca3cac2d1a0745916176120c55599de7288e4b898af325c5), [Arbiscan](https://arbiscan.io/tx/0xb4dd9d142216e831973abb44c5e2fec58cd051653b370bfb6ef9810b23becb28).
* WETH (Polygon) from Polygon to Ethereum. User receives ETH (Ethereum). [Polygonscan](https://polygonscan.com/tx/0xbee44922bd19d7caea42eb8ee0b294fb4a8ad24856edf03789307a910d86be6d), [Etherscan](https://etherscan.io/tx/0xc90871b598b046ece0cbb57c7b5d55ea077c8807376da4295a2bae953f001498).
* ETH (Base) from Base to Optimism. User receives ETH (Optimism). [BaseScan](https://basescan.org/tx/0x903480628939cca78e7cc407215732a52343e35989f57ba1a60933ca925fab70), [Optimism](https://optimistic.etherscan.io/tx/0xaa7dde6ccca32e8352b146d3eb82a61e077cefc3a6e050a5d87d7fcb4d5c30db).
* ETH (Optimism) from Optimism to Ethereum. User receives ETH (Ethereum). [Optimism](https://optimistic.etherscan.io/tx/0xcf2d35f1b0a385bfa55f27351f56fc041a614d5ce2486727e52ee845f08c5915), [Etherscan](https://etherscan.io/tx/0x8adb301e36157064589d81ffba99dd11f00b9ab3390a6d20dbe5897b6bcb57ff).

Ticket is closed.
