### ISSUE TITLE
[QA][Mainnet] Error computing receive amount

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1461]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: 
https://preview.portalbridge.com/bf7b5b43a8/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
1. Prepare to send 0.001 wstETH from Ethereum to BSC
2. Observe

Actual result: Message "Error computing receive amount" is shown and user is not able to continue with transaction

Expected result: User is able to continue with transaction

Attachment:

![Screenshot 2024-01-11 at 13 47 27](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/53dc1b6b-64a1-47ed-b370-f0894011c2ca)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/35c92db9-f071-47ca-98b9-73598a7fd50e

Comments: wstETH (BSC) is automatically selected as the receiving asset, if it is manually changed to wstETH (Ethereum) user is able to continue with transaction

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c040d96f-6863-45bb-82ab-5195cdcf6207

**Comment by tsadovska** [comment]
Issue is also reproducible with following scenario:
1. Prepare to send 0.0015 ETH (Arbitrum) from Arbitrum (Metamask) to Base (Metamask)
2. Click "Approve and proceed with transaction" button
3. Click "Cancel" button on Metamask notification to change network

Actual result: Warning "Error computing receive amount" does not disappear after user swaps networks, disconnects/ reconnects wallets again, changes amount.

Checked on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet].


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a908dab4-d7b7-4f5a-8673-aad5801f90fe

**Comment by kev1n-peters** [comment]
There is no wstETH pool deployed on BSC yet

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending WETH (Polygon) from Polygon (Metamask) to Base (Metamask). "Error computing receive amount" appears after Metamask notification is closed or canceled. Error does not disappear after changing amount in "From" section or changing asset in "To" section.



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8a7a9584-eb4d-43e6-9fc4-3733a911bb72

**Comment by aadam-10** [comment]
this seems like a different issue to the original one, created a new ticket for it https://github.com/wormhole-foundation/wormhole-connect/issues/1473
