### ISSUE TITLE
[QA] Network is not included in the brackets for total sum after fees

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1468]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from:
https://wormhole-connect-mainnet.netlify.app/# 

Steps:
1. Prepare to send 0.0023 ETH (Base) from Base to Ethereum
2. Observe after dee sum in the Route section

Actual result: Sum after fee is shown with the token name, but without Network in the brackets

Expected result: Sum should be shown together with the network name in the brackets 

Attachment:

<img width="700" alt="Screenshot 2024-01-12 at 16 21 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a415c113-62f9-4f53-99b5-4f8631e9efca">

<img width="892" alt="Screenshot 2024-01-12 at 16 20 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5f3fa901-db1a-4a52-8bc6-d962826f32c7">

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/ and https://portalbridge.com/. 
The issue no longer reproduces. Closing the ticket. 

Attachment: 
<img width="727" alt="Screenshot 2024-06-12 at 09 40 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/62071c10-c159-40dd-bdb5-6b29d03e07ce">
