### ISSUE TITLE
[QA] Pop-up "This transaction will take up to 24 hours to complete" is shown after amount is entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1469]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.216 (Official Build) (arm64).

Steps:
1. Select Base network in From section
2. Select BSC network in To section
3. Connect Metamask wallets
4. Select ETH (Base) asset
5. Type amount 0.001

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f100627f-f9a3-44d7-ad91-9addebade9e4

## What is the expected/desired behavior
Warning is shown after user clicks on "Approve and proceed with transaction" button.

**Comment by aadam-10** [comment]
Governor limit for Base was hit yesterday, so this indeed was the expected operation. You can check the current limits and the remaining daily amount here under the governor section: https://wormhole-foundation.github.io/wormhole-dashboard/#/
