### ISSUE TITLE
[QA][iOS] Can not connect to MetaMask through Connect Wallet - MetaMask

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#147]
Preconditions: 
MetaMask wallet installed to the device
Wallet is not connected to the app

Environment: 
iPhone 11 (iOS 15.4.1), Chrome Version 110.0.5481.83
iPhone 14, iOS 16.0, Safari

Steps:
1. Open wormhole-connect.netlify.app
2. Click on Connect Wallet
3. Click MetaMask
4. Observe

Actual result: User can not connect through MetaMask option, the option is unresponsive.

Expected result: MetaMask option is responsive and user can connect to the wallet.

Comments: User can connect with MetaMask if first clicking WalletConnect -> MetaMask

Attachments:

https://user-images.githubusercontent.com/91047061/223050293-e2ff3f39-3c59-479f-9640-aa35cab764d9.MP4

**Comment by M-Picco** [comment]
The Metamask option is to connect through the browser extension, which is not available for mobile browsers and therefore not installed on the device. I think the issue is that it's not properly checking that it is not detected, and shows it as installed anyways.

**Comment by AigaD** [comment]
Closing this.
"Install Metamask" is shown in the wallet list and the button is responsive, but not detecting when the app is already installed to the device - https://github.com/wormhole-foundation/wormhole-connect/issues/606#issue-1705275741
