### ISSUE TITLE
[Feature] Support Metamask Snap for Sui

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1471]
## What is the expected/desired behavior

- Support connecting to Sui via Metamask Snap
- Requires https://github.com/XLabs/wallet-aggregator-sdk/pull/22, which should be in `0.0.1-alpha.9` of `@xlabs-libs/wallet-aggregator-sui`

**Comment by tsadovska** [comment]
Scenarios - Tested OK:
* Send MATIC from Polygon (Metamask) to Sui (Sui Metamask Snap) with automatic route: [Polygon](https://polygonscan.com/tx/0x548b6609f4d74553e3b910c9df2712eead8e4ba82d058c4ea96bae142ed448b4), [Sui explorer](https://suiexplorer.com/txblock/7v8Sgyx6C5FFxDUL6oCSSYnanpNxr1qBc1X7meveG97C)
* Send SUI from Sui (Sui Metamask Snap) to Avalanche (Metamask) with manual route: [Sui explorer](https://suiexplorer.com/txblock/HW7akhj6yUvPcprZRqSjKQwCKjxxdHzh3CEBa3t5R3vt), [Avascan](https://avascan.info/blockchain/c/tx/0xbd6e21bc9142dfc28040b3e5cfea911a7d8f6c2a439b21c7ff5567e43f88f4b8)
* Send SUI from Sui (Sui Metamask Snap) to Solana (Solflare) with manual route: [Sui explorer](https://suiexplorer.com/txblock/EV3xZKcrcmi9JuX29uFssqnYx9zbUHK79bTgR26osBYj), [Solana](https://explorer.solana.com/tx/3o2YCRGvWyUE1gQZnbWxBNxEvnD5wXU2i3xfZtm6T56T98P3uFztGbqxwCkcnp6NzinnDHhSeVTUXXZr4Mp7pYqr)

Issues noticed during validation:

- https://github.com/wormhole-foundation/wormhole-connect/issues/1528 
- https://github.com/wormhole-foundation/wormhole-connect/issues/1532
