### ISSUE TITLE
[Feature] Add support for Solana Wallet Connect

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1472]
Should be enabled by https://github.com/XLabs/wallet-aggregator-sdk/commit/f54732b02af36c8d67c6fc156554af1469641e95

`0.0.1-alpha.14` of `@xlabs-libs/wallet-aggregator-solana`

**Comment by Eiei070922** [comment]
Excuse me. If I want to consult with someone, who can I talk to?

**Comment by tsadovska** [comment]
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/1508. Cannot connect wallet with "WalletConnect for Solana" when scanning QR Code from Phantom app.
