### ISSUE TITLE
[QA] "Error computing receive amount" appears after Metamask notification is closed or canceled

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1473]
Reopening the ticket. Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending WETH (Polygon) from Polygon (Metamask) to Base (Metamask). "Error computing receive amount" appears after Metamask notification is closed or canceled. Error does not disappear after changing amount in "From" section or changing asset in "To" section.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8a7a9584-eb4d-43e6-9fc4-3733a911bb72

_Originally posted by @tsadovska in https://github.com/wormhole-foundation/wormhole-connect/issues/1461#issuecomment-1889009339_

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#

Attachment:
![Screenshot 2024-01-16 at 15 56 52](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d8eaf2d-241a-4d58-a645-96d995b20c49)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2283f830-87ec-4976-932d-05034a432aee

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] when sending wstETH from Optimism (Metamask) to Ethereum (Metamask). "Error computing receive amount" appears after Metamask notification is closed.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6d2f5f52-a746-441f-af28-1abc1d85b227

**Comment by tsadovska** [comment]
Re-checked scenarios mentioned in the ticket on https://portalbridge.com/. Issue is no longer reproducible, "Error computing receive amount" error does not disappear after closing MetaMask notification. 


https://github.com/user-attachments/assets/ea68d3cb-028d-4e71-ad22-e4ffb00cab32



Ticket is closed.
