### ISSUE TITLE
[QA] [Mainnet] Asset balance not loading for second transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1478]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.0013 ETH (Optimism) from Optimism to Arbitrum
2. Click Approve and proceed with transaction
3. Wait until the transaction is completed
4. Click on "<" Bridge button to go back to Home screen
5. Connect Optimism Network
6. Click assets
7. Observe

Actual result: Asset balance is not loading

Expected: Asset balance is loading

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f9c1056-92b0-410b-b836-75fb60637f8a

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c4d9ab86-c47d-4c9c-905a-91c7436988f0

**Comment by AigaD** [comment]
Issue is still reproducible.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://portalbridge.com/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4607182d-dec3-439a-ba35-ebdbabc92b75

**Comment by AigaD** [comment]
Issue is still reproducible. Tested from: https://wormhole-connect-mainnet.netlify.app/#
Balance is not loading for all assets for second transaction.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/12b88ecf-b4c6-4c90-ae76-7ecf1c66c580

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/#
Balance for all assets is not loading after clicking on Bridge more assets when transaction has been completed.
Attachment:

![Screenshot 2024-03-08 at 11 31 05](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dadbcd8d-6d19-43a6-8f6a-297ecc7449e7)

**Comment by Eiei070922** [comment]
Thank you so much 💗 🙏

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eiei070922** [comment]
Could you please tell me the details? I'm afraid I'll make a mistake.🙏🥰

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eiei070922** [comment]
Why are there emails from so many places that say they will help me with assets but I haven't responded?

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eiei070922** [comment]
Hello, I'm Thidarat. I'd like to cancel all of my Genius contracts. Is that possible? I don't have much time to continue playing.🙏💗

**Comment by AigaD** [comment]
Closing, tested ok.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Balance is loaded for second transaction in a row
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f60cf41e-294b-4080-87f1-a85758948e93
