### ISSUE TITLE
[QA] Wrapped instead of Native token is shown for the Network in available token list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1479]
Preconditions:
Metamask wallet connected
ETH (BSC) asset added to BNB Network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect BNB network
2. Open asset list
3. Check if ETH (BSC) asset is displayed

Actual result: In wallet it shows as Ethereum token, but in Wormhole Connect asset list WETH token is displayed

Expected result: ETH (BSC) token is shown in available token list

Attachment:

[BSC explorer](https://bscscan.com/tx/0x7e697c240f9488c91b61dbf6720de1ffa48ce8660942c51fc905df9b0f3abbac) regarding added token

![Screenshot 2024-01-15 at 11 53 48](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3bff4928-6a26-4df5-9603-1949ba918d4a)

![Screenshot 2024-01-15 at 11 53 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4bab8833-3695-444d-84a6-5c787d244085)

**Comment by tsadovska** [comment]
Issue is no longer reproducible.
The same token name is displayed on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZQJgAsmgCeaaOKo0iEVm2i5cW6nQAUoPXtzkA1jHphLVvYIwATcqIDutXJ2EACUZmFwhnMKsAYwALTGhEJE5cGMhSSEoUQlDIsHRoNABzNMSABgAPACMATgAWAA40aoBmeoAmAHZ3ADZG9u5ugFYARmbed2GO%2Buru2vY0Bo6AM0g2gCF2auzcqxt7BOQK5ebqgGFB%2BuHuQerBtcHmqMGoyuHqyvZSyual%2BvdebpRFqDThtU5oUrbHYQXCkDS0KKQDCwEpgJjQqwRDEQNDudzpWiOJAVXjDXinU7DSDdSDuNBrNqXbiQSruarDTjNEaDUotbjDLhMtrPSG6bHWVQAB0giW85FIKBi5AANpAodiAL5i6EAXW1kS1ORcWNysXiiTWCPVO3yRVRxPK3WqTMG3Tawydw1OayWnPY7nYgzatXcnA6w1KHW6lQ61W4pV4pU69WtuT2MDK5TagMGkFKwyDIbanDd9QTDW4bSepSWA3YkA6kCDnBmwy9qcisPhiORqPR4pNGNx%2BLoRIqlUgzW4jdKvQ6xdK7gGp3YHW43C5aw6aAWa1etVq3XYp2qzu6HehuClMuQcoVStVF4N%2BtyeqNVkNr5fegA6iFoYOYRmlgiRyCqGhoE%2BVi2sUpCJAAcsIuC8Gg5DsAAUjE9iBJAaAAGr8IE0CqDE3iVAACvBvDwd0P6FGskqBLYgRrMIUTdO4HSwIIADSUHWHYGbIPUgx4Ws3AAIoAFonsIUm2EsaCSrgaw%2FgAVrA%2FDeB0ACalRSWpqhBgCKBqbg5EAOJqX4Em8CgEn8TCcLQAiSIonBaLvpEgE7MOBJEohyGoRhWGQDh%2BGEcRpEUVRNF0QxTEsWxHFcbxjkuFe0qyvKioqmq365J%2BGJvtiACOlDkDQHlIPBpU9AAGqVvD1IIlS0KclAWfUSiCD%2BP6UOR9RDPBeHdGp4jDEolT1ZAPHlOwtSBLxGH8UVuQ%2BdEcQgcgySpOkmTpTB9oVFEkbrGSnBLM0zQ0v6TbVImtQzKel21JA9TcE0gZ1LwDTpemBwOmsNafWWpSlPUQ1NmuQ14kGsw1BcbSVG04z1B0KM1MM%2F3Oa5vYef22IbZEfmjpm7CVIMgxPW0nFvKU7DDJUaCcPU5KVJwpQnG2py1JyYa1Nm6OlFE6W7Ne2X3nlYtgGtOwlTscthMTEDAYDvCkJUGCwgdBUuEd1UVA813uAmUQArUCw8uMPTMtOR5HqMHSDNO2beg0tT%2FYJgMVMDtZoGDENQ4MMMce48O1Ij7Qo2jGPI%2ByOPdm5fZecrqck3i%2Fnk8MAe8GsTp5km3Q0vUW7smgBZrLzzvDLUBZjDytSDGg5562mEu3jlD75enH5t3oCuFf3KtgGriSSMpGAoBgtBZP3EAG5mOe1PyaCxjWbRTksNQdPOMyAvnG4cacPQXFzzSQKMXv7Jmfug%2BDQc0iH3Cw%2BH2aR7c0eo%2B46OYwn89gC7C5Hs7l%2FwDl7i4UmhJMzvHYPUGMlNOinF%2BtSDorQogbHpEuEYpw2jBmLs7bokZmjuBljCDuSA7y5UfAAiAStIiD2fOnEeY9kBrDQLQHu2JF6HHKMbEhZsLZWwTHibodsozsEds0Z2rtuju3qJ7ABANb4gwDg%2FSGT9Q5w3flHZG39f7x2xko3GICU7iicBAqwUCxzzRzmzfO1RC7ZhLmXHOldq4jDrg8Xgjdm6t0sRKLKncpY0ICfQsIjCwjhLAJE2W%2BoNQAEoxRvhIJQTh4haR0AwIUA4OtIBEBIADdq5BoBLGyYgLEvh%2FBBDalECpRp7CqFlH4AIgRakdloKoFAlQVTNOqYEDsBRcC9lOFtQGlpRbfgBgASXcPU00YyLRWj1tYzM2Ynh5gLMGdwxZSzlg%2BlWHktYjwNibMWVs7Zvz0IwFEEpiQYhGElPQAA9M8jhnDcC0BYLcrAxQoi2HIN88gKBnk%2FJcs8qedpaDPOGJDZotRnl%2BA0HSUg7hnlVNaSwSU0BCgdjBRZSA%2FzyCzNlHCSU0p3AAFo%2FB4BiHilU8pEgAGIxi8CnNwDs7hCWQuVI4WF8T9Q%2FloOBAo8yXCNMSEKkVkFvydO6b05AP5BloGGSiUZ5pkBgWVBBDsMy5kWIWRqpAWqdUrMzmTYSolxLSVkvJRSylVIaS0rpfShljLdFMuZKyNk7IOSud%2BG5dzkAPNwE8%2BArz3l4C%2BWCv5AKgUgrBdCyFxRoVcghh0RFuBkVoFRei4FpBu6iGVOQQoXgliUGVMqUQtzi2kFEKQQolRRBtAfpKcooh5zkowKIbeUZuhoCiCJNAWKcUAH5JgQ16NMam9KsAEqJSS4J1CuEuC5VEHljhugCtCD%2BWlaQMgoDFVYCViq937TnkaOVPTlSSuVaqyA6rtpJBSPu3WRo9VHpcKw59e0D1PlWbwu%2BajwYaOhi%2FMOEddExx%2FnHLGHZrm3MBiGsNEbCRRqBb8wlcbbkJvIFgJN6AU3PLTejTN2bc1yhQAWvKRaS1lorVWmt8p62Nuba29tnbJTdt7cXAdQ6R2FHHR0SdkNbiKKNPirDxL9WUK7tLb8a6N2IH5aEOWP4c1ax1oeg14rIBNMVRp7WpA31hCvQqpASrvxDJGYs5AGtNPGYvWED9OmgK2aQPZozJmM4jmgYB1RgdQPP1fpBz%2BejY5%2FyMUaBDQakDIZeW8tDnyMM4qk%2FG0FeHwXJroMRnkpGkXQBRWiyj1HVS0dLT2hj1aGV1obU2lt4M20draF2ntMZeODubgJoTInp3iaApl%2BdALF2yZCSuqwin0C8uU%2FUbdVgfzkEntPWen6IAnos4t4Zy2nMuDMzexVd6bNGonltmeO3dje0XT5b9J2p5nf%2FeavzQMAvqODlot%2BCMwvQYMXB%2F1RpA1IceQlyNyWY1pZwxl%2FDELCM5ZIxmgrRW81UcLcWir5bK3VdrSx%2Br7HmutZ4%2F2zrw7sWCYnUNUTM7vySYXTJqh3dOXcqm3y2bqnBXM04atsA62fzs%2FG3oPbt6rMqqO0%2B9hnDdWXf1dd9zYu%2BdWMezYoDgW3vge0Z9pG33YP%2F2iwGxD9ygfhsSx86NmXY2Aoh4m6HULcvprI4VnNxX80o7o5VjHTHausYa6UJrnHuPtcJ%2FxknPXyd9dndAIb0nJbLoZ%2BupnM25txJABqAA3EAA%3D%3D%3D) and in MetaMask wallet. 

![image](https://github.com/user-attachments/assets/b90ca0eb-4efa-41c1-83a3-9896e818502b)


![image](https://github.com/user-attachments/assets/9917ff75-0c87-4604-8438-5ceca2ff271b)

Closing the ticket.
