### ISSUE TITLE
[iOS] UI at Sending to section disappears when Network at Sending from is selected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#148]
Preconditions:
Wallet is connected

Environment:
iPhone 14, iOS 16.0, Safari

Steps:
Click on Select Network at Sending from section
Observe the UI next to both Token sections and Select Network at Sending to section

Actual result: UI disappears.

Expected result: UI stays until sections are changed.

Attachment:

https://user-images.githubusercontent.com/91047061/223054488-cc3d6941-0439-42a7-982b-70c22d26f4eb.MP4

**Comment by tsadovska** [comment]
Will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Issue is still reproducible, Network UI disappears at sending To section when user selects Network and asset at sending From section.
Tested from: https://wormhole-connect.netlify.app/
Environment: iPhone 14, iOS 16.0, Safari
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/387be1d0-4449-468e-9961-959175609873

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Checked on iPhone 11 Pro. 

![Screenshot 2024-06-10 at 15 16 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d1c89350-ba39-45f0-955d-152b0a3df04b)

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2). Checked on iPhone 11 Pro.

![Screenshot 2024-08-15 at 16 45 29](https://github.com/user-attachments/assets/54bcd11e-5498-4979-8dc7-63d129e856ba)

**Comment by tsadovska** [comment]
Please view following tickets:
* https://github.com/wormhole-foundation/wormhole-connect/issues/2912
* https://github.com/wormhole-foundation/wormhole-connect/issues/2911
