### ISSUE TITLE
[QA][Mainnet] Token registration message is shown when wallet is not connected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1480]
Preconditions:
Wallets are not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. At sending from section select Optimism Network
2. Connect Metamask wallet at sending from section
3. Select Polygon network at sending to section
4. Select wstETH asset from drop down list at sending from section
5. Observe
6. Connect Metamask wallet at sending to section
7. Observe

Actual result: Message " This token is not registered, you must [register](https://www.portalbridge.com/#/register) it before you continue. Newly registered tokens will not have liquid markets. " is shown before wallet at sending to section is connected and the message disappears when the wallet is connected

Expected result: Message " This token is not registered, you must [register](https://www.portalbridge.com/#/register) it before you continue. Newly registered tokens will not have liquid markets. " should appear when network, asset is selected and wallets are connected and also only if the token is not registered

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2432e3e0-2fb9-49f3-92d6-31bc2e0b3a21

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect.netlify.app/
Token registration message is shown before second wallet is connected, after connecting the wallet registration message disappears 
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/77d91141-5475-46a3-90d3-51514d677e6f

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
Metamask wallet is not yet connected for Klaytn Network when message to register token is shown, after connecting wallet, message disappears. But the token for the chain need to be registered in order to continue with transaction 
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a549152f-8fc0-4813-8bed-9c2853059a07

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Token register message is shown before wallet at sending To section is connected
Attachment:

![Screenshot 2024-02-28 at 10 02 05](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b18f4d2a-4c70-4e8a-873b-4e562d700357)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Token registration message is shown for transaction USDC from Mumbai to Alfajores, when wallet for Alfajores network is not yet connected
Attachment:

<img width="1226" alt="Screenshot 2024-03-20 at 09 01 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d4dfde55-84ef-4604-936b-91cf7f9c2a9f">

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/#
Token registration message for transaction USDC from Fuji to Arbitrum Sepolia is shown when wallet for Arbitrum Sepolia network has not yet been connected.
When connecting the wallet the token registration message disappears, but user is not able to start the transaction
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/518fc5c1-4356-4a37-8a69-c41eb7ed591e

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Token registration message is shown before connecting wallet at sending To section
Attachment:
<img width="1163" alt="Screenshot 2024-05-14 at 16 28 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4835223c-438d-40c8-94c2-c2a70e761726">

**Comment by tsadovska** [comment]
Scenarios mentioned in the ticket are no longer reproducible on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Closing the ticket.
