### ISSUE TITLE
[QA] Cannot connect Metamask wallet to register asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1482]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.216 (Official Build) (arm64).

Steps:
1. Prepare to send SOL from Solana (Phantom) to Moonbase (Metamask) 
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in warning "This token is not registered.."
3. Connect Phantom wallet
4. Select SOL asset
5. Select Moonbeam network
6. Click "Connect" button 
7. Select Metamask option
8. Check if wallet is connected  

Error:
```
Error: User rejected the request.
    at Xi.<anonymous> (<anonymous>:7:4037)
    at Generator.next (<anonymous>)
    at f (<anonymous>:1:1048)
```

Note:
* Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1373

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b7367ade-223b-4acf-975d-b947875f1e5c

## What is the expected/desired behavior
Metamask notification to connect to the page does not appear.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer [Testnet]. Warning "Wallet not connected" is shown and requests do not appear in MetaMask extension when user clicks on "Connect" button in Step 2 "Target". 


![Screenshot 2024-02-13 at 14 26 48](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d65520ca-9ac8-4775-8caf-61308570f5ea)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
It seems that it is not possible to connect Metamask wallet, if Exodus wallet is enabled
Attachment:
Exodus wallet connected: 

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d10be308-88a1-40c8-9727-9eef4f19afb2

Exodus wallet disabled:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0bde4565-71c7-4788-b1a1-fe89056e2886

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Issue reproducible, cannot connect Metamask wallet to register asset `Error: User rejected the request.`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/79ab3d52-e81e-4d9a-936b-89a92c996927

**Comment by tsadovska** [comment]
Issue is no longer reproducible. SOL transfer from Solana (Phantom) to Moonbeam (MetaMask) was successful. Checked on https://portalbridge.com/ [Mainnet].
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/3ed1ChA5Gm5YPMYHBFUJyCi7sFRmGqDEhS6hnXhgWYV9mVp53e71B71gC4n8ybn1pB4rZJTbjekY6QHUaGcd9eAh)
* Send to tx: [Moonscan](https://moonscan.io/tx/0x04fa378c42ff9404a98f415a3e0724deaaac2d69bba54dfd882378aad78001ae)

![image](https://github.com/user-attachments/assets/d526d0c8-841b-4321-a0fa-52cd0b588e71)


Ticket is closed.
