### ISSUE TITLE
[QA] Sometimes link "Add token to your wallet" is not displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1483]
## Describe the current behavior in detail
Checked on https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 14.2.1 and Google Chrome Version 120.0.6099.216 (Official Build) (arm64)ю

Steps:
1. Prepare to send 0.0007 ETH from Ethereum (Metamask) to Avalanche (Metamask)
2. Check if link "Add token to your wallet" is displayed after tx is completed

Note:
* Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/975
* Issue is no longer reproducible after transaction is resumed
* Send from tx: [Etherscan](https://etherscan.io/tx/0x84122afe197b00f0a4b96439faac7b9ff6b058cfbec7fb125f420c0353e9dd9b)
* Send to tx: [AvaScan](https://avascan.info/blockchain/c/tx/0xd70de12137a4917c1f2035fbb6557477e2621ddbc8d7fe82881220dc89446a3a)

![Screenshot 2024-01-16 at 10 51 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4d2da68f-55de-496c-b9d4-18017596bc35)

## What is the expected/desired behavior
Link "Add token to your wallet" is displayed.

**Comment by kev1n-peters** [comment]
The ETH Bridge route will not show an "Add to Wallet" button when the asset received is the native gas token

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
* Send from tx: [Etherscan](https://etherscan.io/tx/0x63c7c0cffa1db81311d46f14b5513fe0ee01b85c502a6597e8ac642ea20b02b2)
* Send to tx: [Avanscan](https://avascan.info/blockchain/c/tx/0xf34d3f45ff9a21f856a3574ad4900e264df0550c541dd07d8cdef1348269e0f9)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9119e387-2c5b-453f-bf0e-a01a24598f60)

Ticket is closed.
