### ISSUE TITLE
[QA][Mainnet] Wrapped Ether token shows as Native in the asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1485]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.0015 WETH (Avalanche) from Avalanche to Base/Optimism
2. Click Approve and proceed with transaction
3. Wait until the transaction is finished
4. Add WETH token to the wallet
5. Open Base scan / Optimism explorer
6. Check the received token (name, contract address) 
7. Go back to Bridge screen
8. Select Base/Optimism Network
9. Connect Metamask wallet
10. Open asset list
11. Search for WETH (Base)/WETH (Optimism)

Actual result: In the list the token is shown as Native although it is Wrapped Ether token, both tokens have the same contract address - 0x4200000000000000000000000000000000000006

Expected result: Token shows as wrapped

Comments: 
From my transaction 0.0015 WETH(Avalanche) from [Avalanche](https://avascan.info/blockchain/c/tx/0x8d91442366e73c582efa15bb8f8eb0d609d090f57d452006c25cde65d381756f) to [Base](https://basescan.org/tx/0x1187565d493307e8dab302ab923ba1fb33201372ec7e00189ba261cc54f18b5e) links

[BaseScan](https://basescan.org/token/0x4200000000000000000000000000000000000006?a=0xd493066498ace409059fda4c1bcd2e73d8cffe01) for the received Wrapped Ether token
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6e70ed75-e603-4a36-a8cc-3924f27ff1e7

![Screenshot 2024-01-16 at 16 23 12](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f9b3470-70a2-4f2f-9852-b8752c0fa5d0)

**Comment by kev1n-peters** [comment]
This WETH token is actually native on Base, so that's why it says native in the video.

**Comment by aadam-10** [comment]
expected, explained over slack
