### ISSUE TITLE
[QA][Mainnet] Wormholescan shows status Completed while confirmations are still loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1486]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.0006 WETH (Polygon) from Polygon to BSC
2. Click Approve and proceed with transaction
3. While confirmations are loading at approximately 312 confirmations done from 512 click on Wormholescan
4. Observe

Actual result: Wormholescan shows status Completed while confirmations are still loading

Expected result: Wormholescan shows status Pending while confirmations are still loading

Attachment:
[Wormholescan](https://wormholescan.io/#/tx/0x9ab4c41e795e64368000efa7a945a8f625b577f6a7266eb1c81560f715090887)
[Polygon explorer](https://polygonscan.com/tx/0x9ab4c41e795e64368000efa7a945a8f625b577f6a7266eb1c81560f715090887)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4cc4223f-8232-4d28-a8ce-d83fddcbaa74

**Comment by AigaD** [comment]
Reproduced from: https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/#
Wormholescan showed status Completed, while confirmations were still loading, funds were already received

Attachment:

![Screenshot 2024-01-17 at 08 48 01](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fa03295e-5fbe-4a25-88c3-1ac3e2cfe953)

**Comment by AigaD** [comment]
Reproduced also for transaction [Polygon](https://polygonscan.com/tx/0x102121d46727ff6f2873430aed75b9c5b4c32dc977961f5fd552058b240ad974) -> Arbitrum
Tested from: https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/71f57956-cebf-44da-9c38-7fa267da73a2

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 WETH from Polygon to BSC, link to [Wormholescan](https://wormholescan.io/#/tx/0x1c29164d5b049d8c7ed779e547dd63f184e42e1b87a305cc9938bd7cbe88d9e2) is not showing the status Pending while the confirmations are loading.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/106d838f-e71b-4c6e-9df8-7c6e4ed345ce

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. Correct status is displayed on Wormholescan.
Scenarios checked:
* WETH (Polygon) transfer from [Polygon](https://polygonscan.com/tx/0xdf0959fea5df18c7ff3b06bcb7080e783c2b87aaec2980c1180000f01e242172) (MetaMask) to [BSC](https://bscscan.com/tx/0x341b8ee8f077f9b4754306b3eb44482b94038f1db14c64567fa9485972de64c6) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0xdf0959fea5df18c7ff3b06bcb7080e783c2b87aaec2980c1180000f01e242172)
* WETH (Polygon) transfer from [Polygon](https://polygonscan.com/tx/0x1de4d67f65a886d1c4fdeb0338abdcc638dec3bf093da39e187d17404ef6f0f0) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x795abba2b0aeefe9f50538b40892649afb823702ff7fb56f1f56b08052876505) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x1de4d67f65a886d1c4fdeb0338abdcc638dec3bf093da39e187d17404ef6f0f0)

Ticket is closed.
