### ISSUE TITLE
Remove Wrapped Options For Frankenstein ETH 

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1487]
<img width="382" alt="Screenshot 2024-01-12 at 2 22 21 PM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/4761680/9bf7190a-c22a-4b7e-82a6-db978833fbf6">
Having the wrapped ETH always show up as a destination asset option has become especially confusing in a world with ETH bridge.

We should depreate wrapped ETH from non Ethereum entirely. We should remove non primary eth options in the “destination asset” view so if you’re bridging a non Ethereum ETH eg Arbitrum ETH to eg Sui normally it would show you a “wormhole wrapped Arbitrum ETH” option to land on Sui with this Frankenstein asset - this should no longer be presented to the user. 

The logic would be a simple “turn off token bridge route/destination asset if original asset == ETH && ETH.origin != Ethereum”

Some sample situations:

ETH(Ethereum) on Ethereum -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option 
ETH(Optimism) on Optimism -> Solana: should be disallowed
ETH(Avalanche) on Avalanche -> Solana: should be disallowed
ETH(Ethereum) on Sui -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option 
ETH(Ethereum) on Solana -> Optimism: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option 
ETH(Ethereum) on Solana -> Ethereum: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option

**Comment by kev1n-peters** [comment]
I think this should also include Frankenstein wstETH

**Comment by tsadovska** [comment]
1) Checked whether following scenarios are allowed (or disallowed) on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:

ETH(Ethereum) on Ethereum -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Optimism) on Optimism -> Solana: should be disallowed - Tested OK
ETH(Avalanche) on Avalanche -> Solana: should be disallowed - Tested OK
ETH(Ethereum) on Sui -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Ethereum) on Solana -> Optimism: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Ethereum) on Solana -> Ethereum: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK

2) Checked ETH Bridge transfer:

Send 0.001 ETH (Ethereum) from Ethereum to Solana with manual bridge: [Etherscan](https://etherscan.io/tx/0x2eae9b43995819774762fe65a7582b9391e40e69db3fc1b009d86a1746802ed1), [Solana](https://explorer.solana.com/tx/44xxFehjf9dHH3kDigz9ZcDqaqfr2XFC6PY9aPAmJUtrF5t6HMvhPxZLpDD5EbDfSDBaKD9beNf47wgGU7Xcw5YP).


Created issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1535

**Comment by tsadovska** [comment]
Checked whether following scenarios are allowed (or disallowed) on https://preview.portal-bridge-ui.pages.dev/ac97e9d348/ [Mainnet]:

ETH(Ethereum) on Ethereum -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Optimism) on Optimism -> Solana: should be disallowed - Tested OK
ETH(Avalanche) on Avalanche -> Solana: should be disallowed - Tested OK
ETH(Ethereum) on Sui -> Solana: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Ethereum) on Solana -> Optimism: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
ETH(Ethereum) on Solana -> Ethereum: ALLOWED and the destination asset list displays wormhole wrapped ETH as an option - Tested OK
