### ISSUE TITLE
[Bug] ETH/wstETH NTT transfer estimated amount inconsistent

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1491]
## Describe the issue in detail

 - Chrome MacOSX Metamask
 - Select "BSC" as source chain and "WETH (BSC)" as asset and 0.001 as amount
 - Select "Avalanche" as destination chain
 - Note that "Estimated Amount" in destination box shows 0.000999
 - Note that separately, "Expected to receive" in Preview section shows 0.000448 WETH

![Screenshot 2024-01-16 at 3 41 14 PM (1)](https://github.com/wormhole-foundation/wormhole-connect/assets/689351/ed5bb800-42ce-4ba9-bf53-f9819526ebc6)

## What is the expected/desired behavior

I expect "Estimated Amount" to be equivalent to "Expected to receive"

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending wstETH (Optimism) from Optimism (Metamask) to Ethereum (Metamask). 


![Screenshot 2024-02-06 at 11 52 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dc095beb-ef8e-4841-8d5c-fa54378f9a55)

**Comment by kev1n-peters** [comment]
The first box doesn't include the relayer fee, but the second box does. I was told to implement it this way, but we can change it if we want.

**Comment by tsadovska** [comment]
@tonyjin Can we close this issue or Expected Amount in "To" section should include relayer fee?
