### ISSUE TITLE
[QA][Mainnet] Transaction confirmations dropped to negative count and is not moving forward

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1493]
Preconditions:
Metamask wallet connected
Console is opened

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/#

Steps:
1. Prepare to send 0.0005 WETH (Polygon) from Polygon to BSC
2. Click Approve and proceed with transaction
3. Click on Wormholescan while confirmations are still loading at approximately 100 confirmations ( issue reported #1486 )
4. Go back to transaction
5. Observe 

Actual result: Confirmation count dropped to negative number, has not moved forward for 35min. Console shows error `pb-index.js:126 GET https://preview.portal-bridge-ui.pages.dev/data/banners.json net::ERR_ABORTED 404 (Not Found)`

Expected result: Confirmation count is summed up until transaction is completed

Attachment:

![Screenshot 2024-01-17 at 08 53 23](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b33d500e-b5ed-4325-97fb-0e032ad1b4ed)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b5158e6a-5baf-43ff-beed-c994aeb01abc

**Comment by aadam-10** [comment]
duplicate, closing in favor of https://github.com/wormhole-foundation/wormhole-connect/issues/918
