### ISSUE TITLE
[QA] Not automatically switching to corresponding asset when changing assets

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1494]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/#

Steps:
1. Prepare to send WETH (BSC) from BSC to Arbitrum
2. Change WETH (BSC) asset to WBNB
3. Observe asset at sending To section
4. Change WBNB asset back to WETH (BSC)
5. Observe

Actual result: Asset at sending To section stays connected to WBNB (BSC) asset

Expected result:  Asset should automatically connect to corresponding asset for the transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f16a46ea-cec7-4e31-9bca-7c82d240c3fa

**Comment by AigaD** [comment]
Reproduced from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b8306de-7c7b-4fad-8c13-a8f2f2a93ff5

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Asset is not automatically changing when switched couple of times
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/25239d08-dc74-4d9f-a1b4-a3fe5330f6be

**Comment by agodlevska** [comment]
Reproduced on https://portalbridge.com/.
Asset is not automatically changing when switched couple of times.
Attachment:
<img width="729" alt="Screenshot 2024-07-02 at 13 52 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/6c00b6d0-3aa5-4f6d-a080-c5851babc6dc">

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ when changing WBNB to WETH (BSC). Source chain - BSC (MetaMask), Destination chain - Arbitrum (MetaMask). 

https://github.com/user-attachments/assets/bc17a75f-be03-4ff7-9b53-ec262fa83360

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign, assets are no longer automatically selected in "To" section.

https://github.com/user-attachments/assets/113df7dd-0c4a-4653-a6f2-fd7966c30366

Closing the ticket.
