### ISSUE TITLE
Add time estimate to route selection cells

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1497]
Right now we dont display an expected time on any route, all currently available routes are expected to take as long as network finality given they are all reliant on token bridge. 

We should show this network finality estimate under the fee on right hand side in the route selection cells. 

Under "after fees" we should show an estimate with the copy "x minutes/seconds" based on the destination chain. 

<img width="709" alt="Screenshot 2024-01-18 at 12 09 59 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/4761680/c9b4c493-b6f5-4bdd-a3b9-6eb13f25b026">

Disclaimer: I know this this isn't a scalable solution given the hard-coded values we should think about the interface for taking in a "completion time" value for each new "route" integrated.

**Comment by kev1n-peters** [comment]
The time estimate should be based on the source chain since the guardians will not emit a VAA until the source transaction is finalized

**Comment by yuli-ferna** [comment]
@aakashthumaty What do you think? Shall we leave this format? Remembering that we have three cases:

- You have a time in minutes or estimated seconds

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/c8aa6c00-6f1b-449c-8c42-75a5e181bc4f)

- The transaction is instantly completed

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/befadd80-37a4-4c0b-9a20-10247d4661f4)

- In the case of some chain, we don't have the data to calculate the time, so we would leave it as it was originally.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/0553b6e8-00df-4686-b100-0350950d4317)

I listen to suggestions

**Comment by yuli-ferna** [comment]
With the `finalityThresholds ` array we can know all estimated times. The number of blocks before a transaction is considered "final", so this would be the list of the chains that we can know their estimated time so far. The ones with 0 means that the transaction is instantaneous.

```
const finalityThresholds = [
  ["Ethereum", 64],
  ["Solana",   32],
  ["Polygon",  32],
  ["Bsc",      15],
  ["Fantom",    1],
  ["Celo",      1],
  ["Moonbeam",  1],
  ["Avalanche", 0],
  ["Sui",       0],
  ["Algorand",  0],
  ["Aptos",     0],
  ["Sei",       0],
  ["Near",      0],
  ["Terra",     0],
  ["Terra2",    0],
  ["Xpla",      0],
  ["Injective", 0],
  ["Karura",    1],
  ["Acala",     1],
] as const satisfies MapLevel<Chain, number>;
```
https://github.com/wormhole-foundation/connect-sdk/blob/d7f078c63c26d5100915673dd5dbeba433558423/core/base/src/constants/finality.ts#L26

**Comment by AigaD** [comment]
Estimate time is shown for transactions mentioned in the list. Time estimates are not shown for transactions from: Base, Cosmos chains, Arbitrum, Optimism, Klaytn
Chains with block number 0, shows estimate time: Instantly
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2024-02-08 at 15 53 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/28722bb3-c7bc-479a-b310-15dca45e64b7)
![Screenshot 2024-02-08 at 15 53 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7214b01a-2c85-4ea1-a0aa-d44ad512587b)
![Screenshot 2024-02-08 at 15 55 27](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ed9782b7-644a-4c1f-bac1-f894aa08330c)
