### ISSUE TITLE
Show a tooltip that tells a user to select network before selecting asset

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1498]
Today we block selecting an asset to transfer if a user has not selected a network.

Can we add a tooltip that tells the user to select network before selecting asset  - the tooltip should be triggered on hover OR on click over "asset". - (in the interim of getting a full UX treatment) 
![Uploading Screenshot 2024-01-18 at 12.10.32 AM.png…]()

**Comment by artursapek** [comment]
shouldnt be hard
