### ISSUE TITLE
Block user from exiting window when manual transfer not complete

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1500]
Today if a user attempts to close the final screen of Connect (where they see the number of confirmations and eventually get prompted to claim their tokens with another transaction approval from the destination wallet) nothing stops them from doing so EVEN THOUGH they need to navigate back to the claim screen to get their assets. 

Can we add a (temporary until we get better designs from George) unload alert in the design of the current governor alert (pasted below)  [if transfer=manual && transfer != complete] that informs the user:

"Title: Your transfer has not been completed."

"body: You need to approve a transaction from your destination wallet once your token transfer has reached finality on the destination chain. Please leave this page open or navigate to the redeem page to complete the transfer https://portalbridge.com/advanced-tools/#/redeem"

<img width="330" alt="Screenshot 2024-01-18 at 12 46 16 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/4761680/e97268ea-527f-405a-a2e7-be28aa21e120">

**Comment by artursapek** [comment]
we may need to resort to `window.alert` if we want to interrupt people closing the page with a confirmation. I can dig into this.

**Comment by tsadovska** [comment]
Checked on https://preview.portalbridge.com/7246284e5d/ [Mainnet].

Tested OK:
* Pop-up warning "Changes may not be saved" is shown when user sends asset with manual route, Redeem screen is opened, asset is not claimed and user wants to refresh the page 
* Pop-up warning "Changes may not be saved" is shown when user sends asset with manual route, Redeem screen is opened, asset is not claimed and user wants to close the page
* Pop-up warning "Changes may not be saved" is shown when user sends asset with manual route, Redeem screen is opened, user clicked on "Claim" button, but asset is not claimed yet and user wants to close the page
* Pop-up warning "Changes may not be saved" is not shown when asset transfer is completed and user wants to refresh the page


Tested NOK:
* Pop-up warning "Changes may not be saved"  is not shown when user clicks on Back button, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1702
