### ISSUE TITLE
Add warning for transfer larger than CCTP max transfer limit (1M)

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1504]
A user hit a limit of 100k on the CCTP bridge in Connect, we know Circle imposes limits of 1M on CCTP transfers (dependent on the chain) but are unclear on where this 100k limit is being imposed. We need to investigate where its propagating from (doesn't seem to be relayers). My hypothesis is that the CCTP limits are on an address basis (we hit CCTP from the WH CCTP contracts) and over some small window of time, amounting perhaps to 1M in the period this user tried it.

1. find the source of the limit and remedy it or decide to keep it if its unsolvable or legitimate 
2. implement elegant error handling that matches the UI of "amount must be greater than 0" below:  
<img width="785" alt="Screenshot 2024-01-19 at 4 53 10 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/4761680/a8ccdb14-9072-4f0d-89ae-46076277f9e2">

**Comment by tonyjin** [comment]
<img width="716" alt="Screenshot 2024-01-19 at 11 53 37 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/689351/ee6dbd82-c87b-4992-9ce9-d0b3ee0b6f72">

Separate issue - once you try to transfer 7 digits worth of assets, the number is clipped.

**Comment by tonyjin** [comment]
<img width="1644" alt="Screenshot 2024-01-19 at 11 55 27 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/689351/a9df6729-a861-436f-9625-fa8b5e5b23e3">

A test transfer of 1000005 USDC failed with the above error:

> main.js:691 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Burn amount exceeds per tx limit", method="estimateGas", transaction={"from":"0x8F26A0025dcCc6Cfc07A7d38756280a10E295ad7","to":"0x774a70Bbd03327c21460B60f25b677d9e46AB458","data":"0x59b87d8e0000000000000000000000005425890298aed601595a70ab815c96711a31bc65000000000000000000000000000000000000000000000000000000e8d4f15b40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000008f26a0025dccc6cfc07a7d38756280a10e295ad7","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: Burn amount exceeds per tx limit","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204275726e20616d6f756e74206578636565647320706572207478206c696d6974","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

**Comment by tonyjin** [comment]
I was able to send a transfer of 999999 USDC on testnet: https://wormholescan.io/#/tx/0x6bfe684d844bb6388ff19d85df5b2f0ab3fa02f2286d4387597441957a78d9d5?network=TESTNET

**Comment by tonyjin** [comment]
Circle's CCTP limit (currently 1M on the networks we support) should be purely a per-message limit, and users should be able to send sequential 999K transfers without waiting for finality from the first transfer. We have previously tested batching multiple Circle messages into a single transaction >1M.

Circle has a separate inbound minting limit per network that should be very large and not run into in regular operations. They do not publicize this per-network minting limit.

**Comment by yuli-ferna** [comment]
@tonyjin  I have a couple of questions, what should the warning say for now the text I use is:
"Burn amount exceeds per transaction limit"

and when we talk about the Circle's separate inbound minting limit, is it related to the map they have? [(burnLimitsPerMessage)](https://github.com/circlefin/evm-cctp-contracts/blob/master/src/roles/TokenController.sol#L69 ) https://developers.circle.com/stablecoins/docs/limits#per-message-burn-limit

**Comment by tonyjin** [comment]
Suggested language - "Amount larger than Circle per-transfer limit"

Thoughts @Wesleyleung?

cc @yuli-ferna

**Comment by Wesleyleung** [comment]
The UI elsewhere already specifies the route is provided by Circle, so I would suggest keeping the error message more generic. To future proof, I also think leaving out specifying 1,000,000 USDC is fine if Circle up/lowers their limit in the future.

Suggested language -  "Amount larger than the maximum per-transfer limit. Please try a lower amount".

**Comment by mliu-xlabs** [comment]
Hey @Wesleyleung - I was thinking "Your transaction exceeds the maximum transfer limit of 1,000,000 USDC. Please use a lower amount."

Reasoning for me to include the limit # is b/c it's a somewhat ambiguous suggestion otherwise, the user would not have a sense of how much lower that they would need to set it and could lead to repeated tries and frustration. 

Let me know your thoughts!

**Comment by Wesleyleung** [comment]
Sounds great. If Circle doesn't have plans to change this limit, then agree being more descriptive for the user is always better.
