### ISSUE TITLE
[QA] [Testnet] Cannot send asset with Sui MetaMask Snap

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1506]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome
1. Select "Sui" network as source chain and connect "Sui MetaMask Snap" wallet in From section
2. Select "Fuji" network as destination chain and connect "Metamask" wallet in To section
3. Select Sui asset and enter amount 0.01
4. Click "Approve and proceed with transaction" button
5. Observe Metamask notification and click "OK" button

Actual result:
* Wormhole-connect is requesting to execute transaction on mainnet instead of testnet
* Error in Console:
```
Error: DRY_RUN_FAILED: Package object does not exist with ID 0xf47329f4344f3bf0f8e436e2f7b485466cff300f12a166563995d3888c296a94
    at E6.fromSimpleErrorMessage (main.js:695:42104)
    at convertError (main.js:695:43060)
    at signAndExecuteTransactionBlock (main.js:695:44685)
    at async SuiWallet.signAndSendTransaction (main.js:695:94408)
    at async signSuiTransaction (main.js:519:14533)
    at async signAndSendTransaction (main.js:519:15811)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79338)
    at async Object.gr [as onClick] (main.js:691:95817)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5fe44f7f-25bb-4b80-beb7-3e209edfeccf)

![Screenshot 2024-01-19 at 12 32 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f61b4cf7-2668-433a-898e-084a5ca3b7fc)

Note: Issue is not reproducible on mainnet https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by aadam-10** [comment]
investigated and unfortunately there's nothing we can do on this side, as metamask snap isn't supported on sui testnet.
