### ISSUE TITLE
[QA] Cannot connect "Sui Metamask Snap" with Phantom wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1507]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome

1. Phantom and Metamask wallets are installed
2. Click "Connect wallet" and select "Sui Metamask Snap" option
3. Click "Use Phantom" option in Phantom Wallet notification 
4. Check if wallet is connected

Actual result: Wallet is not connect. 
```
VM122:7 Uncaught (in promise) Error: The method does not exist / is not available.
    at Xi.<anonymous> (<anonymous>:7:5149)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1190
    at new Promise (<anonymous>)
    at rt (<anonymous>:1:1010)
    at Qi.request (<anonymous>:7:3385)
    at ea.<anonymous> (<anonymous>:7:9356)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1190
    at new Promise (<anonymous>)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d8557173-2a41-4a23-bbbb-bc9b49993200

## What is the expected/desired behavior
Wallet is successfully connected.

**Comment by kev1n-peters** [comment]
Metamask Snap is not going to work with Phantom

**Comment by AigaD** [comment]
Not reproduced from: https://portalbridge.com/# 
And closing according to comment above

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/06c09c82-e567-4395-a483-349a42230bad
