### ISSUE TITLE
[QA] Cannot connect OKX Wallet when Evmos network is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1509]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome

1. Select "Evmos" as source chain
2. Click "Connect wallet" button and select "OKX Wallet" option
3. Check if wallet is connected

Actual result: Wallet is not connected.
```
Uncaught (in promise) Error: No chain info found for evmos_9001-2
    at CosmosEvmWallet.addChain (main.js:399:94142)
    at CosmosEvmWallet.connect (main.js:399:93438)
    at async dr (main.js:794:91875)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5d8dfaff-bb9a-4747-a3c1-4c1bcb49affa)

Note: Issue is not reproducible when selecting Osmosis or Kujira network.

## What is the expected/desired behavior
Wallet is connected.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Cannot switch over to Kujira Network when OKX wallet is connected
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6117f7f1-60b5-4554-826d-c5414ae5649e

**Comment by AigaD** [comment]
Reproducible from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#
Cannot connect or switch to Evmos with OKX Wallet
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0fa2a658-f480-4f8d-ae62-84305ab051bf

**Comment by aadam-10** [comment]
@AigaD @tsadovska the resolution to this was to hide the option for Evmos as it won't work

**Comment by tsadovska** [comment]
New issue was created: https://github.com/wormhole-foundation/wormhole-connect/issues/1573
