### ISSUE TITLE
[QA] Cannot select "Sui MetaMask Snap" option when "OKX Wallet" extension is enabled

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1510]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome

1. Install and enable "OKX Wallet" extension
2. Open wormhole-connect
3. Click "Connect wallet" and select "Sui MetaMask Snap" option

Error: `Uncaught (in promise) {code: -32601, message: "The method 'wallet_requestSnaps' does not exist / is not available.", data: {…}}`

Note: "Sui MetaMask Snap" option can be successfully selected when "OKX Wallet" extension is disabled. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/499c8568-1a21-44ff-99a5-da5e9b060c56

## What is the expected/desired behavior
User can successfully select "Sui MetaMask Snap" option.

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ee13f020-10cc-4fb8-8c8a-89a8a5171a95

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Issue reproducible from Mainnet, cannot connect to Sui Metamask Snap wallet when OKX wallet extension is enabled.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9d8847f-9d13-456c-86bc-9c143836f341

**Comment by tsadovska** [comment]
Issue is no longer reproducible, "Sui MetaMask Snap" wallet can be successfully connected. 

Checked on:
- https://wormhole-connect.netlify.app/ [Testnet]
- https://portalbridge.com/ [Mainnet]
- https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Ticket is closed.
