### ISSUE TITLE
[QA] Cannot connect Bitget (Cosmos) wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1511]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome

**Scenario 1:**
1. Select Osmosis/ Kujira/ Evmos
2. Click "Connect wallet" button and select "Bitget (Cosmos)" option
3. Check if wallet is connected

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at main.js:399:93968
    at Array.some (<anonymous>)
    at CosmosEvmWallet.hasChain (main.js:399:93948)
    at async CosmosEvmWallet.connect (main.js:399:93402)
    at async dr (main.js:794:91875)
```

**Scenario 2:**
1. Click "Connect wallet" button and select "Bitget (Cosmos) option"
2. Check if wallet is connected

Error: `Uncaught (in promise) There is no chain info for cosmoshub-4`

Actual result: Wallet is not connected.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b90593b-c266-4de8-ba07-6ee659f33f04

Note: Issue is not reproducible with Bitget (Sui), Bitget (Solana) and BitKeep (Aptos) wallets. 

## What is the expected/desired behavior
Wallet is connected.

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Cannot connect to Bitget wallet.
It seems that the wallet does not offer Osmosis, Kujira networks, it fails to add the Evmos netwotk. Only Cosmos network can be added in the wallet itself.
Attachment:
![Screenshot 2024-01-30 at 17 56 13](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a58492a8-2636-4424-a8a8-7a402fae3f50)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6f4fd14b-90e8-472b-aa92-5619abc197fa

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d28181d9-e8ad-457c-9dff-337fcc0d1e1f)

**Comment by tsadovska** [comment]
Issue is also reproducible when Injective networks is selected as source chain. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Linked to https://github.com/wormhole-foundation/wormhole-connect/issues/1763.

Error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at cosmos-inyqw_uq.js:27:776123
    at Array.some (<anonymous>)
    at xP.hasChain (cosmos-inyqw_uq.js:27:776105)
    at async xP.connect (cosmos-inyqw_uq.js:27:775592)
    at async Fn (main.js:522:205929)
```

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Cannot connect Bitget wallet to Injective Network `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')`
Attachment:

<img width="1331" alt="Screenshot 2024-03-14 at 11 18 52" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/af6978ff-585a-4318-a32d-6c045f739e02">

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJJFgoR3QsQi4Rk3DPmKy3AMYbBYbXJiKzYAL4g7QA%3D%3D#)
User is able to connect Bitget wallet when Osmosis network is selected, but not when Evmosand Kujira Networks are selected `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')`

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f1703bb-bb83-4173-b7fe-d9b2bbe21aef


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/accf13e1-82df-4816-80ea-96a97edc7422

**Comment by tsadovska** [comment]
Closing the ticket, because Cosmos chains are no longer displayed on https://portalbridge.com/. 
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
