### ISSUE TITLE
[QA] [Testnet] Cannot connect Coin98 wallet with Cosmoshub network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1514]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome

Scenario 1:
1. Select Cosmoshub network as source chain
2. Click "Connect wallet" button in From section and select Coin98 wallet

Actual result: Clicking on "Coin98 wallet" option has no effect. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a9c4e7cf-c5d2-44d9-a73f-49e3b2f8e641)

Scenario 2:
1. Select Kujira network as source chain
2. Click "Connect wallet" button in From section and select Coin98 wallet
3. Change network to "Cosmoshub"

Actual result: Network is not changed. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e37cc494-9af2-4c1c-9308-dbca5d86018b

Notes:
* Issue is not reproducible with Leap wallet. User can successfully connect Cosmoshub network and then connect Leap wallet.
* User can successfully connect Coin98 wallet with Osmosis, Evmos, Kujira. 

## What is the expected/desired behavior
User can connect Coin98 wallet with Cosmoshub network or option is not shown.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect.netlify.app/
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09af7730-4b73-4363-9894-8f7de34fdc6e
