### ISSUE TITLE
Descript Error Message When A Native Route is Unavailable

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1520]
Currently the following error message is thrown when a native route is unavailable in ETH bridge:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/4761680/8aff4945-7fb6-4a80-8770-951cb8d250b5)

Initially, this behavior is only relevant to ETH bridge but going forward for ETH bridge as well as any new native routes are added (e.g. Mayan) if a route is unavailable (due to liquidity or API being down) the following error should be displayed:

“This asset is temporarily unavailable on (chain), please try again soon.”

**Comment by aadam-10** [comment]
merged into a single ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1572
