### ISSUE TITLE
Wallet Connect Integration for Solana failed on test with phantom mobile

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#1521]
Couldnt get the wallet connect integration to successfully work on the major wallets. The wallet it did work with failed to sign the tx. Need to troubleshoot if this is a wallet aggregator issue or a connect issue but initially suspect its wallet connect. 

cc @kev1n-peters @mliu-xlabs @M-Picco

**Comment by kev1n-peters** [comment]
Added an observation while testing here: https://github.com/wormhole-foundation/wormhole-connect/pull/1448#issuecomment-1896284442
