### ISSUE TITLE
[QA][Mainnet]No corresponding token available at target chain when sending ETH (Optimism)

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1526]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.199

Tested from: https://wormhole-connect-mainnet.netlify.app/# / https://wormhole-connect.netlify.app/#

Steps:
1. Select Optimism Goerli Network at sending From section
2. Select Moonbase/Fantom/Alfajores network at sending To section
3. Select ETH (Optimism) asset
4. Observe sending To section asset field
5. Open asset list at sending To section
6. Observe

Actual result: Asset is not automatically selected at sending To section when sending ETH (Optimism) from Optimism Network. If manually selecting WETH (Goerli) asset, then message "No bridge or swap route available for selected tokens" is shown

Expected result: Asset at target chain is automatically selected, user is able to continue with transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5121b57d-8688-4a68-a1fa-95cd50ce00d3

**Comment by AigaD** [comment]
Same behaviour also reproduced when sending ETH (Base) asset.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8bc69e0c-1210-41dc-bda1-4a3052bd40a7

**Comment by kev1n-peters** [comment]
This is intentional to prevent users from receiving Frankenstein ETH. See https://github.com/wormhole-foundation/wormhole-connect/issues/1487
