### ISSUE TITLE
[QA] Error when clicking on "Sui MetaMask Snap" option when Metamask app is not installed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1528]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome

1. Metamask extension in not installed or is disabled
2. Click "Connect wallet" button
3. Select "Sui MetaMask Snap" option

Actual result: Error is shown is Console.  
```
Uncaught (in promise) Error: MetaMask not detected!
    at main.js:695:45766
    at async SuiWallet.connect (main.js:695:93432)
    at async dr (main.js:794:91875)
```

![Screenshot 2024-01-23 at 14 14 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95b4af8f-f87a-4738-a3d5-ded4c00b1cf5)

## What is the expected/desired behavior
"Sui MetaMask Snap" option is not shown when Metamask app is not installed or is disabled.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d1d3cbe4-37cf-45c6-840c-21ced6545ae9

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/#
Sui Metamask Snap offered when Metamask wallet is not available.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ad9ee7ab-9a96-4d21-a36a-cbc148010484
