### ISSUE TITLE
Canonical tBTC deployments on different chains shown as wormhole wrapped

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1529]
1. Select Ethereum as the from network
2. Open the token list
3. Filter the token list to tBTC
4. Check the results

- ✅ The tBTC that's native on Ethereum is marked as native 
- ❌ The list displays tBTC on other chains marked as wormhole wrapped, while the contract addresses point to the canincal tbtc deployment on those chains

While point 2 is technically true, it's misleading as tBTC has always been a burn and mint style token, with wormhole-wrapped flavors not being officially supported. We should find a way to filter them from the list.

**Comment by tsadovska** [comment]
Tested OK on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Only native tBTC is shown on Ethereum, Polygon, Optimism, Arbitrum, Base and Solana. 

Ticket will be rechecked on https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet] after https://github.com/XLabs/portal-bridge-ui/issues/693 is resolved.

**Comment by AigaD** [comment]
Checked from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/
tBTC shown as Native from: Ethereum, Polygon, Solana, Base, Arbitrum, Optimism
tBTC shown as wrapped from: BSC, Fantom, Avalanche, Celo, Moonbeam, Sui, Aptos, Osmosis, Evmos, Kujira

Attachment:

<img width="838" alt="Screenshot 2024-01-25 at 14 53 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b5659411-983e-4a86-9884-d1861df247ff">
<img width="941" alt="Screenshot 2024-01-25 at 14 51 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6b484912-d9da-42cf-8090-564371fa19bc">
