### ISSUE TITLE
[QA] [Mobile] "Sui MetaMask Snap" option is not clickable 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1532]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with iPhone 11 Pro iOS 16.5.1 and Google Chrome

1. Open wormhole-connect on mobile
2. Click "Connect" button and select "Sui MetaMask Snap" option

<img width="361" alt="Screenshot 2024-01-23 at 19 49 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/92e670e0-6c20-47a3-8f37-6159ab9fb5cd">

## What is the expected/desired behavior
"Sui MetaMask Snap" option should not be shown on mobile or should be clickable.

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Tested from: iPhone 14, iOS 16.0 Chrome
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/11af2438-0340-43e2-aaac-ec892765e160

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ (Connect v2).
Checked with iPhone 11 Pro 17.5.1 and Google Chrome Version 128.0.6613.34.
