### ISSUE TITLE
[QA] Asset is field is not cleared when changing From network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1535]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome

Related ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1487

1. Prepare to send 0.001 ETH (Ethereum) from Ethereum (Metamask) to Solana (Phantom)
2. Change Ethereum network to Optimism
3. Select ETH (Optimism) asset
4. Check if Asset field in To section is cleared

Actual result: Asset field in To section is not cleared. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de1dee03-aaaf-4841-92e6-b4de0999a465

## What is the expected/desired behavior
Asset field is cleared.

**Comment by agodlevska** [comment]
Issue is reproducible on https://portalbridge.com/. 

Error in console: 
```
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at D1.makeError (pb-index-BW2L8WsT.js:376:47781)
    at D1.throwError (pb-index-BW2L8WsT.js:376:47914)
    at D1.throwArgumentError (pb-index-BW2L8WsT.js:376:47975)
    at pb-index-BW2L8WsT.js:386:20679
    at Generator.next (<anonymous>)
    at _r (pb-index-BW2L8WsT.js:386:20132)
``` 

Attachment: 

https://github.com/user-attachments/assets/b4293a91-d561-4f6d-9bfa-680e594ad04e

**Comment by tsadovska** [comment]
Expected behaviour after redesign. 
Ticket is closed.
