### ISSUE TITLE
[QA] [Mainnet] Transaction is shown as still loading when asset was received

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1537]
## Describe the current behavior in detail
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet]. Checked with macOS and Google Chrome.

Scenario 1 :
1. Send 0.001 USDC (Avalanche) from Kujira (Keplr) to Evmos (Leap)
2. Check if transaction is completed
3. Check if asset is received

Actual results:
* Transaction is shown as still loading when asset was received. 
* Transaction is shown  as still loading after transaction is resumed.
* Send from tx: [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/A10DFEADE9460741B53AD26F08601E660B6ADC64DB7CE1A92E9C9D27FF6BC0AD)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/641afd9f-165a-4c09-a110-e12c9dcc53c9

Scenario 2:
1. Send 0.01 USDC (Avalanche) from Evmos (Keplr) to Kujira (Keplr)
2. Check if transaction is completed
3. Check if asset is received

Actual results:
* Transaction is shown as still loading when asset was received
* Transaction is shown as still loading after transaction is resumed.
* Send from tx: [MintScan](https://www.mintscan.io/evmos/tx/8A5AFA5B85FD1DF47AD6071DABEF71E9942C98B7C244B8AE7DB1E3C0EF12071B)

## What is the expected/desired behavior
Transaction is successfully completed.

**Comment by AigaD** [comment]
Reproduced for transaction 1 SUI from [Sui](https://suiexplorer.com/txblock/8QFYjxNQ12TfyH6fEgTsMG3qmCK1H5GNP2DtmFTrFswd) (Sui wallet) to Polygon (Rabby wallet) with automatic route.
Tested from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/
Attachment:
<img width="1092" alt="Screenshot 2024-01-24 at 13 21 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/df219404-0ba6-4054-bbbc-6c1b3a4ebab5">

Uploading Screen Recording 2024-01-24 at 13.21.04.mov…

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1138

**Comment by kev1n-peters** [comment]
For the Kijura transfer, we try to look for the `write_acknowledgement` attribute when searching for the redeem event now (added in this PR https://github.com/wormhole-foundation/wormhole-connect/pull/1490)
However, the `write_acknowledgement` attribute doesn't exist on the destTx when we do the search here https://github.com/wormhole-foundation/wormhole-connect/blob/21b349bc29d37f49bb85899416a83dd8fa1a3975/wormhole-connect/src/routes/cosmosGateway/utils/transaction.ts#L59, but `recv_packet` does exist (what we were using prior to the PR)
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/96065607/f9f98967-379a-4bac-91bb-a78085534eda). The token was definitely redeemed on Evmos here: https://www.mintscan.io/evmos/tx/8A5AFA5B85FD1DF47AD6071DABEF71E9942C98B7C244B8AE7DB1E3C0EF12071B. So are there some cases where the TX is redeemed, but `write_acknowledgement` doesn't exist?

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1561--wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenarios:
* Send 0.001 USDC (Avalanche) from Kujira (Keplr) to Evmos (Leap): [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/245E1C06CF93A1D6601CFE9C4C1250F818670FB7976081ACE976F9564A8EB57C), [Mintscan](https://www.mintscan.io/evmos/tx/ED22C9C996FB354CBA89E9429B1895AD05D4A7257E5A4FADB50BF1CD7C258B25)
* Send 0.01 USDC (Avalanche) from Evmos (Keplr) to Kujira (Keplr): [Mintscan](https://www.mintscan.io/evmos/tx/69FA5D04B3052FFC8050E677DA004342A2ED33308DF1C0AD74F4E631ED3E88E6), [Kujira](https://finder.kujira.network/kaiyo-1/tx/9A21032CCDFBE4C11075AFCB502FB30BD11667B979A27E18933D2B8D5B354F0A)
* Send 0.0001 WSOL from Osmosis (Keplr) to Kujira (Keplr): [Mintscan](https://www.mintscan.io/osmosis/transactions/1DFDB7B94C2C0A3698D6B2D582FF05D127DA0FA0F8149DF3566FA53C60E568C8), [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/4DCBE0216872E49D2038341162391243C321263EF92809F2450B46EEE26A74C6)
* Send 0.0001 CELO from Osmosis (Leap) to Evmos (Leap): [Mintscan](https://www.mintscan.io/osmosis/transactions/E3DDB3DCA55FBE7478A345188FB1EA7E91736E1C22B2AE8B96113DC7FBE224CB), [Mintscan](https://www.mintscan.io/evmos/tx/A4B48C2C479D28403BC29333113682FB4EAE51E1BD90FEC7E99015A83F672BF0)
