### ISSUE TITLE
[QA] OKX Wallet (Ethereum) is not shown in wallets list although user can connect it by using Metamask option

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1539]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Related ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1345

1. Click "Connect wallet" button
2. Search for "OKX" 
3. Check if OKX Wallet (Ethereum) option is shown (Actual result: Option is not shown)
4. Close window
5. Select Ethereum network as source chain
6. Click "Connect wallet" button and select Metamask option

Actual result: OKX Wallet notification is opened. User can connect OKX Wallet account.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7d7e3239-9826-4aaa-b0ef-049aad89bb23

## What is the expected/desired behavior
OKX Wallet (Ethereum) is shown in the list on "Connect wallet" window or user is not able to connect OKX Wallet (Ethereum) through Metamask option.

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1674--wormhole-connect.netlify.app/ [Testnet]. User can connect OKX Wallet (Ethereum) through MetaMask option. 



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/384052b9-e250-461c-8249-d5d2b384b2a0

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNxEc00NIWIRcIybhnzFAY0gcRmwWB1yYii2AC%2BIB0A#)
OKX wallet is not offered in wallet list. When clicking on Metamask walet, OKX pop-up is opened and user is able to connect to OKX, but Metamask icon is displayed
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7a0f720b-89bd-4714-afb4-d4cfff79ecef

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/ac15114854/
OKX wallet is not offered in wallet list when extension it turned on. When clicking on MetaMask wallet, OKX pop-up is opened and user is able to connect to OKX but Metamask icon is displayed.

**Comment by tsadovska** [comment]
Issue is no longer reproducible, OKX (Ethereum) wallet is displayed in Wallets list. Checked on https://wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/user-attachments/assets/37880794-401b-4d3d-8c44-f9ff5f574ce8)

Ticket is closed.
