### ISSUE TITLE
[QA][Mainnet] Sui Metamask Snap wallet does not disconnect when user revokes connection from wallet itself

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1540]
Preconditions:
Wallet is not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#

Steps:
1. Connect Sui Metamask Snap at sending From section
2. Open Metamask wallet extension
3. Click on three dots to open menu
4. Select "Snaps"
5. Scroll down and select Disconnect
6. Observe

Actual result: Although Sui Metamask Snap connection to Wormhole or Portal app is revoked, it does not show as disconnected

Expected result: Wallet disconnects from any app that user clicks on Disconnect

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f7b79893-18fb-4eef-a897-961ed6e66551

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/71cb735e-78aa-45ff-bf15-effa97e2453b

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 

Attachment:

https://github.com/user-attachments/assets/0ac09284-518c-4d7b-8bf0-2846fd2c4063
