### ISSUE TITLE
[QA] "Disconnect wallet" link is not working when Metamask wallet is connected through OKX Wallet 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1541]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Related ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1345

Steps:
1. OKX Wallet and Metamask extensions are enabled
2. Select Ethereum network 
3. Click "Connect Wallet" button and select Metamask option
4. Select Metamask option in OKX Wallet notification 
5. Click "Disconnect wallet" link on pop-up "Select "Disconnect wallet" and refresh the page to connect to a different wallet"
6. Check that Metamask wallet is disconnected.

Actual result: Metamask wallet is still connected.

Attachments:

![Screenshot 2024-01-24 at 16 01 08](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aaaae078-9346-402f-bac2-589d8b18ea1b)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f19d51c6-029c-4b18-b1b7-03b40f32b33e

## What is the expected/desired behavior
Metamask wallet is disconnected. 

Issue is not reproducible when OKX wallet account is connected ("OKX" option is selected in Step 4). In this case account is disconnected when user clicks on "Disconnect wallet" link. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d5f7e2b4-c36c-45a5-b7e2-af7631391996

**Comment by AigaD** [comment]
Same behaviour reproduced from: https://portalbridge.com/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/46f2563b-d553-4cc9-b4f5-95c34207f894

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/
OKX Metamask wallet is not disconnecting when clicking on Disconnect wallet on the pop-up message
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09ab026c-7d10-4e26-a9ad-d5aca2c6f092

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 


https://github.com/user-attachments/assets/f749388f-e38a-48d6-b33b-54d302137bac

Ticket is closed.
