### ISSUE TITLE
[QA] [Mainnet] Cannot connect to Sui Metamask Snap wallet when Phantom wallet is connected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1542]
Preconditions:
Wallet not connected
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#

Steps:
1. Select Solana Network at sending From section
2. Connect Phantom wallet 
3. Select Sui at sending To section
4. Try to connect Sui Metamask Snap wallet
5. Observe
6. Refresh the page
7. Select Sui at sending To section
8. Connect Sui Metamask Snap wallet
9. Select Solana Network at sending From section
10. Connect Phantom wallet 
11. Observe

Actual result: Cannot connect Sui Metamask Snap wallet when Phantom wallet is connected first, console shows error: `Uncaught (in promise) Error: Already connecting`

Expected result: Sui Metamask Snap wallet is connected

Comments: Didn't reproduce this issue with Solflare wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f62c6c10-d8af-4b18-8c4a-e531c35d8e19

**Comment by kev1n-peters** [comment]
I can connect Sui metamask snap if I connect it before connecting Phantom. So it appears that there's an issue with Phantom preventing the user from connecting Sui metamask snap.

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1df50346-5942-4192-aa13-0ceed61ddf3b

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7246284e5d/
Cannot connect to Sui Metamask Snap when Phantom wallet is connected first, error shown `Error: Already connecting`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ebe9a883-1cda-4993-b087-eebabd5d3107

**Comment by tsadovska** [comment]
Issue is no longer reproducible. 
Sui MetaMask Snap wallet can be successfully connected when Phantom wallet is already connected. Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) and https://portalbridge.com/. 


![image](https://github.com/user-attachments/assets/88e3a611-407c-4c34-845f-c939892230f7)


Ticket is closed.
