### ISSUE TITLE
[QA][Mainnet] Rabby wallet is not offered if OKX Wallet extension is enabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1546]
Preconditions:
Rabby wallet is in use
OKX Wallet extension is enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#

Steps:
1. Click on Connect wallet
2. Search Rabby
3. Observe
4. Disable OKX Wallet in extension
5. Go back to Wormhole connect/ Portal bridge and refresh the page
6. Click On Connect Wallet
7. Search Rabby wallet
8. Observe

Actual result: Rabby wallet is not shown in the list if OKX Wallet extension is enabled

Expected result: Rabby wallet is shown if it is enabled, Metamask wallet is shown if Metamask wallet is enabled

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e681e379-99eb-4c88-ab66-d905fc7097b8

**Comment by AigaD** [comment]
This is also reproduced from: https://portalbridge.com/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d06042da-611a-4a2a-80e7-322e1a0b1be1

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e2b76ab1-bc6d-4481-9b75-92bd554327f2

**Comment by agodlevska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) and still reproducible on https://portalbridge.com/. 

Attachment: 

https://github.com/user-attachments/assets/b0b76035-3b96-4829-8c0b-7c4221eb6b4d

**Comment by tsadovska** [comment]
Issue is no longer reproducible after redesign. Checked on https://wormhole-connect-mainnet.netlify.app/.


https://github.com/user-attachments/assets/8ae68ad8-96b4-4146-8fb3-2a5a87fbfe09

Closing the ticket.
