### ISSUE TITLE
[QA] [Mainnet] Cannot send asset from OKX Wallet (Cosmos)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1547]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.01 WGLMR from Kujira (OKX Wallet) to Avalanche (Metamask)
2. Click "Approve and proceed with transaction" button

Error:
```
Error: Broadcasting transaction failed with code 5 (codespace: sdk). Log: spendable balance 100000ukuji is smaller than 1000000ukuji: insufficient funds: insufficient funds
    at Pr.broadcastTxSync (main.js:350:110730)
    at async Pr.broadcastTx (main.js:350:110477)
    at async CosmosWallet.sendTransaction (main.js:399:94791)
    at async CosmosWallet.signAndSendTransaction (main.js:399:94998)
    at async signCosmosTransaction (main.js:519:15417)
    at async signAndSendTransaction (main.js:519:16077)
    at async Operator.send (main.js:525:79299)
    at async Object.gr [as onClick] (main.js:691:95817) 
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/80df0d18-e43e-4189-9b86-c22c31f04b30)

Notes:
Issue is also reproducible when:
* Sending 0.01 WGLMR from Kujira (OKX Wallet) to BSC (Metamask)
* Sending 0.0001 WBNB from Kujira (OKX Wallet) to BSC (Metamask)

Issue is not reproducible when
* Sending 0.001 WBNB from Kujira (Leap wallet) to Avalanche (Metamask): [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/1B12DDCADE5EFA9E4271172CC165889F21F251C3316084102A06FB40607C2DFC), [Avascan](https://avascan.info/blockchain/c/tx/0x5212059790337bf4b4d41faa254bcbfbd6c03ca13b6d8bd83c2717cf1af0d3da)
* Sending 0.001 WFTM from Kujira (Keplr) to Celo (Metamask): [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/D2985D44F50F63D488EF3B93CEE001305821BCCFB3991B39974E8C98FB084A46), [Celo explorer](https://explorer.celo.org/mainnet/tx/0x78fa49817b5e8777b29cf4c635603b6e6ccc5332efb94f7a14eb37d8c1603858)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/ac97e9d348/ [Mainnet] when sending 0.0001 Kujira (OKX Wallet Cosmos) to Evmos (Leap). 

```
Error: Broadcasting transaction failed with code 5 (codespace: sdk). Log: spendable balance 100000ukuji is smaller than 1000000ukuji: insufficient funds: insufficient funds
    at Pr.broadcastTxSync (main.js:350:110730)
    at async Pr.broadcastTx (main.js:350:110477)
    at async CosmosWallet.sendTransaction (main.js:399:94791)
    at async CosmosWallet.signAndSendTransaction (main.js:399:94998)
    at async signCosmosTransaction (main.js:519:15417)
    at async signAndSendTransaction (main.js:519:16077)
    at async Operator.send (main.js:525:79512)
    at async Object.gr [as onClick] (main.js:691:95817)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/28a2341b-9ee3-4cf2-950f-90cd2fe039fd)

**Comment by AigaD** [comment]
Closing.
I believe more KUJI asset was needed to be added for gas fee.
Tested from: https://portalbridge.com/#
Transaction 0.001 WFTM from [Kujira](https://finder.kujira.network/kaiyo-1/tx/C776B9BD21113EC69A30C8FAB9AFD2A55B4C9844F112E0A795D9AE0689F83276) (OKX Wallet) to [Osmosis](https://www.mintscan.io/osmosis/transactions/34012331CDED9458ED35A274D23D6CEEFB1F23A526DB8204117BAA660E31D3A4) (Leap) tested OK.
Attachment:

![Screenshot 2024-01-30 at 17 25 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/02c960fd-a327-4a02-86ee-8684d2aae465)

Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.01 WGLMR from [Kujira](https://finder.kujira.network/kaiyo-1/tx/5D047B981832DFF8242EDA1E96175CE1957AEFE83C868632CF4B97DDE124D1DA) (OKX Wallet) to [Avalanche](https://avascan.info/blockchain/c/tx/0xfb10dbf0601a62f00f5442aa75c8d47cb8311a4b8c955dee17865cf50248770f) (Metamask) tested OK.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a675607c-af75-4efc-aa69-609c949abd9d
