### ISSUE TITLE
[QA][Mainnet] Sui Metamask Snap wallet offered when Rabby wallet is in use

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1548]
Preconditions:
Rabby wallet is in use
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#

Steps:
1. Select Sui Network
2. Click on Connect Wallet
3. Select Sui Metamask Snap
4. Observe

Actual result: Sui Metamask Snap wallet is shown in the list when Rabby wallet is in use. When user tries to connect to Sui Metamask Snap wallet, error in console is shown: `method [wallet_getSnaps] doesn't has corresponding handler`

Expected result: If Rabby wallet is in use then Sui Metamask Snap should not be offered in wallet list the same as Metamask wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/93897443-847b-49db-b4de-744207dd67a2

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/18cfd3c3-19dc-4f50-b050-c4c154caa46c

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Sui Metamask Snap is offered when Rabby wallet is in use, Sui Metamask Snap option is clickable.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cc7f48db-0cd7-4c8a-bccd-0d7a459e028a

**Comment by agodlevska** [comment]
Issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2). 
Sui Metamask Snap is offered when Rabby wallet is in use.

Attachment: 

https://github.com/user-attachments/assets/16d52cb6-fe2e-4df2-9f5f-81cd20cf7620
