### ISSUE TITLE
[QA] [Testnet] Cannot add token using Rabby wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1555]
Preconditions:
Rabby wallet is in use

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# and https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 BNB from BSC to Moonbeam
2. Select Automatic Route
3. Add some Native gas
4. Click Approve and proceed with transaction
5. When transaction is completed click on "Add WBNB to your wallet"
6. Observe the pop-up message

Actual result: In Rabby wallet pop up message "Token not found from this contract address" is shown, cannot add the token to wallet

Expected result: Token is added

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/35165fa5-67e6-4580-af90-27b924d4bb3b

**Comment by AigaD** [comment]
Tested form: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Also for transaction 1 CELO from Alfajores to Arbitrum user cannot add token to Rabby wallet
Attachment:

<img width="1235" alt="Screenshot 2024-01-26 at 13 46 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7ab4d71c-2b44-4a09-9ad5-e0fded846860">

**Comment by AigaD** [comment]
From mainnet there are no issues when adding token, so only testnet is affected.
Checked from: https://portalbridge.com/#

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1674--wormhole-connect.netlify.app/#
Cannot add USDC.e testnet token using Rabby wallet
Attachment:

<img width="1322" alt="Screenshot 2024-04-04 at 09 32 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a431a976-2b15-4455-b3f7-3a82132477a0">

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/#
Cannot at Ws token to Rabby wallet
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b71ae962-5c70-4f4f-aebd-1043f7064cc5

**Comment by agodlevska** [comment]
Still reproduced on: https://wormhole-connect.netlify.app/.
Cannot add USDC.e, WBNB, CELO, WAVAX tokens using Rabby wallet.

**Comment by agodlevska** [comment]
The bug is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Tokens WBNB, WAVAX, CELO and USDC successfully added to the Rabby wallet. 
Closing the ticket.

Attachment:
<img width="498" alt="Screenshot 2024-07-25 at 14 00 26" src="https://github.com/user-attachments/assets/46df1f55-ea54-4be5-bdb9-ae23211d1f3b">
