### ISSUE TITLE
[QA] [Mainnet] User can send asset through an invalid route by changing the destination chain

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1558]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

1. Select "Polygon" network as source chain and connect "Metamask" wallet in "From" section
2. Select "Moonbeam" network as destination chain and connect "Metamask" wallet in "To" section
3. Select WETH (Base) asset and enter amount 0.00001 
4. Observe that **route is not available**
5. Change "Moonbeam" network to "Base"
6. Change "Base" network back to "Moonbeam"
7. Observe that it is **possible to start transaction**
8. Click "Approve and proceed with transaction" button

Actual result: Transaction is started.

Notes:
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x58b148ef85b8c5fdae610a24922d1c1a3f05966738aaa35f7c7e54c831b2f934)
* Send to tx: [Moonscan](https://moonscan.io/tx/0x67dfea994e81dc235b5abe3796396dd56efe0652af40160808f74afdf089400a)
* WETH (Base) is received on Moonbeam

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9fe0dccc-6a61-4a52-b09f-42be19118443

![Screenshot 2024-01-26 at 14 02 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2386be01-80c2-43b6-afa4-14467d854300)

## What is the expected/desired behavior
Warning is shown. It is not possible to send WETH (Base) from Polygon to Moonbeam based on ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1487.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/ac97e9d348/ [Mainnet]. User is able to start invalid route transfer. Send from tx: [Polygonscan](https://polygonscan.com/tx/0x4241389cc731ec311a69b40516e734c23eee025bbf7152b86d730b12b980ead0).

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAAcRHAJ60R0QsQi4Rk3DPmKUIrWUhoUOwWH1yYi22AC%2BIV0A%3D%3D#) and https://portalbridge.com/
Issue is no longer reproducible. User cannot send WETH asset to Moonbeam by switching to Base and back to Moonbeam, WETH asset is no longer selected.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e68a1809-4f7e-4b51-9ad5-3cea571f8362
