### ISSUE TITLE
[QA][Exodus]Transaction from Solana fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1560]
Preconditions:
Exodus wallet connected at sending From section
Keplr wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# and https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SOL from Solana to Sei
2. Click Approve and proceed with transaction
3. Observe 

Actual result: Transaction fails, reason `WalletSendTransactionError at StandardWalletAdapter.sendTransaction`

Expected result: Transaction is Approved and completes in next screen

Attachment:

<img width="1170" alt="Screenshot 2024-01-26 at 14 28 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/876ae297-d536-47ed-9bd4-fa2512fdd517">

**Comment by AigaD** [comment]
Issue still reproducible from: https://wormhole-connect.netlify.app/#
Testing from: https://wormhole-connect-mainnet.netlify.app/# is blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/1689

**Comment by tsadovska** [comment]
Exodus wallet doesn't support testnet environment. SOL transfer from [Solana](https://explorer.solana.com/tx/26hPm7nCGLQwoP1pdcDCq79aREaBpSypk2xC1d4jpber1e21BoWAJds1y4XQhEqtKsx18Ws39CLvxgRDbYnBhham) (Exodus) to [Sui](https://suiscan.xyz/tx/CqHsnDZun2UuJyrzX4AnSqQHRHYZnze8564F6AimPpvQ) (Sui wallet) was successful on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Ticket is closed.
