### ISSUE TITLE
[QA] [Brave] Claiming fails on Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1567]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Brave browser.

1. Prepare to send 0.01 ETH from Goerli (Brave Wallet) to Solana (Brave Wallet)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button

Actual result: Transaction fails. Error `Failed to sign transaction.`

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/552164a7-ed90-43a7-ab21-831887694105)

Notes:
* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x15ea30a0e584f0c53d0e35f2c449fd9707a046eecbb507b02c07a06887c85d89)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x15ea30a0e584f0c53d0e35f2c449fd9707a046eecbb507b02c07a06887c85d89?network=TESTNET)
* Issue is not reproducible when sending 0.001 ETH from Goerli (Metamask) to Solana (Phantom) with Google Chrome browser: [Etherscan](https://goerli.etherscan.io/tx/0xe6d54cb6598c406c2f8a6535aa0a01ac7e934ea1d19e324621c4b8fcbc1e67ec), [Solana Explorer](https://explorer.solana.com/tx/2r2MVT9JLYbpMZPhdckDmqXMPxzuuCiND7qSnfNz35bHiUJL7e5HXf1MmiLjw6G37v6P8CBDTEsu7zDHQqZnW5jQ?cluster=devnet)

## What is the expected/desired behavior
Transaction proceeds without error.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app 
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/557 is resolved

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. AVAX transfer from [Fuji](https://testnet.avascan.info/blockchain/c/tx/0x508e4de6f538c253bfecbaf047669f972bdc92a8e9e9ce7457a21a76515503a0) (Brave wallet) to [Solana](https://explorer.solana.com/tx/3V5BZs9hxNc3bY4GNgFJhTXVhdbFK3BMmrqW5pppgNYs5UDAJtjoz162JK85RBFYdSdWkUQQ7kdeu2fyAqY1iNX3?cluster=devnet) (Brave wallet) was completed. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/249b9749-275e-4835-8816-19b537ede745



Ticket is closed.
