### ISSUE TITLE
[QA][Mainnet] Keplr wallet when disabled is still showing as available, if Leap wallet is enabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1577]
Preconditions:
Leap wallet extension enabled
Keplr wallet extension disabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Click on Connect wallet
2. Observe Keplr and Leap wallets in the list
3. Click Keplr
4. Observe the pop-up window
5. Close the pop-up window
6. Disable Leap wallet in extensions
7. Refresh Portal bridge/Wormhole-connect page
8. Click Connect wallet
9. Observe Leap and Keplr wallets in the list
10. Click Keplr

Actual result: When Leap wallet extension is enabled, Keplr wallet also shows in the wallet list as available, although it has been disabled. When clicking on Keplr, Leap wallet pop-up is openened

Expected result: Keplr wallet shows that it needs to be installed in the wallet list when the extension is disabled

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ecd3e8e1-bdf5-4f9c-bcb6-8fc6a3516be2

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Issue still reproducible. If Keplr wallet is not available for the user, by clicking on the Keplr wallet in wallet list, Leap wallet pop-up is opened

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fc897f9f-b702-4df7-9537-de63dab496ae

**Comment by agodlevska** [comment]
Tested from: https://portalbridge.com/.
Keplr wallet extension has been disabled, but it still shows as available in the wallet list. Also, the Keplr wallet can be connected.

Attachment:

https://github.com/user-attachments/assets/d72532a7-3007-4f30-adf6-3cdd53c3fec5

**Comment by tsadovska** [comment]
Cosmos chains are no longer displayed in Networks list on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Closing the ticket.
