### ISSUE TITLE
[QA] USDC (Ethereum) is not received on Evmos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1578]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

1. Prepare to send 0.01 USDC (Ethereum) from Osmosis (Leap) to Evmos (Leap)
2. Click "Approve and proceed with transaction" button
3. Check that asset is received

Actual result: USDC (Ethereum) is not received on Evmos (Leap). Amount is not increased in wallet and on wormhole-connect.

- Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/5DA544239A63C746C0FA1F97F0D59D1A4B04B3344ED386443D14186604125592)
- Send to tx: [Mintscan](https://www.mintscan.io/evmos/tx/23416A025743149544FF0DFC0B6B394A45215EB737E2A399D15F53ED73FE6F04)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/39a1fec5-af1c-4189-a7c9-fac07e3081dd

Issue is not reproducible when:
* Sending 0.001 USDC (Polygon) from Osmosis (Leap) to Evmos (Leap): [Mintscan](https://www.mintscan.io/osmosis/transactions/8ECA4124A49F04E43C179CF26A783BA460A01FCC71F3AE37BA3935582E511B7B), [Mintscan](https://www.mintscan.io/evmos/tx/23416A025743149544FF0DFC0B6B394A45215EB737E2A399D15F53ED73FE6F04)
* Sending 0.01 USDC (Solana) from Osmosis (Leap) to Evmos (Leap): [Mintscan](https://www.mintscan.io/osmosis/transactions/D91AD02D57BDEC5CD05A3FC096CFDB2BD2E765E43CD0909043872CC3B5F6A45D), [Mintscan](https://www.mintscan.io/evmos/tx/3F3C853DCA1B1DACAF3CC67463611AA72726D01DFF19FEF0735C777D565AEA5D)

## What is the expected/desired behavior
Asset is received.

**Comment by nik-suri** [comment]
To clarify my understanding -- the assets successfully reach Evmos, but they do not appear in the user's balance?

If so, this is likely happening because of the asset conversion -- USDC (Ethereum) on Evmos is whitelisted to automatically be converted to an ERC20 asset. Querying the user's cosmos wallet address may not be representative since the tokens have been converted to the EVM-side of the chain.

We may need to query a different RPC endpoint to get the user's balance for this token.

**Comment by danburck** [comment]
Thanks for reporting! The Evmos development team is in the final steps of shipping a much better experience on handling tokens on Evmos. It's included in our next chain upgrade in a couple weeks. We call it the Unified Token Experience.

**Comment by tsadovska** [comment]
Inflows into Evmos are disabled (ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1681).
Ticket is closed.
