### ISSUE TITLE
[feat] - improve wallet search box 

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1579]
## Description and context

Currently, when someone types into the wallet search box to look for a wallet, it filters only by wallet name and not for network, since not all the wallets have the network as part of their name, if you type for instance Solana, you could probably end with none wallet displayed.

<img width="1012" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/05539544-a021-4bbd-a34a-c9db2aa54376">

<img width="1035" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/7e99ee36-13ef-4b37-8f1d-99472384c652">

## Definition of done

When I type into the wallet search box it show search by name or network

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Confirming that search in the Connect Wallet section can be done by wallet name or supported Network
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6170e49b-4a5d-427a-96d9-3db7abc86401
