### ISSUE TITLE
[QA] OKX Wallet is connected when user tries to connect Petra wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1584]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] with macOS and Google Chrome. 

1. "Petra Aptos Wallet" extension is disabled
2. Click "Connect wallet" button
3. Select "Petra" option

Actual result: "OKX Wallet" notification appears. User is able to connect OKX wallet. Petra icon instead of OKX wallet is shown when wallet is connected.

![Screenshot 2024-01-31 at 20 23 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/680709eb-38b8-4f43-9b69-4e63e933392d)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ab0664cb-d961-4268-a0f8-7da23062c939)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/36a17ea7-5a39-43de-a1f4-538f6469f336)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e372b4e8-92b4-458c-9b9f-e4c1afef7c77

## What is the expected/desired behavior
Petra option is shown as inactive when Petra extension is disabled or correct icon is used when wallet is connected.

**Comment by AigaD** [comment]
Closing, no longer reproduced.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://portalbridge.com/#
OKX wallet is not opened when user clicks on Petra wallet that has been disabled in extensions

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8c20b786-cff8-4c45-9698-a7808439496d
