### ISSUE TITLE
Integrate NTT route for Wormhole Connect

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1585]

**Comment by kev1n-peters** [comment]
## Objective
Enable users to transfer "NTT" tokens between supported chains. Users should have the option to manually execute the transfer (requiring 2 transactions) or use relayers for automatic transfer (requiring 1 transaction). Initially this will only support NTT tokens that use Wormhole verification (`WormholeTransceiver` contract).

## Specifications

- [x ] Manual NTT transfer: User incurs gas costs on both the source and destination chains, requiring 2 transactions.
- [x ] Automatic NTT transfer: User incurs gas costs and relayer fee on the source chain only, requiring 1 transaction. The relayer completes the transfer on the destination chain. Standard relayers are used for transfers between EVM chains, while specialized relayers are used for transfers to and from Solana.

## Error Cases
- [ ] Source chain rate-limits (outbound): If the user would be rate-limited on the source chain, display a warning message and prevent the initiation of the transfer.
- [x] Destination chain rate-imits (inbound): If the user is rate-limited on the destination chain, display a warning message and mention clearly that the user will need to resume the transfer in a new transaction after the rate limit expires. Also display when the rate limit expires. Display a warning if the user would likely be inbound rate-limited before the transfer on the source chain is even initiated.
- [x ] Source chain contract paused: If the contract is paused on the source chain, prevent the user from initiating a transfer.
- [x] Destination chain contract paused: If the contract is paused on the destination chain, prevent the user from initiating a transfer.
- [x] Standard relayer delivery failure: Display an error message with the revert reason. NOTE: Re-delivery support is out of scope.
- [x] Specialized relayer delivery failure: Delivery should be guaranteed unless the contract reverts (gas limit too low or misconfigured).
