### ISSUE TITLE
[QA] [Testnet, Mainnet] [Klaytn] "NaN" instead of "0" is shown in Amount field when user enters and then deletes amount

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1586]
## Describe the current behavior in detail
Checked on https://deploy-preview-1543--wormhole-connect.netlify.app/ [Testnet] and https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send KLAY from Klaytn (Metamask) to Mumbai (Metamask)
2. Enter Amount 2
3. Delete Amount
4. Check Amount field in Preview section

Actual: Text "NaN Wrapped Klay" is shown

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/38abfede-3249-4e18-975a-ccfa6be4e833

## What is the expected/desired behavior
Text "0 Wrapped Klay" is shown.

**Comment by yuli-ferna** [comment]
@tsadovska  It seems to be a general error of the manual route, it happens to me in other chains

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/c2e2c6e2-5768-409c-ab83-60aaccfc4a63)

**Comment by yuli-ferna** [comment]
@tsadovska Fixed! :)
Tested in: https://deploy-preview-1543--wormhole-connect.netlify.app [Testnet]

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/d8848433-afb2-423e-92bf-10c75d28bf81)

**Comment by tsadovska** [comment]
Thank you! Issue is no longer reproducible on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://deploy-preview-1543--wormhole-connect.netlify.app/ [Testnet].

Ticket is closed.
