### ISSUE TITLE
[QA] [Mainnet] [Klaytn] Incorrect icon is used for WKLAY asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1587]
## Describe the current behavior in detail
Build - Tested NOK: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet]
Build- Tested OK: https://deploy-preview-1543--wormhole-connect.netlify.app/ [Testnet]

Checked on macOS with Google Chrome. 

Steps:
1. Prepare to send KLAY from Klayth (Metamask) to Ethereum (Metamask)
2. Check WKLAY icon in "To" section

![Screenshot 2024-02-01 at 09 24 18](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b173c560-d9d0-44b9-a5bd-08ef47144ddc)

## What is the expected/desired behavior
Correct icon is used for WKLAY asset in "To" section.

**Comment by tsadovska** [comment]
Issue is also reproducible on transaction screen. Incorrect icon is used in link "Add <token> to your wallet".

![Screenshot 2024-02-01 at 09 53 02](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b373c25d-c0eb-44d6-9708-c2f5e2d15c6c)

**Comment by yuli-ferna** [comment]
@tsadovska Fixed!
https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet]
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/56e4ba7b-b6dd-4057-9cde-6ff7a1a3b353)

**Comment by tsadovska** [comment]
Thank you! Correct icon is shown in "To" section, in "Route" section and next to the link "Add wKLAY to your wallet" on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet].

Ticket is closed.
