### ISSUE TITLE
[QA] [Testnet, Mainnet] User can click on "Approve and proceed with transaction" button when amount is not entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1588]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 1 SOL from Solana (Phantom) to Mumbai (Metamask)
2. Clear Amount field
3. Click on "Approve and proceed with transaction" button 

Actual result: Transaction fails.
```
Error: invalid decimal value (argument="value", value="", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (main.js:166:46766)
    at Logger.throwError (main.js:166:46899)
    at Logger.throwArgumentError (main.js:166:46960)
    at parseFixed (main.js:166:62069)
    at parseUnits (main.js:169:83125)
    at RelayRoute.send (main.js:523:30007)
    at Operator.send (main.js:525:79536)
    at Object.gr [as onClick] (main.js:691:95837)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/79425bff-7b7b-4440-b7d7-3c88638e0af8

## What is the expected/desired behavior
User can click on "Approve and proceed with transaction" button only when all fields are entered.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/#
Transaction APT from Aptos (Petra) to Klaytn (Metamask)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a11166ab-b7da-429c-8c40-40e09c0b9ca4

**Comment by AigaD** [comment]
Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 0.01 CELO from Celo to Fantom
2. Observe that all fields are active, Automatic route is not active
3. Delete the amount
4. Observe 

Actual result: After deleting the amount Approve button and Native gas fields are shown, Approve button is active and user can click on it

Expected result: If the amount is deleted the Native gas field is not shown and Approve button is not active

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd28cea8-1654-4ba5-a71f-511b900819ae

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Approve button is shown when user deletes the amount entered
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e903ad53-8071-4d28-ab7b-9533e3d47168

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.
"Approve and proceed with transaction" button is not displayed when amount is not entered. 
Ticket is closed.
