### ISSUE TITLE
[QA] [Mainnet] [Klaytn] WKLAY contract address on wormhole-connect is different from contract address in Metamask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1589]
## Describe the current behavior in detail
Checked on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Open Metamask extension > Switch to Ethereum network > Check token details for WKLAY asset
2. Open wormhole-connect > Select Ethereum network > Connect Metamask wallet > Open Assets list > Check contract address for WKLAY asset
3. Compare contract addresses

Asset in explorer: https://etherscan.io/token/0x9AEA32B459e96C8eF5010f69130bf95fd129ac05

![Screenshot 2024-02-01 at 10 03 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/064618c0-5741-4309-9c7a-d4b4175294aa)

## What is the expected/desired behavior
Contract address on wormhole-connect and in Metamask is the same.

## Notes
* Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues.
* Issue is also reproducible on Celo network on https://preview.portalbridge.com/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible from https://preview.portalbridge.com/b05f4e9322/ [Mainnet] on Polygon. 
* WKLAY contract address on Portal Bridge: 0xe4f0...C817
* WKLAY contact address in MetaMask: 0x415ce980fde17F1FF102e1c6e4ce860Acc615D74, [Polygonscan](https://polygonscan.com/token/0x415ce980fde17F1FF102e1c6e4ce860Acc615D74)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
wKLAY contract address on Optimism network from Wormhole-connect and Metamask are different.
Attachment:
<img width="968" alt="Screenshot 2024-05-08 at 15 37 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bb694570-28d1-4ce7-af50-4c847180d6f1">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] on Blast. 

![Screenshot 2024-05-13 at 14 16 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/78ff66c0-c8f1-4646-9c85-bea4d2f7a519)

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:
* WKLAY (Klaytn) on Ethereum, 0x9AEA32B459e96C8eF5010f69130bf95fd129ac05
* WKLAY (Klaytn) on Polygon, 0x415ce980fde17F1FF102e1c6e4ce860Acc615D74
* WKLAY (Klaytn) on Optimism, 0xbbeF8233a0d10EEAb84E913FaDB337ab9b62F683

Blast network is not displayed in Networks list on Portal Bridge. 
Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by tsadovska** [comment]
Changes have been merged on https://portalbridge.com/ [Mainnet], correct contract addresses are displayed.
Closing the ticket.
