### ISSUE TITLE
[QA] [Improvement] [Klaytn] [Mainnet] Show checksummed contract address for WKLAY

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1591]
## Describe the current behavior in detail
Checked on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Open Metamask extension > Switch to Klaytn network > Check WKLAY token contract
2. Open wormhole-connect > Select Klaytn network > Open Assets list > Search for WKLAY asset > Check WKLAY contract address 
3. Compare contract addresses

Actual result: Contract address on wormhole-connect is displayed only with lowercase letters. 

Asset in explorer: https://scope.klaytn.com/token/0xe4f05A66Ec68B54A58B17c22107b02e0232cC817

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f8cfc397-43b8-4306-905c-98a2b88259c6)

## What is the expected/desired behavior
Contact address is displayed with lowercase and uppercase letters. 
Contract "0xe4f0...C817" instead of  "0xe4f0...c817" is shown.

**Comment by yuli-ferna** [comment]
@tsadovska Fixed! :) 
https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet]

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/35125931/b7d6ba4c-4236-4ccc-8980-31a3e1c4d3f6)

**Comment by tsadovska** [comment]
Thank you! Checksummed contract address is shown on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Ticket is closed.
