### ISSUE TITLE
[QA] [Testnet, Mainnet] WMATIC contract address on wormhole-connect is different from contract address in Metamask 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1595]
## Describe the current behavior in detail
Checked on https://deploy-preview-1543--wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome.

Steps:
1. Select Klaytn network as source chain > Connect Metamask wallet > Open Assets list > Check WMATIC contract address
2. Open Metamask extension > Switch network to Klaytn Testnet > Check WMATIC token details

Asset in explorer: https://baobab.klaytnscope.com/token/0xca8d3675585D27E5c98c1aB885260AC2E4eD97BE?tabId=tokenTransfer

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/117a35b1-49f7-416f-a13a-dc71262fca5f)

## What is the expected/desired behavior
Contract address is the same on wormhole-connect and in Metamask.

## Notes
* Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues.
* Issue is also reproducible on Celo network.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![Screenshot 2024-03-11 at 17 12 45](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/28b95e25-4d8d-46a0-b630-bb2a3561fd89)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) on Moonbeam network. Asset in Explorer: https://moonscan.io/token/0x82DbDa803bb52434B1f4F41A6F0Acb1242A7dFa3

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/ [Mainnet] on Celo network. WMATIC in Explorer: [Celo Explorer](https://explorer.celo.org/mainnet/token/0x9C234706292b1144133ED509ccc5B3CD193BF712/token-transfers). 

<img width="876" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5812031a-036c-4040-a180-62b6a02b6953">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ on BSC network. WMATIC on Explorer: https://bscscan.com/token/0xc836d8dC361E44DbE64c4862D55BA041F88Ddd39

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/455da9c1-a871-4d85-bf59-5308961b1362)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/bceadc8c64/#
WMATIC token contract address is different on Portal and Metamask
WMATIC contract address in Metamask - 0xb88A6064B1F3FF5B9AE4A82fFD52560b0dF9FBD3
Attachment:
<img width="972" alt="Screenshot 2024-05-08 at 12 38 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/66520ef8-8304-4940-9f9c-917cf4a65dc3">

**Comment by tsadovska** [comment]
Tested OK on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Ticket is closed.
