### ISSUE TITLE
[QA] [Mainnet] Cannot claim asset on Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1598]
## Describe the current behavior in detail
Checked on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet].

Steps:
1. Prepare to send 0.0001 wKLAY from Moonbeam (Metamask) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button
4. Approve Phantom notifications

Actual result: Loading doesn't finish. Asset is not received. 

Send from tx: https://moonscan.io/tx/0x29cb719238a3eef2dd4797d6f4a1ab53cafadb9241829339166000e1b6c1efd9

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b393f33d-f302-41a5-953c-3a1b8b7eb311)

## What is the expected/desired behavior
User can successfully claim asset.

**Comment by tonyjin** [comment]
I tried to recover this tx (0x29cb719238a3eef2dd4797d6f4a1ab53cafadb9241829339166000e1b6c1efd9) via:

- Wormhole Connect: Error message with "Bridge transaction not found, check that you have the correct chain and transaction ID", see screenshot of console error
<img width="1078" alt="Screenshot 2024-02-05 at 10 08 41 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/689351/1d48b5c6-8b61-4a0a-b081-de999ebaca5e">
- Advanced Tools: Recover flow correctly identifies unclaimed Solana-bound tx

**Comment by tsadovska** [comment]
Transaction hash `0x29cb719238a3eef2dd4797d6f4a1ab53cafadb9241829339166000e1b6c1efd9` can be successfully found on https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/ [Mainnet], but when searching the same hash on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] I have the same error as @tonyjin :
```
UnknownDomainError: Attempted to access an unknown domain: 13.
Hint: have you called `context.registerDomain(...)` yet?
    at WormholeContext.resolveDomainName (main.js:337:1721)
    at WormholeContext.toChainName (main.js:350:627412)
    at EthContext.getMessage (main.js:347:86607)
    at async Operator.getRouteFromTx (main.js:525:76659)
    at async Object.pr [as onClick] (main.js:796:6084)
```

**Comment by sebastianscatularo** [comment]
I've saw that issue, on an injective tx, and was due that connect does not support injective, for this case, not sure what's going on

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Loading does not finish for transaction from [Klaytn](https://baobab.klaytnscope.com/tx/0x3821a4487e24cdd91cf8343fe4ff17bfcdba98e95eb014a4f7837576ea76bb88) to Solana

Attachment:
![Screenshot 2024-02-07 at 12 38 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/023e7bd6-7808-4281-a31c-7ad5616fed68)

**Comment by AigaD** [comment]
Closing the ticket.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.01 WFTM from [Moonbeam](https://moonscan.io/tx/0x9d84980535e015d1c7b6713d9721e440fa50d3206b71fdf87d0652e901a1a986) (Metamask) to [Solana](https://explorer.solana.com/tx/21bxegrYeiUqFNhGqEVddoLULCMcLKJNZp6zfExnKL6CoKEME9zy8vNLhf2TyA9jo86xz3XdWWCqbFZQxgMLZtkn) (Phantom) was completed.
Transaction 0.01 wKLAY from [Moonbeam](https://moonscan.io/tx/0x54bd5fa9892363f2a6cb5f7857b5e921aee7fbe68c157ff148ece32393ff0a53) (Metamask) to [Solana](https://explorer.solana.com/tx/4TP1WcnpusWVxi81jJWPTDzWcWshDjFBPmavp7qDtgjgJg2hLNCvE3y4Dj4NQGTDM94jhxh23LFubxDu5c6tsjQA) (Phantom) was completed

Attachment:

![Screenshot 2024-03-07 at 12 56 50](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ef574b8e-87ed-4e75-91a3-21c1c33699c4)

![Screenshot 2024-03-07 at 13 04 33](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7e18401-3d32-4d46-b3cc-7f3cd15b1c4c)
