### ISSUE TITLE
[QA][Mainnet] Claiming on Aptos fails, transaction issue

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1602]
Preconditions:
Solflare wallet connected at sending From section
Fewcha wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.01 SOL from Solana to Aptos
2. Click Approve and proceed with transaction
3. Click Claim when possible
4. Observe

Actual result: Transaction fails at Claim, reason `Error: Transaction issue
`
Expected result: Token is claimed and transaction is completed

Attachment:

![Screenshot 2024-02-05 at 09 29 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/77b504b6-8385-4c80-8608-af92cf07f7dc)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d8bc9b48-0b9e-4706-9469-7336278047ec

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from [Solana](https://explorer.solana.com/tx/2WgQkUfiDM1bRWPMoH7rJnSn7nUoeSjYdGZfo86AdMR9TAtSBC57jVj1vZhrVHFNVNPiojo9ZqjFhgV57eeMp5aA) (Solflare) to [Aptos](https://explorer.aptoslabs.com/txn/0x60f26f5c6ca0846da6789facee856f91e86a95f480b4c9fc2a0a361962102b77?network=mainnet) (Fewcha) was completed.
Closing the ticket.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4b6b8a92-ec69-426e-95ce-8da987781d21

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.01 USDC (Arbitrum) from Arbitrum (Metamask) to Aptos (Fewcha) fails at Claim, console shows `Error: Transaction issue`
Attachment:

<img width="1370" alt="Screenshot 2024-02-19 at 13 11 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4af35231-048a-4db9-9cbe-f5c92bc9a60d">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3752e90-4e4d-40fc-8ef2-644c05ff0d0f

**Comment by AigaD** [comment]
Issue reproduced from https://portalbridge.com/
Transaction 0.01 USDC from Arbitrum (Metamask) to Aptos (Fewcha) fails at Claim, reason `Error: Transaction issue`
Attachment:

<img width="1384" alt="Screenshot 2024-03-28 at 12 45 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aaaf5b1e-6388-4c50-83fa-bab960ca5266">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a4b42b7a-5dce-454b-a1b5-0b91a91eeefb

**Comment by agodlevska** [comment]
Issue is still reproduced from https://portalbridge.com/
Transaction 0.01 USDC from Arbitrum (Metamask) to Aptos (Fewcha) fails at Claim with error message: 
`Error with transfer, please try again.`

Attachment:
<img width="1440" alt="Screenshot 2024-05-22 at 11 50 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/463931da-57e5-4981-a6ba-6999059112a1">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://portalbridge.com/ [Mainnet] with the scenario mentioned above. 
Scenario checked: 0.0001 USDC transfer from Arbitrum (MetaMask) to Aptos (Fewcha). 
* Send from tx: https://arbiscan.io/tx/0x69b275d282ce19a4b280ff0486daac31f2ce5be8c9641208d65163c82c29011a
* Link to Wormholescan: https://wormholescan.io/#/tx/0x69b275d282ce19a4b280ff0486daac31f2ce5be8c9641208d65163c82c29011a

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d35d582-63a2-4f15-969e-8e2d6ca9de76)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/ when sending 0.0001 USDC from Arbitrum (MetaMask) to Aptos (Fewcha).

- Send from tx: [Arbitrum](https://arbiscan.io/tx/0x349a538a1cefd1661ba934374b404ba96d051e5f798d0b1ce7a20290e7c44c92)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x349a538a1cefd1661ba934374b404ba96d051e5f798d0b1ce7a20290e7c44c92)

Error: 
```
ApiError: Bad Request
    at catchErrorCodes (pb-index-CQl3SLEd.js:271:64333)
    at pb-index-CQl3SLEd.js:271:64797
```
