### ISSUE TITLE
[QA][Mainnet] Add <suggested> token button is not reacting

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1604]
Preconditions:
Sui wallet connected at sending From section
Exodus (Ethereum) wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.1 WAVAX from Sui to Avalanche
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. When transaction is completed click on Add <suggested> token to wallet
5. Observe

Actual result: Add token button is not reacting

Expected result: Token is added to the account

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a331f0ad-c78f-4171-9853-017d1a97ac05

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
For transaction Solana to Base, WSOL add token button is not reacting
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/34213b65-11b2-43a2-b0e1-405a7495eaf6

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Cannot add suggested WSOL token to Klaytn Network. error in console `'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/505121fc-fa1f-4951-8d36-124aab0cb8fc

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/749d45da9e/#
Add <token> to your wallet button is not reacting for transaction SOL from Solana to BSC
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/df892cff-6a98-4818-a738-98de3436e74f

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Add <token> to your wallet button is not reacting for transaction 0.01 GLMR from Moonbase to BSC

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/052c4809-e8b8-4349-9e1d-00561ab446c6

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 1 SOL from Solana (Phantom) to Fantom (MetaMask). Error appears in Console when clicking on "Add WSOL to your wallet" link:

`MetaMask - RPC Error: The symbol in the request (WSOL) does not match the symbol in the contract ( ) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract ( )'}`
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract ( )'}`

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 WSOL from Kujira (Keplr) to Base (MetaMask). Send from tx: [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/7F85766DDB6C13624C72E5E08FB16B6991AEC9B97434EC74B47710D6AB24F570), Send to tx: [BaseScan](https://basescan.org/tx/0xcce72a2693955aac3824d34173eebb8e83e79a44b97ef785a51e350099b98895).

Error when clicking on "Add WSOL to your wallet" link:
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

**Comment by tsadovska** [comment]
Issue is also reproducible on https://portalbridge.com/ [Mainnet] when sending 0.001 ETH (Optimism) from Optimism (MetaMask) to BSC (MetaMask). Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0xc024f742e44712309e13eb8622e252c01690401c0e252ea9b883a174299eef21), Send to tx: [BscScan](https://bscscan.com/tx/0xaa54fae5f5dead683035f521ef7dcdedee11053d115955800b5bd3b65c65f251).

Error after clicking on "Add WETH (BSC) to your wallet" link:
 ```
Uncaught (in promise) 
{code: -32602, message: 'The symbol in the request (WETH) does not match the symbol in the contract (ETH)'}
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c69d9a7a-f1e9-4328-83d1-abe5625b1c90)

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/#
Add token button is not adding the token to wallet for transaction ETH (Ethereum) from Ethereum (Metamask) to BSC (Metamask)
Button reacted to network switch, but when adding the token error in console `'The symbol in the request (WETH) does not match the symbol in the contract (ETH)'` is shown
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6e9e883d-3dac-4ffb-a934-4d737fafc593

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending USDC.e from Polygon (MetaMask) to Celo (MetaMask). Send from tx: [Polygonscan](https://polygonscan.com/tx/0x5631ee5a124b23663326faffdd38735ae7c0aaf8ca4058eeb264dd5b89393c1a), send to tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0xfa60c90f751ab8d8e6d4d94c457d0b8bcc356c1ace7374c79f5b8a30439c1f04). 

Error appears after clicking on "Add USDC.e to your wallet" link:
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (USDC.e) does not match the symbol in the contract (USDC)'}`

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Add WSOL token to wallet button is not reacting for transaction 0.001 WSOL from Optimism to Base
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ee80ac64-3bd1-48d3-8f0f-990c1e0401e0

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/#
Add WSOL token button is not reacting when SOL asset is sent from [Solana](https://explorer.solana.com/tx/AUMBmZ79izLWfoAxVeuXrL2yJdRTxPfzd6xhyLCqCLRLkWexwWaCX3xQg3myRUPSYJcuS2VxKzpPxX2svs5zKXA) to Polygon network results in `'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending SOL from Solana to Celo. 
Error appears after clicking on "Add WSOL to your wallet" link: `Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/44UcLGJk8fZu4k4A15J9Jz6eiPuHqW5meSygasoESvA1Tz4fyYf3amYisoJZSDH4Fhi2arvXHrrGPr6aaTu4cLhi)
* Send to tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0x8e7bac0a199bff3b4b3559a58f27e8d9f0184427d918228bdf852826987a0b0e)

**Comment by AigaD** [comment]
Add token button is not reacting for transaction GLMR from [Moonbase](https://moonbase.moonscan.io/tx/0x9b0f016056ad4f857e98940521e515e08c92f82bdc140acf8ceb3d0e8b6e046f) to [Alfajores](https://explorer.celo.org/alfajores/tx/0x5b6cef3befff1f95d9bbc14150f504a56c46788629d69fa2a414b25b65be2e98).
Tested from: https://wormhole-connect.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c1bf2858-270d-486b-8432-df49ca7fd760

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending 0.0001 WSOL from Osmosis (Leap) to BSC (MetaMask). Error appears after clicking on "Add WSOL to your wallet" link:
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`
* Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/CB8CDE9BD6F2A766100A1E3A0D6E712B0C513EEBF5D926F651761AB97463E84A)
* Send to tx: [BscScan](https://bscscan.com/tx/0xd266c5ec1022671761bd505eb856dd8bc08d77f6bec95597af9ebccc8daa5917)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/#
When sending 0.01 WSOL from [Optimism](https://optimistic.etherscan.io/tx/0x1b120e34fa23e030a2a1b2745a9d585799471a61846bdc003df5209d17447f8f) to [Polygon](https://polygonscan.com/tx/0x1c54ff28a475b3eb39f67a5b9188478f63ec3fe594baeab60e304fd65763bb8f) Add WSOL to you wallet is not reacting `'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'`

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6). 
Error `Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}` appears after clicking on "Add WSOL to your wallet" link. 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/z7Byp9oCE6YDZLyXVHr6Ped3Gh74xYTkEXyCjvMqr38GwyWhGHiU9rAvZQvHoG1nabPVbrucNdfj7pEEU2hSyJD)
* Send to tx: [FTMScan](https://ftmscan.com/tx/0x42e0f8eb3c31fc603be347699d1404fe3ad470496c077148d59e2012982a5aaf)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6).
Error `Uncaught (in promise) {code: -32602, message: 'The symbol in the request (USDC.e) does not match the symbol in the contract (USDC)'}` appears after clicking on "Add USDC.e to your wallet link". Scenario: Send 0.0001 USDC.e (Polygon) from Polygon (MetaMask) to Avalanche (MetaMask). 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0xfa1f172af90c4f027ceff78c7f4fa4a10e8f64b88f54fe6b828a533c1f1f06ab)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x57a09053b5fcf1692e48b7937b25c9f8845edb318af7e1a40c87d9c76d952ede)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/8228d00809/#
For transaction 0.001 ETH (Base) from Base to Avalanche, add token button is not reacting `'The symbol in the request (WETH) does not match the symbol in the contract (WETH.e)'}`
Attachment:

<img width="1309" alt="Screenshot 2024-04-03 at 10 51 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c21bb914-cdd2-4117-b6fa-9f549232c6f1">

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Add WSOL to your wallet button is not reacting for transaction SOL from Solana (Solflare) to BSC (Metamask) `'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/#
Cannot add W token to Sepolia wallet `'The symbol in the request (W) does not match the symbol in the contract (Ws)`
Attachment:

Uploading Screen Recording 2024-04-15 at 19.49.32.mov…

**Comment by AigaD** [comment]
Tested OK from: https://testnet.portalbridge.com/ed4e22522f/#
User is able to add Ws token to wallet
Attachment:
<img width="1266" alt="Screenshot 2024-04-16 at 08 38 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a4ce0e0a-0970-4a22-bb5f-e6de3119056a">

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNxEc00NIWIRcIybhnzFWAFaQAxrgyxImwWB1yYigOoAxACoBZW2AC%2BIXyA#)
Cannot add WSOL to wallet for transaction SOL from Solana 9Solflare) to Optimism (Metamask), `VM396:1 MetaMask - RPC Error: The symbol in the request (WSOL) does not match the symbol in the contract (SOL) 
{code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] when sending 0.011 WSOL from Solana (Phantom) to Avalanche (MetaMask). Error appears in Console after clicking on "Add WSOL to your wallet" link: 

`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}`

* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/2sWDnb1G5JcnzZrnTRhJ1eh8GvkRfYLPzJG2aNBsNpduzJqAPBNANTpeXc4dcVmweZiZuRRXkwWSL3M6KYnwwERT)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0xcc5f72dc87bdb124137dfd5c22dd790c4153656e201112c723c99f89cae2b763)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/867455)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f02fe4e6-4756-40db-a666-248ef91122de)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
When adding WETH to BSC using [Wormholescan](https://wormholescan.io/#/tx/0x8c53473b102fb1caa5316eb581fa889ee99cbc67fbca6d78c804b60dc2a34446) for transaction form Ethereum to BSC, message `'The symbol in the request (ETH) does not match the symbol in the contract (WETH)` is shown and token is not added

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae5b5978-9e98-4677-ae04-5f4559018123

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0005 WETH (Polygon) from Polygon (MetaMask) to Avalanche (MetaMask). 

Error is shown after clicking on "Add WETH (Avalanche) to your wallet" link:
`MetaMask - RPC Error: The symbol in the request (WETH) does not match the symbol in the contract (WETH.e) {code: -32602, message: 'The symbol in the request (WETH) does not match the symbol in the contract (WETH.e)'}`


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/49ca9993-3ee8-46cf-85e3-436b86b43347)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
Cannot add WSOL token to wallet after transaction is completed `VM36:1 MetaMask - RPC Error: The symbol in the request (WSOL) does not match the symbol in the contract (SOL)`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f57e34a-d8a4-4db5-9dc9-4ca30eb6ac0b

**Comment by agodlevska** [comment]
Reproducible on https://portalbridge.com/#
Sending 0.0003 SOL from Solana (Solflare) to X Layer (Metamask).
Unable to add WSOL token, error message: `VM236:1 MetaMask - RPC Error: The symbol in the request (WSOL) does not match the symbol in the contract (SOL)`

**Comment by agodlevska** [comment]
Reproducible on hhttps://preview.portalbridge.com/2c6f665417/
Sending 0.001 SOL from Solana (Backpack) to Fantom (MetaMask).

Attachment:
<img width="1440" alt="Screenshot 2024-06-17 at 15 44 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/d5ae20fa-8408-4051-8e38-2669ecb891a1">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] when sending 0.0005 wstETH from Ethereum (MetaMask) to BSC (MetaMask) with "Native Token Transfer (NTT) - Lido Bridge" route.
* Send from tx: [Etherscan](https://etherscan.io/tx/0x9b18009b3fe5d3c75d2f81d5538e106fe6a3ad27b5b66ed1660d8337a7574968)
* Send to tx: [BscScan](https://bscscan.com/tx/0x299d5d8cb6f1c59b24801267fa36a80937d1fdaf89ff8207301a796b3d95130d) 
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x9b18009b3fe5d3c75d2f81d5538e106fe6a3ad27b5b66ed1660d8337a7574968)

Error appears in Console after clicking on "Add wstETHbsc to your wallet" link:
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (wstETHbsc) does not match the symbol in the contract (wstETH)'}`
 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1d011944-3bb3-4e78-b3b7-aceb8800817a)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/321a610744/ [Mainnet] when sending 0.001 WSOL from Solana (Solflare) to Moonbeam (MetaMask).

Send from tx: [Solana](https://explorer.solana.com/tx/4UP3jvvDLq1j1zShdndUZzDPE5eMqS82tt8g4y3HV21JhgJaGuPCxbXrfpTziYZr7TWeYw3H8bRrHqNWVHP6EpZH)
Send to tx: [Moonbeam](https://moonscan.io/tx/0x097f1a30abf371e891f444ac128b8016f7a626c155c491a67c933c57d4f412f7)
Link to [Wormholescan](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/932211)

Errors:
```
Uncaught (in promise) 
{code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}
``` 
```
MetaMask - RPC Error: The symbol in the request (WSOL) does not match the symbol in the contract (SOL) {code: -32602, message: 'The symbol in the request (WSOL) does not match the symbol in the contract (SOL)'}
```

**Comment by tsadovska** [comment]
"Add <token> to your wallet" link is no longer shown after redesign. 
Closing the ticket.
