### ISSUE TITLE
[QA] Incorrect wallet address was shown for transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1606]
Preconditions:
Metamask wallet connected at sending From section
Nightly Wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://wormhole-connect.netlify.app/# 

Steps:
1. Prepare to send 0.001 ETH from Goerli to Aptos
2. Click Approve and proceed with transaction
3. Observe if the correct wallet address is shown at sending from section

Actual result: Address with multiple 0'os was shown instead of the correct wallet address

Expected result: Correct wallet address shown

Comments: Noticed this happening once. Creating ticket to keep track if this would be reproduced again

Attachment:

![Screenshot 2024-02-05 at 17 29 17](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0232006b-603b-46d0-8b92-92d3521ec2f2)

**Comment by tsadovska** [comment]
Reproduced once on https://wormhole-connect.netlify.app/ [Testnet] when sending ETH from Goerli (MetaMask) to BSC (MetaMask). Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xcd1a5ce6c1441bbcf3444636873be56d6c26186d71483d37818bc71b8eb0828d). Correct wallet account is shown when transaction is resumed (Menu > Resume transaction). 


![Screenshot 2024-02-14 at 10 21 00](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/738e5217-b309-476c-bea9-080ab6a30a6e)

**Comment by AigaD** [comment]
Closing this as Ethereum network is being deprecated. Have not reproduced this with other networks. If the issue will re-appear ticket will be reopened.
