### ISSUE TITLE
Include the hashed css file for WalletConnect

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1607]
Fix for WalletConnect - it should work with this change

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Managed to successfully connect Metamask app to WormholeConnect, but the transactions were failing. Ticket created for WormholeConnect Ethereum - https://github.com/wormhole-foundation/wormhole-connect/issues/1622
When trying to connect Phantom App with WalletConnect Solana, the QR code shows as invalid. Added comment to this ticket - https://github.com/wormhole-foundation/wormhole-connect/issues/1508
