### ISSUE TITLE
Wallet aggregator update - Change name for OKX and Bitget wallet

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1608]
## Description and context

New names to display: "OKX Wallet" and "Bitget Wallet" respectively

## Definition of done

The names of the wallets in the list are "OKX Wallet" and "Bitget Wallet" respectively

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
OKX Wallet - tested OK
Bitget Wallet - issue created https://github.com/wormhole-foundation/wormhole-connect/issues/1621 


![Screenshot 2024-02-08 at 16 26 51](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cafbb58b-ded1-4ce5-ba83-10a3ff9b8d24)

**Comment by AigaD** [comment]
Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1621 tested OK. Changing status for this ticket.
Attachment:

![Screenshot 2024-02-09 at 19 20 31](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/96683040-08cf-4966-92da-98a4bb633d50)
