### ISSUE TITLE
Add Sepolia testnets

### ISSUE THREAD

**Issue by kev1n-peters** [wormhole-foundation/wormhole-connect#1614]
Goerli has been deprecated for Ethereum at least and new deployments are happening on the Sepolia networks for native token transfers. Support these networks in Connect.

**Comment by tsadovska** [comment]
Tested OK:
* Check that balance is loading for Sepolia
* Check that transaction from Sepolia is successful (Send from tx: [Etherscan](https://sepolia.etherscan.io/tx/0x317f689b7add9690cf28baad525f1f5375a4dfb12f6545d15d055db5c0086dca), Send to tx: [FtmScan](https://testnet.ftmscan.com/tx/0x69ac0c2be774b269ebf510607f9a6a7e2c171a257f3e60a6722d2cd1cb8d0a05))
* Check that transaction to Sepolia is successful (Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0xb803e13a7e840d4ef9c1d0763d595910e52a1e1af8b767483fb5ca99973ef764), Send to tx: [Etherscan](https://sepolia.etherscan.io/tx/0xdf49322e16087086a4594210300869ab0e13e37feaf18e17af0ac0315bdda7b8))
* Check that user can resume Sepolia transaction
* Check that Sepolia, Arbitrum Sepolia, Base Sepolia and Optimism Sepolia options are shown in dropdown in "Resume transaction" screen (Menu > Resume transaction).
* Check that network icons are displayed for Sepolia, Arbitrum Sepolia, Base Sepolia and Optimism Sepolia on desktop

Tested NOK:
* Check that balance is loading for Arbitrum Goerli, https://github.com/wormhole-foundation/wormhole-connect/issues/1636
* Check that balance is loading for Base Sepolia, https://github.com/wormhole-foundation/wormhole-connect/issues/1643
* Check that balance is loading for Optimism Sepolia, https://github.com/wormhole-foundation/wormhole-connect/issues/1644
* Check that user can register assets for Sepolia networks, https://github.com/wormhole-foundation/wormhole-connect/issues/1630
* Check that Arbitrum Sepolia icon is displayed on mobile, https://github.com/wormhole-foundation/wormhole-connect/issues/1306
