### ISSUE TITLE
[QA] Transaction is still confirmed from wallet side, when on Wormhole shown as completed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1618]
Preconditions:
Sui wallet is connected at sending from section
Rabby wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SUI from Sui to Klaytn
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe the transaction in Rabby wallet pop-up
5. Observe the transaction

Actual result: Occasionally wallet confirmation is still in progress when transaction shows as completed

Expected result: Transaction is confirmed from wallets side and then shown as completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f6ab96c2-3a41-42d9-b4dc-a28de89ca029

![Screenshot 2024-02-08 at 10 17 46](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b0763f61-d0d9-4465-8125-a928d65f9c2b)

![Screenshot 2024-02-08 at 10 16 39](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ac073d5c-287b-4bed-a52c-127eb843a13c)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced for transaction from Fuji to Klaytn. Rabby pop-up shows that the transaction is still in progress, but Wormhole-connect shows that it is already completed
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ea1d1310-dbf1-44d3-ba97-22074b1e73e0

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced for transaction 0.01 wKLAY from Sepolia (Rabby) to Klaytn (Rabby), transaction was still signed on wallet pop-up, but on bridge screen showing as completed.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/edbdb54f-7bd1-414a-b55c-92730222f1b9

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ when sending SUI from Sui (Sui) to Klaytn (Rabby). 

https://github.com/user-attachments/assets/7a1131c9-6ab5-40e5-83d5-8d2d473f21fa

Closing the ticket.
