### ISSUE TITLE
[QA][Mainnet] Wallet is written twice for Bitget wallet and shown twice for Solana network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1621]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Click on Connect Wallet
2. Search Bitget
3. Observe wallet for Solana network

Actual result: Wallet is written twice for Solana supported Bitget wallet and also wallet itslef repeats twice in the list

Expected result: It is written Bitget Wallet https://github.com/wormhole-foundation/wormhole-connect/issues/1608

Attachment:

![Screenshot 2024-02-08 at 16 27 00](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2be08b25-0fb1-4a4d-bce5-c07b16404343)

**Comment by sebastianscatularo** [comment]
@AigaD could you share the current Solana wallets that you have installed? since I'm not able to reproduce it at the same deployment as you did, could be something with your current setup, also could you try on incognito or cleaning up your session?

<img width="1019" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/1277510/7debf91c-6ba2-4404-a39d-32306e8a8cb9">

**Comment by AigaD** [comment]
Cleaned up history, but still two Bitget wallets were shown for Solana

My current wallets that are installed and enabled:
Phantom
Solflare
Bitget
Nightly
Exodus
Backpack
OKX Wallet
Coin98
Wallet installed, but disabled in extensions: Solong

![Screenshot 2024-02-09 at 14 11 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e4f0e209-00b5-446c-9e2e-cabfda2bdd04)


For incognito I also see only one Bitget for Solana, but unfortunately I can not check it when the extension is added, it doesn't allow to do it in incognito.

![Screenshot 2024-02-09 at 14 16 37](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e7837506-25ba-4fc2-8feb-aa90ac8971c6)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Verifying that there are no longer two Bitged wallets shown for Solana Network
Thank you for the fast fix!
Attachment:

![Screenshot 2024-02-09 at 19 20 31](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/44fd8360-efbf-4982-8ac4-e327acbefd3d)
