### ISSUE TITLE
[QA][Mainnet] Cannot start transaction using WalletConnect

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1622]
Preconditions:
Metamask wallet connected though WalletConnect
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85
iPhone 14, iOS 16.0

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.01 ETH from Ethereum to BSC
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `main.js:696 Error: No matching key. keychain: a053bbbac7fcc361019e8dd938ab47f8102dab027e59dbe2d8666a95916ea4e6`

Expected result: Pop-up to confirm the transaction is shown on mobile device, transaction is started

Comments: Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1607

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/734f64b3-22ba-4d86-9e71-1b85a3ffad28

![Screenshot 2024-02-08 at 16 55 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f53e217-baf8-4ce4-a31b-8522da10b23d)

**Comment by SamantaCasal** [comment]
I was able to perform a txs. 
TX: https://wormholescan.io/#/tx/0xf557a6932d3f77cc1ee4e304ba0899a261517a543bb57f66ea50146e057b6e0d 
Evidence: 

https://github.com/wormhole-foundation/wormhole-connect/assets/69044575/0fbfd469-422c-4a20-b68b-10b6656ded9b

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Managed to start the transaction when wallet is connected through WalletConnect, however it seems that the Confirm pop-up on Metamask mobile app does not appear if the Network has to be added. The loading on Wormhole connect continues until fails with error `'Request expired. Please try again.'` Clicking second time on Approve button the transaction is started, the pop-up on mobile device to confirm transaction appears

Attachment: 
![Screenshot 2024-02-09 at 18 20 49](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/28166ee9-ebb0-470d-b7ca-f3d68a7d55d6)

Transaction recording from computer: 

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e2168bb3-6ba2-40c8-8bf2-b5e10f11efb0

From mobile device:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/423b9b60-3c14-4216-b578-f9b767aba224

**Comment by AigaD** [comment]
If the network had been previously added to Metamask, the transaction runs smoothly.
Attachment:

[Mobile screen recording with transaction](https://drive.google.com/file/d/1l9z9mItM2cUzNE_Vmq-isJc-RXWWUFHU/view?usp=sharing)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced also from testnet, transaction confirmation is not shown, when new Network is added to the newly installed Metamask mobile app. Transaction expires

Attachment:

![Screenshot 2024-02-12 at 10 21 49](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/58873553-5905-4518-84c3-aeef60d1d8a4)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction eventually also expires if the Network has been previously added and Metamask app has been previously connected through WalletConnect for another transaction. No Confirm pop-up shows on the Metamask mobile app to confirm the transaction.
Confirm pop-up was shown if user disconnected and then re-connected with WalletConnect Metamask wallet app
Attachment:

![Screenshot 2024-02-12 at 13 42 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f7ec8301-fe4b-43ea-b7d5-858ba7d80d62)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/749d45da9e/#
Confirm notification is not showing on mobile Metamask app after pressing Approve and proceed with transaction for transaction BNB (WalletConnect Metamask app) to Fantom (Wallet Connect Metamask app)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/015c79a7-6325-4f19-804c-4f7385733a7c

![Screenshot 2024-02-16 at 14 26 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c1adebf9-5345-410a-8245-5521a0a24f5b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:

Preconditions:
* MetaMask wallet was previously connected with QR Code through WalletConnect.
* Phone is locked.

Steps:
1. Open https://wormhole-connect-mainnet.netlify.app/ on Desktop
2. Select Avalanche network as source chain 
3. Click "Connect wallet" button and select "Wallet Connect" option
4. Check that MetaMask wallet is successfully automatically connected in "From" section
5. Select AVAX asset and enter Amount 0.001
6. Select Fantom network as destination chain
7. Click "Connect wallet" button and select "Wallet Connect" option
8. Check that MetaMask wallet is successfully automatically connected in "To" section
9. Click "Approve and proceed with transaction" button
10. Unlock phone
11. Open MetaMask app and enter password
12. Check if confirmation notification appears
13. Click "Approve and proceed with transaction" button again
14. Check if confirmation notification appears

Actual result: Transaction fails with error. Confirmation notification does not appear on mobile. 

```
main.js:499 Error: No matching key. keychain: 7aafb8a96fa603d293c4c039508c848f4228dd9b7ad955c0a24805e7308601a8
    at Wu.get (index.es-lgqa_eUG.js:40:38388)
    at Yu.getSymKey (index.es-lgqa_eUG.js:40:41255)
    at Yu.encode (index.es-lgqa_eUG.js:40:40200)
    at qf.sendRequest (index.es-lgqa_eUG.js:40:96222)
    at index.es-lgqa_eUG.js:40:92025
    at new Promise (<anonymous>)
    at qf.request (index.es-lgqa_eUG.js:40:91992)
    at async gn.request (index.es-lgqa_eUG.js:40:115707)
    at async Ag.request (index.es-SHP5dhxA.js:27:15129)
    at async is.request (index.es-SHP5dhxA.js:27:27825)
```

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)
After adding new network the loading time on Step2 takes longer, but eventually a pop-up is shown on the mobile Metamask app to Confirm transaction and the transaction is completed
Closing the ticket.
Attachment:
<img width="765" alt="Screenshot 2024-05-22 at 11 08 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/50d629ee-806c-43ad-b139-d746396c8dc8">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f74e0789-9f20-49fc-8b40-fc8228318a16
