### ISSUE TITLE
[QA][Improvement] Wrapped Klay abbreviation should look the same everywhere it is used

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1628]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Actual result: For transactions **w**Klay abbreviation is used, but in Token list it is shown **W**KLAY

Improvement: Use the same abbreviation for Wrapped Klay asset [wKlay] both in the available token list and when transaction happens

Attachment:
For transaction that is completed:
![Screenshot 2024-02-09 at 15 29 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a0a975d-e41d-4168-ac36-cc67e7303361)

How it is shown in Available token list:
![Screenshot 2024-02-09 at 15 31 57](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f67b4ffa-60a3-49b9-be16-40a97588af20)
net

**Comment by tsadovska** [comment]
Issue is no longer reproducible. The same abbreviation for wrapped Klay is used on Bridge and Transaction screens. 

Checked on https://portalbridge.com/:
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


![image](https://github.com/user-attachments/assets/cdfc254c-ffd7-44b5-aaf1-87c745aded16)

![image](https://github.com/user-attachments/assets/52129235-005e-4203-92fc-7f5f49ebdf6f)


Closing the ticket.
