### ISSUE TITLE
[QA][Testnet] Cannot register assets for Sepolia networks

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1630]
Preconditions:
Metamask Wallet conencted

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Steps:
1. Prepare to send 0.001 USDC (Base Goerli) from Base Goerli to Base Sepolia
2. Observe that token needs to be registered
3. Click on [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) 
4. Select Base Goerli
5. Connect Metamask Wallet
6. Paste USDC asset contract address 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
7. Click Next
8. Open Network List
9. Search for Sepolia networks

Actual result: Only Ethereum 9Sepolia) is present in the list

Expected result: User is able to register asset for Sepolia transaction

Attachment:

![Screenshot 2024-02-12 at 10 45 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/87e9fcc4-70a9-4d7e-b0ae-f37dcd12a096)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-foundation.github.io/example-token-bridge-ui/#/register [Testnet]. Base Sepolia, Arbitrum Sepolia and Optimism Sepolia networks are not displayed in the list.

**Comment by AigaD** [comment]
Tested from: https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Sepolia/ Arbitrum Sepolia and Optimism Sepolia networks are not displayed in the network list.
Attachment:
<img width="838" alt="Screenshot 2024-05-21 at 12 17 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/159f2af0-136b-4f78-bc5b-6ed95f757bce">
