### ISSUE TITLE
[QA] USD equivalent is not shown for destination chain asset in Native gas section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1631]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 5 FTM from Fantom (Metamask) to Alfajores (Metamask)
2. Select "Automatic Bridge" route in Route section
3. Enable "Native gas" section
4. Check if USD equivalent is shown under CELO asset

![Screenshot 2024-02-12 at 10 59 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8244bfa8-39ac-4e9d-8718-0bdc70648ee8)

Note: Linked issue https://github.com/wormhole-foundation/wormhole-connect/issues/1436.

## What is the expected/desired behavior
USD equivalent "($0.00)" is shown under CELO.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
USD equivalent is not shown if the slider position on Native gas is at starting point, if user changes the slider the USD value is also shown
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cb3d0b31-4965-417f-a7f4-c03b301be0d6

**Comment by tsadovska** [comment]
USD equivalent is no longer displayed below the slider after redesign. 

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


![image](https://github.com/user-attachments/assets/7d8a695d-ee23-4b1f-be37-93287f714640)


Ticket is closed.
