### ISSUE TITLE
[QA] [Wormholescan] MetaMask notification does not appear after clicking on "Add to MetaMask" button 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1633]
## Describe the current behavior in detail
Steps:
1. Open https://wormhole-connect.netlify.app/ [Testnet]
2. Send 0.001 ETH from Goerli (MetaMask) to Sepolia (MetaMask)
3. Click on Wormholescan link when transaction is completed
4. Click on "Add to MetaMask" button

Error:
`Failed to switch chain in MetaMask {code: -32602, message: "Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received:\nundefined", stack: 'Error: Expected 0x-prefixed, unpadded, non-zero he…olgcge/scripts/background/background.js:18:15253)'}`

Notes:
* Link to Wormholescan: https://wormholescan.io/#/tx/0xb803e13a7e840d4ef9c1d0763d595910e52a1e1af8b767483fb5ca99973ef764?network=TESTNET
* Send from tx: https://goerli.etherscan.io/tx/0xb803e13a7e840d4ef9c1d0763d595910e52a1e1af8b767483fb5ca99973ef764
* Send to tx: https://sepolia.etherscan.io/tx/0xdf49322e16087086a4594210300869ab0e13e37feaf18e17af0ac0315bdda7b8 
* Checked with macOS and Google Chrome. 

![Screenshot 2024-02-12 at 12 02 38](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d0d46ea1-cc47-4435-a2f3-7fdf6402dc16)

## What is the expected/desired behavior
MetaMask notification opens and user can successfully add token to MetaMask.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#
Goerli network balance is no loading as the Goerli is being deprecated https://www.alchemy.com/blog/goerli-faucet-deprecation , but for transaction BSC to Moonbase Wormholescan "Add to Metamask" button allowed user to add the BNB token to Metamask wallet.
Closing the ticket.
Attachment:
Tested from: https://wormhole-connect-mainnet.netlify.app/#

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7817268e-851e-4745-9a62-5591977d2e53

Tested from: https://wormhole-connect.netlify.app/#

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c5085a11-8da6-4dcd-97c2-49c0e0dc560b
