### ISSUE TITLE
[QA] Balance is not loading in "To" section for wKLAY on Fantom

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1638]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome.

Preconditions: User has some wKLAY on Fantom

Steps:
1. Prepare to send 1 KLAY from Klaytn (MetaMask) to Fuji (MetaMask)
2. Change Fuji network to Fantom
3. Check if balance is loaded in "To" section

Actual result: Balance for wKLAY is not loading in "To" section. 

Error:
```
Error: Wormhole Circle relayer contract for domain klaytn not found
    at EthContracts.mustGetWormholeCircleRelayer (main.js:347:77745)
    at CCTPRelayRoute.getRelayerFee (main.js:524:16967)
    at CCTPRelayRoute.isRouteAvailable (main.js:524:13629)
    at Operator.isRouteAvailable (main.js:525:78443)
    at main.js:696:87575
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b3a6acc8-9fa3-4609-9bd8-46dc63202c38

## What is the expected/desired behavior
Balance for WKLAY asset is displayed.

**Comment by AigaD** [comment]
Closing the ticket.
Linking to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1897 Asset balance is not automatically loading at sending To section
Tested from: https://wormhole-connect.netlify.app/#
