### ISSUE TITLE
[QA]"Add <token> to your wallet" pop-up is not showing on mobile if network is switched

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1639]
Preconditions:
Metamask wallet app connected though WalletConnect

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://wormhole-connect.netlify.app/#
iPhone 14, iOS 16.0

Steps:
1. Prepare to send 1 AVAX from Fuji to Alfajores
2. Select Pay with automatic transaction in Route section
3. Click Approve and proceed with transaction
4. Wait until transaction is finished
5. Click on "Add <token> to your wallet"
6. Approve Network switch
7. Observe if mobile device shows pop-up to add token
8. Click on "Add <token> to your wallet" again

Actual result: If network switch is confirmed from mobile app the Add token pop-up is not shown after Network switch is completed, user has to click again on the Add token button

Expected result: Add token pop-up is shown after network is switched

Comments: After approximately 5min another pop-up to add the token is shown on the Metamask mobile app

Attachment:

Uploading IMG_4671.MOV…

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign. 
Closing the ticket.
