### ISSUE TITLE
[QA] [Mainnet] Source chain gas estimate in Preview section differs significantly from gas estimate on MetaMask notification

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1641]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.001 ETH from Ethereum (MetaMask) to Avalanche (MetaMask)
2. Check "Source chain gas estimate" amount in Preview section
3. Click "Approve and proceed with transaction" button
4. Check Gas estimate in Metamask wallet

Actual result:
* Source chain gas estimate on wormhole-connect is ~ 0.0003 ETH (~$0.75)
* Gas estimate in Metamask notification is 0.00323203 ($8.03)

![Screenshot 2024-02-12 at 15 28 49](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ca9006e2-0223-4df6-90bc-97ec0e83a022)

## What is the expected/desired behavior
Source chain gas estimate is similar to gas estimate in MetaMask notification.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 USDT from Ethereum (MetaMask) to Sui (Sui wallet). 
* "Source chain gas fee" on Bridge screen is 0.00015 ETH (~$0.46)
* "Gas fee" on Redeem screen is 0.003307 ETH (~$10.06)
* Send from tx: [Etherscan](https://etherscan.io/tx/0xa73168a33fa6a064a0227af744d6a063e55a12379f519e4f23dc1ce422f52595)
* Send to tx: [Sui Explorer](https://suiexplorer.com/txblock/AAUh3YNkAQSzSC7qfbxyphuG8ysrUe9dPN9but58taHW)

![Screenshot 2024-02-25 at 15 06 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4de45934-cf74-4989-b30d-9c97d160bd8d)


![Screenshot 2024-02-25 at 15 11 19](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/176ef810-8421-448f-b885-aa45f65dbb2b)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/894b0821-4781-4c3c-a4c7-5cea9df767fc)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7246284e5d/ [Mainnet] when sending 100 BONK from Solana (Phantom) to Ethereum (MetaMask). "Destination chain gas estimate" on Bridge screen is ~ 0.0003 ETH (~ $0.93), but "Gas estimate" on Redeem screen is ~ 0.007232 ETH (~ $22.33). 

![Screenshot 2024-02-26 at 10 14 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cdab4574-3266-4e89-aea7-45ae4c8b72e8)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/7246284e5d/ [Mainnet] when sending with tBTC route. Gas estimate on wormhole-connect shows 0.0003 ETH(~$0.94), but gas fee in MetaMask is $56.08. Sent 0.000001 tBTC from Optimism (MetaMask) to Ethereum (MetaMask). Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0xd4c71139251069e705464d584f7693fe4e1d23d2036dfd66bd39166822dd851c).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/34a1e5ec-9a9e-4d05-951e-92b9aa8b06e3)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending 0.000001 WBTC from Ethereum (MetaMask) to Fantom (MetaMask) with Manual Bridge (Wormhole) route. Gas estimate on https://preview.portalbridge.com/ is ~ 0.00015 ETH (~$0.59), but gas fee in MetaMask is ~$30. 


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f77cf06a-152b-4d64-80fd-6e36941739c1)

**Comment by aadam-10** [comment]
https://github.com/wormhole-foundation/wormhole-connect/pull/1764 will solve the issue for the ETH bridge route.

tickets for the other 2 routes:

- https://github.com/wormhole-foundation/wormhole-connect/issues/1766
- https://github.com/wormhole-foundation/wormhole-connect/issues/1765

**Comment by tsadovska** [comment]
Tested OK. Source chain gas estimate is similar to gas estimate in MetaMask notification when sending with "ETH Bridge" route. 

* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ee09eeb6-faa7-410c-bf67-54cf869bbf12)


* https://preview.portalbridge.com/b1ba6e856a/ [Mainnet]


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9810766e-e3de-4a8e-b26b-514bf87c14c9)
