### ISSUE TITLE
[QA] [Mainnet] Cannot change slider position when sending WBTC from Ethereum

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1642]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.000039 WBTC from Ethereum (MetaMask) to Celo (MetaMask)
2. Enable "Native gas" section
3. Change slider position

Actual result: Cannot change slider position. 

Notes:
* Issue is also reproducible when Fantom, Moonbeam or Polygon network is selected as destination chain. 
* Issue is not reproducible when user sends WBTC to BSC. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/70abd442-84d9-439d-9e5d-0f431261a1d9

## What is the expected/desired behavior
User can change slider position in "Native gas" section when sending WBTC from Ethereum or "Native gas" section is not available.

**Comment by tsadovska** [comment]
issue is reproducible on https://portalbridge.com/ [Mainnet] with the same scenario.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending 0.000028 WBTC from Ethereum (MetaMask) to Moonbeam (MetaMask). 

Steps:
1. Select Ethereum as source chain and Moonbeam as destination chain
2. Connect MetaMask wallets in From and To sections
3. Select WBTC (Ethereum) asset and enter Amount 0.000028
4. Enable "Native gas" section
5. Try to change slider position

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] (Portal Bridge: v0.2.13-Pfe79048439, Wormhole Connect: v0.3.8-beta.0-development) when sending 0.000028 WBTC from Ethereum (MetaMask) to Polygon (MetaMask).

**Comment by agodlevska** [comment]
Issue not reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) but still reproducible on https://portalbridge.com/. 

Attachment: 

https://github.com/user-attachments/assets/74ec0298-10d9-4c23-9e86-7fd08a83cd60

**Comment by tsadovska** [comment]
Issue is no longer reproducible.

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development



https://github.com/user-attachments/assets/8e33a0db-d69b-4510-95de-8465f36d018d


Ticket is closed.
