### ISSUE TITLE
[QA][Testnet] Base Sepolia asset balance is not completing the loading process 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1643]
Preconditions:
Metamask wallet connected 

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Connect to Base Sepolia
2. Open asset list
3. Observe if asset balances are loaded

Actual result: ETH for Base Sepolia is loaded, but the rest of tokens are still in loading status

Expected result: Assets with balance are loaded and left visible in the Available token list

Attachment:

![Screenshot 2024-02-12 at 16 04 43](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6ec2c4aa-808f-4012-9067-8a3efc7e064a)

**Comment by tsadovska** [comment]
Loading icons are no longer displayed.
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2431.

![image](https://github.com/user-attachments/assets/fef0c9a2-ba73-4077-b886-6880ce236877)


Closing the ticket.
