### ISSUE TITLE
[QA][Testnet] Optimism Sepolia balance is not loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1644]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Connect to Optimism Sepolia
2. Open asset list
3. Observe if asset balances are loaded

Actual result: Balance for Optimism Sepolia is not loading, console shows: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'error')`

Expected result: Assets with balance are loaded 

Attachment:

![Screenshot 2024-02-12 at 16 52 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2948b52a-3de0-4c3c-9b2b-11d489511c58)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/#
Optimism Sepolia balances are not loading

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4314169d-43d3-4c45-8f78-6dc5eec8c3e1

**Comment by agodlevska** [comment]
Still reproducible on https://wormhole-connect.netlify.app/.
Optimism Sepolia balances are not loading.

```
Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'error')
    at main-Cubx2sfv.js:345:157717
    at Array.forEach (<anonymous>)
    at fetchJson.then.emit.action (main-Cubx2sfv.js:345:157677)
``` 

Attachment:
<img width="1393" alt="Screenshot 2024-06-28 at 11 33 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/db24021c-eedc-4482-9832-1083e04817a4">

**Comment by tsadovska** [comment]
Re-checked the issue on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2). ETH balance is loading on Optimism Sepolia. 

![Screenshot 2024-08-22 at 15 41 37](https://github.com/user-attachments/assets/1c8d5312-b3ab-452a-86e4-50d8a6996841)

Remaining issue: Corresponding asset is not displayed in "To" section when sending CELO from Alfajores (MetaMask) to Optimism Sepolia (MetaMask). Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2365.

Closing the ticket.
