### ISSUE TITLE
Add support for Polygon USDC.e

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1648]
## Description and context
Connect only supports sending native USDC on Polygon ([Polygonscan](https://polygonscan.com/token/0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359)).

Polygon also has an older bridged version of USDC (called USDC.e, [Polygonscan](https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174)) from before native USDC issuance. There is ~330M circulating of USDC.e and ~125M of USDC on Polygon. Only supporting USDC creates a problem when certain ecosystems expect the more widely circulating USDC to be bridged in.

This task is to add support for bridging USDC.e from Polygon to other chains.

## Definition of done
Connect can be configured to allow bridging USDC.e from Polygon to other chains.

When USDC.e from Polygon is bridged to Sui, the user should end up with https://suivision.xyz/package/0xcf72ec52c0f8ddead746252481fb44ff6e8485a39b803825bde6b00d77cdb0bb

**Comment by tonyjin** [comment]
This also requires token bridge relayer support for Polygon USDC.e cc @mliu-xlabs

**Comment by tonyjin** [comment]
Update - because of https://github.com/wormhole-foundation/wormhole-connect/issues/1287, this issue no longer needs to be implemented at the Connect level.

Instead, integrating apps (e.g. Portal) can configure Connect to support USDC.e on Polygon.

**Comment by mliu-xlabs** [comment]
https://github.com/orgs/XLabs/projects/2/views/9?sliceBy%5Bvalue%5D=Iteration+6&pane=issue&itemId=54475873
