### ISSUE TITLE
[QA] [Testnet] Transactions to/ from Solana fails 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1650]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS.

Scenario 1:
1. Prepare to send 0.001 SOL from Solana (Phantom) to Fuji (MetaMask)
2. Click "Approve and proceed with transaction" button

Error:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 51FuCdHKuTSLtpRG496dLZffyYowCfweVAU27xwW25veAc3BjvMiiNFYYMfZz9DE7kKNfQk3RfygBjtG1ZsaWrKt using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61281)
    at async Connection$1.confirmTransaction (main.js:171:56723)
    at async SolanaWallet.sendTransaction (main.js:517:300118)
    at async signSolanaTransaction (main.js:519:19328)
    at async signAndSendTransaction (main.js:519:20770)
    at async BridgeRoute.send (main.js:523:22484)
    at async Operator.send (main.js:525:80482)
    at async Object.gr [as onClick] (main.js:696:101813)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2130d430-6a08-4e35-a02b-96b49376d6b5)

Scenario 2:
1. Prepare to send 9,991 AVAX from Fuji (MetaMask) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button

Actual result: Loading doesn't complete. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6f4f17d6-a2a7-421b-9d1d-783fa5e1eff5)

## What is the expected/desired behavior
User can successfully send assets to/ from Solana.

**Comment by tsadovska** [comment]
Tested OK:
* Checked that Manual Bridge transactions to Solana are successful
  * Send CELO from Alfajores (MetaMask) to Solana (Phantom): (Send from tx: [Celo explorer](https://explorer.celo.org/alfajores/tx/0x08f453a23f00f35f06eeaff6402a0f6bf1b4768a8d338d9d679a2af35b0ead2f), Send to tx: [Solana Explorer](https://explorer.solana.com/tx/3QAvYV2gPLqYPVAPzf156oNV14ykuLsBVobeWcj7wZKx2g7GxbWEVszBbCwqBaLE7XxqangQymD3ATufuo4eQcNN?cluster=devnet))
  * Send MATIC from Mumbai (Metamask) to Solana (Phantom): (Send from tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x87044b1b4853dda2f0062200c615b47469fab38b5715f1e726178d1af4441c64), Send to tx: [Solana explorer](https://explorer.solana.com/tx/3XineqxiJXZaZjRk3E4APA2m7BHwQFBV2HHLXF1wQJ5sKnTuoAvSdJk5JVCZezoEvbJqJspm9noovZeucgazfacJ?cluster=devnet))
* Check that Automatic Bridge transactions to Solana are successful
  * Send FTM from Fantom (MetaMask) to Solana (Phantom): (Send from tx: [FtmScan](https://testnet.ftmscan.com/tx/0x24b56da8d962ce822a76a523fd46d92b284f36f891c8488c8b3d7cc1f3fb9106), Send to tx: [Solana explorer](https://explorer.solana.com/tx/2KBoBhwgoU1qSjVudtrpsAcufV5evhJKjs5XzmCwwg1ESGvrbfH9A5EGXqoKqayvsFKKdk5q79NzUpv4Cg35MydR?cluster=devnet))
  * Send AVAX from Fuji (MetaMask) to Solana (Phantom): (Send from tx: [Avascan](https://testnet.avascan.info/blockchain/c/tx/0xc5aae596765ee8a0e034dc2b08564e87641f9a45dcefe3a0a86c1f19d924b151), Send to tx: [Solana explorer](https://explorer.solana.com/tx/3vkDDMMQWbQLgopvw33yD5BPbu92mD6HEn55hMMiVZkS5Q4mMaeoMdy6ehQgQFgskbNN14zg4KD6bEAos2gNN1ft?cluster=devnet))
 
 Tested NOK:
 * Transaction from Solana is stuck on "Waiting for Wormhole network consensus . . ." step
 * Transaction is displayed with incorrect Timestamp on Solana Explorer, https://github.com/wormhole-foundation/wormhole-connect/issues/1656

**Comment by tsadovska** [comment]
Tested OK:
* Manual Bridge route from Solana (Send from tx: [Solana Explorer](https://explorer.solana.com/tx/27ALb9ck3fiSP5NoGjydceNJALBSMb4RzVsFEwXXxafptqLximXt6wBKhkiUJqELNNSgzpBPnGJqW26VaZgGY54d?cluster=devnet), Send to tx: [FtmScan](https://testnet.ftmscan.com/tx/0x1c7efba97d0b2060fdfa04f8233de6155697bba255e7a91f52c5333dc422a143))
* Automatic Bridge route from Solana (Send from tx: [Solana Explorer](https://explorer.solana.com/tx/5r6jRdMBifhwsQKhXKPUFW3X3DtiAhAwnJeuKUm2gRx84RnhNZST1diNqm43kHKzqjzr79SpVPdp23MFBXjAyQMy?cluster=devnet), Send to tx: [FtmScan](https://testnet.ftmscan.com/tx/0x92003a20b9f83988e234258b98594f5628dcbc668aacf4187c4e2ca3a0b735a4))
* Manual Bridge route to Solana (Send from tx: [Avascan](https://testnet.avascan.info/blockchain/c/tx/0xf46e66db9e001e9ffac6afc8550efe8d77f22b0a8de4c9c38b2309fac66b280b), Send to tx: [Solana Explorer](https://explorer.solana.com/tx/5aw31L2Nnv7G71HSs6Dr7uUKUfRYjunWqrpS6QVHQEv4zXkvknNFiphCgBs5kTE49ecSBDCdfJDgjwd5BGJ9VYBd?cluster=devnet))
* Automatic Bridge to Solana (Send from tx: [Moonscan](https://moonbase.moonscan.io/tx/0x55201ef1174139080a03ad7da809f6300c07a36caec45c53b6b54dee9104a822), Send to tx: [Solana Explorer](https://explorer.solana.com/tx/3zgXHuEvDQdVdx2MdeYiHy1QiD8KFdhfPPx5WamkJnzb51j5HSZwXkoYn1GU1e33ei1xsjaEDfhxLy9RGheuBEHj?cluster=devnet))

Ticket is closed.

**Comment by agodlevska** [comment]
Reopening the ticket. 
Reproducible on https://wormhole-connect.netlify.app/. 

Sending 0.2 GLMR from Moonbase (Rabby) to Solana (Phantom). 
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 3bbZ3f9a3SAEipgve4pJnwSwRMt1Bz862Y5kTaAfKveE2AGsRaVz2YCxiGHXXekBoBpa89c7kgJoqj28emCe2D7b using the Solana Explorer or CLI tools.
    at wc.confirmTransactionUsingLegacyTimeoutStrategy (index.browser.esm-BbJzvgvx.js:7:40043)
    at async wc.confirmTransaction (index.browser.esm-BbJzvgvx.js:7:36009)
    at async A.sendTransaction (solana-BFUnTRO_.js:2:42141)
    at async ae (solana-BFUnTRO_.js:2:50603)
    at async signAndSendTransaction (main-DpR6Nu3N.js:260:158466)
    at async SDKv2Signer.signAndSend (main-DpR6Nu3N.js:265:14319)
    at async ssw (main-DpR6Nu3N.js:260:7735)
    at async signSendWait (main-DpR6Nu3N.js:260:7475)
    at async TokenBridgeRoute.complete (main-DpR6Nu3N.js:260:45600)
    at async Object.Ut [as onClick] (main-DpR6Nu3N.js:298:1360)
``` 
```
Failed to calculate compute unit limit for Solana transaction: TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
``` 
Attachment:
<img width="1440" alt="Screenshot 2024-07-09 at 17 30 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/0eaa1f79-3f9d-46c6-bb5d-e26c76faa15c">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 
* Send from tx: [Moonscan](https://moonbase.moonscan.io/tx/0x3e1470d528d64b61bd69760e8232a2af8dca077e3174a0d4e325ec21102245d7)
* Send to tx: [Solana explorer](https://explorer.solana.com/tx/3JDYXsxktAGL5hM4DswjwzunXm7QeyCEw1f3qzksHuQT3NESLs5MdkiuG1ZPxEPViWPg7Z1hFrUM7eC3Wo3HzsuF?cluster=devnet)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x3e1470d528d64b61bd69760e8232a2af8dca077e3174a0d4e325ec21102245d7?network=TESTNET)

![image](https://github.com/user-attachments/assets/7fb7f680-eaeb-4b4c-8b86-bda9d8aee69d)


Ticket is closed.
