### ISSUE TITLE
[bug] - wormhole connect deep linking not working

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1663]
When portal mounts wormhole connect with search tx information, the search is not getting triggered.

### Acceptance Criteria

Given an user with a deep link with a **sourceChain as string (for instance: solana)** and a **txHash** valid
When use it at the browser (paste it to the address input)
And hit enter key
Then user got redirected to the search screen
And automatically the search button get fired 

Given an user with a deep link with a **sourceChain as string (for instance: solana)** and a **transactionId** valid
When use it at the browser (paste it to the address input)
And hit enter key
Then user got redirected to the search screen
And automatically the search button get fired

Given an user with a deep link with a **sourceChain as number  (for instance: 1)** and a txHash valid
When use it at the browser (paste it to the address input)
And hit enter key
Then user got redirected to the search screen
And automatically the search button get fired

Given an user with a deep link with a **sourceChain as number  (for instance: 1)** and a transactionId valid
When use it at the browser (paste it to the address input)
And hit enter key
Then user got redirected to the search screen
And automatically the search button get fired

Given an user with a deep link with a sourceChain as number or string and an transactionId invalid
When use it at the browser (paste it to the address input)
And hit enter key
Then user got redirected to the search screen
And automatically the search button get fired
And the search screen shows the current error message for invalid tx hash

Given an user with a deep link with a sourceChain as number or string invalid
When use it at the browser (paste it to the address input)
And hit enter key
Then the user keeps on main screen
And non error got triggered

## Sample DeepLinks

https://preview.portalbridge.com/caab316c7d/?sourceChain=sui&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r

https://preview.portalbridge.com/caab316c7d/?sourceChain=suin&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r

https://preview.portalbridge.com/caab316c7d/?sourceChain=sui&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r2

https://preview.portalbridge.com/caab316c7d/?sourceChain=21&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r

https://preview.portalbridge.com/caab316c7d/?sourceChain=2221&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r

https://preview.portalbridge.com/caab316c7d/?sourceChain=21&txHash=CbXtcUMGoUA5w9PvsFHPNoK6r1iicam8rKjJT7sw5q7r2

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/7246284e5d/
Testing results can be viewed [here](https://docs.google.com/spreadsheets/d/128zHVbllDoayKv9srzk9tIZSlYiIuCYmGKYNqQH16zk/edit#gid=623464453)
For reference from todays check deeplink with address input https://preview.portalbridge.com/7246284e5d/?sourceChain=polygon&transactionId=0x0e0a488ac1561ccc82222f816029607c269ec3e7454084ca923e87414bcfde66 Tested OK
