### ISSUE TITLE
[QA] [Testnet] Cannot connect OKX Wallet when Osmosis/ Cosmoshub/ Kujira network is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1667]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

1) Error when user selects Osmosis network and then connects OKX Wallet:
`Uncaught (in promise) {code: -32603, message: 'There is no chain info for osmo-test-5', data: {…}}`

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88bae8b7-7092-4a22-890b-2f1ef3efed36)

2) Error when user selects Cosmoshub network and then connects OKX Wallet:
```
Uncaught (in promise) Error: No chain info found for theta-testnet-001
    at CosmosWallet.addChain (main.js:399:94142)
    at CosmosWallet.connect (main.js:399:93438)
    at async dr (main.js:799:91935)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/df3e8297-da9e-4e84-8fb4-df6fa8f55fab)

3) Error when user selects Kujira network and then connects OKX Wallet:
`Uncaught (in promise) {code: -32603, message: 'There is no chain info for harpoon-4', data: {…}} `

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b38b39df-13e1-4b68-a67b-a146878f3e1f)

Note: 
* User can connect OKX Wallet on https://wormhole-connect-mainnet.netlify.app/ when Osmosis or Kujira network is selected. 
* OKX Wallet is not shown in the list when Evmos network is selected. 

## What is the expected/desired behavior
User can connect OKX Wallet or wallet is not displayed in the list.

**Comment by AigaD** [comment]
Tested from: [Testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk%2BQhBTDJKGfMXKBYNXJg6CEAL4hTQA%3D#)
Issue is still reproducible, cannot connect OKX wallet when Osmosis network is selected, `'There is no chain info for osmo-test-5'`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8fc21a5-1393-4deb-ba19-ce82568cc1dd
