### ISSUE TITLE
[QA] [Nightly] Transaction from/ to Aptos fails

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1672]
## Describe the current behavior in detail
Builds - Tested NOK:
https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
https://preview.portalbridge.com/749d45da9e/ [Mainnet]

Checked on macOS and Google Chrome.

Steps:
1. Prepare to send 0.001 APT from Aptos (Nightly) to Arbitrum (Metamask) 
2. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.

```
Error: Waiting for transaction 0x30b4fadad439e28427ec135ae9a5ca8bdbf3f2e12475e4de36465571215e814f failed
    at _AptosClient.waitForTransactionWithResult (main.js:166:20454)
    at async _AptosClient.waitForTransaction (main.js:166:20802)
    at async signAndSendTransaction (main.js:519:20942)
    at async BridgeRoute.send (main.js:523:22484)
    at async Operator.send (main.js:525:80482)
    at async Object.gr [as onClick] (main.js:696:101847)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/17dec4d4-6f78-492c-a18b-36e9a377cd68)

Notes:
* Issue is also reproducible when sending 0.001 APT from Aptos (Nightly) to Avalanche (MetaMask).
* Issue is not reproducible when sending 0.001 APT from Aptos (Spika) to Arbitrum (Metamask) 

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by tsadovska** [comment]
Transaction to Aptos (Nightly) fails with error:
```
Error: Waiting for transaction 0x0dcf62144968de0be1699dd8c1d4af3cf00e4188fe55588a36d5df39914de3b7 failed
    at _AptosClient.waitForTransactionWithResult (main.js:166:20448)
    at async _AptosClient.waitForTransaction (main.js:166:20796)
    at async signAndSendTransaction (aptos-ULIyiTpW.js:34:306160)
    at async signAndSendTransaction (main.js:322:771115)
    at async BridgeRoute.redeem (main.js:326:22702)
    at async Operator.redeem (main.js:328:79566)
    at async Object.jn [as onClick] (main.js:500:1087)
```
Send from tx: [Sui explorer](https://suiexplorer.com/txblock/8iaavV74CU17cHPcDG7cA2oL9YUwbraVqezfYj1X213n)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c2045f44-bf34-4d15-9175-ffcfc3b6fe4c)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Claiming at Aptos fails
Transaction from Polygon (Rabby) to Aptos (Nightly) failed at Claim
Transaction [BSC ](https://bscscan.com/tx/0xb4b878c5bb19ea8a5dbfb39e181a31efb82a1d948404797981a96fa07d610f1f)(Rabby) to Aptos (Nightly) failed at Claim
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a35e7d3-8788-47e2-8ebd-0aa67a379267

![Screenshot 2024-03-06 at 08 36 45](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7dfb6167-fe1e-48fe-86bd-71efc60a3782)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/ and https://wormhole-connect-mainnet.netlify.app/#
User is not able to connect to Nightly wallet. Issue reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/1821
Ticket will be re-checked after mentioned issue is resolved

**Comment by tsadovska** [comment]
Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1821.
