### ISSUE TITLE
[QA] [Testnet] [Circle CCTP] Cannot claim USDC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1678]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.001 USDC from Mumbai (MetaMask) to Arbitrum Goerli (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button
4. Check if transaction is completed

Actual result: Transaction fails after clicking on "Claim" button. Send from tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x88e5dbd45ea4bf9f8d12ab85e3ca018e8368e3a2ba9af764249caa68c4c1822b).

Error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x109bC137cb64eAb7c0B1ddDd1Edf341467dC2D35","data":"0x57ecfd280000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000f800000000000000070000000300000000000004020000000000000000000000009f3b8679c73c2fef8b59b4f3444d4e156fb70aa50000000000000000000000009f3b8679c73c2fef8b59b4f3444d4e156fb70aa50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009999f7fea5938fd3b1e26a12c3f2fb024e194f970000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc18500000000000000000000000000000000000000000000000000000000000003e80000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc185000000000000000000000000000000000000000000000000000000000000000000000000000000821b5a0950749a9602496ec74bd97828d20787d847761a803d5c25bfc6efc67bc469d156bf2dcc9bef0041e6b15ffd3604038d97a4674c4b80f232fe1649ea02e21c577076ace68be402daf7519c5cc031a539e8bc10357d6482bf1e0089f7cb62770c7cdd509b6ce4e18b277803dc52d7d34b4d6c537a11fa597db2a6907ad258391c000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at checkError$1 (main.js:172:114180)
    at Web3Provider.<anonymous> (main.js:172:124788)
    at Generator.throw (<anonymous>)
    at mn (main.js:172:113201)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1e35ab94-78f3-4014-bce6-7cfebd5209b5)

Note: Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] (Send from tx: [Polygonscan](https://polygonscan.com/tx/0x82b55e39e9fb690351435b37bc271abaeb2d8d0f6c493d9633e076987e9d940e), Send to tx: [Arbiscan](https://arbiscan.io/tx/0x7d3245f5b081b563c1b0d4cdea37d9ac9fd449aacfdeca5174f2e7efc7d407ee))

## What is the expected/desired behavior
Transaction was successfully completed.

**Comment by agodlevska** [comment]
The bug is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Sending 0.01 USDC from [Sepolia](https://sepolia.etherscan.io/tx/0x26ab9c4ed2a520cf82bbae1e9056a79b0bb200a4e2318539a973524c38688b97) (MetaMask) to [Arbitrum Sepolia](https://sepolia.arbiscan.io/tx/0x8c40e82e84afb8d7985e0bc17fef42797e47aae740603ceda71bf6e8381fc67e) (MetaMask), [Wormholescan](https://wormholescan.io/#/tx/0x26ab9c4ed2a520cf82bbae1e9056a79b0bb200a4e2318539a973524c38688b97?network=TESTNET).
Closing the ticket.

Attachment:
<img width="1439" alt="Screenshot 2024-07-23 at 10 14 22" src="https://github.com/user-attachments/assets/37a12333-9501-4a42-8e6d-db5ea3e795fa">
