### ISSUE TITLE
[QA] [Mainnet] Transactions from Kujira and Osmosis fails with "RPC not found" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1680]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 CELO from Kujira (Leap) to Osmosis (Leap)
2. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.

```
Error: RPC not found
    at xP.getAccount (cosmos-R02QmrCi.js:112:136532)
    at xP.signTransaction (cosmos-R02QmrCi.js:112:137234)
    at async xP.signAndSendTransaction (cosmos-R02QmrCi.js:112:137796)
    at async qO (cosmos-R02QmrCi.js:112:138492)
    at async signAndSendTransaction (main.js:322:776325)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101845)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b9b0d14-3f1a-424e-8bc4-f97472d22a02)

Issue is also reproducible when:
* Sending 0.0001 CELO from Kujira (Leap) to Fantom (MetaMask)
* Sending 0.0001 CELO from Osmosis (Leap) to Fantom (MetaMask)

Issue is not reproducible when sending 0.0001 CELO from Evmos (Leap) to Fantom (MetaMask): Send from tx: [MintScan](https://www.mintscan.io/evmos/tx/E308B53C2CC5BD008A9EE729A2D90ECB4A0173B4581FFCE2B0905C1187961E62), Send to tx: [FTMscan](https://ftmscan.com/tx/0x46a3eba0d438a977ba68d793e75d0ccc6f7c3a58db403b00a072dfbc28519847)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from Kujira to Moonbeam fails, with reason `Error: RPC not found`
Attachment:
<img width="1309" alt="Screenshot 2024-02-20 at 17 17 50" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/10566bae-7ca8-4e9b-af3d-c78910feb90d">

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/7246284e5d/
Failing to send WGLMR asset from Kujira (Leap) to Fantom (Metamask)
And Failing to send 0.001 USDC (Polygon) from Osmosis (Leap) to Fantom (Metamask)

![Screenshot 2024-02-23 at 09 28 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c1b05ab6-bab0-449c-965c-3844d5c04c76)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a5b0842-260e-40ad-a8f9-19dd84d51f62

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://portalbridge.com/#
Transaction from [Osmosis](https://www.mintscan.io/osmosis/transactions/461D579B3E03454AEDCF1F8B4EE31FB0C1F950ABDB934835E4C49E355CA62F79) to [Solana](https://explorer.solana.com/tx/5Boqg9GEnUeJQEEVt61XUb6Kt4nbuW3QA8RMjFni2eXXzaGRjrYt5pd3coRCd5TazSJz6M8MpNgXDbXCPhkdAdLd) was completed

Tested from: https://aurora.dev/
Transaction from [Kujira](https://finder.kujira.network/kaiyo-1/tx/F681F3EDC7285745451ACB84082207D82A7A2EC30EE816C8DC269C28FC43F3F5) (Leap) to [Fantom](https://ftmscan.com/tx/0x0dfd0711ce7f3985f5a9d430ec6713822646701a6f100ac2ebf5eb77e34edf5e) (Metamask) was completed

Attachment:

![Screenshot 2024-03-05 at 10 57 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/25b21dac-7cef-4f6a-ac4e-b6da2ff4d333)


![Screenshot 2024-03-05 at 11 24 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/145046f4-62cf-4493-93d2-c479501b5e5b)

Closing the ticket
