### ISSUE TITLE
Disable inflows into Evmos via the Connect UI

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1681]
## Description and context
The UI should be updated to disallow transferring tokens into Evmos due to the large number of issues experienced. Users should still be able to transfer assets out of the network.

This is a UI change only, specific to Connect and by extension, Portal. The IBC connection and other frontends will be unaffected.

- The Evmos UI element should be removed from the list of available networks, if the list is opened from the "to" (destination) section.
- The UI element should be there if the list is opened from the "from" (origin) section
- Remove the ability to flip the origin and destination chain with the middle button if the origin chain is evmos

## Definition of done
- User is unable to use Connect to transfer tokens into Evmos
- User is able to transfer tokens out of Evmos

**Comment by artursapek** [comment]
@aadam-10 - instead of greying out evmos, it's easier to just not have it in the chains list at all. is that cool?

**Comment by aadam-10** [comment]
@artursapek yes ty

**Comment by tsadovska** [comment]
Checked on https://portalbridge.com/ [Mainnet]. 

Tested OK:
* Evmos network is not shown in "To" section when network is not selected in "From" section
* Evmos network is not shown in "To" section when network is selected in "From" section
* Evmos network can be selected in "From" section
* "Switch" button is disabled when Evmos network is selected in "From" section 
* User can make transfers from Evmos network:
  *  CELO transfer from Evmos -> Avalanche: [MintScan](https://www.mintscan.io/evmos/tx/0DAC6A1D02E05758963B23BF6A506B371A598B7A8593383BD26FDBC20D6CA630), [Avascan](https://avascan.info/blockchain/c/tx/0xd912392a8780432a825cbdb1e9f683957ea2faf99d2ffc9ec4b8d5d5d86962df)
  * WGLMR transfer from Evmos -> Osmosis: [Evmos](https://www.mintscan.io/evmos/tx/ECC97DFE65A4FF4879DA3E7D484EE3B63C913B117CA61D90574AB49B25BEAD4C), [Osmosis](https://www.mintscan.io/osmosis/transactions/5E640E2ED4A4C966CEECCF13E5CA1AF8EA57A1E53DBBD4F5AE596B16FBCCEF7F)
* Transactions from Evmos can be successfully resumed through Menu > Resume transaction
