### ISSUE TITLE
[QA][Mainnet, Testnet]Fin wallet pop-up is opened instead of Metamask when connecting wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1684]
Preconditions:
Metamask extension enabled
Fin extension enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK
https://wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Connect any Ethereum Network (during test Base was connected)
2. Click on Connect Wallet
3. Select Metamask
4. Observe

Actual result: Instead of Metamask wallet, Fin wallet pop-up is shown

Expected result: Metamask wallet is opened

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49d043c6-f6ef-4a12-aa4e-35391670a1cb

**Comment by Eiei070922** [comment]
I'm sorry, can anyone help me? I need some advice. I'm just starting to
learn how to play with crypto and transactions on the blockchain. Will my
assets be confiscated? I'm not very good at English. I don't understand the
words. I'm trying to learn the vocabulary but I'm still confused

ในวันที่ จ. 19 ก.พ. 2024 20:38 AigaD ***@***.***> เขียนว่า:

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
No longer reproduced. When clicking on Metamask wallet Metamask wallet is connected.
Closing the ticket
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8433230-e1b7-4d1f-b751-337a39e7b106
