### ISSUE TITLE
[QA] [Mainnet] [ETH Bridge, wstETH Bridge] Header does not match the route 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1685]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.001 ETH from Ethereum (MetaMask) to Avalanche (MetaMask)
2. Check Route section

Actual result: Header does not match the route.

![Screenshot 2024-02-19 at 16 17 49](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e02ce70e-bef5-4ee4-8814-026c9993644e)

## What is the expected/desired behavior
The same route is displayed in Route option and header.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] with wstETH Bridge route. 


![Screenshot 2024-03-08 at 11 10 18](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f385b3f9-f896-4ed7-b4e5-8ae87cdf75dc)

**Comment by tsadovska** [comment]
Reproducible from https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with ETH Bridge and wstETH Bridge.

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
For wstETH bridge incorrect information about provider is shown in Route section
Attachment:
<img width="1025" alt="Screenshot 2024-03-27 at 11 43 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f3115e4c-9c9e-41a3-823a-5523a7d2d194">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#

Attachment:
<img width="683" alt="Screenshot 2024-04-02 at 15 31 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/60e4cf41-9fff-44a9-a6e9-8d2a7b640873">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/
<img width="1034" alt="Screenshot 2024-05-17 at 08 56 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49f0cf9f-cefc-4ccc-b087-6653c3080603">
Both for ETH and wstETH route header does not match the route naming
Attachment:

<img width="722" alt="Screenshot 2024-05-17 at 08 57 13" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/04fdf7c1-6b73-47ab-b1d6-66ba196c51ff">

**Comment by agodlevska** [comment]
Reproduced on: https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/
Both for ETH and wstETH route header does not match the route naming.

Attachment: 
<img width="1440" alt="Screenshot 2024-05-30 at 13 23 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/dd66a7f2-41d7-40c8-81ae-b3bf7cab0287">

**Comment by agodlevska** [comment]
Reproduced on: https://preview.portalbridge.com/954c469c33/
Both for ETH and wstETH route header does not match the route naming.

Attachment:
<img width="731" alt="Screenshot 2024-06-25 at 16 32 22 1" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/eb501611-5e2c-41f8-8ed0-65b079b68c7e">

**Comment by agodlevska** [comment]
The bug is no longer reproducible on https://portalbridge.com/ as the message indicating by who route is provided no longer present. 

The bug is still reproducible on https://wormhole-connect-mainnet.netlify.app/. 

Attachments: 
Portal Bridge:
<img width="607" alt="Screenshot 2024-07-04 at 14 00 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/0d97f629-709a-4117-b884-95037f57552d">

Wormhole Connect:
<img width="621" alt="Screenshot 2024-07-04 at 14 03 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/7bac7ba8-8e8d-4e9c-937a-4b4112515beb">

**Comment by agodlevska** [comment]
The bug is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/cb3fd769-2703-4ec9-b47d-45e2f1cded6f
