### ISSUE TITLE
[QA][Testnet] Failing to start a transaction from Base Goerli

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1686]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested OK

Steps:
1. Prepare to send 0.001 USDC (Base Goerli) from Base Goerli to any network (e.g. Fantom)
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction is not starting and then fails, reason `Error: missing revert data in call exception; Transaction reverted without a reason string `

Expected result: Transaction is started and completes

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/518d8ec4-dee8-47ec-9ad3-2e606dab45db

<img width="1367" alt="Screenshot 2024-02-19 at 17 30 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/52755d3d-08cb-4951-85a8-2d6974b74c35">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
When sending 0.001 USDC (Base Goerli) from Base Goerli (Metamask) to Solana (Phantom) transaction is not starting, console shows error `Error: Token not supported for relay at EthContext.getRelayerFee`
Attachment:

![Screenshot 2024-02-29 at 09 05 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c99f1b16-7787-4897-9ff8-07c5ffff6490)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Failings to start transaction APT from Base Goerli to Aptos (Rise wallet) `Error: network does not support ENS`
Attachment:

![Screenshot 2024-03-04 at 14 37 54](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/274b9c66-0b2a-45ab-9d92-a7c7aecffa90)

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1613

**Comment by tsadovska** [comment]
Base Goerli balance is not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
