### ISSUE TITLE
[QA] [Mainnet] Transactions from Evmos fails with "Unsupported type" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1688]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.0001 APT from Evmos (Leap) to Kujira (Leap)
2. Click "Approve and proceed with transaction" button

Actual: Transaction fails.

```
Error: Unsupported type: '/ethermint.types.v1.EthAccount'
    at or.accountFromAny [as accountParser] (main.js:319:1617039)
    at or.getAccount (main.js:322:107098)
    at async or.getSequence (main.js:322:107237)
    at async or.sign (main.js:322:114921)
    at async bu.signTransaction (cosmos-R02QmrCi.js:27:776774)
    at async bu.signAndSendTransaction (cosmos-R02QmrCi.js:27:777067)
    at async qO (cosmos-R02QmrCi.js:112:138492)
    at async signAndSendTransaction (main.js:322:776325)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101845)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1e1157b2-9422-41a3-a072-1b2042d25642)

Issue is also reproducible with following scenarios:
* Send 0.0001 CELO from Evmos (Leap) to Kujira (Leap)
* Send 0.0001 CELO from Evmos (Leap) to Osmosis (Leap)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7246284e5d/
Transaction 0.01 USDC (Polygon) from Evmos (Leap) to Solana (Phantom) fails with reason `Error: Unsupported type: '/ethermint.types.v1.EthAccount'`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a3a61f63-12bf-4b57-97aa-a9b7dbfecc0f

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Transaction 0.001 WFTM from Evmos (Leap) to Kujira (Leap) fails with reason `TypeError: Failed to fetch`

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae921aeb-fe0d-4f83-a826-beb9ed834d4a

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/
Transaction 0.0001 APT from [Evmos](https://www.mintscan.io/evmos/tx/224EAF90CA8F6F8782A9B75DB570A079013F43A340B9D1C99A4EC132782A70EC) (Leap) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/305F3EFC2E7B9EF39363D289C9E22589BB54B78C9EC678B13E4A2B5559866EE4) (Leap) was completed
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 USDC (Polygon) from [Evmos](https://www.mintscan.io/evmos/tx/50A60088B53C79DC820DB24BC1405A69F6A36930CCDB1D2FBC070D619442C5D4) (Leap) to [Solana](https://explorer.solana.com/tx/2gMjbAWvUrjm7UpxZpD8hE4E9Wt2Ee2uEJ3eJZF6HDp9TRCQnMLoZpLTSPZCda4d3BmBas3m4sChJ3gyxqE2sjWM) (Phantom) was completed
Closing the ticket.
Attachment:
<img width="901" alt="Screenshot 2024-03-27 at 09 18 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d851614-b9d7-413c-a59b-d363af0ca952">
<img width="1027" alt="Screenshot 2024-03-27 at 09 23 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d32aa8aa-e8a7-4b90-999a-5ec4da8421f6">

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending USDC (Solana) from Evmos (Keplr) to Kujira (Keplr)

```
Error: Unsupported type: '/ethermint.types.v1.EthAccount'
    at Oo.accountFromAny [as accountParser] (pb-index-Bn_4pseu.js:487:1626035)
    at Oo.getAccount (pb-index-Bn_4pseu.js:490:107172)
    at async Oo.getSequence (pb-index-Bn_4pseu.js:490:107311)
    at async Oo.sign (pb-index-Bn_4pseu.js:490:114999)
    at async tr.signTransaction (cosmos-ySs4DZjY-DMrgS7G2.js:27:776760)
    at async tr.signAndSendTransaction (cosmos-ySs4DZjY-DMrgS7G2.js:27:777053)
    at async pk (cosmos-ySs4DZjY-DMrgS7G2.js:112:138624)
    at async signAndSendTransaction (pb-index-Bn_4pseu.js:490:777337)
    at async Operator.send (pb-index-Bn_4pseu.js:495:127455)
    at async Object.ko [as onClick] (pb-index-Bn_4pseu.js:717:27642)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c9a57d8d-268d-406c-9da7-f2207a6cd419)

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJJFgoR3QsQi4Rk3DPmK5bAFYYKaDYLDa5MRZbABfEI6A%3D%3D%3D#)
Transaction 0.001 USDC from [Evmos](https://www.mintscan.io/evmos/tx/811A03CDC335CBE7FA810B71A49D094914A0B73CD19F17DF11A9D72A38D10DDA) (Keplr) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/282A919455CF842BFDDB776CDB4EFEB2BAE8ACBBAB07F45C570BD26D69E92382) (Keplr) was completed
Tested from: https://portalbridge.com/
Transaction 0.001 USDC from [Evmos](https://www.mintscan.io/evmos/tx/B276BE74786A0DB118CA2DF270DA8AF2FB748104C32902C0D7B1858F0D2A85B2) (Keplr) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/E4602A65DD6B89FE76B5B523371B4EACFF6D9CACB212392984A18DC3DED9055B) (Keplr) was completed.
Closing the ticket.
Attachment:

<img width="692" alt="Screenshot 2024-05-21 at 10 33 13" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d93a4204-9a05-4f66-92dc-3f894ddf620b">

<img width="1015" alt="Screenshot 2024-05-21 at 10 45 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b93da732-6977-4e3d-9b79-7f325d280fb8">
