### ISSUE TITLE
[QA] [Mainnet] Transactions from Solana fails with "TransactionExpiredTimeoutError" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1689]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.0001 SOL from Solana (Phantom) to Avalanche (MetaMask)
2. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.

```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 4k2pnxbqksQRxrQSVXsSUWwedUEHP6YjUHtAEckHoT667Fy9TgZhR1de8ruGrBCjqrBArnxfSA348X5SdHGqrpZh using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61258)
    at async Connection$1.confirmTransaction (main.js:171:56700)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:40048)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:775672)
    at async BridgeRoute.send (main.js:326:22209)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101845)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eb7d73a0-301c-49f6-992d-f8c86bee862c)

Issue is also reproducible when sending 0.00001 SOL from Solana (Phantom) to Fantom (MetaMask). 

Issue is not reproducible with following scenarios:
* Send BONK from Solana (Phantom) to Fantom (MetaMask): Send from tx: [Solana Explorer](https://explorer.solana.com/tx/JcbxHVcZ4B1SgEkWT4HX2TTQPXA5VpPPtyfs437prEFKc3GXJadNzkFt16EfPPYuyoca11D6G5HbgmrBq2vBgEa), Send to tx: [FTMscan](https://ftmscan.com/tx/0xa74ca3969c62eb7674817b39fc943b0138b6087d18b5d92707de316cb23f0e65)
* Send DAI from Solana (Phantom) to Celo (MetaMask): Send from tx: [Solana Explorer](https://explorer.solana.com/tx/2dW8G4mJfyd3HgUX725PjBBC67SQmrX8iF2BExz9V2UmvT8TZcXcdymhJF3Ff98UmWh7ntszWsYxEvuJ94S6gGvb), Send to tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0x278858b227b0ab387c0705cae61c8f253ed7c9b25065aab645be4f08d4cdb34d)

## What is the expected/desired behavior
Transaction proceeds without errors.

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/732 and https://github.com/XLabs/portal-bridge-ui/issues/729

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet] (send from tx: [Solana Explorer](https://explorer.solana.com/tx/6vQBFz7wtyBmyZenzic9Je3CvGU1M7YhqYEXUaQQyziZZ9vRj2WqQxAbz23Nj9nmrCpw6Jppkey2GhvMRiDHoHH), send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x960f12684f0afcc12d07ab09fd9adcb02968f5f511c5a998cb6929aa70c98b20))
* https://portalbridge.com/ [Mainnet] (send from tx: [Solana Explorer](https://explorer.solana.com/tx/4D7anDviWnB6oyQi3kmNapUYd64MTNSfjdJWp56xjYXNkPgRPfEFWSqYVUJssSf5iK9LCLj4oNuabnE2eLyWydvk), send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x8dc85434326cb79d4754c7dd4954dfbfa43ee52b107d5677d90816e8e69fd9fa))

Ticket is closed.

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
`TransactionExpiredTimeoutError:` was shown for transaction from Solana (Exodus) to Sui (SUI)

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4aa7df16-58df-433f-a41d-c152c2e512fd

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] when sending 0.0001 SOL from Solana (Phantom) to Fantom (MetaMask). 

Error:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 2JMr1AQrrrrfXGdRFzRCcFZndqKAPhDmWrcboQXuaaJv6Amjjz1C4Von1m87LiW2wdaksWAKULtNAymtdd3ruR1x using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61258)
    at async Connection$1.confirmTransaction (main.js:171:56700)
    at async O.sendTransaction (solana-mxqvqbiT.js:1:40048)
    at async Ie (solana-mxqvqbiT.js:1:48158)
    at async signAndSendTransaction (main.js:322:774354)
    at async BridgeRoute.send (main.js:326:22209)
    at async Operator.send (main.js:328:80407)
    at async Object.Gn [as onClick] (main.js:499:101875)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b19b3ff-22ae-4bf2-9f91-1fd15b6be493)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction tBTC from Solana (Solflare) to Moonbeam (Metamask) fails with reason `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.`
Attachment:

![Screenshot 2024-03-06 at 10 04 58](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3732b8f1-8e95-4798-8758-9ab96a83e068)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending SOL from Solana (Phantom) to Avalanche (MetaMask) with "Automatic Bridge" route. 

Error: 
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 57RTGK2PSBC2Ywi2GYU7mnUfGSxaFT4G8DcrQRyPU3UDvJrZTJPFmZac67SFZsi3YoUnrrE7PMiisTzVdJTTio5g using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (pb-index.js:339:61258)
    at async Connection$1.confirmTransaction (pb-index.js:339:56700)
    at async E.sendTransaction (solana-aFYDy2Js-BE3Rb0Re.js:7:40079)
    at async ge (solana-aFYDy2Js-BE3Rb0Re.js:7:48239)
    at async signAndSendTransaction (pb-index.js:490:768742)
    at async RelayRoute.send (pb-index.js:494:30619)
    at async Operator.send (pb-index.js:496:81757)
    at async Object.Sr [as onClick] (pb-index.js:692:32413)
```


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/654775a0-3e7a-439e-8edf-635adadbf9b1)

**Comment by artursapek** [comment]
I just tested this again on https://preview.portalbridge.com/b1ba6e856a/. tried a Solana tx to Avalanche and it went through. I also tried one to Ethereum which also went through. it's definitely possible to still get timeouts sometimes, but it should be much less common.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/897596/7ba94e06-e914-4523-85c0-227f894569ba)

**Comment by artursapek** [comment]
going to close this for now. if we see more widespread issues happen again we can re-open.

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/# 
Re-opening the ticket
For manual transaction the second transaction is started (first has `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.` ), but for automatic transactions noticed that sometimes three transactions in a row have transaction timeout error.

Attachment:

<img width="1282" alt="Screenshot 2024-03-15 at 11 08 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd11d306-57af-4a14-83c7-29fe7fbd92f4">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/#
Transaction timeout is shown for transaction Solana to Osmosis
Attachment:

<img width="1358" alt="Screenshot 2024-03-19 at 12 57 13" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/923cf2c4-b68f-4087-80df-46eaf8784b89">

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/
First transaction USDC from Solana to Polygon failed `main-DFYuu1qs.js:522 TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.` Second transaction was started.

Attachment:
<img width="1288" alt="Screenshot 2024-03-20 at 16 52 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d4805e23-f02f-42b7-bab2-fa0a986fd379">

**Comment by tsadovska** [comment]
Claim transaction fails with "TransactionExpiredTimeoutError" when sending 0.01 USDC (Ethereum) from Ethereum (MetaMask) to Solana (Phantom). Checked on https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet].

Send from tx: [Etherscan](https://etherscan.io/tx/0x7e423eea2c03185bf697408849bb8abc8d46524dca7ccafecdcf3234d6d17cbf)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/59c17638-0e3c-4330-b34a-ddc8c93e4977)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/#
Transactions USDC from Solana (Phantom/Solflare/Exodus wallets) to Polygon fails reason `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.`
Attachment:
<img width="1320" alt="Screenshot 2024-03-25 at 10 38 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f8d3191-e0ae-4269-9809-d7357bc7a99b">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending 0.00001 SOL from Solana (Phantom) to Fantom (MetaMask). 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/38fdab39-4668-4b0c-a2eb-1e2bf7df98e2)

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 SOL from Solana (Phantom) to BSC (MetaMask). 

<img width="1020" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0b0e7f1c-e302-4298-982b-d0e50d39b612">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/ed4e22522f/#
Transaction 0.001 W (Solana) from Solana (Solflare) to Base (Metamask) Native token transfer manual route, failed to start `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. `
Attachment:

<img width="1248" alt="Screenshot 2024-04-19 at 08 44 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/59fc406b-2d9d-4053-a516-3dccb90914a5">

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Two transactions from Solana (Solflare) to Osmosis (leap) that were started expired in 60 seconds `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.`
Attachment:

<img width="1276" alt="Screenshot 2024-04-23 at 09 01 13" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/713e84b0-d861-451c-a7fc-464f3743d742">

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNxEc00NIWIRcIybhnzFZNN0ibBYHXJiLzYAL4h7QA%3D#)
`Wormhole Connect: error completing transfer TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.` is shown when trying to send 0.001 USDC (Solana) from Solana (Solflare) to Base (Metamask)
Attachment:
<img width="1290" alt="Screenshot 2024-04-30 at 12 34 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/70d1965c-0653-4338-b013-1e393851e5be">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Transaction 0.0001 SOL from Solana (Solflare) to Injective (Leap) fails, reason `pb-index-DrUOIUci.js:727 Wormhole Connect: error completing transfer TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.`

Attachment:

<img width="1275" alt="Screenshot 2024-05-07 at 15 44 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a7a95772-9b1d-412d-ae64-9db9f5b109c3">

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
`pb-index-Bl6bYNaM.js:727 Wormhole Connect: error completing transfer TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.` was shown for transaction 0.001 SOL from Solana (Solong) to Fantom (Metamask)
Attachment:
<img width="1270" alt="Screenshot 2024-05-21 at 14 08 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/174a5e00-40da-403a-b266-76a7ded8c47c">

**Comment by agodlevska** [comment]
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/
Transaction 0.001 SOL from Solana (Nightly) to Fantom (Metamask) fails with error `Wormhole Connect: error completing transfer 
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.`

Attachment:
<img width="1440" alt="Screenshot 2024-05-23 at 09 48 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/ac7219ea-0f49-4c07-8558-b790f6ad46b6">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.002 SOL from Solana (Phantom) to X Layer (MetaMask). 

Error appears after clicking on "Approve and proceed with transaction" button:
```
Wormhole Connect: error completing transfer TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature bMw3zpNqdR1Qigd3xrVYr5sbt8aUiYsdebMo3Wz58jAFP7wA2kP5YmmHeXHGGWSDpn1YGbud8fNNeCLdP2YA6NW using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (pb-index-DSi4RVd3.js:354:61416)
    at async Connection$1.confirmTransaction (pb-index-DSi4RVd3.js:354:56858)
    at async E.sendTransaction (solana-f9a7wYby-DxCUZcxw.js:7:44807)
    at async Ne (solana-f9a7wYby-DxCUZcxw.js:7:52965)
    at async signAndSendTransaction (pb-index-DSi4RVd3.js:516:72097)
    at async BridgeRoute.send (pb-index-DSi4RVd3.js:516:92596)
    at async Operator.send (pb-index-DSi4RVd3.js:519:93019)
    at async Object.ko [as onClick] (pb-index-DSi4RVd3.js:742:29990)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6e9968e7-d3bc-4cc0-a9cd-2c9f552b9c45)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with Phantom wallet.
* SOL transfer from [Solana](https://explorer.solana.com/tx/jsKA5ukNa9x31KoSNx3ywq58iqJQzURd2vw44AL6gtFA2qBTicCD99JKgfYw4QSbW21A6Vvw4qYRz6Q2AcjjUo1) (Phantom) to [Avalanche](https://avascan.info/blockchain/c/tx/0x91b62c6442adcbd48415d6004064076162f590571c2121992f3a6e3c63f8e953) (MetaMask)
* CELO transfer from [Solana](https://explorer.solana.com/tx/3aQRyr6dhYMSdKRgykeYE967e3dBZ1LwqPbXTsHiihHviBf1YpxyL6LBkrdVCTUzySLPar8RPZKscMUCFn8uyS9J) (Phantom) to [Osmosis](https://www.mintscan.io/osmosis/transactions/825B98A133893CF4B43E2A148467C923EF74E5445704607194988BD786C12379) (Leap)
* USDC from [Solana](https://explorer.solana.com/tx/3wrG2VWJCV5pAYHQPS2HmLUsHBsUV413uGLtQ6knEoHdz1br6dSEMnw66ZKSV5QNPv7hoj9KfXZh4ahDmS5fzvM3) (Phantom) to [Base](https://basescan.org/tx/0xd3ec271f3a29aba91e5853c1573e7aa60ac65643a8f9a0c7fa8c9a6084753343) (MetaMask) 
* SOL transfer from [Solana](https://explorer.solana.com/tx/4r4fsth88rPbcjMX6FuMLeaVfeLypyYRHVivtFKW56pm3gnQR8TD3wkCFBQzJjJuY8yPhGquvYt8FGi1XY6Bk9as) (Phantom) to [Injective](https://explorer.injective.network/transaction/39CB6BFA62E43BF5D39B142976BD1DBC38F28B7EB20A72D28963561CA6025F2C/) (Leap) 
* SOL transfer from [Solana](https://explorer.solana.com/tx/3UJ6yEVByoiAaiYvnDPVDHajUErg7YqdtNCJNqLTnNSSSRSAQrG3pcmHv6iwxeSoAidnm1HaS5m2yCkfp2vmm6NK) (Phantom) to [Fantom](https://ftmscan.com/tx/0xb3a75af2e50690bbe0a729e93223da1f1053f51a8aa9f632af8090fa68ca1351) (MetaMask) 

Issue is still reproducible with Nightly, Backpack wallets. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/3b81f32422/ [Mainnet]. 
* SOL transfer from Solana (Nightly) to Fantom (MetaMask)
* SOL transfer from Solana (Backpack) to Fantom (MetaMask)

```
Wormhole Connect: error completing transfer WalletSendTransactionError: 90 second timeout: unable to confirm transaction
    at oe.sendTransaction (solana-D8cUoBhF.js:2:49036)
    at async C.sendTransaction (solana-D8cUoBhF.js:2:44693)
    at async De (solana-D8cUoBhF.js:2:52946)
    at async signAndSendTransaction (main-HNR-Orw1.js:506:72760)
    at async BridgeRoute.send (main-HNR-Orw1.js:506:93065)
    at async Operator.send (main-HNR-Orw1.js:509:91731)
    at async Object.nr [as onClick] (main-HNR-Orw1.js:547:35185)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c3e3f96f-3c70-464b-8c49-8c9677a1030d)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenarios:
* SOL transfer from [Solana](https://explorer.solana.com/tx/2Ye88RisNdzVqxMeufVcH8QByE8tdNP9dn6F36spLrDNYVKJCP68Cn6JsqYAD4A59Prc9f4sghWuq11cYHBehwrD) (Nightly) to [Fantom](https://ftmscan.com/tx/0x37648f4c53ebef89a41f3234e71f6a0d471a70e93342af9d61798b77ebaa6f5d) (MetaMask) with Manual Bridge route
* SOL transfer from [Solana](https://explorer.solana.com/tx/NCFZZUMPf4vjJjLsxLCf7GgaHCosUWSGMsbGPudTHbmoE6cbA29pQnPuCqHrBXXJ9FrLyxsw6XgVr9UBW5txqyF) (Nightly) to [BSC](https://bscscan.com/tx/0xe3c1c52dd73869848f417e7d2eccbab1c7fb9d263963d64d95d46994cd7ef4d5) (MetaMask) with Automatic Bridge route 
* SOL transfer from [Solana](https://explorer.solana.com/tx/2XQjyUs5bEzFa5wAEUjh3y6FFWLk9nkgBdLpwbNmnQd7T2njeRkkxKDv4nZQ1YVrQjZugfwxEzx6QcNFY8XfcYDM) (Backpack) to [Celo](https://explorer.celo.org/mainnet/tx/0x1e8f4b7c63bc8312f1720f43c2edfbd827029fc7041edef84bc57efa88542ca3) (MetaMask) with Manual Bridge route
* SOL transfer from [Solana](https://explorer.solana.com/tx/47Siys7hjjiWmdvYe2DXWe7yLhWWa5guFRSb1x5Ts1bKz2dwm85BvRiQatjwiLJbidg4hsiQLPZ7AVoMEXr6ccCr) (Backpack) to [Sui](https://suiscan.xyz/tx/5LT31Hs47bTKKi2aJJLmQgG69CGhbodmNAr284j1iNx3) (Sui Wallet) with Automatic Bridge route
* SOL transfer from [Solana](https://explorer.solana.com/tx/4MMA5MDa3EpjdyUGr6N49jGcpjsXiKbG5Y1Egdoyho3X8UCXV5nTBZLvhCXeVdxMg38Q2w9i4VSWs6M5cnpzo94) (Phantom) to [Avalanche](https://avascan.info/blockchain/c/tx/0xc3d7492afa381cf2af0820888c87fde3306546a3850d79ea37dd16a6c4b347d9) (MetaMask) with Manual Bridge route

Ticket is closed.
