### ISSUE TITLE
[QA][Improvement] Provide matching warning messages for different networks when resuming transaction with invalid transactionId

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1696]
Preconditions:
Invalid transaction Id from Solana - 3Z3UJNdB2KgK2tVvqtMbfCS7hM6qjgQr93mN3kdmWuV7QsLpS3SrAuoMz7t54ra9FMcPYo9AsA1dMzrJw6iz8PVQ2
Invalid transaction Id from BSC - 0xb41408b00500d08a17a57ec8a42d9b2dd4a1046aa3ddbf4a58ed7482637513762

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#
https://preview.portalbridge.com/caab316c7d/

Steps:
1. Click on Menu
2. Open Resume transaction
3. From Network drop down list select Solana
4. Paste in the invalid transaction Id
5. Observe warning message
6. Copy incorrect transaction hash for BSC Network
7. Paste the transaction Id in search window
8. From drop down list select BSC
9. Observe warning message

Actual result: For Solana network the warning message when transaction ID is invalid is: "Bridge transaction not found, check that you have the correct chain and transaction ID", but for BSC network when incorrect transactionId is entered warning message is: "Invalid transaction ID"

Improvement: In case incorrect transaction Id is entered show the same warning message for all Networks

Attachment:

![Screenshot 2024-02-22 at 17 13 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9ff6ffc5-cef4-4604-b4fc-f744ecf4d21d)
![Screenshot 2024-02-22 at 17 13 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/57e95104-4a09-45c8-bc7f-0b2f942d5407)

**Comment by agodlevska** [comment]
Note: The error message is dependent on the transaction ID, not the network. Changing the provided transaction IDs for different networks will result in different errors.
