### ISSUE TITLE
Add integrator way to configure Solana priority fees

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1697]
## Description and context
Solana transactions require setting a priority fee to land transactions during periods of high congestion.

See:
- https://docs.solanalabs.com/proposals/fee_transaction_priority
- https://docs.helius.dev/solana-rpc-nodes/alpha-priority-fee-api

I propose adding a config that allows users to pass in a method for calculating appropriate Solana priority fees to set per transaction. Passing in a method allows integrators to customize how they calculate this, including:
- using Solana RPC `getRecentPriorityFees` to estimate based on past priority fees
- using Helius `getPriorityFeeEstimate` to lean on an external service to estimate appropriate priority fees

**Comment by artursapek** [comment]
I've looked into this and know generally how to get it done. however, it depends on #1698 merging first, which enables to add non-JSON-serializable things functions into the integration config. as of right now, because Connect only supports a stringified JSON config, we literally can't do this.

**Comment by tsadovska** [comment]
1) "TransactionExpiredTimeoutError" appears in Console when sending assets from Solana. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/b1ba6e856a/ [Mainnet]. Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1689.

2) "TransactionExpiredBlockheightExceededError" appears in Console when sending assets to Solana. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/b1ba6e856a/ [Mainnet]. Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1754.
