### ISSUE TITLE
[QA] Warning "Changes may not be saved" is not shown when user clicks on Back button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1702]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/7246284e5d/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 AVAX from Avalanche (MetaMask) to Celo (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click on "Back" button on transaction screen
4. Check if warning Changes may not be saved" is displayed

Actual result: User is redirected to the main screen. 

![Screenshot 2024-02-23 at 12 42 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cc967667-f394-422b-8050-d14e14367161)

warning:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/928c7bfe-aca8-4607-bc7b-f7a4e9c497f1)

Notes:
* Issue is not reproducible when user clicks on USDC tab, Rewards tab or Portal icon.
* Linked: https://github.com/wormhole-foundation/wormhole-connect/issues/1500 

## What is the expected/desired behavior
Warning "Changes may not be saved" is displayed.

**Comment by agodlevska** [comment]
The bug is still reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 

When the back button is pressed user is redirected to the main screen and the "Changes may not be saved" warning is not displayed.
