### ISSUE TITLE
[QA] [Testnet, Mainnet] [Solana] Warning "This dApp could be malicious" is shown in extension window

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1707]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Open Menu > "Resume transaction" screen
2. Search for tx hash `0x40dc1864f15a668768e82197b6e08fd1aeae8ca3b7317bd4dc6d2788ec75d27a` in Arbitrum network
3. Click on "Claim" button

Actual result: Warning "This dApp could be malicious" is shown in Phantom extension. 

![Screenshot 2024-02-23 at 19 27 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/21225655-af4d-4b83-b46d-38a37bc5b5ee)

## What is the expected/desired behavior
Warning is not shown. 

## Notes

Issue is not reproducible on https://portalbridge.com/ [Mainnet]. 
Scenario checked: Send SOL from Solana (Phantom) to Kujira (Leap).

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.03 SOL from Solana (Phantom) to Fuji (MetaMask). 


![Screenshot 2024-02-25 at 20 27 21](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/85198699-ea3c-4be9-9f84-51036834a573)

The transaction started successfully after the user clicked the "Ignore warning, proceed anyway" link.

**Comment by tsadovska** [comment]
Note: Issue is not reproducible on https://portalbridge.com/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 WETH from Ethereum (MetaMask) to Solana (Phantom). Warning "This dApp could be malicious" is shown in extension window.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f55b6e7c-665e-4fb6-947c-3074ebcfeca9)

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ when sending 0.05 SOL from Solana (Phantom) to Fantom (MetaMask). Warning "This dApp could be malicious" is shown in extension.

Attachment:
<img width="1440" alt="Screenshot 2024-07-24 at 11 14 17" src="https://github.com/user-attachments/assets/94ca8ca6-a64a-485a-bdc9-3ddc924c6e99">
