### ISSUE TITLE
[QA] [Testnet] USDC (Alfajores) is not present in Assets list 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1708]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS. 

1. Request USDC (Celo Alfajores) faucet on https://faucet.circle.com/ 
2. Open https://wormhole-connect.netlify.app/
3. Select "Alfajores" network as source chain
4. Select MetaMask wallet in From section
5. Open Assets list
6. Check if USDC (Alfajores) asset is present

Actual result: USDC (Alfajores) is not present in Asset list. Asset contract address: 0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B ([View Asset in explorer](https://explorer.celo.org/alfajores/token/0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B/token-transfers))

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d741adc0-3915-4d45-b841-ed9905a7d2a6)

## What is the expected/desired behavior
USDC (Alfajores) asset is present in Assets list.

**Comment by agodlevska** [comment]
The bug is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/e6f095a8-0cf8-46f9-8232-082dd7536aef
