### ISSUE TITLE
[QA]Incorrect Source address shown at Wormholescan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1709]
Preconditions:
Metamask wallet connected at sending From section
Sui Metamask Snap wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#
https://preview.portalbridge.com/7246284e5d/#

Steps:
1. Prepare to send 1 USDT from Ethereum to Sui
2. Click Approve and proceed with transaction
3. When transaction is in Progress click on View on Wormholescan
4. Observe the Source chain Source address

Actual result: Incorrect Source chain is shown

Expected result: Correct source chain address is shown

Attachment:

![Screenshot 2024-02-26 at 09 15 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/43f70777-76a5-40e7-8646-decd03145cce)

![Screenshot 2024-02-26 at 10 07 03](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ea4e2d25-4f7f-439e-b098-ae5c44a0b67b)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/
Incorrect Source address for transaction 0.0004 ETH from Ethereum (Metamask) to Polygon (Metamask), Source address for Metamask should be - 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01
Attachment:
[Wormholescan](https://wormholescan.io/#/tx/0xe17b0f68e2d903f938926cd302f932e294620aa493293fab601a4f547db967fa)
<img width="1009" alt="Screenshot 2024-05-17 at 09 00 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f1fa325e-6d0d-440c-8fc2-3bc0dd647e44">

**Comment by tsadovska** [comment]
Rechecked scenarios on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
* Correct source chain address is shown on [Wormholescan](https://wormholescan.io/#/tx/0xb9d20916c5041717f5fabe9ca558e9d4af6dd4773d3200b9a44f6f1e18c874ec) when sending USDT from [Ethereum](https://etherscan.io/tx/0xb9d20916c5041717f5fabe9ca558e9d4af6dd4773d3200b9a44f6f1e18c874ec) (MetaMask) to [Sui](https://suiscan.xyz/mainnet/tx/8yAYUYxyH8f9VeykAc2uJ7LkkosNxmKDUVCHvGFbCnak) (Sui Wallet) with Manual Bridge route.
* Correct source chain address is shown on [Wormholescan](https://wormholescan.io/#/tx/0x70cffa62a238075f990735e87f3cd325561a1e3557fc50a72cf676e9502bd50c) when sending USDT from [Ethereum](https://etherscan.io/tx/0x70cffa62a238075f990735e87f3cd325561a1e3557fc50a72cf676e9502bd50c) (MetaMask) to [Sui](https://suiscan.xyz/tx/Duf8sXTpeX2k9GrYjwmEDFF8wuz2fjeAr4hXsysgpxyi) (Sui Wallet) with Automatic Bridge route. 
* Correct source chain address is shown on [Wormholescan](https://wormholescan.io/#/tx/0x0304b45af46ba52ff18e38f5cecf4edd7038eeef59427cb797e374560b564d34) when sending ETH from [Ethereum](https://etherscan.io/tx/0x0304b45af46ba52ff18e38f5cecf4edd7038eeef59427cb797e374560b564d34) (MetaMask) to [Polygon](https://polygonscan.com/tx/0x1bf589d1a8b18d7d2014dd284a68d066dc57250c5e658f8853df40bcc79af44f) (MetaMask) with ETH Bridge route. Remaining issues: https://github.com/wormhole-foundation/wormhole-connect/issues/1423, https://github.com/wormhole-foundation/wormhole-connect/issues/2086
* Correct source chain address is shown when transaction is "In Progress" status.
* Correct source chain address is shown when transaction is in "Completed" status. 

Ticket is closed.
