### ISSUE TITLE
[QA][Mainnet] Transaction fails with reason - "Cannot estimate gas"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1710]
Preconditions:
Metamask wallet connected at sending From section
**Sui Metamask Snap** wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK
https://preview.portalbridge.com/7246284e5d/# - Tested NOK
https://wormhole-connect.netlify.app/ - Tested OK

Steps:
Prepare to send 0.1 USDT from Ethereum (Metamask) to Sui (Sui Metamask Snap)
Confirm that Manual Bridge in Route section is selected
Click Approve and proceed with transaction
Observe

Actual result: Transaction fails to start, failing reason: `Error: cannot estimate gas; transaction may fail or may require manual gas limit`

Expected result: Transaction is started

Comments: Transaction with automatic route tests OK.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/db83f2ed-c201-4131-9aa2-816612efc91b

![cannot estimate gas](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4c202e44-1a10-4605-ae43-ed71f798a2e9)

**Comment by AigaD** [comment]
Also transaction 0.1 USDT from Ethereum to Aptos (Nightly) using Manual Bridge in routes failed with reason: `Error: cannot estimate gas; transaction may fail or may require manual gas limit `
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e8ccb4bf-f1fa-4ec4-9660-2e1dcba6278c

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] when sending 1 USDT from Ethereum (MetaMask) to Injective (Leap). 

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0xdAC17F958D2ee523a2206206994597C13D831ec7","data":"0x095ea7b30000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa58500000000000000000000000000000000000000000000000000000000000f4240","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at checkError$1 (main.js:172:114180)
    at Web3Provider.<anonymous> (main.js:172:124788)
    at Generator.throw (<anonymous>)
    at mn (main.js:172:113201)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/48f0baae-5c62-4f9c-a25f-a79e8436a3a3)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/

Also reproduced when sending USDT from Ethereum (Metamask) to Arbitrum). Transaction fails with reason `Error: cannot estimate gas; transaction may fail or may require manual gas limit`

Attachment:
<img width="1332" alt="Screenshot 2024-03-18 at 10 37 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4bf0faf6-bed3-4dd5-b594-31daf97448a4">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with following scenario:

1. Prepare to send 2 USDT from Ethereum (MetaMask) to BSC (MetaMask)
2. Select "Automatic Bridge" option in Route section
3. Change slider position
4. Click on "Approve and proceed with transaction" button

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0xdAC17F958D2ee523a2206206994597C13D831ec7","data":"0x095ea7b3000000000000000000000000cafd2f0a35a4459fa40c0517e17e6fa2939441ca00000000000000000000000000000000000000000000000000000000001e8480","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (pb-index-DsRyVLaa.js:334:46729)
    at Logger.throwError (pb-index-DsRyVLaa.js:334:46862)
    at checkError$1 (pb-index-DsRyVLaa.js:340:114131)
    at Web3Provider.<anonymous> (pb-index-DsRyVLaa.js:340:124730)
    at Generator.throw (<anonymous>)
    at so (pb-index-DsRyVLaa.js:340:113152)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/665c9347-9730-471a-849d-7237d429493d)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Transaction 0.1 USDT from Ethereum (Metamask) to Osmosis (Leap) fails, reason `Error: cannot estimate gas; transaction may fail or may require manual gas limit`
Attachment:
<img width="1315" alt="Screenshot 2024-04-08 at 11 35 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f3d83ca7-f8d5-44fb-b857-402e49fd7eee">

**Comment by AigaD** [comment]
Tested from: [Wormhole Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYoAOIjgE9aI6NsFg9cmIoCqAZQYAVO2AC%2BIXyA#)
Transaction USDT from [Ethereum](https://etherscan.io/tx/0x8f82b28fad434ef202d5f0d0e09f48cad2e3a4cd48583ad84c28889e4822c64c) (Metamask) to [Polygon](https://polygonscan.com/tx/0x33230600d94d9eede47de9f5a793653828934a089eb964a8c2ca2ca6f091ffe3) (Metamask) tested OK
Tested from: https://portalbridge.com/
Transaction USDT from [Ethereum](https://etherscan.io/tx/0x66e28ada92335ab72ceee97e8a121fefdef82ed9deba7d34bb4930a2209e0dd0) (Metamask) to [Osmosis](https://www.mintscan.io/osmosis/transactions/5C5DAC7E0D5686F99765B0305BFFCEAECAC7854B0D2151F369D11D238D95A18C) (Leap) tested OK
Closing the ticket.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c42f66a-c846-436c-aacd-c15da537fc94

**Comment by AigaD** [comment]
Tested from: [Wormhole Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYoAOIjgE9aI6NsFg9cmIoCqAZQYAVO2AC%2BIXyA#)
Transaction USDT from [Ethereum](https://etherscan.io/tx/0x8f82b28fad434ef202d5f0d0e09f48cad2e3a4cd48583ad84c28889e4822c64c) (Metamask) to [Polygon](https://polygonscan.com/tx/0x33230600d94d9eede47de9f5a793653828934a089eb964a8c2ca2ca6f091ffe3) (Metamask) tested OK
Transaction USDT from [Ethereum](https://etherscan.io/tx/0x9f5566c3390d669082d41d4e3222c14ac97d305f365b92028b0a383715cefcd6) (Metamask) to [Arbitrum](https://arbiscan.io/tx/0x25ccaaa045f1b8a0bd75d1c864e95d294c34cda7edd971f3a800cf549c049ab2) (Metamask) tested OK
Tested from: https://portalbridge.com/
Transaction USDT from [Ethereum](https://etherscan.io/tx/0x66e28ada92335ab72ceee97e8a121fefdef82ed9deba7d34bb4930a2209e0dd0) (Metamask) to [Osmosis](https://www.mintscan.io/osmosis/transactions/5C5DAC7E0D5686F99765B0305BFFCEAECAC7854B0D2151F369D11D238D95A18C) (Leap) tested OK
Closing the ticket.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c42f66a-c846-436c-aacd-c15da537fc94
