### ISSUE TITLE
[QA][Testnet] Transactions with USDT asset are not moving past Waiting for Wormhole Network Consensus

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1711]
Preconditions:
Metamask wallet connected
USDT asset available

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.1 USDT from Goerli to BSC (or any other Network)
2. Click Approve and proceed with transaction
3. Observe if transaction is completed

Actual result: Transaction stays at "Waiting for Wormhole network consensus . . ." and is not moving forward

Expected result: USDT asset is sent to target chain

Attachment:
Transactions:
0.1 USDT from [Goerli](https://goerli.etherscan.io/tx/0x27b2546fad21075d788feaff8561b3961631fadf9d394e5699a17615aeff7936) to BSC
1 USTD from [Goerli](https://goerli.etherscan.io/tx/0xe112793e4ed1f92da9b569468a676f006b1ee082e080fb52e4b744c3a7e3e0a2) to Fantom

![Screenshot 2024-02-26 at 14 25 14](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/078f39ed-9e82-4deb-8e60-62b701894bf1)

**Comment by tsadovska** [comment]
Goerli network is deprecated: https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
Ticket to add support for USDT (Sepolia) token: https://github.com/wormhole-foundation/wormhole-connect/issues/2187.
Ticket is closed.
