### ISSUE TITLE
[QA] [Testnet] USDT is not present in Assets list on BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1712]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ with macOS and Google Chrome.

Steps:
1. Request USDT faucet on https://www.bnbchain.org/en/testnet-faucet 
2. Open https://wormhole-connect.netlify.app/ 
3. Select BSC network as source chain
4. Select MetaMask wallet in From section
5. Open Assets list
6. Check if USDT asset is present

Actual result: USDT is not present in Asset list. Asset contract address: 0x337610d27c682E347C9cD60BD4b3b107C9d34dDd ([View Asset in Explorer](https://testnet.bscscan.com/token/0x337610d27c682E347C9cD60BD4b3b107C9d34dDd))

![Screenshot 2024-02-26 at 16 08 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/61bab955-ca9b-4407-bc4d-f534fa7acc85)

## What is the expected/desired behavior
USDT asset is present in Assets list.

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/.
USDT is not present in Assets list on BSC.

Attachment: 

https://github.com/user-attachments/assets/fe6c38cd-cc42-438b-8b44-04eb333980d1

**Comment by agodlevska** [comment]
Issue is reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2).
USDT is not present in Assets list on BSC.

Attachment:
<img width="945" alt="Screenshot 2024-08-16 at 16 05 36" src="https://github.com/user-attachments/assets/147e18b4-7fc8-4434-a939-ec7a671993a3">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/. 
USDT is not present in Assets list on BSC.

Attachments:
<img width="1434" alt="Screenshot 2024-09-23 at 15 29 35" src="https://github.com/user-attachments/assets/48d4ba61-abd4-4fda-9dfe-2c04fcd8e835">
<img width="1440" alt="Screenshot 2024-09-23 at 15 29 52" src="https://github.com/user-attachments/assets/ec267625-b6bf-4a19-a551-c56b10861a91">
