### ISSUE TITLE
[QA]WSOL contract address is different on Wormhole-connect and on Metamask

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1717]
Preconditions:
Metamask wallet connected
WSOL asset is available for Ethereum Network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect Ethereum Network
2. Click on Asset
3. Search WSOL asset
4. Observe contract address
5. Open MetaMask extension
6. Select Ethereum network
7. Observe Token details for WSOL asset

Actual result: Contract address numbers are not matching on Wormhole-connect and Metamask wallet

Expected result: Contract addresses are matching

Comments:
WSOL contract address on [Etherscan](https://etherscan.io/token/0xD31a59c85aE9D8edEFeC411D448f90841571b89c)

Attachment:

![Screenshot 2024-02-27 at 08 55 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c87f9505-28de-4b67-b0a8-4651a8d83b06)

**Comment by tsadovska** [comment]
Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues.

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WSOL (Solana) on Ethereum, 0xD31a59c85aE9D8edEFeC411D448f90841571b89c
- WSOL (Solana) on Polygon, 0xd93f7E271cB87c23AaA73edC008A79646d1F9912

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
