### ISSUE TITLE
[QA] WETH (Base) contract address is different on Wormhole-connect and on Metamask

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1718]
Metamask wallet connected
WETH (Base) asset is available for Ethereum Network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect Ethereum Network
2. Click on Asset
3. Search WETH (Base) asset
4. Observe contract address
5. Open MetaMask extension
6. Select Ethereum network
7. Observe Token details for WETH (Base) asset

Actual result: Contract address numbers are not matching on Wormhole-connect and Metamask wallet

Expected result: Contract addresses are matching

Comments:
WETH (Base) contract address on [Etherscan](https://etherscan.io/token/0x1D4241F7370253C0f12EFC536B7e16E462Fb3526)

Attachment:

![Screenshot 2024-02-27 at 08 58 18](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a7a3da63-d097-4387-a403-6414cbcf6fb3)

**Comment by tsadovska** [comment]
Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues.

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WETH (Base) on Ethereum, 0x1D4241F7370253C0f12EFC536B7e16E462Fb3526
- WETH (Base) on Base, 0x71b35ECb35104773537f849FBC353F81303A5860

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
