### ISSUE TITLE
[QA] Cannot register USDT asset for transaction from Klaytn

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1719]
Preconditions:
Metamask wallet connected
USDT asset is available for Klaytn Network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.1 USDT from Klaytn to Base Goerli
2. Observe that token needs to be registered
3. Click on[ register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register)
4. Select Klaytn as Source chain
5. Connect wallet
6. Select USDT asset (Contract address - 0x9aE3161B9ADb36C534881BE5510300F8c89003dA )
7. Select Base Goerli for target chain
8. Connect wallet
9. Click Next on Send attestation
10. Click Create
11. Observe

Actual result: Token registration is stuck on Step 4 "Create wrapped token", error in console `Uncaught (in promise) Error: No wallet selected` is shown although wallets are connected and there is no notification in the wallet itslef

Expected result: Token is registered

Attachment:

![Screenshot 2024-02-27 at 09 34 37](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d6269d27-187d-43fd-a5ab-f9cfa4fc3a05)

**Comment by tsadovska** [comment]
Issue is reproducible when registering USDT asset for transaction Klaytn -> Aptos. Asset is shown as registered on "Token registration" page, but Aptos Explorer shows a "failed" status.
* Contract address: 0x9ae3161b9adb36c534881be5510300f8c89003da
* "Send attestation" step: https://baobab.klaytnscope.com/tx/0x4591390bd5d5f8791841e19a3459d25074fc71c2cb8db902a0b5bf395aac7059
* "Create wrapped token" step: https://explorer.aptoslabs.com/txn/0xe16b052a30536bb2150cc4c267a3b212227df803b42037dba17e7f37bcbd9f86?network=testnet


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/59fa6dff-f2dd-4348-bcd5-0ffb7bf89eb2)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/913ac182-7bb3-4d05-821e-713e18bca00c)

**Comment by tsadovska** [comment]
Issue will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/2232 is resolved. Only KLAY and wKLAY assets are displayed on Assets list when Klay network is selected.
