### ISSUE TITLE
[QA][Testnet]Transaction fails with reason "no wrapper for this token created yet"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1725]
Preconditions:
Phantom wallet connected at sending From section
Metamask wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/ - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested OK

Steps:
1. Prepare to send 0.01 USDC (Goerli) from Solana to Optimism Goerli
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe

Actual result: Transaction fails at Claim with reason "no wrapper for this token created yet", when there was no message that the token should be registered for the transaction

Expected result: Transaction is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2989f41e-a116-4598-bdac-b52ebf74a95d

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1689 is resolved.

**Comment by AigaD** [comment]
Blocked by: https://github.com/wormhole-foundation/wormhole-connect/issues/1793 
Balance for Optimism Goerli is not loading, transaction USDC (Goerli) from Solana (Phantom) to Optimism Goerli is not moving past step 2
Attachment:

<img width="1278" alt="Screenshot 2024-04-11 at 12 59 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6950f1c0-2a19-4d6d-9778-d0667e6da7dc">

**Comment by tsadovska** [comment]
Arbitrum Goerli, Optimism Goerli and Base Goerli balances are not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
