### ISSUE TITLE
[QA] Exodus wallet reacts only with second click

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1730]
Preconditions:
Exodus wallet extension installed

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.184

Tested from:
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
1. Connect Solana Network at sending From section
2. Click on Connect Wallet
3. Click on Exodus
4. Observe
5. Click again on Exodus wallet

Actual result: Exodus wallet reacts to click only with second time, with first click console shows `WalletConnectionError: n.defineFlag is not a function at oe.rt`

Expected result: Exodus wallet reacts with first click

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9403b935-9332-4a5e-ae75-aee8263b2445

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet], https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet]. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/309bc9de-9aa9-45cb-80f9-f31bec62bccb


Ticket is closed.
