### ISSUE TITLE
[QA][Improvement] Inform user that he is about to leave page where transaction is in progress

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1735]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/ 
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.001 USDC (Base) from Base to Avalanche
2. Click Approve and proceed with transaction
3. Wait until transaction is started
4. Click on Menu button
5. Click on Resume transaction
6. Try to return back to previously started transaction

Actual result: If user goes to any section under Menu button, he is not warned that transaction is in progress and by opening any other section, he will not be able to return to transaction in progress

Improvement: Inform user that transaction is still in progress before going to any other section

Comments: Linking to this ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1500

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2e8b30ac-6e99-45ab-bfa6-2d6734decbb7

**Comment by tsadovska** [comment]
Menu button is not displayed on Bridge screen on https://portalbridge.com/ and on https://wormhole-connect-mainnet.netlify.app/ after redesign. 

![image](https://github.com/user-attachments/assets/cada6cea-b7a8-4e79-a3d2-ad49345c4253)

![Screenshot 2024-08-26 at 17 27 05](https://github.com/user-attachments/assets/56b30edc-b517-4d65-bcde-06ede6998040)

Closing the ticket.
