### ISSUE TITLE
[QA][Testnet] Token registration not moving past Step 3 "Waiting for Wormhole Network consensus..." 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1745]
Preconditions:
Metamask wallet connected at sending From section
Phantom (Solana testnet) connected at sending To section
USDT balance available for Goerli Network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send USDT asset from Goerli to Solana
2. Observe that message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on [Register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register)
4. Select Goerli Network
5. Connect Metamask wallet
6. Paste in USDT contract address 0xC2C527C0CACF457746Bd31B2a698Fe89de2b6d49
7. Click Next
8. Select Solana network
9. Connect Phantom wallet
10. Click Next
11. Press on Attest and confirm
12. Observe

Actual result: Token attest is not moving past Step 3 "Waiting for Wormhole Network consensus..." 

Expected result: Token gets attested in timely matter and token is registered

Comments: Reproduced also when attesting USDC token for transaction from Goerli (Metamask) to Aptos (Spika)

Attachment:
![Screenshot 2024-03-04 at 11 59 54](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5d1d9876-0a87-4b4d-9d4a-896bbfd26a0b)

![Screenshot 2024-03-04 at 09 26 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bc1df051-9405-4390-864c-4bca174b0ac1)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
DAI (0x2D3538cEe9d0bfA387b20d307C40A95Ee314aAbD) token registration from Goerli to Klaytn is not moving past Waiting for Wormhole network consensus
Attachment:

![Screenshot 2024-03-07 at 12 02 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e2f3c82f-ddfe-4725-b800-e19463a02409)


![Screenshot 2024-03-07 at 12 04 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb34d26c-a606-45ad-8bd2-db3988254686)

**Comment by tsadovska** [comment]
Arbitrum Goerli, Optimism Goerli and Base Goerli balances are not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.

Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1630.
