### ISSUE TITLE
Fix cosmos wallet import issue

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1749]
This should fix cosmos related wallet issues. Please test some transfers between the IBC chains (kujira/evmos/osmosis), and between IBC and non-IBC chains. E.g.

- kujira <> base
- osmosis <> kujira
- osmosis <> solana
- evmos > solana (transferring to evmos is [disabled](https://github.com/wormhole-foundation/wormhole-connect/issues/1681) )

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/#
You will be able to view testing results [here](https://docs.google.com/spreadsheets/d/128zHVbllDoayKv9srzk9tIZSlYiIuCYmGKYNqQH16zk/edit#gid=874226312)
During testing noticed an issue with Evmos transaction, first transaction from Evmos failed, second transaction was started. Added observations to comment section in this ticket - https://github.com/XLabs/portal-bridge-ui/issues/654

Attachment:
![Screenshot 2024-03-05 at 11 45 12](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b295e441-7070-4f40-a222-0e07f5104254)
