### ISSUE TITLE
[QA] Route section information is no longer showing after switching Network for a few times

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1753]
Preconditions:
Metamask wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - - Tested NOK

Steps:
1. Select Fuji network at sending From section
2. Select Celo Network at sending To section
3. Select AVAX asset
4. Switch from Fuji to BSC Network
5. Select BNB asset
6. Switch Again to Fantom Network

Actual result: Route section information dissapear when Network is switched a few times

Expected result: Route section information is displayed

Attachment:

![Screenshot 2024-03-06 at 16 21 13](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f6aa7b2-a156-491c-9c7f-3fd0b59eb91b)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/901f72c5-e13b-452a-826e-f43a3a0b09cc

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Closing the ticket. Route section information is shown after asset is selected.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/103ff6af-6a49-4fb6-ba22-8bde619b300f

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)
If user changes networks The Route section information is no longer shown, but section itself is left shown on the screen.
I asset is not selected Route section should not be shown.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f67c7bb4-a0ac-4e65-aa67-33d602123e64

<img width="963" alt="Screenshot 2024-05-22 at 15 27 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c1b743c-c991-49f7-96db-76bec85b7975">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 

Route section information disappear when Network is switched. 

Attachment:
<img width="1440" alt="Screenshot 2024-08-22 at 18 06 22" src="https://github.com/user-attachments/assets/904f928a-3228-4cea-a492-d1f7ddf091d6">

**Comment by tsadovska** [comment]
Issue is no longer reproducible after the redesign. The amount field becomes empty, and the routes are no longer displayed after clicking the "Swap" button. Once the amount is entered, the available routes are displayed. Checked on https://portalbridge.com/. 


https://github.com/user-attachments/assets/a600c372-27d1-4857-a871-481cb1f0667d




Closing the ticket.
