### ISSUE TITLE
[QA] [Testnet, Mainnet] User is able to enter incorrect value in Amount field and text "$NaN" is shown

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1756]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send CELO from Celo (MetaMask) to Avalanche (MetaMask)
2. Enter invalid amount "2.5."
3. Observe amount in $

![Screenshot 2024-03-07 at 10 36 58](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d9e46475-7e97-4fe1-bf2f-907fc9702394)

## What is the expected/desired behavior
User should not be able to enter invalid value in Amount field.

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/#
When entering invalid amount ($NaN) is shown
Attachment:
<img width="682" alt="Screenshot 2024-03-26 at 10 43 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c6446f6-1f47-47ab-b860-52a23d6bc884">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Attachment:
<img width="998" alt="Screenshot 2024-04-15 at 11 57 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/883d8eb0-7711-45e9-890d-15305bb78d4c">

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by tsadovska** [comment]
Cannot reproduce the scenario on https://portalbridge.com/. 
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Ticket is closed.
