### ISSUE TITLE
[QA] "Error: failed to send transaction: Transaction simulation failed" when claiming on Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1757]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Open Menu > Resume transaction
2. Search for transaction hash 0x0452ba0f7e7d707963c181b65a1ed12de19e27fdf85184978c012e2acddb449b (Fuji)
3. Click on "Claim" button
4. Check if transaction has completed

Actual result: Transaction fails.

Errors:
```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x0
    at Connection$1.sendEncodedTransaction (main.js:172:1562)
    at async Connection$1.sendRawTransaction (main.js:172:1027)
```
`Reached the maximum number of retries.`

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fb59c641-32f7-4ceb-b016-53a495a1c472)

## What is the expected/desired behavior
Asset is successfully claimed.

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/#
Transaction 0.001 Ws from Sepolia to Solana (Phantom) failed at Claim, reason `Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete`
Attachment:
<img width="1282" alt="Screenshot 2024-04-16 at 11 56 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3cb09e71-53b2-43bc-b4a0-b9eb3a207dea">

**Comment by kev1n-peters** [comment]
I've noticed this before and there seems to be intermittent transaction simulation failures depending on the Solana devnet RPC used. I don't think this is a Connect level issue or anything we can really do.

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 SUI from Sui (Sui) to Solana (Phantom). Send from tx: [Sui Explorer](https://suiexplorer.com/txblock/54dDbJf3fYEmT8pVSDaqiNUJ5wrBMju7QJFyTNhN1vaC?network=testnet)

```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Computational budget exceeded
    at Connection$1.sendEncodedTransaction (main-UFl2dA4n.js:334:1562)
    at async Connection$1.sendRawTransaction (main-UFl2dA4n.js:334:1027)
    at async sendAndConfirmTransactionsWithRetry (main-UFl2dA4n.js:481:91514)
    at async postVaaWithRetry (main-UFl2dA4n.js:484:629531)
    at async postVaa (main-UFl2dA4n.js:484:782211)
    at async BridgeRoute.redeem (main-UFl2dA4n.js:486:24266)
    at async Operator.redeem (main-UFl2dA4n.js:489:132187)
    at async Object.Sr [as onClick] (main-UFl2dA4n.js:525:1313)
```


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/64c828d4-bd89-4f1b-99de-cb5edaf3252e)

**Comment by tsadovska** [comment]
Reproducible on https://testnet.portalbridge.com/ed4e22522f/ [Testnet] when sending 0.0001 Ws from [Base Sepolia](https://base-sepolia.blockscout.com/tx/0xfde64d3916fc867e42b6943e2d58a52894013545b07a9c2ad470456f5ec6ad15) (MetaMask) to Solana (Phantom). 

Error appears in Console after clicking on "Claim" button.
```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection$1.sendEncodedTransaction (pb-index-BqOk2Zp5.js:348:1562)
    at async Connection$1.sendRawTransaction (pb-index-BqOk2Zp5.js:348:1027)
    at async sendAndConfirmTransactionsWithRetry (pb-index-BqOk2Zp5.js:495:91514)
    at async postVaaWithRetry (pb-index-BqOk2Zp5.js:498:629568)
    at async postVaa (pb-index-BqOk2Zp5.js:498:776025)
    at async IA.receiveMessage (pb-index-BqOk2Zp5.js:503:103026)
    at async NttManual.redeem (pb-index-BqOk2Zp5.js:503:120466)
    at async Operator.redeem (pb-index-BqOk2Zp5.js:503:131641)
    at async Object.Ao [as onClick] (pb-index-BqOk2Zp5.js:726:1113)
```

**Comment by tsadovska** [comment]
Checked on https://wormhole-connect.netlify.app/ [Testnet]. Transaction were completed successfully. 
* AVAX transfer from [Fuji](https://testnet.avascan.info/blockchain/c/tx/0x8a4105f4b30c2cfac85a20355d920e626a50916ce4aba051d042f3b33ec4da72) (MetaMask) to [Solana](https://explorer.solana.com/tx/5ZetMAnyQ1wv629HicANuenBsL4J3Usp3EwZyMv1PQU8A9RcY1rUU9kzECiZPm7UjTH9JxTuDvZzANbHRrJHeWB9?cluster=devnet) (Phantom). 
* WFTM transfer from [Sepolia](https://sepolia.etherscan.io/tx/0xa495d81fa24142d754903250c487d67d87bdc3211ba486ea82a4606b03c302af) (MetaMask) to [Solana](https://explorer.solana.com/tx/5R9Xu3ZG2mSzodc1jnxdhDovtcCqA17N8eSArZDX6n4ZvbbHE7CVziABtMK5Cg9JSkrLha7ZBgAnffrcfrqPL45T?cluster=devnet) (Phantom). 
* 0.0001 SUI transfer from [Sui](https://suiscan.xyz/testnet/tx/BFMRKh9VGuE4PPa51LgkqizZZE8KtVNHTH8vs5LkJZaf) (Sui) to [Phantom](https://explorer.solana.com/tx/XZWRDofPM4Lic6LzvVpfMWNUvQywKN8MTVajRHDFx4V6qho5ZiYSBmKy21BnWG2K47eDNjYAxy2RNR4hUd6HAy8?cluster=devnet) (MetaMask) 

Checked on https://testnet.portalbridge.com/ed4e22522f/ [Testnet]. Transaction were completed successfully. 
* Ws transfer from [Base Sepolia](https://base-sepolia.blockscout.com/tx/0x58d27cacea43efe740a586ea455377e582d83fcb3566e61a7925ef3980170cd9) (MetaMask) to [Solana](https://explorer.solana.com/tx/66ZmpHJ47bKQYjoynBYLuusB2ddBczoQNp1Uwj7uC9cWkU8cKosJwQZ9rjEmkVRZF79S6R5khKR4KoRztGa6vSPE?cluster=devnet) (Phantom) with Automatic route
* Ws transfer from [Base Sepolia](https://base-sepolia.blockscout.com/tx/0x1feb1c11488b7e58a6fc06a9d5fb478c9f4bc31373e115d95a308197d87e1d39) (MetaMask) to [Solana](https://explorer.solana.com/tx/4LHGq4aHhpDySxjPdpnHETgrq4ZkH1nU5TXrQutzx9nbH77J2GvMT6QS5361zgvueBX5DMJNqdb7rY1wZb6AJWKA?cluster=devnet) (Phantom) with Manual route

Ticket is closed.
