### ISSUE TITLE
[QA] [Mainnet] "Error fetching relayer fee" shown for transaction, it cannot be started

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1758]
Preconditions:
Metamask wallet app connected through WalletConnect at sending From section (Or Metamask wallet conencted)
Metamask wallet app connected through WalletConnect at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/ - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
1. Select Ethereum Network at sending From section
2. Select Polygon Network at sending To section
3. Select ETH (Ethereum) asset
4. Enter the amount
5. Observe

Actual result: Transaction cannot be started `Error fetching relayer fee` is shown when entering all required fields for transaction

Expected result: Transaction can be Approved 

Attachment:
Using WalletConnect (Metamask app):

![Screenshot 2024-03-08 at 09 04 54](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9a39ca7-02dd-437e-9daa-cac97cf83ae8)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/44275bc6-20c9-4841-9ec4-f99d5e5f5d9c

Metamask wallet:

![Screenshot 2024-03-08 at 09 10 14](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fda810f6-f8d3-4306-b097-3c3c21768828)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Issue is no longer reproduced, "Error fetching relayer fee" is no longer shown for transaction ETH from Ethereum (WalletConnect) to Polygon (WalletConnect)
Closing the ticket
Attachment:
<img width="1075" alt="Screenshot 2024-03-13 at 09 32 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7fcb0553-fdc0-49e3-ac4e-f4edb30e16b9">

**Comment by agodlevska** [comment]
Reopening. 
Tested on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/
Sending ETH from Ethereum (Metamask) to Polygon (Metamask). 

Transaction cannot be started `Error fetching relayer fee` is shown when entering all required fields for transaction. 
Attachment: 
<img width="1440" alt="Screenshot 2024-05-29 at 14 49 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/487eac50-96c5-47d7-8076-9e81eb23e160">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/, 0.0003 ETH transfer Ethereum (MetaMask) to Polygon (MetaMask) was successful. 
* Send from tx: https://etherscan.io/tx/0x93797ebcc84d409bf8c148d5ea5b10a6af591217bfc5a5fece6fa61d7e390c83
* Send to tx: https://polygonscan.com/tx/0x220a100a2f6157669b37e6d043600a0f03bc9175a9076767967763202abc9b8c

![image](https://github.com/user-attachments/assets/0457c3e2-0d03-4850-9cf4-5ca4644b4a20)

Closing the ticket.
