### ISSUE TITLE
[QA] Install Coin98 URL can not be reached 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1762]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Coin98 extension is not installed or is disabled
2. Select Evmos as source chain
3. Click "Connect wallet" button
4. Select "Install Coin98" option

Actual result: https://wallet.coin98.com/ is opened

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e147852b-08b9-47c6-9423-20fcfccef538)

## What is the expected/desired behavior
Correct link is https://coin98.com/wallet 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88c839e8-2f24-4c09-b6ed-b6b3e6d50146)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Coin98 wallet URL leads to "This site can’t be reached"

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/599fa112-da37-4a77-942a-61a3ded3cba6

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ when user selects any Cosmos chain (Osmosis/ Evmos/ Kujira/ Injective), opens "Connect wallet" screen, and then clicks on "Install Coin98" option. Issue is not reproducible with Solana network. In case when Solana network is selected, https://coin98.com/ page is opened.

**Comment by tsadovska** [comment]
Closing the ticket, because it was reproducible when Cosmos chain was selected as source chain. 
Cosmos chains are no longer displayed on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
