### ISSUE TITLE
Injective support in Wormhole Connect

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1763]
## Description and context
- explorer: https://explorer.injective.network/
- this is a Cosmos chain via IBC

## Definition of done
- 2tx transfers out of Injective into non-IBC chains work
- 1tx transfers into Injective from non-IBC chains work
- 1tx transfers into Injective from other IBC chains work
- 1tx transfers out of Injective into other IBC chains work
- the INJ token itself is not supported by Connect

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b1ba6e856a/# and https://wormhole-connect-mainnet.netlify.app/
High priority issue noticed so far during testing:
#1785  [QA] Transaction from Aptos to Injective not moving past Step 2
#1784  [QA] [Mainnet] Transaction from Sui to Injective is stuck on Step 2
#1778  [QA] Transactions from Evmos to Injective are not moving past Step 2

Transactions can be viewed through this [link](https://docs.google.com/spreadsheets/d/128zHVbllDoayKv9srzk9tIZSlYiIuCYmGKYNqQH16zk/edit#gid=1435303588)

<img width="729" alt="Screenshot 2024-03-12 at 16 36 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a8b75c54-eede-4ad3-8f41-41d79cb1fcc5">
