### ISSUE TITLE
[QA] [Mainnet] Source chain gas estimate in Preview section differs significantly from gas estimate on MetaMask notification - token bridge route

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1765]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 USDT from Ethereum (MetaMask) to Sui (Sui wallet). 
* "Source chain gas fee" on Bridge screen is 0.00015 ETH (~$0.46)
* "Gas fee" on Redeem screen is 0.003307 ETH (~$10.06)
* Send from tx: [Etherscan](https://etherscan.io/tx/0xa73168a33fa6a064a0227af744d6a063e55a12379f519e4f23dc1ce422f52595)
* Send to tx: [Sui Explorer](https://suiexplorer.com/txblock/AAUh3YNkAQSzSC7qfbxyphuG8ysrUe9dPN9but58taHW)

![Screenshot 2024-02-25 at 15 06 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4de45934-cf74-4989-b30d-9c97d160bd8d)

![Screenshot 2024-02-25 at 15 11 19](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/176ef810-8421-448f-b885-aa45f65dbb2b)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/894b0821-4781-4c3c-a4c7-5cea9df767fc)

_Originally posted by @tsadovska in https://github.com/wormhole-foundation/wormhole-connect/issues/1641#issuecomment-1962958365_

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
Total fee estimate in Preview section is shown as 0.00015 ETH (~$0.53), but on Metamask the gas fee is 0.00369926 ETH ($13.06)
[Ethereum scan](https://etherscan.io/tx/0x05c79bac75ae53d5c2efe207b02ba7890c561b99c24be7336e1858a1320b1b71)
Attachment:
<img width="1273" alt="Screenshot 2024-03-21 at 09 26 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/844edb92-88a7-4ca9-9648-fcfbc3889498">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending 0.0001 ETH (Ethereum) from Ethereum (MetaMask) to Fantom (MetaMask).
* Source chain gas estimate in Preview section is ~ 0.0001 ETH (~$0.37)
* Gas fee in MetaMask 0.00225586 ETH ($8.28)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.00001 W from Ethereum (MetaMask) to X Layer (MetaMask). 

* Source chain gas estimate: ~ 0.00015 ETH (~$0.57)
* Gas fee in MetaMask: ~8$


![Screenshot 2024-05-28 at 21 14 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d41211c3-eef7-464a-8ee2-7a7a4f9baad5)


![IMG_4473](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b0a1a6bf-dfac-4219-9263-bf73dd3a602e)

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 1 USDT from Ethereum (MetaMask) to Sui (Sui Wallet) with Automatic Bridge route. 
* "Source chain gas estimate" on wormhole-connect is ~ 0.0003 ETH (~$1.05)
* Gas estimate in MetaMask is 0.00247461 ($8.68)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/82c3367d-ff72-4ae3-aa97-f3b76b00ad3f

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.

Checked following scenarios:
* USDT transfer from [Ethereum](https://etherscan.io/tx/0xf1ca77bed8089e076b86b2b3aafeb25feec3b50261fd1ae2e5770208ddac5bae) (MetaMask) to [Sui](https://suivision.xyz/txblock/ym4nCFnxaDrGcZQqWsFFqAh9nEeCDhPF3UnF8azdGb9) (Sui wallet); Source chain gas estimate 0.00015 ETH, gas fee in MetaMask 0.00015941 ETH, link to [Wormholescan](https://wormholescan.io/#/tx/0xf1ca77bed8089e076b86b2b3aafeb25feec3b50261fd1ae2e5770208ddac5bae).
* ETH transfer from [Ethereum](https://etherscan.io/tx/0x95751995b171e23651cf478489d1542899a9b91838c5fdc28b4a01fb7be04f55) (MetaMask) to [Fantom](https://ftmscan.com/tx/0xfb0956ca0d4ceb2e18e6fa84afea3ebe213c1103de2ddfb13308aacbf6aa4698) (MetaMask); Source chain gas estimate is 0.0001 ETH, gas fee in MetaMask 0.00014183 ETH, link to [Wormholescan](https://wormholescan.io/#/tx/0x95751995b171e23651cf478489d1542899a9b91838c5fdc28b4a01fb7be04f55).
* W transfer from [Ethereum](https://etherscan.io/tx/0xea83046149aeb2918bae79189e3364a73f3e1e2c512d63fbb08f4b3a207c0d8f) (MetaMask) to [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x32ae98c39e2af29834c0acd8855bd94c747af3e8186c6e29d793273b5bf94782) (MetaMask); Source chain gas estimate is 0.00015 ETH, gas fee in MetaMask 0.00034846 ETH, [link to Wormholescan ](https://wormholescan.io/#/tx/0xea83046149aeb2918bae79189e3364a73f3e1e2c512d63fbb08f4b3a207c0d8f).

Closing the ticket.
