### ISSUE TITLE
[QA] [Mainnet] Source chain gas estimate in Preview section differs significantly from gas estimate on MetaMask notification - tBTC route

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1766]
Issue is also reproducible on https://preview.portalbridge.com/7246284e5d/ [Mainnet] when sending with tBTC route. Gas estimate on wormhole-connect shows 0.0003 ETH(~$0.94), but gas fee in MetaMask is $56.08. Sent 0.000001 tBTC from Optimism (MetaMask) to Ethereum (MetaMask). Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0xd4c71139251069e705464d584f7693fe4e1d23d2036dfd66bd39166822dd851c).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/34a1e5ec-9a9e-4d05-951e-92b9aa8b06e3)

_Originally posted by @tsadovska in https://github.com/wormhole-foundation/wormhole-connect/issues/1641#issuecomment-1964553219_

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
For transaction 0.00001 tBTC from Ethereum to Polygon fee estimate in Preview section significantly differs from the one shown in Metamask wallet.
Attachment:
<img width="1279" alt="Screenshot 2024-04-02 at 11 09 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/36d4e967-6e07-49b9-aa5d-28c2797595eb">

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/3b81f32422/ when sending 0.000001 tBTC from Ethereum (MetaMask) to Solana (Phantom).

- "Source chain gas estimate" on Portal Bridge is ~ 0.00015 ETH (~$0.58)
- Gas estimate in MetaMask is 0.00180364ETH ETH ($6.94)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] when sending 0.000001 tBTC from Optimism (MetaMask) to Arbitrum (MetaMask). 
* "Destination chain gas estimate" on Portal Bridge is 0.004 ETH (Arbitrum) (~13.94)
* Gas estimate in MetaMask is 0.00000469 (~0.02)
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x51e831fbfeca4f4c87610d3ce296ffce18792ddd0f2bdb79a6034e360ea53e81)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/0xd5ac5498f7a891cb8e7c09760d4dc6f729a7d0822d6df70df5f4f819573a956c)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x51e831fbfeca4f4c87610d3ce296ffce18792ddd0f2bdb79a6034e360ea53e81)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3168dee1-4b08-437c-b30c-08a091c6ebf3
