### ISSUE TITLE
[QA] [Mainnet] WGLMR contract address on wormhole-connect is different from contract address in Metamask 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1770]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Select BSC network as source chain > Connect Metamask wallet > Open Assets list > Check WGLMR contract address
2. Open Metamask extension > Switch network to BSC Mainnet > Check WGLMR token details

Asset in Explorer: https://bscscan.com/token/0x1C063db3c621BF901FC6C1D03328b08b2F9bbfba

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9a4b034a-7687-4602-b43a-34d122c99fb6)

## What is the expected/desired behavior
Contract address is the same on wormhole-connect and in Metamask.

## Notes
* Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues.
* Issue is also reproducible on Fantom network.

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/bceadc8c64/#
WGLMR contract address also differs from contract address shown in [Suiscan](https://suiscan.xyz/mainnet/coin/0x66f87084e49c38f76502d17f87d17f943f183bb94117561eb573e075fdc5ff75::coin::COIN/txs)
Attachment:

<img width="604" alt="Screenshot 2024-05-08 at 12 48 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4cd0c0d3-206a-4b47-a989-f1b14a5acdee">
<img width="807" alt="Screenshot 2024-05-08 at 12 48 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0c9f099e-1d1d-45c9-9dfc-bb4f0e00d4d2">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Contract address gor WGLMR in Portal and in Moonscan is shown as - 0xAcc15dC74880C9944775448304B263D191c6077F , but in Metamask - 0x43E43580A34c8FdD4694e1F9B5F9b1121a7044a5
Attachment:

<img width="1394" alt="Screenshot 2024-05-13 at 12 46 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/80f242ca-d249-4e45-8dfb-a8528a9edc87">
<img width="1101" alt="Screenshot 2024-05-13 at 12 46 02" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1fcf744e-b5fe-47df-ae9f-c6689c78f163">

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WGLMR (Moonbeam) on BSC, 0x1C063db3c621BF901FC6C1D03328b08b2F9bbfba
- WGLMR (Moonbeam) on Sui, 0x66f87084e49c38f76502d17f87d17f943f183bb94117561eb573e075fdc5ff75::coin::COIN

Blast network is not displayed in Networks list on Portal Bridge.
Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
