### ISSUE TITLE
[QA] Notification to approve transaction is not displayed in Metamask app after network is switched

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1772]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Precondition: Fantom network is selected in MetaMask app.

Steps:
1. Open https://wormhole-connect-mainnet.netlify.app/ on Desktop
2. Prepare to send 0.0001 WAVAX from Fantom (MetaMask through WalletConnect) to Moonbeam (MetaMask through WalletConnect) 
3. Click "Approve and proceed with transaction" button
4. Approve transaction in MetaMask app
5. Click on "Claim" button 
6. Switch network to Moonbeam on mobile 
7. Check if notification to approve transaction appears on mobile

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/72e6adbe-a071-465c-b7fd-bbcdedf20463

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/432e3222-1da0-45f0-b3c2-e247f28b3854

## What is the expected/desired behavior
Notification to approve transaction appears on mobile.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet]. Notification to approve transaction is does not appear in MetaMask app when network is changed. 

Scenario:
1. Switch network to Fantom in MetaMask app on mobile
2. Prepare to send 0.001 ETH (Arbitrum) from Arbitrum (MetaMask through WalletConnect) to Optimism (MetaMask through WalletConnect)
3. Click "Approve and proceed with transaction" button
4. Approve notification to switch network on mobile
5. Check if notification to confirm transaction is displayed. 

Actual result: Notification to confirm transaction is not displayed.

**Comment by Eiei070922** [comment]
I'm sorry, everyone. I can't do anything. Right now I'm having problems
with my family. Can I have everyone handle it for me? I won't do it. Like I
said, I'm just starting to play. Again, please help handle the situation
for me. Thank you very much, especially regarding stocks. I once said that
I have no knowledge about this matter because I just started playing.

ในวันที่ อ. 19 มี.ค. 2024 23:44 tsadovska ***@***.***>
เขียนว่า:

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet].

Steps:
1. Switch network to Polygon in MetaMask app on mobile
2. Prepare to send 0.0001 APT from BSC (MetaMask through WalletConnect) to Blast (MetaMask through WalletConnect) 
3. Click "Approve and proceed with transaction" button
4. Approve notification to switch network on mobile
5. Check if notification to confirm transaction is displayed

Actual result: Notification to confirm transaction is not displayed. 

Error is appears in Console:
```
{context: 'client'} TypeError: Cannot set properties of undefined (setting 'defaultChain')
    at io.onChainChanged (index.es-C3-YBNbP-CRoBi-Wh.js:33:34307)
    at EventEmitter$2.<anonymous> (index.es-C3-YBNbP-CRoBi-Wh.js:33:33013)
    at EventEmitter$2.dt [as emit] (pb-index-u9c9TQ3X.js:260:3498)
    at Ag.setDefaultChain (index.es-C3-YBNbP-CRoBi-Wh.js:33:15383)
    at io.onChainChanged (index.es-C3-YBNbP-CRoBi-Wh.js:33:34214)
    at EventEmitter$2.<anonymous> (index.es-C3-YBNbP-CRoBi-Wh.js:33:32444)
    at EventEmitter$2.dt [as emit] (pb-index-u9c9TQ3X.js:260:3498)
    at zp.onSessionEventRequest (index.es-VnkPP7nS-Bo8sKlWr.js:40:104916)
    at zp.processRequest (index.es-VnkPP7nS-Bo8sKlWr.js:40:98605)
    at zp.processRequestsQueue (index.es-VnkPP7nS-Bo8sKlWr.js:40:97937)
```

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/c6532d9b17/ [Mainnet] when sending 0.00001 wstETH from Optimism (MetaMask mobile app) to Arbitrum (MetaMask mobile app). Notification to approve transaction does not appear in MetaMask app after changing the network. 

https://github.com/user-attachments/assets/4f2f7974-8e1e-488f-bd88-12714df92e53

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2). Checked 1 FTM transfer from Fantom (MetaMask) to Celo (MetaMask) with Manual route. 

Notification to Confirm transaction on Celo does not appear in MetaMask app after user accepts notification to switch network to Celo.
