### ISSUE TITLE
[QA] Cannot connect wallet through WalletConnect for resumed transaction

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1774]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet] with macOS, iPhone and Google Chrome.

Steps:
1. Prepare to send 0.001 GLMR from Moonbeam (MetaMask through WalletConnect) to Celo (MetaMask through WalletConnect) on Desktop
2. Click "Approve and proceed with transaction" button
3. Confirm transaction on mobile
4. Copy transaction hash from Moonscan 
5. Open Menu > Resume transaction 
6. Search transaction
7. Click on "Claim" button
8. Select "WalletConnect" option

Actual result: Transaction fails. 
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0x796Dff6D74F3E27060B71255Fe517BFb23C93eed","data":"0xaa4efa5b49842ab11b132198772b33f9634733c6f9f48b49da39aeaed0e5053d4a27a434","accessList":null}, error={"code":-32603,"message":"VM Exception while processing transaction: revert","data":"0x"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at checkError$1 (main.js:172:113924)
    at Web3Provider.<anonymous> (main.js:172:124788)
    at Generator.throw (<anonymous>)
    at mn (main.js:172:113201)
```

Send from tx: https://moonscan.io/tx/0xfc7ec06ec0a8d8c708fd7f3a8784204f561910d5178c2ed76985288258afc63b

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/56420209-81f1-4f4c-b039-9bd7e2aedae6

## What is the expected/desired behavior
WalletConnect pop-up with QR Code appears. User is able to connect wallet through WalletConnect to finish transfer.

**Comment by SamantaCasal** [comment]
FYI: @yuli-ferna 
Step 1
 
https://github.com/wormhole-foundation/wormhole-connect/assets/69044575/7a595034-fdf4-44c1-980e-35301ba6fddd

Step 2
When clicking approve from mobile, it shows the following message 
![CA093216-0F1A-40D5-8006-9E37296CF41E](https://github.com/wormhole-foundation/wormhole-connect/assets/69044575/9ebd695f-d971-41d1-bf0f-be479546fa36)

https://github.com/wormhole-foundation/wormhole-connect/assets/69044575/32af732b-0ec3-4fc1-9052-95fc38e9db41

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1683

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.
* "Connect wallet" button is shown on Desktop after transfer is resumed
* Notification to approve transaction is shown on mobile after transfer is resumed
* Transaction completes successfully

Closing the ticket.
