### ISSUE TITLE
[bug] Form is cleared after network is selected and wallet is connected for the first time

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1776]
### Is there an existing issue for this?
* [x]  I have searched the existing issues

 ### Current Behavior
Form is cleared after network is selected and wallet is connected for the first time.

### Expected Behavior
Network remains selected and wallet is connected.

### Steps To Reproduce
1. Open https://portalbridge.com/
2. Select Ethereum network as source chain
3. Connect MetaMask wallet in From section

### Environment
```
- OS: macOS 14.2.1 (23C71)
- Wallet: MetaMask
- Browser: Google Chrome Version 122.0.6261.112 (Official Build) (arm64)
```

### Anything else?
https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/9e2cfcd2-2c30-4130-8a2f-ba41678676f6

**Comment by artursapek** [comment]
this was solved
