### ISSUE TITLE
[QA] Gas estimate on wormhole-connect differs from gas estimate in MetaMask notification/ Leap wallet - Cosmos Gateway route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1779]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0002 CELO from Injective (Leap) to Avalanche (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Check "Gas estimate" value in "Send to" section
4. Click "Claim" button
5. Check "Gas fee" in MetaMask notification 

Actual result: "Gas estimate" on wormhole-connect is 0 AVAX ($0.00), but "Estimated fee" in MetaMask is ~0.0096641 AVAX $0.45. 

![Screenshot 2024-03-12 at 11 31 20](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ef8074f3-41d7-4465-b937-9120fb5c844a)

## What is the expected/desired behavior
Gas estimate on wormhole-connect is similar to gas estimate in MetaMask notification.

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b1ba6e856a/
When sending asst from Kujira network Fee estimate on Portal is shown as 0 KUJI, on Leap wallet pop-up the gas fee is shown as 0.01 KUJI
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b89e6cd2-bcd0-43b9-9b15-8146bcf03483

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] on Injective network. "Source chain gas estimate" on Portal Bridge is 0 INJ ($0.00), but gas fee on Leap wallet is 0.00050 INJ ($0.02). 


![Screenshot 2024-03-20 at 12 14 23](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4fa2499b-22e9-4201-ba37-d7784645a5dd)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] when sending 0.0001 USDC from Ethereum (MetaMask) to Avalanche (MetaMask). 
* "Gas estimate" value on Avalanche on Portal Bridge is 0.0003 AVAX (~$0.01)
* "Estimated fee" value in MetaMask is 0.00387435 AVAX $0.18

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2053--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.00001 USDT from Injective (Leap) to Ethereum (MetaMask). 
* "Gas estimate" value on Injective on Portal Bridge is 0 ETH ($0.00)
* "Estimated fee" value on MetaMask is 0.00131987 ETH $3.94

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJCO4plGboWIRcIybhnzFeABaQKkNik2CwOuTEXWwAXxDOgA#)
Gas estimate for ETH is shown as 0 ETH, but on Rabby pop-up shown as 0.00177964 ETH for transaction 0.000001 tBTC from Osmosis (Leap) to EThereum (Rabby)
Attachment:

<img width="1314" alt="Screenshot 2024-05-16 at 11 50 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe4d1543-63f0-44ea-8ca1-f7a4fb102ff4">

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ with the scenario mentioned above, when sending WETH from WETH from Osmosis (Leap) to Ethereum (MetaMask). 
* Gas estimate on destination chain - 0 ETH ($0.00)
* Gas estimate in MetaMask - 0.00034716 ETH ($0.87)


![Screenshot 2024-09-03 at 10 19 46](https://github.com/user-attachments/assets/7dcfce1a-2259-42a6-b5cf-9f55666dfc31)

**Comment by tsadovska** [comment]
Closing the ticket, because gas estimates are no longer displayed on Confirm transaction screen after redesign.
