### ISSUE TITLE
[QA] Occasionally balance for Injective network fails to load

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1780]
Preconditions:
Leap wallet connected (Injective mainnet network)

Environment:
OS: macOS Ventura 13.0.1
Wallet: Metamask, Leap
Browser: Chrome Version 121.0.6167.85
Tested from: https://preview.portalbridge.com/b1ba6e856a/ and https://wormhole-connect-mainnet.netlify.app/

Steps:
1. Click on Select Network
2. Select Injective
3. Click on Assets
4. Observe if balance is loaded
5. Repeat steps 1-4 few times

Actual result: Inconsistent issue, noticed that for some tests the Injective network asset balance is not loading, page has to be refreshed and eventually asset balance is shown.

Expected result: Asset balance is shown every time for Injective Network

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8d25d663-d78d-4c9b-83f8-db56884eef70

![Screenshot 2024-03-12 at 12 12 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/439dbeb0-fa94-42a0-8801-64190c9286ec)

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.
The issue no longer reproduces. The balance for the Injective network is loaded without errors every time.
Closing the ticket.
