### ISSUE TITLE
[QA] [Mainnet] Fee value for should have more decimals after comma - INJ

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1782]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 CELO from Injective (MetaMask) to Osmosis (MetaMask)
2. Check "Gas fee" value in "Send from" section
3. Open "Injective Explorer" link
4. Check "Fee" value

* Send from tx: [Injective Explorer](https://explorer.injective.network/transaction/DFB38E9E856D7FBDE5DADCEEA4921DD38C5D644D1331092C93431898D5ACF24D/)
* Send to tx: [MintScan](https://www.mintscan.io/osmosis/transactions/0ED0281E1A8CD65883BE1042503F7C1A37593FC91424B19B0CAB56A5B539807D)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d3b72955-d319-4a86-a421-fd6b81815a62)

## What is the expected/desired behavior
Gas fee for INJ on wormhole-connect should have more decimals after comma. 

## Notes
Linked to https://github.com/wormhole-foundation/wormhole-connect/issues/651, https://github.com/wormhole-foundation/wormhole-connect/issues/1763.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet]. Gas fee on Redeem screen is 0 INJ, but fee value on Injective transaction Explorer is 0.0005 INJ. 
* Send from tx: [Injective explorer](https://explorer.injective.network/transaction/18C445CF30EA3575E960847EB459874CB66890B8D3327C681B5286CA3B120473/)
* Send to tx: [Moonscan](https://moonscan.io/tx/0xa8649ac499c146195e174fddaafd3284341c15bba0dccb03cc2b6200280721b3)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending WMATIC from Injective (Leap) to Solana (Phantom). 



![Screenshot 2024-03-26 at 08 51 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/01b4228a-c96a-41b9-85e9-5dd68c971fb4)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] when sending 0.00001 WMATIC from Injective (Leap) to Osmosis (Leap). 
* "Source chain gas estimate" value on Portal Bridge is ~ 0 INJ ($0.00) 
* Gas estimate value in Leap wallet is 0.00050 INJ $0.02

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/41c5f197e5/. 
Sending WBNB from Injective (Leap) to Fantom (MetaMask).

Attachment: 
<img width="725" alt="Screenshot 2024-08-14 at 10 20 35" src="https://github.com/user-attachments/assets/ef610c4e-2402-49d9-be1b-817967acb743">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
Sending 0.01 APT from Injective (Leap) to Solana (Phantom).

Attachment:
<img width="551" alt="Screenshot 2024-09-04 at 10 49 50" src="https://github.com/user-attachments/assets/63594341-9242-4093-90d5-478e5739aa5b">

**Comment by tsadovska** [comment]
Cosmos chains are no longer displayed in Networks list after redesign.

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


Closing the ticket.
