### ISSUE TITLE
[QA] [Mainnet] Transaction from Sui to Injective is stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1784]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/b1ba6e856a/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.001 SUI from Sui (Sui wallet) to Injective (Leap)
2. Click "Approve and proceed with transaction" button
3. Check if transaction is completed

Actual result: Transaction is stuck on Step 2.

```
Error: No redeem transaction found on chain injective
    at fetchRedeemedEventNonCosmosSource (/main.js:328:5710)
    at async CosmosGatewayRoute.fetchRedeemTx (/main.js:328:37429)
    at async CosmosGatewayRoute.isTransferCompleted (/main.js:328:36646)
    at async /main.js:524:1246
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7dbc2919-d38e-45ef-a5fe-4e30791b93cb)

## What is the expected/desired behavior
Transaction is completed. 

## Notes
* Send from tx: https://suiexplorer.com/txblock/DJUDuSwgbRvRHcshzGBaBM7jKuSGTAHfWHHyAbU56Mck (checked on https://wormhole-connect-mainnet.netlify.app/)
* Send from tx: https://suiexplorer.com/txblock/CUKQeP7YFWcdi1eKNwvujnMvy6NCP28Z2gMbda16hDdc (checked on https://preview.portalbridge.com/b1ba6e856a/)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Transaction 0.01 SUI from [Sui](https://suiexplorer.com/txblock/5b2mJZGX2mN6rMempYvfCkAhhtefyNvo2k7dqm3PqwCP) (Sui) to [Injective](https://explorer.injective.network/transaction/9815DF860C13BE7E168F3BB8988768050A00FD673822E5DE50B493E12EA13A67/) (Leap) was completed

Tested from: https://preview.portalbridge.com/b1ba6e856a/
Transaction 0.01 SUI from [Sui](https://suiexplorer.com/txblock/5Tb4hnLCJVpeftyNr839wn8tF8xJegTEBibzf9QPRnWS) (Sui) to [Injective](https://explorer.injective.network/transaction/247B515DBA464731E49719CB3CBDDF1808A7EDEE18B49C22A128F5FA78E29BE0/) (Leap) was completed

Closing the ticket
