### ISSUE TITLE
[QA][Mainnet] Transaction from BSC not starting

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1792]
Preconditions:
Metamask wallet connected
Console is open

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/ 

Steps:
1. Prepare to send 0.01 BNB from BSC to Optimism
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction is not starting, console shows `Error: Wormhole Circle relayer contract for domain bsc not found`

Expected result: Transaction is started

Attachment:

<img width="1340" alt="Screenshot 2024-03-14 at 13 00 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bb701d44-47a7-4123-963e-c4230b9a8a62">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d1ef3356-5237-4173-ae2a-a74a7649ffcf

**Comment by OfficialMetamaskdesk** [comment]
Contact the support team directly, send them a mail officialmetamaskdesk@mail.com they’ll assist you.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Tested OK. Transaction 0.001 BNB from [BSC](https://bscscan.com/tx/0x1d96caa68d91c85b272c3e04fc02ba5b8fa61ef9450116ba74a029a982152419) to [Optimism](https://optimistic.etherscan.io/tx/0xd3949b628dca80d4a141e670493018913d1562ce005f75f03cc505afd9dc3043) was started and completed.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8cdb6303-5744-4a01-8de8-0e56e95bb4e8

<img width="1061" alt="Screenshot 2024-03-18 at 10 06 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/37dd2f3e-4822-4c0b-93a3-52c2b6887cc8">
