### ISSUE TITLE
[QA][Testnet] Balance is not loading for Arbitrum/Optimism/Base Goerli networks

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1793]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/#

Steps:
1. Click on Select network
2. Select Optimism Goerli/ Arbitrum Goerli or Base Goerli
3. Click on Assets
4. Observe

Actual result: Balances are not loading for Arbitrum Goerli / Optimism Goerli and Base Goerli Networks

Expected result: Balances are shown for selected networks

Comments: Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1613

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3b6cb243-68eb-49dc-9abd-c09b27d35f76

<img width="1336" alt="Screenshot 2024-03-14 at 16 47 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f5aec855-a80c-4f77-b345-f88aa40246f5">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/20a74e06-bf0d-4a51-ae8e-e71fa46b0de5

**Comment by tsadovska** [comment]
Arbitrum Goerli, Optimism Goerli and Base Goerli  balances are not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
