### ISSUE TITLE
Support Near in Connect

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#1796]
## Description and context

Near is currently supported in the advanced tools legacy bridge experience, but not in Connect.  This is a manual route. This task is to add support for Near through SDKv2 in order to achieve feature parity with advanced tools.
Explorer: https://nearblocks.io/

## Definition of done

(manual) 2tx transfers out of Near work
(manual) 2tx transfers into Near work

## Other notes
Unclear if automatic 1x transfers is required

**Comment by mliu-xlabs** [comment]
if 1tx transfer required, then dependency on relayers support

**Comment by Eiei070922** [comment]
It's very comfortable to look at. The letters are big. Thank you very much.
I like this. The entire team is very skilled. 👍👍🙏

ในวันที่ ศ. 15 มี.ค. 2024 07:22 mliu-xlabs ***@***.***>
เขียนว่า:
