### ISSUE TITLE
[QA][Testnet] Cannot change Native gas slider position when sending FTM from Fantom to Base Goerli

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1804]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/ - Tested OK

Steps:
1. Prepare to send 2 FTM from Fantom to Base Goerli
2. Select Automatic Route
3. Enable Native Gas
4. Try to change slider position

Actual result: Slider position cannot be changed

Expected result: Slider positions is changed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/430271af-6571-46e9-93b1-f9c88737c6b5

**Comment by tsadovska** [comment]
Arbitrum Goerli, Optimism Goerli and Base Goerli balances are not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
