### ISSUE TITLE
[QA][Testnet] Transaction from Mumbai is not starting

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1805]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/#  - Tested NOK
https://wormhole-connect-mainnet.netlify.app/ - Tested OK

Steps:
1. Prepare to send 0.001 MATIC from Mumbai to any network (e.g. BSC)
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction is not starting, console shows `Error: invalid address or ENS name `

Expected result: Transaction is started and completes

Attachment:
<img width="1292" alt="Screenshot 2024-03-18 at 16 13 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bb1c1528-a838-4928-9667-13b41051f65d">

**Comment by AigaD** [comment]
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1958 is solved

**Comment by agodlevska** [comment]
Mumbai network is no longer displayed on https://wormhole-connect.netlify.app/. 

Attachment:
<img width="597" alt="Screenshot 2024-07-24 at 12 29 21" src="https://github.com/user-attachments/assets/61ae59f5-1985-42cd-96f2-570c95c4aac4">
