### ISSUE TITLE
[QA] [Mainnet] Transaction fails with "WalletSendTransactionError: Unexpected error"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1807]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Select Solana as source chain and Fantom as destination chain
2. Connect Phantom wallet in From section and MetaMask in To section
3. Select any asset (in my case USDC Solana, WAVAX, SOL)
4. Enter Amount (in my case 0.0001)
5. Click "Approve and proceed with transaction" button
6. Approve transaction in notification

Actual result: Transaction fails with  "WalletSendTransactionError". 

```
WalletSendTransactionError: Unexpected error
    at se.sendTransaction (solana-X8JuH5fk.js:1:44279)
    at async E.sendTransaction (solana-X8JuH5fk.js:1:39942)
    at async le (solana-X8JuH5fk.js:1:48189)
    at async signAndSendTransaction (main-xoVj7mpe.js:322:771890)
    at async BridgeRoute.send (main-xoVj7mpe.js:326:22381)
    at async Operator.send (main-xoVj7mpe.js:328:82699)
    at async Object.Gn [as onClick] (main-xoVj7mpe.js:522:101296)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dd6ad0f8-d652-4058-9755-2a163e779a62

## What is the expected/desired behavior
Transaction proceeds without error.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
Transaction 0.01 USDC (Avalanche) from Avalanche to Solana failed at claim, reason `WalletSendTransactionError: Unexpected error`
Attachment:
<img width="1305" alt="Screenshot 2024-03-20 at 18 15 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2ebe5b1b-4fd1-48e0-8d88-b3f22a868832">

**Comment by tsadovska** [comment]
Reproducible from https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 USDC (Ethereum) from Etherscan (MetaMask) to Solana (Phantom). 

Error after clicking on "Claim" button:
```
WalletSendTransactionError: Unexpected error
    at se.sendTransaction (solana-OiD9MwxO.js:1:44279)
    at async E.sendTransaction (solana-OiD9MwxO.js:1:39942)
    at async le (solana-OiD9MwxO.js:1:48189)
    at async signAndSendTransaction (main-DFYuu1qs.js:322:772861)
    at async CCTPManualRoute.redeem (main-DFYuu1qs.js:327:84180)
    at async Operator.redeem (main-DFYuu1qs.js:328:83271)
    at async Object.nr [as onClick] (main-DFYuu1qs.js:523:1112)
```

Send from tx: https://etherscan.io/tx/0x7e423eea2c03185bf697408849bb8abc8d46524dca7ccafecdcf3234d6d17cbf


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/947d4fea-5630-4d7b-bc34-e435bd3ca6dd

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/#
Transaction 0.001 WSOL from Klaytn (Metamask) to Solana (Phantom) fails, reason `pb-index-DsRyVLaa.js:716 WalletSendTransactionError: Unexpected error`

Attachment:
<img width="1304" alt="Screenshot 2024-03-26 at 16 27 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/23f6058a-4900-4f24-b687-9ad634fc5a5e">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending 1 BONK from Solana (Phatom or Backpack) to Celo (MetaMask). 

```
WalletSendTransactionError: Unexpected error
    at ie.sendTransaction (solana-e7hOssVY-Rc1sC8iq.js:7:44305)
    at async C.sendTransaction (solana-e7hOssVY-Rc1sC8iq.js:7:39970)
    at async Me (solana-e7hOssVY-Rc1sC8iq.js:7:48208)
    at async signAndSendTransaction (pb-index-Bn_4pseu.js:490:776645)
    at async BridgeRoute.send (pb-index-Bn_4pseu.js:492:22491)
    at async Operator.send (pb-index-Bn_4pseu.js:495:127455)
    at async Object.ko [as onClick] (pb-index-Bn_4pseu.js:717:27642)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4dc1ff36-a5aa-4599-a88d-7ace47278f6b)

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/#
Transaction 0.001 Ws from Sepolia to Solana failed at Claim, reason `WalletSendTransactionError: Unexpected error`
Attachment:

<img width="1294" alt="Screenshot 2024-04-15 at 22 10 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d27c9faf-87ff-4e56-8c06-a9d8d0908251">

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect-mainnet.netlify.app/ 

- Transaction 0.0001 USDC from [Solana](https://explorer.solana.com/tx/2EN2VCxbX822kFJC7iY26nTSHSui5GtJATYmzzUBzR6pa7wLeEwQvHTQp2S8zMA6ReKX411YEhG5ECZE9YETFNLG) (Phantom) to [Fantom](https://ftmscan.com/tx/0x80954c735a67978dafb4dd0a77d73ae80fd1aa0125d280bf99ea2d37f7fe9331) (Metamask)
- Transaction 0.0001 WAVAX from [Solana](https://explorer.solana.com/tx/4RKcgM1mqbR92ZkLA5JbmZXHLctgXi42JmWJubqYg8anzw4btxwobXTKkrxSJfjeVCg97cWQJCo7W1FgHS7S8z2d) (Phantom) to [Fantom](https://ftmscan.com/tx/0x423c6214b6d1bc60e37f9ce508a92c0c5277d48dc2e95d4a2682dbd47858631f) (Metamask)

Tested on https://portalbridge.com/

- Transaction 0.0001 WAVAX from [Solana](https://explorer.solana.com/tx/46zuSn4Bh8uMJmZhjMypgLtVAfcfrv6QvbZKoCUWQkFoi6AH6nPVqc2MSvH9AX9wE3prYfL8VPDQVVQAui3fSJNZ) (Phantom) to [Celo](https://explorer.celo.org/mainnet/tx/0xbc0255d1d8a45ce92220e934382a9da619fc12b28aaadefa48b24aa8541d5a1f) (Metamask)

All transactions are completed. 
Closing the ticket.

Attachments:
<img width="1440" alt="Screenshot 2024-05-24 at 11 25 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b309d818-d8bb-44d3-b86e-26bcac611d27">
<img width="1440" alt="Screenshot 2024-05-24 at 11 26 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/8d674505-fe41-4188-9134-61d1546b9dda">
<img width="1440" alt="Screenshot 2024-05-24 at 11 25 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b3754731-6fee-48ca-8850-d4b7edc65eab">
