### ISSUE TITLE
Adjust compute budgets in Solana to address congestion

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#1808]
## Description and context

Experiment with adjustments to the compute budget (default is 200k per instruction which may be too much) as a means to improve txn error rates on Solana

## Definition of done

200k compute unit set to a lower value such as 80-100k. Observe improved txn rates, if possible.
Verify no regression to manual + automatic txns for Solana

**Comment by artursapek** [comment]
this was done in https://github.com/wormhole-foundation/wormhole-connect/pull/1795
