### ISSUE TITLE
[QA] [Mainnet] Source chain gas estimate in Preview section differs significantly from gas estimate in MetaMask notification - Circle CCTP route, ETH (Ethereum)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1816]
## Describe the current behavior in detail
Checked on https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.01 USDC (Ethereum) from Ethereum (MetaMask) to Solana (Phantom)
2. Check "Source chain gas estimate" amount in Preview section
3. Click "Approve and proceed with transaction" button
4. Check Gas estimate in Metamask wallet

Actual result:
- Source chain gas estimate on wormhole-connect is ~ 0.00015 ETH (~$0.49)
- Gas estimate in Metamask notification is 0.00857137 ETH ($27.11)

![Screenshot 2024-03-20 at 18 34 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0081e780-a6db-42ab-a8d9-c4b1952ca2b8)

## What is the expected/desired behavior
Source chain gas estimate is similar to gas estimate in MetaMask notification.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet].

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/#
Gas fee estimate significantly differs in Preview section and in the Metamask notification.
Transaction 1.3 USDC from Ethereum to Avalanche
Attachement:

<img width="1313" alt="Screenshot 2024-03-25 at 16 26 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/26c55ab5-3f17-4933-b3be-974167446571">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending 0.0001 USDC (Ethereum) from Ethereum (MetaMask) to Avalanche (MetaMask). 
* "Source chain gas estimate" value on Portal Bridge is ~ 0.00015 ETH (~$0.51)
* Gas estimate in MetaMask is 0.00493807 ETH $16.02

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYoAOIjgE9aI6NsFg9cmIrtgAviDdA%3D) when sending 0.0001 USDC from Ethereum (MetaMask) to Polygon (MetaMask). 
* "Source chain gas estimate" on wormhole-connect is ~ 0.00015 ETH (~$0.47)
* Gas estimate in MetaMask is 0.0010641 ETH ($3.44)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/3b81f32422/ when sending 0.01 USDC from Ethereum (MetaMask) to Solana (Phantom).

- "Source chain gas estimate" on Portal Bridge is ~ 0.00015 ETH (~$0.58)
- Gas estimate in MetaMask is 0.001538 ETH ($5.92)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/933197c94d/ when sending 0.01 USDC from Ethereum (MetaMask) to Base (MetaMask).

- Source chain gas estimate" on Portal Bridge is ~ 0.0003 ETH (~$1.06)
- Gas estimate in MetaMask is 0.002964 ETH ($10.48)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ when sending 0.4 USDC from Arbitrum (MetaMask) to Base (MetaMask).

- Source chain gas estimate" on Portal Bridge is ~ 0.0015 ETH (Arbitrum) (~$5.23)
- Gas estimate in MetaMask is 0.000002 ETH (Arbitrum) (~$0.01)

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign. Gas estimates on source chain are no longer displayed. 
Closing the ticket.
