### ISSUE TITLE
[QA]Gas estimate instead of gas fee is shown when transaction is completed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1817]
Preconditions:
Metamask wallet connected at sending From section
Phantom wallet connected at sending To section

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.01 USDC (Polygon) from Polygon to Solana
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe gas fees when the transaction is completed

Actual result: Instead of Gas fee, Gas estimate is shown

Expected result: Gas fee is sown

Attachment:
[Polygon scan](https://polygonscan.com/tx/0xf2a33ab2f2c9ba1c0045da51320ff4652c035bd7a2f315e812d3a2404a7b7802)
[Solscan](https://solscan.io/tx/f9Y1Kc6MwFHuzJrA6wsTfC6FN4dt8AjzkKjZzgkAVz3ktZyQ7RTbvpmMamqCdj4snqzhnEmvvFAnFwyFM9epWUm)

<img width="1115" alt="Screenshot 2024-03-21 at 09 52 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6a21bebd-e87d-4c6a-9a0f-078e04334ad6">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] when sending USDC from Ethereum (MetaMask) to Solana (Phantom). 


![Screenshot 2024-03-25 at 15 17 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7f3fa8af-82ab-4dd7-bccd-86ac4bd7978e)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1674--wormhole-connect.netlify.app/#
For transaction 0.01 USDC from Fuji to Alfajores, gas estimate instead of gas fee was shown when the transaction was completed.
Attachment:
<img width="1054" alt="Screenshot 2024-04-04 at 08 57 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2889083c-05e8-43ed-9763-9453ae10a790">

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/
For transaction to Solana CCTP route gas estimate instead of gas fee shown when transaction is completed
Attachment:

<img width="1008" alt="Screenshot 2024-04-25 at 10 35 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/88bf3624-6ff7-47dd-a251-8dca9ff50785">

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign, gas estimates are no longer displayed on Confirm transaction and Redeem screens.
