### ISSUE TITLE
[QA] Link to "Sui Explorer" opens error page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1819]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 SUI from Evmos (Leap) to Sui (Sui wallet)
2. Click "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Click on "Sui Explorer" link

* Send from tx: https://www.mintscan.io/evmos/tx/5BBB3AC8C833B474FB2F25A6C592283A670BA6CE59F7D00661BA732F31603915
* Send to tx: https://suiexplorer.com/txblock/Ee4P36aKq86iA8PqbAkp4YLEUasTi22sKFbp8RY5ccH3

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e48822e3-fc23-4552-8f32-bd4d517568b2

## What is the expected/desired behavior
Link to "Sui Explorer" opens transaction details page.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 SUI from [Sui](https://suiexplorer.com/txblock/HYUDcEQ8SF9VM5UWRrH6tBZZ6KnmDssnP68vRxYxMMQM?network=testnet) (Sui wallet) to [Fuji](https://testnet.avascan.info/blockchain/c/tx/0xf9bccc65b059034a1391059d319ec1eddf01ee1c17efed915621ede8ab1f53f5) (MetaMask). 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f7875bce-b40c-416e-b229-0df740bc3bb5)

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 2 WGLMR from Moonbeam (MetaMask) to Sui (Sui). Link to "Sui Explorer" opens error page.
* Send from tx: [Moonscan](https://moonscan.io/tx/0x753ff06c73f068ed4ab3199879aa3f553f96b679dc8955c0b83421038131a2eb)
* Send to tx: [Sui Explorer](https://suiexplorer.com/txblock/8fdnm39D7HTXgu1QkCNS77tw5WWvRHsoDUZb6o9G72Uk)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Tested OK, closing the ticket.
[Sui explorer](https://suiscan.xyz/mainnet/tx/9gvLhj5B5M7hZwzRE8ki93fEt8dEVvbDYfTSXwM2ZMT6) link leads to Sui transaction details in suiscan.xyz
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0813d66e-c279-46f4-86ac-a7c9b7152e83
