### ISSUE TITLE
[QA][Mainnet,testnet] Cannot connect to Nightly wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1821]
Preconditions:
Nightly Aptos Mainnet wallet is enabled

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/

Steps:
1. Select Aptos Network
2. Click on Connect wallet
3. Select Nightly
4. Observe

Actual result: Cannot connect to Nightly wallet ` Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`

Expected result: Nightly wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dfdbbb68-b605-4922-9671-9c52aaab6a5e

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/
Cannot connect to Nightly wallet, ` Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3e91a903-7f70-41e6-9db0-05ea64830e1c

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
Cannot connect to Aptos Nightly wallet
`Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`
Attachment:
<img width="1342" alt="Screenshot 2024-04-02 at 10 49 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/06fc56eb-a72a-4527-8554-c3a190ad1b1e">

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/
Cannot connect Aptos Nightly wallet, `Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect.netlify.app/# 
Cannot connect to Nightly Aptos testnet, `Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9476e264-86af-4ac0-bbb2-c45e11ee67d9

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Cannot connect to Nightly Aptos wallet, `Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`
Attachment:
<img width="1286" alt="Screenshot 2024-04-23 at 10 39 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c144e95-098b-4e0d-92be-e6eab5d88f94">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/
Cannot connect to Nightly (Aptos) wallet.
`pb-index-DrUOIUci.js:727 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.`

**Comment by tsadovska** [comment]
Rechecked the issue. It is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by agodlevska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
Cannot connect to Nightly (Aptos) wallet.
Error: 
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{this._wallet=null,this.emit("disconnect")} could not be cloned.
    at sendToContentScriptRequest (chrome-extension://fiikommddbeccaoicoejoniammnalkfa/assets/utils-BKAwMN_b.js:574:101086)
    at chrome-extension://fiikommddbeccaoicoejoniammnalkfa/assets/inject.ts-DkXpmjRw.js:3:5077
    at new Promise (<anonymous>)
    at Bt.connect (chrome-extension://fiikommddbeccaoicoejoniammnalkfa/assets/inject.ts-DkXpmjRw.js:3:4568)
    at R.<anonymous> (https://wormhole-connect-mainnet.netlify.app/assets/aptos-Bz0A28dV.js:80:73078)
    at Generator.next (<anonymous>)
    at https://wormhole-connect-mainnet.netlify.app/assets/aptos-Bz0A28dV.js:80:70555
    at new Promise (<anonymous>)
    at A (https://wormhole-connect-mainnet.netlify.app/assets/aptos-Bz0A28dV.js:80:70324)
    at R.connect (https://wormhole-connect-mainnet.netlify.app/assets/aptos-Bz0A28dV.js:80:72737)
``` 
Attachment: 
<img width="1440" alt="Screenshot 2024-08-16 at 09 29 57" src="https://github.com/user-attachments/assets/22d8ee5e-2c60-483d-b1c2-63e8bbb30412">
