### ISSUE TITLE
[QA] [Mainnet] Sometimes balance does not load for Injective network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1825]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Select Injective network as source chain
2. Connect Leap wallet
3. Open Assets list
4. Check if balance is loaded

Actual result: Sometimes balance does not load.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/25ffd70c-7105-4f85-833b-adfcf136f1eb

## What is the expected/desired behavior
Balance is loaded.

**Comment by Eiei070922** [comment]
Sir, I don't know how to do this. I have no knowledge about this matter.

ในวันที่ ส. 23 มี.ค. 2024 02:48 tsadovska ***@***.***>
เขียนว่า:

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1780.
