### ISSUE TITLE
[QA] [Mainnet] WBNB contract address on wormhole-connect is different from contract address in Metamask 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1836]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/b05f4e9322/  [Mainnet] with macOS and Google Chrome.

Steps:
1. Select Fantom network as source chain > Connect Metamask wallet > Open Assets list > Check WBNB contract address
2. Open Metamask extension > Switch network to Fantom Mainnet > Check WBNB token details

Asset in Explorer: https://ftmscan.com/token/0xc033551e05907Ddd643AE14b6D4a9CA72BfF509B 

![Screenshot 2024-03-26 at 07 49 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/240fa7d2-5226-41f0-af38-754af9d4231f)

## What is the expected/desired behavior
Contract address is the same on wormhole-connect and in Metamask.

## Notes
Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+) to view similar issues.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) on Avalanche network. Asset in Explorer: https://snowtrace.io/token/0x442F7f22b1EE2c842bEAFf52880d4573E9201158
 
![Screenshot 2024-04-02 at 11 28 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/42b204cd-af91-4c04-8916-cc613d866e1b)

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WBNB (BSC) on Fantom, 0xc033551e05907Ddd643AE14b6D4a9CA72BfF509B
- WBNB (BSC) on Avalanche, 0x442F7f22b1EE2c842bEAFf52880d4573E9201158

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
