### ISSUE TITLE
[QA] [Mainnet] WETH (Ethereum) contract address on wormhole-connect is different from contract address in Metamask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1838]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Select Fantom network as source chain > Connect Metamask wallet > Open Assets list > Check WETH (Ethereum) contract address
2. Open Metamask extension > Switch network to Fantom Mainnet > Check WETH (Ethereum) token details

Asset in Explorer: https://ftmscan.com/token/0x2A126f043BDEBe5A0A9841c51915E562D9B07289

![Screenshot 2024-03-26 at 14 00 46](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9add8a17-20c1-4f0e-abbc-d809d6a8fa20)

## What is the expected/desired behavior
Contract address is the same on wormhole-connect and in Metamask.

## Notes
Issue is also reproducible on Avalanche.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (0.2.12-Pbd3e3109b6) on Fantom network.

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/ [Mainnet] on Fantom.

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WETH (Ethereum) on Fantom, 0x2A126f043BDEBe5A0A9841c51915E562D9B07289
- WETH (Ethereum) on Avalanche, 0x8b82A291F83ca07Af22120ABa21632088fC92931 

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
