### ISSUE TITLE
[QA] [Mainnet] Fee value should have more decimals after comma - OSMO

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1839]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b05f4e9322/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Prepare to send 0.001 WSOL from Osmosis (Leap) to BSC (MetaMask)
2. Check "Source chain gas estimate" value in Preview section
3. Click "Approve and proceed with transaction" button
4. Check Gas fee value in Leap notification

Actual result:
* Fee value on wormhole-connect / Portal Bridge is ~ 0 OSMO ($0.00)
* Fee value in Leap wallet is 0.00270 OSMO (<$0.01)

![Screenshot 2024-03-26 at 14 17 33](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de685d27-f0b9-48e0-8626-71dbecf05792)

## What is the expected/desired behavior
Fee value on wormhole-connect / Portal Bridge should have more decimals after comma.

## Note
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/651

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/2c6f665417/ [Mainnet] when sending 0.01 from Osmosis (Leap) to Kujira (Leap). 
* Fee value on Portal Bridge ~ 0 OSMO ($0.00)
* Fee value on Leap wallet 0.00270 OSMO (<$0.01)

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.
Osmosis network is no longer available in Networks list.

Closing the ticket.
