### ISSUE TITLE
[QA]Status Pending not shown in Wormholescan for transaction in progress

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1851]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/ 

Steps:
1. Prepare to send 0.001 WETH from Polygon to BSC 
2. Click Approve and proceed with transaction
3. While confirmations are loading click on Wormholescan link
4. Observe if status Pending is shown for the transaction

Actual result: Status: Pending is not shown in Wormholescan

Expected result: While transaction is in progress, status Pending is shown in Wormholescan

Comments: Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1486

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f54bc69d-abfe-4f37-a804-ad3a4801e34d

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d81229e2-ca1d-4757-9277-8e1b10c7e4fc

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
For transaction 0.00001 tBTC from Ethereum to Polygon, status In Progress is not shown in View in Wormholescan link
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6002efd2-83ac-4ed5-a0bc-ce44eb64fc6e

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.
Checked following scenarios:
* WETH (Polygon) transfer from Polygon (MetaMask) to BSC (MetaMask)
* tBTC transfer from Ethereum (MetaMask) to Polygon (MetaMask)

![Screenshot 2024-08-21 at 15 40 14](https://github.com/user-attachments/assets/94e07004-cf7e-4d64-8615-1e5336068e6b)

![Screenshot 2024-08-21 at 15 43 29](https://github.com/user-attachments/assets/79e92062-1e49-43cc-9873-ef3d1bc321b2)


Ticket is closed.
