### ISSUE TITLE
[QA] User is able to Add <token> to Metamask while transaction is still in progress

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1861]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/8228d00809/#

Steps:
1. Prepare to send 0.01 USDC from Optimism to Base
2. Click Approve and proceed with transaction
3. While Confirmations are loading "Waiting for Circle attestation . . ." click on View on Wormholescan
4. In Wormholescan scroll to the bottom of the page
5. Click on Add to Metamask button
6. Observe

Actual result: While transaction is still on step "Waiting for Circle attestation . . ." token is shown as added to the wallet through Wormholescan section

Expected result: User should not be able to add token to wallet, while transaction is shown as still in progress on Bridge screen

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d5c63193-1307-4699-842f-d26791ce91c2

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/ed4e22522f/#
While transaction 0.001 W from Solana (Solflare) to Base (Metamask) manual Native token transfer route, is still in progress user is able to "Add to Metamask" through [Wormholescan](https://wormholescan.io/#/tx/1/cf5f3614e2cd9b374558f35c7618b25f0d306d5e749b7d29cc030a1a15686238/15)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fdc51f9b-d3cf-4b4d-aa17-a241e48019fd

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
During "Waiting for Circle attestation . . ." step, it is possible to add token to the MetaMask through WHS.  

Attachment: 

https://github.com/user-attachments/assets/f7cf4e12-0d47-4571-955b-94780ca8bd87
