### ISSUE TITLE
[QA] Transaction failed with "Transaction was submitted but was not yet found on the chain" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1862]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/8228d00809/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.00001 WMATIC from Injective (Leap) to Osmosis (Leap)
2. Click "Approve and proceed with transaction" button

Actual result: Transaction fails. 

```
Error: Transaction with ID BD7083A6B8B2DD524A3F422F9F00D151CAA8BB46B3B31F3BDDB9CBBB6291E9A2 was submitted but was not yet found on the chain. You might want to check later. There was a wait of 60 seconds.
    at ro (pb-index-Bn_4pseu.js:490:109234)
    at ro (pb-index-Bn_4pseu.js:490:109647)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fb4db95c-8c08-4901-a5cd-faa3bcfc047e)

## What is the expected/desired behavior
Transaction proceeds without error. 

## Note
Noticed only once during testing.

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is not reproducible with the scenario mentioned above - sending 0.00001 WMATIC from [Injective](https://explorer.injective.network/transaction/03B6AE0141F2BD385E47259BC74A2A7A7E22A79C43F2D5EE61AE85202087691B/) (Leap) to [Osmosis](https://www.mintscan.io/osmosis/transactions/CF21B0979B718C8E1D564065EAB10682795D0C7AFD8A2B5EFB4E0841776C2F6D) (Leap). The transaction was successfully processed without any errors.

Closing the ticket. 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-21 at 12 49 42" src="https://github.com/user-attachments/assets/d9fcaa5d-2626-44a2-8fee-cee1050bba8c">
