### ISSUE TITLE
[QA] [Mainnet] WBTC (Ethereum) contract address on wormhole-connect is different from contract address in Metamask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1864]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Select BSC network as source chain > Connect Metamask wallet > Open Assets list > Check WBTC (Ethereum) contract address
2. Open Metamask extension > Switch network to BSC Mainnet > Check WBTC (Ethereum) token details

Asset in Explorer: https://bscscan.com/token/0x43359676E1A3F9FbB5de095333f8e9c1B46dFA44

![Screenshot 2024-04-02 at 15 10 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/83af035e-16af-4774-8079-1c0e6adbc80b)

## What is the expected/desired behavior
Contract address on wormhole-connect and in Metamask is the same.

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WBTC (Ethereum) on BSC, 0x43359676E1A3F9FbB5de095333f8e9c1B46dFA44

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
