### ISSUE TITLE
[QA] [Mainnet] APT contract address on wormhole-connect is different from contract address in Metamask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1865]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Select Moonbeam network as source chain > Connect Metamask wallet > Open Assets list > Check APT contract address
2. Open Metamask extension > Switch network to Moonbeam Mainnet > Check APT token details

Asset in Explorer: https://moonscan.io/token/0x25331575641d35D9765e1934acC8F0991c58e904

![Screenshot 2024-04-02 at 15 59 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1f0dbe99-7a55-4a35-8b03-c1540a1357f3)

## What is the expected/desired behavior
Contract address on wormhole-connect and in Metamask is the same.

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- APT (Aptos) on Moonbeam, 0x25331575641d35D9765e1934acC8F0991c58e904
- APT (Aptos) on Avalanche, 0x43c588459b3243fA541B98CC4B2E995b3de553A2

Ticket can be closed after changes are merged on https://portalbridge.com/ [Mainnet].

**Comment by agodlevska** [comment]
Changes are merged on https://portalbridge.com/, closing the ticket.
