### ISSUE TITLE
[QA] Token registration warning is shown when asset is not selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1870]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) with macOS and Google Chrome. 

Steps:
1. Prepare to send wstETH (Polygon) from Polygon (MetaMask) to Ethereum (MetaMask)
2. Change destination chain network from Ethereum -> Avalanche -> BSC 
3. Check if asset is selected in To section
4. Check if token registration warning is shown

![Screenshot 2024-04-03 at 11 13 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9ee8f95d-51fe-4043-beb4-aee621edbf7b)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/377fefc2-c058-40e1-ac8a-3379acb95d26

## What is the expected/desired behavior
Token registration warning is not displayed when asset is not selected.

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/. 

Warning _"This token is not registered, you must register it before you continue. Newly registered tokens will not have liquid markets."_ is shown when asset is not selected.

Attachment:
<img width="1440" alt="Screenshot 2024-08-21 at 12 52 57" src="https://github.com/user-attachments/assets/49b35021-b932-4bb8-ae50-2764e4ca22b1">

**Comment by tsadovska** [comment]
Scenario is no longer reproducible on https://portalbridge.com/.
* wstETH token is not displayed in Tokens list on BSC
* warning to register token is not displayed

![image](https://github.com/user-attachments/assets/003dce32-d98c-4c51-92ff-b90ac754ea12)

Ticket is closed.
