### ISSUE TITLE
[QA] Transaction was completed automatically after user switched to Manual Claim

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1871]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/8228d00809/#

Steps:
1. Prepare to send 0.003 BNB from BSC to Polygon
2. Select Automatic transaction
3. Add some Native gas
4. Click Approve and proceed with transaction
5. When possible click on toggle button for Manual Claim
6. Observe

Actual result: Pop-up to switch networks was shown after user clicked on Manual Claim toggle button, but transaction was automatically completed

Expected result: By switching to Manual Claim, transaction is confirmed manually

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8c6f87c4-1dee-40f8-983d-0c295c32dbf2

**Comment by kev1n-peters** [comment]
The relayer redeemed the tx before manual redemption could complete - this is a race that we can't really do anything about

**Comment by AigaD** [comment]
Closing as per comment above.
