### ISSUE TITLE
[QA] USDC.e instead of USDC shown as adding to Metamask wallet from View on Wormholescan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1876]
Preconditions:
Metamask wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1674--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 USDC.e from Alfajores to Fuji
2. Select Automatic transaction
3. Click Approve and proceed with transaction
4. When transaction is completed click on View on Wormholescan
5. Scroll to the bottom of the page
6. Observe the token shown at the Redeem amount
7. Click on "Add to Metamask" button
8. Observe the token pop-up when token has been added

Actual result: USDC.e is shown instead of USDC

Expected result: Added token should be shown USDC for Fuji network 

Attachment:
[Wormholescan link](https://wormholescan.io/#/tx/0x1d85f21308495ec4679c2af35d8011acd3f68cb586c99af804dc8559cbf14c83?network=TESTNET)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/01d2e914-4cf3-42e2-8ee4-75f63feddf87

**Comment by aadam-10** [comment]
fixed on wormholescan side
