### ISSUE TITLE
[QA]Some transactions first fails due to insufficient balance when balance is available

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1879]
Preconditions:
Metamask / OKX wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1674--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 USDC from Fuji to Alfajores
2. Select Manual transaction
3. Click on Approve and proceed with transaction

Actual result: Transaction fails, reason `Error: Insufficient token allowance` when users wallet has enough balance

Expected result: Transaction is started

Comments: Reproduced this 2 times during testing, from 8 tests. When clicking again on Approve button, transaction did start

Attachment:
<img width="1338" alt="Balance2" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3b7b9f5c-cf55-4b75-8a87-b7064ae9d23b">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/69949eec-abb2-4dc8-95bd-f6396acae27b

<img width="1306" alt="Screenshot 2024-04-04 at 11 18 29" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ecf17e15-ff42-4b67-8c0f-09a6a0c6f4a2">
<img width="1273" alt="Screenshot 2024-04-04 at 11 18 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/333d0a8b-540a-4f54-a026-9c4f2310c075">

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1832

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://wormhole-connect.netlify.app/ [Testnet]. 
USDC transfer from [Fuji](https://testnet.avascan.info/blockchain/c/tx/0xdccb6c856c96430453cc1bd0166edede5c1b266d3f1c7b6f55ada653799e6566) (MetaMask) to [Alfajores](https://explorer.celo.org/alfajores/tx/0xc3763b890adb88af26962abdde319c7e109ec7b9cfce272dc47f03a978f04479) (MetaMask) was successful. "Error: Insufficient token allowance" does not appear. 
Ticket is closed.
