### ISSUE TITLE
[QA] Ethereum icon instead of Coin98 Wallet icon is displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1891]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. User has only Coin98 extension installed and "Override Wallet" option is enabled in Coin98 wallet Settings
2. Open https://wormhole-connect-mainnet.netlify.app/
3. Select Ethereum as source chain
4. Click "Connect wallet" button

Actual result: Ethereum icon instead of Coin98 Wallet icon is displayed.

![Screenshot 2024-04-05 at 18 41 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a8967039-ab2a-48e0-b951-a4e89b4c9edb)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8482fab1-d1fd-4740-b07b-8fd02f2f2e8f)

## What is the expected/desired behavior
Coin98 Wallet icon is displayed.

**Comment by AigaD** [comment]
Reproduced also from: https://portalbridge.com/
Coin98 wallet is shown with Ethereum icon
Attachment:
<img width="959" alt="Screenshot 2024-04-29 at 11 06 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c548989e-7bc3-4af2-8025-f88a1e7a1b54">

**Comment by tsadovska** [comment]
Issue is no longer reproducible, Coin98 wallet is not displayed in Wallets list. 
Checked on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsOEACQi%2FQODQ9R8AYRtORKiUsPdhNhMbCJ0wfV1IWFgY9QYAClBvb1hEVGhIBjoy5vMAORsnHzsLdwN0rR7msCbpuYBjJkJITCwjWCZoASoccim5%2FEg8SWRVgAYAD2gAITF06ABOPAeARgBmMQeAFjOzoyMAOwAVmgADM3i97gAOABGYjeXy%2BADYAEwGM4vPAveYvPZzOatdorbCXMxnGFQpEPV7zVEvWFvJE4sQvB4GL54FGPIwws7zIyMs5Im5fKF4%2FHNGRBBjzaAEABuW0mErmsxV0zwYjEAiE5wuQKBoIBUJRZzeQIB5heALMLyM6RhoqMDyBbKBRiRbwBMJMJhdSLESJM4vVkv8AAdoKskMgcCwADbQEOhpT7aYAXS8EtT6rVKsWy1WJiCrV2WZVh2OSpJFyRULE1xRoLOQLMnLEAIBxlBDyhL1BYhRMOgbxRSKR7x%2B8weKNnJmuyYlhI6epRJgBbzeZxd1yhZzJXxhb1hZwMLz56ShUK%2BQJRHI%2B24pjLwi%2FxUs6soV1e0oe8ed%2FmraoIXQ1rCXwAs2XIAtAprWl88wAkieA9uemrzGcmpQngh5ml8Tbwa%2B6qwBGUbYDGcaIImhH4jmoaZmmEC0XM9ESlY4iIHY8AMLARg2HEyoqv%2B%2BIFkQqzrJs2xlgx3iViceowt8WEPMeKIAoGWEmiYSJAu8ZgssaDxIl8BjYVCEEwdcBgPNRkptCuNYQW8DzpECfYmK6QLXECbzzEC8wwqyMLokeoL1mYTLKe6KLpHgZw2S0yDSp%2BiqnGAP6%2FjM0lzIBOogVgpIvGY6TpC80DCmIeCNm50Bwq8Ao6UC25vCYLzGG5KJ%2BXF5a%2FsRkbRigFFUd1KpMSqLEjcNzRCQsSyidg1wyvFECydW%2BW1r2LzuXSVKQtcoICgYYgGLeXxiIC56ITCAIPCY%2B5nKpYqTdMy7EmtY6%2BdAGInYOHoonuZiiiYKK%2BWcoJaQY0DQbezoTpCS1gO%2BMpyilAm%2FtNKo5cB8kjuun11gCKJGGcYhaekBiWiY5rXACeDYdcAWIki4zUpS8Nhn1ZEDQmSZPXMo0SuN2ZPYL0zCKj%2BLo80Imve4lFBC%2BvMyfLcnYAMsBtogBgAFJMO0cTQHgABqFhxJA%2FhMPAMKcH0Zh9Eiwi8Nc4ZxKgcTXDYtIdvKVgANLwy9qxQkChvXCYACKABa6QPDYEeoKCeDhrA1zCAAVvKFjwACACaMIR6n%2Fi3uFOCp7AnAAOKp9xYdmDgYf%2B4lH7I9%2BWV%2Fq3zSY7qqs2OreCazresG8bpvm5b1u2%2FbjvO677uewC3t%2B4rBIkf1sbc2zihL2AIsSgAjlQiDqKlWB9LvgYABq72YUJWDCDDpFQ5dQj4VjCMIVCcJSQJ9IbSKpw4LwfAwnPtAH2Fx2RxF9treK%2FNpiS28NLMSGwtjQB2PDFax9LjoQJtcQqRhwSMmgIdaAroDyGWpPgr40AoTFjdN8AGj1W4BxrNcUGxY9y%2FCvMKC0JhKRalvEZBSrkhwoj0mZGEQ5XgNySs3VK6U0bt28J3PKlwDAwgNF8GcHZWSnheDCPARgoRFRhETJyLxIRfAFICPC%2BM%2BQbwgL1UiWByLry3oxLeO9piwKmq3RB2AzDIBhAQGQaCt4YL1N5TcYh9zzHChyG8%2B4tRBmgOuJmTN3jAnXGOdI1xRRfH9nZV6lxWFgzwBws4XCSGWj4WIARh4XQmgkWI70kjcRb0RslFuGVMrdIgMovUZ4ylmGuFST691xzUOpq8LEnl0jgR0l8F43kzCNRvHgJE9iEYr05mvSiPNFHeIzIrQ5EB4EQD8VgJwScCA4AIAwKSv5wk1kxF8FqeBrqgxRM1UEClOwokMkyEZlMAzpEDK5M0bxoDvAKUSPUJT2G%2FAqZSKpvCAy1LHPU4RTSxDiNadIpuX45GKLORqLUuU9QPCCrCb0t4ATpABmVDcUJ5iWUqiTHS6RZzIiRMCJEZwNxiE2Y41eg19ndJOd4TxzQJUkoudcPADAxWhieWtSJD4zCxKMthRqelAwmBSYhAw6SvRAiyUiHJeSYX2TWvCspiLKk8JqXUoRjTRE4paQpNpTDG5I0JeLXMii%2BlkqxjWQZRiRkPDGWOYUUIpmYiWdcOZwIXiLOWasoE6yhXbOcVzPZG8JUQCld4Q5njRoKAAJReHopQKgiqHDQDEIIAgvBiQhPCCASgL176IEgKCZt3RmhcR4nxO%2B8wB3THaP4aM3FeJxFHa%2BBg%2FgcAwkotO4dcRXxHFgF%2BdIs1XoLXmK%2BF6bAxDjpmoWeai0nr9JrO9EEX07w%2FVRP9QGwNGpgyZpDEhhNDLmPSK%2BWBBB5g9tWEwao4YugAHpIMKsVbABguhgNEEkPMVAiBEOIBwJBpDnRIM3KrAwSD9IoQIkg9xIIFVkBiEg0O2duhwyQF4K%2BHD5doCocQCe6MiVwyRjEAAWm4nAJgzHKIoFWAAYjeGYMwzVgzDUbfMfD8YQL0nLKNYQDA5ZHDPd4SdqwNNaYVlMRdy7V3YGEJuvA27FS7ovVgWW8Z5ZHsKZxnpwk92rAc0569wau5YCDiHcOUcY5xwTknFO6dM45zzgXIuSIS5l0rtXWu9dhqAeA69MDsAIPoGg7BuACGcMobQxhrDOHCP4ckIR80FSARkdgBRvAVGaOYeQNzOw8Y%2BAcVBFQeM8Y7DAc68gOwyBeAwjsKaX44YLh2AJjxggdgfmISQvMIOeB6OMYAPzWgqXWKELp8nDRY2xtDrmc27KGlMBTSmQJIjU%2BWYQQmUE7B0xAPT5mnuSQXUuld8Z9OWes9AWzc01jIK%2B8NY9p63PnpB%2BJZ7Dz8Q3ptWwu1nDkWOrRc6hpIjmkSM9QB4aQGQPYCyzlvLQgCsYeQyd9DwGyuICIBV%2FAVXIM1bMvVxrzWkA4Da3sjrXXFu9f64NlAI2xsTcRdN2bKJ5uLauuOPAq2M0bd4NtgEu2rwHZE0QVj7GzsuLzfJtjN3MCqbKOpprQSQk4Fe2Ad7WBhCW%2BCbIBHzQTO%2Ff%2B8NLdO6PP%2BMCc70JUxIe2%2FOb7rAASrcu%2Bokj4pKPykOuqZjjFLqcfurx1ItLhOMugfA1BmDFP4NU8YzT0r2GGe4cq4IVnjV2fkcgJR6j3PeeJn57wbrQuBuieG6N8bk2zhS7m%2BGBbS2FdK%2FWwx1XO3KSa6BIdqYx29dQ%2FO6K18138DKdN1Ce7ZRhCIGubc%2B5tv7e7%2F33c133h3dmYdwDn3dmrnboP%2BfhxLmofowuffm5Z%2Fo%2B%2BZURcW18f0dE9%2BFk9sdsVcV8dM8pgidMtc9ct884NCty9itadMMy9Gc8Nmcq82c6s68G8Wsed2tOs29Bc%2BtO8hsxde9JcZtB9h95cVs1sVc1cNd9tZ9tdIBddTsl8DdLs5g188AN8wAzdpUHt9FFUj9oAp1zNRClU3cfsr8LMvcrNb8Qd5VFVnMiRXM38w9VCZDSUgI%2FNY9SkADuEgD0VBFQC3VwCM8ph0ticsBSc898tC8isS86c0CK9MDqsa8cCGt68mtG9WtCCBcetSCRdu9xc%2B8B8Zch85dltFcGCJ8mDp8WC58Fhy8OCOMuDc0eDpg%2BCBChDi0vBUwFAABuEAIAA). "Set Coin98 Wallet as default" option was enabled in Coin98 extension. 

![image](https://github.com/user-attachments/assets/739631ec-5f00-4f32-907d-8585292e9bfe)

![image](https://github.com/user-attachments/assets/32f4c752-7d2b-4e86-8126-ad6898cde7c3)


Ticket is closed.
