### ISSUE TITLE
Wallet options flip back and forth sometimes

### ISSUE THREAD

**Issue by artursapek** [wormhole-foundation/wormhole-connect#1894]
1. open https://portalbridge.com/
2. Install Rabby & disable Metamask
3. Select Ethereum as source chain, choose Rabby
4. Select Fantom as destination chain, open wallet menu and wait (could be any EVM chain)
5. Notice that WalletConnect & Rabby options flip back and forth once - kinda weird and makes it easy for someone to misclick

**Comment by tsadovska** [comment]
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/252.
