### ISSUE TITLE
[QA] Balance in "To" section is not loading automatically 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1897]
## Describe the current behavior in detail
Tested NOK:
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Tested OK:
* https://portalbridge.com/ [Mainnet]

Checked with macOS 14.2.1 (23C71) and Google Chrome Version 123.0.6312.107 (Official Build) (arm64). 

Steps:
1. Select BSC as source chain
2. Connect MetaMask wallet in From section
3. Select BNB asset
4. Select Polygon as destination chain
5. Connect MetaMask wallet in "To" section
6. Check if the balance is loaded in the "To" section

Actual results:
* Balance in "To" section does not load automatically even after 2 min. 
* Balance is loaded only after user clicks on Asset in "To" section.

Attachments:
Behaviour on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] - Tested NOK:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0d1f095d-f151-47aa-bbc3-3ee2da23329e

Behaviour on https://portalbridge.com/ [Mainnet] - Tested OK:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d2259ac4-b4d6-445d-9006-b85c47d5d047

## What is the expected/desired behavior
Balance is loaded in "To" section after asset is selected in "From" section/

## Note
Issue is also reproducible with other networks, for example FTM transfer from Fantom (MetaMask) to Avalanche (MetaMask).

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/#
Balance at sending To section is not loaded automatically when token for the transaction is selected
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/86ab5254-61a2-4d63-b890-7644eade76f2

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/ed4e22522f/#
Balance at sending To section is not automatically loaded for the asset selected for the chain
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7435519b-05b8-41b5-82ff-33e902a74b13

**Comment by AigaD** [comment]
Reproducible from: https://portalbridge.com/
Balance in To section is not loading automatically
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/462e2fef-5fd9-4d05-bcce-9b0a0df5c6ef

**Comment by kev1n-peters** [comment]
Should be fixed in https://github.com/wormhole-foundation/wormhole-connect/pull/1982

**Comment by tsadovska** [comment]
Tested OK on https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/.
Tested NOK on https://portalbridge.com/ (Portal Bridge: v0.2.13-0a2b3508ac, Wormhole Connect: v0.3.5).

Issue will be rechecked after https://portalbridge.com/ is updated to Wormhole Connect: v0.3.6.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ (Portal Bridge: v0.2.13-eb254ccb71, Wormhole Connect: v0.3.9). 
Ticket is closed.
