### ISSUE TITLE
[QA][Mainnet] USD equivalent value is not shown

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1898]
Precondition: 
Metamask wallet connected

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.001 WFTM asset from Arbitrum to Solana
2. Observe if USD value of the asset/fees are shown

Actual result: USD equivalent of all fees regardless of designated currency is not shown

Expected result: USD equivalent value is shown

Comment: Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1436

Attachment:
<img width="1063" alt="Screenshot 2024-04-09 at 11 42 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c1d2627-5c1c-4245-9b71-6165a792a9e7">

<img width="685" alt="Screenshot 2024-04-09 at 11 41 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/220200d8-0192-4818-8ec2-69cfbca2daf1">

<img width="522" alt="Screenshot 2024-04-09 at 11 45 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8efd9926-bc2b-459b-9df7-392ac466fd3a">

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKAwgFEAMgHkzYAL4g3QA). 
```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'celo',
    toNetwork: 'fantom',
    token: 'CELO',
  }
}
```


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eccda329-3add-4103-ab84-1ae3262c52e4)

**Comment by AigaD** [comment]
Checked from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D)
```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: '',
    toNetwork: '',
    token: '',
  }
}
```
USD equivalent value not shown when selected to send 0.01 BNB from BSC to Avalanche

Attachment:
<img width="1007" alt="Screenshot 2024-05-02 at 09 33 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e85fb29e-2f1e-4d8c-b1ac-98c24b1fba0d">

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/.
USD equivalent value not shown when sending 0.1 MATIC from Polygon to Moonbeam. 

Attachment:
<img width="1440" alt="Screenshot 2024-06-18 at 13 09 29" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/f4f5c2cc-9b26-454d-95c6-f6a7f3a109c3">

**Comment by agodlevska** [comment]
Reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
USD equivalent value not shown when sending WMATIC from Moonbeam (MetaMask) to Fantom (MetaMask). 

Attachment: 
<img width="727" alt="Screenshot 2024-08-23 at 12 00 06" src="https://github.com/user-attachments/assets/298459d9-231b-44ae-b204-e25f2ff07e26">

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/.
All scenarios described above have been tested and none of them reproduce anymore, USD equivalent value is shown. 
Closing the ticket.
