### ISSUE TITLE
[QA][Mainnet] SUI contract address is different than contract address shown in Metamask

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1900]
Precondition:
Metamask wallet connected
SUI token available for Ethereum network

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect Ethereum network
2. Click on assets
3. Search for SUI token
4. Open Metamask wallet
5. Search for SUI token
6. View token details
7. Observe

Actual result: SUI token address shown in Metamsk ( 0x84074EA631dEc7a4edcD5303d164D5dEa4c653D6 ) does not match what is shown in Wormhole-connect, also the SUI asset cannot be searched by the token address

Expected result: Token addresses match

Comments: Click [here](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+contract+address+is+different+on+Wormhole-connect+and+on+Metamask) to view similar issues

Attachment:

<img width="1122" alt="Screenshot 2024-04-09 at 14 26 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f223b83a-3130-4b23-ac96-4718280a61a6">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
SUI contract address is different in Wormhole-connect and Metamask for Klaytn network
Attachment:
<img width="953" alt="Screenshot 2024-05-08 at 13 44 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/41144d3f-5e8b-4285-b094-138fca8bafdf">

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- SUI (Sui) on Ethereum, 0x84074EA631dEc7a4edcD5303d164D5dEa4c653D6
- SUI (Sui) on Klaytn, unable to check, token address are not displayed for Klaytn network

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/094add29-4193-4391-9c9d-8b563ee7009b)



![image](https://github.com/user-attachments/assets/cc8bf466-d0e1-4e3b-9aa7-e618ba285daf)

Closing the ticket.
