### ISSUE TITLE
[QA] "Gas fee" value on Redeem screen should have more decimals after comma - EVMOS

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1902]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0001 CELO from Evmos (Leap) to Avalanche (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Check fee in Leap notification and approve transaction
4. Check "Gas fee" value on Redeem screen
5. Open MintScan and check "Fees" value

Actual result: "Gas fee" value is 0 EVMOS. Send from tx: [MintScan](https://www.mintscan.io/evmos/tx/A6DBE462AFCF329E69C926AB2CFA6B79D6DA69065ACD3A9D8CC0E4D3CE4DAC37)

![Screenshot 2024-04-09 at 16 10 35](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/341f4ebc-0e9a-47f1-a97e-3675f30c821a)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7dfd02c4-3998-475c-8a40-62d2e0696ac3)

![Screenshot 2024-04-09 at 16 13 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/56796a76-c664-4789-838b-8b403e5efaee)

## What is the expected/desired behavior
"Gas fee" value on Redeem screen should have more decimals after comma 

## Note
Linked https://github.com/wormhole-foundation/wormhole-connect/issues/651

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] when sending 0.001 SUI from Evmos (Leap) to Sui (Sui Wallet). 
* Send from tx: https://www.mintscan.io/evmos/tx/F5117B6A5F068F98B5A6E274A9361158906C11D05F840E5A38C0940D413C25A0
* Send to tx: https://suiscan.xyz/tx/59YXHXMoDNSybusXWkqCTFc8idx9fwHkRGHLwWhE3Whd
* Link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38452)



![Screenshot 2024-07-01 at 15 22 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/69c603d4-315a-4a95-9eb4-f7a6877ebba9)

**Comment by agodlevska** [comment]
Still reproducible on https://portalbridge.com/ when sending 0.05 WMATIC from Evmos (Leap) to Kujira (Wallet entered manually).

- Send from tx: [Evmos](https://www.mintscan.io/evmos/tx/E9640423E1BBAE78752D5466A1D5311E7093D2D026F2708839C786D4DB63DF20)
- Send to tx: [Kujira](https://finder.kujira.network/kaiyo-1/tx/0E056C6F2AC460367D7D50F7A6D7FC1909CBB385F75587160820C5D59A80F2F4)

Attachment:
<img width="848" alt="Screenshot 2024-09-04 at 11 02 02" src="https://github.com/user-attachments/assets/72e05959-5124-461e-9b5d-8f23422f7324">

**Comment by tsadovska** [comment]
Closing the ticket, because Cosmos chains are no longer available on https://portalbridge.com/.
- Portal Bridge version: v0.2.15-8477ae26d0
- Wormhole Connect version : v^1.0.0-beta.1-development
