### ISSUE TITLE
[Task][CCTP] Update Polygon CCTP Mumbai to use Amoy

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1904]
*Task*
Polygon CCTP Mumbai has been deprecated. Polygon CCTP Amoy will be the testnet to use going forward.

*Requirements*
- Domain = 7
- [ ] TokenMessenger: Testnet 	[0x9f3B8679c73C2Fef8b59B4f3444d4e156fb70AA5](https://www.oklink.com/amoy/address/0x9f3b8679c73c2fef8b59b4f3444d4e156fb70aa5)
- [ ] MessageTransmitter: Testnet    [0xe09A679F56207EF33F5b9d8fb4499Ec00792eA73](https://www.oklink.com/amoy/address/0xe09a679f56207ef33f5b9d8fb4499ec00792ea73)
- [ ] TokenMinter: Testnet      [0xE997d7d2F6E065a9A93Fa2175E878Fb9081F1f0A](https://www.oklink.com/amoy/address/0xe997d7d2f6e065a9a93fa2175e878fb9081f1f0a)

*Documentation*
- https://developers.circle.com/stablecoins/docs/evm-smart-contracts

**Comment by Lu-Derik** [comment]
When could Wormhole support Polygon Amoy testnet? All addresses listed here for Polygon testnet seem not working:
https://wormhole.com/docs/build/reference/contract-addresses/
