### ISSUE TITLE
[QA] Error "Token Bridge Relayer contract for domain optimism not found" appears in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1910]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Open https://wormhole-connect-mainnet.netlify.app/ or https://portalbridge.com/  and open Console
2. Select Optimism network as source chain
3. Connect MetaMask wallet in "From" section
4. Select Arbitrum network as destination chain
5. Connect MetaMask wallet in "To" section
6. Select wstETH asset 
7. Check if an error is appearing in the Console

Actual result: Error also appears after Amount is entered or changed. 

```
Error: Token Bridge Relayer contract for domain optimism not found
    at EthContracts.mustGetTokenBridgeRelayer (main-BIApWWvg.js:319:77368)
    at EthContext.getRelayerFee (main-BIApWWvg.js:319:88479)
    at RelayRoute.getRelayerFee (main-BIApWWvg.js:327:138877)
    at RelayRoute.isRouteAvailable (main-BIApWWvg.js:327:133688)
    at Operator.isRouteAvailable (main-BIApWWvg.js:327:125246)
    at main-BIApWWvg.js:524:83605
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eb7f9549-0567-4ecf-af0d-2ee3b07def94

## What is the expected/desired behavior
Error does not appear. 

## Note
Similar error occurs on other chains.

**Comment by DevMac9990** [comment]
I found this problem agin ,can any one help me ,tanks
