### ISSUE TITLE
[QA][Mainnet,Testnet] Rabby wallet is not switched when Bitget wallet is enabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1914]
Precondition:
Bitget wallet enabled in extension
Rabby wallet is installed

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/# 
https://wormhole-connect.netlify.app/#

Steps:
1. Click on Select network
2. Select any EVM network (e.g. Fantom)
3. Click on Connect wallet
4. Observe that Metamask is present
5. Flip to Rabby wallet in extensions
6. Click on link to refresh the web page
7. Repeat steps 1 - 3
8. Observe

Actual result: Metamask wallet instead of Rabby wallet in shown in Connect wallet list, when Bitget wallet extension is enabled

Expected result: When flipped to Rabby wallet, Rabby wallet is shown in available wallet list

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3b8caa23-0c7c-478d-afb9-efe739930db6

**Comment by agodlevska** [comment]
Issue is no longer reproducible, when Bitget wallet extension is enabled user can choose any wallet without any restrictions. 
Closing the ticket.
