### ISSUE TITLE
[QA] [Mainnet] WAVAX contract address on wormhole-connect is different from contract address in Metamask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1918]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Select BSC network as source chain and connect MetaMask in "From" section
2. Open Assets list
3. Check contract address for WAVAX
4. Open MetaMask extension
5. Check contact address for WAVAX on BNB Smart chain

Actual result: Asset in Explorer: https://bscscan.com/token/0x96412902aa9aFf61E13f085e70D3152C6ef2a817

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4632cec7-d39a-4072-adcb-fc17fd61fd8e)

## What is the expected/desired behavior
Contract address on wormhole-connect and in Metamask is the same.

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/ [Mainnet] on Moonbeam. Asset in Explorer: https://moonscan.io/token/0xd4937A95BeC789CC1AE1640714C61c160279B22F


<img width="891" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cb994156-6182-48b8-9c15-67d34edc2ace">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] on Scroll network. Asset in Explorer: https://scrollscan.com/token/0xC043c8A3672f397e7b52bF0a04F47d6f1aA952Ed

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/189a8ddc-4dc1-43ea-8252-4caf1c9f3b32)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/bceadc8c64/#
WAVAX contract address on Portal Bridge Blast network is different than the WAVAX asset available in Blast network in Metamask
Attachment:
<img width="1164" alt="Screenshot 2024-05-07 at 12 05 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5792154c-3329-4449-9c2c-f0ce841924f3">

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- WAVAX (Avalanche) on BSC, 0x96412902aa9aFf61E13f085e70D3152C6ef2a817
- WAVAX (Avalanche) on Moonbeam, 0xd4937A95BeC789CC1AE1640714C61c160279B22F
- WAVAX (Avalanche) on Scroll, unable to check, token address are not displayed for Scroll network

Blast network is not displayed in Networks list on Portal Bridge.

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/712d941311/. 
Closing the ticket.
