### ISSUE TITLE
[QA]Incorrect token information shown in Wormholescan when sending wrapped asset

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1922]
Precondition:
Metamask wallet connected at sending From section
Solflare wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 0.01 WSOL from Polygon to Solana
2. Select Automatic Route
3. Click on Approve and proceed with transaction
4. Click on "View on Wormholescan" link when possible
5. Observe Source chain amount information

Actual result: Asset that was sent was WSOL, but on Wormholescan it was shown as SOL

Expected result: Wormholescan shows if wrapped asset is sent

Attachment:
[Wormholescan link](https://wormholescan.io/#/tx/0x19b3e83c6f0db9aeba29a7644b15a9d5bbeec943006df73bee7752863ccc0fe7) 
[Polygonscan](https://polygonscan.com/tx/0x19b3e83c6f0db9aeba29a7644b15a9d5bbeec943006df73bee7752863ccc0fe7)
[Solscan](https://explorer.solana.com/tx/5EqCZSrSkDFDuzbnfgHNkik1vanKgD6mrLJvCYwWzS2nbKmBWcSiMmvwtEyQGiqpLcJHfciNXM2mabPZzA16eB4M)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d15625c3-069e-44ee-9896-992bd15c4698

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/321a610744/ when sending WSOL from Solana (Solflare) to Moonbeam (MetaMask). 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-21 at 17 09 09" src="https://github.com/user-attachments/assets/11eb7ea0-bb66-4c83-b8d3-7125e45a5863">

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/ when sending 0.001 WSOL from Solana (Phantom) to Moonbeam (MetaMask).

- [Wormholescan](https://wormholescan.io/#/tx/21QUG8UD2KLSsneGDAzuLVJPXg121jraG1skpoabQjgFrxK4xN8eXZn1rRbaPM6sX3SwKKFnScgqwbCmfWr2qybC)

Attachment:
<img width="1440" alt="Screenshot 2024-09-23 at 16 36 01" src="https://github.com/user-attachments/assets/91a9640a-9cbf-4cde-af2d-89b4537285f4">
