### ISSUE TITLE
[QA]Native gas token is sent even, when user has not had access to Native gas section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1923]
Precondition:
Metamask wallet connected at sending From section
Solflare wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 0.01 WSOL from Polygon/Fantom to Solana
2. Select Automatic Route
3. Click on Approve and proceed with transaction
4. Wait until transaction is completed

Actual result: Native gas token is sent/shown when for the automatic bridge transaction the Native gas section was not offered

Expected result: Native gas token section is not sent if user has not selected it in Native gas 

Attachment:
[Polygon scan](https://polygonscan.com/tx/0x19b3e83c6f0db9aeba29a7644b15a9d5bbeec943006df73bee7752863ccc0fe7) - 0x19b3e83c6f0db9aeba29a7644b15a9d5bbeec943006df73bee7752863ccc0fe7 
[Fantom scan](https://ftmscan.com/tx/0x8fdc69d370616016d69e67094c8c7f622a1fd78fa2fd5f1fb3eee7e3f94c89d3)

<img width="1071" alt="Screenshot 2024-04-12 at 09 12 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/63ac590c-5ae8-4aa2-9e39-6d236c0312a3">
<img width="1000" alt="Screenshot 2024-04-12 at 09 13 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/848b7898-acb9-47f9-9c54-f40e267065f2">

<img width="746" alt="Screenshot 2024-04-12 at 10 30 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/10ee173d-59ca-4d83-a66e-18c08afce35e">
<img width="1052" alt="Screenshot 2024-04-12 at 10 35 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/10893242-8608-48bc-86a9-88bf11c2984d">

**Comment by tsadovska** [comment]
Issue is reproducible on Portal Bridge (0.2.12-6088580833) https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. "Native gas token" field is displayed in "To" section when sending WSOL to Solana. 


<img width="1090" alt="Screenshot 2024-04-12 at 15 12 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8c8a8f32-9ef9-428c-9142-63aa075f76a1">

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Reproduced also when sending 0.01 WBNB from Avalanche to BSC using automatic bridge
Attachment:
<img width="696" alt="Screenshot 2024-04-12 at 15 26 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ec22484f-72b8-4362-b93e-032a8f938905">
