### ISSUE TITLE
[QA]Amount does not match in all sections

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1925]
Precondition:
Rabby wallet connected

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/

Steps:
1. Prepare to send 1.5 USDC from Base to Arbitrum
2. Observe USDC value in Preview section, Native gas section, Route section

Actual result: The amount is not matching, in Native gas section the amount is shown lower that the value shown in Preview and Route sections

Expected result: The amount is shown the same in Preview section, Native gas section, Route section

Attachment:

<img width="964" alt="Screenshot 2024-04-12 at 12 55 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ded724a4-a56f-430b-bbcf-cbfb458647e0">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Closing the ticket. 

Attachment:
<img width="555" alt="Screenshot 2024-09-10 at 11 36 18" src="https://github.com/user-attachments/assets/29bae8d6-8db5-4f50-88f3-85d1dece1808">
