### ISSUE TITLE
[QA] [Mainnet] Amount in Route section goes past dedicated area when entering multiple digits

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1929]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect Ethereum network at sending Form section
2. Connect Metamask wallet
3. Connect Fantom wallet at sending To section
4. Connect Metamask wallet
5. Select ETH asset
6. In the amount field enter 40+ digits
7. Observe Route section

Actual result: Amount in the Route section goes past the dedicated area

Expected result: Amount is not going over the dedicated area

Attachment:

<img width="1290" alt="Screenshot 2024-04-15 at 12 00 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/559e2a4f-81b0-4897-b10f-e8985e447262">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
On the old design it is impossible to enter more than 9 symbols, on the new design the issue appears. 

Closing the ticket.
