### ISSUE TITLE
[QA][Testnet] [Solflare] Testnet transaction shows as Mainnet confirmation on wallet pop-up

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1930]
Precondition:
Solflare wallet switched to Solana Devnet

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 1 AVAX from Fuji to Solana
2. Select Manual Route
3. Click Approve and proceed with transaction
4. Click Claim when option is given 
5. Observe the wallet pop-up notification

Actual result: Solflare wallet pop-up shows message `Network mismatch
Your current network is set to Devnet, but this transaction is for Mainnet. Switch to the correct network before signing.` and it is not possible to confirm the transaction.

Expected result: Testnet environment should support Solana Devnet Network for the transactions

Attachment:
<img width="1077" alt="Screenshot 2024-04-15 at 12 20 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/872d3b55-cd4e-401e-9f28-a352c13c5429">

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portalbridge.com/ed4e22522f/
Solflare devnet was connected for the transaction
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8d75e654-5a96-4a37-b769-40a7ef582c4a

**Comment by Yren280** [comment]
Testnet app before confirming the Mainnet URL.

**Comment by scottwilson312** [comment]
I'm having the same issue

**Comment by gooxpf** [comment]
I have same issue, on testnet and devnet transactions.

**Comment by R-K-H** [comment]
Same issue.

**Comment by saifqamar** [comment]
I am also facing the same issue. does anyone find solution?

**Comment by saifqamar** [comment]
I am also facing the same issue. Did anyone find the solution?

**Comment by R-K-H** [comment]
Solflare has acknowledged it's a bug on their part and said they're addressing it in an upcoming release.

> I am also facing the same issue. Did anyone find the solution?

**Comment by EffiEmmanuel** [comment]
I am currently building an app on the Solana Blockchain and I have also been facing a similar issue for some days now. Good to hear it's just a bug and it'll be addressed in Solflare's upcoming release.

**Comment by EugenWay** [comment]
same issues on devnet

**Comment by RenovJ** [comment]
same issue is still caused so far..

**Comment by AhmedAliAbdelaziz** [comment]
the same issue is still on devnet

**Comment by asrarhusain** [comment]
Any updates on this one?

**Comment by kima-bastian** [comment]
I'm having the same issue today....

**Comment by romeoscript** [comment]
still having this issues today
