### ISSUE TITLE
[QA][Mainnet] USDT contract address is different on Wormhole-connect and Metamask wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1931]
Precondition:
USDT asset available at Klaytn network

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Select Klaytn network
2. Connect Metamask wallet
3. Click on Select asset
4. Search for USDT asset
5. Open Metamask wallet
6. Select Klayton mainnet
7. Search for USDT asset and view asset details
8. Observe

Actual result: USDT asset contract address is not matching on Wormhole-connect and Metamask wallet

Expected result: USDT contract address is the same

Attachment:
<img width="1032" alt="Screenshot 2024-04-15 at 13 16 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b1f8aa06-5d2e-40f7-a3ea-bfa18916691d">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
USDT contract address is different on Portal and Metamask

Attachment:
<img width="997" alt="Screenshot 2024-05-08 at 14 19 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/63b0091c-0013-4dc1-97a1-c25f178574f1">

**Comment by agodlevska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet].

Contract addresses on Portal Bridge and in Metamask are the same for following tokens:

- USDT (Ethereum) on Klaytn,  unable to check, token address are not displayed for Klaytn network
- USDT (Ethereum) on Avalanche, 0x9d228444FC4B7E15A2C481b48E10247A03351FD8

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/user-attachments/assets/c9e95663-9140-4232-b415-90b301aff1ea)

![image](https://github.com/user-attachments/assets/11694cf4-b29f-487a-adda-2e3d50bdfea5)


Closing the ticket.
