### ISSUE TITLE
[QA]Cannot "Add to Metamask" through Wormholescan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1937]
Precondition:
Phantom (Devnet) at sending From section
Metamask at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 5 W from Solana to Arbitrum Sepolia
2. Select Automatic Native token transfer Route
3. Click Approve and proceed with transaction
4. When transaction is completed click on View on Wormholescan
5. Click on button "Add to Metamask"
6. Observe

Actual result: User is not able to add token through Wormholescan - Add to Metamask, console shows 
> Failed to switch chain in MetaMask 
{code: -32602, message: "Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received:\nundefined", stack: '{\n  "code": -32602,\n  "message": "Expected 0x-pref…ogaeaoehlefnkodbefgpgknn/background-3.js:3:74857)'

Expected result: Token is added to the wallet

Attachment:
[Solana explorer](https://explorer.solana.com/tx/oLGzKp2SdeyiuQymjtvutLgpvewmm34z2v9NZom3tKzHpefRdqmcLHSqxBGJVvYbjNHFWE8VAuyTisMBhEW469X?cluster=devnet)
[Wormholescan explorer](https://wormholescan.io/#/tx/1/cf5f3614e2cd9b374558f35c7618b25f0d306d5e749b7d29cc030a1a15686238/27?network=TESTNET)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/661763d9-7c3d-4be2-94be-c2e1b3efb03f

**Comment by AigaD** [comment]
Tested OK from: https://portalbridge.com/
User is able to Add W token to Metamask wallet through Wormholescan "Add to Metamask"
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c4648bef-cd73-4b1c-9a57-18fc17c9f45c

**Comment by AigaD** [comment]
Reproduced from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAAcRHAJ60R0QsQi4Rk3DPmKyHNN3xFBYfXJiKAsgEEAKgEkAwjogBfEL5AA%3D%3D%3D#)
Cannot add USDT token from [Wormholescan](https://wormholescan.io/#/tx/0x38dbc3778cf5be50fb98bfc53c20ef5346b17d87ce9e27b07fb50ea0c50d3f75) "Add to Metamask" button `"Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received:\nundefined", stack: '{\n  "code": -32602,\n  "message": "Expected 0x-pref…ogaeaoehlefnkodbefgpgknn/background-4.js:1:26185)'}`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/78716481-b6f5-4ad7-a859-59dffa07c828

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
Cannot add WSOL token through [Wormholescan](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/877899) link `MetaMask - RPC Error: Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received:
undefined`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2d39dc76-7d76-41a9-a0aa-196be0fad2fb

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/, https://wormhole-connect.netlify.app/ and https://portalbridge.com/. 

Tested OK:

- [WAVAX token](https://wormholescan.io/#/tx/0x509eef0fce3c4041b31a0f8a13a971b99cb8c646a58077aa98dba2c89b6731da)
- [WKLAY token](https://wormholescan.io/#/tx/0x6d5b9e8ab235a08fe516b03335218ca560f16aba35f5e12500030609a96b310f)
- [WMATIC token](https://wormholescan.io/#/tx/0xa7602ccaa96295e376924e7d45b8de382c0400ad736e77c7d7a115296699cc76)
- [WGLMR token](https://wormholescan.io/#/tx/0xcb4aa2c26bb75284e59c81fbaa356a89ed2eeebb8c21d8b3dd464178fc2495ec)
- [WFTM token](https://wormholescan.io/#/tx/0x42ed4f48270acdc6d6d80945480aa97620874d8a0de49fdd6624c6fbe09c3e62)
- [USDC token](https://wormholescan.io/#/tx/0x7c5e9652e96129c364345a9cf0acc6eab7ba88ae6ddee503606c798b61f4f51d)
- [tBTC token](https://wormholescan.io/#/tx/0xe8d19780ef5134f4ddbaf82d3ba2f02dc60d3c37965f95825dfa35c011902160)
- [WETH token](https://wormholescan.io/#/tx/0x83c7b0fdb1cbd55ac8a76b329a0921243512b87381ed26e3c57f5807388a2821)
- [wstETH token](https://wormholescan.io/#/tx/0xde7c291c2750c269d9af701664bf345c9a1ad58a4386be17af772822db6fc5bc)
- [CELO token](https://wormholescan.io/#/tx/0x6b3e4dfc5fa720a154295e5a9b3e5b3ee1e432813938ca07b7617181fe8f6fb2?network=TESTNET)

Closing the ticket.
