### ISSUE TITLE
[QA]Route is switching to automatic every time when user changes the amount

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1938]
Precondition:
Metamask wallet connected

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.001 Ws from Sepolia to Optimism Sepolia
2. Select manual Native token transfer Route
3. Change the amount to 0.0001
4. Click outside the amount field
5. Observe the Route section

Actual result: Every time when user changes the amount Automatic Native token transfer route is switched to

Expected result: User changes amount, but if previously selected Manual Native token transfer route, the selection is left at manual route

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/007cdbdc-6352-4e6c-95e8-982420734a2e

**Comment by kev1n-peters** [comment]
This happens with other routes too from what I tested

**Comment by AigaD** [comment]
Tested also from: https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYu4iOaaGm2CweuTEUBRACoAJa2AC%2BIT0A%3D# 
Route section switches to Automatic route if the amount is edited
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2fbbbfac-4988-426d-b0b9-d79b3ea2be92

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
Route section switches to Automatic Route if the amount is changed. 

Attachment:

https://github.com/user-attachments/assets/3111bdf7-6331-4549-9281-547b636eb348

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. Manual route stays selected after changing the amount. 


https://github.com/user-attachments/assets/ab4e21d6-0c17-4157-b967-833514a20f6b

Closing the ticket.
