### ISSUE TITLE
[QA] Ws token instead of W token shown for target chain at Solana in Wormholescan link

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1939]
Precondition:
Metamask wallet connected at sending From section
Phantom wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.001 Ws asset from Sepolia to Solana
2. Select Native token transfer manual route
3. Click Approve and proceed with transaction
4. Click on View on Wormholescan link
5. Observe the asset at redeem amount for target chain

Actual result: Ws token is shown at Wormholescan link at the redeem amount for Solana network

Expected result: W token should be shown at the redeem amount for Solana network

Comments: Failing at Claim for Solana reported here https://github.com/wormhole-foundation/wormhole-connect/issues/1757

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/849408f2-abef-4991-a6f1-e8122bf2118f

**Comment by tsadovska** [comment]
Issue is not reproducible on https://portalbridge.com/, correct token name "W" is displayed on Wormholescan. 
Scenario checked: 0.00001 W transfer from [Ethereum](https://etherscan.io/tx/0x0e7ceda211fc4720c237844fc7c6afe2b6d8ab3af9340209e58043d218df9dfd) (MetaMask) to [Solana](https://explorer.solana.com/tx/23QSSwd6WGkP85SRvhi27XdFNjFt7ExZpdpuZDhgAss766AT5hCcL5ayeorcRH5FRr8RzAonKDUMfiRye8vrNX1K) (Phantom). Link to [Wormholescan](https://wormholescan.io/#/tx/0x0e7ceda211fc4720c237844fc7c6afe2b6d8ab3af9340209e58043d218df9dfd).

Closing the ticket.
