### ISSUE TITLE
[QA] Relayer fee amount not shown in Preview section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1942]
Precondition:
Metamask wallet connected at sending From section
Nightly wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.1 Ws from Sepolia to Solana
2. Select automatic Native token transfer route
3. Click on Total fee estimates
4. Observe Relayer fee section

Actual result: Relayer fee information is not shown, "-" is shown instead

Expected result: Relayer fee is shown

Attachment:

<img width="895" alt="Screenshot 2024-04-17 at 12 48 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/993eb141-d4b4-4edb-aed6-fdb55ec22864">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/ed4e22522f/
For transaction 0.0001 W from Optimism to Solana, Relayer fee information in Preview section is not shown
Attachment:

<img width="666" alt="Screenshot 2024-04-19 at 09 00 50" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/33fcbaff-0aec-41d9-a72c-3bf3d67821ad">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] (Portal Bridge: 0.2.13, Wormhole Connect: 0.3.4-beta.5-development) when sending 0.001 W from Ethereum (MetaMask) to Solana (Phantom) with "Native Token Transfer (Receive tokens automatically)" route. Relayer fee information is not shown. 


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3d82795b-48ab-4a4a-baf4-d766a5234712)

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/
When sending W (Arbitrum) from Arbitrum 9Metamask) to Solana (Solflare), Relayer fee amount is not calculated.

Attachment:

<img width="1021" alt="Screenshot 2024-04-29 at 14 44 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/334c9585-80ba-454b-b47b-61395adbcad4">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
For transaction 0.001 W from Base to Solana, Relayer fee information is not shown
Attachment:
<img width="697" alt="Screenshot 2024-05-07 at 16 51 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b26f586-7c90-4cd4-bdaa-fe19bbd88d55">

**Comment by agodlevska** [comment]
Reproduced from: https://portalbridge.com/
Transaction 0.001 W from Optimism (Metamask) to Solana (Solflare), Relayer fee information is not shown. 
Attachment:
<img width="745" alt="Screenshot 2024-05-27 at 14 56 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/6378b9aa-0a72-479f-bbaf-25f782acd38a">

**Comment by tsadovska** [comment]
Reproducible on https://staging.tally.xyz/gov/mainnet-wormhole [Mainnet] when sending 0.00001 W from Ethereum (MetaMask) to Solana (Phantom). 

<img width="379" alt="Screenshot 2024-06-05 at 18 59 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c14b3cba-703b-49b7-b5b2-65cab7ed7a54">

**Comment by aadam-10** [comment]
closing as the relayer fee for W is 0 currently
