### ISSUE TITLE
[QA]Transaction to Solana not moving past Step 2, Error: 429

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1946]
Precondition:
OKX wallet extension enabled

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.01 Ws from Sepolia to Solana
2. Select Automatic Native token transfer route
3. Click Approve and proceed with transaction
4. Observe if transaction is completed

Actual result: Transaction is not moving past Step 2, console shows `Error: 429 :  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com."}, "id": "ae91e1b4-d177-477a-b60f-25f53c4b4672" }`

Expected result: Transaction is completed

Attachment:

Transaction Ws from [Sepolia](https://sepolia.etherscan.io/tx/0x2a54287736d06bc77bc17d286e1ac3675c60cc3f494c16ba189e639bd20cc217) (Metamask) to Solana (Nightly)

Transaction Ws from [Sepolia](https://sepolia.etherscan.io/tx/0x1ed47627a1d3857a586042eeff1723c5f59fa171976a3cb19c0852e1dbcbd0f7) (Metamask) to Solana (OKX Wallet)
<img width="1322" alt="Screenshot 2024-04-17 at 14 49 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f79e12cb-0054-46d9-8d01-2a429cbb8eb0">

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/ed4e22522f/
Reproduced also for transaction Arbitrum Sepolia (Metamask) to Solana (Backpack)
Transaction is left at Step 2 loading.

Attachment:

<img width="1313" alt="Screenshot 2024-04-18 at 09 28 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b17e418f-4d0e-4976-9eba-ea9c4558ff60">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://testnet.portalbridge.com/ed4e22522f/ [Testnet]

Scenarios checked:
* Send 0.0001 Ws from Sepolia (MetaMask) to Solana (Phantom): [Etherscan](https://sepolia.etherscan.io/tx/0xc15f0f7a2197528f0b0c77dfa110ddc88cd2c8f9565dbe10096858d15f458f81), [Solana explorer](https://explorer.solana.com/tx/4N8Mqv5PQ4M9MsuDZyubnna7hyw1YyZb4bqjRgffnGBjtCzvnkPxq5mTfbZWfTRKXUPyhDbY5SsYi7cNCz4nzd3k?cluster=devnet)
* Send 0.000001 Ws from Arbitrum Sepolia (MetaMask) to Solana (Phantom): [Etherscan](https://sepolia.arbiscan.io/tx/0x2fec42881bb8aa5529486c1cf40b34e7e195b205f4171227b478edc491a4570f), [Solana explorer](https://explorer.solana.com/tx/3BLAZ6xm9wmSoMzEvYBqSfbvqupRqNvdhKHcc9dYGMvWt1deMHfBZ1hJSeUGu4dYWb44XTMKHTrqRsg1dSbZEo5e?cluster=devnet)

Ticket is closed.
