### ISSUE TITLE
[QA] [Testnet] Cannot change slider position when sending asset to Mumbai

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1947]
## Describe the current behavior in detail
Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 123.0.6312.107 (Official Build) (arm64)

Tested from:
https://wormhole-connect.netlify.app/ [Testnet]
https://testnet.portalbridge.com/ed4e22522f/ [Testnet]

Steps:
1. Select Solana as source chain and connect Phantom wallet
2. Select Mumbai as destination chain and connect MetaMask wallet in To section
3. Select SOL asset and enter amount 1 SOL
4. Select "Automatic Bridge" route and enable "Native gas" section
5. Change slider position

Actual result: Cannot change slider position. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cbf6116a-5585-4029-9c3f-b7f0e30e4e08

## What is the expected/desired behavior
Slider position can be changed.

**Comment by AigaD** [comment]
Tested from:
https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.3 GLMR from Moonbase to Mumbai
2. Select automatic Route
3. Enable Native gas field
4. Try to change slider position

Actual result: Cannot change native gas slider

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c602a787-74ad-46bf-81f4-ecbd46a02edd

**Comment by agodlevska** [comment]
Mumbai network is no longer displayed on https://wormhole-connect.netlify.app/.

Attachment:
<img width="597" alt="Screenshot 2024-07-24 at 12 29 21" src="https://github.com/user-attachments/assets/a68cbdbc-5cf8-459f-b3cc-a5ee7f47ff27">
