### ISSUE TITLE
[QA][Mainnet] Asset balance not loaded automatically when Network is switched

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1951]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/ed4e22522f/#

Steps:
1. Select Ethereum network
2. Connect Metamask wallet
3. Click on Assets and select W token
4. Change Ethereum network to Arbitrum
5. Observe token balance

Actual result: Token balance is not shown after switching networks, user has to open the asset list in order for the balance to show

Expected result: Token balance is shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/252857b5-efac-40af-b49e-e712f11ad426

**Comment by AigaD** [comment]
Reproduced also from: https://portalbridge.com/
Corresponding W token to Arbitrum network is not automatically changed, instead of W (Arbitrum) -> W (Ethereum) is left connected until user changes the assets.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4ddaa1b0-5d28-49e6-a431-71d9858e4d06

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/ with the scenario mentioned above. 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-19 at 15 38 59" src="https://github.com/user-attachments/assets/4b6c4cad-f1d9-484e-8f5f-af27c28b2609">

**Comment by agodlevska** [comment]
The issue is no longer reproducible on https://portalbridge.com/. When the user changes the network, W (Ethereum) does not remain connected. Additionally, the balance for the selected network is correctly loaded and displayed.

Attachment:

https://github.com/user-attachments/assets/998e1b23-7055-4ef9-8849-1518177dc69e
