### ISSUE TITLE
[QA] [Testnet] Claiming on Solana fails with "Cannot read stream: RpcTransport has not been started" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1955]
## Describe the current behavior in detail
Checked on https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development) with macOS Sonoma 14.4.1 and Chrome Version 123.0.6312.107 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.0001 Ws from Base Sepolia (MetaMask) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button

Actual results:
* Asset claiming fails with `GOT ERROR Error: Cannot read stream: RpcTransport has not been started` error
* Send from tx: [Etherscan](https://base-sepolia.blockscout.com/tx/0x5b16eed055d48659670d24d9788f72948be0fe2c813ab4a54a9be808e9c1fbe9)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x5b16eed055d48659670d24d9788f72948be0fe2c813ab4a54a9be808e9c1fbe9?network=TESTNET)

```
GOT ERROR Error: Cannot read stream: RpcTransport has not been started
    at fi.<anonymous> (<anonymous>:3:211291)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1598
    at new Promise (<anonymous>)
    at je (<anonymous>:1:1418)
    at fi.send (<anonymous>:3:211244)
    at pi.<anonymous> (<anonymous>:3:215125)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1598
    at new Promise (<anonymous>) 
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b588ecdb-c263-4793-ae2e-ef81ea27fd62)

## What is the expected/desired behavior
Token is successfully received.

**Comment by Developer-R-7** [comment]
Hey @tsadovska , I have the same issue but on the mainnet , I am not able to claim my token after bridge

Transaction details:

- Bridged USDC Polygon to USDC Solana
- send from tx: [polygonscan](https://polygonscan.com/tx/0x3d21da729e5994480693257b1a5f330aa3da22ecf009c2877cf7e14d935fbbef)
- Link to wormhole scan: [wormholescan](https://wormholescan.io/#/tx/0x3d21da729e5994480693257b1a5f330aa3da22ecf009c2877cf7e14d935fbbef?view=overview)




Could you assist me in redeeming my tokens on Solana? What are the steps required to claim them?


<img width="1468" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/38732580/67e9aa29-ba64-4f83-9806-36c7e1c6fcc1">

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1757.
Closing the ticket.
