### ISSUE TITLE
[QA][Mainnet] Failing to start transaction "WalletSendTransactionError: Transaction cancelled"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1964]
Precondition:
Solflare connected at sending From section
Metamask connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.001 W from Solana to Base
2. Select Automatic Native token transfer route
3. Click Approve and proceed with transaction
4. Observe

Actual result: Pop-up `Simulation failed
Balance changes are unknown. Proceed with caution and make sure you trust this transaction.` with unknown balance changes are shown and when user selects "I trust this transaction" and click approves, transaction fails, reason `WalletSendTransactionError: Transaction cancelled`

Expected result: Transaction is started

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/38c838d0-9540-4785-b08c-2c57b5ef73bf

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Tested OK. User is able to send 0.001 W (solana) from [Solana](https://explorer.solana.com/tx/363ETYd22kcrmJ7vAGayZ9L4SBwr5v353UqNU4TdQYjnnr7SVrVnMfSXUTVgbvHDyEMjSAkTwMhkLciLpaiLW7x) (Solflare) to [Base](https://basescan.org/tx/0x190837a9b3622dc1c1170c681ad3d2ff6fc9fcd969561dcd78ce42df07aa9d66) (Metamask) using Automatic Native token transfer route

Attachment:

<img width="1031" alt="Screenshot 2024-05-20 at 13 37 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/83e813ce-d4e0-42b5-9919-38593a80c1d8">


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ceba6bc8-9930-4b30-9920-9ca969d73890

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) and https://portalbridge.com/. 

Sending 0.001 SOL from Solana (Nightly) to Sui (Sui). 

Error message in console: 
```
Wormhole Connect: error completing transfer 
Error: Simulation failed: {"InstructionError":[1,{"Custom":1}]}
Logs:
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
  Program log: Instruction: Approve
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2903 of 400000 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb invoke [1]
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: Burn
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4790 of 362751 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
  Program 11111111111111111111111111111111 invoke [2]
  Program 11111111111111111111111111111111 success
  Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth invoke [2]
  Program log: Sequence: 933367
  Program 11111111111111111111111111111111 invoke [3]
  Transfer: insufficient lamports 2009076, need 2477760
  Program 11111111111111111111111111111111 failed: custom program error: 0x1
  Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth consumed 18438 of 347208 compute units
  Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth failed: custom program error: 0x1
  Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb consumed 68327 of 397097 compute units
  Program wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb failed: custom program error: 0x1
    at Tt (solana-CI9LWdVg.js:2:52115)
    at async he (solana-CI9LWdVg.js:2:50974)
    at async signAndSendTransaction (main-B5BQWVC9.js:273:62073)
    at async SDKv2Signer.signAndSend (main-B5BQWVC9.js:280:202769)
    at async ssw (main-B5BQWVC9.js:245:7760)
    at async signSendWait (main-B5BQWVC9.js:245:7467)
    at async TokenBridgeRoute.initiate (main-B5BQWVC9.js:245:48200)
    at async SDKv2Route.send (main-B5BQWVC9.js:280:207173)
    at async Operator.send (main-B5BQWVC9.js:280:211649)
    at async ft (main-B5BQWVC9.js:313:65845)
``` 
Reopening the issue. 

Attachments:
<img width="1438" alt="Screenshot 2024-08-22 at 12 05 12" src="https://github.com/user-attachments/assets/05b481b2-e8d6-4f56-9f8c-95ae9d5b9aff">
<img width="1440" alt="Screenshot 2024-08-22 at 12 05 20" src="https://github.com/user-attachments/assets/8dea8b00-592f-4d83-8a93-42d17ac8aa0c">
