### ISSUE TITLE
[QA] Wallets remain connected after returning from "Terms of Use" page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1969]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/ed4e22522f/ [Mainnet]  with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.01 AVAX from Fuji (MetaMask) to Fantom (MetaMask)
2. Click on "Terms of Use" link
3. Click on Back button
4. Check if wallets in From and To section are connected 

Actual result: Wallets remain connected after returning from "Terms of Use" page

![Screenshot 2024-04-19 at 16 26 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b9dd6531-01fd-400b-9fef-1101be75289d)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ea729627-8649-4f36-98d4-3a7084363e24

## What is the expected/desired behavior
All entered transaction information is displayed or the form is cleared.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Wallets are left connected after user returns to Bridge screen from FAQs
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bae97b81-0116-46da-be4f-88ee64a6f037

**Comment by agodlevska** [comment]
Reproducible on https://portalbridge.com/.

Attachments:
<img width="550" alt="Screenshot 2024-06-18 at 11 53 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/3436c37b-76d7-4a1e-b0e2-6979d0cefb14">

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/80f549de-f519-4d51-97ef-6928ad5bb475
