### ISSUE TITLE
[QA] "Estimated time" value in Route section should be right-aligned

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1970]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] (Portal Bridge: 0.2.13, Wormhole Connect: 0.3.4-beta.5-development) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 W (Base) from Base (MetaMask) to Ethereum (MetaMask)
2. Check if "Estimated time" value in Route section is right-aligned

![Screenshot 2024-04-19 at 17 57 59](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/30e032c9-09da-4fdb-856f-03751c7bb5a1)

## What is the expected/desired behavior
"Estimated time" value in Route section should be right-aligned.

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/.
Sending 0.00001 wstETH (Ethereum) from Ethereum (MetaMask) to BSC (MetaMask).

Attachment:
<img width="648" alt="Screenshot 2024-06-28 at 15 03 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/daa453e0-b802-428f-a4fd-30323f87a991">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Sending 0.0001 W from Base (MetaMask) to Ethereum (MetaMask).
Issue is not reproducible anymore, "Estimated time" value in Route section is right-aligned (same with wstETH token).

Attachment:
<img width="1438" alt="Screenshot 2024-08-20 at 13 24 08" src="https://github.com/user-attachments/assets/0363eb77-fe2f-4aae-aef7-3726e9a61a56">
