### ISSUE TITLE
[QA] "Error: Wormhole instruction not found" appears multiple times when sending W from Solana to Ethereum

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1971]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/ed4e22522f/ [Mainnet] (Portal Bridge: 0.2.13, Wormhole Connect: 0.3.4-beta.5-development) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.011 W from Solana (Phantom) to Ethereum (MetaMask)
2. Select "Native Token Transfer (Receive tokens automatically)" route
3. Click "Approve and proceed with transactions" button

Actual result:  Redeem screen does not open. Errors are displayed multiple times in Console. 
```
Error: Wormhole instruction not found
    at getMessageSolana (pb-index-uz2Jxxzd.js:503:115314)
    at async NttRelay.getMessage (pb-index-uz2Jxxzd.js:503:121512)
    at async Object.ko [as onClick] (pb-index-uz2Jxxzd.js:725:27797)
```
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3049fcfe-1c58-4a0b-ac17-050234d62bfc)

## What is the expected/desired behavior
Redeem screen is opened. "Error: Wormhole instruction not found" error does not appear.

**Comment by agodlevska** [comment]
Tested on https://portalbridge.com/# 

Transaction 0.001 W from [Solana](https://explorer.solana.com/tx/3Uk6ARkkzZvpfaw5NnhDJXKpYVbpALnr4ciBMbjsQ84nn2ZejEX5YzdBqwQSd3UP8b8eZwMWpgjo6FHJQ834QruL) (Phantom) to [Ethereum](https://etherscan.io/tx/0x9d6f58f5ed21b3da6b8565d17531b07f3d1e260468f241ece7384b2a97454672) (Metamask) with Native Token Transfer (Receive tokens automatically)" route was completed. 

Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-05-24 at 09 36 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/3c816f55-a521-4cee-bd8a-3de89f01cae7">
