### ISSUE TITLE
[QA] Warning "Amount cannot exceed balance" is not shown after network is changed 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1973]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

Preconditions: 
User doesn't have SUI on Fantom. 

Steps:
1. Prepare to send 2 SUI from Sui (Sui wallet) to Fuji (MetaMask)
2. Change source chain from Sui to Fantom
3. Check if warning "Amount cannot exceed balance" is displayed

Actual result: Warning is not displayed. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c60a3e5b-75c4-47a2-8609-912a9907c011

## What is the expected/desired behavior
Warning is displayed.

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/. 
Issue is no longer reproducible, warning "Amount exceeds available balance." is displayed.

Attachment:

https://github.com/user-attachments/assets/c8aab25f-e18c-4453-81c2-c55ae3f63843
