### ISSUE TITLE
[QA]Cannot connect to Aptos Snap wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1975]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/ - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
1. Click on Select Network
2. Select Aptos network
3. Click on Connect wallet
4. Select Snap
5. Observe

Actual result: Aptos Snap wallet is not connecting, console `'The method "wallet_enable" does not exist / is not available.'`

Expected result: Aptos Snap wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6e2c0ddf-484a-4ef7-bc62-6904c1c657d1

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Cannot connect to Aptos Snap wallet `VM590:1 MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available. `
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9d2365d2-c53b-48fa-9b2c-5aca038bff24

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
User is no able to connect to Aptos - Snap wallet, `MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available.`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5db07076-97b7-49dd-90ea-6050bebffa4a

**Comment by agodlevska** [comment]
Reproduced on: https://portalbridge.com/
User is no able to connect Snap wallet to Aptos, `Metamask - RPC Error: The method "wallet_enable" does not exist / is not available.`

Attachment:
<img width="1440" alt="Screenshot 2024-05-24 at 09 20 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/0d309c95-fbca-4fb7-9e1a-0b85e326eee1">
