### ISSUE TITLE
[QA] Wallets are reconnected after user disconnects them and then swaps networks

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1978]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64).

Steps:
1. Select Fantom as source chain and check that MetaMask wallet is automatically connected in From section
2. Select Fuji as destination chain and check that MetaMask wallet is automatically connected in To section
3. Click "Connect wallet" button is "To" section and select "Disconnect wallet" option
4. Check if wallets are disconnected
5. Click on "Swap" button
6. Check if wallets are reconnected 

Actual result: Wallets are reconnected.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e55b4e43-269d-4a6a-be2e-68cdc118f229

## What is the expected/desired behavior
Wallets should remain disconnected.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#
Issue is no longer reproducible, if user has disconnected wallets then they are not automatically connected when networks are selected or swapped.
Closing the ticket.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/28c2da16-927d-4817-b2d4-0749a767a570



https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4845a7ea-2f74-4ef2-8cb7-fb51426c56c5

**Comment by AigaD** [comment]
Re-opening.
Tested from: https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYqwArSAGNcGWJG2CweuTEUB1AGIAVALL2wAXxB%2FIA%3D#

Managed to reproduce when disconnecting Leap wallet and then swapping network places, Leap wallet is again connected to the network.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6f4578c8-7275-4e2c-847a-bfde060e92d7

**Comment by AigaD** [comment]
Closing this ticket, new issue was opened with different behaviour/steps to reproduce https://github.com/wormhole-foundation/wormhole-connect/issues/2007
