### ISSUE TITLE
[QA]Cannot change Native gas slider position for transaction Alfajores to Fantom

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1979]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/

Reproducibility: 1/5

Steps:
1. Prepare to send 5 CELO from Alfajores to Fantom
2. Select Automatic Route
3. Enable Native gas section
4. Change the slider position

Actual result: Occasionally cannot change slider position for Native gas slider

Expected result: User is able to change position of Native gas slider every time

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8bec8879-98f9-431b-9dad-4e1c03701f1f

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2). 
Issue is no longer reproducible, reproducibility: 0/10.

Closing the ticket.
