### ISSUE TITLE
[QA] Fee estimates should have more decimals behind comma - Cosmos gateway

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1983]
Precondition:
Metamask connected at sending From section
Leap connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://portalbridge.com/

Steps:
1. Prepare to send 0.01 AVAX from Avalanche to Osmosis
2. Scroll to preview section and expand Total fee estimate
3. Observe
4. Click Approve and proceed with transaction
5. Observe fee estimate on wallet pop-up confirmation

Actual result: Fee estimate is shown on Bridge screen is as 0 AVAX

Expected result: Fee estimate on Metamask pop-up shown as 0.002 AVAX, should be shown on Bridge screen as well

Attachment:

<img width="1264" alt="Screenshot 2024-04-23 at 09 25 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b415aca-0253-4e46-a43a-5b1de6ee3840">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
Fee estimate is shown on Bridge screen is as 0 AVAX.

Attachment:
<img width="580" alt="Screenshot 2024-09-10 at 11 21 42" src="https://github.com/user-attachments/assets/3d671fc8-5b8c-476c-8c53-7ace444ae25c">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.
Cosmos chains are no longer available in Networks list.

Closing the ticket.
