### ISSUE TITLE
[QA] [Pontem wallet] Failed to sign transaction, when Claiming on Solana

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1984]
Precondition:
Leap connected at sending From section
Pontem wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://portalbridge.com/

Steps:
1. Prepare to send 0.001 WSOL from Osmosis to Solana
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. Observe

Actual result: Transaction fails at Claim `Failed to sign transaction.`

Expected result: Transaction is Claimed and completed

Attachment:
[Osmosis explorer](https://www.mintscan.io/osmosis/tx/F2B93BB37E8A6C797C3E8272CFCD5C1ECA34D64EDD0E65CA26C98A0CAAA0E8BF)

<img width="1247" alt="Screenshot 2024-04-23 at 12 06 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0c9cfbf9-d4b3-4799-a11c-5e920742df0e">
<img width="1281" alt="Screenshot 2024-04-23 at 12 06 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8231c158-2bec-49ac-b0b7-130f655c2333">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/41e7699f-aefe-4dc9-bbca-88d39cbe325d

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
`Failed to sign transaction.` shown when Claiming asset sent from Avalanche to Solana (Pontem).

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/704809c6-07fb-4873-9cec-dbbc8505277d

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 
Checked following scenarios:
* WSOL transfer from [Osmosis](https://www.mintscan.io/osmosis/transactions/3F37F33D7676989CF2B5920C256AD9D5B1D3028CEBFDA05840AF0BF663C5AF21) (Leap) to [Solana](https://explorer.solana.com/tx/2nzCp2EXSjZjRPea4nENPVwtNh7hj2Q8rDpqbhe9MQyGRawrhwLx4dpcMEfJi9mGHmNGX4xUvZ1pxEyZWKUQ3tnC) (Pontem), link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38166)
* WAVAX transfer from [Avalanche](https://avascan.info/blockchain/c/tx/0x82a27654f76b3a7097b2296f69dab5abe8bc1b1c4b2e05ba37189214dbd9c778) (MetaMask) to [Solana](https://explorer.solana.com/tx/3nL6Cc9LtDakFdEJNVjSgZJfMgHNHYPDY7uvUf2DYYXArPcTyEtJVzvxaDyZ62NUJJErnzopmKLPw9b9L6ghsWRQ) (Pontem), link to [Wormholescan](https://wormholescan.io/#/tx/0x82a27654f76b3a7097b2296f69dab5abe8bc1b1c4b2e05ba37189214dbd9c778)

Ticket is closed.
