### ISSUE TITLE
[QA][Testnet] Corresponding Network ETH asset is not available for the Route

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1991]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/#

Steps:
1. Click on Select Network at sending From section
2. Select Base Sepolia network
3. Click on Connect wallet
4. Select Metamask
5. Click on Select Network at sending To section
6. Select Sepolia network
7. Click on Connect wallet
8. Select Metamask
9. Click on Asset
10. Select ETH (Base Sepolia) asset
11. Observe sending To asset section

Actual result: ETH (Sepolia) asset is not selected for the Route, when clicking on asset section at sending To section, no available asset is shown for the route

Expected result: ETH (Sepolia) asset should be selected for the Route at sending To section

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fd1fe200-1fbb-4452-8051-bf06294aa597

**Comment by agodlevska** [comment]
Still reproducible on https://wormhole-connect.netlify.app/.
ETH asset is not selected for the Route.

Attachment: 

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/72bf0b3a-97b3-41ee-b721-8b19666eec62
