### ISSUE TITLE
[QA]Glitch with Bridge screen fields when returning from completed transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1998]
Precondition:
None

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
1. Select BSC network at sending From section
2. Connect Metamask wallet
3. Select Aptos network at sending To section
4. Connect Pontem network
5. Select BNB asset to transfer
6. Enter amount (e.g. 0.01 BNB)
7. Click Approve and proceed with transaction
8. Click Claim when option is given
9. When transaction is completed click Bridge more assets
10. Observe

Actual result: Approve button, Preview section and message "This transfer requires two transactions: one on the source chain and one on the destination chain. You will need gas on the destination chain." is shown for a moment when user clicks on Bridge more assets and returns to Bridge screen

Expected result: Only field to enter chain values are shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ee1d7703-c440-416e-8f7c-f7b6e11fd9db

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8d4a8c25-98bd-459d-963b-0eba607a1cb1

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://portalbridge.com/, https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/
Only fields for entering chain values are displayed, without any glitches.

Attachment:

https://github.com/user-attachments/assets/3645a461-6a78-4bac-aa19-ba1dff41ed47
