### ISSUE TITLE
[QA] [Testnet] Token bridge route instead of Circle CCTP route is offered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1999]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

Steps:
1. Prepare to send USDC (Fuji) from Fuji (MetaMask) to Base Sepolia/ Optimism Sepolia/ Arbitrum Sepolia
2. Check Route section

Actual result: Token bridge route instead of Circle CCTP route is offered. 

![Screenshot 2024-04-25 at 15 05 46](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f6943297-6ecc-44c9-a80c-d388f47663f1)

CCTP routes are suggested when user prepares to send USDC (Fuji) from Fuji (MetaMask) to Base Goerli/ Optimism Goerli/ Arbitrum Goerli.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1e75be4b-a8df-4c10-be61-e8eebad7c647)

## What is the expected/desired behavior
Circle CCTP routes are offered.

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] 
Attachment:
<img width="753" alt="Screenshot 2024-06-04 at 14 53 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/d1162631-93bc-413e-b116-cf461ad5c4c2">

**Comment by tsadovska** [comment]
Closing the ticket, because currently USDC transfer from Fuji to Optimism Sepolia is not available on https://wormhole-connect.netlify.app/. USDC token is not shown in the Tokens list in "To" section.
