### ISSUE TITLE
[QA] [Testnet] Cannot register tBTC token

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2002]
## Environment
Checked on [testnet](https://wormhole-connect.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 
```
{
  env: 'testnet',
  "bridgeDefaults": {
    fromNetwork: 'fuji',
    toNetwork: 'sepolia',
    token: 'tBTC',
  }
}
```

## Describe the current behavior in detail

Steps:
1. Open [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIkTNgCsK%2BQhBTDJKGfMXpIAB2EcKLDQLDa5MRSgBCAFQDCVsAF8QnoA%3D)
2. Click [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link in Token registration warning
3. Register asset: asset contract - 0x7E1779F65B644E5f98DdC4D2cB0A0106a7E6d9e1, source chain - Avalanche, target - Ethereum (Sepolia)
4. Refresh the page [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIkTNgCsK%2BQhBTDJKGfMXpIAB2EcKLDQLDa5MRSgBCAFQDCVsAF8QnoA%3D)
5. Check if warning to register asset is displayed

Actual result:
Token registration message is still displayed: "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets."

Expected result:
Token registration message is no longer displayed. 

## Notes/ Attachments
* Link to Snowtrace in "Send attestation" step: [Snowtrace](https://testnet.snowtrace.io/tx/0x58188678430fa284620518aeab365a20de963f7ad22f4db41ded1b21a11132d7)
* Link to Etherscan in "Create wrapped token" step: [Etherscan](https://sepolia.etherscan.io/tx/0x1d9a28103a3cd15ec134cd5c99cb5c957eed75c8b5feae7704877aa2f4559e96)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aa91bae5-cf13-4d4a-b172-199f9ad257ae)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6f9766e5-da68-4cae-8308-c013e8c6ff48)

**Comment by AigaD** [comment]
Linking to ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1248

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] for tBTC (Solana) -> tBTC (Goerli) transfer from Solana (Phantom) to Sei (Leap).

**Comment by tsadovska** [comment]
Scenario can no longer be reproduced, closing the ticket.
