### ISSUE TITLE
[QA] [Testnet] Token bridge route instead of wstETH Bridge route is offered 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2004]
## Environment
Checked on [testnet](https://wormhole-connect.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64).

```
{
  env: 'testnet',
  "bridgeDefaults": {
    fromNetwork: 'sepolia',
    toNetwork: 'mumbai',
    token: 'wstETH',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk6SAAdhHCi3yEIKYZJQz5i0W1EkWFbQLB65MRVMwBRACoAJa2AC%2BIb0A%3D%3D%3D)
2. Check Route section

Actual result:
Token bridge route instead of wstETH Bridge route is offered.

Expected result:
wstETH Bridge route is offered when sending wstETH Bridge from Sepolia (MetaMask) to Mumbai (MetaMask).

## Notes

![Screenshot 2024-04-26 at 14 54 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/50b85e25-6d63-470e-91a2-e88a054e22d9)

Only wstETH (Goeli) asset shown in "Available tokens" list.

![Screenshot 2024-04-26 at 14 54 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b71dd484-576a-4176-9192-1dbf25a34875)

Issue is not reproducible on https://portalbridge.com/ [Mainnet] (Portal Bridge: v0.2.13-0a2b3508ac, Wormhole Connect: v0.3.5) and https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

![Screenshot 2024-04-26 at 14 50 37](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/56ad51cb-715a-4c7a-9bac-31c80d7d67b4)

**Comment by kev1n-peters** [comment]
The portico routes are only available in mainnet
