### ISSUE TITLE
[QA] Links from Wormholescan lead to incorrect links

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2005]
Precondition:
Leap (Injective mainnet) switched in wallet

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJHgAWkCpDYpCxCLhGTcM%2BYqwArSAGNcGWJG2CweuTEUBVAMoMAKvbABfED8gA%3D%3D#

Steps:
1. Prepare to send 0.01 USDT from Ethereum (Metamask) to Injective (Leap)
2. Click Approve and proceed with transaction
3. When transaction is completed click on View on Wormholescan
4. In Target chain section click on USDT asset and Destination address links
5. Observe

Actual result: Links at Target chain section for [USDT](https://explorer.injective.network/token/ibc/2108F2D81CBE328F371AD0CEF56691B18A86E08C3651504E42487D9EE92DDE9C/) and [wallet address](https://explorer.injective.network/account/aW5qMTl1czk2MjlsdTNhNjg0cnA5dGtkMDNmZHl6czc3YWQ3dDl0YXhr/) lead to incorrect links

Expected result: Link to USDT token information and destination address lead to correct links

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/218fd4c1-c5bc-492e-91c8-34d0ffc32904

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJK2i4xhYhFWTcM%2BYoDGkDiPWCwquTEUBhAKIAZAPKmwAXxCugA%3D) when sending 0.01 CELO from [Fantom](https://ftmscan.com/tx/0xf17c51bfe686991f188c78f618540c5e6a3954eee5eaccbe4968a7bae509db7e) (MetaMask) to [Celo](https://explorer.celo.org/mainnet/tx/0x2d1a87cf6a5fe545a3b51d01a808fe8a6fac8a00b851d65c080018a7b39761f5) (MetaMask). Invalid link is opened when user clicks on [Celo](https://explorer.celo.org/mainnet/token/0x471EcE3750Da237f93B8E339c536989b8978a438/token-transfers) link on [Wormholescan](https://wormholescan.io/#/tx/0xf17c51bfe686991f188c78f618540c5e6a3954eee5eaccbe4968a7bae509db7e).

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 USDT from [Ethereum](https://etherscan.io/tx/0x7b016049b498ec7d82e003e39971b6bc9b643d6bc765ecb777c9f7f9be2387cb) (MetaMask) to [Injective](https://explorer.injective.network/transaction/AF944AD78101C96F89994CCCC221AE97839853C7906AB4923CAF5906E1CCAEE0/) (Leap).[ Invalid link](https://explorer.injective.network/token/ibc/3384DCE14A72BBD0A47107C19A30EDD5FD1AC50909C632CB807680DBC798BB30/) is opened when user clicks on USDT link on [Wormholescan](https://wormholescan.io/#/tx/0x7b016049b498ec7d82e003e39971b6bc9b643d6bc765ecb777c9f7f9be2387cb).
