### ISSUE TITLE
[QA]Wallet is re-connected when network is selected in other section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2007]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D# - Tested NOK
https://wormhole-connect.netlify.app/# - Tested NOK

Steps:
1. Select Kujira/Aptos network at sending To section
2. Check that wallet is re-connected according to previous wallet that was selected
3. Disconnect the wallet
4. Click on Select network in sending From section
5. Select any network (e.g. Mumbai)
6. Observe wallet at sending To section

Actual result: Wallet at sending To section is re-connected after disconnecting it, when selecting network in other section

Expected result: Wallets are not re-connected after user has disconnected any of them

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a2434b5-6e98-4cff-aa40-9559529b9a35

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6ed260fe-ac09-4735-8cc4-19b93a64aedd

**Comment by agodlevska** [comment]
Issue is reproducible on https://portalbridge.com/. 

Steps:

1. Select Injective network at sending To section
2. Check if Leap wallet is auto connected
3. Disconnect the Leap wallet
4. Click on Select network in sending From section
5. Select any network (e.g. Sui)
6. Observe wallet at sending To section

Attachment:

https://github.com/user-attachments/assets/9c0ffcf6-4945-413b-b637-f5ae836aac3a
