### ISSUE TITLE
[QA]Approve button is no longer shown after switching network few times

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2009]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAAcRHAJ60R0QsQi4Rk3DPmKAxpA4idgsPrkxFAYQCiAGQDy1sAF8Q3oA%3D%3D#

Steps:
1. Prepare to send 4 MATIC from Polygon to Celo
2. Select Automatic Route and add some gas
3. Change network at sending To section a few times
4. Observe if all fields are shown

Actual result: After changing the network a few times, Native gas, Preview field and Approve button is not shown. User has to switch to Manual and back to Automatic route for the fields to be shown again

Expected result: Fields are loaded after every network switch

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/43f4b7a8-f139-4d14-9b67-dd727b4f5770

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, regardless of network change - the slider remains in place and "Approve and proceed with transaction" does not disappear. 
Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/db31f7a7-4aca-4e46-b955-a424f1b7fe94
