### ISSUE TITLE
[QA] [Mainnet] "MetaMask - RPC Error" occurs when sending asset to Moonbeam

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2011]
## Environment
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'bsc',
    toNetwork: 'moonbeam',
    token: 'BNB',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGW4BjQsQi4Rk3DPmKUIkdDKQ0KdYLBa5MRQCFx9y2AC%2BIV0A%3D%3D)
2. Enter 0.0001 in Amount field
3. Click "Approve and proceed with transaction" button
4. Click "Claim" button on Redeem screen

Actual result: Transaction fails after clicking on "Claim" button.
Expected result: Transaction completes successfully. 

Error:
```
MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code
: 
-32603
data
: 
{code: -32603, message: 'execution fatal: Module(ModuleError { index: 51, error: [0, 0, 0, 0], message: None })', cause: null}
message
: 
"Internal JSON-RPC error."
[[Prototype]]
: 
Object
```
## Notes/ Attachments
Send from tx: [BscScan](https://bscscan.com/tx/0x93c8a5ee499ebf47eca113eb87ea0856cf0e0f95b827f12b62b2f835e2fb9ad0)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6638c718-a2a0-4be5-b950-f004492da0f7)

Issue is also reproducible on macOS Sonoma 14.4.1 and Google Chrome for Testing Version 122.0.6261.94 (Official Build) (arm64) when sending CELO from Celo (MetaMask) to Fantom (MetaMask). 

![Screenshot 2024-04-29 at 13 23 45](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1a5f1619-3a40-4c0d-bbd3-4ffde042c3c0)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.0001 WSOL from Avalanche (MetaMask) to Moonbeam (MetaMask). Send from tx: https://avascan.info/blockchain/c/tx/0x7ce01557be486ed58a6689f462397ec4b2c6787c4a8f919d40c58c97409a7a67

```
MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code
: 
-32603
data
: 
{code: -32603, message: 'execution fatal: Module(ModuleError { index: 51, error: [0, 0, 0, 0], message: None })', cause: null}
message
: 
"Internal JSON-RPC error."
[[Prototype]]
: 
Object
```


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aad038b7-9402-497b-a292-eb03001c03c0

**Comment by kev1n-peters** [comment]
Not able to reproduce this https://wormholescan.io/#/tx/0xb81e9fec9ec931bb582b6d89085e1a31410a14a4f476dcc31f7ea7727cc562bf 
![Uploading image.png…]()

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ when sending 0.0001 WBNB from BSC (MetaMask) to Moonbeam (MetaMask).
* Send from tx: https://bscscan.com/tx/0x856a92568f0e65a01eff5e598e259c7d4a2a8208422838d33a8d6e7c92795c19
* Link to Wormholescan:  https://wormholescan.io/#/tx/0x856a92568f0e65a01eff5e598e259c7d4a2a8208422838d33a8d6e7c92795c19


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/419e6b05-395a-4c91-83f0-36e1aaa30a15

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2053--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.00011 WGLMR from Kujira (Leap) to Moonbeam (MetaMask) with Cosmos Gateway Manual route. 

* Send from tx: [Kujira Finder](https://finder.kujira.network/kaiyo-1/tx/B4D7B07D87C137B06949F62A8248FBFB947C5788AED00110D89EA5EF3E9A4C98)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/33216)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a3f0853b-9a3f-4867-9c43-96f7db44c8d9)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Checked following scenarios:
* Send 0.0001 WBNB from BSC (MetaMask) to Moonbeam (MetaMask): [BscScan](https://bscscan.com/tx/0xee82ccc018c7b45703003b183dcaf0f21167ebc97ec3ccf26eb0788eef1019ca), [Moonscan](https://moonscan.io/tx/0x4727810783c7597ad0f5ee4856df3529045f903e74b0ff9763bae6ccc9d98bc8)
* Send 0.0001 WSOL from Avalanche (MetaMask) to Moonbeam (MetaMask): [Avascan](https://avascan.info/blockchain/c/tx/0xb49c241c48a3c81f39f4c31718410d2a472a272135f9ce8d63c2c3ff8cf63a5f), [Moonscan](https://moonscan.io/tx/0x3523986d96a11a70ded8c651a303a796d028859c66007fcb3314e3dafb6fab60)
* Send 0.0001 WGLMR from Kujira (Leap) to Moonbeam (MetaMask): [Kujira Finder](https://finder.kujira.network/kaiyo-1/tx/51906407CF424A699420A2D5729F77C1D0CE1B8BD14F115BACC138E3DFC3F5B9), [Moonscan](https://moonscan.io/tx/0xcb00bf94492eaee285348b53dfe71227b8e01cbf58906ad271874f889dd88853)

Ticket is closed.
