### ISSUE TITLE
[QA] [Mainnet] Cannot change slider position when sending USDC from Base

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2012]
## Environment
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'base',
    toNetwork: 'polygon',
    token: 'USDCbase',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGTTdIhYhFwjJuGfMUAHERwCetEdHWCwWuTEUBVAMoMAwstVWwAXxDegA%3D%3D)
2. Enter 1.5 in Amount field
3. Enable "Native gas" section
4. Change slider position

Actual result: Slider position cannot be changed. 
Expected result: Slider position can be changed. 

Reproducibility: 1/4

Error:
```
Uncaught (in promise) TypeError: Failed to fetch
    at getUsdVal (main-E6sKK0B5.js:484:653676)
    at getConversion (main-E6sKK0B5.js:484:653886)
    at main-E6sKK0B5.js:524:19156
```

## Notes/ Attachments

[Link](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+cannot+change+slider+position) to similar issues.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3a716e8d-2469-4943-bb22-72ee9ac32133

**Comment by agodlevska** [comment]
Tested on https://wormhole-connect-mainnet.netlify.app/
Issue is still reproducible. 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/a127aa37-46d7-417b-bb5c-15d7f9538836

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/.
Closing the ticket.
