### ISSUE TITLE
[QA]Wallet is not automatically switching to corresponding network when changing settings in configs

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2019]
Precondition:
Arbitrum network with Metamask wallet connected at sending From section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGgpkMuCmxSFiEXCMm4Z8xWTTdI2wWD1yYiy2AC%2BIR0A%3D%3D%3D#)
```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'arbitrum',
    toNetwork: 'base',
    token: '',
  }
}
```
Steps:
1. Open "Custom config"
2. Change section  `fromNetwork: 'arbitrum'`, to fromNetwork: 'solana'
3. Observe

Actual result: Wallet is not changing to Solana supported wallet (e.g. Solflare), but instead Metamask wallet is left connected

Expected result: Solana supported network is automatically connected when configuring environment

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/42e9c13c-9554-4d76-8f6e-f03727e79795
Metamask wallet left connected to Osmosis network:

<img width="1205" alt="Screenshot 2024-04-30 at 15 45 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6c456a78-7b1c-414d-8ebe-4a0b4bfd7e22">

**Comment by tsadovska** [comment]
Re-checked the issue on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERAEQBGbDDUaQAIpABmaEgBtcZHolAQIEtgHsUAOTwB3dWwDWiJAGV1MtNDSFiEXOp259Rk%2BcvXbKsA8MwTXmAAviBBQA%3D%3D). Issue is still reproducible, please see video attached. 

https://github.com/user-attachments/assets/b31c4518-de9a-415a-ad15-e586ae05cf73
