### ISSUE TITLE
[QA]wKLAY contract address on SUI explorer is different that on Wormhole-connect

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2022]
Precondition:
Leap (Evmos mainnet) enabled

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGgpkMuCmxSFiEXCMm4Z8xWTTdI2wWD1yYiy2AC%2BIR0A%3D%3D%3D#)

Steps:
1. Prepare to send 0.001 wKLAY from Evmos to Sui
2. Click Approve and proceed with transaction
3. Click Claim when option is given
4. When transaction is completed click on " See wKLAY token on [Suiscan](https://suiscan.xyz/mainnet/object/0xe5462cee7bfa503109e9da9bd5be39624bb0e0e62b468e3be554234377ea08b1) "
5. Observe token contract address
6. Return to Bridge screen
7. Connect Sui network
8. Open asset list
9. Observe wKLAY contract address given there

Actual result: Contract addresses are different

Expected result: Same contract address for wKLAY shown in the available token list for Sui network and in Suiscan

Attachment:
See wKLAY token on [Suiscan](https://suiscan.xyz/mainnet/object/0xe5462cee7bfa503109e9da9bd5be39624bb0e0e62b468e3be554234377ea08b1)
[Evmos explorer](https://www.mintscan.io/evmos/tx/452DB41E6E077C3225E9FADB1CCFC1179311FB93B6768E6FB46A9C64BEAADA55)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5c7c3e25-1c21-4f05-81a8-26f960773251

<img width="509" alt="Screenshot 2024-04-30 at 14 53 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09235cba-e1fd-4e4a-9c15-622de9901d4a">
<img width="1212" alt="Screenshot 2024-04-30 at 14 52 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dabbab22-cd79-4f48-b5c0-8c0f9d4ca938">

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/ [Mainnet]. 

Asset on Sui Explorer: https://suiscan.xyz/mainnet/object/0xe5462cee7bfa503109e9da9bd5be39624bb0e0e62b468e3be554234377ea08b1

![image](https://github.com/user-attachments/assets/6698bf33-6732-4ae2-81af-cde157573f99)

Ticket can be closed after changes are merged on https://portalbridge.com/.

**Comment by tsadovska** [comment]
Changes have been merged on https://portalbridge.com/ [Mainnet].
Closing the ticket.
