### ISSUE TITLE
[QA] User is allowed to start the transfer when amount is insufficient for transfer via the wstETH Bridge

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2023]
## Environment
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.93 (Official Build) (arm64).

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'arbitrum',
    toNetwork: 'optimism',
    token: 'wstETHarbitrum',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGgpkMuCmxSFiEXCMm4Z8xSIAOuDCgzctRQWD1yYiqd1wBRACoAJZavWa2hAAviDBQA#)
2. Enter 0.0004 in Amount field
3. Click "Approve and proceed with transaction" button

Actual result: Transaction fails.
```
Wormhole Connect: error completing transfer Error: Output amount too low, please try again later.
    at U6.send (main-aNdJO9Jn.js:487:70247)
    at Operator.send (main-aNdJO9Jn.js:489:132124)
    at Object.er [as onClick] (main-aNdJO9Jn.js:524:31319)
```
Expected result: Transaction proceeds without errors or warning "Min amount too low, try increasing the send amount" is shown.  

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f6cdb860-f23e-4675-a95f-9bfa777e881f)

**Comment by AigaD** [comment]
Same behaviour when sending 0.0003 wstETH from Arbitrum to Polygon, error `Wormhole Connect: error completing transfer Error: Output amount too low, please try again later.`

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b2f603f6-22a1-476a-b373-11e86f262eee

**Comment by agodlevska** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/)
Transaction 0.0003 wstETH from [Arbitrum](https://arbiscan.io/tx/0x0bd4605767f4fb1b42e2343fbf6e19d665571d618d8b822a4b44e735cf010aa4) (Metamask) to [Polygon](https://polygonscan.com/tx/0x591eeb293798db9b8efe5b2f98df594a9501f7735c8f60d38acf2a83256f87db) (Metamask) was completed.
Closing the ticket.
Attachment:
<img width="1439" alt="Screenshot 2024-05-23 at 16 11 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/4f608cad-71f1-4d8d-98d6-93abe68fed3f">
