### ISSUE TITLE
[QA]Wallet reconnects after returning from Resume transaction screen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2029]
Precondition:
Transaction hash, for completed transaction, e.g. Celo - 0x50c931f32e8f3cf6b71a4a8049c631742f3ef502c58649e8951a228fc9962fcc
Fields on Bridge screen are left empty

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)

`{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: '',
    toNetwork: '',
    token: '',
  }
}`
Steps:
1. Click on Resume transaction
2. Paste in the transaction hash from competed transaction ( 0x50c931f32e8f3cf6b71a4a8049c631742f3ef502c58649e8951a228fc9962fcc )
3. Select corresponding network (Celo)
4. Click Search
5. When transaction results are loaded click on "<" button to return to Bridge screen
6. Observe wallet section at sending To

Actual result: Wallet is reconnected at sending To section after returning from Resume transaction screen

Expected result: Bridge screen fields are left empty

Comment: Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1813

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6f671b0b-866b-4fff-9241-2a493c2ae860

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Wallet reconnects after user returns to Bridge screen from Resume transaction screen (in test used Scroll - 0xe37f5297a9634f145469a36157583876b21b2fb7223f7a47ea94d8e5a82a5eff )
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/13818424-d9ed-4780-b596-cda2d912aaf8

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Rabby wallet re-connects after returning to Bridge screen from a resumed transaction
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09672794-522e-430e-812c-f29a0136eccd

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
0xe37f5297a9634f145469a36157583876b21b2fb7223f7a47ea94d8e5a82a5eff - Scroll network. 

Attachment:


https://github.com/user-attachments/assets/274b9698-bdd4-430c-9ea2-bdcbc8ed8c7a
