### ISSUE TITLE
[QA] Transaction using gateway transaction hash is not found

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2030]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)

`{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: '',
    toNetwork: '',
    token: '',
  }
}`

Steps:
1. Prepare to send 0.001 wKLAY from Kujira (Leap) to Aptos (Rise)
2. Click Approve and proceed with transaction
3. When transaction is completed click on "View on Wormholescan"
4. Click on Gateway Tx Hash link
5. Observe

Actual result: Transaction details are not shown when clicking on transaction hash link at Gateway Tx Hash

Expected result: Transaction details are shown 

Attachment:
[Kujira explorer](https://finder.kujira.network/kaiyo-1/tx/54EA68E3ED48B29678BC7092B8D261B47E6FCE8864E5D4C9D18C3DC1402D49A4)
[Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/32755)
[Gateway TX hash](https://bigdipper.live/wormhole/transactions/0X478F05AE01CDCBC499FE34F2FC3F37F4ABE8CE8E827F209BDA7BB655C7FD1C68)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/46e1ba64-f16d-495f-97e2-99af53e1a6c4

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Transaction 0.001 USDT from Osmosis to Avalanche, by clicking on [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/33233) - [Getaway TX hash](https://bigdipper.live/wormhole/transactions/0X326A3FB861E3354DA97DC23C9C09799363DBE07A15FC310F0D36CBB2F0C7FCC4), transaction is not found
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/027d2789-7971-4737-af79-ea3fbd8f8cca

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
For transaction from Osmosis to Blast (Rabby) transaction using Gateway TX hash from [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/33760) results are not found.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/912ffe37-fd60-498f-a642-124d8e82946b

**Comment by agodlevska** [comment]
Issues is no longer reproducible. 
All three cases mentioned above have been verified, and the transaction details are displayed for each of them.
Closing the ticket. 

Attachment:


https://github.com/user-attachments/assets/57e52f39-dcf9-467e-878a-f9e2f6b525c1
