### ISSUE TITLE
[QA] "Estimated time" value is not shown when sending from Scroll/ Blast/ Mantle

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2042]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.0001 WAVAX from Scroll/ Blast (MetaMask) to Avalanche (MetaMask)
2. Check if "Estimated time" value is displayed in "Route" section

Actual result: "Estimated time" value is not displayed.
Expected result: "Estimated time" value should be displayed. 

## Notes/ Attachments
"Estimated time" value is calculated when sending AVAX from Avalanche to Scroll. 

![Screenshot 2024-05-07 at 10 01 50](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a5598d7e-5d10-41bf-8f35-36dce29c3bcc)

**Comment by AigaD** [comment]
Estimated time also not shown when sending other assets from Scroll, e.g. WMATIC
Tested from: https://preview.portalbridge.com/bceadc8c64/
Attachment:

<img width="971" alt="Screenshot 2024-05-10 at 08 51 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d654f0d0-dde9-4ce7-a3ed-f105f17c76cc">

**Comment by agodlevska** [comment]
Tested on https://portalbridge.com/
Issue is still reproducible, "Estimated time" value is not displayed when sending assets from Scroll.

Attachment:
<img width="1440" alt="Screenshot 2024-06-03 at 11 31 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/3e60ec62-156c-4969-beaf-35ba8c569a11">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ba2ee08429/ [Mainnet] when sending SUI from Mantle (MetaMask) to Sui (Sui Wallet).

![Screenshot 2024-07-01 at 09 55 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0bb17471-20be-48cf-be29-5adea7e99a35)

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/.
Issue is still reproducible, "Estimated time" value is not displayed when sending assets from Mantle.

Attachment:
<img width="723" alt="Screenshot 2024-07-26 at 11 09 34" src="https://github.com/user-attachments/assets/4cf0411c-3aba-467c-9f4e-57c7008cab30">

**Comment by tsadovska** [comment]
Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2683.
