### ISSUE TITLE
[QA]Different icons for ETH Scroll and WETH Scroll

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2045]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Select Scroll network
2. Connect wallet
3. Click on Asset
4. Switch to All tokens tab
5. Observe icon used for ETH (Scroll) and WETH (Scroll)

Actual result: Different icons are used for ETH (Scroll) and WETH (Scroll)

Expected result: The same icon used for ETH (Scroll) and WETH (Scroll)

Attachment:
<img width="514" alt="Screenshot 2024-05-07 at 12 31 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/de8b4f5b-ba95-4c97-898e-cd136b4d7a4f">

**Comment by tsadovska** [comment]
Tested OK on https://deploy-preview-2051--wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/316b2640-4f5f-44e9-9ffb-fe65f0c017ad)
