### ISSUE TITLE
[QA]Different icons for ETH Blast and WETH Blast

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2046]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Select Blast network
2. Connect wallet
3. Click on Asset
4. Switch to All tokens tab
5. Observe icon used for ETH (Blast) and WETH (Blast)
6. Actual result: Different icons are used for ETH (Blast) and WETH (Blast)

Expected result: The same icon used for ETH (Blast) and WETH (Blast)

Attachment:
<img width="537" alt="Screenshot 2024-05-07 at 12 42 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/20418466-71ec-4ac5-9d78-24303a48ed2c">

**Comment by tsadovska** [comment]
Tested OK on https://deploy-preview-2051--wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/43ef946c-240b-4439-b28a-251d68c11f91)
