### ISSUE TITLE
[QA]Status "In progress" is not shown in Wormholescan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2048]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Prepare to send 0.0001 tBTC from Ethereum to Polygon
2. Click Approve and proceed with transaction
3. While transaction is in progress click on "View on Wormholescan"
4. Observe the Status of the transaction

Actual result: Status section in Wormholescan in left empty

Expected result: Status label "In progress" is shown

Attachment:
[Wormholescan](https://wormholescan.io/#/tx/0x14c61c80cdc86c3ab3f089385b524611a7d1738ecf6c79af63c928e7d5265f21)
[Ethereum explorer](https://etherscan.io/tx/0x14c61c80cdc86c3ab3f089385b524611a7d1738ecf6c79af63c928e7d5265f21)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/256c2d71-9dff-4f48-b4b4-94a37ba716ba

How it should be displayed:
<img width="929" alt="Screenshot 2024-05-07 at 14 23 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/072f5d1c-16ba-4568-bfd6-b2f5cbdba959">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
For transaction 0.0004 ETH from Ethereum to Base, Status in [Wormholescan](https://wormholescan.io/#/tx/0x335ddc49b29f06d29cb64780f2f2bc202b8a6d93cdc4d8205ccb33308bbc636f) link "in progress" is not shown
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3d2d2d2-077a-4217-a84a-f92b6f600153


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3d2d2d2-077a-4217-a84a-f92b6f600153

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
All statuses are shown in Wormholescan. 

Closing the ticket.
