### ISSUE TITLE
[QA] [Wormholescan] Balance in "Add suggested tokens" notification should have more decimals 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2049]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64).

Steps:
1. Send 0.0004 wstETH (Arbitrum) from Arbitrum (MetaMask) to Polygon (MetaMask) or resume transaction 0x417410eafa52863175eb30360b52fe21da2cddc72129238e3e825b6ec0f984ae (Arbitrum)
2. Click "View on Wormholescan" link
3. Click on "Add to MetaMask" link
4. Check balance

Actual result: Balance is 0 wstETH.
Expected result: Balance have more decimals after comma.

## Notes/ Attachments
* Send from tx: https://arbiscan.io/tx/0x417410eafa52863175eb30360b52fe21da2cddc72129238e3e825b6ec0f984ae
* Send to tx: https://polygonscan.com/tx/0x797472c067783024232d15116e0d519898972afac1952935729ff858f09321d8
* Link to Wormholescan: https://wormholescan.io/#/tx/0x417410eafa52863175eb30360b52fe21da2cddc72129238e3e825b6ec0f984ae

![Screenshot 2024-05-07 at 14 47 33](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/31893fb6-719f-4232-ac93-5103638753a8)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b77eb423-7df1-4af0-956e-8a5fed898ab3

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/# and https://wormholescan.io/#/tx/0xe17b0f68e2d903f938926cd302f932e294620aa493293fab601a4f547db967fa
More decimals behind comma should be shown when adding token from Wormholescan link
Attachment:

<img width="1025" alt="Screenshot 2024-05-17 at 09 30 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/460008c8-6afb-4499-85f3-469bf66f0ea9">
