### ISSUE TITLE
[QA] Transaction fails to start, "Error: Simulation error"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2052]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Prepare to send 0.0001 W from Solana (Solflare) to Optimism (Metamask)
2. Select Native token transfer automatic
3. Click Approve and proceed with transaction
4. Observe

Actual result: Test failed to start, reason `Wormhole Connect: error completing transfer Error: Simulation error:`

Expected result: Transaction is started

Attachment:
<img width="1268" alt="Screenshot 2024-05-07 at 17 23 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ddba1807-5c54-4214-aa29-12a50f2da933">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c73a1e69-a86e-43f5-8ec5-535565a86c5f

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://preview.portalbridge.com/3b81f32422/ [Mainnet]. 
W transfer from [Solana](https://explorer.solana.com/tx/2XVAxYbA3MksRjJoFdo9bhaYm7km6K2CyTGQQA4mjCRiYaXkKLN7NjMAHm2CvzWxnA2bPDUR8BdF9XkTubaeSiuZ) (Solflare) to [Optimism](https://optimistic.etherscan.io/tx/0xaae7a504e464ba4605af1c3a7a7a7326b1a6bd6cf449a8ba4e551e4f936655a7) (MetaMask) was successful. 
Ticket is closed.
