### ISSUE TITLE
[QA] [Mainnet] "MetaMask - RPC Error" occurs when sending asset from Moonbeam

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2054]
## Describe the current behavior in detail
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiVCJHQykNCkLEIuEZNwz5i7iI5poaLYLC65MRQHEAMgFkASlbABfEF6A) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64). 

Steps:
1. Prepare to send 5 GLMR from Moonbeam (MetaMask) to Solana (Phantom)
2. Select Automatic Bridge option
3. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails. 
`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}`

Expected result: Transaction proceeds without errors.

## Notes/ Attachments
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eb7c43c4-29e1-466b-b5d9-9585c3d742aa)

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://metamask-i0.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

* Send from tx: [Moonscan](https://moonscan.io/tx/0x075582d008ec1606b3c406be620fd697f65e39e0608c9d99d68a22e4d0793ac2)
* Send to tx: [Solana explorer](https://explorer.solana.com/tx/4UGD5dMFmygkqLAdLGx3aPiEENzb2y1aDByTtbXvxieyMqXSnvc7L4GdCPT3btvxYy2TxiqMxyK3UKjFLyoUzM6y)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/46bba7cf-42f9-4226-86d4-d505bf8197f4)


Ticket is closed.

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/.
The issue was reproduced twice, and the third time the transaction completed successfully.

Attachment:
<img width="1439" alt="Screenshot 2024-09-03 at 09 54 59" src="https://github.com/user-attachments/assets/23cc3e16-e1b0-4bac-b9dd-d845ce85649b">

**Comment by tsadovska** [comment]
Transaction completed successfully from the first attempt.

Scenario checked: 0.1 DAI transfer from Moonbeam (MetaMask) to Celo (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0xfb987c20d1b145350058ad836bde40b532a93ed9b8e6f750d2b6bca5a8f2adea).

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development


https://github.com/user-attachments/assets/f2c02b18-3136-4fd2-b53d-a2d945d99d54


Closing the ticket.
