### ISSUE TITLE
[QA] Sui wallet automatically reconnects after disconnecting the wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2060]
Precondition:
Sui wallet was connected to Sui network

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNzYZCxCLhGTcM%2BYqwArSAGNcGWJDWCwmuTEUB1AELinVsAF8QHoA%3D%3D)

```
> `{
>   env: 'mainnet',
>   "bridgeDefaults": {
>     fromNetwork: 'sui',
>     toNetwork: 'injective',
>     token: 'WBNB',
>   }
> }`
```

Steps:
1. Click on Sui wallet
2. Disconnect Sui wallet
3. Refresh the page
4. Observe Sui wallet

Actual result: Sui wallet re-connects after disconnecting it

Expected result: Sui wallet remains disconnected after refreshing the page

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/10a23911-ad23-4512-8e5b-9d552b0dda13

**Comment by agodlevska** [comment]
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (connect v2).

Closing the ticket.
