### ISSUE TITLE
[QA] [Mainnet] Cannot register WMATIC for transaction BSC -> Scroll

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2064]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] (Portal Bridge: v0.2.14-P0d3df97c66, Wormhole Connect: v0.3.8-beta.1-development) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.0001 WMATIC from BSC (MetaMask) to Scroll (MetaMask)
2. Check that warning to register token is displayed
3. Open https://preview.portalbridge.com/bceadc8c64/advanced-tools/#/register 
4. Select BNB network and 0xc836d8dC361E44DbE64c4862D55BA041F88Ddd39 contract address in Source section
5. Select Scroll network and connect MetaMask wallet in Target section
6. Finish token registration
7. Refresh the page https://preview.portalbridge.com/bceadc8c64
8. Prepare to send 0.0001 WMATIC from BSC (MetaMask) to Scroll (MetaMask)
9. Check that warning to register token is displayed

Actual result: Token registration warning is still displayed after token was successfully registered on https://preview.portalbridge.com/bceadc8c64/advanced-tools/#/register. 
Expected result: Token registration warning is no longer displayed after token was registered. 

## Notes/ Attachments
1. Source: https://bscscan.com/token/0xc836d8dC361E44DbE64c4862D55BA041F88Ddd39
3. Send attestation: https://bscscan.com/tx/0x6236547e9dd6bee85f6f194e77ab18010533500ad6fd8138d987f7bbdba8296c, https://wormholescan.io/#/tx/0x6236547e9dd6bee85f6f194e77ab18010533500ad6fd8138d987f7bbdba8296c?network=MAINNET
4. Create wrapped token: 0xa6bd8824ca25acd27ff82d418ef995afff126fd885d978219c66e9b4a39d028c, https://scrollscan.com/tx/0xa6bd8824ca25acd27ff82d418ef995afff126fd885d978219c66e9b4a39d028c

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/551ced98-2f31-468a-8f4b-321f7a7f0fe0)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b905028d-f6b2-4a31-8b30-c5665f6c7ca7)

**Comment by kev1n-peters** [comment]
wormhole-wrapped WMATIC (BSC) was attested instead of WMATIC (Polygon)

**Comment by tsadovska** [comment]
Correct contract address: 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270.
Ticket is closed.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f0c8025e-2790-47c5-abad-1399c8935877)
