### ISSUE TITLE
[QA] Transactions in Scroll Metamask network are showing as failed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2066]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Prepare to send 0.0001 WAVAX from Ethereum to Scroll
2. Click Approve and proceed with transaction
3. Wait until transaction is completed
4. Click on Metamask extension
5. Observe Activity records in Scroll network

Actual result: Transaction is showing as failed in Metamask extension, but Confirmed in Scrollscan

Expected result: Transaction is shown as Confirmed

Attachment:
[Ethereum explorer](https://etherscan.io/tx/0xf59c040053ac40148f8fdf719a7fac647912f5de43e4dcf830e2793b82fda968)
[Scrollscan](https://scrollscan.com/tx/0x0364084454f4847f7d2215184dcf7c254eb95e23131637f8b6ac0ba3205eb4b3)

<img width="1342" alt="Screenshot 2024-05-09 at 16 16 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9df4ba7e-bfd8-442f-9884-197f0efa0a60">

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Issue is n longer reproducible, transactions are shown as confirmed on Scroll network in MetaMask. 

Attachment:
<img width="355" alt="Screenshot 2024-10-03 at 10 09 02" src="https://github.com/user-attachments/assets/be9a5a54-18d7-4c51-8316-8eb6fbc6a2fe">
