### ISSUE TITLE
[QA]Occasionally first transaction from Scroll fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2069]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Steps:
1. Prepare to send 0.001 WAVAX from Scroll to Optimism
2. Click Approve and proceed with transaction
3. Confirm the transaction in wallet pop-up
4. Observe if transaction is started

Actual result: Occasionally first transaction from Scroll fails `MetaMask - RPC Error: JsonRpcEngine`

Expected result: Transaction is started

Comments: During three tests from Scroll the first transaction failed with some error, but when approving the transaction the second time, the transaction started

Attachment:
<img width="1232" alt="Screenshot 2024-05-10 at 10 56 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/790c25d0-db82-42a8-b755-3aab5e1ed54a">

**Comment by tsadovska** [comment]
Issue is no longer reproducible.

Checked WAVAX transfer from Scroll (MetaMask) to Optimism (MetaMask) with following builds:
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]: [Scrollscan](https://scrollscan.com/tx/0x0be7509c6b485839adf051f7e1a6b3a066ad3b30c529af39b6628c347f549159), [Optimistic etherscan](https://optimistic.etherscan.io/tx/0xfa28ef067d7ad6a580437178d868bb1fab6a0f1508ba6c057aa84b654ae557bf)
* https://portalbridge.com/ [Mainnet]: [Scrollscan](https://scrollscan.com/tx/0xde9a4fa57faa42c585b786925e733134fba3ba35a285cb5988ed98a250d9847c), [Optimistic etherscan](https://optimistic.etherscan.io/tx/0x02958575f76ceada26670ab6b60490daf03b9726abe3868bef1f9bb1228663a8)

Ticket is closed.
