### ISSUE TITLE
[QA] Link to Wormhole supported chains leads to 404

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2070]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNwDGojh0LEIuEZNwz5ivAAtIFSGxSbBYHXJiKA6gEEAas4Aa1sAF8QPoA%3D#)

Steps:
1. Click on FAQs
2. Expands section "What chains and assets does Connect support?"
3. Click on https://wormhole.com/network
4. Observe

Actual result: Link https://wormhole.com/network leads to `404 MEANS NOT FOUND`

Expected result: Link to Wormhole supported chains is opened

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1f9b80ed-5a6d-47e4-ad5e-666cb644039d

**Comment by tsadovska** [comment]
Issue is no longer reproducible. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3fa9c688-b141-4c4a-89bf-622b2c880c29



Ticket is closed.
