### ISSUE TITLE
[QA] [Mainnet] Transactions to Kujira are stuck on Step 2

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2071]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome 

Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJCO4plGboWIRcIybhnzFctgCsMFNJsFgdcmIoDCAUQAyAeStgAviC9A)
2. Prepare to send 0.0001 CELO from Osmosis (Leap) to Kujira (Leap) or resume transaction `F60F72CD7BF30E133DA7B9682D14A3B3E9B385B9706F526EF2FC334EA5A0645D` (Osmosis)
3. Click "Approve and proceed with transaction" button
4. Check if transaction is completed

Actual result: Transaction is stuck on Step 2
Expected result: Transaction is completed. 

## Notes/ Attachments
Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/F60F72CD7BF30E133DA7B9682D14A3B3E9B385B9706F526EF2FC334EA5A0645D)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5977d73f-4e2a-4825-9d31-5f22fcc06902)

Issue is also reproducible when sending 0.002 WGLMR from Osmosis (Leap) to Kujira (Leap). Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/73ACD10B3264F8FEA4C0B17CE916632D6AB2490BC36213FCF8B3950D82D13FBD).

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c2ef2810-bcf9-4713-8f9c-ab4a5c12639c)

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJCO4plGboWIRcIybhnzFctgCsMFNJsFgdcmIqtgAviCdA%3D%3D#)
Issue is no longer reproduced.
Transaction 0.001 CELO from [Osmosis](https://www.mintscan.io/osmosis/transactions/3FF4FFAA27A96559A028944F3D44F89C5FBCE27DB3790C9B38D11F1FAC61DCC4) (Leap) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/36403F63875AB9CA14424631B3EA89CB838F31B289240C07FEFC1CD9006C3A1C) (Leap) was completed.
Closing the ticket.
Attachment:

<img width="1130" alt="Screenshot 2024-05-20 at 15 28 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49faea41-e943-490b-ac44-55479582a2ed">
