### ISSUE TITLE
[QA]Cannot register token to Blast network, network not found in the list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2074]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/3064c36d95/
Token registration - https://portalbridge.com/advanced-tools/#/register

Steps:
1. Prepare to send 0.01 MATIC from Polygon to Blast
2. Observe that token need to be registered
3. Click on [register](https://portalbridge.com/advanced-tools/#/register) 
4. In source chain select Polygon
5. In asset field paste in contract address 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
6. Click Next
7. Open network list
8. Search for Blast

Actual result: Blast network is not found in the Network list to register token

Expected result: Blast network is found in the network list, token can be registered

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/07ff95ec-7650-41eb-9df7-02f78bcaebfa

**Comment by AigaD** [comment]
Blast network found if manually changing the URL to https://preview.portalbridge.com/3064c36d95/advanced-tools/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b5fa1bf5-5273-4a13-957c-98a124ef314a

**Comment by kev1n-peters** [comment]
Blast is only exposed on the preview of advanced tools
