### ISSUE TITLE
[QA] User is asked to add more to fund to amount section if adding more to Extra Native gas

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#208]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.211 MATIC from Mumbai to Goerli
2. Click on Extra native gas drop down
3. Change the amount at Extra native gas
4. Observe the Gas payment, Extra native gas and Preview sections
5. Add more fund to the amount section
6. Observe

Actual result: When changing the Extra Native gas section the Gas payment, Extra native gas and Preview fields switched to inactive. User needs to add more funds in the amount section in order for the fields to change to active again.

Expected result: Extra native gas section can be edited and fields stay active.

Comments:  If the user has not gotten any warnings of the Amount before it is quite confusing why the fields are changed to inactive, if the warnings are present then next step is clear, but in the Extra Native gas section it is written: "Your wallet has little or no native gas (ETH) balance on Goerli. . Would you like to convert some of the MATIC you’re bridging to ETH?" Doesn't this mean that user should not change the amount, but be in the boundaries for the amount that is already given in the amount?

Attachment:

https://user-images.githubusercontent.com/91047061/225295953-d99128bc-ba22-46d7-b48f-bc1db97f8e13.mov

https://user-images.githubusercontent.com/91047061/225300106-b5ee9f11-e8ff-4fac-92cf-aaf1edc380f9.mov

**Comment by anondev2323** [comment]
We've fixed this. From the latest netlify deploy: 

https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/7bf7bb04-176d-499c-8b52-33197c534dfb

Successful tx: https://explorer.celo.org/alfajores/tx/0xef204a6a7458f1f666c9a9deadf418c2345845d72d1da49121713343127a51c1

**Comment by AigaD** [comment]
Tested OK
Scenario: Verify that user is not asked to increase the amount if changing Native Gas slider.
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4ccb7998-4832-4eec-bd08-63bd7ff439ff
