### ISSUE TITLE
[QA] Cosmos wallets automatically reconnects after user disconnects them

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2082]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGTTdIhYhFwjJuGfMUAHERwCetEdHWCwWuTEUBVAMoMAwstVWwAXxDegA%3D%3D#)
https://preview.portalbridge.com/3064c36d95/#

Steps:
1. Connect Cosmos Network (e.g. Osmosis)
2. Observe that previously connected wallet re-connects (e.g. Leap, Keplr)
3. Click on wallet and press - disconnect 
4. Hard refresh the page
5. Connect the same network as before (e.g. Osmosis)
6. Observe wallet section

Actual result: Wallet automatically re-connects after user has previously disconnected it

Expected result: Wallet is not automatically connected to previously chosen wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/734ba848-8628-4526-afdd-9565cf81c0cb

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b44cff7e-8d8e-4bda-8c76-0406f6030138

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
The wallet automatically reconnects after the user disconnects it and reloads the page.

Attachment:

https://github.com/user-attachments/assets/f8037d6a-27a8-4a6f-a2f7-a3fc71b8150a

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Cosmos chains are no longer available in Networks list.

Closing the ticket.
