### ISSUE TITLE
[QA]No indication shown that asset is not available for the Route

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2084]
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ismu74igsIbkxFeiAF8QLoA%3D%3D%3D#)

{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'fantom',
    toNetwork: 'scroll',
    token: '',
  }
}

Steps:
1. Select USDC.e asset
2. Observe

Actual result: No messages to show that the USDC.e asset is not supported for transaction from Fantom to other networks (except Ethereum) If network changed a few times at sending To section, message to register asset is shown

Expected result: Message "No bridge or swap route available for selected tokens" is shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/85b4ec2c-86fd-4ebb-803f-338ac1daa8b4

<img width="773" alt="Screenshot 2024-05-15 at 11 09 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09c66ff2-f6b7-4435-9715-8e749c933938">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/. 
No message to show that the USDC asset is not supported for transaction from Avalanche to Blast.

Attachment:

https://github.com/user-attachments/assets/8e300139-71b8-4a2d-bb7c-dc1b0be06787
