### ISSUE TITLE
[QA] "TypeError" errors appear in Console after opening the page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2106]
## Describe the current behavior in detail
Builds Tested NOK:

- https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
- https://portalbridge.com/ [Mainnet]
- https://wormhole-connect.netlify.app/ [Testnet]

Checked on macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64). 

Steps:
1. Open the page
2. Check errors in Console

Actual result: "TypeError" errors appear in Console.
```
TypeError: Cannot redefine property: solana
    at Function.defineProperty (<anonymous>)
    at bt (<anonymous>:2:1502465)
    at <anonymous>:2:1775281
    at <anonymous>:2:1777912
    at <anonymous>:2:1778005
    at <anonymous>:2:1778011
    at <anonymous>:2:158
    at <anonymous>:2:223
```
```
 TypeError: Cannot assign to read only property 'solana' of object '#<Window>'
    at bt (<anonymous>:2:1502644)
    at <anonymous>:2:1775281
    at <anonymous>:2:1777912
    at <anonymous>:2:1778005
    at <anonymous>:2:1778011
    at <anonymous>:2:158
    at <anonymous>:2:223
```
```
TypeError: Cannot assign to read only property 'solana' of object '#<Object>'
    at <anonymous>:2:1502449
    at Array.forEach (<anonymous>)
    at bt (<anonymous>:2:1502388)
    at <anonymous>:2:1775296
    at <anonymous>:2:1777912
    at <anonymous>:2:1778005
    at <anonymous>:2:1778011
    at <anonymous>:2:158
    at <anonymous>:2:223
```
```
TypeError: Cannot assign to read only property 'phantom' of object '#<Window>'
    at bt (<anonymous>:2:1502644)
    at <anonymous>:2:1775296
    at <anonymous>:2:1777912
    at <anonymous>:2:1778005
    at <anonymous>:2:1778011
    at <anonymous>:2:158
    at <anonymous>:2:223
```

Expected result: Page opens without errors. 

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d723ac79-0e64-443a-b681-06a4f611ca09)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b95953f8-25d8-4ac0-a999-473024d7bbba)

**Comment by agodlevska** [comment]
The issue can no longer be reproduced.
Closing the ticket.

Attachments: 
<img width="1440" alt="Screenshot 2024-06-03 at 09 25 50" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/6b7be98a-e098-4b5b-9cc8-737c9212b503">

<img width="1440" alt="Screenshot 2024-06-03 at 09 26 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/3b9a84e0-7831-4838-a8be-d6884323c89e">
