### ISSUE TITLE
[QA] [Mainnet,Testnet] An unexpected error occurs if user backgrounds wallet pop-up and then tries to again Connect the wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2107]
Precondition:
Previously Rise wallet was connected to Aptos network
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: '',
    toNetwork: '',
    token: '',
  }
}

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#) -  Tested NOK
[Testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk%2BQhBTDJKGfMXKBYNXJg6CEAL4hTQA%3D#) - Tested NOK

Steps:
1. Connect Aptos network
2. Click outside the Rise pop-up window
3. Click on Connect wallet
4. Select Rise wallet
5. Observe

Actual result: An unexpected error has occurred. Please refresh the page.` TypeError: Cannot read properties of undefined (reading 'toLowerCase')` is shown when user backgrounds the first pop-up notification from a wallet and tries to again connect the same wallet

Expected result: Wallet pop-up should again be shown on the screen

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b6e643ed-be37-41f8-93a7-80ebe38c319e

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect.netlify.app/. 
Issue is no longer reproducible.

Closing the ticket.
