### ISSUE TITLE
[QA] Select Network and Asset screens are not well accessible in landscape mode

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#211]
Preconditions: Phone view in landscape

Environment: iPhone 14 Plus, iOS 16.0.1, Safari

Steps:
1. Click on Network section
2. Scroll through the list
3. Close Network section
4. Click on Assets
5. Scroll through the list of Assets
6. Observe

Actual result: Asset and Network screens are not supported in landscape mode.

Expected result: Landscape mode is supported.

Attachment:

https://user-images.githubusercontent.com/91047061/225555364-38c3c744-e7a7-45cb-a3d8-d09fc92a1ac6.MP4

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] with Samsung S20 (Android 12).

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] with iPhone 11 Pro 16.5.1 and Google Chrome 114.0.5735.124. Networks, Assets and Wallets lists are not well accessible in landscape mode.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Environment: iPhone 14, iOS 16.0
User is not able to scroll though asset list in landscape mode.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6cef35c9-087d-4a57-a569-4f33c14aab4c

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Checked on iPhone 11 Pro with Google Chrome Version 125.0.6422.80.

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2360
