### ISSUE TITLE
[QA][Solong] First pop-up opens just as a black screen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2119]
Precondition:
Solong wallet connected for Solana

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 124.0.6367.210

Tested from:
https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Prepare to send 0.0001 FTM from Fantom to Solana
2. Observe that Create account message is shown
3. Click on Create account
4. Observe Solong wallet pop-up window

Actual result: Black Solong wallet pop-up window is opened, user is not able to confirm the action

Expected result: User is able to confirm the action in wallet pop-up

Comments: Noticed this when starting a transaction as well, second pop-up opens with option to Confirm the actions

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c943aa30-ea1b-47fb-94b7-df4a2376037d

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/852526ff-a464-40ff-95c9-e2af9b4824f9)

Ticket is closed.

**Comment by tsadovska** [comment]
Reopening the issue. It is reproducible on https://preview.portalbridge.com/933197c94d/ [Mainnet] when sending W from Ethereum (MetaMask) to Solana (Solong). Black screen opens after user clicks on "Claim" button. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95807457-5f6a-4b0c-b61f-76099639adb3)

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ [Mainnet] with the same scenario, when sending W from Ethereum (MetaMask) to Solana (Solong).


https://github.com/user-attachments/assets/2aa9dd22-3664-4113-99a5-3937916f81cb

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ when sending 0.0001 FTM from Fantom (MetaMask) to Solana (Solong). Blank Solong notification opens after user clicks on "Claim" button. Link to [Wormholescan](https://wormholescan.io/#/tx/0xa5d1176a2b6b150c13b8b5803e493a1b780bd3756d7ef8f6884a47f652e32294). 

![image](https://github.com/user-attachments/assets/80e49f91-9d30-4b19-a2af-6e1ef41ed388)
