### ISSUE TITLE
[QA]Wallet drop down appears on the left side, when console is opened

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2120]
Precondition:
Console is open

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 124.0.6367.210

Tested from:
https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#

Steps:
1. Select Any network (e.g. Base)
2. Click on wallet
3. Observe the drop down list

Actual result: Wallet drop down list opened on the left side of the screen when console is open

Expected result: Drop down list is opened under Connect wallet

Attachment:
<img width="1309" alt="Screenshot 2024-05-23 at 11 05 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2ba5eb30-78ed-40ab-9bb9-19dec00bd9ae">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/72e25375-f303-4109-b88f-4af28bf84dfe

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D).
Issue is no longer reproduced when changing the screen size, if the dropdown is open - it moves in accordance with the screen.

Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-09-03 at 12 09 35" src="https://github.com/user-attachments/assets/c5289904-d7f8-4347-b775-f7af94cd2078">
