### ISSUE TITLE
[QA] [Mainnet] Asset selection possible in From section, but there is no route available to send the asset - ETH (Blast)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2123]
## Describe the current behavior in detail
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGQ5pu%2BIoLC4Rk3DPmLCxCNrkxFAUQAqACWWr1xAL4gnQA%3D) with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64).

Steps:
1. Prepare to send ETH (Blast) from Blast (MetaMask)
2. Check for available routes when any network is selected in the 'To' section

Actual result: No routes available.
Expected result: At least one route is available or a warning is displayed.

## Notes/ Attachments

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/73f15d75-d9eb-4e22-89fa-2294987436d4)

**Comment by agodlevska** [comment]
Issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (connect v2).
No routes or warning/error notifications.

```
Error: Wormhole Token Bridge Relayer contract for domain Blast not found
    at new C (index-p1gv-U9u.js:1:4631)
    at EvmChain.getProtocol (main-DlCXFGuc.js:240:246354)
    at async AutomaticTokenBridgeRoute.supportedSourceTokens (main-DlCXFGuc.js:245:43855)
    at async SDKv2Route.supportedSourceTokens (main-DlCXFGuc.js:273:68256)
    at async main-DlCXFGuc.js:275:203434
    at async Promise.all (/index 2)
    at async RouteOperator.allSupportedSourceTokens (main-DlCXFGuc.js:275:203387)
    at async main-DlCXFGuc.js:312:93423
``` 

Attachment:
<img width="1436" alt="Screenshot 2024-09-03 at 11 58 15" src="https://github.com/user-attachments/assets/06ffceb3-e6b8-4062-95ec-5b455d0c4fc4">
