### ISSUE TITLE
[QA] “Custom config” allows select an asset that is not available for selection

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2124]
## Describe the current behavior in detail
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ismu74igsIbkxFeiAF8QLoA%3D%3D%3D) with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64). 

Steps:
1. Prepare to send asset from Avalanche (MetaMask) to Blast (MetaMask)
2. Open "Custom config"
3. Fill in the field: token 'ETH'
4. Click outside Custom config block 
5. Check Asset in 'From' section

## Notes/ Attachments

![Screenshot 2024-05-23 at 14 56 25](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3c5461b8-7652-4475-803c-edf9821996a8)

**Comment by agodlevska** [comment]
Tested on [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ismu74igsIbkxFAUQAqACT0QAviB9A) and [Testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ismu74igsIbkxFAUQAqACT0QAviB9A), issue no longer reproduces.
Closing the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-06-10 at 10 44 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/6d9cf614-58e2-4e18-b788-05b954378c78">
