### ISSUE TITLE
[QA] Error: Nonce too low, when starting transfer from Goerli, through WalletConnect wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#213]
Preconditions: Wallet is connected through Wallet Connect (QR code) to the mobile device

Environment: 
iPhone 14 Plus, iOS 16.0.1, Safari
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Networks From - Goerli, To - Fantom
2. Select Asset - ETH
3. Type in the amount (e.g. 0.0432)
4. Choose pay with two transactions
5. Click "Approve and proceed with transaction"
6. Confirm the transaction on mobile device
7. Observe

Actual result: Error message "Error sending transfer, please try again" is shown on the Bridge screen and on the mobile pop-up "Transaction error - nonce too low" is shown.

Expected result: Transaction is successfully completed.

Attachments:

https://user-images.githubusercontent.com/91047061/225582164-97582b80-f02f-4839-a29a-57af1ab33fd2.mov

![IMG_0128](https://user-images.githubusercontent.com/91047061/225582323-23be22c6-1e15-4c6b-9d6a-eaec9aef1199.PNG)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect.netlify.app/
Transaction from [Goerli](https://goerli.etherscan.io/tx/0x2dffb1d3169e62a3c5e768d285c6ea9bfad5f0fa75d28dea8876ec0877691b9a) (WalletConnect-Metamask) -> [Fantom](https://testnet.ftmscan.com/tx/0xe45847347a03732cdf9559e4a565dad761c3c2808f778cb27b23da4f41ae7bea) (WalletConnect-Metamask) was completed
Tested from: iPhone 14, iOS 16, Metamask app
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e1515bd1-39b2-40a4-9eeb-0fc0279119bc
