### ISSUE TITLE
[QA] Warning message “Amount cannot exceed balance” is not automatically updated when wallet is changed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#215]
#### Steps:
1. Connect Solflare wallet (user has less than 1 SOL in Solflare wallet)
2. Select Solana network and SOL asset 
3. Type amount that exceeds balance (e.g. 1)
4. Click “Approve and proceed with transaction” button
5. Change wallet to Phantom (user has more than 1 SOL in Phantom wallet)
6. Observe

#### Actual result:
Warning message “Amount cannot exceed balance” does not automatically disappear. Warning message is no longer displayed when user clicks on “Approve and proceed with transaction” button again.

#### Expected result:
Warning message “Amount cannot exceed balance” is no longer displayed.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome Version 111.0.5563.64 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/225625576-dbb66cef-86a5-40c2-afbf-045b0ecde657.mov

**Comment by anondev2323** [comment]
Seems to work on the latest netlify deploy. Tried with Metamask as well as Phantom/Solflare

https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/9fb11933-6ebd-459c-8cf4-4e5f31cd2989

https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/120d361d-b3b9-4e4e-baed-16814d4df6c9

**Comment by tsadovska** [comment]
Thank you! Rechecked on https://wormhole-connect.netlify.app/ , issue is no longer reproducible. Warning message is automatically updated. Closing the ticket.
