### ISSUE TITLE
[QA] [Mainnet] Cannot send asset through Native Token Transfer Automatic route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2151]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.113 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask)
2. Select "Native Token Transfer Receive tokens automatically" route
3. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails.

`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}`

`Wormhole Connect: error completing transfer {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}`

Expected result: Transaction proceeds without errors.

## Notes/ Attachments
* Issue is not reproducible when sending asset via "Native Token Transfer Approve tranfer with destination wallet" route.
* Issue is also reproducible on https://portalbridge.com/.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95eecd22-7e1d-47f3-b261-2a12dd75b5c2)

**Comment by tsadovska** [comment]
* https://portalbridge.com/ [Mainnet], USDC.e transfer with NTT Automatic route from Fantom (MetaMask) to Ethereum (MetaMask) 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a2d7f97e-34cd-49e2-a2ff-3e6de44da72b)

* https://preview.portalbridge.com/ac15114854/ [Mainnet], osETH transfer with NTT Automatic route from Arbitrum (MetaMask) to Ethereum (MetaMask)

`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}`

`Wormhole Connect: error completing transfer {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}`

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9938661d-56f4-4210-9a13-beeba0a2f802)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].
 * Send from tx: [FTMScan](https://ftmscan.com/tx/0x63d1e06d07aaadecc9e2c1c03e732a313515f9c7e2d6e714af614b3516eeda9d)
 * Send to tx: [Etherscan](https://etherscan.io/tx/0x3cc6109802e1066915d880e3be05c8dfeb1d8222ef117dbcd4f934e9c7c21da0)
 * Link to [Wormholescan](https://wormholescan.io/#/tx/0x63d1e06d07aaadecc9e2c1c03e732a313515f9c7e2d6e714af614b3516eeda9d)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/35937717-9a1f-431c-803b-e61a6c6cac9d)

Ticket is closed.

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/63d956a348/, reopening the ticket.
Sending 1 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask)

Attachment: 
<img width="1440" alt="Screenshot 2024-06-14 at 11 36 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/12faa689-4912-4879-a8c1-651d91ffeb59">

**Comment by agodlevska** [comment]
The transaction did not go through due to insufficient FTM balance, after replenishment the transaction was successful, there were no errors. 
Сlosing the ticket.
<img width="1419" alt="Screenshot 2024-06-14 at 12 37 52" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/ecad5558-0172-42c1-b6e7-f80a15759e78">
