### ISSUE TITLE
[QA] "X Layer" icon is not well displayed on mobile

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2157]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with iPhone 11 Pro iOS 17.4.1 and Google Chrome Version 125.0.6422.80. 

Steps:
1. Open https://wormhole-connect.netlify.app/  on mobile
2. Select "X Layer" network as source chain
3. Check the icon

Actual result: "X Layer" icon is not well displayed.
Expected result: "X Layer" icon is well displayed.

## Notes/ Attachments

<img width="318" alt="X Layer icon" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/90daf8d4-0899-46a3-80a0-144e4855b944">

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/ and [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2).

Now everything looks good, the icon looks correct on both the old and new versions. 
Attachments:
<img width="379" alt="Screenshot 2024-08-22 at 11 57 58" src="https://github.com/user-attachments/assets/2a57cf89-db7d-4fbd-a5de-2e39418834c0">
![Screenshot_2024-08-22-11-57-03-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/de0d166c-30ec-4814-8300-a6762ed77ccb)
