### ISSUE TITLE
[QA] Error: Not supported, for transaction from MetaMask to WalletConnect (app)

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#216]
Preconditions: 
1. Wallet at sending from connected through MetaMask Chrome extension
2. Wallet at sending "To" section connected through WalletConnect app (e.g. Zerion)
3. Console is open

Environment:
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Zerion app v2.13.0

Steps:
1. Select Networks at From and to Sections (e.g. Fuji and Alfajores)
2. Select Asset (e.g. AVAX)
3. Enter the amount
4. Click pay with (two transactions)
5. Click "Approve and proceed with transaction"
6. Click Confirm on MetaMask Chrome extension pop-up
7. Click "Claim" on transaction screen when option is given
8. Observe

Actual result: "Your claim has failed, please try again" is shown to the user.

Expected result: Transaction is completed.

Attachment:

https://user-images.githubusercontent.com/91047061/225623809-0fd2042e-a833-446d-b0cb-ededca5d68b2.mov

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Tested NOK.
User is not able to send asset from Metamask wallet to WalletConnect Zerion desktop app. Error in console: `Error: Missing or invalid. request() method: wallet_addEthereumChain`
Environment: Zerion desktop app v 2.13.0
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d18b2bc8-ef44-4240-b622-9c75e216af69

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 AVAX from Avalanche (Metamask) to Celo (Zerion). 

Error appears in Console when clicking on Claim button:
```
Error: Missing or invalid. request() method: wallet_addEthereumChain
    at Ha.isValidRequest (main.ff0584f4.js:2:10883970)
    at async Ha.request (main.ff0584f4.js:2:10867433)
    at async Wa.request (main.ff0584f4.js:2:10890439)
    at async Is.request (main.ff0584f4.js:2:10969451)
    at async js.request (main.ff0584f4.js:2:10980978)
    at async tc.request (main.ff0584f4.js:2:10989908)
    at async v4.evm.mO.walletConnect.connectorOptions.projectId.addChain (main.ff0584f4.js:2:18661018)
    at async v4.evm.mO.walletConnect.connectorOptions.projectId.switchChain (main.ff0584f4.js:2:18660784)
    at async w4 (main.ff0584f4.js:37:280414)
    at async Object.onClick (main.ff0584f4.js:190:99470)
```

User has 0.4 CELO on Celo in Zerion wallet. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cc50ccdd-ab3a-45a7-83fb-0fb50ddafa39)

**Comment by AigaD** [comment]
Will re-check after https://github.com/wormhole-foundation/wormhole-connect/issues/1495 is fixed

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1495
