### ISSUE TITLE
[QA] [Mainnet] USD equivalent of osETH is not displayed 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2165]
## Describe the current behavior in detail
Environment: 

- https://preview.portalbridge.com/ac15114854/ [Mainnet]
- https://preview.portalbridge.com/63d956a348/ [Mainnet]

Checked with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Prepare to send osETH from Arbitrum (MetaMask) to Ethereum (MetaMask)
2. Enter Amount (in my case, 0.00019)
3. Observe USD equivalent of osETH

Actual result: USD equivalent of osETH is not displayed.
Expected result: USD equivalent of osETH is displayed.

## Notes/ Attachments

![Screenshot 2024-06-04 at 09 36 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4fd5746a-cfa7-44cd-ac34-0ec2135a1d46)

**Comment by agodlevska** [comment]
Issue is reproducible on https://portalbridge.com/. 

Attachment:
<img width="811" alt="Screenshot 2024-07-26 at 10 40 51" src="https://github.com/user-attachments/assets/f6906ebb-6f45-4711-b1b1-d6a2321545c5">

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/321a610744/ when sending 0.00001 osETH from Arbitrum (MetaMask) to Ethereum (MetaMask). 

Attachment:
<img width="531" alt="Screenshot 2024-08-15 at 10 28 30" src="https://github.com/user-attachments/assets/6ba7fe80-d6fe-405b-a915-2bdc1174b9e3">

**Comment by agodlevska** [comment]
Issue is reproducible on hhttps://preview.portalbridge.com/b3b7091778/ when sending 0.000001 osETH from Arbitrum (Rabby) to Ethereum (Rabby).
