### ISSUE TITLE
[QA] Bug sending ERC-20 tokens from BSC

### ISSUE THREAD

**Issue by anondev2323** [wormhole-foundation/wormhole-connect#218]
## Describe the current behavior in detail

<img width="548" alt="Screen Shot 2023-03-16 at 2 13 49 PM" src="https://user-images.githubusercontent.com/122566365/225714803-a10baf52-bb2e-4fa2-bba0-d52427db0407.png">

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/466 is resolved
