### ISSUE TITLE
[QA] [Testnet] An "Unexpected error" occurs when Sei network is selected 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2181]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Preconditions:
Leap, Keplr, Fin, Compass wallets are not installed or are disabled. 

Steps:
1. Select Sei network as source chain
2. Observe

Actual result: An unexpected error has occurred. 

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Send (main-0-9QBYvg.js:547:34001)
    at Nh (main-0-9QBYvg.js:39:18929)
    at cj (main-0-9QBYvg.js:41:3497)
    at Vk (main-0-9QBYvg.js:41:49475)
    at Uk (main-0-9QBYvg.js:41:43863)
    at Tk (main-0-9QBYvg.js:41:43786)
    at Ik (main-0-9QBYvg.js:41:43626)
    at Nk (main-0-9QBYvg.js:41:39598)
    at Ek (main-0-9QBYvg.js:41:40496)
    at jg (main-0-9QBYvg.js:39:3536)
```

Expected result: Error does not occur after selecting a network. 

## Notes/ Attachments
Issue is not reproducible when Leap extension is enabled. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5d10d585-0fbf-4718-8375-7ee1b9b4a089)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/. 
Leap, Keplr wallets are not installed or are disabled.

Attachment: 

https://github.com/user-attachments/assets/8262af29-5005-4d60-81b8-4a938199ad7d

**Comment by tsadovska** [comment]
Issue happens when the setting is `useRedesign: false`. It does not happen when the setting is `useRedesign: true`.

**Comment by tsadovska** [comment]
Closing the ticket, because Sei network currently is not displayed in the list of networks on testnet.
