### ISSUE TITLE
[QA] [Testnet] Cannot change slider position when sending SOL from Solana to Sui

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2188]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.5 and Google Chrome Version 125.0.6422.113 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.1 SOL from Solana (Phantom) to Sui (Sui Wallet)
2. Enable "Native gas" section
3. Change slider position

Actual result: Cannot change slider position.
Expected result: Slider position can be changed.

## Notes/Attachments

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/9f2b357a-7443-4b4a-893e-b5342f877351

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2).
Ticket is closed.
