### ISSUE TITLE
[QA] Error message is shown for a second when claiming the asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2202]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/2c6f665417/ [Mainnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Preprare to send 0.001234 WSOL from Solana (Phantom) to BSC (Rabby)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button 

Actual result: Error message is shown for 1 second, but then transaction completes successfully. Asset is received.  
`{code: -32000, message: 'transaction indexing is in progress', data: 'transaction indexing is in progress'}`

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments
Issue is not reproducible with MetaMask wallet. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c12c193d-69e1-489d-9dbe-11343e2f4db1

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Issue is no longer reproducible, transaction proceeds without errors, [Wormholescan](https://wormholescan.io/#/tx/2qApNffRSciANkzo9pwSh35ZRNhK32NsE5vfL8rr6utqzi5UXpk97ZsARSqvw5W5ja6pXvtU4wV8CAzGti1hCekc).

Closing the ticket. 

Attachment:


https://github.com/user-attachments/assets/6ae9636f-f872-4f98-a2ae-15e6ae2bb61e
