### ISSUE TITLE
[QA] [Mainnet] Fee value should have more decimals after comma - KUJI

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2203]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/2c6f665417/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 APT from Kujira (Leap) to Osmosis (Leap)
2. Check "Source chain gas estimate" value in Preview section
3. Click "Approve and proceed with transaction" button
4. Check Gas fee value in Leap notification

Actual result: 
- Fee value on wormhole-connect / Portal Bridge is ~ 0 KUJI ($0.00)
- Fee value in Leap wallet is 0.00340 KUJI (<$0.01)

Expected result:
Fee value on wormhole-connect / Portal Bridge should have more decimals after comma.

## Notes/ Attachments
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/28ec36af-83c8-41c3-a20f-daf7119b4464)

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/321a610744/ when sending 0.001 WAVAX from Kujira (Leap) to Injective (Leap). 

- Fee value on Portal Bridge is ~ 0 KUJI ($0.00)
- Fee value in Leap wallet is 0.00340 KUJI (<$0.01)

Attachment: 
<img width="698" alt="Screenshot 2024-08-15 at 12 23 23" src="https://github.com/user-attachments/assets/06cc9414-da67-4be8-bed4-830e2432b15e">

<img width="406" alt="Screenshot 2024-08-15 at 12 23 14" src="https://github.com/user-attachments/assets/a5e6287b-aa09-4e89-b116-bbc521eb4208">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.
Kujira network is no longer available in Networks list.

Closing the ticket.
