### ISSUE TITLE
[QA] Relayer fee is not displayed when sending USDC from Ethereum to Fantom with NTT Automatic route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2210]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 126.0.6478.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.1 USDC from Ethereum (MetaMask) to Fantom (MetaMask)
2. Select "Native Token Transfer Receive tokens automatically" option in "Route" section
3. Expand "Total fee estimates" in "Preview" section
4. Check "Relayer fee" value

Actual result: Relayer fee is not displayed. 
Expected result: Relayer fee is displayed. 
 
## Notes/ Attachments

![Screenshot 2024-06-19 at 12 52 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aad403dc-cadb-4032-b0ce-8031ad72f3da)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8b6491733c/ [Mainnet] when sending 0.3 USDC from Ethereum (MetaMask) to Fantom (MetaMask). 


![Screenshot 2024-06-26 at 13 11 01](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ad8aaa56-a710-45ae-a15d-c79351707fad)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/ when sending 0.3 USDC from Ethereum (MetaMask) to Fantom (MetaMask). 

Attachment:
<img width="487" alt="Screenshot 2024-09-06 at 12 27 57" src="https://github.com/user-attachments/assets/f117e789-7122-42f8-945e-046cbd8d89aa">
