### ISSUE TITLE
[Bug] Token Registration Issue. Arbitrary Token. Ethereum > Solana

### ISSUE THREAD

**Issue by yanmarinich** [wormhole-foundation/wormhole-connect#2214]
Description:
I have registered the VRD token and added to Wormhole Connect configuration, including its wrapped asset details. However, when attempting to use the token, I encounter the error message: "This token is not registered, you must register it before you continue. Newly registered tokens will not have liquid markets."

Steps to reproduce:

1. Set up the WormholeConnect configuration with the following details:
```
import WormholeConnect, {
  WormholeConnectConfig,
} from "@wormhole-foundation/wormhole-connect";

const config: WormholeConnectConfig = {
  networks: ["solana", "ethereum"],
  env: "mainnet",
  tokens: ["VRD"],
  bridgeDefaults: {
    fromNetwork: "ethereum",
    toNetwork: "solana",
    token: "VRD",
  },
  tokensConfig: {
    VRD: {
      key: "VRD",
      symbol: "VRD",
      nativeChain: "ethereum",
      wrappedAsset: "APSRGqgDWCfR483RLx6HiWF8oaU2SQ4wmnQLJaTiSkkv",
      tokenId: {
        chain: "ethereum",
        address: "0xf25304e75026E6a35FEDcA3B0889aE5c4D3C55D8",
      },
      coinGeckoId: "viridis-network",
      icon: "https://assets.coingecko.com/coins/images/32709/standard/200x200.png?1698986518",
      color: "#2894EE",
      decimals: {
        default: 18,
      },
      foreignAssets: {
        solana: {
          address: "APSRGqgDWCfR483RLx6HiWF8oaU2SQ4wmnQLJaTiSkkv",
          decimals: 8,
        },
      },
    },
  },
};

function App() {
  return <WormholeConnect config={config} />;
}

export default App;

```

2. Start the application.
3. Attempt to bridge the VRD token from Ethereum to Solana.

**Experienced behavior:**
The application displays an error message: "This token is not registered, you must register it before you continue. Newly registered tokens will not have liquid markets."

**Expected behavior:**
The application should recognize the VRD token as registered and allow the bridging process to proceed without errors.

**Solution recommendation:**
Please verify if the VRD token configuration is correctly set up in the Wormhole Connect system and ensure that new tokens with wrapped assets are correctly recognized and registered.

Additional Information:

Package versions:

```
{
  "name": "viridis-wormhole",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@wormhole-foundation/wormhole-connect": "^0.3.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "typescript": "^5.2.2",
    "vite": "^5.2.0"
  }
}
```

Attestation:
https://etherscan.io/tx/0x367b1b7cb6f68b6d832e5c0bf1d3297b9ec65462e022e6cd469b523a921498c1

https://wormholescan.io/#/tx/0x367b1b7cb6f68b6d832e5c0bf1d3297b9ec65462e022e6cd469b523a921498c1?network=MAINNET

Source Token 
https://etherscan.io/token/0xf25304e75026e6a35fedca3b0889ae5c4d3c55d8

Wrapped Token
https://solscan.io/token/APSRGqgDWCfR483RLx6HiWF8oaU2SQ4wmnQLJaTiSkkv

**Comment by Venlickjalj** [comment]
hello, bro, I have the same issue
 May I ask how you resolved it in the end?
