### ISSUE TITLE
[QA] Asset is displayed in lowercase instead of uppercase on WormholeScan

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2218]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 126.0.6478.62 (Official Build) (arm64).

Steps:
1. Prepare to send 0.1 CELO from Celo (MetaMask) to Ethereum (MetaMask)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Click on "View on Wormholescan" link
5. Check the asset in "Target chain" section 

Actual result: Asset is displayed with lowercase.
Expected result: Asset is displayed with uppercase.

## Notes/ Attachments
* Send from tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0xc8ba162fdfc3813116c14d5988e9d1e52b586cfcf69d8e80e5715004b2125d1b)
* Send to tx: [Etherscan](https://etherscan.io/tx/0xd2529e27e21395acf243f32ea9122792247e976f601186f98f75eb247a0f6cb3)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xc8ba162fdfc3813116c14d5988e9d1e52b586cfcf69d8e80e5715004b2125d1b)

![Screenshot 2024-06-21 at 20 36 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ee1076b3-abeb-40e1-ab79-b4736197a1c1)

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible.

- [Wormholescan 1](https://wormholescan.io/#/tx/0x4d4c92f650632cd10ee804b4ef4ee24c37d58f84d7c1d64f11d4df9cef7c722f)
- [Wormholescan 2](https://wormholescan.io/#/tx/0xf19af6a320eb987a546191150c30b63d42be057886a3061f11d477c232c68eb9)
- [Wormholescan 3](https://wormholescan.io/#/tx/0xe5ae98eb66192b7c04efbd2632bb866ef399f1465d08cd2a686e3e3518427866)
- [Wormholescan 4](https://wormholescan.io/#/tx/7KiNhqX2DqpQTGtF9GEZGdGLbEYK68BFWRKd8Yng31uH)
- [Wormholescan 5](https://wormholescan.io/#/tx/H37zUaUBc6FV7wLh4sX7awA9v6S7cBW9PtuuGnkLx7Hy)

Closing the ticket.
