### ISSUE TITLE
[QA] Transactions to Base are stuck on Step 2 with message "Waiting for relayer. . ."

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2221]
## Describe the current behavior in detail

Checked on https://preview.portalbridge.com/954c469c33/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.63 (Official Build) (x86_64).

Steps:

1. Prepare to send 1 DAI from Arbitrum (MetaMask) to Base (MetaMask) or resume transaction `0xc3a265deb2ed0f50dd1afb83579f7ef8703a38237fb7bb48aaad614491723aac` (Arbitrum)
2. Click "Approve and proceed with transaction" button
3. Check if transaction is completed

Actual result: Transaction is stuck on Step 2 with message "Waiting for relayer. . ." (waiting more than 6 hours). 
Expected result: Transaction is completed.

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-06-25 at 17 31 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/e671cbd2-5c4f-40bd-af27-3046a4ca5210">

**Comment by tsadovska** [comment]
Rechecked on https://preview.portalbridge.com/954c469c33/ [Mainnet].
Transaction mentioned in the ticket is successfully completed:
* Send from tx: https://arbiscan.io/tx/0xc3a265deb2ed0f50dd1afb83579f7ef8703a38237fb7bb48aaad614491723aac
* Send to tx: https://basescan.org/tx/0x584c4210fa6bf15524d86d550d4cdb8bf7b16cca50c9b79cb082a3e294c25b48
