### ISSUE TITLE
[QA] [Testnet] Transactions to/from Sui fail

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2234]
## Describe the current behavior in detail
Checked https://wormhole-connect.netlify.app/ [Testnet] with macOS 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.001 SOL from Solana (Nighlty/Solflare) to Sui (Sui)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen

Actual Result: "Error with transfer, please try again" error appears and error in console. 

```
Error: Transaction failed with the following error. Package object does not exist with ID 0x562760fc51d90d4ae1835bac3e91e0e6987d3497b06f066941d3e51f6e8d76d0
    at dapp-interface.js:1:63892
    at dapp-interface.js:1:18198
    at a._next (dapp-interface.js:1:17632)
    at t.next (dapp-interface.js:1:10318)
    at dapp-interface.js:1:63809
    at a._next (dapp-interface.js:1:17632)
    at t.next (dapp-interface.js:1:10318)
    at dapp-interface.js:1:18191
    at a._next (dapp-interface.js:1:17632)
    at t.next (dapp-interface.js:1:10318)
``` 

Expected Result: Claiming on Sui is successful.

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-07-09 at 17 11 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/9df556f6-a74b-46eb-a8d3-0b42a69156ef">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D).

Checked following scenarios:
* SOL transfer from Solana (Phantom) to Sui (Sui wallet). Link to [Wormholescan](https://wormholescan.io/#/tx/3BP8BLXXjjv8z51w1sB6oxwrq1vA7rYhoM21W1DXQCf1E3p1HRL8BHFZfGfXgcGpdSTjpQRg78iVBsmTShuPej9n?network=TESTNET).
* SUI transfer from Sui (Sui wallet) to Fantom (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/3gjjmJXnB2nJs4XE82Q8uRiPZE9JV21Z1JaBppWdvmfL?network=TESTNET). 

![image](https://github.com/user-attachments/assets/8178bab1-78d3-48fe-81da-18459626c56c)

Closing the ticket.
