### ISSUE TITLE
[Bug] Connect should not automatically connect a Wallet Connect wallet for the destination wallet

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#2240]
## Description and context
Connect should not assume and auto-connect an EVM wallet as the destination if the source wallet was connected via Wallet Connect. For example, Safe multisigs (connected via Wallet Connect) are not automatically deployed to all EVM chains and a Safe that exists on one EVM chain likely does not exist on another.

## Steps to reproduce
1. Connect an Eth Safe multisig as the source wallet and choose an asset.
2. Choose BSC as the destination chain.
3. Note that the source wallet is automatically connected as the destination wallet.

![Screenshot 2024-07-09 at 4 26 26 PM](https://github.com/wormhole-foundation/wormhole-connect/assets/689351/08aa33ed-eec6-4cbc-9dad-e6827f12ad64)

## Expected behavior
If the source wallet was connected with Wallet Connect, disable logic that auto-connects the source wallet as the destination wallet if an EVM chain is selected as the destination wallet.

**Comment by emreboga** [comment]
Note: In the redesign we do not auto-connect destination wallet at all and require user's action to do so after connecting a source wallet.

**Comment by sebastianscatularo** [comment]
fix merged, closing it
