### ISSUE TITLE
[Bug] UI errors attempting to transfer wstETH from BSC to Eth Multisig

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#2241]
## Description and context
The UI shows "Error with transfer, please try again" while attempting to transfer wstETH from BSC to an Eth Safe Multisig. When you look at the transactions actually submitted by the wallet, the transactions seem to be going through.

## Steps to reproduce
1. Set up a transfer of wstETH from a BSC EOA to an Eth Safe multisig.
2. Initiate the transfer, which triggers a token approval signature.
3. Sign the transaction and notice the "Error with transfer, please try again":
> pb-index-CiHkcnmS.js:742 Wormhole Connect: error completing transfer 
{code: -32000, message: 'transaction indexing is in progress', data: 'transaction indexing is in progress'}
4. Click the "Approve and proceed with the transaction" button and notice that the same error message shows, although the actual transaction seems to be successful:
> pb-index-CiHkcnmS.js:742 Wormhole Connect: error completing transfer 
{code: -32000, message: 'transaction indexing is in progress', data: 'transaction indexing is in progress'}

![Screenshot 2024-07-09 at 4 44 24 PM](https://github.com/wormhole-foundation/wormhole-connect/assets/689351/a7b64d24-a69a-428d-a766-da915cbc5eab)

5. If you go to "Resume transaction" and enter in the transfer txn, you will get to a successful transaction screen:
![Screenshot 2024-07-09 at 4 46 12 PM](https://github.com/wormhole-foundation/wormhole-connect/assets/689351/bea832a2-14fd-4722-aa86-eb99faba704d)

Successful txns:
- token approval: https://bscscan.com/tx/0x25a62374ffa8403ba83a1ecea1d34a98748d58ac6661777fcde64a71a296271c
- transfer from BSC: https://bscscan.com/tx/0x86778955c61aa424f0605900a448099935b2a50247c0e0d9f9ff6602aec976d7
- receipt on Eth: https://etherscan.io/tx/0x0f30c72b9761c3f178f3d9b3a22f112d8dcca2e354c52638b8ecd48a701e1c7f

## Solution recommendation
Neither the BSC token allowance approval nor the attempted transfer should show an error message, and the UI should progress to the transaction in progress screen.

**Comment by tsadovska** [comment]
Can reproduce this issue on https://portalbridge.com/ [Mainnet]. 
Redeem screen does not open for transaction that is in progress. 
Checked the same scenario that is mentioned in the description: 0.00001 wstETH transfer from BSC (Rabby, EOA) to Ethereum (WalletConnect, Safe{Wallet} multisig app on iPhone).

Error was shown on the screen, but transaction was completed successfully. 
* Send from tx: [BscScan](https://bscscan.com/tx/0x85ee3f0301867eae99d2619dba90d2a37a5e93b5379cbc1181f13edbd9282ca7)
* Send to tx: [Etherscan](https://etherscan.io/tx/0xff5ff6a0f4757fcf6f22d66d54e54dc6d169c378da20894ee75534ccbcebc262)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x85ee3f0301867eae99d2619dba90d2a37a5e93b5379cbc1181f13edbd9282ca7)




https://github.com/user-attachments/assets/a3ab5956-ef80-4256-b12c-895fcbc479ea

**Comment by mliu-xlabs** [comment]
https://www.notion.so/wormholefoundation/Manual-Address-Input-Spec-de2d405de0d14e87800bb4dd04b7d948?pvs=4
