### ISSUE TITLE
[QA] Transactions from Solana to EVM networks fail on Step 2, invalid EVM address error

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2242]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect.netlify.app/ with macOS and Google Chrome Version 126.0.6478.127 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.001 SOL from Solana (Solflare/Nightly) to BSC (MetaMask) with Manual Bridge
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen
4. Check if transaction is completed

Actual Result: The transaction fails on the Step 2 with the invalid EVM address error. 

```
Error: Invalid EVM address 6,155,136,87,254,171,129,132,251,104,127,99,70,24,192,53,218,196,57,220,26,235,59,85,152,160,240,0,0,0,0,1 expected first 12 bytes to be 0s
    at b.trimUniversalAddress (evm-C-lk1FNZ.js:2:4140)
    at new b (evm-C-lk1FNZ.js:2:3554)
    at B.redeem (index-CQMmy3LS.js:1:3489)
    at async ssw (main-DpR6Nu3N.js:260:7671)
    at async signSendWait (main-DpR6Nu3N.js:260:7475)
    at async TokenBridgeRoute.complete (main-DpR6Nu3N.js:260:45600)
    at async Object.Ut [as onClick] (main-DpR6Nu3N.js:298:1360)
``` 
Expected Result: The transaction completes without errors. 

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-07-10 at 10 05 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/5518fa77-4c2c-454e-a500-86bc927c4c90">

**Comment by Sweetmind300** [comment]
@agodlevska
This issue has been preview on the Pull Requests. To resolve, Contact the official DefiProtocol page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/2365 is resolved.

**Comment by tsadovska** [comment]
* Transaction completed successfully on https://wormhole-connect-mainnet.netlify.app/ (Connect v2), [link to Wormholescan](https://wormholescan.io/#/tx/3reJJwPX7awpoxmyoSRgjMWL7MLgHZbrRnWHYfMdBtY8HiziUBGRzgnmHRRNEYunGxUpTUm2pHFwRueU9xNmNxdx) - 0.00001 SOL transfer from Solana (Phantom) to BSC (MetaMask).
* Transaction completed successfully on https://portalbridge.com/, [link to Wormholescan](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/933980) - 0.000001 SOL from Solana (Phantom) to BSC (MetaMask). 
* Transaction is stuck at step 2 when checking on https://wormhole-connect.netlify.app/, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2424. 

Closing the ticket.
