### ISSUE TITLE
[QA] Cannot add token to the wallet - USDT

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2250]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/3365c86aff/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64). 

Steps:
1. Send 1 USDT from Base (MetaMask) to BSC (MetaMask)
2. Click on "Add USDT to your wallet" link

Actual result: MetaMask notification does not open. 

`Uncaught (in promise) {code: -32602, message: 'The decimals in the request (6) do not match the decimals in the contract (18)'}`

Expected result: Token can be successfully added to the wallet.

## Notes/ Attachments
* Send from tx: [BaseScan](https://basescan.org/tx/0xe932d0d17b302b9835b1d8cc4f64768d48dcefe66273b8d1bd5f42a55f72538b)
* Send to tx: [BscScan](https://bscscan.com/tx/0xf9f9654a321234e9b69132a2272ad2a6c6dbb096b95e8cb5cfda06180fa7c1f0)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xe932d0d17b302b9835b1d8cc4f64768d48dcefe66273b8d1bd5f42a55f72538b) 

![Screenshot 2024-07-17 at 10 43 29](https://github.com/user-attachments/assets/11b054b9-b410-4a14-aaa7-94a6a7019cca)

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/321a610744/ and on https://portalbridge.com/. 
Issue is no longer reproducible, the USDT token is successfully added to the MetaMask wallet. 
Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/80e46044-4bbb-4fdd-89ed-ac19005706f8
