### ISSUE TITLE
[QA] Transaction showed as completed when confirmations where just loading at sending from section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#226]
Preconditions:
Wallet at sending from connected with Solflare
Wallet at sending "To" section connected through WalletConnect QR code - MetaMask

Environment:
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Send 0.0321 SOL from Solflare to Mumbai
2. Click Approve and proceed with transaction
3. Observe

Actual result: All three test steps showed as complete while at sending from section the Confirmations were still in progress.

Expected result: Transaction steps happen consequently.

Comments:
Happens inconsistently, I have noticed this happening 3 times during my tests (that is why putting P2 label), so not sure what exactly triggers it.
Solana explorer - https://explorer.solana.com/tx/5M4uLyXSEa6XKRhGtib4rXZdjgNquZJuZQu1NHfRYcgvM1PxzDeNoP3Xec19zzhrPMkSPBFRguJ8f72hFaGZFukr?cluster=devnet

Attachment:
<img width="1307" alt="Screenshot 2023-03-20 at 11 51 27" src="https://user-images.githubusercontent.com/91047061/226304683-de057633-c7b7-48ae-95f4-610bc539e290.png">
<img width="1275" alt="Screenshot 2023-03-20 at 11 52 14" src="https://user-images.githubusercontent.com/91047061/226304694-e1ba72a1-f80f-4ff8-bfa6-0fbb38f32fb6.png">

**Comment by anondev2323** [comment]
Hm, I can't reproduce this now and it only happened to me 1 time. Gonna bump back to a p1

**Comment by AigaD** [comment]
Closing this as this is no longer reproducible. Will continue to observe and re-open the ticket if issue reappears.
Tested from: https://wormhole-connect.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d8702304-41de-4e67-820c-9404da15a02f
