### ISSUE TITLE
[QA] [USDT Bridge] Transaction fails after clicking on "Approve and proceed with transaction" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2260]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/3365c86aff/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64).

Steps:
1. Prepare to send 1 USDT from BSC (MetaMask) to Base (MetaMask)
2. Click on "Approve and proceed with transaction" button

Actual result: Transaction fails.

```
Error: Error computing receive amount
    at y3.computeReceiveAmountInternal (pb-index-BwgrtC5m.js:519:31243)
    at y3.computeReceiveAmountWithFees (pb-index-BwgrtC5m.js:519:31737)
    at Operator.computeReceiveAmountWithFees (pb-index-BwgrtC5m.js:519:93671)
    at Ao (pb-index-BwgrtC5m.js:742:10889)
    at pb-index-BwgrtC5m.js:742:11181
    at Rj (pb-index-BwgrtC5m.js:46:26723)
    at Ik (pb-index-BwgrtC5m.js:46:46749)
    at Xk (pb-index-BwgrtC5m.js:46:45442)
    at Qk (pb-index-BwgrtC5m.js:46:44396)
    at Fk (pb-index-BwgrtC5m.js:46:40658)
```

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/8f0bc7b2-4577-4f63-894d-1ad524a13141)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/c6532d9b17/ [Mainnet] when sending 5 USDT from BSC (MetaMask) to Arbitrum (MetaMask) or Optimism (MetaMask).

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/321a610744/ [Mainnet] when sending 8 USDT from BSC (MetaMask) to Arbitrum (MetaMask). 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-15 at 10 02 06" src="https://github.com/user-attachments/assets/9ed6b7d8-c911-4afd-9299-4a6ebdfefde9">

**Comment by agodlevska** [comment]
Reproducible on https://portalbridge.com/ [Mainnet] when sending 9 USDT from BSC (MetaMask) to Optimism (MetaMask).

Attachment:
<img width="1440" alt="Screenshot 2024-08-26 at 10 18 08" src="https://github.com/user-attachments/assets/b249e01d-0624-4721-a6d4-65a61e8557d6">
