### ISSUE TITLE
[QA] Balance should have the same amount of decimals for all tokens

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2267]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Select BSC network and connect MetaMask wallet
2. Open Assets screen
3. Check balance of BNB, USDC, WETH (BSC) assets

Actual result: Some tokens have 18 decimals, some have 6 decimals.
Expected result: Balance should have the same amount of decimals for all tokens. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/c7f9ce88-f97e-4330-9264-5f7a498490dc)

**Comment by agodlevska** [comment]
Issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2).

Tokens have completely different numbers of digits after the decimal point in the balance. 
Attachment: 
<img width="1440" alt="Screenshot 2024-08-22 at 10 46 34" src="https://github.com/user-attachments/assets/4909d843-e3dd-4f01-9b3f-2d8ff5066e61">

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2500.
