### ISSUE TITLE
[QA] An unexpected warning is displayed that bridge or swap route is not available

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2275]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Prepare to send 1 CELO from Alfajores (MetaMask) to BSC, Fuji or Moonbase (MetaMask)
2. Check if warning "No bridge or swap route available for selected tokens" is displayed 

Actual result: Warning is displayed.
Expected result: Warning is not displayed. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/f6a523f0-f510-46a8-93f7-b708b31bb12b)

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.5 USDC from Polygon (MetaMask) to Base (MetaMask). 
Warning "No bridge or swap route available for selected tokens" is displayed.

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/.
Issue is no longer reproducible, warning is not displayed.

Closing the ticket.

Attachments:
<img width="1439" alt="Screenshot 2024-10-09 at 12 09 14" src="https://github.com/user-attachments/assets/9790a75b-6f10-48af-89dc-317a53ce5e65">
<img width="1440" alt="Screenshot 2024-10-09 at 12 09 22" src="https://github.com/user-attachments/assets/f88d5950-4df2-4d4b-a6b4-c0ce08f8a2f5">
