### ISSUE TITLE
solana usdc to base dont arive

### ISSUE THREAD

**Issue by stsx21** [wormhole-foundation/wormhole-connect#2279]
hello ısent solana network usdt to base usdt stil not arive, ı sent you screen photo
![Ekran Alıntısı](https://github.com/user-attachments/assets/7c8a94a5-d3ba-451b-8eab-e7666675c463)

## Steps to reproduce

1.
2.
3.

**Comment by tsadovska** [comment]
According to data on Wormholescan and BaseScan, asset should have been received on a destination address. 

https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/914616
https://basescan.org/tx/0x413b1f60d78a6228c3c2a9801aff43f16ad7070935d1b9d7b87b20fd18ecde5b

Please tell if you are experiencing any more issues.
