### ISSUE TITLE
[QA] Balance does not load on Assets screen when opening the screen from To section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2281]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Prepare to send 0.9 WFTM from Moonbeam (MetaMask) to Avalanche (MetaMask)
2. Click on Asset in To section
3. Check if balance is loaded

Actual result: Balance does not load.
Expected result: Balance is loaded. 

## Notes/ Attachments:
Issue is not reproducible on https://portalbridge.com/ [Mainnet]. 

https://github.com/user-attachments/assets/ebfc17a2-114b-400e-a040-a61a892d05fc

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect.netlify.app/. 
Issue is no longer reproducible, balance is loaded. 

Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/985366e2-bdc0-4f40-8272-f845e16050b8
