### ISSUE TITLE
[QA] An "Unexpected error" occurs after user changes asset 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2289]
## Describe the current behavior in detail
Checked on https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Prepare to send W (Base) asset from Base (MetaMask) to Optimism (MetaMask)
2. Change asset to USDC (Base)

Actual result: An "Unexpected error" occurs.

```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Xh (pb-index-DpSSC7gq.js:44:21979)
    at dj (pb-index-DpSSC7gq.js:46:3493)
    at Wk (pb-index-DpSSC7gq.js:46:49465)
    at Vk (pb-index-DpSSC7gq.js:46:43855)
    at Uk (pb-index-DpSSC7gq.js:46:43778)
    at Jk (pb-index-DpSSC7gq.js:46:43618)
    at Ok (pb-index-DpSSC7gq.js:46:39596)
    at Fk (pb-index-DpSSC7gq.js:46:40494)
    at jg (pb-index-DpSSC7gq.js:44:3548)
    at pb-index-DpSSC7gq.js:46:37736
```

Expected result: Error does not occur.

## What is the expected/desired behavior

https://github.com/user-attachments/assets/c186f850-27b8-4321-9196-4b5943f24a46

**Comment by annemarieshev** [comment]
Hello @tsadovska 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:
1. Prepare to send SOL from Solana (Solflare) to Ethereum (MetaMask)
2. Change asset to USDC 


https://github.com/user-attachments/assets/11dd57c2-be12-4293-8921-abf60bfd60c4

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, error does not occur.

Attachment:

https://github.com/user-attachments/assets/b91fd515-4aa5-4250-b03b-6e2765dc5609
