### ISSUE TITLE
[QA] Fee should have more decimals after comma - ETH (Optimism)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2293]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/c6532d9b17/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Send 0.00001 tBTC from Optimism (MetaMask) to Solana (Backpack)
2. Check Gas fee in "Send from" section

Actual result: Gas fee is shown as 0 ETH (Optimism). 
Expected result: Gas fee has more decimals after comma. 

## Notes/ Attachments
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x8b4770d89e4e9e178cfd5a9bfc14204ce854059315f8bdfa05509fe94895880c)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/SxqXTi6EtFo9La8VZvBRNu6222cqnGzrgxWKMjiQaUi8utGh3TstWuaaiSN7JyKWy2X8n1QPXrYZzRGaVXqhfms)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x8b4770d89e4e9e178cfd5a9bfc14204ce854059315f8bdfa05509fe94895880c)

![Screenshot 2024-07-29 at 14 38 49](https://github.com/user-attachments/assets/979d4ba8-6e01-49d7-ace9-a4b8c210d3ea)

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/. 
Transaction `0x59e55742c51dd1b886c3eb83ca29b7ec40498e03f83317ba2c296d118478dac6` has been resumed and gas fee is shown as 0 ETH (Optimism). 

Attachment:
<img width="664" alt="Screenshot 2024-09-02 at 09 56 55" src="https://github.com/user-attachments/assets/c01ba157-1294-4f7a-bb65-a51857a0d1bf">
