### ISSUE TITLE
[QA] Missing revert data error appears in Console at Step 2  

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2294]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/c6532d9b17/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Steps:
1. Send 0.00001 wstETH (Optimism) from Optimism (MetaMask via WalletConnect) to Arbitrum (MetaMask via WalletConnect)
2. Click on "Approve and proceed with transaction" button
3. Open Console
4. Check for error when transaction is at Step 2 

Actual result: "Missing revert data in call exception" appears in Console.

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x0b2402144Bb366A632D14B83F244D2e0e21bD39c","data":"0xaa4efa5bc67f46c890a95d4263ceac9b7e45c8f014e1a2452a569b9b8b4a0e409d2b1461","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":0,\"message\":\"we can't execute this request\"},\"id\":null}","error":{"code":0},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x0b2402144bb366a632d14b83f244d2e0e21bd39c\",\"data\":\"0xaa4efa5bc67f46c890a95d4263ceac9b7e45c8f014e1a2452a569b9b8b4a0e409d2b1461\"},\"latest\"],\"id\":80,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://and76cjzpa.execute-api.us-east-2.amazonaws.com/arbitrum/"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (pb-index-DTP8NjvQ.js:349:46683)
    at Logger.throwError (pb-index-DTP8NjvQ.js:349:46816)
    at checkError$1 (pb-index-DTP8NjvQ.js:355:114650)
    at StaticJsonRpcProvider.<anonymous> (pb-index-DTP8NjvQ.js:355:125505)
    at Generator.throw (<anonymous>)
    at ao (pb-index-DTP8NjvQ.js:355:113927)
```

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments
Asset is received. 

![Screenshot 2024-07-29 at 15 43 35](https://github.com/user-attachments/assets/70cb7ec2-9dd0-40b4-a7c9-72a899c1ea4d)

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/, when sending 0.5 USDT from Arbitrum (Rabby) to BSC (Rabby). 

Attachment:
<img width="1440" alt="Screenshot 2024-09-03 at 18 54 19" src="https://github.com/user-attachments/assets/1106ca28-2dc8-4aaa-b9c1-7747eec285d0">
