### ISSUE TITLE
[QA] Claim transaction on Solana fails with "WalletSendTransactionError: Transaction cancelled" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2305]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 USDC from Base (MetaMask) to Solana (Solflare)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Approve Solflare notification

Actual result: Transaction fails.
```
WalletSendTransactionError: Transaction cancelled
    at qt.sendTransaction (solana-BoXYdsfJ.js:2:46318)
    at async A.sendTransaction (solana-BoXYdsfJ.js:2:41996)
    at async ae (solana-BoXYdsfJ.js:2:50783)
    at async signAndSendTransaction (main-BIXv4aXg.js:276:79303)
    at async SDKv2Signer.signAndSend (main-BIXv4aXg.js:287:146233)
    at async ssw (main-BIXv4aXg.js:245:7754)
    at async signSendWait (main-BIXv4aXg.js:245:7461)
    at async CCTPRoute.complete (main-BIXv4aXg.js:245:48762)
    at async Object.Dt [as onClick] (main-BIXv4aXg.js:320:1384)
```
Expected result: Transaction proceeds without errors.

## What is the expected/desired behavior
Note: Transaction does not complete after user tries again. 
* Send from tx: [BaseScan](https://basescan.org/tx/0x5cd719188df57d3fb1e8d8f6ec438b459dad601dc67d17120609b815bb49fbb1)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x5cd719188df57d3fb1e8d8f6ec438b459dad601dc67d17120609b815bb49fbb1)

<img width="1171" alt="image" src="https://github.com/user-attachments/assets/48589df6-b83f-4d2b-b1bc-3e04417ae672">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Transaction with scenario described above proceeds without errors.

- [Base](https://basescan.org/tx/0xea345e42fa999709cb2a84742e8cb1dead03ab7233157582d50cd497017b2d4b)
- [Solana](https://solscan.io/tx/EK7qwpCnW7u9DgwsBb2MoE6ZeqVDidE94sczz6JSZHNU9EvRB58qni4LABaHq6kByFTHBbFukLtioeSRXLNaj6k)
- [Wormholescan](https://wormholescan.io/#/tx/0xea345e42fa999709cb2a84742e8cb1dead03ab7233157582d50cd497017b2d4b)

Closing the ticket. 

Attachment:
<img width="1439" alt="Screenshot 2024-09-04 at 14 47 12" src="https://github.com/user-attachments/assets/f051ff23-d584-435c-a720-14d3ce63d0fd">
