### ISSUE TITLE
[QA] Tokens are not displayed on Arbitrum network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2307]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.72 (Official Build) (x86_64).

Steps:

1. Select Arbitrum as source chain
2. Connect MetaMask wallet
3. Open assets list

Actual result: Message "No balances detected" is shown.
```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": 0, "message": "we can't execute this request" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] } }, code=BAD_DATA, version=6.13.1)
    at makeError (main-BIXv4aXg.js:235:42962)
    at main-BIXv4aXg.js:236:215083
``` 

Expected result: Available tokens are displayed.

## Notes/Attachments
Similar issue: #2301 
![Screenshot 2024-08-01 at 11 15 34](https://github.com/user-attachments/assets/ac62f786-6c15-4e43-b185-5ff052856b9d)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2) and https://portalbridge.com/.
Closing the ticket.
