### ISSUE TITLE
[QA] Improvement: Remove from wallet list wallet supporting the same Solana network when it is already selected in one section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#231]
Preconditions: Wallet is not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. At From section connect to Solflare wallet
2. Select Network Solana
3. At To section choose Phantom wallet
4. Open Select Network section and choose any Network

Actual result: User is able to choose wallet supporting only Solana network also at To section, when transaction won't be possible.

Improvement: Do not show Solflare/Phantom wallet if in one of the sections Solflare/Phantom wallet is already connected.

Attachment:

https://user-images.githubusercontent.com/91047061/226366386-136724ed-276a-496b-8c12-284558520b9a.mov

**Comment by AigaD** [comment]
Need advice, can the wallets be removed if there is no supported Network to choose from in case that supported Network is already selected in one or another section? Or all wallets will be shown in the list in case Network isn't selected first
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2bc7f999-3823-4eba-b3d7-99cde1dfbd7a

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Solana wallets are offered to be connected in "To" section when Solana network is already selected as source chain.

**Comment by AigaD** [comment]
Closing, as now it is only possible to select Wallet, when Network is selected first and the same Network is not present at both selections for send From and Send To if selected at one of them already.
Tested from: https://wormhole-connect-mainnet.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c21671dd-818d-42da-9062-fc8d5c683422
