### ISSUE TITLE
[QA] Circle CCTP Automatic route is not offered when required transfer amount is entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2310]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64). 

Steps:
1. Prepare to send 0.260752 USDC from Arbitrum (MetaMask) to Optimism (MetaMask)
2. Select Circle CCTP Automatic route
3. Change slider position - 8%
4. Change Amount to 4.560490
5. Check if Circle CCTP Automatic route can be selected.

Actual result: Circle CCTP Automatic route is not offered for selected. 
Expected result: Circle CCTP Automatic route can be selected when required transfer amount is entered.  

## Notes/ Attachments
Note: The Circle CCTP Automatic route is available if, during data entry, you keep the amount unchanged and input the number 4.560490.

https://github.com/user-attachments/assets/589e9b05-4da6-4c2d-bd70-c596944b72bf

![image](https://github.com/user-attachments/assets/646b7c5f-d359-452e-9d3a-7a6d3c9e5800)

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ with Avalanche -> Optimism tx. 

Attachment: 

https://github.com/user-attachments/assets/a1bf9e59-c8ed-4ede-84e7-ecdfb9a13d22
