### ISSUE TITLE
[QA] Cannot resume transaction 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2313]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.89 (Official Build) (arm64).

Steps:
1. Open Resume transaction screen
2. Search for transaction that was sent with Circle CCTP Automatic route

Examples: 
* 0x434329629ed0c0c468aa868d2dd9e6cbc770b00812c0646a90cee2a173e75e0e (Ethereum) (Send from tx: [Ethereum](https://etherscan.io/tx/0x434329629ed0c0c468aa868d2dd9e6cbc770b00812c0646a90cee2a173e75e0e), Send to tx: [Avalanche](https://polygonscan.com/tx/0xdf55b526269d4d6903718550f903cc81eca149e3ade3e1a7fc74a6d9114248bf), [Wormholescan](https://wormholescan.io/#/tx/0x434329629ed0c0c468aa868d2dd9e6cbc770b00812c0646a90cee2a173e75e0e))
* 0xbb5a688ca35cd00a32bb872601d26f1b6db46418b3402c2ce35e305d94ab6263 (Avalanche) (Send from tx: [Avalanche](https://avascan.info/blockchain/c/tx/0xbb5a688ca35cd00a32bb872601d26f1b6db46418b3402c2ce35e305d94ab6263), Send to tx: [Polygon](https://polygonscan.com/tx/0x6c8f9cd47d136f3d4d31d0c505d7ec6d4624c344adfc41eb7c3b893a0ff97418), [Wormholescan](https://wormholescan.io/#/tx/0xbb5a688ca35cd00a32bb872601d26f1b6db46418b3402c2ce35e305d94ab6263))
* 0xc9804710598c16a76cf70727044532d4edb1d2aab1431bf8d5e16fad32aa0bac (Optimism) (Send from tx: [Optimism](https://optimistic.etherscan.io/tx/0xc9804710598c16a76cf70727044532d4edb1d2aab1431bf8d5e16fad32aa0bac), [Polygon](https://polygonscan.com/tx/0x29b9a8ae4a866f064ea0c6887f9a8355b93163069132933a4aa660857af94cff), [Wormholescan](https://wormholescan.io/#/tx/0xc9804710598c16a76cf70727044532d4edb1d2aab1431bf8d5e16fad32aa0bac)) 

Actual result: Loading does not finish.
An error appears in Console:

```
Uncaught (in promise) Error: ChainId 0 is not valid for this protocol and action
    at Object.to (main-BIXv4aXg.js:240:148127)
    at deserializeLayoutItem (main-BIXv4aXg.js:240:12534)
    at internalDeserializeLayout (main-BIXv4aXg.js:240:11835)
    at deserializeLayoutItem (main-BIXv4aXg.js:240:12759)
    at internalDeserializeLayout (main-BIXv4aXg.js:240:11835)
    at deserializeLayout (main-BIXv4aXg.js:240:11299)
    at main-BIXv4aXg.js:240:152685
    at deserializePayload (main-BIXv4aXg.js:240:152741)
    at deserialize$1 (main-BIXv4aXg.js:240:152165)
    at getVaa (main-BIXv4aXg.js:245:19698)
```

Expected result: Transaction is successfully found. 

## Notes/ Attachments
Note: Transactions that were sent with Circle CCTP Manual route can be successfully resumed. 

![image](https://github.com/user-attachments/assets/07c00e6e-5010-49d6-9110-3cf67f44cfd7)

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERLgPYDWMMgGFe0AGZNEoCBADqZXgBs00NNOKywggJ6IkC5arSFNssjpQAjZfrmmtENbgyxIwgBaYWyRSrUOjnyC0ACSNBqOsgDGXlj6fsaBUWg0NGz0ZPoAHACsAGoAQgBiAIoAWsIAnAAq5fziaAAOuIVyAFawAKoA7gDsAJpW5e06uQBMAIIAbCjtuAAKAOLtZLilkyilybIAvtyOGNFi%2Bh64uE1ZAPRXaGQUuGQAdMdYjJDR%2FLwvvChXr9AyFcMOh3kCAMy5AAM2T6VzWqhoaDYNCuPV%2BbA8ykgAH0lLxGLwceISEolDjjvi2Di2IwrDjxlCmU0AB44vrjJpNDDEqx9abTNDRPJoJ5NaCMAD8AEY%2BjDptlslVcgAWHYQAFLD5fcL6dFsFBYpSQdVgOjREFoJRZMAyKJmyCNUm4RDTA5afZmT1aOR4DyQDIkFCRRy6Ox%2BgOQIOmizWWzIezu2TOVzuOI%2BJARwMoU3BGC621mLSxbz6LNRnNJrSpdKZfRQlmFKHiYpobJMmHZaaQXJ9YpdtITaYqqzK7LjKxTGiwyej6Wm72HY4Zs4Xa63e54Z4A96fb7HP4AoGWsFXSEwuEI6BIlFojFG3H4wnE0nkym8am0%2BmM5lsjlcnlxD5AUhRFMUJRlOUu0VZU1SrMBNW1XgCyQfVDWxU1zUta0QyiOgnSUF0wGlbJ4MXCByLAORkSsDB2CDXDZDDBMaLojhKyLMBYxsJQ7FNFM3E8UtkFY%2BiOKiPMwgiQt7QQ9N9FE9jTQgGsMnuetG2bVt2yZRVu17ftpkHcZh1HXJx0nSZpz6WcqnnMj4KOE5kFXS54BuO4Hm3Xg3iQn5Dx8wFgVBegz2hWF4VwRFkVRdEUExbE8QJIkSTJCllA%2FGk6QZDtWXZTluV5flBWFXJRXFKVZXlGDVVNRC9xQtCH0wj5sJtO08MdNBnUQEiHK9JM5F4FoQQwMhgxk0NID0BNhpcFAxvExxuPjAx%2BLQFxBPk5A5tG8bcwEfNpI6xwS3iHaRoW%2Fb4JUtI1JtJAGybFs2w7PSez7AcaCHEcxwnKcZwnOyF0c5dTnONyPM3R4fl8vd%2FP%2BQLjxCiFwsvKLrxiu94ofJLn1St8Ms%2FbKfyhPL%2F0KoDitAsrwMqqCFSVWr4PqnVpNQj90ONFqLXQHDJs6giiL6zjKMouQrDuSBGIgZiDEligY0sHi%2BPggS02EpAFZNeDJILE7i22rWpeUsBVLrZAnq017dK7D7DOM0y%2Fss6zbPs0XQecpBXPXTyt1hiU%2FIPRGsGRtBT3PCKrxvWL70Sp8UtfdKqSy79cr%2FArAOAkqwIqyDqqZuDONZ5D2aajD4Kwvn2s4iB8O6wjetIj2BuIRdoHOJY2F4Eg3IFqiZbADvcAAWWMd42BtABtWv%2B6iM7oAAOTQFBpd8IwAhu2RzfU5BF5qXBJjQXgABEACkPEEAAJSA0HyLor%2BgHQPB6KwFkXyZF%2BmORGEKJor%2F4FfQoNRohGT6LAAAMgAaVNjwQ60AoHTTsIkTes8eBsFUGQaIkBUyT0QDPWSWgDaEJ3g9feh9j7n0vpAG%2Bd8H5Pxfm%2FD%2BX8f5%2FwAUAkBYDIEwK3hJHQTQ14cwNM1XhexREAF1REoLQKUEgvBcABn0IvAAjjQaYAANZRkxsgQKsCIEgSxsgjwgXIOQJAFhdlyIvfI0x2iUGlCPKw6jIBQJZCfFUV9oHn1NpRIhaC5LeGXqvMsuB%2FTZlgWbO6FtHosmiFCDkhRpSTAAKLiHBOCbsJ86C5CqJMKEKoqjTCqFUVJKpIDZFbFUE%2BOSVSTBVNkCJklEEzQMOWaMoj2CYOwbg6e%2FiIDENkqQjSJ8rC5FVFUcYNA%2BjSiqFCE%2B0pJbJOyJMYQVhklQnBHZaUwgVTJPBMkvoKoTKwihNECJWhcD8MEeXbmoiKISK3r42QAyYjpiCYIxS7T%2FFDMtiyXI6TwQ0ChJMaIMwVRoBVNCKyajiiQGKPyE%2B0x5ngj6LkeFJlhCFHqUXQhYAmlIJYmwWiYlGkYMBN0tweCwAENxXPEhUTd4xPmW2SYhQimQCZCZbs2RCh9DsmgaUuRCg7NRdKFUgrwSTGhJCtA0xzmyEuQIvUnMRF9LAE8rQkjZ4arpYbQJK9BG7SuktQZDKHoNmlBC4olq%2BXNnGOCYoQEqh9A5IU6Y0Q2XFAyTQYQajzIbPBJAaU4JGnwOaXYI1i1SVdJwZS3ptLdX2h%2BTEqoVgT7ZD5KM8YfRhB1MgNMPo4JsgepPmgQoNBii5G2eMcYKoBSoumPEwF8qeBXOVcIiuaqdUQC1bJHVLyNRvINfobWETk0Nn%2BekoFIKwUQqhWkaYsL4VIqRcG1F6LpiYuxaGkI4aEyjo6WSrBsaAzxtpQOxw463GWuWWyqoHKoRcvKby%2FlgrhUqlFeK%2F5Ur8llTlXchVbbkA3J1l2h52r4K9rEW3IguwgA) when resuming tx on Optimism, tx hash `0x132214277adc131778970bc5a944c023dfd4eb483ec0a0ace0ee16417f50c4c6`.
* Transaction details: 0.000011 W transfer from Optimism (MetaMask) to Base (MetaMask)
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x132214277adc131778970bc5a944c023dfd4eb483ec0a0ace0ee16417f50c4c6)
* Send to tx: [BaseScan](https://basescan.org/tx/0x125c44d4798e5293bf705c124531bd6746f3cbcb15064018cf85bb223c30dd8e)

Errors in Console:
```
Uncaught (in promise) Error: Encoded data does not match any of the given payload types - 1,0,0,0,4,13,0,34,47,88,30,242,98,194,220,214,211,253,242,111,203,97,159,68,55,124,77,8,122,135,43,209,66,72,157,32,220,74,45,78,121,214,227,190,147,1,52,118,240,245,89,216,119,171,142,50,90,131,113,134,130,181,165,219,151,48,168,234,170,77,71,1,2,154,52,92,104,230,169,113,14,199,34,206,188,113,159,68,162,85,30,87,3,203,63,58,90,211,109,255,253,43,233,32,121,38,241,78,234,190,9,62,246,16,75,127,183,156,99,153,95,155,23,254,234,87,100,203,92,23,95,185,5,73,65,12,227,1,3,62,74,56,244,170,2,222,201,249,188,239,84,250,123,246,109,86,151,218,211,167,217,11,107,223,247,126,135,149,222,41,31,25,114,239,231,131,195,226,27,114,93,144,91,35,118,173,116,249,32,132,61,174,17,88,33,163,135,89,218,97,209,224,17,1,4,35,136,14,241,30,79,180,53,195,175,241,245,134,77,53,155,190,143,227,19,186,242,253,102,63,30,16,156,203,12,171,37,72,19,111,137,235,161,133,223,77,147,233,49,93,32,56,172,106,248,47,57,26,247,234,200,168,98,26,182,178,208,92,205,1,5,41,209,155,105,63,243,28,126,11,163,38,163,129,123,108,240,118,252,80,234,69,223,14,17,115,174,246,80,252,139,80,171,66,106,211,55,54,176,173,66,143,40,79,234,62,157,33,143,106,129,130,167,255,143,202,93,42,171,200,143,224,90,86,12,1,6,100,225,236,105,140,1,219,227,79,156,139,58,147,49,100,250,33,188,171,203,81,185,216,179,189,202,71,74,106,148,51,154,83,164,184,241,56,96,79,67,180,225,186,231,108,158,22,72,61,214,73,145,146,221,124,233,200,65,229,57,236,116,107,13,1,7,217,195,9,152,186,247,215,94,155,232,246,248,247,40,246,202,175,3,174,182,247,35,102,51,244,228,127,235,76,195,210,215,8,124,77,180,113,240,20,247,146,102,25,16,22,114,92,54,220,140,92,88,93,247,220,25,96,251,117,35,3,209,48,83,0,8,28,249,92,129,238,30,186,221,231,7,205,52,238,42,237,71,240,6,211,118,158,49,70,97,12,95,75,133,48,199,233,68,36,52,11,198,250,247,144,116,79,163,128,22,10,96,78,154,13,41,100,232,247,22,241,75,242,231,170,74,63,53,236,100,1,10,192,245,58,232,244,163,185,134,163,138,24,103,172,210,104,248,18,16,93,213,208,213,139,88,145,148,123,53,239,164,93,135,117,137,21,16,9,130,215,142,81,137,30,218,76,122,241,93,249,65,145,215,23,141,196,172,183,87,206,243,65,160,109,78,1,11,23,64,105,71,21,126,51,162,63,214,92,20,96,82,225,126,2,208,251,118,107,230,231,199,113,71,46,124,67,31,43,247,106,232,147,92,239,171,143,189,117,251,156,232,255,232,179,31,160,202,165,245,238,87,56,164,97,250,84,200,159,212,44,216,1,13,49,124,224,188,160,166,85,242,175,27,119,110,54,34,161,191,134,30,141,101,3,33,237,204,203,230,230,55,242,95,233,117,101,134,189,18,11,62,18,227,10,215,62,164,117,121,125,43,97,170,193,22,156,172,151,114,33,173,175,147,227,43,185,57,1,16,204,176,37,164,209,36,87,31,195,113,152,98,112,61,69,241,209,189,75,35,248,93,188,181,76,179,92,26,63,24,1,210,76,11,66,91,195,129,90,65,77,18,74,120,73,213,31,55,197,246,54,117,252,151,76,137,92,246,8,172,2,224,205,123,0,17,195,39,45,45,166,75,59,155,125,216,112,98,1,97,110,55,184,138,202,219,165,204,223,53,185,103,113,62,156,193,214,158,87,197,229,202,204,176,230,14,107,57,48,216,216,172,235,223,159,209,101,146,237,49,4,41,231,39,187,0,79,85,160,166,1,102,177,218,101,0,0,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,155,216,183,181,39,202,78,103,56,203,218,189,245,28,34,70,103,86,7,61,0,0,0,0,0,0,4,174,1,153,69,255,16,0,0,0,0,0,0,0,0,0,0,0,0,26,79,26,121,15,35,255,185,119,41,102,203,111,54,220,214,88,3,62,19,0,0,0,0,0,0,0,0,0,0,0,0,83,51,208,172,166,74,69,10,221,111,239,118,214,209,55,95,114,108,180,132,0,145,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,76,0,0,0,0,0,0,0,0,0,0,0,0,150,49,40,143,64,80,247,207,191,119,183,127,133,64,222,207,108,252,112,18,0,79,153,78,84,84,8,0,0,0,0,0,0,4,76,0,0,0,0,0,0,0,0,0,0,0,0,176,255,168,0,8,134,229,127,134,221,82,100,185,88,43,42,216,123,43,145,0,0,0,0,0,0,0,0,0,0,0,0,150,49,40,143,64,80,247,207,191,119,183,127,133,64,222,207,108,252,112,18,0,30,0,0
    at main-B_vQ2Uks.js:240:152596
    at deserializePayload (main-B_vQ2Uks.js:240:152741)
    at deserialize$1 (main-B_vQ2Uks.js:240:152165)
    at getVaa (main-B_vQ2Uks.js:245:19698)
```

```
Uncaught (in promise) Error: value mismatch: (constant) layout value: 1, data value: 153
    at checkNumEquals (main-B_vQ2Uks.js:240:5271)
    at deserializeLayoutItem (main-B_vQ2Uks.js:240:12423)
    at internalDeserializeLayout (main-B_vQ2Uks.js:240:11835)
    at deserializeLayout (main-B_vQ2Uks.js:240:11299)
    at main-B_vQ2Uks.js:240:152498
    at deserializePayload (main-B_vQ2Uks.js:240:152741)
    at deserialize$1 (main-B_vQ2Uks.js:240:152136)
    at getVaa (main-B_vQ2Uks.js:245:19698)
```

![image](https://github.com/user-attachments/assets/5b7893f8-6678-4983-9a73-0efb62359899)

**Comment by kev1n-peters** [comment]
Connect does not support resuming automatic transfers at the moment

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2475.
