### ISSUE TITLE
[QA] Transaction screen does not open in 30 min although ‘from’ transaction has successfully completed 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#232]
#### Steps:
1. Connect Crypto.com wallet in ‘From’ section via Wallet Connect > Desktop
2. Connect Metamask wallet in ‘To’ section via Wallet Connect > QR Code
3. Prepare to send 0.01 AVAX from Fuji to Fantom
4. Click on “Approve and proceed with transaction” button 
5. Wait 30 minutes
 
#### Actual result:
* Transaction is displayed as Loading for more than 30 minutes
* Loading doesn’t finish, transaction screen is not displayed
* There are no errors in Console
* Transaction is displayed as Completed in Transaction scan

#### Expected results:
* Transaction screen is opened
* ‘From’ transaction is displayed as completed in wormhole-connect

#### Tested devices:
* MacBook Pro, macOS Monterey 12.6.1, Chrome Version 111.0.5563.64 (Official Build) (x86_64)
* Samsung S20 (Android 12), Chrome Version: 110.0.5481.63

#### Attachment:

https://user-images.githubusercontent.com/10746654/226375716-f3b76ef2-06ce-49cc-bd5f-1bd5a6a89c4a.mov

**Comment by anondev2323** [comment]
Could you please check if this is reproducible anymore? We implemented polling here and I don't think it is an issue anymore

**Comment by tsadovska** [comment]
Tested OK
Scenarios:
* Transaction is successful when the same Metamask wallets are connected with Metamask Extension and user sends  AVAX from Fuji to Fantom (Gas payment = Pay with AVAX)
* Transaction is successful when the same Metamask wallets are connected with Metamask Extension and user sends AVAX from Fuji to Fantom (Gas payment = Pay with AVAX & FTM)
* Transaction is successful when different Metamask wallets are connected with Metamask Extension and user sends AVAX from Fuji to Fantom - not checked because of #607
* Transaction is successful when the same WalletConnect wallets are connected with QR Code and user sends AVAX from Fuji to Fantom (Gas payment = Pay with AVAX)
* Transaction is successful when the same WalletConnect wallets are connected with QR Code and user sends AVAX from Fuji to Fantom (Gas payment = Pay with AVAX & FTM)
* User sends wrapped asset from Fuji to Fantom
* User sends AVAX from Fuji to any other network

Closing the ticket.
