### ISSUE TITLE
[QA] Automatic Bridge routes are not disabled when an amount less than is required is entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2358]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 MATIC from Polygon (MetaMask) to Avalanche (MetaMask)
2. Select "Manual Bridge" option
3. Select "Automatic Bridge" option

Actual result: "Automatic Bridge" option cannot be clicked. No warning is shown. Routes are not disabled. 
Expected result: Routes are disabled. 

## Notes/ Attachments

https://github.com/user-attachments/assets/a467a9b4-196f-4ec1-961c-04656aa106f6

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, automatic route is disabled. 
Closing the issue. 

Attachment:
<img width="1440" alt="Screenshot 2024-09-30 at 17 01 49" src="https://github.com/user-attachments/assets/4f5a00e2-eef2-4f33-bf52-b11babfdf2fa">
