### ISSUE TITLE
[QA] [Testnet] Corresponding asset is not displayed in "To" section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2365]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRAMwEMAbUkAXxCA%3D%3D) with mac OS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

Steps:
1. Prepare to send 1 CELO from Alfajores (MetaMask) to Base Sepolia/ Optimism Sepolia/ Arbitrum Sepolia
2. Check Asset in "To" section

Actual result: Asset is not displayed and warning is not shown.
Expected result: Asset is selected or warning is shown

## Notes/ Attachments

Error in Console:
`Failed to get destination token: Error: Token 0x000000000000000000000000f194afdf50b03e69bd7d057c1aa9e10c9954e4c9 is not a wrapped asset`

![image](https://github.com/user-attachments/assets/0980fd22-09cf-4097-ac23-cb028b0f92ba)

**Comment by agodlevska** [comment]
Issue is reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) when sending BNB/WBNB from BSC to Fuji. Asset is not displayed and warning is not shown.

Attachment: 
<img width="1440" alt="Screenshot 2024-08-19 at 13 22 21" src="https://github.com/user-attachments/assets/739f3e37-6e33-43b0-9f34-7cfe17e2bf39">

**Comment by tsadovska** [comment]
* CELO token is displayed in "To" section when CELO token and Alfajores network are selected in "From" section
* WBNB token is displayed in "To" section when WBNB token and Fuji network are selected in "From" section

Ticket is closed.
