### ISSUE TITLE
[QA] Tokens balances are not displayed on Sei

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2372]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

Steps:
1. Select Sei asset in From section
2. Connect Leap wallet
3. Check tokens balances

Actual result: Token balances are not displayed. 
Expected result: Token balances are displayed.

## Notes/ Attachments

```
Failed to get token balances TypeError: Cannot read properties of undefined (reading 'abciQuery')
    at sl.queryAbci (cosmwasm-DcTezrWr.js:4:1812)
    at Object.request (cosmwasm-DcTezrWr.js:4:2977)
    at m.AllBalances (cosmwasm-DcTezrWr.js:4:51487)
    at Object.allBalances (cosmwasm-DcTezrWr.js:4:53959)
    at Hn.getBalances (cosmwasm-DcTezrWr.js:4:1062560)
    at main-C_OfgCFH.js:308:69142
```

![image](https://github.com/user-attachments/assets/165cd0f5-0101-4a6b-8587-b86be5bacbe3)

**Comment by emreboga** [comment]
Sei has been removed from the list of available chains since this issue was created. We need to revisit this for release requirements.

https://wormholelabsxyz.slack.com/archives/C077DT4GS3U/p1724858920162879
