### ISSUE TITLE
[QA] [Improvement] Add scroll functionality for viewing all tokens with balances in network token selection

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2378]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (x86_64).

Steps:

1. Select BSC as source chain
2. Connect MetaMask wallet
3. Open Assets list
4. Observe the list of available tokens with balances 
5. Attempt to scroll through the list without using the search bar.

Actual result: The list of tokens is not scrollable, preventing users from seeing all available tokens with balances unless they type in the search bar. Scrolling only becomes available if the search yields multiple results. 

Expected Result: The token selection interface should allow users to scroll through the entire list of available tokens with balances without needing to use the search bar. All tokens should be visible and accessible at all times.

## Notes/Attachments

https://github.com/user-attachments/assets/89bdcb9c-3710-4084-9f3f-1719e0d5fa57

**Comment by danielisaacgeslin** [comment]
this seems fixed in the latest development code

https://github.com/user-attachments/assets/a639e6d6-87e8-483b-905d-085560b5318f

**Comment by Wesleyleung** [comment]
scrolling exists now in latest build
