### ISSUE TITLE
[QA] Wallet address is not displayed in "Send from" section after resuming the transfer

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2379]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

Steps:
1. Open [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D)
2. Click on "Resume Transaction" link
3. Search for transaction, 0x21812d31ee951755df474bfb39c91f0344a4966e49408af1e4da21c0e8cfd151 (Polygon)
4. Check if wallet address is displayed in "Send from" section

Actual result: Wallet address is not displayed.
Expected result: Wallet address is displayed. 

## Notes/ Attachments

![Screenshot 2024-08-14 at 18 03 24](https://github.com/user-attachments/assets/17c59cef-26b5-41bf-aa25-4be4f30bf2ea)

https://github.com/user-attachments/assets/aed27085-cfda-4a3e-a606-333230e28fce

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/ac2a9a0933/. 
Issue is reproducible, when resuming the transaction via token bridge manual route - 0.1 GLMR from Moonbeam to Celo. Wallet address is not displayed in "Send from" section.

Reopening the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-11-05 at 16 05 40" src="https://github.com/user-attachments/assets/15e95591-c377-48e8-b725-969892d36bae">

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/0a16bf3ef2/.
Issue is reproducible, when resuming the transaction via token bridge manual route - 0.17 FTM from Fantom to Sui. Wallet address is not displayed in "Send from" section.

Attachment:
<img width="645" alt="Screenshot 2024-11-11 at 16 45 07" src="https://github.com/user-attachments/assets/b6b0934c-aabd-44ed-b507-fae8e50dc5df">

**Comment by agodlevska** [comment]
Сlosing this ticket as it seems to be more relevant to another existing ticket - https://github.com/wormhole-foundation/wormhole-connect/issues/2736.
