### ISSUE TITLE
[QA] Amount field not resetting after network and asset change in "From" section 

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2388]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma Version 14.6.1 and Google Chrome Version 127.0.6533.120 (Official Build) (x86_64)

Steps:

1. Prepare to send 1 FTM from Fantom (MetaMask) to BSC (MetaMask)
2. Switch network to Avalanche and asset to AVAX in "From" section
3. Observe that the entered amount persists instead of resetting to zero and "View routes" button inactive

Actual result: When changing the network and asset in the "From" section, the amount input field should reset to zero.
Expected result: The entered amount remains unchanged after changing the network and asset in "From" section. 

## Notes/Attachments

https://github.com/user-attachments/assets/bc5a80a2-f1a6-47a8-a1fc-0bb9de211918

<img width="544" alt="Screenshot 2024-08-15 at 17 50 02" src="https://github.com/user-attachments/assets/31010a65-4148-4d51-861e-d8d428743221">

**Comment by danielisaacgeslin** [comment]
@agodlevska this seems fixed in the current version

**Comment by agodlevska** [comment]
@danielisaacgeslin Thank you! 
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (connect v2).
Issue is no longer reproducible. Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/236d54e0-1052-4b58-83c4-10cc0609700a
