### ISSUE TITLE
[QA] Search does not work in "Connect a wallet" list

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2389]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Solana network in "From" section
2. Click "Connect source wallet" button
3. Type "wallet" or "Phantom" and then press Enter button
4. Check if Search works

Actual result: Search does not work in "Connect a wallet" list.
Expected result: Search is working correctly. 

## Notes/ Attachments

https://github.com/user-attachments/assets/a85901b9-e0f6-4a4f-96c8-2feecb9a8813

**Comment by agodlevska** [comment]
Issue is reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D). 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-26 at 09 53 32" src="https://github.com/user-attachments/assets/37ecbc13-7910-4ef9-9bed-9164e217dd86">
