### ISSUE TITLE
[QA] [Testnet] Claiming fails with "Error: unimplemented" error when sending asset to Sei

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2394]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Prepare to send 0.00001 CELO from Celo (MetaMask) to Sei (Leap)
2. Click on "Review transaction" button
3. Confirm transfer
4. Click on "Claim" button

Actual result: Transaction fails.
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

```
Error: unimplemented
    at signAndSendTransaction (main-aEt-DbGq.js:269:161568)
    at SDKv2Signer.signAndSend (main-aEt-DbGq.js:276:202775)
    at main-aEt-DbGq.js:245:7516
    at ssw (main-aEt-DbGq.js:245:7766)
    at async signSendWait (main-aEt-DbGq.js:245:7467)
    at async TokenBridgeRoute.complete (main-aEt-DbGq.js:245:48471)
    at async vt (main-aEt-DbGq.js:309:87731)
```

https://github.com/user-attachments/assets/8a09ff90-f0a9-4ca0-8a72-3d01c54e52b3

**Comment by emreboga** [comment]
@tsadovska I've verified this a few times with the latest deployment and it seems to be working:
https://www.loom.com/share/a4dcbd6772504298b3d571f399f0e723?sid=4b57a19a-c441-45ea-bf00-123a7c89eef6

It might be something missing or not previously implemented in SDK or Redesign. Can you please verify from your end as well? Thanks!

**Comment by tsadovska** [comment]
Rechecked the issue on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D). 

* Sei network currently is not displayed
* 0.0001 CELO transfer from [Alfajores](https://explorer.celo.org/alfajores/tx/0x7345544a2cda896a72d87eb7cd4bd5440c64e7f02ed434a58aa281bda0790f6c) (MetaMask) to [Moonbase](https://moonbase.moonscan.io/tx/0xfd790e9eded0099cc684553f4d7000064fd77ce30c6514980dbe9a9c2e661772) (MetaMask) - Asset has been received, but status has not been updated to "Completed" on [Wormholescan](https://wormholescan.io/#/tx/0x7345544a2cda896a72d87eb7cd4bd5440c64e7f02ed434a58aa281bda0790f6c?network=TESTNET), ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2398. 

Closing the ticket.
