### ISSUE TITLE
[QA] "ERC20: transfer amount exceeds balance" error appears in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2396]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Fill in the fields in From section: [USDC](https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831),  Arbitrum (MetaMask)
2. Fill in the fields in To section: [USDC](https://avascan.info/blockchain/c/address/0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E), Avalanche (MetaMask)
3. Enter Amount, 0.6
4. Select "Automatic route" option
5. Click on "Review transaction"
6. Confirm transfer

Actual result: Transaction fails.
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

```
Wormhole Connect: error completing transfer Error: execution reverted: "ERC20: transfer amount exceeds balance" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000", reason="ERC20: transfer amount exceeds balance", transaction={ "data": "0xe4269fc4000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000000000000000927c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000010494454a5d000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e583100000000000000000000000000000000000000000000000000000000000927c000000000000000000000000000000000000000000000000000000000000338c400000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert={ "args": [ "ERC20: transfer amount exceeds balance" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-BlRpU2F-.js:235:71362)
    at getBuiltinCallException (main-BlRpU2F-.js:236:107247)
    at M1.getBuiltinCallException (main-BlRpU2F-.js:236:108201)
    at Ya.getRpcError (main-BlRpU2F-.js:236:211293)
    at Ya.getRpcError (evm-C3A2TvAW.js:2:1682)
    at main-BlRpU2F-.js:236:215228
```

https://github.com/user-attachments/assets/be55212c-1f2e-4538-88cf-e918dff7f4eb

**Comment by emreboga** [comment]
@tsadovska I've tried the same source/dest configuration as well as another one with a low balance. I can't seem to repro the issue above. Can you verify on your end as well?

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D).

The first attempt to execute the transaction as described above resulted in an error (att. 1). 
```
Wormhole Connect: error completing transfer Error: No receipt for 0x2d1b7e94fb5a1d3aeae44691bd35e90a4fb9c609907a215afd5fb1a6d4e5fc7e on Arbitrum
    at E.parseTransactionDetails (index-lccCmM9l.js:1:3905)
    at async CircleTransfer.st [as getTransferMessage] (main-RPuOtJsw.js:245:18376)
    at async AutomaticCCTPRoute.initiate (main-RPuOtJsw.js:245:53829)
    at async SDKv2Route.send (main-RPuOtJsw.js:273:70761)
    at async St (main-RPuOtJsw.js:313:66416)
``` 

However, upon retrying, the transaction was successfully completed without any issues (att. 2).

Attachment 1: 

https://github.com/user-attachments/assets/1f9f16ae-f6b5-46e0-a802-cba56865ffd4

Attachment 2: 
<img width="1440" alt="Screenshot 2024-09-11 at 15 08 10" src="https://github.com/user-attachments/assets/2495ea62-4876-41ee-99c8-a2ce20d4f365">

**Comment by tsadovska** [comment]
Issue is reproducible with following details:
* Source chain: Fantom network, SUI token, MetaMask wallet
* Destination chain: Sui network, SUI token, Sui wallet
* Amount: 0.239697 (in my case it is max amount)

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Transaction fails every time the 'Confirm Transaction' button is clicked. 

```
Wormhole Connect: error completing transfer Error: execution reverted: "ERC20: transfer amount exceeds balance" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000", reason="ERC20: transfer amount exceeds balance", transaction={ "data": "0x0f5287b0000000000000000000000000c277423a21f6e32d886bf85ef6ccb945d5d28347000000000000000000000000000000000000000000000000000000000e497c680000000000000000000000000000000000000000000000000000000000000015a4055514cc6ce87f54250bf954e0f5b9f5b3ce48bea3ff0af687a20e63b312b800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x7C9Fc5741288cDFdD83CeB07f3ea7e22618D79D2" }, invocation=null, revert={ "args": [ "ERC20: transfer amount exceeds balance" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (pb-index-BDwcyk1t.js:271:19452)
    at getBuiltinCallException (pb-index-BDwcyk1t.js:272:107223)
    at Ju.getBuiltinCallException (pb-index-BDwcyk1t.js:272:108177)
    at Ui.getRpcError (pb-index-BDwcyk1t.js:272:211164)
    at Ui.getRpcError (evm-SljAss8Z-NLDvwg-G.js:7:2076)
    at pb-index-BDwcyk1t.js:272:215073
```


https://github.com/user-attachments/assets/2bbe097f-9737-4023-b64f-c1219ef87e0c

**Comment by tsadovska** [comment]
Issue is also reproducible with following details:
* Source chain: Arbitrum network, USDC token, MetaMask wallet
* Destination chain: Solana network, USDC token, Phantom wallet
* Amount: 0.001

Checked on https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAwkwCoAKASlTQLogBfIA%3D%3D

Transaction fails every time the 'Confirm Transaction' button is clicked.

```
Wormhole Connect: error completing transfer Error: execution reverted: "ERC20: transfer amount exceeds balance" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000", reason="ERC20: transfer amount exceeds balance", transaction={ "data": "0x6fd3504e00000000000000000000000000000000000000000000000000000000000003e80000000000000000000000000000000000000000000000000000000000000005c88530005699842a79fa44891dd80aa7310f0a71783ce22e2dda80722cec045f000000000000000000000000af88d065e77c8cc2239327c5edb3a432268e5831", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x19330d10D9Cc8751218eaf51E8885D058642E08A" }, invocation=null, revert={ "args": [ "ERC20: transfer amount exceeds balance" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-DOmoORVP.js:228:68988)
    at getBuiltinCallException (main-DOmoORVP.js:229:107247)
    at fu.getBuiltinCallException (main-DOmoORVP.js:229:108201)
    at Pi.getRpcError (main-DOmoORVP.js:229:211293)
    at Pi.getRpcError (evm-BKx3jHY2.js:2:2070)
    at main-DOmoORVP.js:229:215228
```

![image](https://github.com/user-attachments/assets/d92d5110-e681-4566-8be1-3db356eed67e)

**Comment by emreboga** [comment]
@tsadovska can you confirm that this happens only for manual transactions?

**Comment by tsadovska** [comment]
@emreboga Issue was happening with automatic route ([scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2396#issue-2470731781)) and manual route ([scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2396#issuecomment-2370704708)). Changing the ticket priority, because issue has low reproducibility level. 

Rechecked all the scenarios mentioned in the ticket on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgEQFsCGAlpDLFgDQjhjKICus0AzpgNpUQB0XAIgKIBiAQQCqAGQAqAfQBKAeWHjeAZTJh2YLh0ixY0ug0YAKUBFNhYiVNEjMwJs6dEEAJoknxGsXuIASrdQ52AYFgAMYAFoSQmFi8sOHQyNC0OOTBgfiQeADmiTEADAAeAEYAnAAsABx4pQDMlQBMAOzOAGzVjfytAKwAjLWCzr1NlaWt5dx4VU0AZtANAELcpWkhDhZW0dhFs7WlAMLdlb383aXdC921od2hxb2lxdz5xbUzlc6CraF13bwN%2Bzw%2BVWa1MsGQeBsoWgBAAbnkwGxQQ57MizHhnM4koxbFgioJeoJ9vtetBWtBnHgFg1jvxoMVnKVerxan1uvk6vxenxaQ1bsCKGj1gBPAAO0BiSGQOHCiAANtAQUKAL6CtEAXTVa1V6VMqNBESiMQWjFCStBmRyCLxhVapVp3VaDV6dt6%2BwWMxZ3Gc3G6DXKzl4TV6%2BSarWKTVK%2FHygnyzUq5rWG2sBUKDW%2B3Wg%2BV6foDDV4TsqMaq%2FAaN3yMy63GgTWgft4Y16bsTIXBkNNMPhyH8Qog%2BqFGKxTFxRWK0Fq%2FFr%2BXaTXz%2BWcXX23Ca%2FH4rIWTTwUwW93K5Va3H2pXtrRbyNgYol2ClMvliq1aJ1Qs1uogT5CL7WAHUe6D%2ByFDSIGIlHlSE8DPBxLVybtsAAOXEWBBDwRBuAAKXCKwfGgPAADVhB8SBhXCeBigABVgwRYNaL9sgWUUfFQHwFnEUJWmcJpYVEABpCCzGTLYsEqbocIWfgAEUAC0j3ECTUBmPBRVgBYvwAK1hYR4CaABNYoJJU4U%2FS%2BHAVNgUiAHEVM8MTBBwMTeLBCEoU7BEkV7f9kUHbFcXgxDkLQjDoCw3D8MI4iyIoqiaLohimJYtiOO4%2BzAgvcVJRQW8FSS0x32RT80QAR1oRAGBgrBYPytoAA18sESpRGKRh9loMzKgAWVEL8v1oUjKh6WCcNaFTpF6Vrikq6AuMKbhyh8bi0PsnKQnchxAIEuIEiSFIsqg60ilCUNFkJXgZlqWpyW9OtSljcoxmPY7ymgSp%2BBqX0KkEKosv41MFgrZ6i3yfJKl6usV16zE%2FXGMojgaYoGkGSomlhspek%2BxyOzhFzXxRLHAk84dU24Ypum6G6GnYh58m4XpijwXhKiJYpeHyPYm32coWSDcp0wR%2FIzQfIUUqvLAb1lTL%2BdBRa1jy7VxbMZazFWmJBGQYoCHBLbZcgsDoNTK5TucGNQi%2BcopnZQY2jpScDwPfomm6Sd03dKpyk%2BywU22QofsrPB%2FsB4HulBtjnAh8oocaWH4cRmGmVR9toQxmDXKFeWQjxnECd6H3BAWO0szjVpyUqDcmTwHMFjZu3enKHMBnZcpujwU9NaTS80ulUX7xx7Lm9MaWQkl7GhUV7BZEUggcAIRhUh7iAdtKopM%2FKLk8EjCsGgnGYyiaWcxm%2BHO1zY%2FY2iOZnamgfpXc2b7fp9gG%2FfJAP%2BDB4P01D85w7h5wEaRmOZ%2FMNH45dl%2FMnLu6JMReVTI8bglQIxE2aPsd6ZImj1FCEsKkC4%2Bj7AaP6AudtWihlqM4LKfFW7XnSh3YhYAB6BD7oEaheou7DywAsPAjBO5CjnrrU6hDDbG1NjGTErRLZhm4DbWodsHatCdpUF2f8voey9n9O%2BQMH6B3Bq%2FMOMNP7f2jijORADnKJ1AUEXspg04jimpnemOdSh53TIXYumcy4Vz6NXK4gg64NybsYiAgs24ZXYb2ehZhaEOHoaExayoACUaoXxUFoGw6QFImAEGyFsdW0AKBUH4o1RAkAZipMwPqDwXhfANVCEU4IVhhSSk8N4Hw5SWyMGFDgYo8pamlJ8C2LIsAMb7EiEBbAJo%2BbBH4gASWcJUtYTDhkQXMamdMNwsw5n9M4fMhZixPTLOySsB4ax1nzI2Zs4sB4EFCHkmI4QdCimYAAeluawthsBGAcHOUQXIoRUCIFeYgHAty3k2FuePK0jBbm9CBrUcotzPCQkpMgZwtySn1I4KKSA2QWwArMtAT5iAJmSghKKcUzgAC0ng4DhAxfKFAMQADEAxBATn4C2Zw2LgVylsOCh8i0vyMFAlkKZDhqkxB5Xy8C4tmmtPadgL83S8C9PhP0o02AQJyjAi2cZkyTEAQGQJFVarNbzOwEJES4kpKlBknJBSSlVLqU0jpPSBk4atGMqZCyVkbJ2ROeLM5FzsBXNgDc9A9zHlwBeQCj5Xyfl%2FIBaC4FuRQWskBk0aFsBYV4HhYi35yAO6SDlIgbIbgZi0DlHKSQ5y83IEkMgbIxRJANDvqKQokhZyEoIJITeYZWh4FCEJPAKK0UAH5hiA3aKMEmlKiBYpxXish7c7zMtZfgdlmBWhcofF%2BcliRkg4AFWYIV0rN2bWnsECVbS5TCtlfK6AirBmxHiFujWoy3aQBnctJh60H3HrWIam0ijb4AxUSDJ%2BQcQ6aIjl%2FKOyMWynPOQJf1gbg04lDT8952LI3nOjYgIgsb8DxtuYmhGKa00ZqQDgbNd5c35sLcW0t5aUBVprXWhtTaW2ijbR2gu3be39uyEOpoI6gbnFkcETFaHcWauFuQ%2Bd4sWWhDZRyyoa71BfnTardWO6tV7ugDU6Vqm1bIEfYEU9UqsAyvFj0vpOqlYq304Z9Yz7X26iYcrNTBmv2p3AfjBRN9faAcfs%2FUD78tGRx%2Fno4IMHfVYHg3ch5SHnkobRWJqN%2FysOArjUwfD7JCMwsgHChFpHyMKkowW9tNGy1UsrdW2t9aAaNubQ0Vt7aIycZ7Q3HjfGBNjuE4EUT06JMi2k8EWT8nMCcvUNyxAY8J5T13aYfdpnJu9Om%2B5swxnz3SsvZZpVWBR5LcnitsEDnNVvqsyPKb%2B25mefTt572vn%2FZqJfpDIL4GdFQa9cEH1cHrkxZDfF8NSWMMpew0C3DGWCPJpy3lzNZGc15pK0Wkt5WK0Meq8x%2BrjWONdta321FvHh29UE%2BO8WvWvkzsk3OsWQ3F14GXWAMbZhuU0zYbNiA82vxM8CatlpZ6L3mblVt29LC2HqqOyz0wMzWGc4cD%2Boof67uqOA%2Bop70MXuQd%2FuF71sHLnfaDbFp5YbUsRu%2BYDmNIOQWZaTUR3L6b8tZth1R0riO6OVcYzV%2FIdXWPsea1j7juOOsE66xOyAU7Sf9ak5TwIw2l0KaU2%2BCgyoADcIAgA) and they started and completed successfully. 

Checked following transactions:
* 0.6 USDC transfer from Arbitrum (MetaMask) to Avalanche (MetaMask) with CCTP Automatic route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x928452c0cebf78e01a99dfe694fe911d43120ff2138213ff49c165b535e49902).
* 0.0001 SUI transfer from Fantom (MetaMask) to Sui (Sui wallet) with Manual route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x7742f3ec2288b19fdd055af0bc5e739c0ef750ed1b276336fa318c8205fd3cfb). 
* 0.001 USDC transfer from Arbitrum (MetaMask) to Solana (MetaMask) with Manual route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x3ab1c9502c778418187db84abdf5dff30fd52fbef44659a10433f6917e47503b).

**Comment by tsadovska** [comment]
Issue occurred on Netlify with [custom config](https://wormhole-connect-mainnet.netlify.app/?config=IIGxAICcHsFcBcCmBnAUKg3q84B2j4B3aSAawC5wByAWwEMBLXfeKgGm3Fgcox2QAW0QgElcABRgBzSCmQB1BgBMpBSvEixE4AL4ccMBCkoBtALJ0AnnVwAlOEnkAJALqodAblRA) when sending 0.015392 WSOL (maximum available amount) from Base (MetaMask) to Solana (Phantom) with MayanRouteWH. 

![image](https://github.com/user-attachments/assets/17edcc3a-5cee-41e9-a9aa-e69c22f1070f)

**Comment by tsadovska** [comment]
Rechecked the scenarios mentioned in the ticket on https://wormhole-connect-mainnet.netlify.app/ on Dec 9.
Issue is no longer reproducible. 

Following transactions completed successfully:
* 0.6 USDC transfer from Arbitrum (MetaMask) to Avalanche (MetaMask) with CCTP Automatic route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x70f074c0ef764d2da8e59908275649e336784a6e2569ec6cad282a327e22c2a7). 
* 0.238696 SUI (max available amount) transfer from Fantom (MetaMask) to Sui (Sui wallet) with Automatic route. Link to [Wormholescan](https://wormholescan.io/#/tx/0xaa69c8a71dc3426e6e49cf1d93748c04c3a3002c5f1aeb0aa0aef8fcf708729d). 
* 0.001 USDC transfer from Arbitrum (MetaMask) to Solana (Phantom) with CCTP Manual route. Link to [Wormholescan](https://wormholescan.io/#/tx/0xed4845ba89365fa1b073665c8cadb12afb08ee65a683c9f1800ba8cd0fafa29c). 

Closing the ticket.
