### ISSUE TITLE
[QA] Status "Pending redeem" is shown for completed transaction

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2398]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64). 

Steps:
1. Send 0.000001 ETH from Ethereum (MetaMask) to Moonbeam (MetaMask)
2. Click on "View on Wormholescan" after transaction is compled
3. Check the status

Actual result: Status "Pending redeem" is shown. Asset is received.
* Send to tx: https://etherscan.io/tx/0xed7ecaffaa389b24b378ab52ebd764f1a01b41e3ffa84a43b97568f495c7fac1
* Send from tx: https://moonscan.io/tx/0xbd8843e24e34dcf3e75c9ad2770bbf76fbec48221dc1d19750e8e3d22f8963c4
* Link to Wormholescan: https://wormholescan.io/#/tx/0xed7ecaffaa389b24b378ab52ebd764f1a01b41e3ffa84a43b97568f495c7fac1
Expected result: Status "Completed" is shown. 

## Notes/ Attachments

https://github.com/user-attachments/assets/d8f4ead5-347e-4d6e-b10f-cc59fed2374f

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/b3b7091778/. 
The status 'Pending redeem' is shown on WHS more that 5 minutes after the asset is received.

Attachment:

https://github.com/user-attachments/assets/a87b676f-f863-4b8d-b835-906e72a28a63

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) when sending 0.0001 CELO from [Alfajores](https://explorer.celo.org/alfajores/tx/0x7345544a2cda896a72d87eb7cd4bd5440c64e7f02ed434a58aa281bda0790f6c) (MetaMask) to [Moonbase](https://moonbase.moonscan.io/tx/0xfd790e9eded0099cc684553f4d7000064fd77ce30c6514980dbe9a9c2e661772) (MetaMask). Asset has been received, but status has not been updated to "Completed" on [Wormholescan](https://wormholescan.io/#/tx/0x7345544a2cda896a72d87eb7cd4bd5440c64e7f02ed434a58aa281bda0790f6c?network=TESTNET).
