### ISSUE TITLE
[QA] Balance is not loading for Fantom

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2400]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Fantom network in From section
2. Connect MetaMask wallet
3. Open dropdown in From section and check tokens balances

## Notes/ Attachments
```
Error: Chain Fantom not supported
    at toMayanChainName (main-BlRpU2F-.js:278:786317)
    at fetchTokensForChain (main-BlRpU2F-.js:278:786766)
    at MayanRoute.supportedSourceTokens (main-BlRpU2F-.js:278:789550)
    at SDKv2Route.supportedSourceTokens (main-BlRpU2F-.js:280:197908)
    at async Operator.allSupportedSourceTokens (main-BlRpU2F-.js:280:203899)
    at async main-BlRpU2F-.js:313:24488
```

```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": 0, "message": "we can't execute this request" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "latest" ] } }, code=BAD_DATA, version=6.13.2)
    at makeError (main-BlRpU2F-.js:235:71362)
    at main-BlRpU2F-.js:236:215083
```

![image](https://github.com/user-attachments/assets/94aa144e-8f4f-4ec0-97fd-74223b345496)

Issue is also reproducible on https://portalbridge.com/.

![image](https://github.com/user-attachments/assets/8751ecd7-adc2-40d2-adb2-24e4973e781f)

**Comment by emreboga** [comment]
@tsadovska I've re-run the repro steps with the latest deployment and I can see the balances for Fantom:

<img width="1392" alt="Screenshot 2024-08-26 at 10 08 50 PM" src="https://github.com/user-attachments/assets/d5af3b70-0a98-458a-b660-c6be160a1910">

This could either be fixed in the SDK or there might have been an RPC endpoint issue, or something else. Can you also verify from your end?

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KApgdgbgXABAcgLYEMCWEJgC4IDQgCuAzmAEpgAmYxaA5hPNgE6FgEC%2BQA) (Connect v2), [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) and https://portalbridge.com/. Balances are successfully loaded on Fantom network. 


Ticket is closed.

**Comment by agodlevska** [comment]
Reopening the ticket, issue reproducible on https://wormhole-connect.netlify.app/. 
Balance is not loading for Fantom. 

```
Failed to get token balances Error: network does not support ENS (operation="getEnsAddress", info={ "network": { "chainId": "4002", "name": "unknown" } }, code=UNSUPPORTED_OPERATION, version=6.13.2)
    at makeError (main-DEJ0TEGo.js:281:68890)
    at assert$6 (main-DEJ0TEGo.js:281:69074)
    at u0.getEnsAddress (main-DEJ0TEGo.js:282:159239)
    at async u0.Wu (main-DEJ0TEGo.js:282:160249)
    at async u0.fromName (main-DEJ0TEGo.js:282:159483)
    at async Uu.getResolver (main-DEJ0TEGo.js:282:185075)
    at async Uu.resolveName (main-DEJ0TEGo.js:282:185230)
    at async checkAddress (main-DEJ0TEGo.js:282:7353)
    at async main-DEJ0TEGo.js:282:95304
    at async Promise.all (/index 0)
``` 
```
Failed to get token balances Error: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0x70a08231000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01", "to": "0xfB174b43228950C2055CFc25AE93f2DCe8E2beF0" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (main-DEJ0TEGo.js:281:68890)
    at getBuiltinCallException (main-DEJ0TEGo.js:282:107247)
    at fu.getBuiltinCallException (main-DEJ0TEGo.js:282:108201)
    at Uu.getRpcError (main-DEJ0TEGo.js:282:211293)
    at main-DEJ0TEGo.js:282:215228
``` 
```
Failed to get token balances Error: could not coalesce error (error={ "code": -32062, "message": "Batch size too large" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (main-DEJ0TEGo.js:281:68890)
    at Uu.getRpcError (main-DEJ0TEGo.js:282:212926)
    at main-DEJ0TEGo.js:282:215228
``` 

Attachment:
<img width="1440" alt="Screenshot 2024-10-07 at 14 28 12" src="https://github.com/user-attachments/assets/47202485-2ca2-4210-8cee-3109319459c1">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Balances are successfully loaded on Fantom network.

Closing the ticket. 

Attachment:
<img width="589" alt="Screenshot 2024-10-21 at 15 58 51" src="https://github.com/user-attachments/assets/014abd70-e401-429b-9974-36adf9b30047">
