### ISSUE TITLE
[QA] [Testnet] SUI token balance is not loading

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2402]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Sui network in From section
2. Connect Sui wallet
3. Check if SUI token balance is diplayed. 

Actual result: SUI token balance is not loading.
Expected result: Correct SUI balance is displayed. 

## Notes/ Attachments

Issue is not reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 

```
Error: Chain Sui not supported
    at toMayanChainName (main-C23N_Ad5.js:278:786317)
    at fetchTokensForChain (main-C23N_Ad5.js:278:786766)
    at MayanRoute.supportedSourceTokens (main-C23N_Ad5.js:278:789550)
    at SDKv2Route.supportedSourceTokens (main-C23N_Ad5.js:280:197908)
    at async Operator.allSupportedSourceTokens (main-C23N_Ad5.js:280:203899)
    at async main-C23N_Ad5.js:313:24488
```
    
    
![Screenshot 2024-08-19 at 12 51 23](https://github.com/user-attachments/assets/21282eaf-93e6-4797-8862-fdfd8239541c)

![Screenshot 2024-08-19 at 12 46 25](https://github.com/user-attachments/assets/0ae5e1cf-a3a3-4b77-a44a-a80d8e2e0a5f)

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D). 
The SUI token balance is now successfully loading and displaying.

Closing the ticket. 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-26 at 09 12 19" src="https://github.com/user-attachments/assets/d25dcb4a-5408-4949-a795-bf1ffa941109">
