### ISSUE TITLE
[QA] An error page opens after clicking on APT contract address link

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2403]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Aptos as source chain and connect Pontem wallet
2. Click on contract address link below APT token

Actual result: An error page opens https://explorer.aptoslabs.com/address/0x1::aptos_coin::AptosCoin?network=mainnet
Expected result: APT token page opens. 

## Notes/ Attachments

![Screenshot 2024-08-19 at 14 05 49](https://github.com/user-attachments/assets/313963d8-8536-43d3-8009-e53c20c21bac)

![image](https://github.com/user-attachments/assets/43936855-195c-409b-ba5b-156836c98537)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 

Attachment:
<img width="1440" alt="Screenshot 2024-09-30 at 17 45 21" src="https://github.com/user-attachments/assets/a58ca1e5-7be0-4b12-a75c-2a84f0c665d5">
