### ISSUE TITLE
[QA] APT token is displayed as "Unknown" in Phantom notification

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2408]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/321a610744/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Send 0.0001 APT from Evmos (Leap) to Solana (Phantom)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Check token name in Phantom notification
 
Actual result: APT token is displayed as "Unknown". 
Expected result: Correct token name is displayed. 

## Notes/ Attachments

![Screenshot 2024-08-20 at 16 52 32](https://github.com/user-attachments/assets/43bf4f85-6a41-4655-adcc-854fbed43355)

**Comment by agodlevska** [comment]
Issue reproducible on https://portalbridge.com/, when sending 0.01 APT from Injective (Leap) to Solana (Phantom). 
APT token is displayed as "Unknown".

Attachment:
<img width="1440" alt="Screenshot 2024-09-04 at 10 52 00" src="https://github.com/user-attachments/assets/695dd375-9a66-4132-ada0-33c4e55331c1">
