### ISSUE TITLE
[QA] [Mainnet] Previously searched networks are only shown next time when Selecting Network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#241]
Preconditions: None

Environment: 
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
MacBook Pro, macOS Ventura 13.0.1, Firefox version 109.0.1 (64-bit)

Steps:
1. Click on Select Network
2. Type in the Search field letter "u" for example
3. Observe search results
4. Click on "X" to exit Select Network window
5. Click again on Select Network
6. Observe

Actual result: Second time opening the Select Network window only previously searched options are shown in the list, user has to refresh the page for the list to fully show again or make a new search and then delete the search.

Expected result: When closing the Select Network with search results, full list should be shown next time opening Select Network.

Attachment:

https://user-images.githubusercontent.com/91047061/226522256-84a7e4f6-dcfc-4f87-bf0d-b839d0196a2e.mov

**Comment by tsadovska** [comment]
Issue is reproducible on:
* https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/
* https://wormhole-connect.netlify.app/
