### ISSUE TITLE
[QA] [Testnet] Transaction is stuck at claiming step, SOL transfer Solana → BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2424]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64). 

Steps:
1. Send 0.001 SOL from Solana (Phantom) to BSC (MetaMask) with Manual route
2. Click on "Claim" button
3. Open MetaMask extension and check the transaction status

Actual result: Transaction has been pending for more than 1.5 hours.
Expected result: Transaction was completed successfully. 

## Notes/ Attachments
* Link to [Wormholescan](https://wormholescan.io/#/tx/55xDHNoDDeLvgY8oB9wBJRukASnrvMDn5NwTKSQJQmYhx16EwKtx5AsSaW5CYU9MadeNqXKTEbesLGdMdnWMPsgV?network=TESTNET)
* Link to [BscScan](https://testnet.bscscan.com/tx/0x34ceae8a11cabaedf56e19eeec0bc5be6c8ad578ed6e641da0ea425a4a4ac08a) 

![image](https://github.com/user-attachments/assets/db5d5c23-87c3-4d72-aca7-38705c0304fb)

**Comment by emreboga** [comment]
@tsadovska I've followed your steps and can get to the claim step. It completes the transaction but still shows an error (see below). I think the original issue is not there but we might have another one. Can you verify this from your end as well? 

<img width="1396" alt="Screenshot 2024-08-26 at 9 43 37 PM" src="https://github.com/user-attachments/assets/ac250ba9-1acc-49de-a53d-b854f8cee042">

**Comment by tsadovska** [comment]
@emreboga 
* [Original scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2424#issue-2482857350) is no longer reproducible on https://wormhole-connect.netlify.app/, claiming step finished successfully. Please see link to  [Wormholescan](https://wormholescan.io/#/tx/ksMdxRTuhMdMyspiG2doSQtfNoyGseiCU6xLjUiPKTVbeGTUuhwQ3aD4XjwWwPjpkMidE6XwwzRMiZdj3qJJDzu?network=TESTNET). The issue was caused by having some pending transfers in the wallet. After I canceled them, the transaction proceeded.
* Checked SOL transfers from Solana to BSC/ Polygon on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KApgdgbgXABAcgLYEMCWEJgC4IDQgCuAzmAEpgAmYxaA5hPNgE6FgEC%2BQA) and all completed successfully without errors. I tested with Phantom, Solflare, MetaMask, and Rabby wallets.


I am closing this ticket and will let you know if I am able to reproduce the issue you had.
