### ISSUE TITLE
[QA] Unavailable route is shown as selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2425]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Prepare to send 5 SOL from Solana (Phantom) to Fuji (MetaMask)
2. Select Automatic route option
3. Change Amount to 0.001 
4. Check if Automatic route option is shown as selected when route is unavailable 

Actual result: Automatic route is selected. 
Expected result: Manual route is selected.

## Notes/ Attachments

https://github.com/user-attachments/assets/62444de4-dd64-4ed3-b26c-f073abba7ba7

**Comment by emreboga** [comment]
This was a previously known issue which is currently fixed. Right now the routes list updates correctly for unavailable routes when user enters an invalid amount input.
@tsadovska can you verify from your end as well?

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/. 
Issue is no longer reproducible, manual route is selected when user decrease amount. 
Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/a98dd9b6-4f03-4061-8502-f76c86656cac
