### ISSUE TITLE
[QA] Blank screen appears when changing slider position - networks were swapped 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2426]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Prepare to send 3 USDC from Arbitrum (MetaMask) to Avalanche (MetaMask)
2. Click on Swap button
3. Select Automatic route 
4. Click on "Review transaction" button
5. Change slider position 

Actual result: Blank screen appears. 
Expected result: Slider position is changed.

## Notes/ Attachments
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2363

https://github.com/user-attachments/assets/fbc5b829-1f45-4dcc-88d3-40e4a99b6bf3

**Comment by emreboga** [comment]
This is a regression from recent Route changes. We have removed the static `routeOrderOfPreference`, but we need to remove the whole `establishRoute` function.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KApgdgbgXABAcgLYEMCWEJgC4IDQgCuAzmAEpgAmYxaA5hPNgE6FgEC%2BQA):
* Blank screen does not appear after user changes slider position
* Transfer finished successfully, link to [Wormholescan](https://wormholescan.io/#/tx/0x023ca20aac25fc14a8f1255f0cdf622f390d05b3c2fe3d5c2b370e773e3de0f8)
