### ISSUE TITLE
[QA] Improvement of user experience when sending asset from Solana, Aptos or Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2427]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

User story: User wants to send asset from Solana, Aptos or Sui. MetaMask wallet was previously connected for EVM chains. 

Steps:
1. Refresh the page, [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2)
2. Click on "Select chain and token"
3. Click on "+ other" option
4. Check if Solana, Sui, Aptos networks can be selected

Actual result: Solana, Sui, Aptos networks cannot be selected. To send asset from Solana, Aptos or Sui, user needs to disconnect MetaMask wallet, then change the network.

Expected result: User should be able to select Solana, Aptos or Sui network even if network is shown as not available for selection. After that, MetaMask wallet should be disconnected. 

## Notes/ Attachments

https://github.com/user-attachments/assets/c25cd611-0a71-479e-9876-9429016528d4

**Comment by emreboga** [comment]
This is a negative side-effect of pre-selection of Ethereum for the chain when user opens the asset picker, which also triggers to connect to the last known EVM wallet.
@Wesleyleung We need product input here. Do we want wallet-auto connect when user first launches the asset-picker? This allows use to show the balances in the token list. I don't think we can have both showing token balances by default vs. not auto-connecting which restricts the network selection to the wallet supported ones.

**Comment by artursapek** [comment]
We should definitely let users select any network regardless of what wallet is currently connected. The connected wallet should not dictate the options.

If the user picks a chain that's incompatible with the currently connected wallet, Connect should either disconnect it or auto-switch to the compatible one (if the user has connected it before).

**Comment by Wesleyleung** [comment]
Additionally, current Connect ties the logic to what networks are shown based on wallet, but with more and more wallets supporting multiple chains, this becomes a maintenance issue (eg. Phantom only being shown when selecting Solana or vice-versa). 

I agree with Art's suggestion. We should decouple wallet and network selection filtering. This may lead to a few logic changes:
1) If a user already has a wallet connected, they can select any chain.  
- If they select an incompatible chain, disconnect the wallet and let the user choose a new wallet OR auto-switch to the last known connected compatible wallet, if available.
2) If a user does not have a wallet connected, they can attempt to connect to any wallet detected on their browser. This will trigger a check on the network that's been selected:
- Check if the wallet they've chosen is compatible with whatever network that happens to be selected (whether its the empty state like Ethereum or the user chose to change the network first, it doesn't really matter). 
- If the wallet is incompatible with whichever network that had been selected, show an error in and have them try another wallet.

**Comment by Wesleyleung** [comment]
this has been fixed with suggestion #1 above
