### ISSUE TITLE
[QA] User is not able to change wallet multiple times in a row (Solflare/Phantom)

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#243]
Preconditions: 
1. Wallet is not connected
2. MetaMask/Phantom/Solflare extensions added to browser

Environment:
MacBook Pro, macOS Ventura 13.0.1, Firefox version 109.0.1 (64-bit)

Steps:
1. Click on Connect Wallet
2. Choose MetaMask and proceed to connect to the app
3. Click on Connect Wallet button again and choose Change Wallet
4. Click Phantom
5. Change the wallet back to Metamask
6. Now Click on Connect Wallet button again and choose Change Wallet
7. Click on Phantom
8. Observe

Actual result: When choosing to switch back to Phantom/Solflare wallet when it was already previously connected, the buttons for Phantom/Solflare are not responding.

Expected result: User is able to change wallets.

Attachment:

https://user-images.githubusercontent.com/91047061/226614774-ab70a838-dbed-4cbc-8bde-1d18d8e6c352.mov

**Comment by anondev2323** [comment]
This was fixed a little while ago.  This is on the latest deploy

https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/c3b559e3-b55e-46de-a0ea-483d7bc2e2d5

**Comment by AigaD** [comment]
Tested OK.
Scenario: Verify that wallets can be changed multiple times in a row.
Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
MacBook Pro, macOS Ventura 13.0.1, Firefox version 109.0.1 (64-bit)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ef4fe1f3-e688-41e0-b5e1-53c0a30ce822
