### ISSUE TITLE
[QA] Contract addresses displayed on the wormhole-connect do not correspond with the contract addresses in MetaMask

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2432]
## Describe the current behavior in detail
Checked on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) and https://wormhole-connect-mainnet.netlify.app/ with macOS 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Select Polygon network in From section
2. Search for WFTM asset
3. Observe the contract address
4. Compare token contract address in MetaMask

Actual result: Different contract address is displayed in MetaMask. 
Expected result: Contract address is the same. 

## Notes/ Attachments
* https://wormhole-connect-mainnet.netlify.app/

![Screenshot 2024-08-26 at 13 46 59](https://github.com/user-attachments/assets/2e129619-4b00-4a86-ad2c-61b2c9a89392)

* https://wormhole-connect.netlify.app/:

![Screenshot 2024-08-26 at 12 42 08](https://github.com/user-attachments/assets/e84d3a32-e5bd-40be-9cc6-3fde169d7609)

Issue is also reproducible with other assets.
Issue is not reproducible on https://portalbridge.com/.

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-testnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (connect v2). 

CELO contract addresses on Ethereum do not correspond with the contract addresses in MetaMask. 

Attachment: 
<img width="1440" alt="Screenshot 2024-08-26 at 15 39 20" src="https://github.com/user-attachments/assets/78fcd02e-e908-42b6-b80a-5c1c721cb51a">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/user-attachments/assets/07574e22-6e01-409d-a402-b4fb29b12580)

![image](https://github.com/user-attachments/assets/b4522fad-ea92-44eb-9bfc-9be33dc90da2)

Ticket is closed.
