### ISSUE TITLE
Transfer Error Unknown 

### ISSUE THREAD

**Issue by developerdeep01** [wormhole-foundation/wormhole-connect#2439]
I am transferring solana native token to ethereum native token and getting unknown error while transferring . Also getting the same error while testing the already deployed websites, such as pancakes, jupiter etc .

**Comment by Etandooley** [comment]
@developerdeep01 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by tsadovska** [comment]
Checked following scenarios on https://portalbridge.com/:
* Transfers with Manual Bridge route and Native Token Transfer Manual route
* Transfers with Automatic Bridge route and Native Token Transfers Automatic route 
* Transfers with new account
* Transfers with insufficient SOL balance in Solana account
* Transfers with insufficient ETH balance in Ethereum account
* Transfers with different Solana wallets: Phantom, Solflare, Bitget, Backpack
* Transfers with different Ethereum wallets: MetaMask, Rabby
* Transfers when target chain wallet address was entered manually

All transfers finished successfully.
