### ISSUE TITLE
[Bug/UI issue] I should be able to select a chain for a different wallet type

### ISSUE THREAD

**Issue by artursapek** [wormhole-foundation/wormhole-connect#2441]
Steps to reproduce:

1. Connect Metamask for an EVM chain at least once so Connect auto-connects it
2. Select Ethereum as the source chain, and Polygon as the destination chain
3. Click on the destination token picker and try to change from Polygon to Solana
4. Notice that Connect doesn't let you click on Solana at all because Metamask is already selected as the destination wallet

I would expect Connect to let me select Solana, and either disconnect the destination wallet or, if I've previously used a Solana wallet, auto-connect my Solana wallet. This current behavior is frustrating and confusing.

<img width="503" alt="image" src="https://github.com/user-attachments/assets/b2909ade-0525-4c39-b1bb-9d7f139dec99">

**Comment by tsadovska** [comment]
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2427  Improvement of user experience when sending asset from Solana, Aptos or Sui.
