### ISSUE TITLE
[QA] [Improvement] Add network information for USDC identification

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2457]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Arbitrum network as source chain (MetaMask wallet was auto-connected)
2. Search for USDC token

Actual result: Network information is not displayed next to the token.  Since there are many different USDC options to choose from, it might confuse users.

Expected result: Network information is displayed next to the token.

## Notes/ Attachments
Current behaviour:

![image](https://github.com/user-attachments/assets/c86b85cb-3c22-4314-81a7-ef8fffc9ad87)

Expected behaviour:

![image](https://github.com/user-attachments/assets/550c1afc-8221-47b3-9d3d-e8e1e5335818)

**Comment by Wesleyleung** [comment]
This should be resolved with PR 2445
