### ISSUE TITLE
[Bug] Token list should be scrollable with all tokens

### ISSUE THREAD

**Issue by emreboga** [wormhole-foundation/wormhole-connect#2460]
## Description and context
Currently this is a short-list with top 5 tokens.

## Steps to reproduce

1. Open an asset picker
2. Select any network

## Experienced behavior

See that the token list shows the top-5 only.

## Expected behavior

It should show all tokens in a scrollable list with 5 visible.

## Solution recommendation

We can make this scrollable just like the network list.

**Comment by tsadovska** [comment]
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2378 [QA] [Improvement] Add scroll functionality for viewing all tokens with balances in network token selection.
