### ISSUE TITLE
[QA] Native token of the previously selected network remains visible in the token list

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2470]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Polygon network and MATIC token in "From" section (MetaMask wallet was auto-connected)
2. Select Ethereum network and ETH token in "To" section (MetaMask wallet was auto-connected)
3. Change target chain from Ethereum to BSC
4. Check if ETH token is displayed in the list

Actual result: ETH token is displayed in the list. Token is greyed out and cannot be selected. 
Expected result: ETH token should not be displayed in the list on BSC network, because it is a native token of Ethereum network.  

## Notes/ Attachments

https://github.com/user-attachments/assets/8ecfc35e-5511-4cab-b088-0931a0e8447e

**Comment by artursapek** [comment]
I don't think this is a bug. it works with any token. for example, select USDC on any EVM chain, then close the menu, then open it again and switch chains. USDC is at the top of the list. I think it's maintaining that for you on purpose in case you want to switch chains and keep the same token that you had before.
