### ISSUE TITLE
[QA] USD equivalent and Bridge fees are not displayed after returning to "Bridge assets" screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2471]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Prepare to swap 0.288334 SOL from Solana (Phantom) to WSOL on Ethereum (MetaMask)
2. Select "Automatic route Mayan Finance"
3. Click on "Review transaction" button
4. Click on Back button
5. Check if USD equivalent and Bridge fees are displayed 

Actual result: USD equivalent and Bridge fees are not displayed. 
Expected result: USD equivalent and Bridge fees are displayed. 

## Notes/ Attachments
Current behaviour: 
![Screenshot 2024-08-29 at 08 02 01](https://github.com/user-attachments/assets/95920a00-1ac4-4f02-a9b4-df87f3799b74)

https://github.com/user-attachments/assets/fa21bbe8-985a-4486-95a6-dd2dfa63e190

Expected behaviour:

![image](https://github.com/user-attachments/assets/a80a055a-711f-46d2-b2a4-b30e989b853e)

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, USD equivalent and Bridge fees are displayed after returning to "Bridge assets" screen. 

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/47c99037-8245-44e1-bdbb-f48e7e8f6209
