### ISSUE TITLE
[QA] Cannot resume a transfer

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2475]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Swap 0.04 SOL from Solana (Phantom) to ETH on Ethereum (MetaMask)
2. Open https://wormhole-connect-mainnet.netlify.app/
3. Click on "Resume transaction" link
4. Search for transaction

Actual result: Transfer not found.
Expected result: Transaction is found.

## Notes/ Attachments
* Send from tx: [Solscan](https://solscan.io/tx/2zsSErWrqT4hfy2Z1UfYwg4id1HKptQmfgKrm7Rjk4aySwngx4pzgZA95SefazXd1usGR6VufCa2gb36QkB5RHUr)
* Send to tx: [Etherscan](https://etherscan.io/tx/0xe08fb934410243326837d1d864e23c18b163575daa94960ad04dba9a91e78474)

```
Error: no bridge messages found
    at SolanaWormholeCore.parseTransaction (main-D-Ks2QVS.js:275:111770)
    at async main-D-Ks2QVS.js:245:42090
    at async main-D-Ks2QVS.js:245:6422
```

![image](https://github.com/user-attachments/assets/95641f8e-3b24-4fae-b417-d767e3b0cc00)

![image](https://github.com/user-attachments/assets/4a1c18d6-f93f-43fe-ba69-7117d3f0ff69)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending asset with "Manual Bridge" route. 
Scenario checked: 0.0001 SOL transfer from [Solana](https://solscan.io/tx/5Nw1sD4Sjimr9AGgfH2yY2dRk7zuzFb85vLWQFPiByLCDXmo6W4y8Lg24iBemG5Z1n7qyrAaA7rPVkG2NuoyUHHj) (Phantom) to [Ethereum](https://etherscan.io/tx/0x16aed3f207cf89648e54649b53c714c9f75dc13c5c1e134c83d3c96e6659f92e) (MetaMask). 

![image](https://github.com/user-attachments/assets/1555ffca-e66c-4a24-8055-41edae32b10b)


Loading doesn't finish on "Resume transaction" screen when searching for `5Nw1sD4Sjimr9AGgfH2yY2dRk7zuzFb85vLWQFPiByLCDXmo6W4y8Lg24iBemG5Z1n7qyrAaA7rPVkG2NuoyUHHj` in Solana network. 


```
Uncaught (in promise) Error: when deserializing item 'mintRecipient': chunk is shorter than expected: 1048 < 1060
    at updateOffset (main-D-Ks2QVS.js:240:9945)
    at deserializeLayoutItem (main-D-Ks2QVS.js:240:11783)
    at internalDeserializeLayout (main-D-Ks2QVS.js:240:10177)
    at deserializeLayout (main-D-Ks2QVS.js:240:9641)
    at main-D-Ks2QVS.js:240:142534
    at deserializePayload (main-D-Ks2QVS.js:240:142777)
    at deserialize$1 (main-D-Ks2QVS.js:240:142172)
    at getVaa (main-D-Ks2QVS.js:245:19975)
```

![image](https://github.com/user-attachments/assets/2aa87c23-2f80-4f9e-acd7-caa9b58e9926)

**Comment by artursapek** [comment]
The first part of this issue isnt a bug - you can't resume a Mayan transfer. It's only an automatic route (this has been fixed)

The second part of this does look like a different, valid bug.

**Comment by tsadovska** [comment]
Comment from @kev1n-peters in ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2313

> Connect does not support resuming automatic transfers at the moment
