### ISSUE TITLE
[QA] [Improvement] Show a warning message when user clicks on "Start a new transaction" button and transaction has not completed yet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2476]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Swap 0.04 SOL from Solana (Phantom) to ETH (MetaMask)
2. Click on "Start a new transaction" button when status "Transaction submitted" is displayed

Actual result: User is redirected away to "Bridge assets" screen without confirmation. 
Expected result: Confirmation is shown when user tries to leave the page while transaction is still in progress. 

## Notes/ Attachments

https://github.com/user-attachments/assets/4430cfff-e0d6-4436-bd5a-b69dfbf03c32

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/0af992dedf/. User is redirected away to "Bridge assets" screen without confirmation.

https://github.com/user-attachments/assets/d1ba0719-1a44-4d7a-87dc-d213e8922a42

**Comment by Wesleyleung** [comment]
I forget, does the current Portal show a confirmation message? If you have a screenshot of that, that would be helpful!

**Comment by tsadovska** [comment]
@Wesleyleung On https://portalbridge.com/ there is no confirmation message, because "Bridge more assets" button appears after bridge has completed. On new Connect/ Portal "Start a new transaction" button appears when transfer is started.

So maybe there should be a confirmation message that user is redirected away to "Bridge assets" screen or "Start a new transaction" button should appear later, after bridge has completed.

https://github.com/user-attachments/assets/75929638-6ed0-4721-8a3a-fb82c2aaf2a4

![image](https://github.com/user-attachments/assets/b4edd518-d07d-4277-adea-9d775fe10591)

**Comment by agodlevska** [comment]
Reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aC89fUhYWBCwhgAKUG9vWERUaEgGOh0UsHMAORsnHzsLdwMAYS1cvLBkuryAYyZCSEwsI1gmaAEqHHJaxvxIPElkDoAGAA9oACExSugATjxlgEYAZjFlgBZJyaMjAHYAVmgAM031pYAOACMxTd3dgDYAJgNJ9bx1pvXBo08mkMu1sDMzJN7rdXssNk0PusHptXv8xOtlgZdnh3isjPdJk0jCjJq95rtboCgalkEEGE1oAQAG69GrUvINdkpPBiMQCIRTaanU4XY63d6TTanY7mdbHMzrIyVe4UozLU6Y05GV6bY73EwmdWvMSvExUrmpfwAB2gHSQyBwLAANtBzVylEM6gBdCKND3sznUlptDomIJpAa%2BoEjMas8HTV63MRzd4XSanMw4sTHY7GC7LW7rC5id73aCbd6vV5bfZNZbvBsmOZuoEgzKC94mY6bTaTdVzW6TSG7e6bB6TAzrQmVW63Xand7Y7Z96EovAtxoyOkM5lx7QWiCBi08vmCbLxh67Y5p3HHaASuW7JrHV54fNTnlNSY8254EeS3ZUyfDd2Vga1bWwe1HUQF0QL9KNGh9T1vH9RCEIgKxxEQOx4AYWAjBsAAJNlqSPRpgyIDouh6PpI2QlIY3GQV7j2X9ljHd5jhNX9xRMV5Ti2Mx0TFZZXl2Aw%2F1ua97zmAxljglI2zBLAZmvTZlkqU5CxMDVTjmU5NiaU4mnuDF7i%2BUcLiTMxUXYrV3kqPBJgUmlt0ZFkJjAfcDzI9kT35c8VOmBUzEqSp1mgMkxDwFNtOgR4NmJATTj7TYTHWYxtPeYznPQ6kwJtO0UGg2C8rqVD2SQ9kKsaXzmlaSjsDmekXIgRi4yC2FtNORFYRuOYLmJAwxAMBddjEE4pxfe5jmWEwh0mTjKTK1J0nbeNKyM6BvjGkttXeQczApEx3iMyYLj4gxoDvBc1WrG5WrALcsh3DySItOqgX8s9mPLLttsTY53iMSYxD4yoDBlEwpTmY48D%2FOZTJeV4qjhGFHsU8CiodZ1XRWlIaqBKrqUJ7xibqYR3tq%2BjvAo5T3BgoJ13xsB2s8rAilgTNEAMAApJgMkI6A8AANQsQjIH8Jh4HuTgCjMApXmEXg5itQjUEIuYbARbMmSsABpR6lI6W5ThFuYTAARQALUqZYbGt1ALjwK1YDmYQACsmQseBjgATXua2Pf8BcbJwD3YE4ABxD28MtswcEto3aRe9y9xplJPsab6BWwTnub5gXoCF0Xxcl6XZflxXldV9XNe141jj1w2WcxwrIOK3GMcUFnyepABHKhEHUdmCn7k0AA1%2B7MW4rHuBhKioKPbh8KxhGEKhOBhU4ChF14PYcdYfHuCfoH16YsUIg2%2BZc0nM4zsA6ao7pemgfpHrZwUvyBuZ1jMIwrgomgMNaAGphyiThAA3Y0Bbhhk1HsI6y0H7G3jHMc6YZBwHFnGSaUJgYS8gXGJFiWlSzvCElJe4pYNjJzcruTy3kPoP25LyAKgoDD3GFLses2YMQTnWPcPARhbihXuCDdS6wbi7GJCcQCgNCTdwgAVCCWAoJd1bj3B%2BfdyorSzhAJ%2B2AzDIHuAQGQ78Waf3jAZHsYghxNBstiecQ5eSmmgF2FGKMthnC7JWSocwKS7CNmtZSMw0EXTwJgyY2DQEynwWIQhI51TikoeQvUVCAQs2evSNO9CmH1FyRAHOgUZiTnCWYOYsJtqLSrDA2GGxfh6UqFeASux1gGTMCleceBXgKKeljDuOMYJ41yXfPIWi8gjMPA%2FfRWAnCuwIDgAgDA6IWgsUFH4ux0p4Fmudd4aULgsRzO8USqJynQ2NJUE0WlJSbGgFsQJoJBShIwQcSJMJol4ONHEysCSSHJLEBQtJNDU50KpgGfJYBCmCmWOZB4eoFzHEqEdSK3ZbhNFkjFMGAlKgNjeK8M4rxJjdjED0pR2MSpDIPBoi0YyCY6KmQ1ZScw8AMApVyVZMwrHLjMHYsSf4UpCRNCYVxL4DAeN1KcbxrxfH%2BPuetIKTzwkvKibg2J8TiFJLIf81JLF0nIJTlkkFXlcm6LyJC%2BMJThHlOWJUysZJbi1J%2BK0uYjSzjrBaW0jppwukkr6Sozugzu4TLJitEZYyaoKAAJReCQpQKgLKHDQDEIIAgvAwSmPCCASgSkF6IEgBcFNOQUi4XwkReeTRC15AyP4O0eECKETLRuBg%2FgcD3BgjWkthENyjFgLuSoDKOjNSaBuJSbAxAVrqNMwdcEzVBU2ucHai49ofEOsdU6KULoo2uqA4GokJGVA3KTAgTRc0dCYDEK02QAD0l7mUstgAwXQx6iCSCaKgRAj7EA4EvU%2BrIl75mxgYJepEtxniXrwkEaKyAxCXuLXW3QVpIC8A3D%2BqO0BX2IFHXaWkVobRiAALR4TgEwZDMEUAdAAMSbDMGYNKZoEJJqaP%2Bp054kS%2BhqsIBgjNRjju8FWjoHGuPMyGE2ltbbsDCC7XgHtLI%2B0hmwAzJ0TNh1BMw3koE0yFNKbyjO025sra23to7Z2rt3Zex9v7QOwdQ6vHDpHGOccE5JwQoe49ykz2wAvega9t64APp%2FS%2Bt9H6v0%2FsA%2F%2ByQgGpSROOGB2AEG8BQZg5%2B5AuM7BOj4NhC4VAnROjsMetLyA7DIF4PcOwEoDhWmmHYIGOGCB2H2S%2BV8TRTZ4Hg4hgA%2FHKSJiZbjqgCQhFDaG32qb9QM0qQwGNMfPK8NjvphBEdfv0HjEA%2BPifm7RRtzbW1On45J6T0BZONU6C%2FdbCER1jrU%2BRft2BqILeWdnFhP1UHoMVVgt5KrPlqsSaQlJlCdUHoQkek92B3Oee80IXzH7n2Dffce4LiAiChfwOFy9kWpIxbiwlpAOBkuDNS%2BlurWWct5ZQIV4rpWXkVaq%2B8GrdWZpVjwE1r1rXeAdeOF12cvWSNEFQ%2Bh4bqiA30bQ5NzArHcjsfi8Y0xOAltgBW1gYQEuTGyDuykETW2dsIW7b2q7WBDGS%2BV8p0Eqm6rTL10rsxyEZ0hOexE5VMSPvfPVd9rVv3qHOYB650956r03vB%2FeyHiHodBe%2FfD39YXBAo5Smj8DkBIPQaxzjl0ePeAZcJ7l0jBWislbK5MSn1WrS1fq%2FTxnLWEMs86zCDnpw%2BtDAG7z87I3yUbgm%2FgZjIvbgzdyMIRAcyFlLJl3L7vvfFkq%2B8GrsT8vdva7kzM4fSzDeZGN8haZsye199H8w08ud5U26VW9%2B3BDHdfb%2BQCv77uhiA7c97rzvu71%2BdDwFmHn6Q8I7%2FUjiPqPosx7j4l7HKW0sp4E7Zbp75ak7Z4U6Vb56F506NbNbM6s7s49bV5c6QA85DYN785jZ1At54Bt5gCi60pd4CIsoD7QDVribEGsqq6bYT4Saa5SbT6HZMosoL6QBL7qY67MFUGmoPbb7W5hK2774fKH5ELH6aqn5u5DAuZA5YAg4%2B4%2Bb%2B7%2BZB6w4v5h7v4RZR5f6xax7xbx5Jb%2F746ZbAHE6Z5k45557U4F604NYM5wFl4IGV5IE14Tqh5oEYYYH%2BpYF5A4F4EEEoReAegKAADcIAQAA%3D%3D%3D), when sending 0.1 USDC from Optimism to Base via AutomaticCCTPRoute. 
The ability to click on the "Start a new transaction" button appears only if any automatic route is used.

Attachment:
<img width="1440" alt="Screenshot 2024-10-04 at 12 39 01" src="https://github.com/user-attachments/assets/62409df6-7a2d-4c44-b678-52319c0a2422">

**Comment by tsadovska** [comment]
Closing the ticket as not a bug.
