### ISSUE TITLE
[QA] Estimated time differs from actual time required to complete the transaction

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2479]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Swap 2.4 PYTH from Solana (Phantom) to USDC on Arbitrum (MetaMask)
2. Check "Time on destination" value
3. Wait until the transaction completes

Actual result: "Time on destination" value is 00:12.
Expected result: Еransaction completed after an hour.

## Notes/ Attachments
Link to Mayan Finance Explorer: https://explorer.mayan.finance/swap/5G38fuEXH4tovT4LwnqpzRJGt5mAx9ncMtBDBNkUXEiNChCi9F2s8r5k8FVdJfLAvDKgM4TcggMUshLuHFSQYM8z

![Screenshot 2024-08-29 at 12 51 37](https://github.com/user-attachments/assets/95eb5fb2-a8e0-415a-a817-04a1d19db01f)

**Comment by agodlevska** [comment]
Issue reproducible on https://wormhole-connect-mainnet.netlify.app/, when swapping 2 USDT from Ethereum (MetaMask) to ETH on Arbitrum (MetaMask). 

Attachments:
<img width="480" alt="Screenshot 2024-08-30 at 13 24 37" src="https://github.com/user-attachments/assets/448adaa9-869e-45ab-ac82-bff67ecf188c">

<img width="1299" alt="Screenshot 2024-08-30 at 13 29 24" src="https://github.com/user-attachments/assets/644c8e7c-dce6-40ab-8949-72ce3c135896">
