### ISSUE TITLE
[QA] Different "Time to destination" value is displayed before and after clicking on "Review transaction" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2482]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Prepare to swap 0.0006 ETH from Ethereum (MetaMask) to SOL on Solana (Phanton)
2. Check "Time to destination" value
3. Click on "Review transaction" button
4. Check "Time to destination" value

Actual result: "Time on destination" value before clicking on "Review transaction" button is 24:00. "Time on destination" value after clicking "Review transaction" button 0:00. 

Expected result: "Time to destination" value is the same. 

## Notes/ Attachments

https://github.com/user-attachments/assets/b0baab29-f0a8-47f4-9633-2764f2f6f491

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D). 
Issue is no longer reproducible, "Time to destination" value is the same.

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/868d0c7a-2fcf-4839-923a-c157f04e138a
