### ISSUE TITLE
[QA] [Improvement] Add network information for WETH identification 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2484]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select Avalanche network in "From" section (MetaMask wallet was auto-connected)
2. Search for WETH tokens 

Actual result: Network information is not displayed for WETH (Ethereum), https://avascan.info/blockchain/c/address/0x8b82A291F83ca07Af22120ABa21632088fC92931.

Expected result: Network information is displayed. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/929d823f-d228-49f5-8fcf-e1248b799147)

**Comment by Wesleyleung** [comment]
this should be fixed now with frankeinstein asset filtering
