### ISSUE TITLE
[UI-Feature] Wallet network filtering is too strict / no longer accurate

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2487]
## Description and context

Wallets are increasingly becoming multi-chain and assumptions we had in the past such as Phantom being Solana only are no longer accurate. When a user selects a network and then looks at supported wallets, they should see a much broader list. We should add Phantom and Backpack to the EVM supported list so the user can see the following choices when they select a network.

**EVM**
-Metamask
-Rabby
-Coinbase
-Phantom
-Backpack

**SVM**
-Phantom
-Backpack

**Comment by sebastianscatularo** [comment]
PR closed, https://github.com/wormhole-foundation/wormhole-connect/pull/2556

**Comment by yuli-ferna** [comment]
Should be fixed https://preview.portalbridge.com/b1f3c5115d/
@Wesleyleung @sebastianscatularo 

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/30b32240-d631-46b5-ad88-062ead7d92ad">
