### ISSUE TITLE
[QA] Native USDT is not present in Assets list on BSC network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2494]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXyA%3D%3D%3D) with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.85 (Official Build) (x86_64).

Steps:

1. Select BSC network as source chain
2. Select MetaMask wallet in From section
3. Open Assets list
4. Check if native USDT asset is present in assets list

Expected Result: Native USDT asset is present in Assets list on BSC.

Actual Result: Native USDT is not present in Asset list. Asset contract address: 0x55d398326f99059fF775485246999027B3197955.

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-08-30 at 11 20 27" src="https://github.com/user-attachments/assets/eae1446b-e088-466f-9f4b-245ed94c07ba">

**Comment by kev1n-peters** [comment]
Resolved  
<img width="516" alt="image" src="https://github.com/user-attachments/assets/e29620e5-cc78-4b22-8143-ef5d05bbdd5f">
