### ISSUE TITLE
[QA] Selected route is hidden when user clicks on "Hide other routes" link

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2496]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Prepare to swap 0.186131 SOL from Solana (Phantom) to WSOL on Avalanche (MetaMask)
2. Click on "View other routes" link
3. Select Manual route
4. Click on "Hide other routes" link
5. Check if selected option is displayed

Actual result: Automatic Bridge route option is displayed. 

Expected result: Manual Bridge route option is displayed. 

## Notes/ Attachments

Similar issue: [QA] Selected route is hidden after user returns from Confirm transaction screen. 

https://github.com/user-attachments/assets/61d4ea5e-00e3-4c95-9715-82521e5f4f55

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, selected route is displayed when user clicks on "Hide other routes" link. 

Attachment:

https://github.com/user-attachments/assets/75364b29-076c-4d62-8811-1ee9e518e6b3
