### ISSUE TITLE
[QA] Selected route is hidden after user returns from Confirm transaction screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2497]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Prepare to swap 0.186131 SOL from Solana (Phantom) to WSOL on Avalanche (MetaMask)
2. Click on "View other routes" link
3. Select Manual route
4. Click on "Review transaction" button
5. Click on Back button

Actual result: Automatic Bridge route option is displayed.

Expected result: Manual Bridge route option is displayed.

## Notes/ Attachments

Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2496 [QA] Selected route is hidden when user clicks on "Hide other routes" link.

https://github.com/user-attachments/assets/def18837-0006-4dad-9d59-0ed152653a7f

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.
Issue is no longer reproducible, selected route is displayed after user returns from Confirm transaction screen. 

Attachment:

https://github.com/user-attachments/assets/0952e8ea-fcb7-4252-a5ca-0703ba3a1981
