### ISSUE TITLE
[QA] [Improvement] Show network supported tokens in "To" section when "From" section is empty or incomplete

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2499]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Select any network in "From" section
2. Check if tokens are displayed

Actual result: Tokens are not displayed.
Expected result: Tokens are displayed. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/51000a12-e77e-421e-8a1b-b88209a3b650)

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, tokens are displayed in "To" section when "From" section is empty or incomplete. 

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/0a8e0848-b74c-48bf-9596-67bfac062f22
