### ISSUE TITLE
[QA] An unexpected error occurs after user changes destination chain - Mayan route 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2502]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.85 (Official Build) (arm64).

Steps:
1. Prepare to swap 0.000003 WBTC from Ethereum (MetaMask) to USDC on BSC (MetaMask)
2. Change destination network to Celo 

Actual result: An unexpected error occurs.
Expected result:  Error does not occurs.

## Notes/ Attachments

https://github.com/user-attachments/assets/521d09fa-d8a5-414b-bcb3-5e07f5560c75

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, error does not occurs.

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/e9dd07f9-9d11-493a-a122-70aba7a8b388
