### ISSUE TITLE
[QA] ‘Send to’ section does not finish loading after user claims tokens on mobile 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#251]
#### Steps:
1. Open Resume transfer screen
2. Search for transaction hash “0x76d726fd6720ac69a1c6b4046a118a51d169e97f702f3746a93c2298ba3b3aad” in Goerli network
3. Click “Connect wallet” button
4. Select “Wallet Connect” option
5. Click “Claim” button
6. Select “Metamask” option
7. Enter Metamask password
8. Click Back button to return to wormhole-connect
9. Observe
 
#### Actual result:
Loading on ‘Send to’ section does not finish.

#### Expected results:
Loading on ‘Send to’ section is finished.

#### Tested device:
Samsung S20 (Android 12), Chrome Version: 110.0.5481.63

#### Attachment:

https://user-images.githubusercontent.com/10746654/227226263-bbd546fb-04ae-4baf-8054-de1226b0f8e1.mp4

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1323 is closed

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] from iOS with following scenario:
1. Click Menu > Resume transaction
2. Search for 0x2fa0d4657e3bdf88cc5b83902c36637712cc8517dd44f1aab3295dfc5e5358ff (Fantom)
3. Click "Claim" button
4. Enter Metamask password
5. Return to wormhole-connect page
6. Check if loading has finished

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] from iOS 17.4.1.
Notification to confirm transaction does not appear in MetaMask app and 'Send to' section does not finish loading after user clicks on Claim button. Send from tx: [FTMScan](https://ftmscan.com/tx/0xed7932c70e22ba8445b8ad2fd525e36ff6f42a9319d4ce8fe73eecdafa49eb1b).


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/767a5252-a959-4391-af4c-c9aade3ac1be

**Comment by tsadovska** [comment]
Please view the ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1772.
