### ISSUE TITLE
[QA] Missing link to Wormholescan after transaction completion

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2528]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.114 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.0001 USDC from Base (MetaMask) to Solana (Solflare)
2. Complete the transaction process
3. Observe the transaction summary page

Expected Result:
A link to Wormholescan should be present, allowing the user to view the transaction details.

Actual Result:
No link to Wormholescan is provided after the transaction is completed.

## Attachments/Notes
Expected:
<img width="1440" alt="Screenshot 2024-09-04 at 15 03 26" src="https://github.com/user-attachments/assets/71236c8c-8d76-4a82-8f26-1ac74dbbe37f">

Actual:
<img width="1439" alt="Screenshot 2024-09-04 at 14 47 12" src="https://github.com/user-attachments/assets/f5ef3a28-6afe-4e50-85f9-a73f489b565e">

**Comment by tsadovska** [comment]
Issue is also reproducible when sending USDC from Solana (Phantom) to Polygon (MetaMask) with Manual route. 
Send from tx: https://solscan.io/tx/2dPF5k8pLYbdVg7sSvaZa9kPbqL5V4U8nh1MaXKuxqmugRUtWH7XsnSgjZxJmNRMQTwUm2ir2QnM1Dq348eAQpq6

![image](https://github.com/user-attachments/assets/45706b28-3480-4f5a-b9a4-590c848b927f)

**Comment by kev1n-peters** [comment]
should be fixed by https://github.com/wormhole-foundation/wormhole-connect/pull/2523

**Comment by agodlevska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
Closing the ticket. 

Attachments:
<img width="604" alt="Screenshot 2024-09-06 at 09 47 02" src="https://github.com/user-attachments/assets/5158cf7b-c9f2-4fce-acd1-b3b33d292217">
<img width="652" alt="Screenshot 2024-09-06 at 09 49 22" src="https://github.com/user-attachments/assets/99af3551-6211-45eb-9d5d-b835bb2fd681">
