### ISSUE TITLE
[QA] "Error: could not coalesce error" occurs when claiming asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2546]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZSIRWbaLlziqNWgApQSpbnIBrGPTB79SwRgAm5UQHdauTsIASjZpYgXv%2BgMYAFpjQiEicuIGQpJCUKIRefmDo0GgA5tFhAAwAHgBGAJwALAAcaAUAzCUATADsNgBsZTXcDQCsAIwVvDYdtSUFDUXsaKW1AGaQ1QBC7AUJSfqGJqHIuRMVBQDCbSUd3G0FbdNtFf5t%2FnkdBXnsWXkV4yU2vA3%2BlW2c1VtoWQuLEFwpDQ0Fo%2FkgGFgmTATAB%2Bl8cIgaBsNhitDMSFyvA6vC2Ww6kAakBsaGm1T23EgeRsBQ6nAqnTaWUq3A6XAp1Quf0UiIMAE8AA6QMIOcikFCBcgAG0g%2F0RAF8eQCALpKvyKxKWBFJIIhMLTMFyxYpdLQzE5BoFCltBrVDqWjpbabjensGzsNrVIo2Ti1DpZWoNPK1ArcLK8LJ1EpGpLLGDZHLVN5tSBZDqe73VTi2krh0rcarnLLjVrsSC1SCeziDDqOmN%2BIEgsEQqGkTy88yagHI1F0DG5PKQCrcCtZJq1LNZGytLbsWrcbgM6a1NCjaZXIpFBrsLYFK0NesA3CC4XIUXiyUyw%2FqtVJVVdpQau%2B3pQAdXbi21fl1WDCcmlIJoNe%2BgmhkbbIAAcsIuC8Gg5DsAAUoEJhuJAaAAGr8G40B8oEDh5AAChBvAQQ0r5pNMApuEYbjTMI%2FgNDYtSwIIADSwEGMY8bICUbTodM3AAIoAFq7sIwlGOMaACrg0yvgAVrA%2FAOLUACaeTCfJfKeq8KDybgBEAOLyc4gm8CggkcYCwKguCkLQrCvJft2KJohiUEwXBiHIZAqEYVhOF4YRxGkeRlHUbR9GMcxbFWZYx5CiKYoStKsovkkT5wveiIAI6UOQNDgUgEE5Y0AAaOW8CUgh5LQWyUIZJQALKCK%2Br6UARJTtBB6ENPJ4gdE1eRlZArE5OwRRuGxiEcZlSTOZYP6rOEkTRLE8TpZYoFmrk%2FgBjMOKcOMFQVESbqVgUEZFIMe5HUUkAlNw5QesUvClHFcbLbk0zFk9uZZFkJRdZW85dSinpDIUuzVHk1Q9CUtSw4UHQfTZzb2eBjmIgtSQ9m5CbsHkbRtNd1RMdcWTsB0eRoJwJS4nknBZJstZbEU9K%2BkUSYI1k%2FhxUsJ5JReqX82Ac2LNlizi94ONKEtYS8KQeQYECcRxdtRW5KcJ02OG%2FivEUoxMj0jSUiO27bl0tRtCOSZOqURQfVxX05D9JZoP9gPA20oOMTYENFFDNSw%2FDiMw7SqNNnZrYftjD6465fYEx0Hu8NMlqppGDREiUy60mg6bTGz1sdEU6bdEyRRtGgB6bbGgtnsll5pfHljS34ksZXXnaIvLyCSDJGAoBgtAba3EAawmKdFKyaAhsW1TDuMhS1BOgxvOni6MVsjS7MzFSQF0TsrAmbt%2FQDXtEj73Bg%2F7SaB0cwdwzYCNIxH3fWVHLYOePSiy94eMk5rByDcdgJRgxEzqFsN6hJahVH8LMUk05OhbGqF6bO1sGgBgqDYUWgIG5IHPClK8H9HykM7jeVu%2F8wB9yQNMNAtAW6IknsA7WOC9YGyNuGFEDQzaBnYJbCo1tbYNHtiUR2pDPqn1%2Bh7C%2BQMr6%2B3BvfIOMNn6v3DijSRaNo4%2Fw7NQ%2FQgD0TJ1TunAomckw5zzinQuxdOhl1OLwSu1da6%2FwFolRuwsSGuLFuQ7u7cIAUIgOLeUABKHk94SCUEYeIYkdAMBpFWKrSARASCfTquQaA4x4mIARE4Fw7har%2BByZqEwfIRTOFcG4Qp9ZaB8hQHkaU5T8luHrKkXA9ktjBF%2FMgA0fMXyfQAJI2GKTqLpy1enXkMf2RMyZUzpi9DYLMOY8yPULEyEs25yyVizDWOsL524YH8BksIgQ1ACnoAAeguQwxhuBaAsCOVgDI%2FgjDkAeeQFAFzHmgguUPU0tALkdCBhUIoFznAghJKQGwFy8mVJYAKaAaR6zfMMpAF55AhkimBAKIUNgAC0zg8CBGRdKMUYQADE3ReDDm4PWGwaK%2FlSjMECtU4tXy0AAqkEZlhSlhHZZyoCL5an1MacgV8rS0DtKhJ0vUyB%2FxSkAvWQZwye7fjGX%2BAVkzE5GJ4nxASIkxISSkjJOSillJqQ0lpHSDQ9IGWMqZcyll9kvkOcc5ApzcDnPgFcm5eB7nfOea895nzvkAr%2BRkAFDJAa1DBbgCFaAoUwo%2BaQZuogpTkDSPYcYlApRSlEEc9NpBRCkDSHkUQ1QL4ChyKICcOKMCiGXoGBoaB%2FC8TQPCxFAB%2BPogMmgDBJiSrAqL0WYo8cQphlh6X%2BEZWYBorK1SviJWtOI3L9C8rFUumIashV1IaVKPlEqpWQBld0laUQt1j28Mq1di11XIAiOe9aWrew6vNGfWRAN5Egxvn7AOKiQ4vzDsjesByjnLQ9V6n16I%2FXvKeWioNRyQ3kCwGG9AEaLlRoRrG%2BNibRQoBTalNNGas05rzQWsUxbS3lsrdW2tAp62Nuzi2ttHa0jdtqL2oGRwJGahRfBjFKrCFNxFi%2BKdM7EAsq8GyhNytVYoBvRAddSBXwyZVqQbdmphV7oPS%2BNpHS71IEVrJ9Tl74rO1HQtWhRm1MaYTi%2B6Z77PZfuvrfP9j9VGhzfpozUoG3VIAg5c650G7mwcRfx4NXzkM%2FPDXQDDTIsPgugJC6FeGCMyiI5mhtpH82kqLSWstFaAZVprdUOtDbgxMdbdXVj7HOP9p494PjI7BNEObnShl6AmUSZKPOrwr5yCD2HqPBTYAlP9cGyPUz%2BgtOiuU4e%2FTsqkAD3aUNqbnEVgWYfLQ5bQ9JvPvxsAxzcjvaKLvpDdzAH1HAedZqV14GzmBd9SFgN4XEORZQ78tDsXMMxsS8lpN%2BHU3psy9m3NOXC2UYKzRkrZXGPNqq%2B2hFbGe1dS4wOl8TXXmjqE54id%2BgxOdeZT1qTC6aaMJG2NsneOlAzf3WK%2Bb0qDP0MYUq8zKrLNM4YdTgx2qHMyKcydn9SjzvQ0u0B9%2BPmXVgZOQ971QXbn%2Bqi4Gt5b3Q2ff%2BXF6N2GksJpS8moHxGstg%2FI3lqjhWsjFbowxir8OWNI9q6j%2Brg7oDDqxy14TXjvAE7QF1sAkn9CZQ1PKAA3EAA%3D) with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001234 SOL from Solana (Phantom) to BSC (MetaMask)
2. Select Manual route
3. Click on "Claim" button

Actual result: Transaction fails. 

```
Error: could not coalesce error (error={ "message": "No matching key. keychain: 426b687e4e7bf8d4984fc11ddfd5c5b855d621a2b33be1874e964d8941ff48cc" }, payload={ "id": 5, "jsonrpc": "2.0", "method": "wallet_addEthereumChain", "params": [ { "blockExplorerUrls": [ "https://bscscan.com", "https://bscscan.com" ], "chainId": "0x38", "chainName": "BNB Smart Chain", "nativeCurrency": { "decimals": 18, "name": "BNB", "symbol": "BNB" }, "rpcUrls": [ "https://rpc.ankr.com/bsc" ] } ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (main-BUFOYwdP.js:235:68988)
    at Ya.getRpcError (main-BUFOYwdP.js:236:212926)
    at Ya.getRpcError (evm-CjWSIFBG.js:2:1700)
    at main-BUFOYwdP.js:236:215228
```
    
Expected result: Transaction proceeds without errors.

## Notes/ Attachments
Issue is reproducible when user clicks on "Claim" button several times. 

![image](https://github.com/user-attachments/assets/2b70f6e7-8efc-4c04-afdc-68cd27ba8f26)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending WETH (Base) from Solana (Phantom) to Base (MetaMask).

Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZQJgAsmgCeaaOKo0iEVm2i5cW6nQAUoPXtzkA1jHphLVvYIwATcqIDutXJ2EACUZmFwhnMKsAYwALTGhEJE5cGMhSSEoUQlDIsHRoNABzNMSABgAPACMATgAWAA40aoBmeoAmAHZ3ADZG9u5ugFYARmbed2GO%2Buru2vY0Bo6AM0g2gCF2auzcqxt7BOQK5ebqgGFB%2BuHuQerBtcHmqMGoyuHqyvZSyual%2BvdebpRFqDThtU5oUrbHYQXCkDS0KKQDCwEpgJjQqwRDEQNDudzpWiOJAVXjDXinU7DSDdSDuNBrNqXbiQSruarDTjNEaDUotbjDLhMtrPSG6bHWVQAB0giW85FIKBi5AANpAodiAL5i6EAXW1kS1ORcWNysXiiTWCPVO3yRVRxPK3WqTMG3Tawydw1OayWnPY7nYgzatXcnA6w1KHW6lQ61W4pV4pU69WtuT2MDK5TagMGkFKwyDIbanDd9QTDW4bSepSWA3YkA6kCDnBmwy9qcisPhiORqPR4pNGNx%2BLoRIqlUgzW4jdKvQ6xdK7gGp3YHW43C5aw6aAWa1etVq3XYp2qzu6HehuClMuQcoVStVF4N%2BtyeqNVkNr5fegA6iFoYOYRmlgiRyCqGhoE%2BVi2sUpCJAAcsIuC8Gg5DsAAUjE9iBJAaAAGr8IE0CqDE3iVAACvBvDwd0P6FGskqBLYgRrMIUTdO4HSwIIADSUHWHYGbIPUgx4Ws3AAIoAFonsIUm2EsaCSrgaw%2FgAVrA%2FDeB0ACalRSWpqhBgCKBqbg5EAOJqX4Em8CgEn8TCcLQAiSIonBaLvpEgE7MOBJEohyGoRhWGQDh%2BGEcRpEUVRNF0QxTEsWxHFcbxjkuFe0qyvKioqmq365J%2BGJvtiACOlDkDQHlIPBpU9AAGqVvD1IIlS0KclAWfUSiCD%2BP6UOR9RDPBeHdGp4jDEolT1ZAPHlOwtSBLxGH8UVuQ%2BdEcQgcgySpOkmTpTB9oVFEkbrGSnBLM0zQ0v6TbVImtQzKel21JA9TcE0gZ1LwDTpemBwOmsNafWWpSlPUQ1NmuQ14kGsw1BcbSVG04z1B0KM1MM%2F3Oa5vYef22IbZEfmjpm7CVIMgxPW0nFvKU7DDJUaCcPU5KVJwpQnG2py1JyYa1Nm6OlFE6W7Ne2X3nlYtgGtOwlTscthMTEDAYDvCkJUGCwgdBUuEd1UVA813uAmUQArUCw8uMPTMtOR5HqMHSDNO2beg0tT%2FYJgMVMDtZoGDENQ4MMMce48O1Ij7Qo2jGPI%2ByOPdm5fZecrqck3i%2Fnk8MAe8GsTp5km3Q0vUW7smgBZrLzzvDLUBZjDytSDGg5562mEu3jlD75enH5t3oCuFf3KtgGriSSMpGAoBgtBZP3EAG5mOe1PyaCxjWbRTksNQdPOMyAvnG4cacPQXFzzSQKMXv7Jmfug%2BDQc0iH3Cw%2BH2aR7c0eo%2B46OYwn89gC7C5Hs7l%2FwDl7i4UmhJMzvHYPUGMlNOinF%2BtSDorQogbHpEuEYpw2jBmLs7bokZmjuBljCDuSA7y5UfAAiAStIiD2fOnEeY9kBrDQLQHu2JF6HHKMbEhZsLZWwTHibodsozsEds0Z2rtuju3qJ7ABANb4gwDg%2FSGT9Q5w3flHZG39f7x2xko3GICU7iicBAqwUCxzzRzmzfO1RC7ZhLmXHOldq4jDrg8Xgjdm6t0sRKLKncpY0ICfQsIjCwjhLAJE2W%2BoNQAEoxRvhIJQTh4haR0AwIUA4OtIBEBIADdq5BoBLGyYgLEvh%2FBBDalECpRp7CqFlH4AIgRakdloKoFAlQVTNOqYEDsBRcC9lOFtQGlpRbfgBgASXcPU00YyLRWj1tYzM2Ynh5gLMGdwxZSzlg%2BlWHktYjwNibMWVs7Zvz0IwFEEpiQYhGElPQAA9M8jhnDcC0BYLcrAxQoi2HIN88gKBnk%2FJcs8qedpaDPOGJDZotRnl%2BA0HSUg7hnlVNaSwSU0BCgdjBRZSA%2FzyCzNlHCSU0p3AAFo%2FB4BiHilU8pEgAGIxi8CnNwDs7hCWQuVI4WF8T9Q%2FloOBAo8yXCNMSEKkVkFvydO6b05AP5BloGGSiUZ5pkBgWVBBDsMy5kWIWRqpAWqdUrMzmTYSolxLSVkvJRSylVIaS0rpfShljLdFMuZKyNk7IOSud%2BG5dzkAPNwE8%2BArz3l4C%2BWCv5AKgUgrBdCyFxRoVcghh0RFuBkVoFRei4FpBu6iGVOQQoXgliUGVMqUQtzi2kFEKQQolRRBtAfpKcooh5zkowKIbeUZuhoCiCJNAWKcUAH5JgQ16NMam9KsAEqJSS4J1CuEuC5VEHljhugCtCD%2BWlaQMgoDFVYCViq937TnkaOVPTlSSuVaqyA6rtpJBSPu3WRo9VHpcKw59e0D1PlWbwu%2BajwYaOhi%2FMOEddExx%2FnHLGHZrm3MBiGsNEbCRRqBb8wlcbbkJvIFgJN6AU3PLTejTN2bc1yhQAWvKRaS1lorVWmt8p62Nuba29tnbJTdt7cXAdQ6R2FHHR0SdkNbiKKNPirDxL9WUK7tLb8a6N2IH5aEOWP4c1ax1oeg14rIBNMVRp7WpA31hCvQqpASrvxDJGYs5AGtNPGYvWED9OmgK2aQPZozJmM4jmgYB1RgdQPP1fpBz%2BejY5%2FyMUaBDQakDIZeW8tDnyMM4qk%2FG0FeHwXJroMRnkpGkXQBRWiyj1HVS0dLT2hj1aGV1obU2lt4M20draF2ntMZeODubgJoTInp3iaApl%2BdALF2yZCSuqwin0C8uU%2FUbdVgfzkEntPWen6IAnos4t4Zy2nMuDMzexVd6bNGonltmeO3dje0XT5b9J2p5nf%2FeavzQMAvqODlot%2BCMwvQYMXB%2F1RpA1IceQlyNyWY1pZwxl%2FDELCM5ZIxmgrRW81UcLcWir5bK3VdrSx%2Br7HmutZ4%2F2zrw7sWCYnUNUTM7vySYXTJqh3dOXcqm3y2bqnBXM04atsA62fzs%2FG3oPbt6rMqqO0%2B9hnDdWXf1dd9zYu%2BdWMezYoDgW3vge0Z9pG33YP%2F2iwGxD9ygfhsSx86NmXY2Aoh4m6HULcvprI4VnNxX80o7o5VjHTHausYa6UJrnHuPtcJ%2FxknPXyd9dndAIb0nJbLoZ%2BupnM25txJABqAA3EAA%3D%3D%3D). 

An error appears after clicking on "Claim" button. Transaction finishes successfully, link to [Wormholescan](https://wormholescan.io/#/tx/wsAHs8HUJjCLB7gJ9y4ektpePbLTWWpa76iKWR3hmCGHtjZm8jPHtZngFNXgKph911UzHfdpf2b9whdhRFgheVC).

```
Error: could not coalesce error (error={ "code": -32603, "data": { "cause": null, "error": { "code": -32016, "message": "over rate limit" }, "id": 1086800123, "jsonrpc": "2.0" }, "message": "Non-200 status code: '429'" }, payload={ "id": 18, "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": [ "0x12af0e3", true ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (main-DyeDmw1W.js:235:68988)
    at Ya.getRpcError (main-DyeDmw1W.js:236:212926)
    at Ya.getRpcError (evm-Cx7nIM-U.js:2:1700)
    at main-DyeDmw1W.js:236:215228
```


![image](https://github.com/user-attachments/assets/b912a073-22ec-43cf-a531-70eed2f40c69)

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/0a16bf3ef2/. 
Issue reproducible when claiming transaction - 0.012 DAI from Optimism (Coinbase) to Arbitrum (Coinbase). 

Reopening the issue. 

Attachment:
<img width="1439" alt="Screenshot 2024-11-11 at 17 22 41" src="https://github.com/user-attachments/assets/ab61cbce-351e-4fe1-9435-dcbe2663f065">

**Comment by tsadovska** [comment]
Rechecked following scenarios on https://wormhole-connect-mainnet.netlify.app/ on Dec 9. Issue is no longer reproducible. 

* 0.001234 SOL transfer from Solana (Phantom) to BSC (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/5fw3JL7Ta26JQ7GpMoCYFWGPqZT8PczvYRFWbH6pNcKeeyNtXFirUJdxWSwPqByjQWuVs1gDJqEdMhnbtmvSqWFV).
* 0.012 DAI transfer from Optimism (MetaMask) to Arbitrum (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0x1c3b0a33a1cf8530b2daadd68239717c9248e8df2ce3a4cbfe225ba0a05647bf). 

Closing the ticket.

**Comment by fredrickj6288** [comment]
I’m having that problem. I’m looking for a solution!

**Comment by fredrickj6288** [comment]
Do not have a password to check on main net
