### ISSUE TITLE
[QA] Receiving amount displays as NaN on transaction screen

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2565]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.120 (Official Build) (x86_64). 

Steps:

1. Prepare to send 0.001 WMATIC from Base (MetaMask) to BSC (MetaMask)
2. Select Manual route
3. Click on "Review transaction" button

Expected result: The received amount should be correctly displayed as the actual amount (e.g., 0.001 WMATIC).

Actual result: The received amount is displayed as "NaN" on the transaction screen.

## Attachments/Notes

<img width="1440" alt="Screenshot 2024-09-11 at 10 01 51" src="https://github.com/user-attachments/assets/9cb2c310-715a-4b1a-88d0-d5fa5ad0137d">

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMgIF8Qg%3D) (Connect v2). 

Scenario checked: 0.0001 BNB transfer from BSC (MetaMask via WalletConnect) to Fantom (MetaMask via WalletConnect) with Manual route. 

Asset is received.
* Send from tx: [BscScan](https://testnet.bscscan.com/tx/0xa2a46c7c93092bd6a5f95e327c335e9e90c245d055615f3626a537b612091892)
* Send to tx: [FTMScan](https://testnet.ftmscan.com/tx/0x4989b47e921e155a30670c3686a26b9699101a19aeb767d5af92992d50006333)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xa2a46c7c93092bd6a5f95e327c335e9e90c245d055615f3626a537b612091892?network=TESTNET)

![Screenshot 2024-09-11 at 10 08 23](https://github.com/user-attachments/assets/8857de45-b99f-4c81-96c4-7467ccdbff4f)

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/0af992dedf/ (Connect v2) when sending 0.001 AVAX from Avalanche (MetaMask) to Fantom (MetaMask).

- Send from tx: [Avalanche](https://snowtrace.io/tx/0x9f09ebd8f863df2f85641616e73516963974938d32a95342703fd2eb454c00b3?chainid=43114)
- Send to tx: [Fantom](https://ftmscan.com/tx/0x858ebfc9fdba41740ca3b6f88c666782135a840c80420a87d1efb4037bab055c)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x9f09ebd8f863df2f85641616e73516963974938d32a95342703fd2eb454c00b3)

Attachment:
<img width="1434" alt="Screenshot 2024-09-12 at 09 59 53" src="https://github.com/user-attachments/assets/42153fbb-f260-4137-9912-e1c7756be50e">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/b1f3c5115d/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
The received amount correctly displayed as the actual amount.
Closing the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-09-13 at 09 56 33" src="https://github.com/user-attachments/assets/6408384c-8f80-471c-9dc8-93e8a4eb6eb1">
