### ISSUE TITLE
[QA] Increment/decrement artifact shows up in Amount input field

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2573]
## Describe the current behavior in detail

<img width="628" alt="Screenshot 2024-09-11 at 5 12 46 PM" src="https://github.com/user-attachments/assets/5aa94d52-13a0-4b12-8cf1-04fb2e76f761">

This seems to be only affecting Portal.

## What is the expected/desired behavior

The up/down arrows shouldn't appear in the Amount input field

**Comment by danielisaacgeslin** [comment]
this is most likely due to portal's preview not using connect's latest code

**Comment by sebastianscatularo** [comment]
this should be addressed at https://github.com/wormhole-foundation/wormhole-connect/pull/2627

**Comment by tsadovska** [comment]
Looks great on https://preview.portalbridge.com/b1f3c5115d/. 

![image](https://github.com/user-attachments/assets/e39d5e99-d2e8-4f3d-8d4a-e6d9fb70b7bb)

Closing the ticket.
