### ISSUE TITLE
[QA] Loading icon is not displayed 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2602]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64).

Steps:
1. Prepare to send 0.00001 FTM from Fantom (MetaMask) to Ethereum (MetaMask) 
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button
4. Verify that the loading icon is displayed while the user waits for the MetaMask window or the Transaction screen to open

Actual result: Loading icon is not displayed.
Expected result: Loading icon is displayed. 

## Notes/ Attachments

Actual result:
![Screenshot 2024-09-16 at 10 50 39](https://github.com/user-attachments/assets/ff53ca5f-1846-4ae7-9b23-0728fbf2b06f)

https://github.com/user-attachments/assets/b0ee8a34-cb44-453b-979f-e7e781c2211d

Expected result: 

https://github.com/user-attachments/assets/6c6d7a75-bd97-4586-bead-385859e52163

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b1f3c5115d/. 
Loading icon is not displayed.

Attachment:
<img width="527" alt="Screenshot 2024-09-16 at 11 36 43" src="https://github.com/user-attachments/assets/e6b2d7b1-a568-49c7-84ec-5671483d47b4">
