### ISSUE TITLE
[QA] Transaction fails with "Error: missing revert data" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2603]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask)
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button

Actual result: Transaction fails. 

```
Wormhole Connect: error completing transfer Error: missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0xb293f97f000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000020000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000040100010000000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x68dB2f05Aa2d77DEf981fd2be32661340c9222FB" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (pb-index-Cs8Ku0aW.js:273:19452)
    at getBuiltinCallException (pb-index-Cs8Ku0aW.js:274:107223)
    at Ju.getBuiltinCallException (pb-index-Cs8Ku0aW.js:274:108177)
    at Ys.getRpcError (pb-index-Cs8Ku0aW.js:274:211164)
    at Ys.getRpcError (evm-C7Q3nys6-CyNxXEFZ.js:7:1702)
    at pb-index-Cs8Ku0aW.js:274:215073
```

Expected result: Transaction proceeds without errors. 

## Notes/ Attachments

https://github.com/user-attachments/assets/8207a806-4659-4f8a-ab5c-18299232777c

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b1f3c5115d/, when sending 0.0001 tBTC from Ethereum (Phantom/MetaMask) to Optimism (Phantom/MetaMask). 

Error in console:
```
Wormhole Connect: error completing transfer Error: missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0xe4269fc400000000000000000000000018084fba666a33d37592fa2633fd49a74dd93a8800000000000000000000000000000000000000000000000000005af3107a400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bf5f3f65102ae745a48bd521d10bab5bf02a9ef4000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002c46111ad250000000000000000000000000000000000000000000000000000000000000f170000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000511e3424c41d82fc2ba67d8d35b09913b1e7da0c9e8557d1813fd96721a3fac9bb1f00000000000000000000000000000000000000000000000000000000000000016dfa43f824c3b8b61e715fe8bf447f2aba63e59ab537f186cf665152c2114c39000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe0100000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe0100000000000000000000000018084fba666a33d37592fa2633fd49a74dd93a88000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000001e000000000000000000000000018084fba666a33d37592fa2633fd49a74dd93a8800000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000000000000000000000000000000000000066ebfd480000000000000000000000000000000000000000000000000000000066ebfd4800000000000000000000000000000000000000000000000000000000000017f90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xd493066498aCe409059fDA4c1bCD2E73D8cffE01", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (pb-index-BwMC8vQL.js:269:19452)
    at getBuiltinCallException (pb-index-BwMC8vQL.js:270:107223)
    at Xu.getBuiltinCallException (pb-index-BwMC8vQL.js:270:108177)
    at Pi.getRpcError (pb-index-BwMC8vQL.js:270:211164)
    at Pi.getRpcError (evm-DQ0xlIWU-C9n4R-bW.js:7:2076)
    at pb-index-BwMC8vQL.js:270:215073
``` 

Attachment:
<img width="1440" alt="Screenshot 2024-09-19 at 12 09 37" src="https://github.com/user-attachments/assets/3e8f4113-1f55-435d-8486-1e223d1fab33">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b1f3c5115d/ when sending 0.0001 tBTC from Ethereum (MetaMask) to Arbitrum (MetaMask).  

![image](https://github.com/user-attachments/assets/37560fd5-9ceb-4cb0-93fe-bd08aef0eb7f)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/712d941311/ when sending 0.57 USDT from Polygon (Rabby) to Optimism (Rabby).
Note: Transactions in the same scenario are completed successfully when using the Coinbase wallet.

Attachment:
<img width="1440" alt="Screenshot 2024-09-26 at 10 49 36" src="https://github.com/user-attachments/assets/f74aac8d-f549-447b-be02-3c7ebabb14ef">

**Comment by Wesleyleung** [comment]
@agodlevska when performing the latest example with 0.57 USDT, did you have a decent amount of gas? Maybe simulation in Rabby found gas to be insufficient.

**Comment by agodlevska** [comment]
@Wesleyleung Yes, it was enough, I have the same account in Rabby and Coinbase. As I mentioned above, transaction with the same scenario was completed successfully without any errors when using the Coinbase wallet.

**Comment by Wesleyleung** [comment]
@agodlevska what route was attempted? The details are blank on the card in your screenshot (which seems like another issue). When I try to enter the same, I need at least 3 USDT

<img width="448" alt="Screenshot 2024-09-26 at 10 41 24 AM" src="https://github.com/user-attachments/assets/dc936168-4be9-4bff-a591-348a8fc551c2">

**Comment by agodlevska** [comment]
@Wesleyleung 0.57 USDT from Polygon (Rabby) to Optimism (Rabby) via MayanRouteSWIFT route. Sometimes the amount for the transaction can be less than what is indicated in the message (probably when multiple routes are available), for me it worked to send 0.57. Now the minimum amount for me is 0.63 USDT. 

Attachment:
<img width="469" alt="Screenshot 2024-09-26 at 17 51 29" src="https://github.com/user-attachments/assets/54f9e8f8-d43f-41a0-aa31-02eeb0cf9597">

**Comment by sebastianscatularo** [comment]
simulation was fine on my side, a network gas cost spike, maybe? 

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/9b5a6ab2-535e-4b5a-9114-bac78b25c33d">

**Comment by agodlevska** [comment]
@Wesleyleung @sebastianscatularo Attempted to reproduce the reported issue, but transaction completed successfully. The issue did not reoccur, so error may have been caused by a gas spike at the time of the initial transaction but the Rabby wallet did not indicate that there was insufficient gas for the transaction.

- Link to [Mayan](https://explorer.mayan.finance/swap/0x54161222c9943c9dbd841c61329a3041d8458cff678341011d040e0e19084874) explorer

Attachment:

https://github.com/user-attachments/assets/0fc41adf-c982-4e5c-966d-83308f9577ca

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ac2a9a0933/ when sending 0.9 USDT from Ethereum (Binance wallet) to BSC (Binance wallet) with Automatic route. Notification to confirm transaction is not displayed in Binance app. 

```
Wormhole Connect: error completing transfer Error: missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0x9a4896fe0400090000006400006400000000000000000000000000000000000000000000000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec700000000000000000000000055d398326f99059ff775485246999027b3197955000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb61370000000000000000000000000f352dc165783538a26e38a536e76dcef227d90f200000000000000000000000000000000000000000000000000000000000dbba000000000000000000000000000000000000000000000000000000000000db65a0000000000000000000000000000000000000000000000000c702d0828ecd7f0000000000000000000000000000000000000000000000000035b36607641a41e", "from": "0xc911CBcdd18B2019A884db5A2Bc7c3a8bfb61370", "to": "0x4db1683d60e0a933A9A477a19FA32F472bB9d06e" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.3)
    at makeError (pb-index-DMUGiEOY.js:271:19062)
    at getBuiltinCallException (pb-index-DMUGiEOY.js:272:107223)
    at Ju.getBuiltinCallException (pb-index-DMUGiEOY.js:272:108177)
    at Go.getRpcError (pb-index-DMUGiEOY.js:272:211289)
    at Go.getRpcError (evm-DMvzqxcS-CLx0ixND.js:7:2047)
    at pb-index-DMUGiEOY.js:272:215198
```


![image](https://github.com/user-attachments/assets/7c387e31-7695-4afb-a3c8-657288405a1b)

**Comment by tsadovska** [comment]
Rechecked following transactions on https://wormhole-connect-mainnet.netlify.app/ on Dec 9. All transfers completed successfully. 
* USDC.e transfer from Fantom (MetaMask) to Ethereum (MetaMask) with NTT Automatic route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x5ba3486e0ee80a139427b3019fa1dd4688b8af3a457b98e31470b0d921b0c127).
* 1.3 USDT from Polygon (Rabby) to Optimism (Rabby) with Mayan Swift route. Link to [Mayan Explorer](https://explorer.mayan.finance/swap/0x374ced69b30f8a4afa272e0c1680f336df61449091de13de8908c5730db757d2).
* 0.5 USDT from Ethereum (Binance) to BSC (Binance) with Automatic route. Link to [Wormholescan](https://wormholescan.io/#/tx/0x732601ada8878169c4ffd781fb158e42a472bd599aeb6293a6c080191e5395b7). 

Closing the ticket.
