### ISSUE TITLE
[QA] Balance is not loading for Klaytn network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2604]
## Describe the current behavior in detail

Checked on https://preview.portalbridge.com/b1f3c5115d/ and https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.138 (Official Build) (x86_64).

Steps:

1. Select Klaytn network (MetaMask wallet was automatically connected)
2. Check tokens balances

Actual Result: Balance for Klaytn is not loading.
```
Failed to get token balances Error: could not coalesce error (error={ "code": -32062, "message": "Batch size too large" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (pb-index-Cs8Ku0aW.js:273:19452)
    at To.getRpcError (pb-index-Cs8Ku0aW.js:274:212791)
    at pb-index-Cs8Ku0aW.js:274:215073
``` 

Expected result: Balance is loading for all tokens.

## Attachment/Notes

<img width="1440" alt="Screenshot 2024-09-16 at 12 13 44" src="https://github.com/user-attachments/assets/64aea154-eb00-49ef-8913-b0bf8081b355">

**Comment by Wesleyleung** [comment]
Looks like RPC issue for Klaytn. May be fine once in production

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/63186ea4-c996-4c40-a64f-e53911388546)

**Comment by tsadovska** [comment]
Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2724.
