### ISSUE TITLE
[QA] Incorrect POL/WPOL token display on Wormholescan 

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2619]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ and https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.138 (Official Build) (x86_64).

Steps:

1. Prepare to send 5 POL from Polygon (Coinbasw) to Solana (Backpack)
2. Select "Automatic route" option
3. Click on "Review transaction" button
4. Monitor the transaction on [Wormholescan](https://wormholescan.io/#/tx/0x040faef6ea189cfc7ab73b763bfea65d719a4b1215c1e0f99e514654bad712c4)
5. Observe that the token is displayed as WMATIC instead of the current name POL/WPOL

Expected Result: Wormholescan should display the token as POL/WPOL during and after the transaction.

Actual Result: Wormholescan displays the outdated token name WMATIC for POL/WPOL transactions.

## Attachments/Notes

<img width="1440" alt="Screenshot 2024-09-17 at 15 46 09" src="https://github.com/user-attachments/assets/a8cc839f-1870-401b-875f-c4906e682b77">
<img width="1440" alt="Screenshot 2024-09-17 at 15 46 17" src="https://github.com/user-attachments/assets/637e2332-3a98-4b3e-8b28-8271d42c69be">

**Comment by yuli-ferna** [comment]
I have already reported the issue to the wormscan team.
