### ISSUE TITLE
[QA] Balance is not loading after switching to Phantom 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2620]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQHUAEoZPnL1yEYDCKgAqOzFqwKQejYAkjIqALogAL5AA%3D%3D%3D) (Connect v2) and https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64).

Steps:
1. Enable "Always ask" option in "Default App Wallet" settings in Phantom app
2. Refresh the page https://wormhole-connect-mainnet.netlify.app/
3. Prepare to send some AVAX from Avalanche (MetaMask) to Base (MetaMask), in my case 1.737305
4. Change MetaMask in "From" section to Phantom wallet
5. Check if balance is displayed in "Amount" section

Actual result: Balance in "Amount" section is not displayed. User can click on "Review transaction" button and then on "Confirm transaction" button. "Unsupported network" notification is displayed after clicking on "Confirm transaction" button. 

Expected result: Balance is displayed in "Amount" section. Message "Amount cannot exceed balance" is displayed if user doesn't have enough asset. 

## Notes/ Attachments

![Screenshot 2024-09-17 at 17 32 01](https://github.com/user-attachments/assets/563832ec-8f4e-4e19-bbe4-a5998c207dba)

https://github.com/user-attachments/assets/64707b5a-2280-4a43-afc8-c9462d5a3623

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://preview.portalbridge.com/b1f3c5115d/. 
Balance is displayed in "Amount" section. Message "Amount cannot exceed balance" is displayed if user doesn't have enough asset. 

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/c8605941-94ed-453e-af61-bc9a2dd1bb59

**Comment by tsadovska** [comment]
Issue occurred again with the [scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2620#issue-2531332937) mentioned above.


![Screenshot 2024-09-18 at 20 14 34](https://github.com/user-attachments/assets/c86fb895-2f8f-43ba-9abf-bd11a49726bb)
