### ISSUE TITLE
[QA] Amount on "Transaction history" page should have more decimals

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2631]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64). 

Steps:
1. Send 0.0001 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask)
2. Open "Transaction history" page
3. Check the amount

Current Result: The sent amount is displayed as 0, and the received amount in the destination chain is not shown.
Expected Result: Both the sending and receiving amounts should be displayed. 

## Notes/ Attachments
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x48e2c6cd72a08c7f10835ba0cc328864f41c16a57613c1310569028aa0db985c)
* Link to [Etherscan](https://etherscan.io/tx/0xaf584ddd42547d34fbba404d158048bc18e1893450f97824be59a16f83aafec0)

![image](https://github.com/user-attachments/assets/268dbb51-cde3-45cf-be76-90ec48529770)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ac2a9a0933/ when sending 0.0001 wstETH from BSC (MetaMask) to Ethereum (MetaMask) with "NTT: Wormhole + Axelar" route. 


![Screenshot 2024-11-05 at 13 17 08](https://github.com/user-attachments/assets/2c9aabdc-d075-4417-b8de-5600fbbd85fb)

**Comment by agodlevska** [comment]
Issue is no reproducible on https://portalbridge.com/, when sending 0.00001 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask). Both the sending and receiving amounts are displayed on transaction history page.

Closing the ticket. 

Attachment:
<img width="439" alt="Screenshot 2024-12-11 at 13 50 47" src="https://github.com/user-attachments/assets/189cfa37-d475-40b8-9f9d-41047c15e042">

**Comment by tsadovska** [comment]
Scenarios mentioned in the ticket completed successfully on [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/). Correct sending amount is displayed on "Transaction history" screen. 

![Image](https://github.com/user-attachments/assets/63a34761-7ae4-4a01-b278-57939f0d7dc0)

![Image](https://github.com/user-attachments/assets/f890bb45-d632-4259-b718-1d322fa2b164)

Created new ticket for remaining issues: https://github.com/wormhole-foundation/wormhole-connect/issues/3187
