### ISSUE TITLE
[QA] Infinite loading loop instead of available routes after inactivity

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2634]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ and https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.6.1 and Google Chrome Version 128.0.6613.138 (Official Build) (x86_64).

Steps:

1. Prepare to send AVAX from Avalanche (MetaMask) to BSC (MetaMask)
2. Leave the transaction page and navigate to a different page or tab
3. Wait for about 10-15 minutes
4. Return to the transaction page

Expected Result: The transaction page should remain functional, displaying all routes and allowing user interactions.

Actual Result: All routes disappear, the page displays an infinite loading loop.

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-09-18 at 13 18 26" src="https://github.com/user-attachments/assets/ae5713a6-76a6-49ab-9d8f-4a1557ef20df">

**Comment by tsadovska** [comment]
Error is shown in Console:
`POST https://and76cjzpa.execute-api.us-east-2.amazonaws.com/ethereum/ net::ERR_SOCKET_NOT_CONNECTED`


![image](https://github.com/user-attachments/assets/8702957c-1d84-4f19-8f9d-90282202bdcb)

**Comment by Wesleyleung** [comment]
@kev1n-peters is currently investigating

**Comment by Wesleyleung** [comment]
Should be fixed with https://github.com/wormhole-foundation/wormhole-connect/pull/2643

**Comment by agodlevska** [comment]
Re-checked on https://preview.portalbridge.com/b1f3c5115d/ and https://wormhole-connect-mainnet.netlify.app/. 
Issue is no longer reproducible, transaction page remains functional, displaying all routes. 

Closing the ticket.
