### ISSUE TITLE
[QA] Two identical messages appeared after changing network to BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2638]
## Describe the current behavior in detail
Checked on  https://wormhole-connect-mainnet.netlify.app/ and https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64).

Steps:
1. Select Ethereum network and ETH token in "From" section (Backpack wallet was auto-connected)
2. Select Solana network and SOL token in "To" section (Backpack wallet was auto-connected)
3. Change destination network to BSC network
4. Check if SOL token stays selected

Actual result: SOL token stays selected. Two identical warning messages appeared. 
Expected result: SOL is changed to WSOL or token is no longer selected.

## Notes/ Attachments

![Screenshot 2024-09-18 at 18 27 18](https://github.com/user-attachments/assets/a788c258-91bd-427b-9772-79e57ef4a621)

https://github.com/user-attachments/assets/03462301-c0fe-4252-ac1b-3f9c842fff47

**Comment by tsadovska** [comment]
Issue is also reproducible when sending tBTC token. Checked on https://preview.portalbridge.com/b1f3c5115d/. 

![Screenshot 2024-09-19 at 10 55 50](https://github.com/user-attachments/assets/0619f312-0694-4f96-918d-b7103df72996)

**Comment by Wesleyleung** [comment]
@nikarm22 this issue is still reproducible for me if you specifically try the switching from SOL to BSC scenario QA outlined.

I think what may be happening is there is an unrelated issue where the SOL that gets selected in this manner is not the correct SOL (Wormholed-wrapped asset vs native) and then this error is able to be surfaced again.

**Comment by tsadovska** [comment]
Two identical messages also appear when swapping SUI (Sui network, Sui wallet) to BNB (BSC, MetaMask). 
Checked on https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/d9a17b1f-09f7-42b9-bbb5-b5fa54fe0453)

**Comment by Wesleyleung** [comment]
Simplifying this ticket to be only about the double error message. Moving the token selection portion to another ticket here: https://github.com/wormhole-foundation/wormhole-connect/issues/2697
