### ISSUE TITLE
[QA] Warning "No routes found" is displayed when "To" section is empty

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2640]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64).

Steps:
1. Select Solana network and SOL token in "From" section
2. Connect Torus wallet
3. Click on "max"

Actual result: Warning "No routes found for this transaction." is displayed.
Expected result: Warning "No routes found for this transaction." is not displayed. 
 
## Notes/ Attachments

![Screenshot 2024-09-18 at 18 46 46](https://github.com/user-attachments/assets/e168e577-0283-4e7b-be84-bf628679893f)

**Comment by mliu-xlabs** [comment]
also the decimal is inconsistent. in the selection it is , and under max balance it’s .
