### ISSUE TITLE
[QA] Sometimes MetaMask wallet remains connected after changing Ethereum network to Solana and it causes blank screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2644]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64).

Steps:
1. Select Ethereum as source chain (MetaMask wallet was auto-connected)
2. Change Ethereum network to Solana 
3. Click on SOL asset

Actual result: MetaMask wallet remains connected when Solana wallet is selected. 
Expected result: MetaMask wallet is no longer connected. 

## Notes/ Attachments
Error occurs each milliseconds after user clicks on SOL option.

![image](https://github.com/user-attachments/assets/4e43f50a-ee24-4989-9244-ee4a09ea1c8d)

After a minute blank screen is displayed. 

![Screenshot 2024-09-18 at 19 28 21](https://github.com/user-attachments/assets/a4ad6344-dfbf-4163-bfdb-76132720926e)

https://github.com/user-attachments/assets/db198cc2-4205-4034-b11d-dc6a03b16ff5

**Comment by kev1n-peters** [comment]
Should be fixed by https://github.com/wormhole-foundation/wormhole-connect/pull/2643

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KARATg9grgLgUwM5gFwAIDaA6XARAUQDEBBAVQBkAVAfQCUB5MqggZQBp0BZAQwE8eAOzqxEnXgOGiEXAMJUACuP5CR8BKwDqASSJUAuiAC%2BQA) and https://portalbridge.com/, wallet correctly switches from MetaMask to Phantom when user changes network from an EVM network to Solana.


https://github.com/user-attachments/assets/632865f0-9e3b-4dbe-9d40-b384649fc0c5
