### ISSUE TITLE
[QA] Infinite loading and error 429 appears after changing the wallet 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2645]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 129.0.6668.59 (Official Build) (arm64).

Steps:
1. Prepare to send 0.030264 SOL from Solana (Torus) to Polygon (MetaMask)
2. Change Torus wallet to Phantom 

Actual result: Infinite loading and error 429 appears.
Expected result: Wallet is successfully changes. Routes are displayed. 

## Notes/ Attachments

https://github.com/user-attachments/assets/7816b8f1-88e8-41ca-ab18-10a3ef1b41d5

**Comment by kev1n-peters** [comment]
Fixed by https://github.com/wormhole-foundation/wormhole-connect/pull/2643
