### ISSUE TITLE
[QA] Transaction details are not split into 2 lines on "Transaction history" page 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2648]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/.

Steps:
1. Select any network and connect a wallet
2. Open "Transaction history" page 
3. Observe how transaction ID and date are displayed

Actual result: Transaction details are not split into 2 lines, margin is missing.  
Expected result: Transaction details are split into 2 lines.  

## Notes/ Attachments

![Screenshot 2024-09-18 at 21 17 04](https://github.com/user-attachments/assets/b65de99f-66c1-4f7a-84ee-a4ffb557e50d)

**Comment by Wesleyleung** [comment]
Please confirm whether this has been fixed?

**Comment by tsadovska** [comment]
@Wesleyleung Yes, issue is fixed. It is not reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 

Closing the ticket.
