### ISSUE TITLE
[Bug] Mayan MCTP instruction error, cannot initiate transfer

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2652]
## Steps to reproduce

1. Input the below fields
<img width="568" alt="Screenshot 2024-09-19 at 11 59 10 AM" src="https://github.com/user-attachments/assets/7f930ea9-f7f4-4a87-8416-d1eef7a894b1">

2. Attempt to sign wallet on the confirmation screen. See error below
<img width="540" alt="Screenshot 2024-09-19 at 11 59 01 AM" src="https://github.com/user-attachments/assets/83a17a3f-3ea1-45a1-9fad-1bfb8df43bfb">

## Experienced behavior
Console errors

<img width="842" alt="Screenshot 2024-09-19 at 11 58 42 AM" src="https://github.com/user-attachments/assets/43bcd6c4-e7dd-44b2-a367-49b79be7fd28">
<img width="848" alt="Screenshot 2024-09-19 at 11 58 49 AM" src="https://github.com/user-attachments/assets/6f31a476-f09b-449e-adff-e45e69c04c9f">

**Comment by tsadovska** [comment]
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2655 [QA] Mayan Swift instruction error, cannot initiate transfer

**Comment by artursapek** [comment]
fixed with https://github.com/wormhole-foundation/wormhole-connect/commit/3677c07149cf1fcf21d0d9a01eb05762d3afdf4d
