### ISSUE TITLE
[QA] Transaction details are not loading in Nightly wallet notification

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2660]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/.

Steps:
1. Prepare to send 1 USDC from Base (Nightly) to Arbitrum (Nightly)
2. Click on "Review transaction" button
3. Click on "Confirm transaction" button
4. Check if transaction details are displayed in Nightly wallet notification

Actual result: Transaction details are not loading in Nightly wallet notification. 
Expected result: Transaction details are displayed. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/ada76930-e8db-4cda-8d29-6fc4cefaac0e)

https://github.com/user-attachments/assets/01e00a08-73a3-4b12-aab6-200f5c924dca

**Comment by emreboga** [comment]
Isn't this something wrong with the Nightly wallet? Or an issue with our SDK?

Cc: @artursapek @kev1n-peters

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/169ff3e1-c168-47a7-907c-26284805ec06)
