### ISSUE TITLE
[QA] Solana wallet/Network is showed as zeros (0X00...) in Etherscan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#267]
Preconditions:
Phantom Wallet is connected at From section
MetaMask Wallet is connected at To section

Environment:
MacBook Pro, macOS Ventura 13.0.1, Firefox version 109.0.1 (64-bit)

Steps:
1. Prepare to send 0.212 SOL from Solana to BSC
2. Click "Approve and proceed with transaction"
3. Click Claim when option given
4. When transaction is finished click on Etherscan link
5. Observe the sent from wallet address

Actual result: Solana address is shown as 0x000...

Expected result: Correct Solana address is shown in the TX scan.

Attachment:
<img width="1096" alt="Screenshot 2023-03-27 at 11 45 32" src="https://user-images.githubusercontent.com/91047061/227890460-db97cfc8-f804-4d7b-9aae-eb97f9e367ec.png">

<img width="1067" alt="Screenshot 2023-03-27 at 11 45 24" src="https://user-images.githubusercontent.com/91047061/227890471-11e18ae9-7822-4ae4-ac19-f1240cc06203.png">

**Comment by anondev2323** [comment]
That just means it's a minted token. Not an error, so going to close
