### ISSUE TITLE
[QA] Token list is incomplete when wallet is not connected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2674]
## Describe the current behavior in detail
Checked on https://portalbridge.com/:
* Portal Bridge: v0.2.15-191783896a
* Wormhole Connect: v^1.0.0-beta.1-development

Steps:
1. Select Arbitrum network in "From" section (Wallet was not connected)
2. Check if WAVAX or WFTM token is displayed in the list

Actual result: Tokens are not displayed in the list until wallet is connected. 
Expected result: Tokens are displayed in the list when wallet is not connected. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/55b1d11e-6929-4cec-83e7-9e48428fdd21)

![image](https://github.com/user-attachments/assets/8b890129-8512-4268-a147-94a8bf4cfb71)

**Comment by emreboga** [comment]
AFAIK we should display all tokens supported when no wallet is connected; and the ones with a balance when a wallet is connected. I'll have a fix for this.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/712d941311/. 


![image](https://github.com/user-attachments/assets/edc5728a-c4de-49df-8df9-7e48780029bd)


![image](https://github.com/user-attachments/assets/66cd29aa-c190-4a62-85e4-0493142c1489)
