### ISSUE TITLE
[QA] "Transaction history" page is not loading

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2677]
## Describe the current behavior in detail
Checked on https://portalbridge.com/:
* Portal Bridge: v0.2.15-191783896a
* Wormhole Connect: v^1.0.0-beta.1-development

Steps:
1. Select Sui network and connect Sui wallet in "From" section
2. Click on "Transaction history" icon

Actual result: Loading does not complete. 
Expected result: Transaction history is displayed.  
 
## Notes/ Attachments
Issue is reproducible with:
* Sui network and Sui wallet
* Aptos network and Spika wallet
* BNB network and Binance wallet

```
Failed to get token balances Vr: Invalid array length, expecting 32
    at gi.request (https://portalbridge.com/assets/sui-Cyoug3Go-_9jJqC8L.js:11:14154)
    at async Os.getBalance (https://portalbridge.com/assets/sui-Cyoug3Go-_9jJqC8L.js:11:43003)
    at async he.getBalance (https://portalbridge.com/assets/sui-Cyoug3Go-_9jJqC8L.js:11:54634)
    at async https://portalbridge.com/assets/sui-Cyoug3Go-_9jJqC8L.js:11:54786
    at async Promise.all (index 1)
    at async he.getBalances (https://portalbridge.com/assets/sui-Cyoug3Go-_9jJqC8L.js:11:54744)
    at async https://portalbridge.com/pb-index-Bk8S0RNv.js:522:12560
```

https://github.com/user-attachments/assets/3861c839-f33a-4371-b2f3-835367aafeb7

**Comment by pinpolhoxx** [comment]
maybe this will help
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by emreboga** [comment]
The problem seems like an unexpected error from Mayan API:
```
{"code":"INVALID_ADDRESS","msg":"Invalid address!"}
```

I'll first handle this error so the page will fail gracefully and then reach out to Mayan folks to fix this on their end.
