### ISSUE TITLE
[QA] Cannot resume transaction - USDC, Manual route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2679]
## Describe the current behavior in detail
Checked on https://portalbridge.com/:
* Portal Bridge: v0.2.15-191783896a
* Wormhole Connect: v^1.0.0-beta.1-development

Steps:
1. Send 0.00008 USDC from BSC (MetaMask) to Ethereum (MetaMask) with Manual route
2. Resume the transfer

Actual result: Transfer is not found. Loading does not complete.
Expected result: Transaction is successfully resumed.

## Notes/ Attachments
Link to [Wormholescan](https://wormholescan.io/#/tx/0x3c89ce969f65f15e8b40c2538a978054e1e8bc88a556758c55c610b4aa90d814).

```
Uncaught (in promise) Error: when deserializing item 'mintRecipient': chunk is shorter than expected: 1048 < 1060
    at updateOffset (pb-index-Bk8S0RNv.js:276:9987)
    at deserializeLayoutItem (pb-index-Bk8S0RNv.js:276:11825)
    at internalDeserializeLayout (pb-index-Bk8S0RNv.js:276:10219)
    at deserializeLayout (pb-index-Bk8S0RNv.js:276:9683)
    at pb-index-Bk8S0RNv.js:276:145798
    at deserializePayload (pb-index-Bk8S0RNv.js:276:146041)
    at deserialize$1 (pb-index-Bk8S0RNv.js:276:145436)
    at getVaa (pb-index-Bk8S0RNv.js:281:20216)
```

![image](https://github.com/user-attachments/assets/9479f01a-23ba-4edb-af06-dffc2593b042)

**Comment by kev1n-peters** [comment]
Issue is in the SDK. This is the actual error I'm getting:
```
Error: scaleAmount({"amount":"80","decimals":8}, 6) would result in altered amount. Use truncateAmount first if you intended to truncate it.
    at Object.scale (http://localhost:5173/node_modules/.vite/deps/@wormhole-foundation_sdk-base.js?v=8ef798bb:3338:9)
    at TokenTransfer.fromIdentifier (http://localhost:5173/@fs/Users/kevin/repos/wormhole-sdk-ts/connect/dist/esm/protocols/tokenBridge/tokenTransfer.js?t=1726857176087:76:37)
    at async TokenTransfer.fromTransaction (http://localhost:5173/@fs/Users/kevin/repos/wormhole-sdk-ts/connect/dist/esm/protocols/tokenBridge/tokenTransfer.js?t=1726857176087:100:20)
    at async TokenTransfer.from (http://localhost:5173/@fs/Users/kevin/repos/wormhole-sdk-ts/connect/dist/esm/protocols/tokenBridge/tokenTransfer.js?t=1726857176087:50:18)
    at async TokenBridgeRoute.resume (http://localhost:5173/@fs/Users/kevin/repos/wormhole-sdk-ts/connect/dist/esm/routes/tokenBridge/manual.js?t=1726857176087:85:22)
    ```

**Comment by kev1n-peters** [comment]
This fixes the scaleAmount issue mentioned above: https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/700

**Comment by emreboga** [comment]
Hi @tsadovska, I'm blocked to reproduce this issue as the manual route is not showing up at all. The automatic routes also returns an error about the amount being too low (Mayan as asking for 45 USDC the least). Can you reproduce this issue with a different source/dest configuration?

<img width="527" alt="Screenshot 2024-09-23 at 11 52 56 AM" src="https://github.com/user-attachments/assets/0091de11-ee05-4dba-8138-ed036e07e4fc">

**Comment by tsadovska** [comment]
@emreboga Issue is also reproducible with following scenario:
1. Select Base network and [USDC](https://basescan.org/address/0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913) (0x83...2913) token in "From" section (in my case, MetaMask wallet was auto-connected)
2. Select Arbitrum network and [USDC](https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831) (0xaf...5831) token in "To" section (in my case, MetaMask wallet was also auto-connected)
3. Enter the amount 0.0001 and continue the transfer

Cannot resume the transaction: https://wormholescan.io/#/tx/0xb036260eeb31db2e96b5b6786ef63c28e8fb096aa85b4aabd4e20e987141f7e9
 

https://github.com/user-attachments/assets/766af77e-4d79-48fb-934d-922e6f8aaf8e

![image](https://github.com/user-attachments/assets/c2f9cecc-2d67-44f9-a1e5-4e43cd9c069a)

**Comment by kev1n-peters** [comment]
> @emreboga Issue is also reproducible with following scenario:
> 
> 1. Select Base network and [USDC](https://basescan.org/address/0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913) (0x83...2913) token in "From" section (in my case, MetaMask wallet was auto-connected)
> 2. Select Arbitrum network and [USDC](https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831) (0xaf...5831) token in "To" section (in my case, MetaMask wallet was also auto-connected)
> 3. Enter the amount 0.0001 and continue the transfer
> 
> Cannot resume the transaction: https://wormholescan.io/#/tx/0xb036260eeb31db2e96b5b6786ef63c28e8fb096aa85b4aabd4e20e987141f7e9
> 
>  Screen.Recording.2024-09-23.at.15.39.44.mov 
> ![image](https://private-user-images.githubusercontent.com/10746654/369875758-c2f9cecc-2d67-44f9-a1e5-4e43cd9c069a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDU5MjgsIm5iZiI6MTcyNzEwNTYyOCwicGF0aCI6Ii8xMDc0NjY1NC8zNjk4NzU3NTgtYzJmOWNlY2MtMmQ2Ny00NGY5LWExZTUtNGU0M2NkOWMwNjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MzM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYzQxZjQ3OTcyMWE1YmFjNjhhZWU3ZWZlNjRiOTFhZTMwN2NhNWE0ZWJiZDFiN2Q3ZGU2MjliMDI1NGIwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eJE84HtLURye_oobVtIifzch_DMVLGuQnanojzwK1wE)

This is a different scenario (not a bug) where the transfer cannot be resumed until the attestation message has been produced.

**Comment by tsadovska** [comment]
Issue is not reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYgC%2BQA).

1. Scenario: 0.0008 USDC transfer from BSC (MetaMask) to Ethereum (MetaMask) 
Transfer can be successfully resumed: 0x71c7af6995635a7a274bf16c6d02ecd3511b4e7c1fa0db5101f1a5c5a4fc41cc (BSC).  Link to [Wormholescan](https://wormholescan.io/#/tx/0x71c7af6995635a7a274bf16c6d02ecd3511b4e7c1fa0db5101f1a5c5a4fc41cc).

2. Scenario: 0.001 USDC transfer from Ethereum (MetaMask) to Solana (Phantom). Transfer can be successfully resumed: 0x120cc5e38a39a59de8401908ca5bd7a45a31bf824b8ff53e0d6d578ba06ed15a (Ethereum). Link to [Wormholescan](https://wormholescan.io/#/tx/0x120cc5e38a39a59de8401908ca5bd7a45a31bf824b8ff53e0d6d578ba06ed15a).

Closing the ticket.
