### ISSUE TITLE
[QA] css styles are not loading for some pages

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2682]
## Describe the current behavior in detail
css styles are not loading for:
* "routes" link: https://wormhole.com/docs/build/applications/connect/routes
* "configure" link: https://wormhole.com/docs/build/applications/connect/configuration
* "ability to drop off some gas" link: https://wormhole.com/docs/build/applications/connect/features
* "features" link: https://wormhole.com/docs/build/applications/connect/features

## Notes/ Attachments

![Screenshot 2024-09-20 at 15 36 46](https://github.com/user-attachments/assets/a5fbd47c-dfbe-4225-b6da-a92ef2796d89)

![image](https://github.com/user-attachments/assets/aefbdd7d-8608-43a0-a584-7d3581c66ff6)

**Comment by eshaben** [comment]
@tsadovska Hi! Do you have reproduction steps?

**Comment by tsadovska** [comment]
Pages now are displayed correctly.

![image](https://github.com/user-attachments/assets/f8232971-4451-4ecf-bdc1-257a49b900ca)

Closing the ticket.
