### ISSUE TITLE
[QA] ETA is not calculated when sending asset from Mantle

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2683]
## Describe the current behavior in detail
Checked on https://portalbridge.com/:
- Portal Bridge: v0.2.15-191783896a
- Wormhole Connect: v^1.0.0-beta.1-development

Steps:
1. Initiate a transfer: 0.0001 WBNB from Mantle (MetaMask) to Optimism (MetaMask)
2. Check if ETA is calculated

Actual result: ETA is not calculated. Loading does not finish. 
Expected result: ETA is calculated.

## Notes/ Attachments

Question: If the ETA cannot be calculated, maybe it would be better to show a message instead of infinite loading? 

<img width="735" alt="image" src="https://github.com/user-attachments/assets/8ed177e1-9987-48bb-ade3-67784bdfdd88">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is no longer reproducible, ETA is calculated when sending asset from Mantle. 

Closing the ticket. 

Attachment:
<img width="610" alt="Screenshot 2024-10-23 at 18 14 56" src="https://github.com/user-attachments/assets/01066fd8-06cd-4459-a0ca-8c639b2d622a">
