### ISSUE TITLE
[QA][Android] Asset list is not scrollable in landscape

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#269]
Preconditions: Wormhole-connect is opened

Environment: Galaxy S22+, Android v12, Chrome v110.0.5481.65

Steps:
1. Click on Asset
2. Scroll through the list of Assets
3. Turn your device to landscape mode
4. Scroll through the list of Assets

Actual result: User is not able to scroll through assets in landscape mode.

Expected result: Assets are accessible is portrait and landscape mode.

Attachment:

https://user-images.githubusercontent.com/91047061/228238214-51faabea-99ad-408d-9846-58de85111a28.mp4

**Comment by tsadovska** [comment]
Duplicate #211.
