### ISSUE TITLE
[QA] User can proceed to review the transaction when no route is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2695]
## Describe the current behavior in detail
Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Steps:
1. Prepare to send 1.57201 USDC from BSC (MetaMask) to Arbitrum (MetaMask)
2. Change source chain to Solana (Phantom wallet was auto-connected) and select USDC token
3. Change Amount if required (in my case, amount exceeded available balance and I clicked on "max" to change Amount to 0.465103)
4. Check that no route is selected
5. Click on "Review transaction" button

Actual result: Transaction details are not displayed. 
Expected result: User should not be able to proceed to review the transaction if route is not selected. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/cca2431c-dd59-4983-9fbf-4649ead2f7f9)

https://github.com/user-attachments/assets/e07ec7cb-687c-43af-8f77-54b5cc748a78

Transaction details are displayed on Confirm transaction screen after route option is selected.

https://github.com/user-attachments/assets/24a75c14-d475-46f1-974e-f6da950af1c9

**Comment by Wesleyleung** [comment]
Looks like an edge case where you're able to get to a state where a route option is not selected. We should make it so that a route option is selected (default 1st result) and check that the "Review transaction" button cannot proceed unless a route is selected.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
