### ISSUE TITLE
[Bug] Mayan min amount messages broken/missing

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2698]
## Steps to reproduce

1. Choose any asset pair that would generate a Mayan route. 
2. Enter a small number
3. Get a generic "route not found" error message when this should tell you the min amount you need to enter.

## Experienced behavior

Compare the differences between Connect vs Mayan's website
![Screenshot 2024-09-23 at 2 02 44 PM](https://github.com/user-attachments/assets/5f42dd57-d45c-4d42-9da5-79572e4a7bd4)
![Screenshot 2024-09-23 at 2 02 30 PM](https://github.com/user-attachments/assets/bb5100c3-1097-42d8-bcfa-8e99e822840e)

## Expected behavior

Inform the user the min amount needed to show a valid route. 
If at least 1 route is valid and others are invalid (eg. valid regular Mayan, invalid Mayan Swift), show the valid route and also include a grey info message informing the user more routes are available above  > x amount.

**Comment by emreboga** [comment]
@Wesleyleung this is what I'm seeing in the latest development:

<img width="536" alt="Screenshot 2024-09-24 at 1 35 42 PM" src="https://github.com/user-attachments/assets/2e9c4682-d35c-43b7-ad83-d12d4551d17a">

Routes that are not available are not shown and we display "More routes available for amounts exceeding ..." message. This change has been with https://github.com/wormhole-foundation/wormhole-connect/pull/2608
I'm not sure why we don't see this message in Portal Bridge though. @nikarm22 Any ideas?

**Comment by nikarm22** [comment]
@emreboga implementation had a bug in #2608 fixed here https://github.com/wormhole-foundation/wormhole-connect/pull/2639/files#diff-b70720c6703c332cc1a63667def94887e91431bd4c3a190f9bd170d516690e6aL448

Once portal updates to newer release will be fixed.
