### ISSUE TITLE
[QA] Amount is not changed if user uses slider, it is changed when user taps on the slider

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#270]
Preconditions: 
Wormhole-connect is opened
Wallets are connected

Environment: Galaxy S22+, Android v12, Chrome v110.0.5481.65

Steps:
1. Prepare to send 0.213 FTM from Fantom to Alfajores
2. Expand the Extra Native Gas field
3. Change the sliders position by sliding it
4. Observe the Amount section in Preview
5. Change the slider by tapping on the slider bar
6. Observe the Amount section in Preview

Actual result: The Amount and Native Token on destination in Preview section changes only when user taps on the slider, when sliding the slider the amount is not changed.

Expected result: Correct information is shown in Preview section.

Comments: Related issue - https://github.com/wormhole-foundation/wormhole-connect/issues/108#issue-1594609777
Attachment:

https://user-images.githubusercontent.com/91047061/228299240-46aa5136-ecf3-47f3-9277-810c1ceb0e1d.mp4

**Comment by AigaD** [comment]
Issue is still reproducible.
Tested from: https://wormhole-connect.netlify.app/
Environment: Galaxy S22+, Android 12
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/53430d91-399c-40eb-b9f5-a2cce2fb70de

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced from iPhone 14, iOs 16.0
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/688b97de-d71b-497d-9a68-1e890be48c6a

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2363
