### ISSUE TITLE
[Bug] USDC automatic routes not showing? 

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2705]
## Description and context

For many EVM L2 -> ETH, automatic routes are not showing. Mayan routes are also not showing. Only manual shows.

Further, only a generic error message shows and does not tell the user if the reason there are no routes is because they need to input a higher amount of USDC

## Steps to reproduce

1. Select an EVM L2 for From
2. Select Eth for To
3. Enter $10 or a smaller number. 
4. See nothing but a generic error or manual CCTP route only. 

## Experienced behavior

<img width="498" alt="Screenshot 2024-09-23 at 11 23 21 PM" src="https://github.com/user-attachments/assets/b7314666-5353-48e7-9d0d-791d9df5f8f8">

<img width="445" alt="Screenshot 2024-09-23 at 11 26 14 PM" src="https://github.com/user-attachments/assets/c54c558b-37af-44e5-8a56-a05b51f153a9">
<img width="421" alt="Screenshot 2024-09-23 at 11 26 05 PM" src="https://github.com/user-attachments/assets/58a10acb-fb4d-4a3b-bcf4-1cb682af5804">

## Solution recommendation

This may be happening because due to network costs, at least $10 is required to bridge into EVM. However, the min amount error message seems to be broken. Neither the min amount warning shows (when no routes are found) nor gray info message shows (when the user has at least 1 successful route)

**Comment by emreboga** [comment]
I can see the expected behavior in latest Netlify deployment:

<img width="507" alt="Screenshot 2024-09-24 at 1 47 11 PM" src="https://github.com/user-attachments/assets/655df30e-91f1-4a6d-95b9-175d61862fbd">

This could have been fixed. @Wesleyleung, can you double-check?

**Comment by kev1n-peters** [comment]
This is an issue in the SDK not throwing the `MinAmountError` for the automatic CCTP route. Here is the fix: https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/703
