### ISSUE TITLE
[Bug] Solana to Sui route doesn't exist for USDC? Possibly other routes too

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2706]
## Steps to reproduce

1. Select USDC on Solana as From
2. USDC on Sui as To (this is strangely only possible if you go back to select USDC on Ethereum first in From, select USDC on Sui, and switch back to USDC on Solana in From)
3. Get zero routes and no feedback why

## Experienced behavior

<img width="470" alt="Screenshot 2024-09-23 at 11 16 25 PM" src="https://github.com/user-attachments/assets/a8125b04-4fcb-4044-b36f-a94632700fb7">
<img width="403" alt="Screenshot 2024-09-23 at 11 36 34 PM" src="https://github.com/user-attachments/assets/7d02f8b1-b699-4d65-9413-3102e329f255">

**Comment by Wesleyleung** [comment]
For some reason, I am only able to get wUSDC to show up if I select USDC on Ethereum as my source input first. Otherwise, there is no input and it makes this case difficult to test. We should fix for this issue first: https://github.com/wormhole-foundation/wormhole-connect/issues/2690

**Comment by kev1n-peters** [comment]
Special case Sui to revert to the previous behavior such that any flavor of USDC is allowed (knowing we will probably deprecate this once Circle USDC is launched and we integrate Sui CCTP)
