### ISSUE TITLE
[QA] Warning "No routes found" is displayed for a brief moment before routes are loaded

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2709]
## Describe the current behavior in detail
Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development

Steps:
1. Select Fantom network and SUI token in "From" section (MetaMask wallet was auto-connected)
2. Select Sui network and SUI token in "To" section (Sui wallet was auto-connected)
3. Click on "max" (in my case, max amount is 0.239697)

Actual result: Warning "No routes found" is displayed immediately for a brief moment before routes are loaded. 
Expected result: Warning "No routes found" is displayed after loading process completes. 

## Notes/ Attachments

https://github.com/user-attachments/assets/c897a50c-f8b9-47e4-9585-6d71ba4edb7b

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is still reproducible, warning "No routes found for this transaction" is displayed immediately for a brief moment before routes are loaded.

Attachment:
<img width="1440" alt="Screenshot 2024-10-23 at 18 20 15" src="https://github.com/user-attachments/assets/23d98458-9574-4931-bb8a-5e8fffb03682">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://portalbridge.com/, routes are displayed without any errors. 

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/a323c0d8-681c-40e5-9944-a7afa0ae7344

**Comment by siomochkin** [comment]
Hey @agodlevska, the issue reproduces for PAXG, maybe I'm missing something, but why I do even need some "routes" to be available while bridging assets?

<img width="645" alt="Image" src="https://github.com/user-attachments/assets/9b15c752-e7cb-4208-b9a3-e5591e6898ef" />

<img width="645" alt="Image" src="https://github.com/user-attachments/assets/acac5ede-9c18-41ac-810d-a9ff23cebe2d" />
