### ISSUE TITLE
[QA] USDT is not present in Assets list on Base

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2720]
## Describe the current behavior in detail
Preconditions:
- User has USDT token on Base

Environment:
- OS: macOS Sequoia 15.0
- Wallets: Coinbase, MetaMask
- Browser: Google Chrome Version 129.0.6668.59 (Official Build) (x86_64)
- https://wormhole-connect-mainnet.netlify.app/

Steps:

1. Select Base network as source chain
2. Select Coinbase/MetaMask wallet in From section
5. Open Assets list
6. Check if USDT asset is present

Actual result: USDT is not present in Asset list on Base.

<img width="500" alt="Screenshot 2024-09-25 at 10 38 59" src="https://github.com/user-attachments/assets/b4a70778-4eff-44af-861a-9984773bd1ee">

Expected result: USDT asset is present in Assets list.

<img width="487" alt="Screenshot 2024-09-25 at 10 39 06" src="https://github.com/user-attachments/assets/8d5d8d87-b9b7-475d-9f7c-b4f4c0a6ccc1">

**Comment by Wesleyleung** [comment]
not able to repro in latest preview. https://preview.portalbridge.com/712d941311/

<img width="480" alt="Screenshot 2024-09-25 at 5 28 07 PM" src="https://github.com/user-attachments/assets/ca08ad3f-7d7d-410f-84de-2810e6fdb8c9">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
USDT is not present in Asset list on Base.

Attachment:
<img width="495" alt="Screenshot 2024-10-07 at 15 54 58" src="https://github.com/user-attachments/assets/8cc32c06-beca-494f-89bc-cac4d912b86a">
