### ISSUE TITLE
[QA] [Improvement] Show min amount required message instead of "No routes found" when sending asset with AutomaticCCTPRoute

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2721]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAgtXALY5R4DGAwrwBUACgCUqNALogAvkA%3D).

Custom config:
```
{
network: "Mainnet",
routes: [AutomaticCCTPRoute]
}
```

Steps:
1. Select Ethereum network and USDC token in "From" section (MetaMask wallet was auto-connected)
2. Select Arbitrum network and USDC token in "To" section (MetaMask wallet was auto-connected)
3. Enter amount, 0.0001
4. Check the warning

Actual result: Warning "No routes found for this transaction" is displayed. 
Expected result: Min amount required warning is displayed.  

## Notes/ Attachments

Current behaviour: 

![image](https://github.com/user-attachments/assets/092984aa-0c22-40ca-b906-eb5730bc4a73)

Route becomes available when higher amount is entered. 

![image](https://github.com/user-attachments/assets/c975c13e-94d3-4809-a8fd-bd8eacf28a07)

**Comment by Wesleyleung** [comment]
This should be fixed here: https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/703, but it has not yet been merged.
