### ISSUE TITLE
[QA] Balance for KLAY on Kaia is loading only after asset is selected, balances for other assets are not loading

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2724]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0IAvkA%3D%3D).

Steps:
1. Select Kaia network in "From" section (MetaMask wallet was auto-connected)
2. Check that balance for KLAY is not loaded
3. Select KLAY token 
4. Open "From" section again

Actual result: Balance for KLAY is displayed. 
Expected result: Balance for KLAY is displayed when user selects Kaia network for the first time. 

## Notes/ Attachments

https://github.com/user-attachments/assets/606baf2d-447f-417a-9ffd-cb99d3a4e7cd

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/712d941311/. Balance for KLAY token is loading only after asset is selected. Balances for other tokens are not displayed. 
* Portal Bridge: v0.2.15-P5c8f2dea8c
* Wormhole connect: v^1.0.0-beta.3-development

https://github.com/user-attachments/assets/1e57f468-a802-45a8-a61c-46ca0cbe7236

**Comment by emreboga** [comment]
@tsadovska can you re-add the screen recordings? The ones above don't seem to open.

**Comment by emreboga** [comment]
The problem is the error from RPC about the batch size when requesting token balances:

```
Error: could not coalesce error (
  error={ "code": -32062, "message": "Batch size too large" },
  payload={
    "id": 2,
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [ "0x49887a216375fded17dc1aaad4920c3777265614", "latest" ]
  },
  code=UNKNOWN_ERROR,
  version=6.13.2
)
```
The default Kaia RPC in Connect and (if any) the override in Portal Bridge is not accepting larger RPC payloads to get the token balances. When I replaced it with our paid RPC in 1Password, it started working.

I think Portal Bridge needs to use another RPC for klaytn. I see that it's using the free one: `https://rpc.ankr.com/klaytn`

**Comment by tsadovska** [comment]
Moved ticket to Portal Bridge repository https://github.com/XLabs/portal-bridge-ui/issues/1119.
