### ISSUE TITLE
[QA] User can start the transfer only after changing the network in extension

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2725]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAgtXALY5R4DGAwrwBUACgCUqNALogAvkA%3D).

Custom config:
```
{
network: "Mainnet",
routes: [AutomaticCCTPRoute]
}
```

Steps:
1. Select Base network in MetaMask extension
2. Prepare to send 0.789212 USDC from Base (MetaMask) to Arbitrum (MetaMask)
3. Click on "Review transaction" button
4. Observe that "Insufficient USDC to cover network costs" warning is displayed
5. Open extension and change network to BSC
6. Wait until warning disappears
7. Click on "Confirm transaction" button
8. Approve MetaMask notifications to switch network back to Base and confirm the transfer

Actual result: Transaction is successfully started. Link to [Wormholescan](https://wormholescan.io/#/tx/0xdc2f0654ead08f9540152996931b53894061a4e00a8d010398cdd6cf3a1a5f90).
Expected result: User can start the transfer without changing the network. Seems like warning "Insufficient USDC to cover network costs" is displayed incorrectly.  

## Notes/ Attachments

https://github.com/user-attachments/assets/be6b4b00-a24d-4d5b-9a90-1e0dd7df0dc4

**Comment by agodlevska** [comment]
Same issue when using Coinbase, Rabby wallet. 
The transaction cannot be initiated without switching the network.

Attachment:

https://github.com/user-attachments/assets/42c499ce-0aeb-4809-a28e-f459b8d22db4

**Comment by emreboga** [comment]
@tsadovska @agodlevska this feature to warn user with insufficient funds was introduced with [this PR](https://github.com/wormhole-foundation/wormhole-connect/pull/2711), but it had issues and was reverted with [this other PR](https://github.com/wormhole-foundation/wormhole-connect/pull/2734) couple days later. We no longer has this check about network costs in the "Review transaction" view. I don't see this warning or the issue described above in the latest deployment, can you please verify? Thanks 🙏

**Comment by tsadovska** [comment]
Insufficient funds warning is no longer displayed on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgEQFsCGAlpDLFgDQjhjKICus0AzpgNpUQB0XAIgKIBiAQQCqAGQAqAfQBKAeWHjeAZTJh2YLh0ixY0ug0YAKUBFNhYiVNEjMwJs6dEEAJoknxGsXuIASrdQ52AYFgAMYAFoSQmFi8sOHQyNC0OOTBgfiQeADmiTEADAAeAEYAnAAsABx4pQDMlQBMAOzOAGzVjfytAKwAjLWCzr1NlaWt5dx4VU0AZtANAELcpWkhDhZW0dhFs7WlAMLdlb383aXdC921od2hxb2lxdz5xbUzlc6CraF13bwN%2Bzw%2BVWa1MsGQeBsoWgBAAbnkwGxQQ57MizHhnM4koxbFgioJeoJ9vtetBWtBnHgFg1jvxoMVnKVerxan1uvk6vxenxaQ1bsCKGj1gBPAAO0BiSGQOHCiAANtAQUKAL6CtEAXTVa1V6VMqNBESiMQWjFCStBmRyCLxhVapVp3VaDV6dt6%2BwWMxZ3Gc3G6DXKzl4TV6%2BSarWKTVK%2FHygnyzUq5rWG2sBUKDW%2B3Wg%2BV6foDDV4TsqMaq%2FAaN3yMy63GgTWgft4Y16bsTIXBkNNMPhyH8Qog%2BqFGKxTFxRWK0Fq%2FFr%2BXaTXz%2BWcXX23Ca%2FH4rIWTTwUwW93K5Va3H2pXtrRbyNgYol2ClMvliq1aJ1Qs1uogT5CL7WAHUe6D%2ByFDSIGIlHlSE8DPBxLVybtsAAOXEWBBDwRBuAAKXCKwfGgPAADVhB8SBhXCeBigABVgwRYNaL9sgWUUfFQHwFnEUJWmcJpYVEABpCCzGTLYsEqbocIWfgAEUAC0j3ECTUBmPBRVgBYvwAK1hYR4CaABNYoJJU4U%2FS%2BHAVNgUiAHEVM8MTBBwMTeLBCEoU7BEkV7f9kUHbFcXgxDkLQjDoCw3D8MI4iyIoqiaLohimJYtiOO4%2BzAgvcVJRQW8FSS0x32RT80QAR1oRAGBgrBYPytoAA18sESpRGKRh9loMzKgAWVEL8v1oUjKh6WCcNaFTpF6Vrikq6AuMKbhyh8bi0PsnKQnchxAIEuIEiSFIsqg60ilCUNFkJXgZlqWpyW9OtSljcoxmPY7ymgSp%2BBqX0KkEKosv41MFgrZ6i3yfJKl6usV16zE%2FXGMojgaYoGkGSomlhspek%2BxyOzhFzXxRLHAk84dU24Ypum6G6GnYh58m4XpijwXhKiJYpeHyPYm32coWSDcp0wR%2FIzQfIUUqvLAb1lTL%2BdBRa1jy7VxbMZazFWmJBGQYoCHBLbZcgsDoNTK5TucGNQi%2BcopnZQY2jpScDwPfomm6Sd03dKpyk%2BywU22QofsrPB%2FsB4HulBtjnAh8oocaWH4cRmGmVR9toQxmDXKFeWQjxnECd6H3BAWO0szjVpyUqDcmTwHMFjZu3enKHMBnZcpujwU9NaTS80ulUX7xx7Lm9MaWQkl7GhUV7BZEUggcAIRhUh7iAdtKopM%2FKLk8EjCsGgnGYyiaWcxm%2BHO1zY%2FY2iOZnamgfpXc2b7fp9gG%2FfJAP%2BDB4P01D85w7h5wEaRmOZ%2FMNH45dl%2FMnLu6JMReVTI8bglQIxE2aPsd6ZImj1FCEsKkC4%2Bj7AaP6AudtWihlqM4LKfFW7XnSh3YhYAB6BD7oEaheou7DywAsPAjBO5CjnrrU6hDDbG1NjGTErRLZhm4DbWodsHatCdpUF2f8voey9n9O%2BQMH6B3Bq%2FMOMNP7f2jijORADnKJ1AUEXspg04jimpnemOdSh53TIXYumcy4Vz6NXK4gg64NybsYiAgs24ZXYb2ehZhaEOHoaExayoACUaoXxUFoGw6QFImAEGyFsdW0AKBUH4o1RAkAZipMwPqDwXhfANVCEU4IVhhSSk8N4Hw5SWyMGFDgYo8pamlJ8C2LIsAMb7EiEBbAJo%2BbBH4gASWcJUtYTDhkQXMamdMNwsw5n9M4fMhZixPTLOySsB4ax1nzI2Zs4sB4EFCHkmI4QdCimYAAeluawthsBGAcHOUQXIoRUCIFeYgHAty3k2FuePK0jBbm9CBrUcotzPCQkpMgZwtySn1I4KKSA2QWwArMtAT5iAJmSghKKcUzgAC0ng4DhAxfKFAMQADEAxBATn4C2Zw2LgVylsOCh8i0vyMFAlkKZDhqkxB5Xy8C4tmmtPadgL83S8C9PhP0o02AQJyjAi2cZkyTEAQGQJFVarNbzOwEJES4kpKlBknJBSSlVLqU0jpPSBk4atGMqZCyVkbJ2ROeLM5FzsBXNgDc9A9zHlwBeQCj5Xyfl%2FIBaC4FuRQWskBk0aFsBYV4HhYi35yAO6SDlIgbIbgZi0DlHKSQ5y83IEkMgbIxRJANDvqKQokhZyEoIJITeYZWh4FCEJPAKK0UAH5hiA3aKMEmlKiBYpxXish7c7zMtZfgdlmBWhcofF%2BcliRkg4AFWYIV0rN2bWnsECVbS5TCtlfK6AirBmxHiFujWoy3aQBnctJh60H3HrWIam0ijb4AxUSDJ%2BQcQ6aIjl%2FKOyMWynPOQJf1gbg04lDT8952LI3nOjYgIgsb8DxtuYmhGKa00ZqQDgbNd5c35sLcW0t5aUBVprXWhtTaW2ijbR2gu3be39uyEOpoI6gbnFkcETFaHcWauFuQ%2Bd4sWWhDZRyyoa71BfnTardWO6tV7ugDU6Vqm1bIEfYEU9UqsAyvFj0vpOqlYq304Z9Yz7X26iYcrNTBmv2p3AfjBRN9faAcfs%2FUD78tGRx%2Fno4IMHfVYHg3ch5SHnkobRWJqN%2FysOArjUwfD7JCMwsgHChFpHyMKkowW9tNGy1UsrdW2t9aAaNubQ0Vt7aIycZ7Q3HjfGBNjuE4EUT06JMi2k8EWT8nMCcvUNyxAY8J5T13aYfdpnJu9Om%2B5swxnz3SsvZZpVWBR5LcnitsEDnNVvqsyPKb%2B25mefTt572vn%2FZqJfpDIL4GdFQa9cEH1cHrkxZDfF8NSWMMpew0C3DGWCPJpy3lzNZGc15pK0Wkt5WK0Meq8x%2BrjWONdta321FvHh29UE%2BO8WvWvkzsk3OsWQ3F14GXWAMbZhuU0zYbNiA82vxM8CatlpZ6L3mblVt29LC2HqqOyz0wMzWGc4cD%2Boof67uqOA%2Bop70MXuQd%2FuF71sHLnfaDbFp5YbUsRu%2BYDmNIOQWZaTUR3L6b8tZth1R0riO6OVcYzV%2FIdXWPsea1j7juOOsE66xOyAU7Sf9ak5TwIw2l0KaU2%2BCgyoADcIAgA). Checked the case when network cost is 0.0361 BNB, but user has 0.0179 BNB. "Error with transfer, please try again" warning is shown for the user after clicking on "Confirm transaction" button. 


<img width="1046" alt="image" src="https://github.com/user-attachments/assets/aca8fa88-0359-4e2e-9b9d-22f79e5acf98">

Transactions mentioned in the ticket started and completed successfully:
* USDC transfer from Base (MetaMask) to Arbitrum (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0xf5cdb35f6d01cc66378170ee3eb9745cb7d5facba6d386442b46132554f4ab49) 
* USDC transfer from Arbitrum (MetaMask) to Optimism (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x1b457e834afc099ca4c83d0613a0235a911d0468467edd8569356183f2d2d78b) 

Closing the ticket.
