### ISSUE TITLE
[QA] Transaction is not shown as completed on Transaction screen when asset is received 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2726]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAgtXALY5R4DGAwrwBUACgCUqNALogAvkA%3D).

Custom config:
```
{
network: "Mainnet",
routes: [AutomaticCCTPRoute]
}
```

Steps:
1. Send 0.7892 USDC from Base (MetaMask) to Arbitrum (MetaMask)
2. Wait until asset is received on Arbiscan
3. Check transaction status on wormhole-connect

Actual result: Transaction status is not updated, asset was received 12 min ago. 
Expected result: Transaction status is updated. 

## Notes/ Attachments

Note: Link to [Wormholescan](https://wormholescan.io/#/tx/0xdc2f0654ead08f9540152996931b53894061a4e00a8d010398cdd6cf3a1a5f90) is not displayed on Transaction screen. 

![image](https://github.com/user-attachments/assets/63837d7d-3162-400f-905c-4a407adcd482)

https://github.com/user-attachments/assets/dc815320-1b3b-405e-990a-60955aa77ddc

**Comment by tsadovska** [comment]
Issue is also reproducible when sending 0.0011 ETH from Arbitrum (MetaMask) to Optimism (MetaMask) with Mayan MCTP route. Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDauAnjmAEpU1YDCAKgAUAuiAC%2BQA).

* Link to [Mayan explorer](https://explorer.mayan.finance/swap/0xa533523b8dd407454075e9de98e4b6478520e4c5062966df761754067aa10bdd)
* Link to [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0xb1149f2e77e00ac0a31e5e32d14156b316d1e565110530b67dc2989cfd54b561)

1. Confirm transfer screen.

![image](https://github.com/user-attachments/assets/4c9e09eb-0f60-4d6b-8f47-018eb8e9869f)

2. Wormhole-connect.

Link to Mayan explorer disappeared during the transfer.  

![image](https://github.com/user-attachments/assets/dcd7f076-2c68-4609-8a90-3d4ab5e50d67)

3. Optimistic Etherscan. 

![image](https://github.com/user-attachments/assets/f417ac76-4190-4bd0-9273-6acf69cc3631)

**Comment by agodlevska** [comment]
Issue is also reproducible when sending 1 POL from Polygon (Coinbase) to USDC on Base (Coinbase) with Mayan MCTP route. Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDauAnjmAEpU1YDCAKgAUAuiAC%2BQA).

Link to [Mayan explorer](https://explorer.mayan.finance/swap/0x46b79799c174dd5c886b5c5a2374fb3c86ff2fc5f8318f97d47242a310cb3955)

Attachment:
<img width="1440" alt="Screenshot 2024-09-25 at 17 32 32" src="https://github.com/user-attachments/assets/0f62ebf8-2b0a-49e5-893f-75032f00f44c">

**Comment by Wesleyleung** [comment]
For this issue, is the transaction able to complete like the below? I just tried 0.7892 USDC from Base (Rabby) to Arbitrum (Rabby)
<img width="473" alt="Screenshot 2024-09-25 at 5 21 43 PM" src="https://github.com/user-attachments/assets/ead31a23-f3e6-4129-a3fb-5c92af3658f2">

**Comment by emreboga** [comment]
Adding @tsadovska for the question above ☝️

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Transaction status is updated once it is completed. 

Checked following transfers on https://portalbridge.com/ on Oct 3:
* USDC transfer from Base (MetaMask) to Arbitrum (MetaMask) with AutomaticCCTPRoute, link to [Wormholescan](https://wormholescan.io/#/tx/0x89ff418bf2e621c7716e5b11754de2ab6d9233c07bf63e10cbe0a6a45471d367) 
* USDC transfer from Arbitrum (MetaMask) to Optimism (MetaMask) with Mayan MCTP, link to [Mayan Explorer](https://explorer.mayan.finance/swap/0x47718cca66d505d88f3866ecba33a29adc569ba2932a7fe9c0216567d6bcfeb1) 
* POL swap to USDC from Polygon (MetaMask) to Optimism (MetaMask) with Mayan MCTP, link to [Mayan Explorer](https://explorer.mayan.finance/swap/0x144fd8fadf0f60d3fd08720673630f2827a7b7044a3acf06cf1351dbf79b48cc)

<img width="387" alt="Screenshot 2024-10-03 at 17 10 53" src="https://github.com/user-attachments/assets/0642a69f-f935-411e-9aff-9b83755f0548">



Checked following transfers on https://wormhole-connect-mainnet.netlify.app/ on Oct 3:
* USDC transfer from Base (MetaMask) to Arbitrum (MetaMask) with AutomaticCCTPRoute, link to [Wormholescan](https://wormholescan.io/#/tx/0xf9f97e23708268f3f642dd527ae7b7650897ca06746c23b2cb3069e76308592b)
* USDC transfer from Arbitrum (MetaMask) to Optimism (MetaMask) with Mayan MCTP, link to [Wormholescan](https://explorer.mayan.finance/swap/0x0dbb177e5566455ea1fcd5a9af60d1e110ca3d9fdcdf2615cb9a2e227821bada)

<img width="367" alt="image" src="https://github.com/user-attachments/assets/d911c06b-fc3e-4f6b-b7da-bed40aece5b9">

Closing the ticket.
