### ISSUE TITLE
[QA] Incorrect number of completed steps is shown on Wormholescan

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2727]
## Describe the current behavior in detail
Checked on [https://wormhole-connect-mainnet.netlify.app/](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAwkwCoAKASlTQLogBfIA%3D%3D)

Custom config:
```
{
network: "Mainnet",
routes: [CCTPRoute]
}
```
Steps:
1. Send 0.0001 USDC from Polygon (MetaMask) to Solana (Phantom)
2. Open link to Wormholescan
3. Check number of completed steps

Actual result: The displayed number of completed steps is incorrect, showing "5/4." When clicking on "5/4 Steps Complete," the "Transaction Progress" screen appears. On this screen, it shows that 3 steps have been completed.

Expected result: Correct number of completed steps is shown on Wormholescan. 

## Notes/ Attachments

Link to [Wormholescan](https://wormholescan.io/#/tx/0xc6cc9db7a0cbb1a3edf21d463174b871f81d4a08c58c68a6800c6a7164e3ce48?view=progress).

![Screenshot 2024-09-25 at 15 55 26](https://github.com/user-attachments/assets/b56bd209-71b0-4382-bf91-063ca3dc4d94)

![image](https://github.com/user-attachments/assets/aee5d3b7-b4c7-4c81-a5b7-8f6c6560acda)

**Comment by Wesleyleung** [comment]
Removing Connectv2 tags and reposting to xLabs Wormholescan: https://github.com/XLabs/wormscan-ui/issues/831
