### ISSUE TITLE
[QA] Missing transaction history for Sui network

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2742]
## Describe the current behavior in detail

Environment:
- OS: macOS Sequoia 15.0
- Wallets: Sui, Coinbase
- Browser: Google Chrome Version 129.0.6668.59 (Official Build) (x86_64)
- https://preview.portalbridge.com/712d941311/

Steps:

1. Select Sui network in "From" section
2. Connect Sui/Martian wallet
2. Navigate to the transaction history section
3. Observe the displayed message

Actual Result: The message "No transactions found for the wallet ..." appears, indicating no transactions are found despite their presence on the wallet.

Expected Result: The transaction history should be displayed accurately for the connected wallet.

## Attachments/Notes

Error in console:
```
Error: Chain Sui not supported
    at toMayanChainName (pb-index-lWqu3ugb.js:519:463439)
    at fetchTokensForChain (pb-index-lWqu3ugb.js:519:463886)
    at MayanRouteSWIFT.supportedSourceTokens (pb-index-lWqu3ugb.js:519:466728)
    at SDKv2Route.supportedSourceTokens (pb-index-lWqu3ugb.js:309:66486)
    at async pb-index-lWqu3ugb.js:311:203663
    at async Promise.all (712d941311/index 6)
    at async RouteOperator.allSupportedSourceTokens (pb-index-lWqu3ugb.js:311:203616)
    at async pb-index-lWqu3ugb.js:490:53511
``` 
<img width="1440" alt="Screenshot 2024-09-26 at 09 52 53" src="https://github.com/user-attachments/assets/a0f398b9-f690-4d97-aa0f-34026014122c">

**Comment by emreboga** [comment]
It seems an error from Mayan API is interrupting the TX history flow and we are not rendering results from WHScan API. I'll take a look into this.

**Comment by tsadovska** [comment]
Similar issue: Transaction history is also not shown for Aptos network, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2746.

**Comment by tsadovska** [comment]
Reopening the ticket. 

Steps to reproduce:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG0AKolTRIAIWTjJAJURroAXRAKA3CCA%3D%3D) 
2. Initiate and complete a transfer: 0.002 SUI from Sui (Sui wallet) to Bsc (MetaMask) with TokenBridgeRoute
3. Click on "Start a new transaction" button
4. Check if transfer is displayed in history

Actual result: Transaction is not shown in history even after the transfer is marked as completed in the "In-progress" widget. I have tried waiting for a while, refreshing the page, and reconnecting the wallet. 

Recording:


https://github.com/user-attachments/assets/5708e645-30be-478c-ab57-94eb29a04aae

**Comment by tsadovska** [comment]
Issue is also reproducible when sending asset with AutomaticTokenBridgeRoute. Scenario checked: 2 SUI transfer from Sui (Sui wallet) to BSC (MetaMask).

 

https://github.com/user-attachments/assets/b9156f9f-3ea2-4234-9a2c-e9f430c49902
