### ISSUE TITLE
[QA] Missing transaction history for Aptos network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2746]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/712d941311/ and https://wormhole-connect-mainnet.netlify.app/.

Steps:
1. Select Aptos as source chain
2. Connect the wallet, in my case Spika
3. Click on "Transaction history" icon
4. Check if transaction history is displayed

Actual result:

- Message is displayed "No transactions found for the wallet 0x6599...795b".
- Wallet 0x659900f39239fbfb0cdd74a188ee04fa38c8c4cb2e12c51998f82f80ee3f795b 
- Link to [Aptos Explorer](https://explorer.aptoslabs.com/account/0x659900f39239fbfb0cdd74a188ee04fa38c8c4cb2e12c51998f82f80ee3f795b?network=mainnet)

Expected result: Transaction history is shown. 

## Notes/ Attachments

Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2742 [QA] Missing transaction history for Sui network

![image](https://github.com/user-attachments/assets/d211e052-dbbd-4654-ac8c-8beb04a8d6fd)

**Comment by tsadovska** [comment]
Reopening the ticket.

Steps to reproduce:

1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG0AKolTRIAIWTjJAJURroAXRAKA3CCA%3D%3D)
2. Initiate and complete a transfer: 0.001 APT from Aptos (Spika wallet) to Arbitrum (MetaMask)
3. Click on "Start a new transaction" button
4. Check if transfer is displayed in history

Actual result: Transaction is not shown in history even after the transfer is marked as completed in the "In-progress" widget. I have tried waiting for a while, refreshing the page, and reconnecting the wallet.

Recording:


https://github.com/user-attachments/assets/deb113e9-f51b-4b6f-9628-58a2346d88c0

**Comment by SergejsBeikulis** [comment]
Reopening the ticket.

Steps to reproduce:

Open [https://deploy-preview-3065--wormhole-connect-mainnet.netlify.app/](https://deploy-preview-3065--wormhole-connect-mainnet.netlify.app/)
Initiate and complete a transfer: 0.001 APT from Aptos (Pontem wallet) to Arbitrum (MetaMask) or 0.0001 APT from Aptos (Petra wallet) to Blast (MetaMask)
Click on "Start a new transaction" button
Check if transfer is displayed in history

Did transactions from Pontem wallet and Petra wallet, Pontem wallet is implemented to Petra wallet.
Transaction from Aptos to Arbitrum [Wormholescan](https://wormholescan.io/#/tx/0xe7426fc463e124095976790ad389ce1d0b3ed41d831485844d4096ce49cd23d4)
Transaction from Aptos to Blast [Wormholescan](https://wormholescan.io/#/tx/0x6f649123cf5ba11096edbc3fa334ba013d8cc8ece5b4df248e270cdbca379358)


https://github.com/user-attachments/assets/0948ff57-f703-44a3-ae54-ccb7c1798f48
