### ISSUE TITLE
[QA] Token is shown as unavailable for selection after clicking on "Swap" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2751]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/712d941311/.

Steps:
1. Select Sui network and [USDC (Solana)](https://suiscan.xyz/mainnet/coin/0xb231fcda8bbddb31f2ef02e6161444aec64a514e2c89279584ac9806ce9cf037::coin::COIN/txs) token in "From" section (Sui wallet was auto-connected)
2. Select Solana network and [USDC](https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v) token in "To" section (Phantom wallet was auto-connected)
3. Click on "Swap" button
4. Open "From" section.

Actual result: [USDC](https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v) token is shown as unavailable for selection.
Expected result: [USDC](https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v) token is shown as available for selection. Balance is shown in "Amount" section. 

## Notes/ Attachments

https://github.com/user-attachments/assets/6ff4fdb9-09ea-41aa-a083-6ca9cf0029cc

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is no longer reproducible, USDC token is shown as available for selection. Balance is shown in "Amount" section.

Closing the ticket. 

Attachment:

https://github.com/user-attachments/assets/4edef73d-613e-4e06-9de6-93c2ca06ba4b
