### ISSUE TITLE
[QA] "Additional Gas" amount is incorrect on "Resume transaction" screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2753]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/712d941311/. 

Steps:
1. Send 1.5 USDC from Sui (Sui wallet) to Solana (Phantom) with Automatic route
2. Change slider position to 50%
3. Check "Additional Gas" amount
4. Start the transfer and wait until transaction completes
5. Resume transaction
6. Check "Additional Gas" amount

Actual result: Incorrect amount is displayed. 
Expected result: The same amount is displayed.

## Notes/ Attachments

Link to [Wormholescan](https://wormholescan.io/#/tx/7wGyLmkweNFDEWFUEs39uijM4Y4G6PL19xnuMXHoxPj7).

![Screenshot 2024-09-26 at 20 11 19](https://github.com/user-attachments/assets/49c0f30a-803d-4762-a56f-7885dfb0d6f5)

![Screenshot 2024-09-26 at 20 11 56](https://github.com/user-attachments/assets/7c599c6f-e1c2-49f1-948d-bff816a2bbe7)

https://github.com/user-attachments/assets/1adcf7b2-0684-4955-927f-79d29c684175

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is still reproducible, "Additional Gas" amount is incorrect on "Resume transaction" screen. 

Attachment:
<img width="2262" alt="image" src="https://github.com/user-attachments/assets/204aabe8-9abd-4b15-ac7f-e570e03dd93e">

**Comment by tsadovska** [comment]
Closing the ticket, because USDC transfer from Sui (Sui wallet) to Solana (Phantom) via CCTP Automatic route is currently not available.
