### ISSUE TITLE
In-progress widget should lead to progress screen or resume txn flow

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2759]
## Description and context

When I tap on the in-progress widget, it should:
A) In the case of manual txns, take me to the resume transaction flow (see below)
B) in the case of all kinds of automatic txns, take me to the progress screen. Probably need to use local storage to persist the remaining time on the ETA and timestamps. For example, if my txn countdown is 20 seconds and there's 15 seconds left when I'm viewing the widget on the homescreen, clicking on it and going to the progress screen should then continue the countdown for me from 15 seconds.

## Definition of done

![Screenshot 2024-09-26 at 2 46 32 PM](https://github.com/user-attachments/assets/4657f157-5f62-4a5b-b42f-ba672fa5b03a)
<img width="496" alt="Screenshot 2024-09-26 at 3 13 56 PM" src="https://github.com/user-attachments/assets/1b563ba3-9c77-4400-998d-f3aa11303a92">

**Comment by emreboga** [comment]
@Wesleyleung I wasn't sure between p1 and p2 for this work, please bump it if you think it's more of a p1.

**Comment by Wesleyleung** [comment]
Yep anything for the in-progress widget feels like a p2

**Comment by emreboga** [comment]
This is currently blocked as the only routes supported resuming now are {Manual/Automatic}Ntt, ManualCCTP, and ManualTokenBridge.
@kev1n-peters is there an existing ticket to add the remaining routes for resume transaction so I can link it here? Thanks 🙏

**Comment by tsadovska** [comment]
Tested OK on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA).
* Checked that in-progress widget navigates to resume transaction flow for manual transactions. Сhecked following routes: Token Bridge Manual route, CCTP Manual route, NTT Manual route 
 * Checked that in-progress widget navigates to progress screen for automatic transactions. Checked following routes: Token Bridge Automatic route, CCTP Automatic route, NTT Automatic route, Mayan route, Mayan MCTP route, Mayan Swift route. 
 * Checked that the countdown updates correctly. 
 
 
![Screenshot 2024-10-30 at 15 58 26](https://github.com/user-attachments/assets/7ee14460-fd35-4773-8111-d91c3fc72db0)

**Comment by Wesleyleung** [comment]
@emreboga can we consider this ticket closed?

**Comment by emreboga** [comment]
@Wesleyleung Yup!
