### ISSUE TITLE
[QA] WPOL token unavailable in "To" section across all networks

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2766]
## Describe the current behavior in detail

Environment:
- OS: macOS Sequoia 15.0
- Wallets: MetaMask
- Browser: Google Chrome Version 129.0.6668.71 (Official Build) (x86_64)
- https://preview.portalbridge.com and https://wormhole-connect-mainnet.netlify.app/

Steps:
1. Select Polygon network and POL token in "From" section
2. Go to the "To" section, select BSC and attempt to select the WPOL token
3. Switch routes between each other two times
4. Return to the "To" section and observe that the WPOL token is now available for BSC and other networks

Actual Result: The WPOL token is only available in the "To" section after a network is selected in the "From" section and switch back to the "To" section. 

Expected Result: The WPOL token should be available in the "To" section across all networks, without any additional actions.

## Attachments/Notes 

https://github.com/user-attachments/assets/2d87e0de-fae4-4db1-a569-e0d4baccb0e7

**Comment by emreboga** [comment]
SDK is not returning WPOL when calling `allSupportedDestTokens`.?
@kev1n-peters do you think this is related to our token config for POL?
