### ISSUE TITLE
[QA] Technical information is displayed in the "insufficient funds" warning

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2775]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAKnEhGAEIJ4AmA5hABKVGiTS4AnjjDDqEMZOmyaAdQASCnFJkiIWAMJMACpu3KIAZRUBJAGJMAuiAC%2BQA%3D) and https://portalbridge.com/. 

Steps:
1. Prepare to swap max amount of ETH (in my case, 0.00385) from Ethereum (MetaMask) to Base (MetaMask) 
2. Select Mayan MCTP route
3. Click on "Review transaction" button
4. Click on "Confirm transaction" button
5. Check "Insufficient funds" warning

Actual result: Technical information is displayed in the warning. 
Expected result: Warning is short and clear. 

## Notes/ Attachments
Warning:
`insufficient funds (transaction={ "chainId": "0x1", "data": "0xfa74fd43000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000000000098d236000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c3000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000000000000000000000000000000000000091e8de0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a7586871f228833ba653110d069a1348e7046c4db78da3078aa8e2397f26c9ab470f23000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000000000000099965b000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000000001a6660066fbf45c0000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000041c456ddd4987ac3848f522fb2413eabcbcdde36759ecfcdddab166ab3deef3e0d42f24bfc700cae71cb1695b89ffced4b5e51d22a0c8609824823262c472bdce31c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c4afd9b706000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000dad8dfa62a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049b610000000000000000000000000000000000000000000000000000000066fc05f900000000000000000000000000000000000000000000000000000000001d1eaf000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288f4050f7cfbf77b77f8540decf6cfc7012", "to": "0x0654874eb7f59c6f5b39931fc45dc45337c967c3", "value": "0xdad8dfa62a000" }, info={ "error": { "code": -32000, "message": "failed with 30000000 gas: insufficient funds for gas * price + value: address 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012 have 3849675388816893 want 3850000000000000" }, "payload": { "id": 11, "jsonrpc": "2.0", "method": "eth_estimateGas", "params": [ { "chainId": "0x1", "data": "0xfa74fd43000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000000000098d236000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000520000000000000000000000000000000000000000000000000000000000000040807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c3000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000000000000000000000000000000000000091e8de0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000028a00001a4041c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2d0e30db05120111111125421ca6dc452d289314280a0f8842a65c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2012456a7586871f228833ba653110d069a1348e7046c4db78da3078aa8e2397f26c9ab470f23000000000000000000000000807cf9a772d5a3f9cefbc1192e939d62f0d9bd380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000000000000099965b000000000000000000000000000000000000000000000000000dad8dfa62a000000000000000000000000000000001a6660066fbf45c0000000000000000000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000041c456ddd4987ac3848f522fb2413eabcbcdde36759ecfcdddab166ab3deef3e0d42f24bfc700cae71cb1695b89ffced4b5e51d22a0c8609824823262c472bdce31c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014111111125421ca6dc452d289314280a0f8842a650000000000000000000000000000000000000000000000000000000000000000000000001ea79a4f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c4afd9b706000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000dad8dfa62a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049b610000000000000000000000000000000000000000000000000000000066fc05f900000000000000000000000000000000000000000000000000000000001d1eaf000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000"`

![image](https://github.com/user-attachments/assets/c17b19b4-a8fd-4231-ba1f-a8eed410857e)

**Comment by Wesleyleung** [comment]
Is this still happening?

**Comment by Wesleyleung** [comment]
@danielisaacgeslin I believe this was addressed in a separate task you're working on, right?

**Comment by tsadovska** [comment]
Rechecked the [scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2775#issue-2559204699) on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsvPX1IWFgY9QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8BzKgkqHDQDEIIAgvBsRePCJQcyp9ECQF%2BBWpoVQmIsXYifcYLaWh1H8MGZirE2KdtvAwfwOAQSEX7e2tit4tiwCfHEUVswJrjFvOZNgYhu3DAOSu4i3r0p3R%2BI9M8z1YRvQ%2Bl9Sqv1KYAywRjLSui4i3i5gQcYDbZhMCKP6RoAB6H9ErJWwAYLoN9RBJDjFQIgEDiAcA%2FtAw0H9JyiwMB%2FeSIEEIf3MSCAVZAYgf1tsHbof0kBeC3ng%2FnaAEHEAbuDEKf0gYxAAFpmJwCYGRwiKBZgAGI7hmDMNVb0pEy3jCQ%2BGH85IkyDWEAwMWWwt3eF7bMaTsmJbrFHeOyd2BhCzrwPOyUi7MzYFFuGcWa70k0eaeiA5xnTPNX3V7H2%2Fsg4hzDhHKOMd46JxTmnDOWcoQ5zzoXYupdy6kRfW%2Biyn7YDfvQH%2BgDcBgPwfA5B6DsH4MoaQ5IFD%2Bo8kfEw7AbDeBcP4Zg8gJmdhwx8AYr8Kg4Zwx2DfZV5AdhkC8BBHYXUrx%2FQHDsOjejBA7AvMglBcYXs8BEZIwAfmNHkssQIbSpNIuRyjkGLPJtWV1dYwnRM%2FihJJpMwhWNQJWPJiAimtNHaEiOsdE7wxKZ03p6ABmxpzEgVd0i67N2WZ4ku7AAljsXIbpIxGVCaFmvodCy1cLrVlK4ZUvhjrn2kVfe%2B7AUWYtxaEAl6DYGVtQbfWlxARAMv4Cyz%2BnL%2Bl8uFeK0gHAZW1kVaq4N2r9XGsoBa21jrkLuu9ZhP1wbh1%2Bx4FG%2FGibvBpsfFm0eBb7GiAUao2tqxqahOUZ25gCTzQpNFY8V4nAp2wDnawMIbXnjZCA6qOp2793SJzoXb9rAbiddm7M1iCzw0DmO9N94ii%2B7Mlg9yRawp0OEU2rh%2FahHAiwvI4ix%2Br9v7%2F1Y6AzjkjePUtwaJwhzLghyeVUp1hyAOG8O0%2Fp5GRnvBqss4axx5rrX2udb2Dzvr%2FoBtDaFyL8bxHxczcJNLr4i31jLYV199bPLbzbfwGJ9XQJ9vNGEIgY5pzzn68N3PhfZzzfeEt5po3D27eGcOWv85Lv6hu4ogco587F8b4kV%2BJuJr%2Ffmsh0H1hIfYfItRYjqP6wUeRbj7FhPgGiWGeyW%2BOMG6exOiGpO2eFOeW%2BeheJWdO5WlW5ezOdWVeTWHOde3OPWTeLeguI2Y2YuEuUu82fesukA8uq2w%2BSum2ww4%2BeAk%2BYAGuQqs%2Bqikqy%2B0AfaWmbBUqFuN22%2B2mNuume%2BL24qkqx%2BkAp%2BVm9uYhvBXqwOd%2Bfu2SAeT%2BsKL%2B7Cb%2BdqH%2Bke6w4WqOWA6O8e8WSeSWqeBO4BmeUB2WuesBBWBeRWRepWSBTONWaBbONenO9ejefOzeAuw2wuhBnexBPepB%2Fe26GelB1G1BKatBLQ9BjBzBlEXgsYCgAA3CAEAA%3D%3D). MetaMask notification with warning "You do not have enough ETH in your account to pay for transaction fees on Ethereum Mainnet network" is shown for the user when user doesn't have enough ETH to pay for the transfer. Warning about "insufficient funds" is no longer displayed on wormhole-connect. 


![Screenshot 2024-11-13 at 16 59 41](https://github.com/user-attachments/assets/8e1ce0d0-5d2e-4831-98cb-0a5b8ba41641)



![image](https://github.com/user-attachments/assets/3c7d7a2f-8916-4deb-9c60-07f6f0b2690b)

Closing the ticket.
