### ISSUE TITLE
[QA] Transaction is not displayed in the In-progress widget

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2796]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Send 0.0001 USDC from Arbitrum (MetaMask) to Ethereum (MetaMask) with CCTPRoute
2. When transfer is started, reload the page
3. Check if transaction is displayed in the In-progress widget

Actual result: In-progress widget is not displayed.
Expected result: Transaction that is not completed is displayed in the In-progress widget. 

## Notes/ Attachments
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x103584ae538c30aca7fa22c4fc8bec92a6a98eba8fa1294dfa30e9814a36f06b).
* Waited 10 minutes, transaction is still not displayed. 
* Recording

https://github.com/user-attachments/assets/1bc4bcca-07bb-4abc-8845-42735f7d636c

* Issue is not reproducible on https://portalbridge.com/.
Portal Bridge: v0.2.15-fc5d193d7d.
Wormhole Connect: v^1.0.0-beta.8-development

![image](https://github.com/user-attachments/assets/b940181d-8d0f-458b-8406-342aaaa815ec)

**Comment by tsadovska** [comment]
Transaction is also not shown in the In-progress widget when sending with AutomaticCCTPRoute. 
Scenario checked: 0.07 USDC transfer from Base (MetaMask) to Arbitrum (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0x09837410472ef586cea187de34deebec1c41e72896b438f737b16d9f42440ce2). 


https://github.com/user-attachments/assets/0f2cd749-7d25-40ec-a179-239fe636b2f0

**Comment by tsadovska** [comment]
Issue is also reproducible with TokenBridgeRoute.


https://github.com/user-attachments/assets/0d74f727-77dc-4fc4-ae23-9a3b965af587

**Comment by Wesleyleung** [comment]
@tsadovska I think you need to connect your source wallet too?

cc @emreboga

**Comment by Wesleyleung** [comment]
So it seems the behavior is inconsistent. Based on other tickets, the transaction for CCTPRoute is displayed (but timer is missing) and for these cases, it the widget doesn't show up at all?

**Comment by tsadovska** [comment]
@Wesleyleung Widget was not showing up, because setting `ui: {  showInProgressWidget: true } ` was missing in my browser. 

Scenarios mentioned in the ticket are displayed in the In-progress widget on [this Netlify config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDI%2FQODQ9R8AYRtOMl8AoJCw92E2ExsvPX1IWFh09QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8ORSgVBJUOGgGIQQBBeDYi8eEEAlBzKn0QJAX4lamhVCYixdiJ9xhtpaHUfwwZmKsTYt228DB%2FA4BBIRQdna2K3i2LAJ8cRRWzAmuMW85k2BiF7cMA5a7iLevSndH4j0zzPVhG9D6X1Kq%2FUpgDLBGMtK6LiLeLmBBxhNtmEwIo%2FpGgAHo%2F0SslbABgugP1EEkOMVAiAwOIBwH%2B8DDQ%2F0nKLAwP95IgQQj%2FcxIIBVkBiD%2FR24duh%2FSQF4LeRD%2BdoBQcQFu4MQp%2FSBjEAAWmYnAJgFHCIoFmAAYjuGYMw1VvSkXLeMFD4YfzkiTINYQDAxZbB3d4ftsxZPyYluscdk7p3YGEPOvAi7JTLszNgUW4ZxYbvSXR5p6IDmmfM81Q9Xsfb%2ByDiHMOEco4x3jonFOacM5ZyhDnPOhdi6l3LqRN9H6LLftgL%2B9AAGgNwFA4hyD0HYPwcQ2hlDkg0P6jyR8bDsBcN4Hw4RuDyAmZ2HDHwBivwqDhnDHYD91XkB2GQLwEEdhdSvH9AcOw6NGMEDsC8yCUFxhezwCRsjAB%2BY0eSyxAhtKk0ilHqPQas8m1ZXV1iifEz%2BKE0mkzCHY1AlYimIDKZ0ydoSY6J1TvDCpvTBnoBGbGnMSBN3SKbu3dZniK7sACVOxchukjEZUJoWa%2Bh0LLVwutWUrhlS%2BGOtfaRd9n7sAxbiwloQSXYMQbWzBj9GXEBECy%2FgHLf68v6UK8V0rSAcAVbWVVmrw36uNeaygNrHWuuQt6%2F1mEg3huHX7Hgcb8apu8Fmx8ebR4lucaIFRmjG2rGppE9RvbmApPNBkyVjxXicDnbAJdrAwhdeeNkMDqomn7uPdIgupd%2F2sBuL1xbizWIrPDQOc7833iKKHsyRD3JFrCmw4RTahH9qkcCIi6jqLX6f3%2FsAzjkDeOyME%2FSwhknSHsuCEp5VanOHIB4YI%2FTxnkZme8Fq2zprXHWvtc691vYfOBv%2BiGyNkXYvJukcl3NwksuvjLfWKtpXP3Ns8tvLt%2FAEnNdAkO80YQiBjmnPOYb43C%2Bl9nMt94a32mTdPYd8Zw5G%2Fzlu%2FqB7iiByjmLuX1viRX4m4msD%2Ba6HIfWFh%2Fh8i1FyOY%2FrDR9FhP8WSewGyWWeqWhOcGmepOyG5OueVOBWhexeZWDOlW1WlerODWNeLWXODevOfWLebewuY2E2EuUuMui2A%2B8ukAiu62o%2BKu22wwk%2BeA0%2BYAWuQq8%2Bqikqq%2B0AA6OmHBUqVud2u%2Bumdu%2BmB%2Bb24qkqp%2BkA5%2BNmjuEh%2FBXqoOD%2BAe2SQeL%2BsKb%2B7CH%2BdqX%2B0e6wkW6OWAmOieiWKeKW6eROkB2eMBuW%2Be8BRWReJWJe5WKBLOdWGBHOde3OjezeAureQuo2ouxB3epBfe5Bg%2Bu6We1BtGtBKa9BLQjBzBrBlEXgsYCgAA3CAEAA%3D%3D):
* USDC transfer from Arbitrum to Ethereum with CCTPRoute
* USDC transfer from Base to Arbitrum with AutomaticCCTPRoute
* WAVAX transfer from Polygon to Avalanche with TokenBridgeRoute

![Screenshot 2024-10-04 at 15 58 45](https://github.com/user-attachments/assets/c1653107-6068-40ba-b11d-bdcdbd0a18f7)


Closing the ticket.
