### ISSUE TITLE
[Feature Request] Add a universal back button in the upper left of the nav

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2800]
## Description and context

Currently when you start a manual txn, there is way to go back other than your browser back. Furthermore, when you do click back, your entire state gets lost (wallets get disconnected etc). 
<img width="494" alt="Screenshot 2024-10-03 at 2 39 07 PM" src="https://github.com/user-attachments/assets/c9c925d7-b415-4fb4-ac55-115c4448cf34">

Across all screens in the bridge flow, we should always have a back button in the upper left that would function as you would expect if this were within a web2 mobile app. You can tap back, and it would go back to the home screen. While we do not need to save the asset selection and amount states since that was relevant for the just fired off transaction, we should keep the user's source wallet connected rather than reset the entire state for them.

**Comment by Wesleyleung** [comment]
![2 - Recieved wrapped asset - Portico bridgge (4)](https://github.com/user-attachments/assets/fde5985b-a10e-41c3-a00f-e3e1ad2e9f13)

**Comment by Wesleyleung** [comment]
@kev1n-peters this is a ticket for the universal back button we talked about on Slack. Though not sure if you were planning on picking this up. I don't think it's a blocker for Portico so we can treat it as a separate ticket.

**Comment by emreboga** [comment]
Currently we have back button on Review Transaction and Redeem views. I think we can close this ticket.
Adding @Wesleyleung if there is anything else here.
