### ISSUE TITLE
[QA] Transaction disappeared from In-Progress transactions widget

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2804]
## Describe the current behavior in detail

Environment: 
- OS: macOS Sequoia 15.0
- Wallets: MetaMask
- Browser: Google Chrome Version 129.0.6668.71 (Official Build) (x86_64)
- [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aC89fUhYWBCwhgAKUG9vWERUaEgGOh0UsHMAORsnHzsLdwMAYS1cvLBkuryAYyZCSEwsI1gmaAEqHHJaxvxIPElkDoAGAA9oACExSugATjxlgEYAZjFlgBZJyaMjAHYAVmgAM031pYAOACMxTd3dgDYAJgNJ9bx1pvXBo08mkMu1sDMzJN7rdXssNk0PusHptXv8xOtlgZdnh3isjPdJk0jCjJq95rtboCgalkEEGE1oAQAG69GrUvINdkpPBiMQCIRTaanU4XY63d6TTanY7mdbHMzrIyVe4UozLU6Y05GV6bY73EwmdWvMSvExUrmpfwAB2gHSQyBwLAANtBzVylEM6gBdCKND3sznUlptDomIJpAa%2BoEjMas8HTV63MRzd4XSanMw4sTHY7GC7LW7rC5id73aCbd6vV5bfZNZbvBsmOZuoEgzKC94mY6bTaTdVzW6TSG7e6bB6TAzrQmVW63Xand7Y7Z96EovAtxoyOkM5lx7QWiCBi08vmCbLxh67Y5p3HHaASuW7JrHV54fNTnlNSY8254EeS3ZUyfDd2Vga1bWwe1HUQF0QL9KNGh9T1vH9RCEIgKxxEQOx4AYWAjBsAAJNlqSPRpgyIDouh6PpI2QlIY3GQV7j2X9ljHd5jhNX9xRMV5Ti2Mx0TFZZXl2Aw%2F1ua97zmAxljglI2zBLAZmvTZlkqU5CxMDVTjmU5NiaU4mnuDF7i%2BUcLiTMxUXYrV3kqPBJgUmlt0ZFkJjAfcDzI9kT35c8VOmBUzEqSp1mgMkxDwFNtOgR4NmJATTj7TYTHWYxtPeYznPQ6kwJtO0UGg2C8rqVD2SQ9kKsaXzmlaSjsDmekXIgRi4yC2FtNORFYRuOYLmJAwxAMBddjEE4pxfe5jmWEwh0mTjKTK1J0nbeNKyM6BvjGkttXeQczApEx3iMyYLj4gxoDvBc1WrG5WrALcsh3DySItOqgX8s9mPLLttsTY53iMSYxD4yoDBlEwpTmY48D%2FOZTJeV4qjhGFHsU8CiodZ1XRWlIaqBKrqUJ7xibqYR3tq%2BjvAo5T3BgoJ13xsB2s8rAilgTNEAMAApJgMkI6A8AANQsQjIH8Jh4HuTgCjMApXmEXg5itQjUEIuYbARbMmSsABpR6lI6W5ThFuYTAARQALUqZYbGt1ALjwK1YDmYQACsmQseBjgATXua2Pf8BcbJwD3YE4ABxD28MtswcEto3aRe9y9xplJPsab6BWwTnub5gXoCF0Xxcl6XZflxXldV9XNe141jj1w2WcxwrIOK3GMcUFnyepABHKhEHUdmCn7k0AA1%2B7MW4rHuBhKioKPbh8KxhGEKhOBhU4ChF14PYcdYfHuCfoH16YsUIg2%2BZc0nM4zsA6ao7pemgfpHrZwUvyBuZ1jMIwrgomgMNaAGphyiThAA3Y0Bbhhk1HsI6y0H7G3jHMc6YZBwHFnGSaUJgYS8gXGJFiWlSzvCElJe4pYNjJzcruTy3kPoP25LyAKgoDD3GFLses2YMQTnWPcPARhbihXuCDdS6wbi7GJCcQCgNCTdwgAVCCWAoJd1bj3B%2BfdyorSzhAJ%2B2AzDIHuAQGQ78Waf3jAZHsYghxNBstiecQ5eSmmgF2FGKMthnC7JWSocwKS7CNmtZSMw0EXTwJgyY2DQEynwWIQhI51TikoeQvUVCAQs2evSNO9CmH1FyRAHOgUZiTnCWYOYsJtqLSrDA2GGxfh6UqFeASux1gGTMCleceBXgKKeljDuOMYJ41yXfPIWi8gjMPA%2FfRWAnCuwIDgAgDA6IWgsUFH4ux0p4Fmudd4aULgsRzO8USqJynQ2NJUE0WlJSbGgFsQJoJBShIwQcSJMJol4ONHEysCSSHJLEBQtJNDU50KpgGfJYBCmCmWOZB4eoFzHEqEdSK3ZbhNFkjFMGAlKgNjeK8M4rxJjdjED0pR2MSpDIPBoi0YyCY6KmQ1ZScw8AMApVyVZMwrHLjMHYsSf4UpCRNCYVxL4DAeN1KcbxrxfH%2BPuetIKTzwkvKibg2J8TiFJLIf81JLF0nIJTlkkFXlcm6LyJC%2BMJThHlOWJUysZJbi1J%2BK0uYjSzjrBaW0jppwukkr6Sozugzu4TLJitEZYyaoKAAJReCQpQKgLKHDQDEIIAgvAwSmPCCASgSkF6IEgBcFNOQUi4XwkReeTRC15AyP4O0eECKETLRuBg%2FgcD3BgjWkthENyjFgLuSoDKOjNSaBuJSbAxAVrqNMwdcEzVBU2ucHai49ofEOsdU6KULoo2uqA4GokJGVA3KTAgTRc0dCYDEK02QAD0l7mUstgAwXQx6iCSCaKgRAj7EA4EvU%2BrIl75mxgYJepEtxniXrwkEaKyAxCXuLXW3QVpIC8A3D%2BqO0BX2IFHXaWkVobRiAALR4TgEwZDMEUAdAAMSbDMGYNKZoEJJqaP%2Bp054kS%2BhqsIBgjNRjju8FWjoHGuPMyGE2ltbbsDCC7XgHtLI%2B0hmwAzJ0TNh1BMw3koE0yFNKbyjO025sra23to7Z2rt3Zex9v7QOwdQ6vHDpHGOccE5JwQoe49ykz2wAvega9t64APp%2FS%2Bt9H6v0%2FsA%2F%2ByQgGpSROOGB2AEG8BQZg5%2B5AuM7BOj4NhC4VAnROjsMetLyA7DIF4PcOwEoDhWmmHYIGOGCB2H2S%2BV8TRTZ4Hg4hgA%2FHKSJiZbjqgCQhFDaG32qb9QM0qQwGNMfPK8NjvphBEdfv0HjEA%2BPifm7RRtzbW1On45J6T0BZONU6C%2FdbCER1jrU%2BRft2BqILeWdnFhP1UHoMVVgt5KrPlqsSaQlJlCdUHoQkek92B3Oee80IXzH7n2Dffce4LiAiChfwOFy9kWpIxbiwlpAOBkuDNS%2BlurWWct5ZQIV4rpWXkVaq%2B8GrdWZpVjwE1r1rXeAdeOF12cvWSNEFQ%2Bh4bqiA30bQ5NzArHcjsfi8Y0xOAltgBW1gYQEuTGyDuykETW2dsIW7b2q7WBDGS%2BV8p0Eqm6rTL10rsxyEZ0hOexE5VMSPvfPVd9rVv3qHOYB650956r03vB%2FeyHiHodBe%2FfD39YXBAo5Smj8DkBIPQaxzjl0ePeAZcJ7l0jBWislbK5MSn1WrS1fq%2FTxnLWEMs86zCDnpw%2BtDAG7z87I3yUbgm%2FgZjIvbgzdyMIRAcyFlLJl3L7vvfFkq%2B8GrsT8vdva7kzM4fSzDeZGN8haZsye199H8w08ud5U26VW9%2B3BDHdfb%2BQCv77uhiA7c97rzvu71%2BdDwFmHn6Q8I7%2FUjiPqPosx7j4l7HKW0sp4E7Zbp75ak7Z4U6Vb56F506NbNbM6s7s49bV5c6QA85DYN785jZ1At54Bt5gCi60pd4CIsoD7QDVribEGsqq6bYT4Saa5SbT6HZMosoL6QBL7qY67MFUGmoPbb7W5hK2774fKH5ELH6aqn5u5DAuZA5YAg4%2B4%2Bb%2B7%2BZB6w4v5h7v4RZR5f6xax7xbx5Jb%2F746ZbAHE6Z5k45557U4F604NYM5wFl4IGV5IE14Tqh5oEYYYH%2BpYF5A4F4EEEoReAegKAADcIAQAA%3D%3D%3D)

Steps to reproduce:

1. Initiate a transaction (0.01 DAI from Arbitrum (Coinbase) to Avalanche (Coinbase))
2. Verify that the transaction appears in the list of transactions in progress on the widget
3. Wait for the transaction to reach the claiming stage
4. Observe that the transaction is no longer visible in the widget

Actual Result: The transaction disappears from the list of transactions in progress once it is ready to be claimed.

Expected Result: The transaction should remain visible in the list of transactions in progress even when it is ready to be claimed.

## Attachments/Notes
[Wormholescan](https://wormholescan.io/#/tx/0xb58b9af177fc7c7689cb800e8efb55ea0208fd049bcf739c0c3acf3cf33020d1)

Note: Another transaction that is ready for claiming still appears in the list, indicating that the issue is not consistent across all transactions.

https://github.com/user-attachments/assets/2a941fda-7d3e-4162-a9d4-1be40840cb27

**Comment by agodlevska** [comment]
A similar situation occurred with the transaction 0.0001 WPOL from Scroll (MetaMask) to BSC (MetaMask), but this transaction disappeared from the list even before it was ready to be claimed.

[Wormholescan](https://wormholescan.io/#/tx/0x70dac0700b17314b07c8b8a32036a2c6ba17f6e2f2c7e9c41860e91e5ddb2121)

Attachments:
<img width="653" alt="Screenshot 2024-10-04 at 13 49 22" src="https://github.com/user-attachments/assets/5a676bad-135d-4b4a-a00a-02f644446aab">
<img width="1439" alt="Screenshot 2024-10-04 at 13 49 34" src="https://github.com/user-attachments/assets/dcfd1b98-8bdc-478b-bee8-746723b1f5e8">

**Comment by Wesleyleung** [comment]
maybe the widget is marking the claim stage as done hence it dissapears?

**Comment by agodlevska** [comment]
Checked [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA).
Issue is no longer reproducible, the transaction remains visible in the list of transactions in progress even when it is ready to be claimed.

Attachment:
<img width="438" alt="Screenshot 2024-10-29 at 11 30 20" src="https://github.com/user-attachments/assets/28e017f7-a9b5-4fe7-87c7-45dda5d13a13">
