### ISSUE TITLE
[QA] Mobile: Text in the “Gas payment” section should be left-aligned 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#281]
#### Steps:
1. Connect Metamask wallets in 'From' and 'To' sections 
2. Prepare to send ETH from Goerli to Fantom from mobile (iOS or Android)
3. Expand “Gas payment” section

#### Actual result:
Text in the “Gas payment” section is not left-aligned. 

#### Expected result:
Text in the “Gas payment” section is left-aligned. 

#### Tested devices:
* iPhone 11 iOS 15.4.1, Chrome Version 111.0.5563.72
* Samsung S20 Android 12, Chrome Version: 111.0.5563.115

#### Attachments:
* iPhone
![iphone](https://user-images.githubusercontent.com/10746654/229476691-329e1ab7-271f-4032-a411-bbc1acf57def.png)

* Android
 
 
![android](https://user-images.githubusercontent.com/10746654/229476720-fff75704-fecb-42d3-82ca-9f8a7fb272c6.png)

* Figma
![Screenshot 2023-04-03 at 12 59 46](https://user-images.githubusercontent.com/10746654/229477766-b5e152f4-28be-43dd-82b4-bd5afd955e59.png)

**Comment by anondev2323** [comment]
Can be done at the same time as #290

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by tsadovska** [comment]
Design has changed, remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1283. 
Ticket is closed.
