### ISSUE TITLE
[Bug] Error occurs when Using Wormhole Bridge with Safe-Global-Wallet (1 of 1)

### ISSUE THREAD

**Issue by junha-ahn** [wormhole-foundation/wormhole-connect#2811]
## Description and context

When using the Wormhole Bridge with a Safe Global wallet (1-of-1 configuration), transactions fail on the Ethereum network. 
- However, the same setup successfully executes transactions on the Polygon network (So I think, it's a simple bug for calling estimateGas RPC on the Ethereum network)
- its not a eth balance issue, I try with balance of eth 0.07 but failed too

## Steps to reproduce

1. Set up a transfer of ETH from Ethereum network to Arbitrum network using Wormhole Bridge.
2. Connect [Safe Global wallet](https://app.safe.global/welcome/accounts) using WalletConnect. (Ethereum network 1of1) 
3. Click the "Review Transaction" button.
4. Click the "Confirm Transaction" button.
5. And Error Occurred (Image below)

## Experienced behavior

<img width="603" alt="image" src="https://github.com/user-attachments/assets/577726a7-cd98-465d-b92a-ad5a9ffc56c5">

- from address is my safe_proxy_contract's address ([source code](https://github.com/safe-global/safe-smart-account/blob/main/contracts/proxies/SafeProxy.sol))

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/8bd741c1-4f77-4dce-9bef-7bdec4ab842f">

```
id: "1728275412759630080"
jsonrpc: "2.0"
method: "eth_estimateGas"
```

**Comment by Krikor-tech** [comment]
@junha-ahn Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Wesleyleung** [comment]
@mliu-xlabs remind me where did we end up with addressing the Safe issues again?

**Comment by mliu-xlabs** [comment]
We are waiting for support and coordination with Safe to get this fixed. Still pending atm. This issue isn't related to the other issue though.

**Comment by junha-ahn** [comment]
May I know when the issue will be resolved (ETA), or does the wormhole bridge not support Safewallet?

**Comment by mliu-xlabs** [comment]
@junha-ahn Safe Wallet should be working now via Wallet Connect. let me know if there are other issues with this -- if no others, I will close this issue.
