### ISSUE TITLE
[QA] Network name is displayed outside the boundaries

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2813]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/.

Steps:
1. Click on "Select chain and token" in "From" section
2. Click on "Other" button
3. Select Optimism Sepolia / Arbitrum Sepolia network

Actual result: Network name is displayed outside the boundaries.
Expected result: Network name fits in the box. 

## Notes/ Attachments

![Screenshot 2024-10-08 at 10 13 08](https://github.com/user-attachments/assets/eab11215-54f2-4d27-9e30-54db3dd04745)

![Screenshot 2024-10-08 at 10 17 55](https://github.com/user-attachments/assets/cf5a17cb-6a4d-4d81-9359-3a65b2563d7d)

**Comment by Krikor-tech** [comment]
@tsadovska Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Wesleyleung** [comment]
We should just wrap to second line

**Comment by Wesleyleung** [comment]
@emreboga I believe this may also be a case more pronounced in mobile? Esp since we increased the font (not sure if it affected the text size for these labels?)

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect.netlify.app/. 
Issue is still reproducible, network name is displayed outside the boundaries.

Attahcment:
<img width="520" alt="Screenshot 2024-11-06 at 17 40 55" src="https://github.com/user-attachments/assets/8e4c078b-84f0-491e-a4c4-ead035a84e30">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/.

![image](https://github.com/user-attachments/assets/90ad2bc1-efa4-4161-bae6-716c60924ccd)

![image](https://github.com/user-attachments/assets/ab070bc8-bc39-43d0-a24d-6516cca800ff)
