### ISSUE TITLE
[QA] [Mobile] Visual issues on mobile when screen zoom is set to maximum 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#283]
#### Precondition:
Screen zoom is set to maximum

#### Steps:
1. Open Networks list and select Moonbase network
2. Open Network list and select Alfajores network

#### Actual results:
* Moonbase: network name is not fully visible and network icon is not displayed
* Alfajores: network icon is poorly visible

#### Expected results:
Network names and network icons are well displayed. 

#### Tested device:
Samsung S20 Android 12, Chrome Version: 111.0.5563.115

#### Attachments:
* Device settings
![settings](https://user-images.githubusercontent.com/10746654/229500990-e7eb61ea-4bc6-4fb9-8723-0693f4e9bb53.png)

* Moonbase
![Moonbase](https://user-images.githubusercontent.com/10746654/229501000-f3bf538e-94f5-4466-9e57-67eb67ed7d5c.png)

* Alfajores

![Alfajores](https://user-images.githubusercontent.com/10746654/229501014-37cf1a0b-5027-43d3-9330-f46f5e6d252a.png)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] with Samsung S20 (Android 12).

**Comment by AigaD** [comment]
Reproduced from device Samsung Galaxy S22+, OS12
Tested from: https://wormhole-connect.netlify.app/#

**Comment by tsadovska** [comment]
Issue is still reproducible on https://portalbridge.com/ and is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ (Connect v2).

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2300 [QA] [Redesign] Some options from "Select a network" dropdown cannot be selected on small screens

Closing the ticket.
