### ISSUE TITLE
[QA] Wrapped tokens are not displayed on Kaia network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2834]
## Describe the current behavior in detail
Tokens are not displayed on Kaia network on https://wormhole-connect-mainnet.netlify.app/. 

![image](https://github.com/user-attachments/assets/0b958e88-49fc-40e2-b2b8-36dea6dcdf21)

## What is the expected/desired behavior
Tokens are successfully displayed. Issue is not reproducible on https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/76c2ca54-0471-4e8a-927e-82e6dad93f80)

**Comment by emreboga** [comment]
@tsadovska This seems to be the similar problem as in https://github.com/wormhole-foundation/wormhole-connect/issues/2724
The default Kaia RPC in Connect is not accepting larger RPC payloads to get the token balances. When I replaced it with the paid RPC in 1Password, it seems to be working.

<img width="868" alt="Screenshot 2024-10-16 at 2 03 25 PM" src="https://github.com/user-attachments/assets/f3205e3c-c36e-42e6-a159-f558efb30d28">

**Comment by tsadovska** [comment]
Closing the ticket as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2993. 
Rechecked on Dec 5 that token balances for Kaia are successfully displayed on https://portalbridge.com/.
