### ISSUE TITLE
[QA] WETH token instead ETH is displayed on Transaction history

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2842]
## Describe the current behavior in detail
Checked on Netlify with following [config](https://deploy-preview-2836--wormhole-connect-mainnet.netlify.app/?config=N4AgTg9grgLgpgZwFwgNoDpMBECiAxAQQFUAZAFQH0AlAeSLJwGUAaEAWQEMBPDgOyujwAuiAC%2BQA%3D%3D%3D).

* https://deploy-preview-2836--wormhole-connect-mainnet.netlify.app/
* Config: `{ routes: [...DEFAULT_ROUTES, MayanRoute] }`

Steps:
1. Transfer 0.008 ETH from Optimism (MetaMask) to Ethereum (MetaMask) as [WETH](https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2) (0xC02...6Cc2)
2. Open Transaction history page
3. Check the token that was sent

Actual result: WETH token is displayed. 
Expected result: ETH token is displayed. 

## Notes/ Attachments 
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x0a847dcac82a20a327a7769c9be2594c598c5c401859fa876196b66562ad8510)
* Send from tx: [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x0a847dcac82a20a327a7769c9be2594c598c5c401859fa876196b66562ad8510)
* Send to tx: [Etherscan](https://etherscan.io/tx/0x9802e47dafe33b9fdd982b736daf472f973a5847f606139ba0586c880a84adfa)

![Screenshot 2024-10-15 at 12 22 43](https://github.com/user-attachments/assets/8817a25a-21d5-4037-9932-4577a88d7a6d)

**Comment by agodlevska** [comment]
Re-checked on [wormhole-connect-mainnet](https://deploy-preview-2836--wormhole-connect-mainnet.netlify.app/?config=N4AgTg9grgLgpgZwFwgNoDpMBECiAxAQQFUAZAFQH0AlAeSLJwGUAaEAWQEMBPDgOyujwAuiAC%2BQA%3D%3D%3D).
Issue is no longer reproducible, ETH token is displayed for new ([Wormholescan](https://wormholescan.io/#/tx/0x19d25aeb16eaa9bf05f4f1f773b9c2982807de9b96d26796ad97b64af68d3b72)) and previously made transactions on Transaction history. 

Closing the ticket. 

Attachment:
<img width="2327" alt="image" src="https://github.com/user-attachments/assets/911e048b-6c0e-4981-9786-e14b616261e5">
