### ISSUE TITLE
[QA] [object Object] text in "Network Cost" in transaction details

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2848]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0
- Wallets: Phantom, Sui Wallet, MetaMask
- Browser: Google Chrome Version 129.0.6668.101 (Official Build) (x86_64)
- https://preview.portalbridge.com/dd12faf4dd/ and https://wormhole-connect-mainnet.netlify.app/

Steps to reproduce:

1. Prepare to send 0.01 SOL from Solana (Phantom) to Sui (Sui Wallet)
2. Observe the "Network cost" field in transaction details (automatic route)

Actual Result: The "Network Cost" information incorrectly displays the raw data "[object Object]" instead of the network cost amount.

Expected Result: The "Network Cost" information should display the correct network cost amount instead of the raw data "[object Object]".

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-10-16 at 16 57 24" src="https://github.com/user-attachments/assets/c1968e26-b75e-47d2-b049-b86385a11268">

<img width="1440" alt="Screenshot 2024-10-16 at 16 57 31" src="https://github.com/user-attachments/assets/bf4ba310-44ca-43b6-8f34-8a1667524c56">

**Comment by artursapek** [comment]
this is my bad. fixing

**Comment by artursapek** [comment]
fixed in https://github.com/wormhole-foundation/wormhole-connect/pull/2851

**Comment by tsadovska** [comment]
Issue is reproducible on [Portal Bridge ](https://preview.portalbridge.com/dd12faf4dd/?sourceChain=optimism&targetChain=arbitrum&sourceAsset=USDCoptimism&targetAsset=USDCarbitrum&route=AutomaticCCTP) on Oct 17 when Automatic CCTP route or "NTT: Wormhole + Axelar" route is selected.


![Screenshot 2024-10-17 at 16 35 19](https://github.com/user-attachments/assets/c753c910-17fb-4ef8-9a6b-0cc8e6058c64)

![image](https://github.com/user-attachments/assets/4e566d68-09ea-4e34-985b-7fee7acc8a5e)

**Comment by tsadovska** [comment]
Reproduced on https://preview.portalbridge.com/4c74faf073/ when sending 0.04 USDC with contract address `0xe6d82Bbe75041E42E51d755e922cE1BA91af9c4d` from BSC (MetaMask) to Polygon (MetaMask). 

![Screenshot 2024-10-30 at 21 45 35](https://github.com/user-attachments/assets/e21cc72c-2309-4c9b-b00d-fa7be425aac2)


Issue is not reproducible on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA) and https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/316ace6d-544f-42df-8bc6-c9f431e8168d)
