### ISSUE TITLE
[QA] "Routes" section title is displayed when transaction data has not been entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2856]
## Describe the current behavior in detail
"Routes" section title is displayed when transaction data has not been entered. 

Reproducible on [Netlify](https://wormhole-connect-mainnet.netlify.app/?config=N4KARATg9grgLgUwM5gFwAIDaA6XARAUQDEBBAVQBkAVAfQCUB5MqggZQBp0BZAQwE8eAOzqxEnXgOGiEXAMJUACuP5CR8BKwDqASSJUAuiAC%2BQA) and https://preview.portalbridge.com/dd12faf4dd/.

Issue is not reproducible on https://portalbridge.com/. 

## Notes/ Attachments

![Screenshot 2024-10-17 at 17 38 52](https://github.com/user-attachments/assets/77f5a009-433f-4da7-bb1c-cb5e2d149c31)

**Comment by Wesleyleung** [comment]
I'm able to reproduce this every time. IMO we should have this fixed before release.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/4c74faf073/.
