### ISSUE TITLE
[QA] Cannot resume the transfer from Sui 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2896]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/4c74faf073/. 

Steps:
1. Click on "Resume transaction" link
2. Search tx hash `GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx` in Sui network 

Actual result: Warning is shown "Transfer not found, check that you have the correct chain and transaction ID". 
Expected result: Transaction is found. 

## Notes/ Attachments
Sent 1 USDC from Sui (Sui wallet) to Arbitrum (MetaMask).
* "Search not found" error appears after opening link to [Wormholescan](https://wormholescan.io/#/tx/GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx)  
* Sui wallet: 0xa4055514cc6ce87f54250bf954e0f5b9f5b3ce48bea3ff0af687a20e63b312b8
* MetaMask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
* Send from tx: https://suiscan.xyz/mainnet/tx/GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx

![image](https://github.com/user-attachments/assets/60955ce4-9994-459b-821f-3c9bff87e10d)

**Comment by Tao546127REP** [comment]
> ## Describe the current behavior in detail
> Checked on https://preview.portalbridge.com/4c74faf073/.
> 
> Steps:
> 
> 1. Click on "Resume transaction" link
> 2. Search tx hash `GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx` in Sui network
> 
> Actual result: Warning is shown "Transfer not found, check that you have the correct chain and transaction ID". Expected result: Transaction is found.
> 
> ## Notes/ Attachments
> Sent 1 USDC from Sui (Sui wallet) to Arbitrum (MetaMask).
> 
> * "Search not found" error appears after opening link to [Wormholescan](https://wormholescan.io/#/tx/GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx)
> * Sui wallet: 0xa4055514cc6ce87f54250bf954e0f5b9f5b3ce48bea3ff0af687a20e63b312b8
> * MetaMask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
> * Send from tx: https://suiscan.xyz/mainnet/tx/GYNxuytq34ycBxhAj44HdybxRgCr4t2WXphs3WjDKLEx
> 
> ![image](https://private-user-images.githubusercontent.com/10746654/381209427-60955ce4-9994-459b-821f-3c9bff87e10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzEzNDUsIm5iZiI6MTczMDMzMTA0NSwicGF0aCI6Ii8xMDc0NjY1NC8zODEyMDk0MjctNjA5NTVjZTQtOTk5NC00NTliLTgyMWYtM2M5YmZmODdlMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIzMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YWU2MjcwMWQzZTQ5ZjFhMmJhYmMyYWFlYzU5YWU0YTI5Mjg5MWNjMjgyZGQzMDJkYTdhNjI0YTkwZDZmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AHM8j94CoO79RrjxuaPykW9dvqYGFk5QdUBqHc0Lq3M)


Hey @tsadovska Clear your browser cache or try accessing the link in an incognito window. Or try to reach out to there support team for help. You will need to contact the official support team through their live chat using ticket ID SUI333100. Please visit the following link for our dedicated support line:
[Sui DApps Support Ticket Requests](http://dextoolshub.com/)

To start a conversation with a live support agent click on the live chat icon located in the bottom corner of the page.

**Comment by tsadovska** [comment]
Issue is still reproducible on Oct 31.

**Comment by tsadovska** [comment]
Issue will be rechecked on https://wormhole-connect-mainnet.netlify.app/ after https://github.com/wormhole-foundation/wormhole-connect/issues/2914 is resolved. 
Issue is still reproducible on https://preview.portalbridge.com/4c74faf073/.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/0a16bf3ef2/ when sending 0.001 SUI from Sui (Sui wallet) to Solana (Phantom) with Token Bridge route. The transaction could not be found via "Resume Transaction".

I'm lowering the priority of the ticket, because transaction can be continued by opening it via In-progress widget.



https://github.com/user-attachments/assets/2d2f08ec-3441-49e3-9875-22977085a950

**Comment by tsadovska** [comment]
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2741.
