### ISSUE TITLE
[QA] Values in “Preview” section should be right-aligned on Android

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#290]
#### Steps:
1. Connect ‘From’ and ‘To’ wallets via WalletConnect
2. Prepare to send FTM from Fantom to Mumbai
3. Type Amount
4. Convert some FTM in “Extra native gas” section
5. Observe Preview section

#### Actual result:
Values in “Preview” section are not right-aligned.

#### Expected result:
Values in “Preview” section are right-aligned.

#### Tested device:
Samsung S20 Android 12, Chrome Version: 111.0.5563.115

#### Attachment:
![device-2023-04-04-114024](https://user-images.githubusercontent.com/10746654/229737440-40704ae0-b3af-4f97-90ca-182ab4cc3671.png)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Closing as duplicate and linking to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1283
