### ISSUE TITLE
[QA] Notification to approve transaction is not displayed in MetaMask app on mobile

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2900]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ with iPhone 11 Pro iOS 17.6.1 and MetaMask v7.33.0 (1460).

Steps:
1. Select Moonbeam network and GLMR token in "From" section
2. Select Arbitrum network and WGLMR token in "To" section
3. Connect MetaMask wallet via Wallet Connect as source and destination wallet
4. Enter Amount, 1
5. Select Manual route
6. Click on "Review transaction" button
7. Click on "Confirm transaction" button
8. Сheck if notification to approve transaction is displayed

Actual result: Notification to approve transaction is not displayed.
Expected result: Notification to approve transaction is displayed. 

## Notes/ Attachments
Recording when Moonbeam network was already added in networks list. 

https://github.com/user-attachments/assets/5f940cec-b5e2-485d-9053-338088d3ed31

Recording when Moonbeam network was not added in networks list. 

https://github.com/user-attachments/assets/39122bb0-2133-4027-b8a0-bdfe90a74ad4

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ac2a9a0933/ with the same [scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2900#issue-2623306126). 

https://github.com/user-attachments/assets/e89e0b8a-7c39-4377-9a98-e9721614007d

**Comment by emreboga** [comment]
Hey @tsadovska , just to confirm before getting to debug this issue. Can you see this with latest Portal? and do you see this only for GLMR transactions with MetaMask? Thanks 🙏

**Comment by tsadovska** [comment]
@emreboga Issue mentioned in this ticket is no longer reproducible. Notification to confirm transaction is displayed and transaction can be successfully started when correct network is already selected in MetaMask mobile app. 


https://github.com/user-attachments/assets/8ad320af-a4cd-4d92-85d1-ae749dbd9f64

During checking noticed one important issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2772. Could you please take a look https://github.com/wormhole-foundation/wormhole-connect/issues/2772#issuecomment-2491640956?
