### ISSUE TITLE
[QA] User can click on "Review transaction" button when there are insufficient funds to initiate the transfer

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2906]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/4c74faf073/. 

Preconditions:
User doesn't have [USDC](https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v) with contract address `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v` on Solana. 

Steps:
1. Select Arbitrum network and USDC token in "From" section (MetaMask wallet was auto-connected)
2. Change source network to Solana (Phantom wallet was auto-connected)
3. Select Arbitrum network and USDC token in "To" section (MetaMask wallet was auto-connected)
4. Enter Amount, 0.0001
5. Click on "Review transaction" button
6. Click on "Confirm transaction" button

Actual result: Transaction fails.

```
Wormhole Connect: error completing transfer Error: Simulation failed: {"InstructionError":[0,{"Custom":1}]}
Logs:
Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 invoke [1]
  Program log: Instruction: DepositForBurn
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
  Program log: Instruction: Burn
  Program log: Error: insufficient funds
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4198 of 175291 compute units
  Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0x1
  Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 consumed 28907 of 200000 compute units
  Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 failed: custom program error: 0x1
    at Tt (solana-DX9PzBJj-q2MIXTdC.js:7:52132)
    at async he (solana-DX9PzBJj-q2MIXTdC.js:7:50991)
    at async signAndSendTransaction (pb-index-DQ_FDK1L.js:310:62053)
    at async SDKv2Signer.signAndSend (pb-index-DQ_FDK1L.js:310:65041)
    at async ssw (pb-index-DQ_FDK1L.js:281:8130)
    at async signSendWait (pb-index-DQ_FDK1L.js:281:7837)
    at async CircleTransfer.$ [as transfer] (pb-index-DQ_FDK1L.js:281:15178)
    at async Ja.initiate (pb-index-DQ_FDK1L.js:281:57140)
    at async SDKv2Route.send (pb-index-DQ_FDK1L.js:310:69299)
    at async mt (pb-index-DQ_FDK1L.js:571:139176)
```
Expected result: "Review transaction" button is not available for selection if there are insufficient funds to start the transfer.

## Notes/ Attachments

![Screenshot 2024-10-30 at 21 35 33](https://github.com/user-attachments/assets/cf70de1a-0f2b-4e18-a46e-ab073df9b175)

https://github.com/user-attachments/assets/495ff383-dee7-4c02-b34d-65a822e9446c

**Comment by emreboga** [comment]
👀

**Comment by emreboga** [comment]
The root issue here is when user changes network, it should clear the previously selected token.

**Comment by emreboga** [comment]
@tsadovska we had fixes about the token list for a selected network is populated correctly so the correct USDC will be selected. Can you check this and let me know if you can still repro? 🙏 
https://www.loom.com/share/f1ed674e712441a187259497d1384df8?sid=9c541d22-9c4c-4790-9277-52df2d63b898

**Comment by tsadovska** [comment]
@emreboga Thank you very much for the explanation :) !
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
