### ISSUE TITLE
[QA] Improvement: Only show relevent options in “Open with” pop-up after user clicks “Approve and proceed button” on Android

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#291]
#### Steps:
1. Connect ‘From’ and ‘To’ wallets via WalletConnect -> Metamask on Android
2. Prepare data to send transaction: select ‘From’ and ‘To’ networks, Asset, Amount 
3. Click “Approve and proceed button” button
4. Observe “Open with” pop-up

#### Actual result:
3 options are displayed in “Open with” pop-up:
* Keyring pro
* Metamask
* Zerion

#### Expected result:
Only Metamask option is displayed.

#### Tested device:
Samsung S20 Android 12, Chrome Version: 111.0.5563.115

#### Attachment:

https://user-images.githubusercontent.com/10746654/229815526-fb9b6920-f5e5-457b-8b2a-5887c3dfcd18.mp4

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
This is reproduced from: https://wormhole-connect.netlify.app/
Environment: Samsung Galaxy S22+, Chrome
Attachment:
![Screenshot_20231212-160805_Android System](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b21bedc2-1181-4e8e-96cc-dc6a52a0c928)

**Comment by tsadovska** [comment]
Closing the ticket as not a bug.
