### ISSUE TITLE
[QA] Page becomes unresponsive when trying to send USDC from Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2914]
## Describe the current behavior in detail
Checked on Nelify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDIwHTB9XUhYWBCwhgAKUG9vWERUaEgGOij08wA5GycfOwt3AwBhLQL0sDSG5oBjJkJITCwjWCZoASoccnrm%2FEg8SWQugAYAD2gAITFq6ABOPFWARgBmMVWAFmnpoyMAdgBWaAAzbc2VgA4AIzFt%2Ff2ANgAmA2nNvE2Wpths1mplsp1sHMzNNHvd3qsti0vpsntt3oCxJtVgZ9nhPmsjI9pi0jGjpu9Fvt7sCQekZEEGC1oAQAG79Oq05pNTkNPBiMQCIQzWbnc5XU73T7TbbnU7mTanMybIzVR5Uoyrc7Y85Gd7bU6PEwmTXvMTvEw0nl0%2FwAB2gXSQyBwLAANtBLValCMGgBdLy0r087mctodLomIKZIb%2BzljCbsyGzd73MQLT5XabnMx4sSnU7GK6re6bK5iT6PaDbT7vd47Q4tVafJsmBYe2lgnLCz4mU7bbbTTULe7TaH7R7bJ7TAybYnVe73fbnT643YD2FovBtkH03JM1kJ7RW7zBo98gWCPKJp77U4Z%2FGnaBShX7Fqnd54QszvktaZ8%2B54MdpX2dMXy3HlYFte1sEdZ1EDdMCQUDK0%2FW9CAkOaFDaSscREDseAGFgIwbAACQ5TkTxBUMiC6Ho%2BgGaNUO8ONJmFR4Dn%2FVYJ0%2BU4zX%2FSUTHec4djMTEJVWd59gMAD7lvR8FgMVYELpLJO0TW9tlWapzmLEwtXOBZzm2FpzhaR4sUeH5xyuFMzHRTidU%2Bao8GmJSMmQBk9zZKYwEPI9GkY5oz0FS8sChTYzGqapNmgCkxDwNMdOgZ4tlJITzgHbYTE2YwdM%2BEyXJjI8ILtB0UFg%2BDCs5dDOUwqrKvSCjWnaajsAWRlXIgZiE1CpMi02XTkXhO4FiuUkDDEAwl32MQzhnN9HlOVYTBHaZuOpeqGg7CEeurYzoF%2BKay11T5hzMKkTE%2BYzpiuASDGgB8lw1Ws7g6sAd0ZZkvLIo9Gs5IKL1Yyse325NTk%2BIxpjEATqgMOUTBlBZTjwACFjMt53hqBE4Ve60SugsrXXdDbmmq2laoDDbyYaYRvpBX70io7b3DgoJN2JpjWZY7ASlgbNEAMAApJhsmI6A8AANQsYjIH8Jh4EeTgijMIp3mEXgFhtYjUGIhYbCRXMWSsABpV6tq6e5znFhYTAARQALWqVYbDt1ArjwG1YAWYQACsWQseBTgATUeO3vf8JdbJwb3YE4ABxb2CJtswcBt033N3T6DwC49s%2FSf6hW5mxebwfmhZFsXJel2X5cV5XVfVzXtd1%2FXTkNk32dBSDSqdQmccUDuwCp2kAEcqEQdRvKwIph7NAANYezHuKxHgYaoqFj%2B4fCsYRhCoTg4XOIpxfeb2HE2HxHln6AjdmHFiONwXXNJhp6e8RmaN6fpoEGV6usnuYfxgwWOFIwNw0TQHGtALUo5xIIlAfsaA9wIzagOGdda2czaJgWNdCMw4jjzgpLKEwcJ%2BRLgkmxbS5ZPgiRko8csWw04eUzt5XyP1c7eHziFOYBhHiin2I2XMWIpybEeHgIw9wIqPAhhpTYdx9ikjOMBUGxI%2B4QGKlBLAMFe4DzQgPIeDRn4NWzu%2FbAZhkCPAIDIH%2BA8%2F7CkMn2MQI4Wi2VxIuEc%2FJzTQB7BjDGOwLg9mrNUBYVJ9imxUttOY2Cbp4DwdMAhUC5QkLEGQscmpJR0JoQaehQIB7vU8lnPy%2FlCkQE4cKacMSzALHhPtVaNZEGIy2P8fS1QbxCX2JsQyZh0qLjwO8VRb0u74x7nBIm7DDG%2BnZuMiAr8IAmKwE4D2BAcAEAYAxI8tjEx%2FH2FlPAi1rqfEylcNieZPjiXRFU%2BGppqhmm0tKbY0AdhhPBMKKJuCjhxLhAk4hppknVlSZQjJYhaHZMYRnfcLD2EzN5PyYKwpVgWSeAaJcpxqhnRir2e4LR5LxShkJaoTYPjvAuO8aYvYxD9PUd3cqozClTO8Po9IdKoVzIWHgBgNKrQbJ6vY1cZhnESQAulESZoTBeLfAYXx%2BpzgBPeEEkJTzVI9VeTE958SiFJJSRQ9J1CgVZLYjkjB6cPrgtpkGdhJSYUA0TOUiRVTVg1OrBSe4DS%2FgdIWC0i4mx2mdO6ecXpFLBmaIJiMvudKIAMu8OM%2FR1UFAAEovC1SoOyhw0AxCCAILwCEVjwiUC2qvRAkArgZvyOkfChESIrxaCWho2R%2FAOgIkRYilatwMH8DgR4cF63luIlucYsB9zVGattNqLQtxbTYGIatTUwytXahtUpiZdqXAOsuI6XxTrnUuulG6GN7pQPBuJWR1QtzPwIC0AtXQmDxBtHkAA9Letl7LYAMF0OeogkgWioEQK%2BxAOBb1vtyLepZ8YGC3pRPcV4t6CJBDisgMQt6y2Nt0DaSAvAtwAdjtAT9iAJ0OncjaO0YgAC0BE4BMHQ3BFAXQADE2wzBmEyhaSqaaWjAZdJeFEMZqrCAYCzcYU7vC1q6DxvjbN6itvbZ27Awhe14H7WyQdM6sDMxdKzMd4TcNFMokOroKm1PzstQXLAFsra2wdk7F2bsPZe19v7IOIcw4R3eFHGO8dE7J1TpVU957tpXtgDe9A97H1wBfQBj9X6f1%2FoA6B4DkhQMyjiacKDsAYN4Dgwh39yBCZ2BdHwXCVwqAuhdHYc9uXkB2GQLwR4dgpRHBtLMOwYMCMEDsEct874WgWzwMh1DAB%2BBUcTkz3E1KEyqGGsNfs00G4ZFV6gsbY5ed4XGYzCDI1%2FQYAmIBCek2t%2BiLa20dpdMJ2T8noCKZat0T%2Be3KrjsnVp6dF3aLrbWSCBdSqcEqvwZ89VPzNVpKoZkuh%2BqT2VTPRe7AfmAtBaECFn976JvfvPVFxARAYv4Di7ehLMlkupfS0gHAWWRk5by61wrxXSsoAq1Vmr7z6uNc%2BM11rC0ax4E636nrvB%2BunEG%2FOEbFGiCYew1NrRIbmNYYW5gTjURuNpYsVYnAm2wDbawMIWXljZAvfSBJw7x3Kp9oHTp0x5j1fWPqLdxXszDdYDMXLjXCE3uRI%2B7EtViTft%2FK1QD3VQOGFedBz5y91670Pph8%2BuHqGEeRf%2FSjwDsXBCY%2FStj6DkBYPwfx4Tt0xPeD5bJyVyj5XKvVdq9MOnTWbQtbayztn3WUOc4G3CXn5xRv1HG0Lu703qVbnm%2Fgdjkv7jLaiMIRAizlmrMV8rwfw%2BVma%2B8NrqTKuTsG6Uws%2FtI%2Fp9qI03d36czl9LKn%2FbwzXDZjKud9913pD3f%2FcBcC4Hvv6hg984HwLwen2hej%2BFxHv6o%2Bo6A%2BjuPWOktJ4p4ZYE7Za5ZZ6k5Fa55lZU6F604Nal7l7M4dZdYc5c487DaN786QCC6TZt4i6zbNBd54A95gBS6MoraiLspj7QB1rSaUEcpa4HZz4yZ65yaL4XasrsrqbgiaZb5W6cEMHQrnhGaO7RIn6EJn6%2FLkKX46rX4%2B71Debg5YCQ5B7Bah5hYR5I5f4x6%2F7xYJ4AEpbJ5pap6ZagEk4FaQEU757U5F4l4M5l5M7tas4oE15oH14YFN6tDR44E4Z4HBoEENBEEkFkGRpeBegKAADcIAQAA%3D%3D%3D). 

Steps:
1. Prepare to send 1 [USDC](https://suiscan.xyz/mainnet/coin/0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN/txs) from Sui (Sui wallet) to Arbitrum (MetaMask)
2. Enter Amount, 1
3. Click on "max"

Actual result: Page becomes unresponsive. 
Expected result: Amount is changed. 

## Notes/ Attachments

```
Error: Chain Sui not supported
    at toMayanChainName (main-guAtXusV.js:352:470468)
    at fetchTokensForChain (main-guAtXusV.js:352:470915)
    at MayanRoute.supportedSourceTokens (main-guAtXusV.js:352:473756)
    at SDKv2Route.supportedSourceTokens (main-guAtXusV.js:319:68172)
    at async main-guAtXusV.js:321:204306
    at async Promise.all (/index 5)
    at async RouteOperator.allSupportedSourceTokens (main-guAtXusV.js:321:204259)
    at async main-guAtXusV.js:326:35544
```

```
Error when checking route is supported: Error: No protocols registered for Sui:PorticoBridge. This may be because the platform specific protocol implementation is not registered (by installing and importing it) or no implementation exists for this platform
    at getProtocolInitializer (main-guAtXusV.js:286:142508)
    at Q.getProtocolInitializer (main-guAtXusV.js:286:148492)
    at gn.getProtocol (main-guAtXusV.js:286:249906)
    at async f0.supportedSourceTokens (main-guAtXusV.js:291:50082)
    at async SDKv2Route.isRouteSupported (main-guAtXusV.js:319:67605)
    at async main-guAtXusV.js:326:34148
    at async Promise.all (/index 4)
    at async main-guAtXusV.js:326:34088 AutomaticPortico
```

![image](https://github.com/user-attachments/assets/19239f8c-b7de-41b4-a301-2b6884cfcfe3)

https://github.com/user-attachments/assets/d86591bd-4ebc-4c7a-9e45-84a4a9d66ed1

**Comment by agodlevska** [comment]
Issue reproducible on https://wormhole-connect-mainnet.netlify.app/, when sending WSOL from BSC (MetaMask) to Solana (Phantom), clicking on "max".

Attachment:
<img width="1440" alt="Screenshot 2024-11-04 at 19 52 56" src="https://github.com/user-attachments/assets/c1f734c9-a295-4c8f-b5ce-b32ff636e548">

**Comment by kev1n-peters** [comment]
Should be fixed by https://github.com/wormhole-foundation/wormhole-connect/issues/2915

**Comment by tsadovska** [comment]
Issue is no longer reproducible https://wormhole-connect-mainnet.netlify.app/.
