### ISSUE TITLE
[QA] Incorrect amounts are displayed on Transaction history page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2980]
## Describe the current behavior in detail
Reproducible on https://preview.portalbridge.com/0a16bf3ef2/.

Steps:
1. Prepare to send 0.0001 W from Base (MetaMask) to Solana (Phantom)
2. Select NTT Manual route
3. Click on "Review transaction" button
4. Click on "Confirm transaction" button
5. Open Transaction history page and check amounts

Actual result: Incorrect sending and receiving amounts are displayed, 0.000001 W.
Expected result: Correct sending and receiving amounts are displayed, 0.0001 W. 

## Notes/ Attachments

Link to [Wormholescan](https://wormholescan.io/#/tx/0x9fd70f0367cc4fe707a1d462727f4416bda7c1116e304a07ddcd688af5877b91).

https://github.com/user-attachments/assets/05e86c26-dab3-47dc-aa39-55c63592e1b4

Issue is reproducible only when sending tokens with NTT Manual route. 

![image](https://github.com/user-attachments/assets/5474fa7d-e378-4461-9d5e-d10093cc6f03)

**Comment by agodlevska** [comment]
Issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGVlEMAFk8ATzxIB0Q1aDJfAKCQsJ8AYRtOCL9A4ND1d2E2ExsvPX1IWFgY9QYAClBvb1hEVGhIBjodKrBzADkbJx87C3cDOK1mlrBK4ZaAYyZCSEwsI1gmaAEqHHIhsfxIPElkWYAGAA9oACExOOgATjwLgEYAZjELgBY9vaMjAHYAVmgAMzubucABwAIzEdyeTwAbAAmAx7G54G7jG5rMYtGp1GbYQ5mPYgoFQi63cawm6gu5QlFiG4XAxPPAwy5GEF7cZGSl7KEnJ5AtHo6rIIIMcbQAgANyWgwFLVGMqqeDEYgEQn2By%2BX1%2BHyBML2dy%2BH3MNw%2BZhuRjiIN5RguXzpXyMULuHxBJhMNqhYihJn58uq%2FgADtBZkhkDgWAAbaA%2B%2BVKdbDAC6eTGsZlcoFk2msxMQRqqyT6M22ylOIOUKBYmOMN%2Bey%2BZkZYg%2BH2MvwuQJuvzEMJB0DuMKhUPuL3GFxho5Mx2j6Mx9TVMJMHzudz2NuOQL2eKeILuoL2BhubLiQKBTy%2BMIZD2XBMpeEnYxkwtFEuL2l9EDTvsVysEjRLoKeH2rJkPmgXVjSecYPihPAW33RVxj2RUgTwTc9SeKtwNvGVYADINsBDMNEEjTDk3zMZEzjbwUzI0iICscREDseAGFgIwbAACWlAV3zGDMiFmeZFmWPMKKqQsdjVEFniQi5txhD5PSQnUTChL57jMGltQuKEngMZCgQAkDjgMC5iKqadsSwQ4ALuC44i%2BNsTFtL5ji%2BO5xi%2BcYQVpEF4S3X5yzMKkZPtGE4jwPZTMFB8xUlXYwBfV9uJlT8VR%2FSyDlNMw4jiG5oG5MQ8ErBzoDBW4OVUr5lzuEwbmMByYQ8iKaIFbDA2DFACKI5rhiomVyJlXqxiSiYpj47BjhFSKIDE4t0qJByvjJIlAWOX4OQMMQDFPJ4xE%2BfdIJBD4LhMdc9jkvluuqWoZxLPt3OgBFts7B0YTXMxeRMGF3L2X5lIMaBgNPa0B0BKawHvBpH1izjfWG9EUu%2FCSe3nB6yw%2BGEjD2MRlLiAxDRMfVjg%2BPBkOOLzIShfpiUJMGzJw9rQwjKNLqqQb0X6gU2e8DnhmEGGhpE7xeIs9xCKCG8WbAGa4qwDpYDrRADAAKSYOo2OgPAADULDYyB%2FCYeAQU4NozDaKFhF4Y5%2FTY1A2OOGxSQbcUrAAaTB8zZiBL5NeOEwAEUAC04guGwA9QX48H9WBjmEAArcULHgD4AE0QQD2P%2FFPQKcFj2BOAAcVj5i%2FbMHA%2FfdoVIZi59BaqOGxgR1VsDlhXldV6B1a1nW9YNo2TbNi2rZtu2HY9D5nbdyW6bavCOqZ2nFElnmBQARyoRB1BltoV89AANFezCBKwQQYOIqHzoEfCsYRhCoThCS%2BNpNahWOHBuHwQV36AXYOek2Nd5WkUuZ11rmAYW%2FEFhLGgCsMG0s1TwXRscG4ZgjD%2FEpNADa0BbQbi0sSVBTxoBAmzHaZ470LqgI9iWY4P1sxrleEebkBoTCEiVKebSkl7JdhhOpfSIIuy3ArtFJ8cUEqw1AQqJUqU1QGBBBqJ4I4Gy0l3DcEEeAjBAiyiCTGNkbiAieByT4aE0ZsgXhAVquEsD4XnlPReoDl49UuvXCA4DsBmGQCCAgMgYGSzgSWVyi4xDrnGIFBkJ51xKi9NAeclNKb3G%2BPOPscRji8ieO7a6FlDjUN%2BngOhewGFYMNCwsQbDNw2h1Hwnhzp%2BGoklhDEU1cRHiJGE0iAjc0qHD3DkswxwiQPTOv2QhRNbhImcnEf8qkng3FcmYSqJ48BQlMeDems9GaEWZk04BLR7EtE2W%2BUBLisBOCjgQHABAGDCV9L49KiIng1TwEdH6MJqq%2FEko2GEWkqQ9IJh6OInp7J6juNAe4aSsRqiybQ14eTCQFOYR6YpfZSmcIqWIXh1TBFV2EfzVMLSwBtLVBcHyoJnSng%2BHEd6eUFxAnGEZQq2NVJxFHNCKE3woR7AXGIRZ5iGadXWa%2BWxvptms0cfs0aFljh4AYLy%2BUVzDj%2BIvGYYJ2lkKVXUp6EwUTIIGFiU6L4CSoRJJSSCm66VwU5MhfkphRSSkcPKdwlFVTJI1IoZXepmL4pNKcS0PFJZOkaJ6RcPpfZuRAiGYiKZxwxnfBuJM6ZsyvjzM5csyxc81kL12dzS6mztmDQUAASi8BzKgkqHDQDEIIAgvBsRePCJQcyp9ECQF%2BBWpoVQmIsXYifcYLaWh1H8MGZirE2KdtvAwfwOAQSEX7e2tit4tiwCfHEUVswJrjFvOZNgYhu3DAOSu4i3r0p3R%2BI9M8z1YRvQ%2Bl9Sqv1KYAywRjLSui4i3i5gQcYDbZhMCKP6RoAB6H9ErJWwAYLoN9RBJDjFQIgEDiAcA%2FtAw0H9JyiwMB%2FeSIEEIf3MSCAVZAYgf1tsHbof0kBeC3ng%2FnaAEHEAbuDEKf0gYxAAFpmJwCYGRwiKBZgAGI7hmDMNVb0pEy3jCQ%2BGH85IkyDWEAwMWWwt3eF7bMaTsmJbrFHeOyd2BhCzrwPOyUi7MzYFFuGcWa70k0eaeiA5xnTPNX3V7H2%2Fsg4hzDhHKOMd46JxTmnDOWcoQ5zzoXYupdy6kRfW%2Biyn7YDfvQH%2BgDcBgPwfA5B6DsH4MoaQ5IFD%2Bo8kfEw7AbDeBcP4Zg8gJmdhwx8AYr8Kg4Zwx2DfZV5AdhkC8BBHYXUrx%2FQHDsOjejBA7AvMglBcYXs8BEZIwAfmNHkssQIbSpNIuRyjkGLPJtWV1dYwnRM%2FihJJpMwhWNQJWPJiAimtNHaEiOsdE7wxKZ03p6ABmxpzEgVd0i67N2WZ4ku7AAljsXIbpIxGVCaFmvodCy1cLrVlK4ZUvhjrn2kVfe%2B7AUWYtxaEAl6DYGVtQbfWlxARAMv4Cyz%2BnL%2Bl8uFeK0gHAZW1kVaq4N2r9XGsoBa21jrkLuu9ZhP1wbh1%2Bx4FG%2FGibvBpsfFm0eBb7GiAUao2tqxqahOUZ25gCTzQpNFY8V4nAp2wDnawMIbXnjZCA6qOp2793SJzoXb9rAbiddm7M1iCzw0DmO9N94ii%2B7Mlg9yRawp0OEU2rh%2FahHAiwvI4ix%2Br9v7%2F1Y6AzjkjePUtwaJwhzLghyeVUp1hyAOG8O0%2Fp5GRnvBqss4axx5rrX2udb2Dzvr%2FoBtDaFyL8bxHxczcJNLr4i31jLYV199bPLbzbfwGJ9XQJ9vNGEIgY5pzzn68N3PhfZzzfeEt5po3D27eGcOWv85Lv6hu4ogco587F8b4kV%2BJuJr%2Ffmsh0H1hIfYfItRYjqP6wUeRbj7FhPgGiWGeyW%2BOMG6exOiGpO2eFOeW%2BeheJWdO5WlW5ezOdWVeTWHOde3OPWTeLeguI2Y2YuEuUu82fesukA8uq2w%2BSum2ww4%2BeAk%2BYAGuQqs%2Bqikqy%2B0AfaWmbBUqFuN22%2B2mNuume%2BL24qkqx%2BkAp%2BVm9uYhvBXqwOd%2Bfu2SAeT%2BsKL%2B7Cb%2BdqH%2Bke6w4WqOWA6O8e8WSeSWqeBO4BmeUB2WuesBBWBeRWRepWSBTONWaBbONenO9ejefOzeAuw2wuhBnexBPepB%2Fe26GelB1G1BKatBLQ9BjBzBlEXgsYCgAA3EAA), when sending 0.00011 W from Optimism (Coinbase) to Solana (Solfalre) via NTT Manual route. 

Attachments:
<img width="604" alt="Screenshot 2024-11-21 at 11 12 46" src="https://github.com/user-attachments/assets/e92cd2a5-7f52-46e3-bc9c-1e94604f8217">

<img width="461" alt="Screenshot 2024-11-21 at 11 12 54" src="https://github.com/user-attachments/assets/6426a148-4c0c-47e5-bdb5-ab2c80c548e0">

**Comment by agodlevska** [comment]
Issue reproducible on https://deploy-preview-3009--wormhole-connect-mainnet.netlify.app/, when sending 0.01 W from Arbitrum (Rabby) to Solana (Solfalre) via NTT Automatic route.

Attachments:
<img width="471" alt="Screenshot 2024-11-26 at 10 56 20" src="https://github.com/user-attachments/assets/4566d458-6077-44f6-9a74-8cf7ce323b25">
<img width="703" alt="Screenshot 2024-11-26 at 10 56 25" src="https://github.com/user-attachments/assets/8a2656fd-eb7f-4166-acf1-c5952b33ed08">

**Comment by emreboga** [comment]
The root cause of this problem is the amount decimals used in the response from Explorer API. When we are parsing the results from `api/v1/operations` endpoint, we use a fix decimals of 8. However, for NTT transactions to Solana, it's 6 decimals.
For instance these two transactions are sending W from Arbitrum and Base to Solana.
From Arbitrum:
https://wormholescan.io/#/tx/0x065831adabaeb9169c65954319412e7a531496d2f46fcf6e965cadfe88e9855b
From Base:
https://wormholescan.io/#/tx/0x2454a12865d0f4382f346636a97c20a8e5ec386add28a37fffc5492924ec7be1

In reverse transactions (W from Solana to others) the number of decimals is 8, such as this one:
https://wormholescan.io/#/tx/5zzHc7DcuvL87pfnwHToX3wwW4BtAXTubHRaAtgDbqio2GLaS4HMmT8oNCaKkA4vqcBxn2dMJ2dcnn8kNQgWmBQL?view=overview

I'll reach out to Explorer team to follow up on this issue.

**Comment by SergejsBeikulis** [comment]
Issue reproducible on [https://preview.portalbridge.com/f37b52e933/](https://preview.portalbridge.com/f37b52e933/) when sending 0.019 SOL from Solana (Backpack) to Polygon (Phantom) via Mayan Swift Route.
[Mayan Explorer link](https://explorer.mayan.finance/swap/4GfDukvEcjDSYLbcK9Jioo4Aife6xsDm2nr6Bizs652ZtSG7ChA8wj3H64bcDZ5rWYyGoN5PGdsGmWHXkhinAjN7)
<img width="632" alt="Sol" src="https://github.com/user-attachments/assets/7304a6d9-ecbe-416e-ae6b-9466c96b9e84">
<img width="581" alt="sol2" src="https://github.com/user-attachments/assets/fb19ae85-8b14-4a21-a284-d21134416bfb">
