### ISSUE TITLE
[QA] Balance is not loading for Kaia

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2993]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/.
Tested OK on https://portalbridge.com/. 

Steps:
1. Select Kaia network
2. Connect MetaMask wallet
3. Check if tokens are displayed in the list

Actual result: Balance is not loading for Kaia.
Expected result: Balance is loaded.

## Notes/ Attachments

```
Failed to get token balances Error: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0x70a082310000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012", "to": "0x608792Deb376CCE1c9FA4D0E6B7b44f507CfFa6A" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.3)
    at makeError (main-UfxkFj4J.js:281:68250)
    at getBuiltinCallException (main-UfxkFj4J.js:282:107247)
    at hu.getBuiltinCallException (main-UfxkFj4J.js:282:108201)
    at Uu.getRpcError (main-UfxkFj4J.js:282:211418)
    at main-UfxkFj4J.js:282:215353
```

Netlify

![image](https://github.com/user-attachments/assets/6967a041-2c39-434a-92ad-cea3960af4be)

Portal Bridge

![image](https://github.com/user-attachments/assets/1a61dddd-6ee4-4386-b537-971abca19762)

**Comment by agodlevska** [comment]
Note: when changing networks with assets, tokens are loaded correctly. However, after reloading the page, everything resets, and the tokens are no longer displayed. 

Attachment:

https://github.com/user-attachments/assets/ec735ebc-8e62-4361-b6e0-75dbca98bd62

**Comment by emreboga** [comment]
@tsadovska This is a similar issue with a free RPC endpoint on Netlify deployments. It errors when request too many token balances. When I overwrite it with a paid service in my localhost, it works fine. I think we can close this as "won't fix".
<img width="760" alt="Screenshot 2024-12-03 at 3 18 38 PM" src="https://github.com/user-attachments/assets/63463650-c6e9-49ce-843c-bf05c650f1b4">

**Comment by tsadovska** [comment]
Rechecked on Dec 5 that token balances for Kaia are successfully displayed on https://portalbridge.com/. 
Closing the ticket based on the [comment above](https://github.com/wormhole-foundation/wormhole-connect/issues/2993#issuecomment-2514413969).
