### ISSUE TITLE
[QA] Amount entered starting with 0.**** or 0 is automatically removed

### ISSUE THREAD

**Issue by SergejsBeikulis** [wormhole-foundation/wormhole-connect#3011]
OS: Sequoia 15.1.1
Browser: Version 131.0.6778.86 (Official Build) (arm64)
Build: [https://deploy-preview-3009--wormhole-connect-mainnet.netlify.app/](https://deploy-preview-3009--wormhole-connect-mainnet.netlify.app/)
## Describe the current behavior in detail
Steps to repro:
1. Select any network, asset and wallet
2. enter amount 0.*** or 0 and wait 1 sec
3. Observe the result
## What is the expected/desired behavior
Expected result: Entered amount is not removed.
Actual result: Entered amount is automatically removed.

Additional comment: If user enters valid amount for example 0.0001 or selects amount from "suggested" than the amount is not removed. Also any amount that starts with 1 and above is not removed.

https://github.com/user-attachments/assets/b5739b03-bcfb-4935-aaba-2169a64f1245

**Comment by agodlevska** [comment]
Issue reproducible on https://wormhole-connect-mainnet.netlify.app/ with the scenario described above.
No issues on https://portalbridge.com/. 

Attachment:

https://github.com/user-attachments/assets/f376d045-2659-41c2-84b2-5b6f4276768a

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ . No issues on https://portalbridge.com/.



https://github.com/user-attachments/assets/50862a05-b283-4be1-bc8c-1b542cc09c50

Closing the ticket.
