### ISSUE TITLE
[QA] An unexpected error occurs after opening "Transaction history" page for accounts that made WorldChain transactions

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3069]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://preview.portalbridge.com/079ceedd85/. 

Steps:
1. Select EVM chain (for example, Ethereum or Arbitrum)
2. Connect MetaMask wallet
3. Open "Transaction history" page

Actual result: An unexpected error occurs. 

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at main-BIr0P3eQ.js:286:2279
    at Array.reduce (<anonymous>)
    at tt (main-BIr0P3eQ.js:286:2254)
    at main-BIr0P3eQ.js:352:6234
    at main-BIr0P3eQ.js:352:7119
    at main-BIr0P3eQ.js:352:8534
    at Array.map (<anonymous>)
    at main-BIr0P3eQ.js:352:8298
    at main-BIr0P3eQ.js:352:8947
    at Vh (main-BIr0P3eQ.js:39:19555) 
```

Expected result: Transaction history page successfully opens. 

## Notes/ Attachments
Issue is reproducible with following accounts (I made transfers to/ from **WorldChain** with these account):

- MetaMask account: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
- Solana account: 4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU

Issue is not reproducible with following accounts:

- MetaMask account: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
- Solana account: 7yEFBzgwqBHmEtPLvKcQgzPTpfcnrScAfrvenvnBJA5n

https://github.com/user-attachments/assets/52f0dd25-3cfa-454d-9bb4-8cc7317c7489

Issue is also reproducible in Incognito mode. 

https://github.com/user-attachments/assets/f1b66669-b47d-4f0d-9442-46d6d4dd70f1

**Comment by marilance** [comment]
Hi there, @tsadovska 
Thanks for reaching out, I noticed you’re experiencing a transcript error and I’ve tried to reproduce your issue but it didn't work. It seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [Workhole-Foundation Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by LiveSupport-debug** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WL240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
