### ISSUE TITLE
[QA] Unable to connect TrustWallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3081]
## Describe the current behavior in detail
Reproducible on https://deploy-preview-3065--wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Aptos network as source chain
2. Click on "Connect source wallet" button
3. Select TrustWallet

Actual result: Wallet is not connected. 

Error in Console:
`Uncaught (in promise) TrustWallet Address Info Error`

Expected result: Wallet is successfully connected.

## Notes/ Attachments

https://github.com/user-attachments/assets/e38f3375-fb8e-45be-82ed-0e372e73cb9e

**Comment by MittyLance** [comment]
We Apologize for any inconvenience this may have caused you. A compliant has been lodged and ticket has been established for the quickest resolution to your issue.
Ticket ID : #TW46365
Visit the official support website to initiate a chat with the support team via [Wormhole Foundation Live Support Desk](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by Derick949** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by tsadovska** [comment]
Trust wallet is no longer displayed in the list on https://deploy-preview-3065--wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/. 

![image](https://github.com/user-attachments/assets/e68394f3-0314-487a-9b53-d30c645d7850)


Closing the ticket.
