### ISSUE TITLE
[QA] Unable to claim transaction using Bitget wallet

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3086]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0.1
- Wallets: Bitget Wallet
- Browser: Google Chrome Version 131.0.6778.140 (Official Build) (x86_64)
- https://preview.portalbridge.com/7e1e7d6a3d/

Steps to Reproduce:

1. Attempt to claim a transaction of 0.001 AVAX from Avalanche to Moonbeam using Bitget Wallet
2. Observe the errors in the console

Expected Result: The transaction should be successfully claimed without any errors.

Actual Result: The transaction cannot be claimed, and errors are displayed in the console.

```
Error while manually redeeming: unknown - Error: Could not find network mapping for chain 1284
``` 
```
Error handling event: TypeError: Cannot read properties of undefined (reading 'amount')
    at validateAmount (pb-index-B-mi_hOO.js:754:475342)
    at display (pb-index-B-mi_hOO.js:754:474897)
    at whole (pb-index-B-mi_hOO.js:754:475278)
    at eventHandler (pb-index-B-mi_hOO.js:765:72756)
    at eventHandler (pb-index-B-mi_hOO.js:1192:43263)
    at Object.triggerEvent (pb-index-B-mi_hOO.js:303:125734)
    at Ho (pb-index-B-mi_hOO.js:752:183716)
    at Object.Nb (pb-index-B-mi_hOO.js:43:10508)
    at Tb (pb-index-B-mi_hOO.js:43:10677)
    at Ub (pb-index-B-mi_hOO.js:43:10743)
``` 

## Attachments/Notes
<img width="1440" alt="Screenshot 2024-12-19 at 17 29 24" src="https://github.com/user-attachments/assets/a8776c16-f34a-4196-9050-4f1e8c04f095" />

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Wormhole SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by tsadovska** [comment]
Claim transaction fails with the same error message when sending 0.00001 WAVAX from BSC (Coinbase) to Moonbeam (Coinbase). 

Issue is reproducible only on https://preview.portalbridge.com/7e1e7d6a3d/.
The same scenario completes successfully on https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/. 

After user clicks on Claim button on https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/, notification to switch network appears. Notification to switch network does not appear on https://preview.portalbridge.com/7e1e7d6a3d/.

![image](https://github.com/user-attachments/assets/f8568a54-50e1-45fa-bed4-681e3674d5e4)


Error that occurs on https://preview.portalbridge.com/7e1e7d6a3d/ after clicking on Claim button:
```
Error handling event: TypeError: Cannot read properties of undefined (reading 'amount')
    at validateAmount (pb-index-B-mi_hOO.js:754:475342)
    at display (pb-index-B-mi_hOO.js:754:474897)
    at whole (pb-index-B-mi_hOO.js:754:475278)
    at eventHandler (pb-index-B-mi_hOO.js:765:72756)
    at eventHandler (pb-index-B-mi_hOO.js:1192:43263)
    at Object.triggerEvent (pb-index-B-mi_hOO.js:303:125734)
    at Ho (pb-index-B-mi_hOO.js:752:183716)
    at Object.Nb (pb-index-B-mi_hOO.js:43:10508)
    at Tb (pb-index-B-mi_hOO.js:43:10677)
    at Ub (pb-index-B-mi_hOO.js:43:10743)
```

Attachments:

* https://preview.portalbridge.com/7e1e7d6a3d/
Link to [Wormholescan](https://wormholescan.io/#/tx/0x25f35016c84abc40cf7b62b8349f8aaacec570df008cb165767675f62472338f), tx hash: 0x25f35016c84abc40cf7b62b8349f8aaacec570df008cb165767675f62472338f


https://github.com/user-attachments/assets/db5fdd92-b9b2-4bf5-9743-273346620cd6


* https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/
Link to [Wormholescan](https://wormholescan.io/#/tx/0x416d2c06e37e269e68b6084892b06f6a19a59facaf675484c5900d3a9943d626), tx hash 0x416d2c06e37e269e68b6084892b06f6a19a59facaf675484c5900d3a9943d626


https://github.com/user-attachments/assets/042769d9-50b6-4e8a-ace0-4412ab7f607d

**Comment by agodlevska** [comment]
Issue reproducible on https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/, when sending 0.001 AVAX from Avalanche to Moonbeam using Bitget Wallet. 

When attempting to claim a transaction using the Bitget extension, a 'System error' message appears and multiple windows open. After closing all these windows, an error message is displayed in the console.

Error: 
```
Error while manually redeeming: unknown - Error: could not coalesce error (error={ "code": -32603, "message": "An internal error was received.\n\nDetails: user reject this request\nVersion: viem@2.21.51" }, payload={ "id": 8, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "chainId": "0x504", "data": "0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000040d00a30768357a19ae543470b962990167ceebe34491f937d917ea817c42e5ac83605b0fe420c9762a75c615947b06dcb1ebb765ed6908b4914084e0dc215c8c3b10000104882536898569d1a43d23420c97be56ffa2bd1cb93fc755cf8430abe7f294bf4aa728ada7f660d0e80ff968c8e7aea65a3f61e5183264b65de6922d4b666743000263efb1258078f8ead7afdac29bc687c111d5aca4ec821f95b1d5cec6a0ae88002f5f19b2f30ed85f9b4c25a3f7a3ba1ac233d4510ce0164da043d27472dcf4db0104a134c4ec8dd8f3761d49edb69229372064b07db323c2d536bdb70ac13623e7ee1b308edeb8d39411ac590d34a7bcbacb35f6c16a94b09a9936445cd3bdc418920105a94ea097c9df5ccccc29f255da6eace258dc4ec9f3ce6a8d4bbb247027bee89324f6fa1b2848e6f1241a21b5fa167629fe177dcc440ea7aff32f940c1d992ec60106787042ea05aca12f141a23b1255c50fbba102ec8729acb9487dd8dd3ad2d50cc4883b47a22d48bbca68d3c31d0859fb4fa41ca0da4403f89832d79eaf436f5b100075c3c113b840d7e0e5b67a99f0a558bfe283d6b14692e16957fd19dc2613b660311e60b3e5e3347bdf1b9a47e90ee4a03fdac761703340d723a6e49c0f955de17010869cffb2537a98fc259d9359de6538f3825db2d4588b28f619a5946364093229c2ddbf5df7fec359ff1d198025d289a6f31d49e9e7ab04e1fe705cef794917cb701093676f8d43047e1065ad92f15e32e171134377029dbb8a41a3ae32aa388b3e26b283137fddb0ff06d9e1c7f9c4f354613c00fa08fd23f65529b113729b1b133ac000a57fdf41a95411ee78ba4029800f58e5439afba4b18c1e600dc39af59d90f94372f004cceb52ffee78cdd9a8ee344218300855981ad1654f2e8dce597a8f700fa0010329064230fbb95e22968825e92d240e4234b37898e6065c3e74fb6410164856908364ed2094af2a84637cfe48c460526622dd99913e797cd65b82579e6f3b6630011b1f345f2d578eb2a12d22d967a83a47f2c989372405b11525924dd82146bf5be6c063182202f4c4725ec9f637328633b9a57383a45c46e24e4ea4ec13dd1d0090012c4122655185c05f8421a8ec1654d3898707ef9a2f2bbfe430449bf97efce38c2242b754a55b390208b70d8d2c7b66fdc060ba1b75d0d32769fa5ecf2a0374a6d0167654f170000000000060000000000000000000000000e082f06ff657d94310cb8ce8b0d9a04541d80520000000000037689010100000000000000000000000000000000000000000000000000000000000186a0000000000000000000000000b31f66aa3c1e785363f0875a1b74e27b85fd66c70006000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01001000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "gas": "0xe6183", "to": "0xb1731c586ca89a23809861c6103f0b96b3f57d92" } ] }, code=UNKNOWN_ERROR, version=6.13.3)
``` 

Attachment:

https://github.com/user-attachments/assets/95111ea1-ca99-4510-b462-f01c22003976

**Comment by agodlevska** [comment]
After reinstalling the Bitget wallet extension and creating an account by re-importing an existing wallet, the transaction was successfully claimed.

Attachment:
<img width="1440" alt="Screenshot 2024-12-20 at 14 14 18" src="https://github.com/user-attachments/assets/2f789c4e-8406-49cd-b0ed-e9d05444e97a" />

**Comment by agodlevska** [comment]
The issue is no longer reproducible. The transaction was successfully claimed on https://preview.portalbridge.com/7e1e7d6a3d/ using the Bitget wallet.

Attachment:

https://github.com/user-attachments/assets/8baec18e-6836-4736-b42b-99377c730de6

**Comment by tsadovska** [comment]
Scenario mentioned in [this comment](https://github.com/wormhole-foundation/wormhole-connect/issues/3086#issuecomment-2556430310) is also no longer reproducible on https://preview.portalbridge.com/7e1e7d6a3d/. 
Claim transaction completes successfully when sending 0.00001 WAVAX from BSC (Coinbase) to Moonbeam (Coinbase).
Notification to switch network appears after clicking on Claim button.



https://github.com/user-attachments/assets/f3db4639-4db2-4d7e-b3f1-90f6166d1e70
