### ISSUE TITLE
[QA] USDT token is not displayed in "To" section when transferring from Base to Arbitrum

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3094]
## Describe the current behavior in detail
Reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://deploy-preview-2838--wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select Base network as source chain (MetaMask wallet auto-connects)
2. Select Arbitrum network as target chain (MetaMask wallet auto-connects)
3. Select USDT token in "From" section
4. Open "To" section and check if corresponding token is displayed

Actual result: USDT token is not displayed in "To" section. However, user can click outside the pop-up and USDT token will be selected. User can successfully start USDT transfer from Base (MetaMask) to Arbitrum (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0x7bd044e582169e0413f8a7a2e4ebf8f59b8329c19cb55aa59f67965e255d8159). 

Expected result: Corresponding USDT token is displayed in the list in "To" section on Arbitrum. 

## Notes/ Attachments

https://github.com/user-attachments/assets/d2cabfe5-6f2b-4f9c-8b6a-9b1355b57c2f

**Comment by Wesleyleung** [comment]
is this still reproducible? I'm not able to

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
USDT token suggested for selection in "To" section.
Closing the ticket.
