### ISSUE TITLE
[QA][Android] Window to confirm token claim is not automatically opened, link at send to section then shows "Error please retry"

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#310]
Preconditions:
Wallets are connected

Environment: Galaxy S22+, Android v12, Chrome v110.0.5481.65

Steps:
1. Prepare to send 0.04441 BNB from BSC to Fuji
2. Nick pay with two transactions
3. Click Approve and proceed with a transaction
4. When possible click on Claim
5. On pop-up click Open with MetaMask
6. Enter the wallet password when asked
7. Observe

Actual result: The window to confirm the Claim is not automatically opening, the link to AvaScan is shown then as "Error please retry..." User can click multiple times on Claim.

Expected result: Transaction completes after user click on Claim, wallet window to Confirm this action is opened.

Comments: Wallet logs out the user after few minutes and it seems because of the part where user has to re-enter the password, the pop-up window is not opening. User then has to manually go to the MetaMask wallet and Confirm the Claim, after approximately 1min transaction completes, but link to AvaScan still does not load. Similar issue - [https://github.com/wormhole-foundation/wormhole-connect/issues/300](https://github.com/wormhole-foundation/wormhole-connect/issues/300#issue-1656822727)

Attachment:

https://user-images.githubusercontent.com/91047061/231111480-c1ccea14-5f71-4f57-ad21-f65d24b2aa96.mp4

![Screenshot_20230411-115019_Chrome](https://user-images.githubusercontent.com/91047061/231111539-cff59995-ed87-499f-85d9-2d13f0c77697.jpg)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Environment: Samsung Galaxy S22+, Chrome, Metamask v7.12.2
Comments: Pop-up to Confirm the Claim is not shown for approximately 15min, transaction is shown as loading after pressing on Claim and only after those 15min and multiple password entries for Metamask app, the Confirm transaction is shown at some moment. And the Confirm window is not automatically opened if user is located at Wormhole-connect

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4498e01a-42bd-4372-99f8-121523779716

![Screenshot_20231213-091411_Chrome](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0e7324e7-7039-4049-a295-04ce6861e637)

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1772.
Closing the ticket.
