### ISSUE TITLE
[QA][Android] User is not redirected back to Wormhole-connect after entering password for wallet app in case Network has to be switched

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#311]
Preconditions:
User has previously made a transaction from different Network (e.g. Fantom to BSC)

Environment: Galaxy S22+, Android v12, Chrome v110.0.5481.65

Steps:
1. Connect wallets
2. User wants to send 0.05541 MATIC from Mumbai to Fantom
3. Select pay with two transactions
4. Click Approve and proceed with transaction
5. On pop-up window select Open with Metamask
6. Enter Metamask wallet password
7. Click Unlock
8. Observe
9. Go back to Wormhole-connect
10. Observe
11. Refresh the page 
12. Repeat steps 1-7
13. Observe
14. Manually open Metamask wallet application
15. Click Switch Network
16. Go back to Wormhole-connect
17. Click again on Approve and proceed with transaction

Actual result: In case Network has to be switched there is an endless loading at the Bridge screen, user has to refresh the page and select all the fields again in order to go to the transaction screen or manually go to the Metamask application and check if the pop-up to switch network is shown there.

Expected result: After entering the password for Metamask application user is able to Confirm the Network switch and is redirected back to Wormhole-connect.

Attachment:

https://user-images.githubusercontent.com/91047061/231127510-6aa3b070-f54e-45c8-9c02-600a215eed35.mp4

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Environment: Galaxy S22+, Android 12
Wallets are connected through WalletConnect.
User approves transaction, but when opening wallet there is no indication that the transaction needs confirmation. Transaction is left loading and it is not moving forward.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9679b21a-aa6b-49e5-b9a6-b8c6c29d4e09

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1772
Closing the ticket.
