### ISSUE TITLE
[QA] Link “Add CELO to your wallet” should not be displayed in “Transaction complete” section when user receives native asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#316]
#### Steps:
1. Connect Metamask wallets in ‘From’ and ‘To’ sections
2. Prepare to send 0.08 CELO from Mumbai to Alfajores
3. Select “Pay with 1 transaction” in “Gas payment” section
4. Wait until transaction is completed
5. Observe  “Transaction complete” section

#### Actual result:
Link “Add CELO to your wallet” is displayed.

#### Expected result:
Link “Add CELO to your wallet” should not be displayed.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome version 111.0.5563.64 (Official Build) (x86_64)

#### Notes:
* Task: https://github.com/wormhole-foundation/wormhole-connect/issues/164
* Release: https://github.com/wormhole-foundation/wormhole-connect/releases/tag/v2023.04.06-alpha

####  Attachment:
![Screenshot 2023-04-11 at 16 22 09](https://user-images.githubusercontent.com/10746654/231216341-ff82d919-0df5-42cf-87f5-d4803016d3ef.png)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. LInk "Add CELO to your wallet" is displayed on Redeem screen when sending CELO to Alfajores.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d6d59573-495a-4141-9384-120c35fe1d6b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. LInk "Add CELO to your wallet" is displayed on Redeem screen when sending CELO to Alfajores.
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x1561d4e4595eb12d9fad2ac0b43f278a945d660e7d57bb462d5214c86790eda0)
* Send to tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0x1a59c7508a0f1eb888d02b980aa2d439e0c1d68b3c688a88be553e0e1cbe1b9f)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f860aa11-ef91-42b9-aa8d-18f2d28bd346)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
![Screenshot 2023-12-20 at 16 17 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5edfd0eb-aef8-4c79-b9ce-26ce9c819b4f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] when sending 0.00002 CELO from BSC (Metamask) to Celo (Metamask). Link "Add CELO to your wallet" is shown on Bridge screen.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) and https://portalbridge.com/. 
Ticket is closed.
