### ISSUE TITLE
[QA] MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#317]
Preconditions: 
1. Wallets are connected
2. Console is opened

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.01 WAVAX from BSC to Fuji
2. Click Approve and proceed with transaction
3. Observe

Actual result: "MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration" is shown in the Console and user can not continue with the transfer.

Expected result: User is moved to the next screen and transaction is complete.

The same behaviour also observed for these transactions:
WSOL - Fuji to Mumbai
WSOL - BSC to Fuji
WSOL - Alfajores to Fantom
WAVAX - BSC to Fuji
GLMR - Moonbase to Mumbai
GLMR - Moonbase to Alfajores
BNB - BSC to Fuji

Attachment:

https://user-images.githubusercontent.com/91047061/231363891-6c9fe2cc-a04e-4f40-ae34-f52fc807e3eb.mov

<img width="1311" alt="Screenshot 2023-04-12 at 10 42 36" src="https://user-images.githubusercontent.com/91047061/231387715-21c059f2-fd35-4978-a21f-0865a93f46aa.png">

<img width="1328" alt="Screenshot 2023-04-12 at 09 01 48" src="https://user-images.githubusercontent.com/91047061/231365104-fd87dacf-5884-4c22-86ad-06d765ac2273.png">

<img width="1322" alt="Screenshot 2023-04-12 at 09 33 54" src="https://user-images.githubusercontent.com/91047061/231371148-fb37bee2-deae-4e2c-8229-dd6376327678.png">

**Comment by tsadovska** [comment]
Closing the ticket, issue is no longer reproducible.
* Send WAVAX from BSC to Fuji ( [BSC](https://testnet.bscscan.com/tx/0xf8fa6b263fdced5148c3171e34901355f45e8aacaf4501c9b55a17df027e1e86), [Fuji](https://testnet.snowtrace.io/tx/0x9189706bcb001c4f333e365a9cba09450cb04f9debc367107a7182b41aa222f4) )
* Send WSOL from Fuji to Mumbai ( [Fuji](https://testnet.snowtrace.io/tx/0xe5550e19b504c1ca3210d6ccce615fa9f985f6ccde8ab583c9d1fd1dd09590e5), [Mumbai](https://mumbai.polygonscan.com/tx/0x8585183e4b3c0492b4b7c0df94b0942295713ea00b5dcc14f6a17f3b20370305) )
* Send WSOL from BSC to Fuji ( [BSC](https://testnet.bscscan.com/tx/0x46fc418b1df2896e451e9b66bcbbf851ab2ad2282a1515a8eea3cfe08b2af43a), [Fuji](https://testnet.snowtrace.io/tx/0x299ef941caaa15476e477535ff8a66952e97e6fff6297d91183c131767b802a5) )
* Send WSOL from Alfajores to Fantom ( [Alfajores](https://explorer.celo.org/alfajores/tx/0x86313456518048f3580aa5bd172a03d68eae2d17725c902ca38e463079fa77f3), [Fantom](https://testnet.ftmscan.com/tx/0xaeaa740ebb37076b91088d87f076bceff09f08850853199c8f29141d13fcd620) )
* Send WAVAX from BSC to Fuji ( [BSC](https://testnet.bscscan.com/tx/0xdff90da0222374d5f7fcee1ea9f182dede45bbcbdde46968a8ee04268458695e), [Fuji](https://testnet.snowtrace.io/tx/0xe234ad3c3f2b4d308180c363a9252d239e436d7e81f9221033803d84e36f4844) )
* Send GLMR from Moonbase to Mumbai ( [Moonbase](https://moonbase.moonscan.io/tx/0xd1d6d364a51d7345d799dba61beb9afe1386e90c143097237d9116b824d5d3e1 ), [Mumbai](https://mumbai.polygonscan.com/tx/0x15cd9e66255094965b3ac56edad5e48a6ca5b5516a8cf84c671702c39165532d) )
* Send WGLMR from Moonbase to Alfajores ( [Moonbase](https://moonbase.moonscan.io/tx/0x44335b5d4e9d2d74bff4a5d57ccdf7bb509bbca11f3fd4b69c5255cfd394062a), [Alfajores](https://explorer.celo.org/alfajores/tx/0x4846af95e360bbd406aceded11e16780817ac784ca2701bbde5d94f8361ee1f3) )
* Send BNB from BSC to Fuji ( [BSC](https://testnet.bscscan.com/tx/0x92b6786ec153cd2a68e57b54004aa3bdf30367da64b3027dd9f1ff3735d02242), [Fuji](https://testnet.snowtrace.io/tx/0x7813296435329dac4601512b6bed9081a6a04594119c599451f6364c4b927ed3) )
