### ISSUE TITLE
[QA] Both wallets are disconnected when user connects the same wallet in Sending ‘From’ and Sending ‘To’ section and disconnects any of them

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#322]
#### Scenario 1: 
Steps:
1. Connect the same Metamask/ Zerion wallet in Sending 'From' and Sending 'To' sections
2. Disconnect Sending ‘From’ wallet

Actual result: Both wallets are disconnected.

Expected result:
* Sending ‘From’ wallet is disconnected 
* Sending ‘To’ wallet is connected

#### Scenario 2: 
Steps:
1. Connect the same Metamask/ Zerion wallet in Sending 'From' and Sending 'To' sections
2. Disconnect Sending ‘To’ wallet

Actual result: Both wallets are disconnected.

Expected result:
* Sending ‘To’ wallet is disconnected
* Sending ‘From’ wallet is connected

Note:
Linked #324 

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome version 112.0.5615.49 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/231465640-3fe20a6d-4a70-4e2a-a24c-212df66bf935.mov

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when user connects the same Metamask wallets.

**Comment by AigaD** [comment]
Issue still reproducible.
Both sections are disconnected if the same wallet is connected and user decides to disconnect wallet from one section.
Tested from: https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2aaf8792-7793-43c6-8c3d-7fac026a6a35

**Comment by tsadovska** [comment]
Issue is still reproducible on:
- https://wormhole-connect.netlify.app/ [Testnet]
- https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

**Comment by AigaD** [comment]
Issue is reproducible from: https://preview.portalbridge.com/7102d8ccad/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09dd6999-2c36-42c6-9aeb-8d2559b8ee08

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c196c30-30a6-47ab-95b9-a992e0323560

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/
Both Metamask wallets are disconnected if user disconnects one of them
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5d993763-27e4-48c5-bc78-424e3cb9ccd7

**Comment by Eiei070922** [comment]
I feel like something has taken up information on my phone.


ในวันที่ พ. 20 มี.ค. 2024 20:47 AigaD ***@***.***> เขียนว่า:

**Comment by tsadovska** [comment]
Issue is also reproducible on https://portalbridge.com/ [Mainnet] with Rabby wallet. Rabby wallet is disconnected in From section after user disconnects it in To section. 


https://github.com/user-attachments/assets/f7d78cd9-3a5a-41b1-85f5-ed1fa0a4b91f

**Comment by tsadovska** [comment]
Closing the ticket as not a bug.
