### ISSUE TITLE
[QA] Improvement: Warning message “Error sending transfer, please try again” should be hidden when user changes transaction details after rejecting the transaction 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#323]
#### Steps:
1. Connect Metamask wallet in ‘From’ section
2. Connect Phantom wallet in ‘To’ section
3. Prepare to send GLMR from Moonbase to Solana
4. Type Amount
5. Click “Approve and proceed with transaction” button
6. Click “Reject” in wallet notification to approve transaction
7. Change transaction details, for example, disconnect ‘From’ wallet or change Asset
8. Observe if warning message “Error sending transfer, please try again” is displayed

#### Actual result:
Warning message “Error sending transfer, please try again” is displayed.

#### Expected result:
Warning message “Error sending transfer, please try again” should be hidden.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.1, Chrome version 111.0.5563.64 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/231470324-81e2eb5d-9f66-4f9f-81ee-25183e15a784.mov

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]. 
Steps:
1. Connect Osmosis network in "From" section
2. Connect Fantom network in "To" section
3. Connect Leap wallet in "From" section
4. Connect Metamask wallet in "To" section
5. Prepare to send 0.1 WFTM
6. Click "Approve and proceed with transaction" button
7. Click "Reject" button on Leap wallet notification
8. Disconnect Leap wallet
9. Connect Leap wallet again (Actual result: Warning "Error sending transfer, please try again" is still displayed)
10. Change network in "From" section to Alfajores
11. Connect Metamask wallet in "From" section
12. Check if Warning message is displayed in "From" section (Actual result: Warning "Error sending transfer, please try again" is still displayed)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/433bd39c-212a-4d91-90d5-bd4b70eb6374

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet]. Error transfer warning message doesn't disappear after user rejects transfer and connects different wallet.

Steps:
1. Prepare to send 0.01 ETH from Goerli (Metamask) to Solana (Solflare)
2. Click "Approve and proceed with transaction" button
3. Click "Reject" button on Metamask notification
4. Change Solflare wallet to Phantom
5. Observe if Error sending warning is displayed


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4500f131-2c8c-428f-8660-673335be78b8

**Comment by AigaD** [comment]
Error message stays, when some informations in transaction is changed or transaction is rejected.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/185aca87-c5d3-43de-8a18-bc5cb72221a5

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with the following scenario:

1. Prepare to send 0.01 GLMR from Moonbeam (Metamask) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Reject Metamask notification
4. Change asset to USDT
5. Observe if warning message "Error with transfer, please try again" is displayed

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2).
When user rejects transaction in the wallet and then changes transaction details, warning no longer appears. 
Ticket is closed.
