### ISSUE TITLE
[QA] Improvement: Phantom and Metamask options should be hidden on Safari as they are not supported

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#332]
#### Steps:
1. Open wormhole-connect on Safari
2. Click “Connect wallet”

#### Actual result:
4 Options are displayed - Solflare, Phantom, Wallet Connect and Metamask.

#### Expected result:
Metamask and Phantom options should be hidden, because they are not supported on Safari. 

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.49 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-04-14 at 12 22 47](https://user-images.githubusercontent.com/10746654/232004669-794209e4-88ff-4a82-b421-3c795e616ee7.png)

**Comment by AigaD** [comment]
Wallets that are not supported from Safari are shown in the wallet list. Option to install them are shown.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/afec9227-19d8-4ec1-9276-d829aa0e22c9

**Comment by tsadovska** [comment]
Phantom and Metamask options are no longer displayed on Safari. Checked on https://wormhole-connect.netlify.app [Testnet]. 

Ticket is closed.
