### ISSUE TITLE
[QA] Networks are selected when user returns to Bridge screen from Resume Transaction screen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#334]
Preconditions:
1. Wormhole-connect is opened
2. TX hash of previously made transaction (e.g. - 0x18e12edd013c0750e7b1dcaea1ea5f6c6f6b70fb5a3572d4789de6b11c247c66 Fantom to BSC)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on Menu
2. Open Resume Transaction
3. Paste the provided TX hash in the Source chain transaction hash field (0x18e12edd013c0750e7b1dcaea1ea5f6c6f6b70fb5a3572d4789de6b11c247c66)
4. Select Network (e.g. Fantom) 
5. Click Search
6. Click "<" to go back to the Bridge screen
7. Observe

Actual result: The Networks that were used in the transaction and searched  in the Resume Transaction are present on the Bridge screen.

Expected result: Field are reset when returning to Bridge screen.

Attachment:

https://user-images.githubusercontent.com/91047061/232064183-d4185dd7-3e7f-4808-a3bf-cc573f564bc9.mov

**Comment by anondev2323** [comment]
Fixed by #420
