### ISSUE TITLE
[QA] Warning message to register token is not displayed if user selects Sending 'To' wallet first and then selects network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#354]
#### Steps:

1. Connect Phantom wallet in ‘From’ section
2. Select Solana network and SOL in ‘From’ section
3. Type Amount
4. Connect Metamask wallet in ‘To’ section
5. Select Moonbase network in ‘To’ section
6. Observe if a warning message to register a token is displayed
7. Click “Approve and proceed with transaction” button

#### Actual results:

- Warning message is not displayed
- Clicking on “Approve and proceed with transaction” button has no effect

#### Expected results:
Warning message “This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets.” is displayed. 

#### Note:
Issue is not reproducible if user selects Sending ‘To’ Network first and then selects wallet:
1. Connect Phantom wallet in ‘From’ section
2. Select Solana network and SOL in ‘From’ section
3. Select Moonbase network in ‘To’ section
4. Connect Metamask wallet in ‘To’ section

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Google Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/232750237-023c8216-d071-40c7-9dc4-1e85f1696b23.mov

**Comment by anondev2323** [comment]
Can you try again? Tried with both Solflare and Phantom


![Image](https://user-images.githubusercontent.com/122566365/235200440-a36a16ab-d617-490a-9327-e6c7f316a465.png)
![Image](https://user-images.githubusercontent.com/122566365/235200439-f08f627a-4430-46f9-8a4b-f74085a17e08.png)

**Comment by tsadovska** [comment]
- Issue is no longer reproducible on https://wormhole-connect.netlify.app/ with the scenario from the description, warning message is displayed correctly. 
- Issue can’t be checked on https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/, because #373 is not deployed yet. 

During checking noticed new scenario that is reproducible only on https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/

**Steps:**
1. Select SOL asset
2. Select Phantom wallet in ‘From’ section
3. Select Metamask wallet in ‘To’ section
4. Select Solana in ‘From’ section
5. Select Moonbeam in ‘To’ section
6. Type Amount, in my case 0.01
7. Click “Approve and proceed with transaction” button

**Actual result:**
* Warning message to register token is not displayed.
*  “Error sending transfer, please try again” is displayed for the user

**Expected result:**
Warning message “This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets.” is displayed.

**Attachment:**

https://user-images.githubusercontent.com/10746654/235217420-af310664-9e00-47e4-a94f-5605953ff2a2.mov

**Comment by anondev2323** [comment]
Ok, will have you re-check once the next mainnet deploy is out.  Solana RPC on mainnet was bad, which would explain this

**Comment by aadam-10** [comment]
the issue is with the solana public rpc, integrators should replace that
