### ISSUE TITLE
[QA] [Android] Sending 'To' wallet disconnects when user taps Back button in Solflare notification while creating token account 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#360]
#### Steps:

1. Connect Wallet Connect wallet in 'From' section
2. Connect Solflare wallet in 'To' section
3. Prepare to send MATIC from Mumbai to Solana
4. Click “Create account” link in warning notification “No associated token account exists for your wallet on Solana. You must create it before proceeding.”
5. Tap Back button in Solflare notification

#### Actual result:
Sending 'To' wallet gets disconnected. 

#### Expected result:
Sending 'To' wallet stays connected. 

#### Tested device:
Samsung S20 Android 12, Chrome Version: 112.0.5615.47

#### Note:
Linked #313 

#### Attachment:

https://user-images.githubusercontent.com/10746654/232858568-057320dd-1d33-46af-a8df-1d578423f0f7.mp4

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Issue still reproducible.
Tested from: https://wormhole-connect.netlify.app/
Environment: Samsung Galaxy S22+, OS12
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aad07f5a-a551-4ef1-bfdf-634451968c92

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/.
Ticket is closed.
