### ISSUE TITLE
[QA] Validations are not triggered when switching networks and a wrapped token is selected

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#367]
## Describe the current behavior in detail

1. Connect From with Metamask
2. Select Mumbai as source network
3. Select WBNB token
4. Connect To with Metamask
5. Select BSC as destination network
6. Input an amount (in my case, 0.029)
7. Change source network to another with a lower balance for the wrapped token (Fuji in my case)
8. Observe that validations are not triggered

## What is the expected/desired behavior

It should either:
a. Trigger validations again
b. Clear the amount input

## Evidence

https://user-images.githubusercontent.com/11276821/232925287-d71b0c14-0f7c-4e71-9645-4d94cd967daf.mov

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Warning message "Amount cannot exceed balance" appears only after user clicks on "Approve and proceed with transaction" button. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e1ea0c28-825d-496e-895f-d307541bf419

**Comment by tsadovska** [comment]
Issue is no longer reproducible.
Checked on https://portalbridge.com/.
Closing the ticket.
