### ISSUE TITLE
[QA] Native gas swap calculations being performed when Solana is the source chain

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#368]
The NativeGasSlider component checks only that Solana is not the target chain, but it doesn't check if it's the source.

![image](https://user-images.githubusercontent.com/11276821/232929000-b121a3f7-4618-4cb6-bd37-ddca1081b838.png)

**Comment by AigaD** [comment]
Tested OK. 
Scenario: Verify that "Swap rate not set" error is not thrown when sending assets from Solana.
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Comments: Different error message was thrown during transactions Solana-Mumbai and Solana-Fuji (see attached video), linked issue - https://github.com/wormhole-foundation/wormhole-connect/issues/149#issue-1611440203
Attachment:

https://user-images.githubusercontent.com/91047061/234781522-183ee159-ecd8-4ee7-8cf6-29e3b26a9d7b.mov
