### ISSUE TITLE
[QA] “Error: fractional component exceeds decimals” appears when user sends too small amount 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#372]
#### Steps:

1. Connect Metamask wallets in ‘From’ and ‘To’ sections
2. Prepare to send ETH from Goerli to Moonbase
3. Type to small Amount, for example 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000001
4. Click “Approve and proceed with transaction” button

#### Actual results:

- “Error sending transfer, please try again” is displayed for the user
- Error is displayed in Console

```
Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at e.value (main.ebfc4165.js:2:8173830)
    at e.value (main.ebfc4165.js:2:8173974)
    at f (main.ebfc4165.js:2:8047389)
    at y (main.ebfc4165.js:2:8048379)
    at Module.c (main.ebfc4165.js:2:8334500)
    at main.ebfc4165.js:2:16947408
    at l (main.ebfc4165.js:2:15854034)
    at Generator.<anonymous> (main.ebfc4165.js:2:15855395)
    at Generator.next (main.ebfc4165.js:2:15854397)
    at n (main.ebfc4165.js:2:15847811)
```

#### Expected results:
User is informed that amount is too small

#### Note:
Issue is also reproducible when a user sends FTM from Fantom (Metamask wallet) to Solana (Phantom wallet).

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachments:

![Screenshot 2023-04-19 at 13 10 28](https://user-images.githubusercontent.com/10746654/233046797-f4d0f328-1b3c-4f76-9875-c16de12e891b.png)

![Screenshot 2023-04-19 at 13 20 39](https://user-images.githubusercontent.com/10746654/233046827-47247568-8e4d-4c60-a8c4-56540f580fe1.png)

**Comment by anondev2323** [comment]
Ah, I think I ran into this and fixed already.  Should check if it is still an issue

**Comment by tsadovska** [comment]
Rechecked current behaviour on https://wormhole-connect.netlify.app/ when sending too small amount:
* "Error sending transfer, please try again" is displayed for the user
* Error appears in Console:
```
Error: invalid decimal value (argument="value", value="1e-85", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at l.makeError (main.14209ac4.js:37:7042993)
    at l.throwError (main.14209ac4.js:37:7043113)
    at l.throwArgumentError (main.14209ac4.js:37:7043168)
    at b (main.14209ac4.js:37:7106677)
    at Module.S (main.14209ac4.js:37:7112610)
    at main.14209ac4.js:137:25029
    at Object.onClick (main.14209ac4.js:137:25428)  
```

Attachment:
![Screenshot 2023-05-09 at 22 07 03](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4bcdab81-60f0-4798-b366-fd10f9e16748)
