### ISSUE TITLE
[QA][Mainnet] SOL asset is not present when Solana Network is selected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#373]
Preconditions:
Solflare wallet is connected

Environment:
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from - https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/#

Steps:
1. Open Network at sending From section
2. Select Solana
3. Open Asset list
4. Observe

Actual result: SOL asset is not showing in the asset list when Solana Network is selected.

Expected result: SOL asset is present.

Attachment:

https://user-images.githubusercontent.com/91047061/233091621-11491f96-11df-4bd5-95bc-cf2fbde09da1.mov

**Comment by tsadovska** [comment]
* Issue is not reproducible on https://wormhole-connect.netlify.app/
* Issue is present on https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/
