### ISSUE TITLE
[QA] ‘Send to’ section is incomplete on Redeem screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#383]
#### Steps:

1. Connect Metamask wallets in ‘From’ section
2. Connect Wallet Connect (Zerion) wallet in ‘To’ section
3. Prepare to send 0.2 GLMR from Moonbase to Mumbai
4. Click “Approve and proceed with transaction” button

#### Actual results:
*  ‘Send to’ section is incomplete on Redeem screen
* Error is displayed in Console:

```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "swap rate not set" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="calculateMaxSwapAmountIn(address)", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000", errorArgs=["swap rate not set"], errorName="Error", errorSignature="Error(string)", reason="swap rate not set", code=CALL_EXCEPTION, version=abi/5.7.0)
    at e.value (main.ebfc4165.js:2:8173830)
    at e.value (main.ebfc4165.js:2:8173974)
    at e.value (main.ebfc4165.js:2:8022843)
    at main.ebfc4165.js:2:8066556
    at l (main.ebfc4165.js:2:15854034)
    at Generator.<anonymous> (main.ebfc4165.js:2:15855395)
    at Generator.next (main.ebfc4165.js:2:15854397)
    at a (main.ebfc4165.js:2:8060613)
```

#### Expected results:
* ‘Send to’ section is complete
* Transaction is proceed without errors

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
* Screenshot

![Screenshot 2023-04-20 at 13 57 21](https://user-images.githubusercontent.com/10746654/233346884-b840cd0a-7854-498f-8189-863d40c40f07.png)

* Recording

https://user-images.githubusercontent.com/10746654/233346930-bfefbfe0-c843-4caf-a509-5af33de6fa1e.mov

**Comment by tsadovska** [comment]
Issue is not reproducible when Metamask wallets are connected in 'From' and 'To' sections.
Checked on https://wormhole-connect.netlify.app/ [Testnet].
Issue will be rechecked with WalletConnect wallets after #747 is fixed.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.1 SUI from Sui to Mumbai
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction is stuck on Step 2, error in console `Uncaught (in promise) Error: call revert exception; VM Exception while processing transaction: reverted with reason string "swap rate not set"`

Expected result: Transaction is completed

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/beb823fd-03cc-49d0-a282-b6d9f3579316

<img width="1339" alt="Screenshot 2023-10-03 at 15 13 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e81ff332-c5da-4477-9023-5892ff0f2711">

**Comment by tsadovska** [comment]
Original issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].
Scenarios - Tested OK:
* Send 0.01 SUI from Sui to Mumbai w/o automatic deposit: [Sui explorer](https://suiexplorer.com/txblock/592rGjbjcvkQDkgZWYr3vkJ6JspktLy9Lk6nEW8WCWm8?network=testnet), [Polygonscan](https://mumbai.polygonscan.com/tx/0x36f372a737f3fb370980496a883d95a35729c61df50f51658f523a5de7a9ede9)
* Send 0.2 GLMR from Moonbase to Mumbai w/o automatic deposit: [Moonscan](https://moonbase.moonscan.io/tx/0xce1fe3c948f5d07e03f6f9df6acc5f392108284fbee9c1185a4e187f138fbdac), [Polygonscan](https://mumbai.polygonscan.com/tx/0x227fd00190d159b8ac942ec37e403e23637b9ae461b827d1f8c9f05d3a59327a)
* Send 0.8 GLMR from Moonbase to Mumbai with automatic deposit: [Moonscan](https://moonbase.moonscan.io/tx/0x4bf928257e0ed351104d0f1bf8c218d953944e5ad89cc9f7f98db81c7a42ddc7), [Polygonscan](https://mumbai.polygonscan.com/tx/0xc064463c84b532aa768748a02990e8d1a21213faa5d3a01228a287a475f649d2)

Remaining issue: Automatic deposit transactions from Sui are stuck on Step 2, ticket #1160
