### ISSUE TITLE
[bug] type definitions not included in npm package

### ISSUE THREAD

**Issue by anondev2323** [wormhole-foundation/wormhole-connect#384]
Add .d.ts files to `files` list in `package.json`

**Comment by tsadovska** [comment]
Tested OK.
Verified that latest version can be run on localhost without errors:
![Screenshot 2023-04-27 at 11 28 59](https://user-images.githubusercontent.com/10746654/234805341-501a41de-7d79-4d88-8e60-e0f7a4989ad1.png)

**Comment by tonyjin** [comment]
Should now be addressed by #1036, which was deployed as part of v0.1.1
