### ISSUE TITLE
[Feature] Allow integrator to pre-fill bridge parameters

### ISSUE THREAD

**Issue by anondev2323** [wormhole-foundation/wormhole-connect#394]
This is a request from a user (via @aakashthumaty).  They would like to specify the destination chain and address.  I think this is a pretty useful feature, and I would suspect other users might want to specify source/destination networks and token as well.

**Comment by aakashthumaty** [comment]
We should update the SDK/UI to:

detect a connected wallet 
let an integrator specify a destination network 
detect injected wallet contexts and determine based on the set network as destination whether a wallet is destination?
