### ISSUE TITLE
[QA] Step 3 "Transaction complete" did not load in 1h

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#403]
#### Environment:
https://wormhole-connect.netlify.app/

#### Steps:

1. Send 0.01 BNB from BSC to Fantom (select pay with 1 transaction in "Gas payment" option)
2. Approve and proceed with transaction
3. Observe

#### Actual result:
Step 3 did not load.

#### Expected result:
Transaction completes successfully.

#### Note:
Issue is also reproducible when:

- User sends MATIC from Mumbai to BSC
- User sends AVAX from Fuji to Alfajores
- User sends BNB from BSC from Fantom
- User GLMR from Moonbase to Fuji

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

- Transaction from Mumbai to BSC, [transaction scan](https://mumbai.polygonscan.com/tx/0xa0cec8236dd8645086d911cb4d8b1d53a9ded82cfd5a9eb9b7ed95b572c036b0
)

![Mumbai_BSC](https://user-images.githubusercontent.com/10746654/233679186-1d2d94bb-b902-403f-b164-3b3b3dea14fe.png)

- Transaction from Fuji to Alfajores, [transaction scan](https://testnet.snowtrace.io/tx/0xe4d647aeb03b839ce769b3d95f1a801ebd29d024ddceed63a89909831e6dcc46)

![Fuji_Alfajores](https://user-images.githubusercontent.com/10746654/233679633-b8aa14c1-0b47-418c-8348-963bc7e4957d.png)

- Transaction from BSC to Fantom, tx [transaction scan](https://testnet.bscscan.com/tx/0x30273a8400ea1b39709a019b3f2fac74286331843389c4005bc02af274016574)

![BSC_Fantom](https://user-images.githubusercontent.com/10746654/233679670-f08ec9ac-eb0b-4a6c-b48c-307ace14e30d.png)

- Transaction from Moonbase to Fuji, [transaction scan](https://moonbase.moonscan.io/tx/0x99dda1529fe79294b9a365d0c075c8ee2daba603f45e09b691e36ed984358c2e)

![Moonbase_Fuji](https://user-images.githubusercontent.com/10746654/233679717-c0b364d4-5b54-41e7-8eac-1fd790128432.png)

**Comment by tsadovska** [comment]
Reopening the ticket, because both me and Aiga can reproduce the issue. Step 2 does not finish loading. 
Sending From transactions:
* https://testnet.snowtrace.io/tx/0xfcdd908ff8845ed5317e52ceb2c282e785d771ba3f49f4acbb10e73eb35cfa39
* https://explorer.celo.org/alfajores/tx/0xae5c299a620f1d9ac752519964becf4cde548c53a03b7c7e93c27372fed431f8

Attachments:
<img width="1369" alt="Screenshot_2023-05-16_at_13 24 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/27c638d9-21a0-496d-a17a-0defe5a06e8f">

![Screenshot_2023-05-16_at_11 39 58](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aa8cb3fe-2c62-416c-9628-5249026cb1fd)

**Comment by tsadovska** [comment]
Step 2 does not finish loading for transaction hash `0xa84af7ea242344809dfe663890a0c7921c228983cb00aa1183a648da7c73a71c` ([Fantom](https://testnet.ftmscan.com/tx/0xa84af7ea242344809dfe663890a0c7921c228983cb00aa1183a648da7c73a71c)). Checked on https://wormhole-connect.netlify.app/ [Testnet].

<img width="1172" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/db0f7076-5ddb-422c-9e0f-37548d1cdbd6">

**Comment by aadam-10** [comment]
closing in favor of focusing on mainnet issues
