### ISSUE TITLE
[QA] Bugticket for task #329, release 0.0.1-beta.3

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#406]
Creating a bugticket linked to release - https://github.com/wormhole-foundation/wormhole-connect/releases/tag/0.0.1-beta.3 and referencing to task - https://github.com/wormhole-foundation/wormhole-connect/issues/329#issue-1667192137
-- https://github.com/wormhole-foundation/wormhole-connect/issues/107 - Tested NOK
-- https://github.com/wormhole-foundation/wormhole-connect/issues/285 - Tested NOK
(Issue linked to #285 -  https://github.com/wormhole-foundation/wormhole-connect/issues/405 was created)

**Comment by tsadovska** [comment]
Closing the ticket. Remaining issue: #107.
