### ISSUE TITLE
[QA] WSOL is not received on Solana

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#408]
#### Preconditions:

- Connect Metamask wallet in ‘From’ section 
- Connect Phantom wallet in ‘To’ section

#### Steps:

1. Prepare to send 0.01 WSOL from Fuji to Solana
2. Click “Approve and proceed with transaction” button
3. Click “Claim” button
4. Approve notifications in wallet extension
5. Check that WSOL is received on Solana

#### Actual result:
WSOL is not received. 

#### Expected result:
WSOL is received. 

#### Note:
Issue is also reproducible when sending WSOL from BSC to Solana.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/233977415-e71b51f4-2df9-46a6-96ec-e8521e5888b3.mov

**Comment by AigaD** [comment]
Tested OK.
From the comment above that Wrapped tokens are unwrapped when sent to its original chain, transaction was Success.
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Attachment:
<img width="1043" alt="Screenshot 2023-04-28 at 10 08 54" src="https://user-images.githubusercontent.com/91047061/235079302-d31bd92c-df4d-4891-8528-7dd8b5bdc999.png">

<img width="1184" alt="Screenshot 2023-04-28 at 10 06 57" src="https://user-images.githubusercontent.com/91047061/235079315-a9f6a9a1-06b6-4f19-b321-f0e62f05af37.png">

<img width="633" alt="Screenshot 2023-04-28 at 10 05 18" src="https://user-images.githubusercontent.com/91047061/235079320-fca721ff-c092-4b3f-add7-0d18c90c3492.png">
