### ISSUE TITLE
[QA][iOS] Connect wallet is shown after clicking Claim if user has connected through mobile

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#411]
Preconditions:
Metamask Wallet connected at sending From section
Metamask wallet through WalletConnect connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
iPhone 14, iOS 16.0

Steps:
1. Prepare to send 0.321 BNB from BSC to Mumbai
2. Click pay with two transactions
3. Click Approve and proceed with transaction
4. When possible click Claim
5. Observe the pop-up on your mobile device and click Switch Network
6. Observe the Transaction Screen

Actual result: Connect Wallet appears after user confirms to "Switch Network" on mobile device. User has to connect the wallet again in order to proceed with transaction.

Expected result: Transaction completes, the previously connected wallets are left connected until transaction is finished.

Attachment:
[Connect Wallet](https://drive.google.com/file/d/1a9ljNDnqvEIDphAo51Llu5Ejnrfb-n9A/view?usp=share_link)

**Comment by AigaD** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/747 is done

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1323 is resolved.

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1772.
