### ISSUE TITLE
[QA] Warning message "Amount can not exceed balance" is not shown if Network is changed 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#421]
Preconditions:
Wallets are connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Networks at sending From and sending To sections (e.g. Mumbai and Alfajores)
2. Select Asset (e.g. WBNB)
3. Enter an amount that exceeds assets balance in the wallet
4. Observe that warning message "Amount cannot exceed balance" is shown
5. Now switch Network at sending From section where entered balance also exceeds balance
6. Observe

Actual result: After switching Network the warning message "Amount cannot exceed balance" is no longer showing, also fields Gas payment, Native gas and Preview switch to active.

Expected result: Warning message "Amount cannot exceed balance" is shown if entered amount exceeds wallet balance for chosen Asset.

Attachment:

https://user-images.githubusercontent.com/91047061/234183056-458d0443-6f35-43fe-ab80-0581215c47b8.mov

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet] with following scenario:
1. Select Ethereum in From section
2. Select Optimism in To section
3. Connect Metamask wallets in From and To sections
4. Enter Amount 6 USDC
5. Change network in From section to Arbitrum (USDC balance on Arbitrum: 4.957729)
6. Observe if Warning "Amount can not exceed balance" is displayed


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3478b0ab-e633-4039-aea5-a1e0b86cdc97

**Comment by AigaD** [comment]
Reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Warning message "Amount cannot exceed balance" is not shown when Networks are changed

**Comment by AigaD** [comment]
Issue is reproducible from: https://wormhole-connect.netlify.app/#
Amount cannot exceed balance warning message is not shown when switching Networks.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f889a263-ff9d-4301-8874-14917acacb64

**Comment by tsadovska** [comment]
Linked #367.

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect.netlify.app/#
Warning message "Amount cannot exceed balance" is shown after Networks are changed
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/29e66bae-98ee-4296-b457-ac275d6935f4
