### ISSUE TITLE
[QA] RPC Error: failed to send transaction: Solana WMATIC-Moonbase

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#424]
Preconditions:
1. Phantom Wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. WMATIC asset available on Solana Network
4. Console is opened

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.0231 WMATIC from Solana to Moonbase
2. Click Approve and proceed with transaction
3. Observe

Actual result: "_Phantom - RPC Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x0_" is shown in the console and transaction fails.

Expected result: Transaction is successfully completed.

Attachment:

https://user-images.githubusercontent.com/91047061/234206757-4c513ced-3fff-4725-8b66-3550cf1b4582.mov

**Comment by AigaD** [comment]
Transaction WAVAX from Moonbase to Solana fails.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

<img width="1336" alt="Screenshot 2023-07-28 at 11 28 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f0e62978-816f-4c80-a47c-63352c2f2eef">

<img width="1344" alt="Screenshot 2023-07-28 at 11 28 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a3c3c44a-752e-491c-8358-3bd62ce87013">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]:
* Send WMATIC from Solana to Moobase ([Solana](https://explorer.solana.com/tx/4CmqkXCRRy3KSX3Yz9s6Abw8yMd79b9QSMP6wvk1LeewVDJvWK1PznyeYBjymNNREwVQWyL6UTJZgVd4z5TTMhgQ?cluster=devnet), [Moonbase](https://moonbase.moonscan.io/tx/0xcb9bb4e7f0acdb4352e341538ea03bef3300b7d766c7a012eb2ef57a190788bb))
* Send WMATIC from Moonbase to Solana ([Moonbase](https://moonbase.moonscan.io/tx/0xb8c47cec5a60dddd15a505ff956c8553519bbb1afdd1ea2026d3e956b1beaced), [Solana](https://explorer.solana.com/tx/66buUc659bXyYMKFnr3ZmKz5Zx9TpMggBLyciYp9ojPTsCk6UZVPxt3BfepSRRdz8thKEvex59mEya1ivBBzq8Wf?cluster=devnet))
