### ISSUE TITLE
[QA] User is able to enter incorrect value in Amount field

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#427]
#### Steps:

1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send FTM from Fantom to Fuji
3. Type incorrect Amount = “1.1.1.1.1.1” 
4. Click “Approve and proceed with transaction” button

#### Actual results:

- User is able to enter incorrect value in Amount field
- Transaction is started

#### Expected result:

- User is not able to enter incorrect value in Amount field
- Transaction does not start

#### Note:
Linked #329

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-04-25 at 13 41 50](https://user-images.githubusercontent.com/10746654/234254232-f62c86de-0a4d-4e73-aa11-a8432784201c.png)

**Comment by AigaD** [comment]
Reproducible, tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1004" alt="Screenshot 2023-10-03 at 11 56 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/391da9c7-28aa-4374-9bc3-b63ee69f0f96">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. User is able to enter incorrect value "1.1.1.568" in Amount field when sending FTM from Fantom (Metamask) to Avalanche (Metamask).

**Comment by AigaD** [comment]
Reproducible from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#

Attachment:

![Screenshot 2023-11-16 at 10 44 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1c696771-b065-4d0d-a452-14e05bc38823)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/ and https://testnet.portalbridge.com/df5df83982/
User is able to enter multiple dots in the amount section
Attachment:
![Screenshot 2023-11-27 at 09 00 49](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb51a21e-1f5c-4cb3-b16b-53f21914f688)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on:
* https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
* https://portalbridge.com/ [Mainnet]

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet].

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/, https://wormhole-connect.netlify.app/ and https://portalbridge.com/. 
Now when user enters the invalid number text "$NaN" is shown in amount field - #1756.
Closing the ticket. 

Attachment: 
<img width="687" alt="Screenshot 2024-06-11 at 09 55 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/506f24a7-737d-4a2e-b6a3-3e1533971eba">
