### ISSUE TITLE
[QA] [Mainnet] Incorrect balance shown for ETH

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#430]
Preconditions: Wallet is connected (ETH balance value at that time 0.14068969)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Ethereum Network
2. Click Assets and from the list choose ETH
3. Observe the balance

Actual result: Balance was shown as 140689690

Expected result: Correct balance shown, during test - 0.14068969

Attachment:
Incorrect balance for ETH:

<img width="570" alt="Screenshot 2023-04-26 at 12 46 52" src="https://user-images.githubusercontent.com/91047061/234539035-679e420b-b246-4eeb-9c56-c677b1160d5a.png">

Correct balance for BNB:
<img width="517" alt="Screenshot 2023-04-26 at 12 50 05" src="https://user-images.githubusercontent.com/91047061/234539182-1ccbe5f4-0c31-4c83-9612-75675c303e19.png">

**Comment by M-Picco** [comment]
REMOVED: commented on wrong issue
