### ISSUE TITLE
[QA][Mainnet] Incorrect value shown at minimum amount needed for transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#431]
Preconditions: Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. At sending From section select Ethereum Network
2. Click Assets and from the list choose ETH
3. At sending To section select Polygon Network
4. In the amount field enter the amount 0.000000001
5. Observe warning message of minimum amount needed for the transaction

Actual result: Warning message shows incorrect value for minimum amount needed for transaction. Currently - 628160.432174, should be 0.000023

Expected result: Minimum amount needed for the transaction shown correctly.

Comment: Seems to be linked with https://github.com/wormhole-foundation/wormhole-connect/issues/430#issue-1684714873

Attachment:
<img width="526" alt="Screenshot 2023-04-26 at 15 06 38" src="https://user-images.githubusercontent.com/91047061/234569917-89f79fa3-bcff-4f75-a02b-39a0390bc51c.png">

**Comment by tsadovska** [comment]
Tested OK. 
Issue is not reproducible on https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/ , minimum amount needed for the transaction is shown correctly.
Closing the ticket. 

![Screenshot 2023-04-27 at 18 14 24](https://user-images.githubusercontent.com/10746654/234907724-0a0a9f1f-6825-489b-913b-653cf243d399.png)
