### ISSUE TITLE
[QA][Mainnet] Current estimates are not calculated 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#433]
#### Environment:
https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect 'From' and 'To' wallets
2. Prepare to send ETH from Ethereum to BSC 
3. Type Amount, in my case “1078244.354797” (warning message shows incorrect value for minimum amount, ticket #431)
4. Observe “Gas Payment” section

#### Actual result:
Current estimates are not calculated.

#### Expected result:
Current estimates are calculated.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-04-26 at 16 54 06](https://user-images.githubusercontent.com/10746654/234598274-444fba8d-e7f6-4bf5-9569-2f50f0745296.png)

**Comment by M-Picco** [comment]
This should be partially solved by PR #438. There's still the issue of the missing fallback gas estimation for mainnet.

**Comment by AigaD** [comment]
Tested OK.
Scenario: Verify that current estimates are calculated.
Attachment:
<img width="547" alt="Screenshot 2023-04-27 at 18 11 13" src="https://user-images.githubusercontent.com/91047061/234906665-9c2772f5-b6f1-4ecb-b415-86dcecf65307.png">

**Comment by AigaD** [comment]
Reopening ticket.
The current estimates and Source chain gas estimate is not calculated if user first inputs amount lower that minimum allowed, then enter minimum allowed amount.

Steps:
1. Connect 'From' and 'To' wallets
2. Prepare to send ETH from Ethereum to BSC
3. Enter the amount lower than minimum amount (e.g. 0.000001)
4. Observe that warning message of minimum amount of 0.00078 is shown
5. Enter minimum amount needed - 0.00078
6. Observe Current estimates and Source chain gas estimate

Attachment:

https://user-images.githubusercontent.com/91047061/235084924-dbf5ed60-b262-457b-84dc-c0642fcadf6c.mov

**Comment by tonyjin** [comment]
@AigaD is this still happening on:
- Mainnet: https://mainnet--wormhole-connect.netlify.app/
- Testnet: https://wormhole-connect.netlify.app/
