### ISSUE TITLE
[QA] [Mainnet] User is not able to connect the same Phantom/Solflare wallets in ‘From’ and ‘To’ sections

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#434]
#### Environment:
https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/

#### Steps:

1. Connect Phantom/ Solflare wallet in ‘From’ section
2. Connect the same wallet in 'To' section
 
#### Actual result:

- Clicking on Phantom/ Solflare option has no effect
- User is not able to connect the same Phantom/ Solflare wallet

#### Expected result:
User is able to connect the same Phantom/ Solflare wallet.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/234614681-da7a7767-dd9c-4f72-9e2f-52227e2f58a2.mov

**Comment by AigaD** [comment]
Tested OK on - https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/
