### ISSUE TITLE
[QA] [Mainnet] Can not connect wallet in other section if wallet was previously changed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#445]
Preconditions: Wallets are NOT connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. At sending From section click on Wallet Connect and choose Phantom
2. Click again on the wallet and click Change wallet
3. Switch to Solflare
4. At sending To section try to connect to Phantom wallet
5. Observe
6. Repeat steps 1-4, but with Solflare wallet as first choice

Actual result: If Solflare/Phantom wallet was previously connected in one section and changed to Phantom/Solflare wallet then user can not connect the wallet at sending To section.

Expected result: User is able to connect wallet of choice.

Attachment:

https://user-images.githubusercontent.com/91047061/234777909-f430872b-919e-4a35-9d7e-cf63224718e1.mov

**Comment by M-Picco** [comment]
Managed to reproduce it on https://6439cde099e912008f2bc758--wormhole-connect.netlify.app (which I think is an older mainnet deploy), but not on https://wormhole-connect.netlify.app/

**Comment by AigaD** [comment]
Tested OK on - https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/ and https://wormhole-connect.netlify.app/#
Scenario: Verify that user is able to connect previously disconnected wallet.
