### ISSUE TITLE
[QA] Warning messages are not displayed before all required fields are filled

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#447]
#### Builds:
Tested NOK

- https://wormhole-connect.netlify.app/
- https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/

Tested OK

- https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/

#### Steps:

1. Click “Approve and proceed with transaction” button

 
#### Actual result:
Warning messages are not displayed.

#### Expected result:
Warning messages are displayed.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

- https://wormhole-connect.netlify.app/ 
![Screenshot 2023-04-27 at 10 58 22](https://user-images.githubusercontent.com/10746654/234798745-8d56985a-d707-4580-ab33-318deca83db6.png)

- Expected result, https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/

![Screenshot 2023-04-27 at 10 58 30](https://user-images.githubusercontent.com/10746654/234798770-161dbad1-7ab5-4432-8459-ba5fecdb8939.png)

**Comment by AigaD** [comment]
Closing this as Approve and proceed with transaction button is not shown until all required fields are filled in.
Testing from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Attachment:
<img width="1320" alt="Screenshot 2023-10-06 at 09 48 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/61ab08cd-60cc-4885-bef9-8bd35882d9f8">
