### ISSUE TITLE
[QA] [Mainnet] Warning "Amount cannot exceed balance" is not shown

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#449]
#### Builds:

Tested NOK:

-   https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/
-   https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/

Tested OK:
https://wormhole-connect.netlify.app/ 

#### Preconditions:
User has 0 SOL on Solana in Phantom wallet.

#### Steps:

1. Select SOL asset
2. Connect Phantom wallet in 'From' section
3. Connect Metamask wallet in 'To' section
4. Prepare to send 0.01 SOL from Solana to BSC
5. Click “Approve and proceed with transaction”

 
#### Actual results:

- Warning message “Amount cannot exceed balance” is not displayed
- Errors are displayed in Console:

```
Error: failed to get balance of account FvdN9u7wL8b9xRHZnkq1acVWFYWgfa2mjE2spQXoqggX: Error: 403 :  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "4be5df04-4f9f-4928-89da-862a0b9c99b2" } 
```

```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "swap rate not set" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="calculateMaxSwapAmountIn(address)", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000", errorArgs=["swap rate not set"], errorName="Error", errorSignature="Error(string)", reason="swap rate not set", code=CALL_EXCEPTION, version=abi/5.7.0)
    at e.value (main.7a7169ba.js:2:8173830)
    at e.value (main.7a7169ba.js:2:8173974)
    at e.value (main.7a7169ba.js:2:8022843)
    at main.7a7169ba.js:2:8066556
    at l (main.7a7169ba.js:2:15853796)
    at Generator.<anonymous> (main.7a7169ba.js:2:15855157)
    at Generator.next (main.7a7169ba.js:2:15854159)
    at a (main.7a7169ba.js:2:8060613)
```

#### Expected results:
Warning message “Amount cannot exceed balance” is not displayed.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachments:
![Screenshot 2023-04-27 at 12 09 43](https://user-images.githubusercontent.com/10746654/234817822-e9e0578c-437e-41b7-bf53-199a09475034.png)

https://user-images.githubusercontent.com/10746654/234817886-cacc458b-b43a-4962-b435-3a8826062757.mov

**Comment by tsadovska** [comment]
Updated description: Issue is also reproducible on https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/

**Comment by anondev2323** [comment]
Related to the Solana rpc, has been fixed and will be out in the next release

**Comment by tsadovska** [comment]
Issue is no longer reproducible, user needs to select network or wallet first and only after that select an asset. Also asset is not present in the Assets list if user doesn't have it. 

Checked on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] and https://wormhole-connect.netlify.app/ [Testnet].
