### ISSUE TITLE
[QA] "Error: Cannot request JSON-RPC method (eth_blockNumber) without provided rpc url" appears in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#466]
#### Builds - Tested NOK:
https://wormhole-connect.netlify.app/
https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/  

#### Steps:

1. Connect Wallect Connect wallets in 'From' and 'To' sections
2. Prepare to send 0.01 BNB from BSC to Mumbai
3. Click “Approve and proceed with transaction” button

 
#### Actual results:

- “Error sending transfer, please try again” is displayed for the user
- Error appears in Console:

```
Error: Cannot request JSON-RPC method (eth_blockNumber) without provided rpc url
    at e.<anonymous> (main.2b4c2911.js:2:9337326)
    at l (main.2b4c2911.js:2:10530270)
    at Generator.<anonymous> (main.2b4c2911.js:2:10531631)
    at Generator.next (main.2b4c2911.js:2:10530633)
    at r (main.2b4c2911.js:2:10524048)
    at s (main.2b4c2911.js:2:10524251)
    at main.2b4c2911.js:2:10524310
    at new Promise (<anonymous>)
    at e.<anonymous> (main.2b4c2911.js:2:10524191)
    at e.<anonymous> (main.2b4c2911.js:2:9337543)

```
#### Expected results:
Transaction proceeds without errors.

#### Notes:

- I use Zerion wallet to check issue on testnet and DeFi wallet in Binance mobile application to check on mainnet.
- Mobile app on iOS: "Binance:Buy Bitcoin Securely"
- Zerion wallet is connected via Zerion Desktop app for Mac

#### Tested devices:

- MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)
- iPhone 11 Pro (iOS 15.6.1)

#### Attachments:

- Mainnet, https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/ 
(In this case I also changed slider position in "Native gas" section, but this step can be skipped)
![Screenshot 2023-04-28 at 13 05 59](https://user-images.githubusercontent.com/10746654/235121627-b4efeb18-8825-4beb-a49b-12c5ae7f4b85.png)

- Testnet, https://wormhole-connect.netlify.app/

https://user-images.githubusercontent.com/10746654/235121667-6c567c87-f5eb-46b8-b025-2ce2ccc232c5.mov

**Comment by tsadovska** [comment]
Issue is also reproducible on https://sui-support--wormhole-connect.netlify.app/ with the following scenario:

#### Steps:
1. Connect Metamask wallet throught Wallect Connect in 'From' section
2. Connect Sui wallet in 'To' section
2. Prepare to send 0.01 BNB from BSC to Sui
3. Click “Approve and proceed with transaction” button

#### Actual results:

- "Error: Cannot request JSON-RPC method (eth_blockNumber) without provided rpc url" appears in Console
- Transaction doesn't start

#### Expected results:
Transaction proceeds without errors.

#### Attachments:
![Screenshot 2023-05-03 at 10 36 38](https://user-images.githubusercontent.com/10746654/235857647-fab9a29d-f21d-48e0-8e78-459684ae8784.png)

**Comment by tonyjin** [comment]
Also reported by a partner from the Mysten team attempting to bridge Ethereum ETH -> Sui WETH with automatic redeems:

```
Error: Cannot request JSON-RPC method (eth_blockNumber) without provided rpc url
    at H.request (main.js:37:7031353)
    at Fp.jsonRpcFetchFunc (main.js:37:9498892)
    at Fp.send (main.js:37:9499405)
    at Fp.<anonymous> (main.js:37:9496441)
    at Generator.next (<anonymous>)
    at main.js:37:9485658
    at new Promise (<anonymous>)
    at Sp (main.js:37:9485403)
    at Fp.perform (main.js:37:9495929)
    at Fp.<anonymous> (main.js:37:9465038)
  ```
    
They shared:
- using MM (through wallet connect) and Sui Wallet
- no failed transaction. This is happening before any gas is spent so no tx ID either
- confirmed that sending and receiving wallet are set appropriately to mainnet ethereum and sui respectively

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ when user sends ETH from Goerli to Mumbai. 
* Error is displayed in Console:
```
Error: Cannot request JSON-RPC method (eth_blockNumber) without provided rpc url
    at z.request (main.14209ac4.js:37:7635340)
    at UA.jsonRpcFetchFunc (main.14209ac4.js:37:10232643)
    at UA.send (main.14209ac4.js:37:10233156)
    at UA.<anonymous> (main.14209ac4.js:37:10230192)
    at Generator.next (<anonymous>)
    at main.14209ac4.js:37:10219409
    at new Promise (<anonymous>)
    at xA (main.14209ac4.js:37:10219154)
    at UA.perform (main.14209ac4.js:37:10229680)
    at UA.<anonymous> (main.14209ac4.js:37:10198789)
```
* Metamask wallets through WalletConnect are connected in 'From' and 'To' sections


![Screenshot 2023-06-07 at 18 31 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fdc82135-9de1-4ee9-ac7c-76186789c7d0)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is fixed.

**Comment by tsadovska** [comment]
Scenarios Tested OK on https://wormhole-connect.netlify.app/ [Testnet]:
* Send BNB from BSC (WalletConnect) to Mumbai (WalletConnect) with automatic deposit - [BSCScan](https://testnet.bscscan.com/tx/0x15906d104cffa78c0fa75ef7455b0f5a441ff423e405115c4d86e882fb158e66), [PolygonScan](https://mumbai.polygonscan.com/tx/0x81772f7a0cdb67119180382b4f900eee675c7d83480f9513a678824500a89246)
* Send ETH from Goerli (WalletConnect) to Mumbai (WalletConnect) with automatic deposit - [Etherscan](https://goerli.etherscan.io/tx/0xa6b1fea463929a47ae052b383b7970eada173eda1d227860546484fa8b808a34), [Polygonscan](https://mumbai.polygonscan.com/tx/0xc8c2ff93ecc0c8ee4e2be5c0695d479d460db27c88b1195650ca9a7f1ed19922)

Scenario Tested NOK on https://wormhole-connect.netlify.app/ [Testnet]:
* Send BNB from BSC (WalletConnect) to Sui (Sui wallet) with automatic deposit, ticket #1326 

Scenario Tested OK on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* Send BNB from BSC (WalletConnect) to Polygon (WalletConnect) with automatic deposit - [BscScan](https://bscscan.com/tx/0xddf34474ff27b203bc65c29011adda01843b44ee9e58c61a3170e8c21cea0432), [PolygonScan](https://polygonscan.com/tx/0xcf09da19b051e5151bfaf56d2f73d4316522cbdd68077719aee3103c84dc1ca0)

Ticket is closed.
