### ISSUE TITLE
[QA] [Mobile] Warning message "Enter an amount" is displayed when Amount is entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#468]
#### Builds - Tested NOK:
https://wormhole-connect.netlify.app/
https://6449a1e58303e00513bcfa29--wormhole-connect.netlify.app/ 

#### Devices - Tested NOK:

- Samsung S20 Android 12, Chrome Version: 112.0.5615.136
- iPhone 11 Pro iOS 15.6.1, Chrome Version 103.0.5060.63 

#### Devices - Tested OK:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Steps:

1. Connect Wallect Connect wallets in 'From' and 'To' sections
2. Prepare to send 0.00000001 WETH from BSC to Mumbai
3. Copy minimum amount from warning message 0.000023
4. Select and delete amount 0.00000001
5. Paste 0.000023 in Amount field
6. Observe if warning message “Enter an amount” is displayed
7. Open and close Assets list
8. Open and close Networks list
9. Observe if warning message “Enter an amount” is displayed

 
#### Actual result:
Warning message “Enter an amount” is still displayed.

#### Expected result:
Warning message “Enter an amount” is no longer displayed when amount is entered.

#### Note:
Linked #329

#### Attachment:

https://user-images.githubusercontent.com/10746654/235150946-6a55e7e4-5112-49da-abef-2d83af725867.mp4

**Comment by anondev2323** [comment]
It is capped at 6 decimals (I've run into wallet issues dealing with decimals beyond 6 places in the past).  Should fix the input handling to reflect this cap

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* Samsung S20 Android 12, Google Chrome 119.0.6045.193
* Samsung S20 Android 12, Brave 1.60.125, Chromium 119.0.6045.199
* iPhone 11 Pro iOS 16.5.1, Google Chrome 114.0.5735.124

Checked on:
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ee668404-8f0e-4a75-8513-5b387b33f548

Ticket is closed.
