### ISSUE TITLE
[Bug] main.css should not modify global css selectors

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#482]
## Describe the issue in detail

- v0.0.1-beta.4
- Integrator reported that main.css modifies global CSS selectors like `body` and `code`, which is not a good practice since it can clobber app-level CSS: https://www.unpkg.com/@wormhole-foundation/wormhole-connect@0.0.1-beta.4/dist/main.css

## What is the expected/desired behavior

- Limit CSS to component level selectors, perhaps via #wormhole-connect

**Comment by anondev2323** [comment]
I didn't realize this file was hanging around.  I've deleted it and will be fixed in the release momentarily
