### ISSUE TITLE
[Enhancement] Use TRM API key and cache TRM results in browser local storage

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#496]
## Describe the issue in detail

 - Using Connect NPM v0.0.1-beta.5
 - Right now there's a `trmCache` that seems to be handled in memory, but this is destroyed and recreated every time the page is destroyed
- The TRM request has a very low rate limit (1/s, 100/day), which will be improved after using an API key, but even then that API key will hit rate limits

## What is the expected/desired behavior

- Cache `trmCache` in browser `localStorage` (I think this makes more sense than `sessionStorage`?), leverage whatever value's cached there in the fast path, and update those values async based on what the TRM request comes back with
- Use API key

**Comment by anondev2323** [comment]
That makes sense. What if an address is added to or removed from the sanctions list though? Should we clear this out after a certain amount of time?

**Comment by tonyjin** [comment]
Clearing the cached entries after a period of time is a good idea 👍

Right now, is the TRM request blocking or non-blocking?

**Comment by anondev2323** [comment]
If it receives a valid response that the address is sanctioned, it is blocking. If it is rate limited, it allows the user to proceed.

**Comment by aakashthumaty** [comment]
2 options for Connect, need to chat with Legal: 

1. Set up a cloud function + firestore to send TRM requests from a backend and cache results (avoid exposing our key to malicious actors) 

2. Put the free link in the connect repo - tell integrators to fill in their own custom TRM Api keys and we only default to free link


For Portal:

xLabs should take the firestore route for sure

**Comment by tonyjin** [comment]
Closing in favor of #673
