### ISSUE TITLE
[Bug] Fee estimate for manual transfers denominated in incorrect token

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#498]
## Describe the issue in detail

 - Connect unkpkg v0.0.1-beta.5 on mainnet
 - Manual transfer of USDC from Solana -> Ethereum should require payment in SOL and ETH for gas
 - Gas estimate in "Preview" section says payment in USDC and ETH

![screenshot](https://i.imgur.com/H5xarfb.png)

## What is the expected/desired behavior

- Gas estimate preview should say XXXXX SOL & YYYYY ETH

**Comment by M-Picco** [comment]
I'll add that the detailed gas estimate for automatic transfers also has this issue for the source gas token estimation.

The following is an automatic transfer of 0.2 USDCavax from Fuji to Fantom:

![image](https://user-images.githubusercontent.com/11276821/235499668-f9a8723b-9e03-4a1a-a7ea-26bf846cd089.png)

While the relayer fee is the same as the transferred token, the source chain gas should be the native gas token (AVAX in this case).
