### ISSUE TITLE
[Bug][Mainnet] Transfer from Polygon -> Solana hangs due to 429 rate limiting from Polygon RPC

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#505]
## Describe the issue in detail

 - Connect unpkg v0.0.1-beta.6: https://codepen.io/tonyjin/pen/VwEzRam
 - Initiate a mainnet transfer of X USDC from Polygon -> Solana
 - Note that transfer details page hangs at ~halfway to 512 confirmations and developer tools shows a lot of 429 errors to a Polygon endpoint, presumably the RPC

## What is the expected/desired behavior

- Add exponential backoff to requests that 429, preferably starting with what the endpoint suggests as `Retry-After` in the response
- Look into how Portal handles polling

**Comment by aadam-10** [comment]
@tonyjin closing as outdated, let us know if it isn't
