### ISSUE TITLE
[Bug] Connect wallet overlay background does not cover entire screen

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#507]
## Describe the issue in detail

 - Connect NPM unpkg v0.0.1-beta.6. Embedded in developer's application via HTML
 - "Connect wallet" overlay background does not cover entire screen

![screenshot1](https://i.imgur.com/pD0xUa6.png)
![screenshot2](https://i.imgur.com/kHYoarS.png)

## What is the expected/desired behavior

Developer suggested the `MuiScopedCssBaseline-root css-8rz0s6` class could have `height: 100%` for the modal to fill the screen.

You could also make the argument that the connect wallet modal should not cover the entire screen and instead have sufficient top/bottom and left/right padding for a modal instead (with a translucent background).

**Comment by anondev2323** [comment]
Ah, will fix.

About changing the modal style. The design team wanted the modal to be full screen. I think we could make this a configurable option pretty easily though
