### ISSUE TITLE
[Bug] Wormhole explorer API incorrect on mainnet

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#508]
## Describe the issue in detail

- Connect NPM v0.0.1-beta.6 via unpkg: https://codepen.io/tonyjin/full/VwEzRam
- Open resume flow, enter `0xb8d8da7be889e44e6fa5578a19c4aa0108779bb941a55a9638a2aebb6be0eb3c` from Ethereum
- Note that `Waiting for Wormhole Network consensus...` is shown and doesn't go away
- Open developer tools and note failed network requests to `https://api.testnet.wormscan.io/api/v1/vaas/2/0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585/111678`

## What is the expected/desired behavior

- Explorer API should be under `https://api.wormscan.io/`
- https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/.env.mainnet suggests `https://api.staging.wormscan.io`, but I don't think that's right. Also, it's not being used by https://github.com/wormhole-foundation/wormhole-connect/blob/aaa9de09e3f02720a5ef89ddf98b56123893b88f/wormhole-connect/src/utils/vaa.ts#L27 properly for whatever reason

**Comment by anondev2323** [comment]
It's working correctly now. Will get this out as soon as possible
<img width="827" alt="Screen Shot 2023-05-01 at 7 44 46 PM" src="https://user-images.githubusercontent.com/122566365/235550842-b4d88d9d-424e-4ab3-8970-042d214d09c6.png">
