### ISSUE TITLE
[QA] [Mainnet] Assets without balance are not showing when first opening asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#513]
Preconditions: Wallets are connected

Issue reproduced from: https://wormhole-connect.netlify.app/ / https://645082646a3f5b6ba59d5ef8--wormhole-connect.netlify.app/

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Network at Sending From section (e.g. Ethereum)
2. Click on the Assets
3. Observe opened list
4. Close asset list
5. Click again to open Assets
6. Observe

Actual result: By opening assets list for the first time, only assets with balance are shown. By opening asset list for the second time (without changing Network) all assets are present.

Expected result: All assets are shown in the list.

Attachment:

https://user-images.githubusercontent.com/91047061/235592414-1d1a754d-60b5-4adc-bbdf-99a24e27f30b.mov

**Comment by anondev2323** [comment]
The desired behavior is actually to filter out tokens with 0 balance. So the first one is correct and preferred. Have included it in a PR which I will link in a moment
