### ISSUE TITLE
Font in wallet address dropdown differs from font on main page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#514]
#### Steps:

1. Connect Metamask wallet in 'From' section
2. Open wallet address dropdown

#### Actual result:
Font in wallet address dropdown differs from font on main page.

#### Expected results:
The same font is used in wallet address dropdown and on main page.

#### Builds:
https://wormhole-connect.netlify.app/ 
https://mainnet--wormhole-connect.netlify.app/
https://645082646a3f5b6ba59d5ef8--wormhole-connect.netlify.app/

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-02 at 13 26 03](https://user-images.githubusercontent.com/10746654/235643159-d90e544a-2907-4c70-ab3e-a2893bc8eb98.png)

**Comment by anondev2323** [comment]
Check again, should be fixed now

**Comment by tsadovska** [comment]
Tested OK
Checked on:

- https://wormhole-connect.netlify.app/
- https://mainnet--wormhole-connect.netlify.app/
