### ISSUE TITLE
[QA] [Sui] Wrapped assets are displayed as “Coin” in Sui wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#515]
#### Steps:

1. Open Token Bridge: https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer 
2. Select Source  = Ethereum (Goerli) in Step 1 “Source”
3. Select Target = Sui
4. Connect Metamask wallet
5. Select ETH asset
6. Type 0.01 in Amount field
7. Connect Sui wallet in Step 2 “Target”
8. Click Next button
9. Click “Transfer” button in Step 3 “Send Tokens”
10. Approve notifications
11. Click “Redeem” button on Step 4 “Redeem Tokens”
12. Observe received assets in Sui wallet

#### Actual result:
Wrapped assets are displayed as “Coin” in Sui wallet.

#### Expected results:
Wrapped assets should have unique names (for example AVAX/ ETH) in Sui wallet.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachments:
![Screenshot 2023-05-02 at 14 14 35](https://user-images.githubusercontent.com/10746654/235651495-959ad27d-2186-4b82-81f9-57c6106fa2cd.png)

https://user-images.githubusercontent.com/10746654/235651523-12c8b3e6-0478-47dc-9c17-93029daee748.mov

**Comment by anondev2323** [comment]
Please check again. I heard they fixed this with Sui

**Comment by tsadovska** [comment]
Closing the ticket, wrapped assets have unique names in Sui wallet.

![Screenshot 2023-05-09 at 22 28 20](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ceffd8ac-c6f5-408d-bed5-6ee509e87013)
