### ISSUE TITLE
[QA] Solana Network assets are present in the asset list, but balance is not loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#516]
Preconditions: Wallets are connected

https://wormhole-connect.netlify.app/ - Tested NOK
https://645082646a3f5b6ba59d5ef8--wormhole-connect.netlify.app/ - Tested OK

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Networks at both sending From and sending To sections (e.g. Moonbase and Alfajores)
2. Click on assets field
3. Observe the asset list
4. Close the list and open it again
5. Scroll to the bottom of asset list
6. Observe

Actual result: Solana Network assets are showing as loading (USDC (Solana) and WSOL (Solana))

Expected result: Balance is loaded and shown

Comments: Linked issue - [https://github.com/wormhole-foundation/wormhole-connect/issues/513](https://github.com/wormhole-foundation/wormhole-connect/issues/513#issue-1691843365)

Attachment:

https://user-images.githubusercontent.com/91047061/235646921-cc744dc8-2b0a-48b2-bc20-5e7e4cffe5e1.mov

**Comment by anondev2323** [comment]
I'm guessing this has something to do with the token not existing. If the token doesn't exist, we shouldn't show it in the modal

**Comment by AigaD** [comment]
Closing as the issue is no longer reproducible. Assets without balance are not showing in the drop down list.

Tested from: https://wormhole-connect.netlify.app/# and https://mainnet--wormhole-connect.netlify.app/

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cc0e43a6-66f5-4ceb-b6e8-4183e63ba622
