### ISSUE TITLE
[Bug] Error: `Cannot use import statement outside a module` when importing from "@wormhole-foundation/wormhole-connect"

### ISSUE THREAD

**Issue by marboro92** [wormhole-foundation/wormhole-connect#519]
## Describe the issue in detail 

Importing from @wormhole-foundation/wormhole-connect causes an error during the production build "Cannot use import statement outside a module" due to import statements in the main bundle. 

Steps to reproduce:
 1. yarn add @wormhole-foundation/wormhole-connect 0.0.1-beta.6
 2. use "import { dark } from "@wormhole-foundation/wormhole-connect"
 3. build project 
 4. build errors: 
 
<img width="541" alt="Screen Shot 2023-05-02 at 10 37 35 AM" src="https://user-images.githubusercontent.com/8175052/235700497-7a270a17-4054-471e-aa2a-78a7dd81fe78.png">

Project: Next.js and React
Package version: 0.0.1-beta.6

**Comment by anondev2323** [comment]
Related to #457
