### ISSUE TITLE
[QA][Sui] Can not redeem tokens, error message "User rejected", when Coinbase wallet extension is enabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#521]
Preconditions: Coinbase and Metamask wallet extensions are enabled
Tested from - https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. On first step select Sui as Source from the drop down list
2. For target choose e.g. Polygon
3. Click button "Connect" and choose Sui wallet
4. On select token drop down list select Sui
5. Enter the amount e.g. 0.002 and click Next
6. Click on button "Connect" on step 2 for the Target wallet
7. Choose Metamask and click Next
8. Click on button "Transfer" on step 3
9. Click Approve
10. On pop-up approve the transaction
11. On step 4 click button "Redeem"
12. Observe

Actual result: Coinbase wallet extension is opened instead of Metamask, although Metamask was connected as target chain. The transfer fails.

Expected result: Metamask pop-up to confirm the transfer is shown, transfer is finished.

Attachment:

https://user-images.githubusercontent.com/91047061/235719729-3ef74291-b976-432d-a0c4-fd3a9768f74a.mov

<img width="1297" alt="Screenshot_2023-05-02_at_16 04 10" src="https://user-images.githubusercontent.com/91047061/235720226-9aa0e462-9e67-4a15-a0bf-b5b176ca5a9c.png">

**Comment by Darnell64** [comment]
Hi @AigaD  I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetprotocol.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.
