### ISSUE TITLE
[QA] Balance in “Add suggested tokens” notification should not be duplicated

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#523]
#### Build:
https://wormhole-connect.netlify.app/

#### Steps:

1. Connect Phantom wallet in 'From' section and Metamask wallet in 'To' section
2. Send 0.01 SOL from Solana to Goerli
3. Click “Claim” button on Redeem screen
4. Click “Add WSOL to your wallet”

#### Actual result:
Balance on “Add suggested tokens” notification is duplicated.

#### Expected results:
Balance on “Add suggested tokens” notification should not be duplicated.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:
<img width="1534" alt="Screenshot 2023-05-02 at 19 35 04" src="https://user-images.githubusercontent.com/10746654/235732551-97d50ca3-d9e6-430d-9e63-563b2b1a77e6.png">

https://user-images.githubusercontent.com/10746654/235732593-d56c6e60-1cd9-4c2e-a3a7-5bf17918b714.mov

**Comment by tsadovska** [comment]
Issue is also reproducible with Sui wallet with the following scenario:
1. Connect Sui wallet in 'From' section
2. Connect Metamask wallet in 'To' section
3. Send 0.5 SUI from Sui to BSC
4. Click “Claim” button on Redeem screen
5. Click “Add SUI to your wallet”

Attachment:
![Screenshot 2023-05-03 at 07 44 53](https://user-images.githubusercontent.com/10746654/235834742-505d5938-a866-490b-b55a-bb0947bcf4a4.png)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending 0.001 WAVAX from Sei network to Fuji.
![Screenshot 2023-05-23 at 01 41 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/91bb07dd-7225-4269-adee-202cf530ceab)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://feature-sei--wormhole-connect.netlify.app/ when sending 0.0001 SEI from Sei to Goerli.
![Screenshot 2023-06-06 at 10 01 35](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4de04deb-9a07-46af-85d0-efa7ebc82f86)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ when sending 0.01 APT from Aptos to Goerli. 

![Screenshot 2023-06-24 at 19 49 59 2](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6a888c2e-9388-4375-b16c-1272486f1b26)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ when sending WGLMR from Moonbeam to Fantom.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2a555e97-d169-4636-b2e0-1763b83e2fae)

**Comment by tsadovska** [comment]
Issue will be rechecked after #739 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible. 
Checked on:
- https://latest--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-only--wormhole-connect.netlify.app/ [Mainnet]
- https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet]

Ticket is closed.

**Comment by AigaD** [comment]
Reopening the ticket.
Tested from: https://wormhole-connect.netlify.app/#
Token name shown twice on the wallet pop-up message.

Attachment:
In attachment for transaction WMATIC  Cosmohub to Mumbai

![Screenshot 2023-10-18 at 10 17 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1b7b2fc1-4075-4682-9300-b402785698b4)

Transaction Celo Cosmohub to Alfajores

![Screenshot 2023-10-18 at 11 44 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cc51a3ac-2f28-4077-a810-4143c991766c)

Transaction WGLMR Cosmohub to Moonbase

![Screenshot 2023-10-18 at 12 52 45](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3274f05-48b8-466d-8939-dc4fa195e3ad)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 APT from Aptos (Rise) to Avalanche (Metamask). Balance in "Add suggested token" notification is duplicated.

* Send from tx: [Aptos explorer](https://explorer.aptoslabs.com/txn/0x58682c5b7fc1a36c7e3caa7b5f25b1367170a4ea0dc4b0156e29fe05558630b0?network=mainnet)
* Send to tx: [Avanscan](https://avascan.info/blockchain/c/tx/0xb2b9ac1b72f8923c6724b7c604c8db3faafa8d42ec90c043cfd3c8fd0415ae44)
* Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/22/0000000000000000000000000000000000000000000000000000000000000001/79681)

![Screenshot 2024-01-08 at 10 40 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f906db7b-9b53-4fdf-b0c1-7ec179bc8d7f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet] when user clicks on "Add <token> to your wallet" several times.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c44094e9-11d0-49cc-96a2-dd86a4de5395

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/ [Mainnet] when user clicks on "Add token to your wallet" link several times.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8c2148b6-b9f6-42c5-bf37-64d54b25f3a6

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7246284e5d/#
For transaction 0.1 BONK from [BSC](https://bscscan.com/tx/0xbc90d109d7d2e9124eba1673fd5e5eb1ce2958a57c14e121c8299795d2ad112a) (Metamask) to Klaytn (Metamask) first click on Add BONK to your wallet is not reacting and with second click pop-up window with KLAY asset shown twice is shown.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/37831584-36bf-4af8-a521-ae87afb342b8

![Screenshot 2024-02-23 at 13 10 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f6f6f06a-ca90-4ad2-876b-e5885d29b96b)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending USDC from Solana to Base (Send from tx: [Solana Explorer](https://explorer.solana.com/tx/5pXW8RbjY4aYTJKgXEcbXrDLLULuysuCoGiDeEbmmPNSQBwVyT7xN8HuhzodDh92xJjVc8CR5qsuDpHRrKW9va3G), Send to tx: [BaseScan](https://basescan.org/tx/0x5b91781059acd7d3f464fd7422d1281ca7ec498b55062ee82286583a26069fff)). Balance in "Add suggested tokens" notification is duplicated when user clicks on "Add <token> to your wallet" link several times.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9bbe5b8d-36a2-43d4-87f5-6ec240a3f707

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGgAOuEd0LEIaybhnzFcjmgCeuaJsFg1cmIoDqAaQAyAQQCalsAF8Q3oA%3D%3D#) when sending 0.01 wKLAY from [Aptos](https://explorer.aptoslabs.com/txn/0x9c46a1d2de00036b6df590c6c31a536010a59cda0bc2498f03b818fc4eebba4b?network=mainnet) (MetaMask) to [Klayth](https://klaytnscope.com/tx/0xb0c37e998cc3882c8d32c93f4cec8728caa8473184dd8e3b8ed3248ca1030471). Balance in "Add suggested tokens" notification is duplicated when user clicks on "Add to your wallet" link several times.


<img width="1077" alt="Screenshot 2024-04-30 at 13 33 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/323270a0-ee0c-4f27-8cd3-136f98c3be50">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
Balance in Metamask wallet pop-up when adding token was duplicated
Attachment:

<img width="1257" alt="Screenshot 2024-05-07 at 16 09 48" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe01b0cb-c27c-42ef-a71a-ac08b941eaaa">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
When adding WETH token to Arbitrum network after transaction is completed from BSC to Arbitrum
Attachment:
<img width="1230" alt="Screenshot 2024-05-17 at 11 03 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ea5b264d-0a5c-4e33-8fde-eb383cc338ea">

**Comment by agodlevska** [comment]
Reproduced on: https://wormhole-connect-mainnet.netlify.app/#
When adding SUI token to X Layer network after transaction is completed from Sui to X Layer
Attachment:
<img width="403" alt="Screenshot 2024-05-31 at 13 55 39" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/add63de5-71ef-49ac-8bb7-c6db76e58343">

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/41c5f197e5/. 
Adding USDC token to Polygon network after transaction is completed from Injective  to Polygon. 
Balance in "Add suggested tokens" notification is duplicated when user clicks on "Add to your wallet" link several times.

Attachment:
<img width="413" alt="Screenshot 2024-08-14 at 10 30 33" src="https://github.com/user-attachments/assets/1bf32d3a-d882-4016-9388-3e85f3ad33b0">

**Comment by tsadovska** [comment]
Closing the ticket, because "Add <token> to your wallet" link is no longer displayed on Transaction screen after redesign. 

Checked on https://portalbridge.com/.
* Portal Bridge version: v0.2.15-8477ae26d0
* Wormhole Connect version : v^1.0.0-beta.1-development
