### ISSUE TITLE
[Bug] Connecting to Solana wallet makes a large number of parallel RPC calls, some are rate limited

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#527]
## Describe the issue in detail

 - https://mainnet--wormhole-connect.netlify.app/ as of 5/2 5:49PM
 - Open network tab
 - Connect Solana wallet, select Solana network
 - Note large number of requests to `https://boldest-fittest-scion.solana-mainnet.discover.quiknode.pro/e27d12bc6ecda7a40246be83a97bf5c010bc89e6/` (half are preflight requests), and note that many of them results in a 429 rate limited error
 - These requests seem to first be a large number of requests to `getAccountInfo` followed by a large number of requests to `getTokenAccountsByOwner`
 
<img width="790" alt="Screen Shot 2023-05-02 at 5 54 57 PM" src="https://user-images.githubusercontent.com/689351/235814971-2843d27b-f552-4397-9de3-eff1b7c7fb0d.png">

## What is the expected/desired behavior
- Batch Solana (and other network) RPC requests to identify token balances

**Comment by anondev2323** [comment]
I think this is just trying to get the token balances. I think the issue with the wormscan url might have caused us to burn through our rpc usage limit, maybe?

**Comment by aadam-10** [comment]
@tonyjin closing as outdated, let us know if it isn't
