### ISSUE TITLE
[Enhancement] No easy way to switch sending/receiving chain

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#531]
## Describe the issue in detail

- https://sui-mainnet--wormhole-connect.netlify.app/ as of 5/2 8:40PM PT
- Select a source chain & destination chain
- If you want to swap the source and destination chain, you have to switch away from the source chain to another, change the destination chain to the original source, and then the source to the original destination

## What is the expected/desired behavior

- Some way to swap sender and receiver via a double arrow, similar to Portal

image: https://teamillini.slack.com/archives/C0508NK3Y2C/p1683138987431219?thread_ts=1683138829.071329&cid=C0508NK3Y2C

**Comment by aakashthumaty** [comment]
Would be great to drop in a dual arrow button vertically in between the network selection buttons and when user clicks - swap.

**Comment by anondev2323** [comment]
Closing in favor of #615
