### ISSUE TITLE
[QA] “Preview” section is not loading and "Current estimate" is not calculated 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#534]
#### Build:
https://sui-support--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect Sui wallet in 'From' section
2. Connect Metamask wallet in 'To' section
3. Send 0.2 SUI from Sui to BSC

#### Actual result:
Current estimates for option “Pay with SUI (one transaction)” are not calculated even after 2-3 minutes. 

#### Expected results:
Current estimates for option “Pay with SUI (one transaction)” are calculated.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachments:

![Screenshot 2023-05-03 at 07 27 01](https://user-images.githubusercontent.com/10746654/235833481-75880f00-2c37-4a36-8adc-c3293cec23b2.png)

https://user-images.githubusercontent.com/10746654/235833491-d1689167-6a5d-45bc-a6dd-f64844cc2f46.mov

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ when sending:
* 0.5 SUI from Sui to Goerli (Metamask wallet)
* 0.1 SUI from Sui to Moonbase (Metamask wallet)

Attachments:
![Screenshot 2023-05-08 at 14 05 49](https://user-images.githubusercontent.com/10746654/236808997-84d60156-89f3-4d82-b729-222dda44446d.png)


![Screenshot 2023-05-08 at 14 06 46](https://user-images.githubusercontent.com/10746654/236809050-2327175c-6b3a-46b1-a58d-d6748cfd788b.png)

**Comment by tsadovska** [comment]
Rechecked the issue on https://wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Select Sui network in ‘From’ section
2. Select Metamask wallet in ‘To’ section
3. Prepare to send 0.01 WMATIC from Sui to Mumbai
4. Observe “Preview” and “Gas payment” sections 

#### Actual results:

- “Current estimate” for “Pay with SUI & WBNB(one transaction)” is not calculated
- “Preview” section is not loading or fees are not displayed (Text "Not available" is shown)
- Error is displayed in Console:

```
Uncaught (in promise) Error: Unable to get token info for relayer fee
    at t.SuiRelayer.calculateRelayerFee (relayer.ts:82:13)
    at async p.getRelayerFee (index.ts:558:5)
    at async index.ts:148:3
```

#### Expected results:

- "Current estimate" for “Pay with SUI & WBNB(one transaction)” is calculated
- “Preview” section is displayed correctly 

#### Note:
Issue is also reproducible with following scenarios:

- Send CELO from Sui to Goerli
- Send WMATIC from Sui to BSC
- Send AVAX from Sui to Fuji

Transaction fails when user clicks on “Approve and proceed with transaction” button (ticket: [#537](https://github.com/wormhole-foundation/wormhole-connect/issues/537)).

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachments:
![Screenshot 2023-07-13 at 11 02 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/83aa4b52-52fb-4140-a3aa-32738848b290)

![Screenshot 2023-07-13 at 12 03 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ca2a1ad8-a980-4f22-b6df-65a48e48be88)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending WBNB from Aptos (Spika wallet) to BSC (Metamask). 

Error is displayed in Console:
```
Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at c.<anonymous> (json-rpc-provider.ts:483:23)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```
![Screenshot 2023-07-31 at 17 01 39](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2f94ddad-41cc-46ce-8df7-f38552a67c5b)

**Comment by AigaD** [comment]
Reproducible from: https://base-relayer--wormhole-connect.netlify.app/#
Current estimate not shown at pay with one transaction section
TX WAVAX from Sui -> BSC
Attachment:

<img width="1259" alt="Screenshot 2023-08-21 at 12 49 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0cc0a5d2-2b9d-4459-88d9-583bc6d9ef6c">

**Comment by tsadovska** [comment]
Issue will be rechecked after #942 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

Ticket is closed.
