### ISSUE TITLE
[QA] [Sui] Several wrapped assets from Sui wallet are not displayed in Assets list

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#535]
#### Build:
https://sui-support--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect Sui wallet in 'From' section
2. Select Sui network
2. Open Assets list
3. Open Sui wallet in Extension
4. Compare assets

#### Actual result:
WETH, WFTM, CELO, WMATIC are not displayed

#### Expected result:
All available wrapped assets are displayed in the list.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Note:
User is not able to find asset via Search.

#### Attachment:
![Screenshot 2023-05-03 at 07 53 52](https://user-images.githubusercontent.com/10746654/235836263-8d1082d2-bd67-4bae-a5d2-44d2f1fcf6a7.png)

https://user-images.githubusercontent.com/10746654/235837837-2e7026dd-9a87-4c7b-a2c8-67b77826aa53.mov

**Comment by tonyjin** [comment]
Sorry, closing this since I realized the configs for the testnet page limit assets to `tokens": ["AVAX","WAVAX","BNB","WBNB","SUI","SOL","WSOL"]`
