### ISSUE TITLE
[QA] "RPC Error: Package object does not exist with ID " from source SUI with wrapped asset

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#538]
Preconditions:
1. Sui Wallet connected at Sending From section
2. Metamask wallet connected at sending To section
3. Console is opened

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.02 WBNB From Sui to BSC
2. Select pay with one transaction
3. Click Approve and proceed with transaction
4. On pop-up Sui wallet extension window click Approve
5. Observe

Actual result: "Error: Transaction failed with the following error. RPC Error: Package object does not exist with ID 0x683696ce7d22989c880452c93fc608e4decd1dcbe1e9e1960a142be0544c3ff1" is shown in the console and transaction fails.

Expected result: Transaction move to the transaction screen and is completed.

Attachment:
<img width="1338" alt="Screenshot 2023-05-03 at 11 23 13" src="https://user-images.githubusercontent.com/91047061/235866212-4d5d1141-4917-49cf-9312-e27d8af36ac2.png">

https://user-images.githubusercontent.com/91047061/235866238-83d73c0a-cda6-4c12-b18f-2dff0ec9cc5f.mov

<img width="1326" alt="Screenshot 2023-05-03 at 11 28 20" src="https://user-images.githubusercontent.com/91047061/235866840-26fcdb6d-cef3-4ec5-956c-d719660b4428.png">

<img width="1219" alt="Screenshot 2023-05-03 at 11 48 32" src="https://user-images.githubusercontent.com/91047061/235871044-2db78d5e-bd16-4d91-8456-001200ba661c.png">

**Comment by tonyjin** [comment]
Sui -> BSC w/ automatic relay

Seems like a Sui-side issue interacting with the wrapped coin
```Error: Transaction failed with the following error. RPC Error: Package object does not exist with ID 0x683696ce7d22989c880452c93fc608e4decd1dcbe1e9e1960a142be0544c3ff1```

**Comment by evan-gray** [comment]
Looks like your Sui wallet was connected to the wrong network?
