### ISSUE TITLE
[QA] Negative current estimate value is shown

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#539]
Preconditions:
1. Sui Wallet connected at Sending From section
2. Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.02 WAVAX From Sui to Fuji
2. At Gas Payment section observe Current estimate values

Actual result: For pay with two transactions current estimated are shown as **-0.001416 SUI** 0.0075 AVAX indicating negative value for SUI.

Expected result: Negative value can not be current estimate.

Attachment:

<img width="670" alt="Screenshot 2023-05-03 at 11 31 26" src="https://user-images.githubusercontent.com/91047061/235868340-2d51c131-029a-44f8-b928-04157b4cd43e.png">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenarios:
* Send 0.01 WMATIC from Sui (Sui wallet) to Sei (Fin wallet/ Leap wallet)
* Send 0.01 WMATIC from Sui (Sui wallet) to Goerli (Metamask)
* Send 0.01 WFTM from Sui (Sui wallet) to Alfajores (Metamask)

Attachment:
![Screenshot 2023-07-18 at 18 00 50](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6b55cc51-1b8e-4887-b457-7a80ee6509ef)

**Comment by AigaD** [comment]
Also negative current estimate value is shown for transaction WAVAX from Sui to Alfajores. Current estimate is not calculated.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="715" alt="Screenshot 2023-07-28 at 13 23 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1218057a-7705-45e6-857d-3fc889687f37">

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending 0.005785 WBNB from Sui (Sui wallet) to Polygon (Metamask). 

![Screenshot 2023-08-21 at 12 38 33](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eeaf94d0-2817-472b-9c12-10acea47ff96)

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] when sending 0.01 SUI from Sui (Sui wallet) to Arbitrum (Metamask).

![Screenshot 2023-09-08 at 22 12 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bcab73e2-099f-4d8b-88d3-14e41dcfab7f)

**Comment by AigaD** [comment]
Closing, as issue is no longer reproducible.
Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:
<img width="1071" alt="Screenshot 2023-09-28 at 11 47 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1bb91451-5bc8-48ec-a987-7da006c87d8d">

<img width="1116" alt="Screenshot 2023-09-28 at 11 50 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d0dba896-7a70-411d-96a0-8b000acf3b43">
