### ISSUE TITLE
[QA] [Sui] “ERC20: transfer amount exceeds allowance" appears in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#540]
#### Build:
https://sui-support--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect Metamask wallet via Wallet Connect in ‘From’ section
2. Connect Sui wallet in ‘To’ section
3. Prepare to send 0.01 WSOL from Fuji to Sui
4. Click “Approve and proceed with transaction”

#### Actual results:

- “Error sending transfer, please try again” is displayed for the user
- Error appears in Console:

```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (main.68a18b01.js:37:1410698)
    at l.throwError (main.68a18b01.js:37:1410818)
    at A.decodeFunctionResult (main.68a18b01.js:37:1316420)
    at Object.<anonymous> (main.68a18b01.js:37:1352530)
    at Generator.next (<anonymous>)
    at a (main.68a18b01.js:37:1348017)
```

#### Expected results:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachments:

![Screenshot 2023-05-03 at 11 49 55](https://user-images.githubusercontent.com/10746654/235871770-673038af-1477-4bda-9506-6f588f9ae8fe.png)

https://user-images.githubusercontent.com/10746654/235872538-9e94482a-2347-4edc-a935-aca1b6ffdcf8.mov

**Comment by tonyjin** [comment]
AVAX -> SUI w/o automatic relay

Don’t have allowances to spend the wrapped SOL?
```
6d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
```

**Comment by anondev2323** [comment]
Ok, so the error about the allowance comes from it trying to test run the transaction to get a gas estimation.  If this happens, it falls back on a default value. I'm not sure why the transaction reverted though

**Comment by tonyjin** [comment]
@tsadovska we could not reproduce this after trying a few times. Do you mind retrying on mainnet with the new build and closing if you can't repro? Thanks!

**Comment by tsadovska** [comment]
Rechecked the issue with the similar scenario on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet].

- https://wormhole-connect.netlify.app/ - Tested NOK when sending 0.01 WETH from Fuji to Sui.
Error is displayed in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC20: transfer amount exceeds allowance" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="transferTokens(address,uint256,uint16,bytes32,uint256,uint32)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000", errorArgs=["ERC20: transfer amount exceeds allowance"], errorName="Error", errorSignature="Error(string)", reason="ERC20: transfer amount exceeds allowance", code=CALL_EXCEPTION, version=abi/5.7.0)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at w.decodeFunctionResult (interface.ts:427:23)
    at Object.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at a (hashes.ts:1:25)
```
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4b320896-390a-40c8-9741-1e126c42d13f)

- https://mainnet--wormhole-connect.netlify.app/ [Mainnet] - Tested NOK when sending 0.001 WFTM from Avalanche to Moonbeam. Transaction fails with error "transaction may fail or may require manual gas limit" (ticket: #780)

**Comment by tsadovska** [comment]
Error "ERC20: transfer amount exceeds allowance" appears in Console when sending asset for the first time. Please view observations in ticket #798. 

Ticket is closed.
