### ISSUE TITLE
[QA] User is not able to change Sui wallet account

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#543]
#### Builds:
https://sui-support--wormhole-connect.netlify.app/
https://sui-mainnet--wormhole-connect.netlify.app/ 

#### Preconditions:
User has 2 accounts in Sui wallet and both are connected to https://sui-support--wormhole-connect.netlify.app/ and https://sui-mainnet--wormhole-connect.netlify.app/  

#### Steps:

1. Connect Sui wallet
2. Open Sui Extension and change account
3. Click on wallet address in wormhole-connect
4. Select “Change wallet”

#### Actual result:
Account is not changed.

#### Expected result:
Account is changed.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/235933056-b18b3104-3472-4028-99df-e38115286c98.mov

**Comment by encryptteam** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. A dedicated team to help resolve problems and issues. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by daveia123** [comment]
hi do you still have issues

**Comment by tsadovska** [comment]
Rechecked the issue. It is reproducible on May 4 on:

- https://wormhole-connect.netlify.app/
- https://mainnet--wormhole-connect.netlify.app/
- https://sui-support--wormhole-connect.netlify.app/
- https://sui-mainnet--wormhole-connect.netlify.app/

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Sui wallet account does not change after user changes the account in extension.

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1171--wormhole-connect-mainnet.netlify.app/
Sui wallet address is not changed in Wormhole-connect although user changed wallet account in extension
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/043dba96-abfd-42d2-a470-c24a5192fa9f

**Comment by tsadovska** [comment]
Scenario is added to #1159. Ticket is closed.
