### ISSUE TITLE
[Mainnet] Solana token registration not recognized

### ISSUE THREAD

**Issue by anondev2323** [wormhole-foundation/wormhole-connect#544]
Eth is definitely registered on Solana
<img width="951" alt="Screen Shot 2023-05-03 at 11 56 19 AM" src="https://user-images.githubusercontent.com/122566365/235971270-dedca574-1d02-4c9d-bf1b-b90573b52b12.png">

**Comment by daveia123** [comment]
did your connect your wallet

**Comment by anondev2323** [comment]
I think it was related to the rpc issue.  I switched it to a new one and it's working ok now. Note, this warning means that the token is registered, but I haven't created an associated token account yet which is accurate.
 
<img width="779" alt="Screen Shot 2023-05-08 at 1 32 16 PM" src="https://user-images.githubusercontent.com/122566365/236891443-6e999f4e-40aa-417c-95f7-e1e55c5131d6.png">
