### ISSUE TITLE
[product] We should not show gas dropoff or automatic relaying toggle when only manual relaying is available for a route

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#547]
### Describe the issue in detail

We can see gas dropoff toggle even when we have no gas dropoff or automatic relaying available.

https://teamillini.slack.com/archives/C0508NK3Y2C/p1683139247228889?thread_ts=1683138829.071329&cid=C0508NK3Y2C

### What is the expected/desired behavior

When automatic relaying is unavailable we should hide gas dropoff as well.

**Comment by anondev2323** [comment]
I can't see that message, can you include a screenshot?
