### ISSUE TITLE
[product] In Manual Flow We should Have Claim Button Glowing

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#549]
### Current Behavior

The claim button is greyed out and the top right of the bottom rectangle says "awaiting claim" 

### Expected Behavior

The claim button should be glowing/white and obviously actionable. 

im unable to add images but here is a slack link: https://teamillini.slack.com/archives/C0508NK3Y2C/p1683138843822269?thread_ts=1683138829.071329&cid=C0508NK3Y2C

**Comment by anondev2323** [comment]
I'm changing the color in the default theme. The integrator would just need to set `button.action`, so I've asked Martin to update that on Portal
