### ISSUE TITLE
[QA] Transactions to SUI does not move further than Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#555]
Preconditions:
Metamask Wallet connected at Sending From section
SUI wallet connected at sending To section

Tested from: https://wormhole-connect.netlify.app/#

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.2 (e.g. BNB from BSC) to SUI
2. Click Approve and proceed with transaction
3. Observe Transaction screen

Actual result: Transaction does not move further than Step 2, step 2 shows as loading.

Expected result: Transaction is completed.

Comments: Since first transaction passed 46min and Step 2 still didn't load at Resume Transfer screen.
Tested:
Fuji -> SUI
0x106ca752981c07bd55281901710b50a78d7c9f82fbb44b2f8d5abfdf9e580216
0x0fec21808ac67917afab5161a8522c4e8aeacca36c731e92e590d795d9feabdb
Mumbai -> SUI
Mumbai - 0x7d3b2c7cd90ed1326fc678a58026089e9a9a50d6ab8257e3ee41963c7e68ff79
BSC -> SUI
BSC - 0x049c63e969bdfa4668a40acaeba54a94e231f3387b3d6540a82ad4b091db6a3f

Attachment:
<img width="1355" alt="Screenshot 2023-05-04 at 10 01 38" src="https://user-images.githubusercontent.com/91047061/236133164-4b35bb5c-70bb-4a34-ae12-9e21a79bfa6b.png">

**Comment by anondev2323** [comment]
Sounds like this is a relayer problem on Testnet also
