### ISSUE TITLE
[QA] User is not able to change slider position in “Extra native gas” section (Sui)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#556]
Issue is reproducible on mainnet https://mainnet--wormhole-connect.netlify.app/  with the following scenario:

#### Steps:

1. Connect DeFi wallet through Wallet Connect in 'From' section
2. Select Ethereum network and ETH
3. Type amount 0.000263
4. Connect Sui wallet in 'To' section
5. Select Sui network
6. Change slider position in "Extra native gas" section

#### Actual result:
User is not able to change the slider position.

#### Expected result:
User is able to change slider position. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/236138957-d2036eea-2358-4775-82a4-402ed6c6f57c.mov

**Comment by tsadovska** [comment]
Issue is reproducible on testnet https://wormhole-connect.netlify.app/ with the following scenario:
#### Steps:
1. Connect Sui wallet in ‘From’ section
2. Select Sui network and SUI asset in ‘From’ section
3. Connect Metamask wallet in ‘To’ section
4. Select Moonbase network
5. Type 0.1 in Amount field
6. Change slider position in “Native gas” section

#### Actual result:
User is not able to change the slider position.

#### Expected result:
User is able to change slider position.

#### Attachment:

https://user-images.githubusercontent.com/10746654/236147031-5820ad7d-c8d2-430d-ad38-1b012793d016.mov

**Comment by anondev2323** [comment]
Looks like there are 2 problems. 1) it is the absolute minimum amount, should require the amount to be slightly greater 2) goerli rpc is returning 429 errors

**Comment by tsadovska** [comment]
Rechecked scenarios on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet].

- https://mainnet--wormhole-connect.netlify.app/ [Mainnet]:

  - Issue is no longer reproducible when a higher than minimal amount is sent.
  
  https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e8cb0ddc-879a-4853-9f16-940d6a9c968c

  - Cannot check scenario "Send minimal SUI amount from Sui (Sui wallet) to Moonbase (Metamask)" because of issue #781.
  -  Cannot check scenario "Send ETH from Ethereum (WalletConnect wallet) to Sui (Sui wallet)" because of issue #747. 


- https://wormhole-connect.netlify.app/ [Testnet]:
  - Cannot check scenario "Send SUI from Sui (Sui wallet) to Moonbase (Metamask)" because of issue #783.
  - Cannot check scenario "Send ETH from Goerli (Metamask) to Sui (Sui wallet)" because of issue #784.
  
 Ticket is closed.
