### ISSUE TITLE
[QA][Testnet]Transaction does not move past Step 1, Waiting for Wormhole network consensus

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#557]
Preconditions:
1. Metamask Wallet connected at Sending From section
2. SUI wallet connected at sending To section

Tested from: https://mainnet--wormhole-connect.netlify.app/

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.497 MATIC from Polygon to SUI
2. Click Approve and proceed with transaction
3. Observe Transaction Screen

Actual result: Transaction did not move past Step 1 for more than 1hour 15min during test, was stuck at status "Waiting for Wormhole Network consensus"

Expected result: Transaction is complete

Comments: TX hash - 0xc27bd81c025b398e60721f7b666a84f67fe9f5b5d7ccc9eaa769b54f544a4a6f

Attachment:

<img width="1322" alt="Screenshot 2023-05-04 at 11 22 56" src="https://user-images.githubusercontent.com/91047061/236151424-2007f11a-e52f-46e3-8f23-cb6559c56cda.png">

<img width="1168" alt="Screenshot 2023-05-04 at 11 30 00" src="https://user-images.githubusercontent.com/91047061/236151523-65dd806c-d833-4cea-aea2-85a16816d539.png">

**Comment by anondev2323** [comment]
I think the relayers were stuck last night.  We'll have to think of what to do in the ui when that happens

**Comment by AigaD** [comment]
Noticed the same happening in testnet - https://wormhole-connect.netlify.app/# for transaction 0.0001 WGLMR from Moonbase to SUI (TX - https://moonbase.moonscan.io/tx/0x29c8150b6b457f9e3fd46789d18403a8bd7e11c53e5574a5ddc61725c2dab1bb )
Attachment:
<img width="1368" alt="Screenshot 2023-05-08 at 14 13 32" src="https://user-images.githubusercontent.com/91047061/236809740-d72bc0c0-3897-4b05-b605-17b32b9edd55.png">

**Comment by AigaD** [comment]
Reproduced this for transaction Sei -> Fantom/Mumbai/BSC/Aptos/Fuji. Transaction is not moving forward, staying on first Step 'Waiting for Wormhole Network consensus"
Tested from: https://wormhole-connect.netlify.app/#

Attachment:
TX - https://sei.explorers.guru/transaction/7C57C4B1C7DCAE7187F376506489D021D2C5C05F4A3942EDE8685C96E5AD73FF
https://sei.explorers.guru/transaction/93D4C29A979952ACB05E76F367F38F11578E6F172F999BE16CBFE63BD294C5C6

<img width="1356" alt="Screenshot 2023-07-27 at 08 56 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0d4e47d5-c31b-4e7a-b449-6fbea9ac98fb">

**Comment by AigaD** [comment]
Tested OK.
Closing as issue is no longer reproducible.
Tested from: https://mainnet--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f2407308-5838-419e-bc13-6197554e1621

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: https://wormhole-connect.netlify.app/#
Multiple transactions from Cosmoshub are not moving further than Step 1, stays on Waiting for Wormhole Network consensus for more than 1hour 30min
[Cosmoshub -> Alfajores ](https://testnet.mintscan.io/cosmoshub-testnet/tx/3B28038EC1B87A181B2ABA0F965F9632B3E786AD862C6C0E7288BD5268552779)
[Cosmoshub -> Moonbase](https://testnet.mintscan.io/cosmoshub-testnet/tx/237125D26BBC461AE970B49944B5C808868B3F9CB0EC11339229476F69DACA87)

Attachment:
<img width="1140" alt="Screenshot 2023-11-03 at 13 58 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d41b335f-6e5a-494b-a19e-73ca1d2b2a81">

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect-mainnet.netlify.app/
Transaction is not moving further than Step 1, stays on Waiting for Wormhole Network consensus 
[Transaction](https://www.mintscan.io/evmos/tx/B46206AD3F99E5EC8993B9D6A9439A87797BCAE08F2751371CEC7FB273515D21) from Evmos to Base 
Attachment:
<img width="1142" alt="Screenshot 2023-11-03 at 15 52 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/880ad605-3859-4d3e-a721-87182f143fa2">

**Comment by AigaD** [comment]
Tested OK from https://wormhole-connect-mainnet.netlify.app/#
Transaction Evmos -> Base was completed.
![Screenshot 2023-11-06 at 09 31 44](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7ec5e8a8-6738-45e1-8810-d586603aebfc)

Tested NOK from https://wormhole-connect.netlify.app/#
[Cosmoshub -> Alfajores](https://testnet.mintscan.io/cosmoshub-testnet/tx/40E973CD0BB3142E7AB862D29B0407AFE780738C7AFD6C90EA50A43F39748C79) transaction is not moving forward Step 1, "Waiting for Wormhole network consensus"

![Screenshot 2023-11-06 at 09 43 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4e1dcf86-8bee-4f98-a30e-e2bac429159e)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction Evmos to Fantom Tested OK
[Mintscan](https://www.mintscan.io/evmos/tx/97288258B6335E6419130091D25F5A5DA235C2560B0F1CF76F2E1F3485CBDDFD)
[Fantom explorer](https://ftmscan.com/tx/0x9b18f5d5669eef7cc7382b6fe1e3e189936f888a9de9571b4771fe7752eb5e07)
![Screenshot 2023-11-07 at 14 42 48](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/437c724d-0d85-4b86-b005-87bff1b35cb6)

Transaction Evmos to Base Tested OK
[Minscan](https://www.mintscan.io/evmos/tx/42CF541C45B335CC1693AA1BDB046E2E53E2C10190E6DCC4E66AF7ABA1CFD69A)
[Base](https://basescan.org/tx/0x5dd1cb682796e29c47426a1671306142391ff6fbcdf3db37fbf6c0e42ff59538)
![Screenshot 2023-11-07 at 14 45 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/713eb0c6-649e-4d82-bfee-ab1988bf0dbd)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1174--wormhole-connect.netlify.app/#
Transaction from Cosmoshub to Optimism Goelri is not moving forward "Waiting for Wormhole network consensus"
- 0.001 WGLMR from [Cosmoshub](https://testnet.mintscan.io/cosmoshub-testnet/txs/219314E28AEDAA000D4BE442B3D796CAEDE6268C206A1A3122B8DF8431EA62A3) to Optimism
- 0.01 WMATIC from [Cosmoshub](https://testnet.mintscan.io/cosmoshub-testnet/tx/AA9A4795DCA4A527D6D43EE33C522AEF4CB7C70A9FE27BFC3F0DAC9F628DF13F) to Optimism Goerli

Attachment:

![Screenshot 2023-11-22 at 08 56 04](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b43e6924-feb0-4c87-bca9-143ae812307b)

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/
Transaction from [Base Goerli](https://goerli.basescan.org/tx/0x765de2c74c129f256ee45ff18c3eb9597e4df7a1fba235d942961411d0fccdaf) to Solana stuck on Waiting for Wormhole consesus step

Attachment:

![Screenshot 2023-11-30 at 14 21 14](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e372cefd-84fe-462c-b96e-c09bca9ba291)

**Comment by AigaD** [comment]
Will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1370 is closed.
Transaction WGLMR from Moonbase to Sui Tested OK. Tested from: https://wormhole-connect.netlify.app/

**Comment by AigaD** [comment]
Issue is reproducible from: https://wormhole-connect.netlify.app/#
Transaction [Base Goerli](https://goerli.basescan.org/tx/0xfac5a18b7a4e0e06a2762986aec9a88c9a6e7daec4eaf88f011e2c2811daf385) to Solana is not moving past step 1 "Waiting for Wormhole network consensus . . ."
Attachment:
![Screenshot 2024-01-08 at 14 10 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0dfdb6de-f2bc-4cae-81b8-8599da596bd0)

**Comment by AigaD** [comment]
Tested OK
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.1 WAVAX from [Base](https://goerli.basescan.org/tx/0x65714e56c8cb01332620211ce4fac9a875753181c2bad1fbe81591dc7d9ba544) to [Solana](https://explorer.solana.com/tx/2ZeMaKBxjkkV4KoqjjrYfkCwhAmEiREpDTkbhwd2qvAUyLuZSVMLmtxof1ZecMGYi2nZMwo6XqpfJmU4uMLFYt6U?cluster=devnet) was completed

Attachment:

![Screenshot 2024-01-18 at 13 07 02](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32a9f3c0-583e-48e2-b19d-1914dc60b13a)

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: https://wormhole-connect.netlify.app/ 
Environment: Brave Browser
Wallets: Brave wallet
Transaction from [Goerli](https://goerli.etherscan.io/tx/0x3c537d6a1371522278b6b755c05e06a3e48e720bcf581e2995ee8509763c91ca) to Solana has not moved past Waiting for Wormhole consensus step for more than 17 hours

Attachment:

![Screenshot 2024-03-01 at 09 15 06](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1de346ff-edae-4e66-9bbc-a0468f7db2c0)

**Comment by tsadovska** [comment]
Closing the issue, because Goerli is deprecated.

Successful transaction on https://wormhole-connect.netlify.app/ [Testnet]:
* Manual Bridge: [Moonscan](https://moonbase.moonscan.io/tx/0x3bb09b443175e784448c7de14b03e93d947081ec8a3ae7cbd4d7cd87470de701), [Celo explorer](https://explorer.celo.org/alfajores/tx/0x31a7bdbfe4bec8d8be7bf299b08aee365097753542ea9534e83fc23cd068816a).
* Automatic Bridge: [FTMScan](https://testnet.ftmscan.com/tx/0x4610d9e09e42455610b4ee81147313265190b162e443c9d34e43989cda4bbb1d), [Snowtrace](https://testnet.snowtrace.io/address/0x0a370E7c5F7F944d451B48bc151a7BEC454bc185/tokentxns)
