### ISSUE TITLE
Click balance to input max amount

### ISSUE THREAD

**Issue by anondev2323** [wormhole-foundation/wormhole-connect#56]

**Comment by anondev2323** [comment]
Let me know if this seems right:

**Manual maximum values:**
Token - token balance
Native token - balance minus gas estimate

**Automatic maximum values:**
Token - balance minus relayer fees minus toNativeToken amount
Native token - balance minus relayer fees minus toNativeToken amount minus gas fees

**Comment by aadam-10** [comment]
https://github.com/wormhole-foundation/wormhole-connect/issues/1377
