### ISSUE TITLE
[QA] Source chain gas estimate not calculated after switching from manual to automatic claim

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#568]
Preconditions:
1. Sui Wallet connected at Sending From section
2. Metamask wallet connected at sending To section

Tested from: https://wormhole-connect.netlify.app/# - Tested NOK
https://mainnet--wormhole-connect.netlify.app/ - Tested OK

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.0004 SUI from Sui to Mumbai
2. Observe minimum amount warning and switch to manual claim
3. Expand section Total Fee estimates
4. Click on pay with one transaction
5. Warning message regarding minimum amount and switch to manual claim should be shown again
6. Enter minimum amount required (in my test 0.1 SUI)
7. In section Total Fee estimates observe Source chain gas estimates

Actual result: Source chain gas estimates are not calculated. Console shows cannot estimate gas fee.

Expected result: Source chain gas estimates are calculated.

Attachment:

https://user-images.githubusercontent.com/91047061/236392310-a8ecb578-7ee2-4ca8-8690-731911655b40.mov

**Comment by tsadovska** [comment]
Issue is no longer reproducible with the scenario from the description. Source chain gas estimates are calculated.
Checked on https://wormhole-connect.netlify.app/ [Testnet]. Remaining issue: #942. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cf34f717-de10-43ff-90fc-6c93c0966389)


Ticket is closed.
