### ISSUE TITLE
[Improvement] Remove Search field from WalletConnect pop-up

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#571]
#### Builds:
https://wormhole-connect.netlify.app/
https://mainnet--wormhole-connect.netlify.app/ 

#### Steps:

1. Click on “Connect wallet”
2. Switch to “Desktop” tab

#### Actual result:
User is not able to put cursor in Search field to search wallet by name. Similar issue was created on ticket #144, but it won’t be fixed. Maybe it is possible to remove the Search field? 

#### Expected result:
User is able to search wallet with Search field or Search field is not displayed.

#### Note:
Linked #144

#### Devices:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:

https://user-images.githubusercontent.com/10746654/236490567-3898ff2f-03a9-4a33-ab6a-81baa8a2d172.mov

**Comment by anondev2323** [comment]
Hi, yes, the reason that is a wont-fix is because this is an external package that we use.  So this isn't actually in our control.  The same is true for anything in the wallet connect modal, unfortunately.  I filed a couple issues with them, but that's as much as we can do

**Comment by tsadovska** [comment]
Closing the ticket according to comment above.
