### ISSUE TITLE
[Bug][Mainnet] Resume transaction can cause app to crash

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#579]
## Describe the issue in detail

 - https://mainnet--wormhole-connect.netlify.app/ as of 5/5 3:29PM PT
 - Open resume transaction flow, choose Sui, and enter `33c479qH9L9gFqU5FhE636UriELQSWxyJa8cHhqkmMXg`
 - Note app crashes & renders a white screen
 ![screenshot](https://i.imgur.com/4c2wQsk.png)

## What is the expected/desired behavior

- Failure to retrieve transaction ID or parsing transaction ID should not result in app crashing

**Comment by kev1n-peters** [comment]
Have not been able to reproduce this issue as of 6/2/2023
