### ISSUE TITLE
[QA]Native gas token information disappears when transaction is complete

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#581]
Preconditions:
Sui Wallet connected at Sending From section
Metamask wallet connected at sending To section

Tested from: https://wormhole-connect.netlify.app/#

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.022 WAVAX from Sui to Fuji
2. Change slider at Native gas to receive Native Gas Token
3. Click Approve and proceed with transaction
4. Observe Send To Native Gas information

Actual result: Send To Native Gas token section is calculated and then the information disappears.

Expected result: Native Gas token information is calculated and shown to the user.

Attachment:

https://user-images.githubusercontent.com/91047061/236748779-9613e4e6-38ea-43b7-80b0-54d21d8e9e41.mov

<img width="758" alt="Screenshot 2023-05-08 at 09 22 10" src="https://user-images.githubusercontent.com/91047061/236749389-70519b66-d314-4ae9-8f1e-74238316de15.png">

**Comment by AigaD** [comment]
This is also reproduced when sending assets to Sei Network, Native Gas information is not shown when transaction is finished.
Tested from: https://feature-sei--wormhole-connect.netlify.app/#
Attachment:
<img width="777" alt="Screenshot 2023-06-06 at 12 15 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/052f1852-b4ad-4af6-80dc-a8741310bc9f">

**Comment by AigaD** [comment]
Reproducible for transactions:
FTM Fantom -> CELO
CELO Alfajores -> Fantom
AVAX Fuji -> Mumbai
Tested from: https://wormhole-connect.netlify.app/#
Native gas token information disappears when transaction is completed.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/79a9f06c-dd18-4da6-901c-2a9c35dfea3a

**Comment by AigaD** [comment]
Reproduced also from https://base-relayer--wormhole-connect.netlify.app/#
Native gas token information is not shown at the end of transaction.
Attachment:
<img width="1371" alt="Screenshot 2023-08-09 at 11 50 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/da114148-0f55-4db7-8077-90576344359e">

**Comment by AigaD** [comment]
Reproducible from https://feature-configurable-routes--wormhole-connect.netlify.app/#
After transaction is finished information for Native Gas token disappears.
Attachment:

<img width="1227" alt="Screenshot 2023-09-12 at 12 05 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a7b11899-65ed-42d5-8d82-3d3d4f7fee37">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3a6a880d-63f0-4a3a-b476-a2f8060d5c00

**Comment by tsadovska** [comment]
Tested OK on https://latest--wormhole-connect.netlify.app/ [Mainnet]. Native gas token value is shown. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d5864c09-6f79-4da0-8803-b057590dac7b)

**Comment by AigaD** [comment]
Reopening as this is reproducible from: https://deploy-preview-907--wormhole-connect.netlify.app/
Attachment:
<img width="1205" alt="Screenshot 2023-09-15 at 17 27 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/457d3590-5caa-45a6-93f7-2474cd54598d">

**Comment by kev1n-peters** [comment]
This should be fixed in #907

**Comment by AigaD** [comment]
Tested OK.
Tested from:
- https://deploy-preview-1005--wormhole-connect.netlify.app/ (Mainnet)
- https://deploy-preview-1014--wormhole-connect.netlify.app/ (Testnet)
Native Gas token information is shown after transaction is complete
