### ISSUE TITLE
[Bug] When source chain is Sui, no wallets show up when trying to connect

### ISSUE THREAD

**Issue by robinsonburkey** [wormhole-foundation/wormhole-connect#588]
When you select Sui as the Source network "From" and click "Connect Wallet", nothing shows up.

<img width="908" alt="Screenshot 2023-05-08 at 11 01 21 AM" src="https://user-images.githubusercontent.com/16466964/236872619-a3a1f6d2-c85c-4c78-baf4-c52e9fe61f26.png">

**Comment by tonyjin** [comment]
Solved by #574
