### ISSUE TITLE
[QA] [Mainnet] Action buttons differs from Figma designs

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#592]
Preconditions:
Sui Wallet connected at Sending From section
Phantom wallet connected at sending To section

Tested from: https://wormhole-connect.netlify.app/# / https://mainnet--wormhole-connect.netlify.app/

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.02 SUI from SUI to Solana
2. Observe and click on button Approve and proceed with transaction
3. Observe and click button Claim
4. Observe button Bridge more assets

Actual result: Buttons Approve and proceed with transaction, Claim and Bridge more assets are shown in white colour.

Expected result: Per Figma design buttons are left with darker background and white letters.

Attachment:
Figma design:

<img width="578" alt="Screenshot 2023-05-09 at 12 42 51" src="https://user-images.githubusercontent.com/91047061/237060144-989d9e4c-1d43-4506-9eb9-e9480c197e06.png">

Implemented:

<img width="675" alt="Screenshot 2023-05-09 at 12 41 01" src="https://user-images.githubusercontent.com/91047061/237060297-3008d064-0b71-477c-b052-f7eebbd737af.png">

<img width="667" alt="Screenshot 2023-05-09 at 12 40 38" src="https://user-images.githubusercontent.com/91047061/237060320-9040e954-c6d4-47b8-a594-0062e78b5149.png">

Mainnet:
<img width="668" alt="Screenshot 2023-05-09 at 12 51 43" src="https://user-images.githubusercontent.com/91047061/237061408-dcf63176-4c80-425e-a6fd-8842b46fdff3.png">

**Comment by anondev2323** [comment]
This was a request. The old color was not prominent enough (looked disabled)

**Comment by AigaD** [comment]
Closing ticket as per comment above.
