### ISSUE TITLE
[QA] Balance is not displayed on "Add Suggested Token" pop-up

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#608]
#### Build:
https://wormhole-connect.netlify.app/ 

#### Precondition:
Metamask app is installed on mobile

#### Steps:

1. Connect Metamask wallet through WalletConnect > QR Code in ‘From’ section on Desktop
2. Connect the same wallet in ‘To’ section
3. Send 0.01 AVAX from Fuji to Fantom (pay with AVAX)
4. Click “Add WAVAX to you wallet” link on Redeem screen
5. Observe pop-up “Add Suggested Token” on mobile

#### Actual result:
Balance is not displayed. 

#### Expected result:
Balance is displayed. 

#### Devices:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)
Samsung S20 Android 12, Chrome Version: 112.0.5615.136

#### Attachment:
![device-2023-05-11-125116](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/52d7b3c5-a3ab-49c7-a924-06c6ad385b13)

**Comment by anondev2323** [comment]
Would maybe check the rpc you have set for Fuji in the metamask extension. Going to close though, as this is something on the wallet side
