### ISSUE TITLE
[QA] Asset balance is not loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#609]
Preconditions:
Wallets are connected

Tested from: https://wormhole-connect.netlify.app/# and https://mainnet--wormhole-connect.netlify.app/

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Select Network (e.g. Goerli/Ethereum)
2. Click on Assets to open list
3. Observe balance

Actual result: Balance is not loading both for testnet and main net, Type error: Failed to fetch.

Expected result: Asset balance is loaded

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/28d2ea1e-ee85-4db3-b47f-031fbcf06611

**Comment by anondev2323** [comment]
Can you check if this is reproducible on https://www.portalbridge.com/sui/? I think this is just another issue with using the public rpcs for testing (I'm trying to get some dedicated rpcs for future use)

**Comment by AigaD** [comment]
Checked on https://www.portalbridge.com/sui/ and the Asset balance did show.
<img width="1187" alt="Screenshot 2023-05-12 at 11 06 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae07eb4a-7461-427e-82b8-9682400376b9">

**Comment by anondev2323** [comment]
ok, good, going to close then and will work on getting better rpcs across the board
