### ISSUE TITLE
[QA] Space is missing in FAQ “What types of assets does Connect support?”

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#611]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Open Menu > FAQs
2. Expand question “What types of assets does Connect support?”

#### Actual result:
Space is missing before link https://github.com/wormhole-foundation/wormhole-token-list

#### Expected result:
There is a space before link.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-16 at 10 35 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2ccbcf33-2e04-485f-b467-33fde4df8f44)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/df5df83982/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet].

**Comment by agodlevska** [comment]
Issue reproducible on https://wormhole-connect-mainnet.netlify.app/ (connect v2) and https://preview.portalbridge.com/b1f3c5115d/.

**Comment by agodlevska** [comment]
Issue is no longer relevant, the FAQ section was reworked during the redesign.
Closing the ticket.
