### ISSUE TITLE
[QA] User is not able to send SUI from Sui to Sei network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#636]
#### Build:
https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Connect Sui wallet in 'From' section
2. Connect Keplr wallet in 'To' section
3. Prepare to send 0.01 SUI from Sui to Sei
4. Click “Approve and proceed with transaction” button

#### Actual result:

- User is not able to send SUI from Sui to Sei. Clicking on “Approve and proceed with transaction” button has no effect.
- Error is displayed in Console:
`formatAssetAddress - error: Error: Unable to fetch object fields from token bridge state. Object ID: 0x32422cb2f929b6a4e3f81b4791ea11ac2af896b310f3d9442aa1fe924ce0bab4`

#### Expected result:
User is able to send SUI from Sui to Sei.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Version 113.0.5672.92 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ff6365c5-d7d0-48b0-85d1-5301e8deebbd

**Comment by tsadovska** [comment]
Issue is also reproducible on https://feature-sei--wormhole-connect.netlify.app/ with the scenario from the description. 

Error in Console:

```
Send.tsx:137 Error: not implemented
    at p.sendWithPayload (index.ts:141:11)
    at b.send (wormhole.ts:207:22)
    at index.ts:167:25
    at Object.onClick (Send.tsx:109:26)
```

Attachment:
![Screenshot 2023-05-31 at 11 32 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3e6dc801-7498-489f-a9ef-75497a06a4ad)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with the scenario from the description. 

Error is displayed in Console:
```
Error: Sui transfer with payload not implemented
    at transfer.js:511:19
    at Generator.next (<anonymous>)
    at transfer.js:7:71
    at new Promise (<anonymous>)
    at NS (transfer.js:3:12)
    at GS (transfer.js:509:12)
    at p.innerSend (index.ts:118:22)
    at async index.ts:167:11
    at async Object.onClick (Send.tsx:104:13)
```
<img width="1108" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/476d56b8-909b-48db-909f-98dea7671023">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenarios:

- With different ‘To’ wallets:

  - Send SUI from Sui (Sui) to Sei (Falcon)
  - Send SUI from Sui (Sui) to Sei (Fin)
  - Send SUI from Sui (Sui) to Sei (Compass)
  - Send SUI from Sui (Sui) to Sei (Keplr)
  - Send SUI from Sui (Sui) to Sei (Leap)
  - Send SUI from Sui (Sui) to Sei (Coin98)

- With different assets

  - Send WMATIC from Sui (Sui) to Sei (Fin)
  - Send WBNB from Sui (Sui) to Sei (Fin)
  - Send WAVAX from Sui (Sui) to Sei (Fin)
  - Send WFTM from Sui (Sui) to Sei (Fin)
  - Send CELO from Sui (Sui) to Sei (Fin)
  - Send WSOL from Sui (Sui) to Sei (Fin)

- With different ‘From’ wallets

  - Send SUI from Sui (Fewcha Move) to Sei (Compass)
  - Send SUI from Sui (Nightly) to Sei (Compass)
  - Send SUI from Sui (Martian Sui) to Sei (Compass)
  - Send SUI from Sui (Coin98) to Sei (Compass)

**Comment by AigaD** [comment]
Reproduced from: https://base-relayer--wormhole-connect.netlify.app/#
Error in console `Error: Sui transfer with payload not implemented` when sending SUI asset from Sui -> Sei
Attachment:
<img width="1329" alt="Screenshot 2023-08-22 at 09 27 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/38d3b0f4-463d-48f6-b9de-4e5f00e08b72">

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by tsadovska** [comment]
Rechecked the issue after #954 is resolved.
Build: https://wormhole-connect.netlify.app/ [Testnet].
Transaction is stuck on Step 2. 
Send from tx: [Sui explorer](https://suiexplorer.com/txblock/HwBntF4df76yzuNvL8JywQMk2EZJRsprbDW1prwt3JTS?network=testnet)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ee7ed1bd-fc2c-4a84-837e-f2a806803464)

**Comment by AigaD** [comment]
This will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1160 is resolved
![Screenshot 2023-10-27 at 12 14 18](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fba63578-4a2a-4d03-b035-a5307247154a)

**Comment by tsadovska** [comment]
Scenario is added to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1160.
Ticket is closed.
