### ISSUE TITLE
[QA] Different Keplr wallet account is displayed on Redeem screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#637]
#### Build:
https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Connect Phantom wallet in ‘From’ section
2. Connect Keplr wallet in ‘To’ section
3. Select Solana network in ‘From’ section
4. Select Sei network in ‘To’ section
5. Type Amount 0.001
6. Observe Kleplr wallet address
7. Click “Approve and proceed with transaction” button
8. Approve wallet notifications
9. Observe Keplr wallet address on Redeem screen

#### Actual result:
Different wallet account is displayed on Redeem screen.

#### Expected result:
The same wallet account is displayed on Redeem screen.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Version 113.0.5672.92 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e6a1cede-4151-4773-9f17-abeb7da1e50e

![Screenshot 2023-05-23 at 01 02 03](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8e63f9ea-ff24-4cd1-99b7-8f6bf7c20b2e)

**Comment by M-Picco** [comment]
Should be fixed now:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/11276821/7db86b23-47a4-4d4d-b110-5f58e824e4ab)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/11276821/65fc94cb-e6bd-400a-9c5d-278669ccebe0)
