### ISSUE TITLE
[QA] Claim transaction fails when sending WFTM from Sei to Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#638]
#### Build:
https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Connect Keplr wallet in 'From' section
2. Connect Sui wallet in 'To' section
3. Select Sei network in ‘From’ section
4. Select Sui network in ‘To’ section
5. Select SUI asset
6. Type amount, 0.001
7. Change asset to WFTM
8. Click “Approve and proceed with transaction” button
9. Click “Claim” button on Redeem screen

#### Actual result:

- “Your claim has failed, please try again” is displayed for the user
- Claim transaction is failed. Error is displayed in Console:

```
Uncaught (in promise) Error: Unable to fetch object fields from token bridge state
    at getIsTransferCompleted.js:206:19
    at Generator.next (<anonymous>)
    at a (getIsTransferCompleted.js:4:58)
```

#### Expected result:
Claim translation is successful. 

#### Note:
Sei Explorer tx: https://sei.explorers.guru/transaction/31DE11FBC8B6A2127A80A463FD5E30B30146A15BF31E1782EF8F15BF5DE2DFBC 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Version 113.0.5672.92 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-23 at 01 15 32](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/329f109a-e0e8-411d-a1b7-002a9179a7c0)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/70e78302-610f-4e53-8dfb-0cc346eca104

**Comment by AigaD** [comment]
Same behaviour also reproduced if sending WAVAX from Sei to Sui.
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/
Attachment:

<img width="1314" alt="Screenshot 2023-05-23 at 10 45 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9eb151ab-a6c9-4a89-88bc-b32c397db736">
