### ISSUE TITLE
[QA] Sei Network reacting field covers Alfajores icon

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#639]
Preconditions: 
1. Keplr wallet connected at sending From section
2. Metamask wallet connected at sending to section

Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Open Network section at sending From
2. Navigate to Alfajores icon and click on the bottom part of it
3. Observe

Actual result: Sei Network icon reacting field covers half of Alfajores icon, so user can accidentally select Sei when actually wanting to select Alfajores.

Expected result: Sei Network reacting field fits to the icons frame.

Attachement:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a140939-1c38-45cc-b038-4d216a6ce2b8

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/671c1f35-69b6-4be7-92c2-58ab2c148092

<img width="821" alt="Screenshot 2023-05-23 at 09 22 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5f568815-5765-4749-8dd7-221114a06312">

**Comment by AigaD** [comment]
Issue is also reproducible from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1344" alt="Screenshot 2023-07-05 at 12 47 32" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/20389f6c-d52d-42f9-bb7f-7195692a74f6">

**Comment by tsadovska** [comment]
Rechecked issue with different screen sizes on https://wormhole-connect.netlify.app/ [Testnet]. Depending on the screen size, Sei network icon reacting field also covers Sui or Solana icon. 

- Screen size: 1585px * 1550px
![Screenshot 2023-07-20 at 16 44 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/802cfc97-02aa-40bc-87e6-c465a11bde7d)

- Screen size: 412px * 915px
![Screenshot 2023-07-20 at 16 43 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/802f7b07-22b9-4af5-8e5f-0fa2e0cabe2b)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet]. 

![Screenshot 2023-08-10 at 12 04 15](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/41a611d4-d761-46f0-bff9-97eadb4dc241)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet]. 

![Screenshot 2023-09-15 at 11 21 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/802d3083-4e60-4c26-bff6-4cffb4305d48)

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:
<img width="990" alt="Screenshot 2023-09-21 at 16 41 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f480aff1-403d-4e5a-8491-8c38ba4c0af5">

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect.netlify.app/
User misclicks on Seit Network
Attachment:
<img width="907" alt="Screenshot 2023-10-02 at 10 50 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f891f3c1-dd12-4aee-8801-a2e4de7e7069">

**Comment by AigaD** [comment]
Closing as this is no longer reproduced.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1250" alt="Screenshot 2023-10-24 at 16 03 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/95864fc6-981d-466e-af44-a4f9b17c1e75">
