### ISSUE TITLE
[QA] Checksummed wallet address is not shown for Sei wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#640]
Preconditions:
1. Keplr wallet connected at sending From section
2. Metamask wallet connected at sending to section

Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Environment: https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 WAVAX from Sei to Fantom
2. Click Approve and proceed with transaction
3. Observe Sei wallet address at transaction screen

Actual result: Checksummed wallet address is not shown for Sei wallet

Expected result: Checksummed wallet address is shown for Sei wallet

Attachment:
<img width="260" alt="Screenshot 2023-05-23 at 17 03 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/29ca3232-4309-47d3-a9c6-867835d97545">

**Comment by AigaD** [comment]
Checksummed wallet address is also not showing for Aptos wallet.
Tested from: https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/#
Attachment:
<img width="260" alt="Screenshot 2023-05-24 at 08 44 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cebe607c-f961-4faf-accd-0b64710ed820">

**Comment by aadam-10** [comment]
same as https://github.com/wormhole-foundation/wormhole-connect/issues/648#issuecomment-1570639201
