### ISSUE TITLE
[QA] Link to Sei explorer is not displayed in 'Send to' section on Redeem screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#642]
#### Build:
https://646aecfa0fe5f87e14add572--wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Open Menu > Resume transaction
2. Search for 0x06ab5b3d9db4102e333bc37a59ad4319f5260309c7a405eddcca8697a7efb2e3 in Goeli network
3. Observe if link to Sei explorer is displayed

#### Actual result:
Link to Sei explorer is not displayed.

#### Expected result:
Link to Sei explorer is displayed: [Sei tx](https://sei.explorers.guru/transaction/4AC3C45030FBA4AAA441C3AA24A907E038A0CE48CEB694BDE1F3CD2C537C49AD) 

#### Notes:
Previously links to Sei explorer were displayed for transactions that are mentioned in the ticket, but now they are not. 

Issue is also reproducible with other networks. 

- Tx 0xa2724776ece7662bb59d86224e160aad4f0db6b46439d72681bdc2eb1a754bdd (Mumbai). Expected link to Sei scan [Sei tx](https://sei.explorers.guru/transaction/EA31603345495DD851665ECA7CA3839157631B46329C505EA1C151830BF75402)
- Tx 0xa9c847ed2c2dae6b8110e580dde85c5c3d39aaf49eb7c786cb646c554d8b6a8f (Fuji). Expected link to Sei scan [Sei tx](https://sei.explorers.guru/transaction/B1CE1209692AE998A7E388BD4756BA207C87BD0C7565BB60EEE9254D3F85AFFD)

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-24 at 12 09 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1154085e-22b9-4783-b1cf-d4b9d8dbe944)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://feature-sei--wormhole-connect.netlify.app/ when user sends USDC from Fuji to Sei network.

**Steps:**

1. Open Menu > Resume transaction screen
2. Search for 0x13b72721431f717a05e83aa3b7022900b58f17ea243c32eacb0b18ffc1552b4f in Fuji network
3. Observe if link to Sei explorer is displayed

**Actual result:**

Link to Sei explorer is not displayed.

**Expected result:**

Link to Sei explorer is displayed: [Sei tx](https://sei.explorers.guru/transaction/669B45CCFE1D5FCD2A6ECE5D97A9A0F42CC2BAE20C7F580FC94F089983334A98 )

**Attachment:**

![642](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5b0c868e-1b8c-496f-bc71-c191eb1de8dd)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://feature-sei--wormhole-connect.netlify.app/ when user sends WFTM from Solana to Sei network. 

[Solana tx](https://explorer.solana.com/tx/3vr4puNp6MbV5UwYdjkAgQki8GSccaBDiXex2fTqhmrWAfFKwr8jztGc6gWtYurWtMiG3hw8Cw6GF2z1QBxZQYMs?cluster=devnet )
![Screenshot 2023-05-31 at 14 02 36](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/714efe32-955e-4a35-b1aa-30622857b104)

**Comment by AigaD** [comment]
Issue was reproduced when sending BNB from BSC to Sei at https://feature-sei--wormhole-connect.netlify.app/
Attachment:
<img width="765" alt="Screenshot 2023-06-06 at 09 57 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/60d52f69-c76b-4179-9a3f-4a49bfc4cdb0">

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ [Testnet] when searching for tx hash `0x7b359c2304d0faad248f5c53e1590631501b4f0e726268f2815172f8d7876fa2` in Fantom network on "Resume transaction" screen.

<img width="595" alt="Screenshot 2023-07-06 at 18 14 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/371f0e77-aa90-475f-9e28-3dffe8326fe1">

**Comment by tsadovska** [comment]
Closing as duplicate: https://github.com/wormhole-foundation/wormhole-connect/issues/865
