### ISSUE TITLE
[QA] Claim Transaction when sending to Aptos fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#644]
Preconditions:
1. Metamask Wallet is connected at sending From section
2. Nightly connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.0001 ETH from Goerli to Aptos
2. Click Approve and proceed with transaction
3. Click Claim when possible
4. Observe

Actual result: Transaction results in: "Your claim has failed, please try again"

Expected result: Transaction is complete

Comments: 
The same behaviour also observed for transactions:
- BSC -> Aptos
- Fuji -> Aptos
- Alfajores -> Aptos

Attachment:

<img width="1321" alt="Screenshot 2023-05-24 at 10 29 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6388e611-617b-49e9-9777-d1f615556510">

**Comment by kev1n-peters** [comment]
Have not been able to reproduce this issue.

**Comment by kev1n-peters** [comment]
Tried again, have not been able to repro.
