### ISSUE TITLE
[QA] Snap option is not clickable on Connect wallet screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#646]
#### Build:
https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/   [Testnet]

#### Steps:

1. Click “Connect wallet”
2. Select “Snap” option

#### Actual result:

- Snap option is not clickable
- Error is displayed in Console:

```
Uncaught (in promise) Error: Current Metamask version doesn't support snaps
    at e.<anonymous> (index.ts:74:15)
    at utils.js:324:1
    at Object.next (utils.js:324:1)
    at o (utils.js:324:1)

```

#### Expected result:
User is able to connect Snap wallet.

#### Note:
Issue is reproducible when:

- “Metamask” and “MetaMask Flask DEVELOPMENT BUILD” extensions are disabled
- “Metamask” and “MetaMask Flask DEVELOPMENT BUILD” extensions are enabled
- “Metamask” extension is enabled and “MetaMask Flask DEVELOPMENT BUILD” is disabled
- “Metamask” extension is disabled and “MetaMask Flask DEVELOPMENT BUILD” is enabled

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-24 at 13 35 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a59e82ff-23a5-4745-bf26-893bba461652)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]

Error in Console:
```
Uncaught (in promise) Error: Current Metamask version doesn't support snaps
    at e.<anonymous> (main.d13e45d0.js:37:7588493)
    at main.d13e45d0.js:37:7587151
    at Object.next (main.d13e45d0.js:37:7587256)
    at o (main.d13e45d0.js:37:7585970)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e8181375-a172-47b3-9991-ac669ef7ac69)

**Comment by AigaD** [comment]
Issue is also reproducible on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Attachment:
<img width="1375" alt="Screenshot 2023-06-27 at 11 06 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4e0bdf2a-2307-48b0-b8df-6b711ddfbbc0">

**Comment by AigaD** [comment]
Tested from https://wormhole-connect.netlify.app/#
When clicking on Snap (Aptos) wallet a pop-up window to connect Metamask and Phantom is opened, the connection fails.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aa06940b-6868-48fe-b497-18f902849482

**Comment by AigaD** [comment]
Issue is reproducible from https://base-relayer--wormhole-connect.netlify.app/#
When Metamask wallet extension is disable Snap wallet is showing as "Install Snap" in the Connect Wallet list, but if Metamask wallet extension is enabled Snap is no longer showing as needed to be installed and when clicking on it wallet connection fails. Error `MetaMask - RPC Error: The method "wallet_getSnaps" does not exist / is not available.` is shown in the console.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/63f32484-5b9d-45f3-82db-5fb7b4173119

**Comment by tsadovska** [comment]
Issue is still reproducible on:
* https://wormhole-connect.netlify.app/ [Testnet]
* https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet].
Error is shown in Console when user selects Snap option:
`MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available. {code: -32601, message: 'The method "wallet_enable" does not exist / is not available.', data: {…}}`

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Aptos Snap wallet is not connecting. `'The method "wallet_enable" does not exist / is not available.'`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/98d9ae7d-42a1-4514-aa5d-25e7cb21a691

**Comment by AigaD** [comment]
Closing this ticket.
Aptos Snap wallet option is clickable, but error `MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available.` is shown when trying to connect the wallet.
Issue regarding it was created - https://github.com/wormhole-foundation/wormhole-connect/issues/1975
