### ISSUE TITLE
[QA] Error: Cannot read properties of undefined (reading 'data') when sending asset from Aptos

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#647]
Preconditions:
1. Nightly Wallet is connected at sending From section
2. Metamask connected at sending To section
3. Aptos Network has wrapped asset (e.g. WMATIC)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 WMATIC from Aptos to Mumbai
2. Click Approve and proceed with transaction
3. Observe

Actual result: `Error: Cannot read properties of undefined (reading 'data') ` is shown when sending wrapped asset from Aptos

Expected result: User is moved to transaction screen and transaction is complete

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/427bd56e-024d-4b4b-b718-02489e9c07d2

**Comment by kev1n-peters** [comment]
I'm not able to repro this issue on my end using nightly wallet

**Comment by AigaD** [comment]
Not able to reproduce this today as well, so will close this. Will reopen if issue reappears.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/beb1fd6b-a8f1-4535-9458-4da2bf448369

**Comment by AigaD** [comment]
Re-opening this ticket.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Error `TypeError: Cannot read properties of undefined (reading 'data')` is shown when ending 0.01 APT from Aptos to Kujira Network
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d64f8cc6-3663-4757-b2cc-78ee1ceb46a9

**Comment by AigaD** [comment]
Same behaviour reproduced for transaction APT from Aptos to Evmos
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2023-11-08 at 08 58 13](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/25cd3e3c-f998-4e4f-8d1f-f2e1ad94dc3c)

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/#
Transaction from Aptos (Nightly) -> BSC (Metamask) fails, reason `Cannot read properties of undefined (reading 'data')`
Attachment:
![Screenshot 2023-12-01 at 13 47 46](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/67fd01a3-4930-44cd-8719-dc23b89ee87b)

**Comment by tsadovska** [comment]
Issue is not reproducible with Spika wallet. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Scenarios - Tested OK:
* Send 0.01 APT from Aptos (Spika) to Evmos (Leap): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x0fd771cedcc8348f07d230459bcff616b59683f660c9520f12824a3dc1c21c46?network=mainnet), [Mintscan](https://www.mintscan.io/evmos/tx/09EE36E555C7B6942208061F8806ECC8569EAADEA2655617C335F6983D7003DE)
* Send 0.01 APT from Aptos (Spika) to BSC (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0xdfed10ac21bbb1160d438ae3beaf945d2378db63488e6816f8858991d83f3703?network=mainnet), [BscScan](https://bscscan.com/tx/0x6e5a8aab47148e0f92a8299ea0a4dc0dc7ee63d2ed1d781c3ed608b15ac61c51)

Issue will be rechecked with Nightly wallet after https://github.com/wormhole-foundation/wormhole-connect/issues/729 is resolved.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transactions tested OK:
0.1 APT from [Aptos](https://explorer.aptoslabs.com/txn/0xe8bb172def82a217125eaff71f260b7894670a9232fece928a1ce466cebb71d8?network=testnet) (Nightly) to [BSC](https://testnet.bscscan.com/tx/0x2567a5ee2f6f0364e856fe7eebc02d8db7788c55dcb4f4c49c2b3e11424c9c2f)
Transaction from Aptos to Evmos/Kujira will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/868 is solved
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Tested OK
0.01 APT from [Aptos](https://explorer.aptoslabs.com/txn/0xf80c70d6447e986398bd41e70c058faa5c379353f51e00155767f64a117f87d9?network=mainnet) (Nightly) to [Evmos](https://www.mintscan.io/evmos/tx/628B8DD6D570ADFEDCF9C7E4C7E0EE8C0E4D61E8A401CFB560FE09C0584EAFF4) (Leap)

**Comment by AigaD** [comment]
Transaction Aptos - Evmos will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1609 is solved

**Comment by tsadovska** [comment]
Tested OK:
- Send APT from Aptos (Nightly) to Mumbai (MetaMask)  on  https://wormhole-connect.netlify.app/ [Testnet] ([Aptos Explorer](https://explorer.aptoslabs.com/txn/0xfc2a0a29322edcca7674dee5cbb2db08cd294467215211bcc45168118746272e?network=testnet), [Polygonscan](https://mumbai.polygonscan.com/tx/0x9a0af3f38bbb90d3328dc9c23a22da6733eb6bfabe6ed8d3291b6ae416ce448b))
Tested NOK:
- Send APT from Aptos (Nightly) to BSC (MetaMask) on  https://wormhole-connect.netlify.app/ [Testnet] ([Aptos Explorer](https://explorer.aptoslabs.com/txn/0xf291a25a2685066a86b15bf893f0fe229f549683819f1c321c77c0afbef55730?network=testnet), [BscScan](https://testnet.bscscan.com/tx/0x24b89f2df304ce2c808d988f3c5fbc3534a80ca4c4aa82a8aea5d9b216979daa))

Tested NOK:
- Send APT from Aptos (Metamask) to Kujira (Leap) https://wormhole-connect-mainnet.netlify.app/ [Mainnet], ticket https://github.com/wormhole-foundation/wormhole-connect/issues/729

Issue will be rechecked after #729 is rechecked.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.001 WMATIC from [Aptos](https://explorer.aptoslabs.com/txn/0xcf2e688cb4e472ce6e116fc2ccfbfd603e507f18510820bf5d39211733f35c6c?network=mainnet) (Nightly) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/2585F7CF5CD029301FB8538DB24E63A14FCF80CDBFA81B0DCE45C99F63DCD7E3) (Leap) was completed.

Attachment:

<img width="1096" alt="Screenshot 2024-03-13 at 12 33 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b63c206f-7a5c-48c0-b40a-1881c9b4131b">

Closing the ticket
