### ISSUE TITLE
[QA] Balance for assets are not loaded when selecting BSC to Sei Networks

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#650]
Preconditions:
1. Metamask wallet is connected at sending From section
2. Keplr wallet is connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Steps:
1. Select BSC Network at sending From section
2. Select Sei Network at sending To section
3. Click on Assets list
4. Observe the balance

Actual result: Balance is not loading for transaction BSC -> Sei, error `Error: processing response error` is shown in the console, transaction is not moving forward

Expected result: Balance is loaded for the assets in the asset list.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/db15492e-2f02-4477-85c6-54a1be2adac3

https://github.com/wormhole-foundation/wormhole-connect/issues/650#issue-1731694720

**Comment by AigaD** [comment]
The same issue, balance not loading, also observed when selecting Networks Solana -> Sei and Sei - > Fuji
Tested from: https://feature-sei--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7a16b1e9-e907-4219-ba50-6e0acfaaf05c

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c4f53733-04da-4a74-8192-983319bc7365

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ without selecting “Sending To” network. 

Steps:
1. Select BSC network in From section
2. Connect Metamask wallet


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2e2b4725-ebb1-4475-99fc-d871a387c63f

**Comment by tsadovska** [comment]
Checked all the scenarios that are mentioned in the ticket. Issue is no longer reproducible. 

Ticket is closed.
