### ISSUE TITLE
[QA] Fee value should have more decimals after comma

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#651]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/   [Testnet]

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Keplr wallet in To section
3. Prepare to send 0.01 ETH from Goerli to Sei
4. Observe “Source chain gas estimate” value

#### Actual result:
"Source chain gas estimate" value is 0, but Gas estimate in Metamask wallet is 0.00013033 ETH (0.25 USD).

#### Expected result:
“Source chain gas estimate” value should have more decimals after comma.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-30 at 12 11 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f7f85603-c450-463e-a1b3-636215c8ffce)

**Comment by AigaD** [comment]
Current estimates at Gas Preview section are not calculated when sending wrapped asset from Goerli to Sei, they are shown as 0
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Attachment:
<img width="626" alt="Screenshot 2023-05-30 at 14 49 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/33ec696a-6b80-431f-a7d9-c16594dfc649">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ when user sends WAVAX from Goerli to Aptos.

<img width="1309" alt="Screenshot 2023-06-23 at 15 54 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e4f2c506-40eb-4e3f-b7dd-b362c32f00f4">

**Comment by tsadovska** [comment]
Can be reproduced on https://wormhole-connect.netlify.app/ [Testnet] when Goerli network is a destination chain. 

Scenarios:
* Send ETH (in my case 0.001) from Base Goerli (Metamask) to Goerli (Metamask)

![Screenshot 2023-08-07 at 14 45 03](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/91874913-d09c-4841-85e7-7c19d89d3672)
* Send MATIC from Mumbai to Goerli
* Send CELO from Alfajores to Goerli
* Send CELO from Fuji to Goerli 
* Send WBNB from Aptos to Goerli

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending 0.5 SOL from Solana (Phantom) to Osmosis (Leap). Gas fee is shown as 0 SOL in "Send from" section, but actual gas fee is 0.00015 SOL. Issue is reproducible only on Redeem screen. Gas estimate is shown correctly on Bridge screen. 

![Screenshot 2023-08-24 at 11 55 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/08a27c37-256d-4bc9-8849-3213345cb32d)

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending 0.1 ETH from Goerli (Metamask) to Osmosis (Leap). "Source chain gas estimate" and "Total fee estimates" values are shown as 0 ETH. Issue is reproducible only on Bridge screen. Gas fee is shown correctly on Redeem screen, 0.00013 ETH. 

![Screenshot 2023-08-28 at 10 42 18](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/416ba453-782b-4306-8a19-b0444b695b40)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/. See: https://github.com/XLabs/portal-bridge-ui/issues/370

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when sending BONK from Solana (Phantom) to Osmosis (Leap wallet).

![Screenshot 2023-08-31 at 20 33 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2696fe48-53a5-405e-82cb-1a2c2dd39130)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet].

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dcc3ca2e-c174-4f02-b5df-c043bf5b35ac)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b03891cd-484e-4de4-8133-d8ef27368c4d


Issue is not closed, because it is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]. "Source chain gas estimate" value is displayed as 0 ETH when sending 0.11 USDC (Goerli) from Goerli (Metamask wallet) to Fuji (Metamask wallet). 
Issue is not reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] with the same scenario.

![Screenshot 2023-09-07 at 10 37 02](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/76cca7fa-b34f-4b9c-8f5c-23bd18709519)

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] when sending ETH from Ethereum to Optimism.

Send from tx: [Etherscan](https://etherscan.io/tx/0x82c53d4c5255f5a1f84780337a008d96a059c0cd9314a00a2700257b0f64c910)
Send to tx: [Optimism](https://optimistic.etherscan.io/tx/0x80878b9149127b6dd4855822c147a2666bbeece72276eb7b25da5175edf5fe1b)

![Screenshot 2023-09-08 at 15 18 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7967230b-b309-4718-bcb7-bb4f179b242e)

**Comment by AigaD** [comment]
Incorrect gas fee shown for transaction 0.02 AVAX from Fuji to Moonbase, 0.02 SOL from Solana -> Fantom
Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/#
Gas fee should be shown 0.000339352 DEV ($0.00) but instead 339352 GLMR is shown

Attachment:
https://moonbase.moonscan.io/tx/0xeafbea5a1009facef15dde3f66ba4cf675b3d0671cfee12f9c4e270580abc6db

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c81ea183-c9bf-4289-abaa-4042f2c72521

<img width="1069" alt="Screenshot 2023-09-12 at 12 23 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aea5f134-76b6-4854-9b51-219fbbf934c6">

<img width="1145" alt="Screenshot 2023-09-12 at 12 22 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/41ee857d-d40c-41bd-9cbc-c288e58375ff">

<img width="1095" alt="Screenshot 2023-09-12 at 13 56 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/925bcab9-0335-459e-896c-504f9be2f6f9">

**Comment by tsadovska** [comment]
Issue is reproducible on https://feature-configurable-routes--wormhole-connect.netlify.app/ [Testnet] when sending 0.001 ETH from Goerli (Metamask) to Optimism Goerli (Metamask). Incorrect gas fee value is shown in "Send to" section, 226183.507539 ETHoptimism instead of 0.00022618350760929 ETH ($0.000000). 

Send to tx: [Optimism](https://goerli-optimism.etherscan.io/tx/0x9ca9e31c7f62c6dce9424e72818a8feb34bb9e626775044e5b1f6106f55598c6)


<img width="629" alt="Screenshot 2023-09-13 at 09 48 50" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/06cf6be7-4ce6-4d61-8a32-7a636af89255">

<img width="522" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7280e147-aacd-47d5-a553-f7a72b22da20">

**Comment by tsadovska** [comment]
Tested OK on https://cctp-only--wormhole-connect.netlify.app/ [Mainnet].
Issue is still reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet].

- Send from tx: [Osmosis](https://www.mintscan.io/osmosis/transactions/B22EA95A035361BBDB8E63C8EC2D5670D5E35575B7EC71901094E0F75165B17C)
- Send to tx: [Basescan]( https://basescan.org/tx/0x17624e23fa54b8dd804058677da89ed33578031beec42da7b6fe5d5516fbca2c)

![Screenshot 2023-09-14 at 22 34 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/74d0dbae-031e-407b-9a20-cd910246f77d)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d36441c0-7a9c-4200-9a60-3b9c1bad8db7)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-907--wormhole-connect.netlify.app/
Attachment:
<img width="1166" alt="Screenshot 2023-09-15 at 10 01 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/47a1484b-bed9-4a46-a34c-bdc3a6e26ec3">
<img width="1145" alt="Screenshot 2023-09-15 at 10 30 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a9056c72-00e8-425c-879b-073ba5a92dc7">

<img width="1093" alt="Screenshot 2023-09-15 at 10 29 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/36137f00-f398-480b-ac3d-9253fef4ef1b">

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1005--wormhole-connect.netlify.app/#
Attachment:
<img width="1212" alt="Screenshot 2023-09-19 at 15 45 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d0ec7026-f687-4dff-88ac-ca478d847c1a">
<img width="1078" alt="Screenshot 2023-09-19 at 15 44 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4319afb8-5004-4dd4-a3d4-c1c35fc78b94">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1014--wormhole-connect.netlify.app/#
Transactions to Osmosis shows fee 0 OSMO
<img width="1122" alt="Screenshot 2023-09-21 at 10 33 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09779782-b203-4c3e-909f-583eb6836cf1">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] when sending 0.0001 ETH (Base) from Base to Ethereum.

- Gas fee on Redeem screen: 0 ETH (Base)
- Gas fee on Etherscan: 0.000015368024901999 ETH ($0.02)

Transaction details:
* Send from tx: [Basescan](https://basescan.org/tx/0x1f23a7e4117217613f66327577f30d6608dcab486b64089def62ee5cabb31d55)
* Send to tx: [Etherscan](https://etherscan.io/tx/0xbf1fad0b0d211d3a689cfadeda21a9e81c0ff7732ed0178eb2c8616b5bda1af6)

![Screenshot 2023-09-26 at 11 06 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/07f492c2-2ccd-48fa-8435-9e8d36656c94)

**Comment by AigaD** [comment]
Issue is reproducible from: https://wormhole-connect.netlify.app/
Attachment:
<img width="690" alt="Screenshot 2023-10-02 at 12 24 43" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2733831c-a451-4958-8e0c-9c7616178484">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
<img width="1183" alt="Screenshot 2023-10-04 at 10 46 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d4fc22c2-55af-40d2-9599-ccb83fcb06d5">
<img width="1188" alt="Screenshot 2023-10-04 at 10 46 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/96264fb0-d526-437b-8f35-433733b847a2">

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.1 DAI from Goerli (Metamask) to Solana (Phantom).

Send from tx: [Etherscan](https://etherscan.io/tx/0x3f91141e54b201898fa94c9fa4e014e1ab30ed8a7f5f9651f4b7b24987956406)
Send to tx: [Solana explorer](https://explorer.solana.com/tx/5MqYq4driQ7aFyFwzK8NTajiWsB8wtK5NYVQPToCL1Ucm4ixTVikAYMtNHPDvheFKDa7pNrJpqNeVRy6kqYPeWq5)


![Screenshot 2023-10-04 at 22 02 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b5481923-38b4-4ea3-8eea-652c0a8a9af5)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
For transaction APT from Aptos -> BSC fees at Source chain gas estimate were shown as 0 APT (fee was 0.000036 APT)
Attachment:

![Screenshot 2023-10-13 at 12 07 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/05f13121-7627-45f6-bf2e-be09a1b464df)

![Screenshot 2023-10-13 at 12 10 03](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/568f422d-52f4-4410-a160-cd925151c7aa)

**Comment by AigaD** [comment]
Also reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2023-10-13 at 17 41 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/14c16a17-80a2-4f82-a729-22ebabc6ff56)

![Screenshot 2023-10-13 at 17 42 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7e801f51-305a-4c69-aa27-396bea669076)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Estimates in preview section shown as 0
Transaction MATIC from Mumbai to Cosmoshub
Attachment:

![Screenshot 2023-10-18 at 09 25 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d450be65-1298-4b5d-9b74-1c4bb30d962d)


<img width="353" alt="Screenshot 2023-10-18 at 09 26 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7c046e0-6eb4-4ae4-9cf8-31850079ee48">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
For transactions to Evmos gas estimates are shown as 0 EVMOS
Attachment:
<img width="999" alt="Screenshot 2023-10-19 at 16 01 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0ddd2f82-673f-4e0d-8ed4-0a02f2d15eef">
<img width="876" alt="Screenshot 2023-10-19 at 16 00 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3e061c22-0df8-4ac3-b10e-ad9dc5ae4342">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] when sending 0.1 USDC from Ethereum (Metamask) to Base (Metamask). 

Gas fee on Redeem screen: 0 ETH (Base)
Gas fee on BaseScan: 0.000098763203820957 ETH ($0.18)

Send from tx: [Etherscan](https://etherscan.io/tx/0xedc9e4f72fc365a04201db840946fa4f442013a932e56f61ff281757c7256559)
Send to tx: [BaseScan](https://basescan.org/tx/0x02b0c033d82731ea2f556478a3c74a3ba792335fa85b556c03226004c0ee8e10)

![Screenshot 2023-10-26 at 04 54 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f41f39fa-033f-4ad1-86be-1c70f568534b)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Transactions to Cosmoshub shows 0 fee in Gas fee
Attachment:
<img width="963" alt="Screenshot 2023-11-03 at 09 26 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8bd2b73-b481-49c0-970a-87bd29e751be">

**Comment by AigaD** [comment]
Reproduced also from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
For transaction Ethereum -> Kujir
Attachment:
<img width="1065" alt="Screenshot 2023-11-14 at 11 50 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f7434542-497c-4b12-85bb-f2341c6e9a41">
<img width="931" alt="Screenshot 2023-11-14 at 11 49 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2293f584-678b-4e42-b5a4-9d8d6db329a2">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/df5df83982/ [Mainnet] when sending 0.0001 USDC from Polygon (Metamask) to Base (Metamask). Gas fee on wormhole-connect is shown as 0 ETH (Base), transaction fee on Basescan is
0.000768078797191231 ETH ($1.59).

* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x8a15c7ddb8bfa7a495ef33e853066362ce03d2725d7dcab0c6e850ca9d791d09)
* Send to tx: [BaseScan](https://basescan.org/tx/0x6576c3778a5939f8963e5560d6913c279beb6446457f2fcb745130177d450bee)

**Comment by AigaD** [comment]
Issue is also reproducible from: https://testnet.portalbridge.com/df5df83982/
For transaction [Moonbase](https://moonbase.moonscan.io/tx/0x85ce579a00e1d01a7e3646727f37d12fd3205badbe79d0be30f686c5cf47ca67) -> [Solana](https://explorer.solana.com/tx/ip1QPAoLTxq46tea1QshTz1sEpNBwBfGL8cWnXRvNaakwWTLyZMYqNtXECSzGBXojK1ATuGJZCogXzhKLunVcCu?cluster=devnet) gas fee is shown as 0 SOL
Attachment:
![Screenshot 2023-11-27 at 09 55 22](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/05775e62-bfab-43a7-be25-af180bc156e1)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/# and https://deploy-preview-1312--wormhole-connect.netlify.app/#
Attachement:
![Screenshot 2023-12-14 at 18 53 27](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ddb3ae6-151f-4f72-b0e9-bae2d5ac9908)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7102d8ccad/
Attachment:
<img width="1313" alt="Screenshot 2023-12-18 at 16 36 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f3c49d5e-58eb-4d1c-8f70-cc1079a21a26">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] when sending 0.2 CELO from Celo (Metamask) to Evmos (Keplr). "0 Evmos" is shown as gas fee.

* Send from tx: [Celo explorer](https://explorer.celo.org/mainnet/tx/0x9312c2f28f5a35ff4224cd1c2ad2d7b5ffda66f4d25599f6f2b9a8d93d59cf9f)
* Send to tx: [Mintscan](https://www.mintscan.io/evmos/tx/801CD6D3D65581455A13F063E691CE2C69A6FD1BC3CCF6C82381027B311527DD)

<img width="928" alt="Screenshot 2023-12-23 at 00 13 48" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/874e618e-5304-4093-9147-dbcc2da55adf">

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/usdc-bridge/ [Mainnet] when sending 0.001 USDC from Polygon (Metamask) to Base (Metamask). 0 ETH (Base) is shown as gas fee.

* Send from tx: [Polygonscan](https://polygonscan.com/tx/0xd79832197ba41436344c1d1c42682381947a0b9d47940002ac64489238585c34)
* Send to tx: [Basescan](https://basescan.org/tx/0x850b81b299f4b333cb67d6f84c6e7a7deb9c1d45279abf78dfa1e65f53f67829)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/676ee952-14f7-492b-9f1f-126d71e9b458)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/
In preview section fees are shown as 0 APT
Attachment:

![Screenshot 2024-01-03 at 09 39 56](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e80d4a7f-f395-44a6-a863-5096311f37c2)

<img width="380" alt="Screenshot 2024-01-03 at 09 59 26" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aec9ec2d-8cc7-4128-a9f2-6827a6d43d6f">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000001 tBTC from Aptos (Spika) to Sui (Sui wallet). 0 SUI is shown as gas fee.
* Send from tx: [Aptos explorer](https://explorer.aptoslabs.com/txn/0xc92a5ed638dc4c9f44f7b815fb2db192819e0dbba227f1ec62cb3dbb6883c5a6?network=mainnet)
* Send to tx: [Sui explorer](https://suiexplorer.com/txblock/CuQdbAdbarvXQk6z4uddNtMkD4NzodJXjbhp2XV6vazH)

![Screenshot 2024-01-03 at 10 48 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/47202cbf-bb89-4222-a01f-99371718fee2)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/#
Gas fee for Base shown as 0 ETH(Base)
Attachment:
![Screenshot 2024-01-16 at 10 52 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0f73b143-4db8-4f4b-94b2-e72c688b12b4)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portal-bridge-ui.pages.dev/59e0c1fff9/#
Attachment:

![Screenshot 2024-01-17 at 14 43 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0d5e1b22-2eb2-4b2e-a517-2a2e8e58e478)

![Screenshot 2024-01-17 at 14 43 02](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e4548dbf-d103-439f-af83-da96a1121f81)

**Comment by AigaD** [comment]
Tested from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/
Fee shown as 0
Attachment:

<img width="1036" alt="Screenshot 2024-01-24 at 09 47 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f9e1c80a-9574-4272-be1e-4b2891e15c9d">

<img width="458" alt="Screenshot 2024-01-24 at 09 49 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/02d59088-5f4b-475b-97b0-f760566caf43">

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/#
Attachment:
![Screenshot 2024-02-01 at 11 12 21](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ee5fff51-519c-4d78-8d1d-8631567777f5)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when sending 1 BONK from BSC (MetaMask) to Solana (Backpack). 0 SOL is shown as gas fee. 
* Send from tx: [BscScan](https://bscscan.com/tx/0x56d76c9f391460b79e34d1d75324eba385d16e9bbf29976944f3dedca63c8a4d)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/3U5qKyM2YAfwun7qxgcwAboTxJghRWHDPj6fjfZMoZgSkKT1puG9wbEGYjVqhC5vCmF9Fgt839GU6NVGo9BVRBgC)


![Screenshot 2024-03-10 at 11 05 51](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2cb24161-0337-4c94-971e-5e1469712809)

**Comment by tsadovska** [comment]
Rechecked scenarios mentioned in the ticket. 
Remaining issues:
* #1782
* #1839
* #1899
* #1902

Ticket is closed.
