### ISSUE TITLE
[QA] Improvement: User should be informed that amount should be increased to proceed the transaction

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#652]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/   [Testnet]

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Keplr wallet in To section
3. Prepare to send ETH from Goerli to Sei
4. Type too small amount, in my case 0.0000000000000000001
5. Click “Approve and proceed with transaction” button

#### Actual result:
Error is displayed in Console:

```
Error: invalid decimal value (argument="value", value="1e-19", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at f.throwArgumentError (index.ts:285:21)
    at h (fixednumber.ts:76:16)
    at Module.c (index.ts:80:12)
    at index.ts:165:21
    at Object.onClick (Send.tsx:109:26)
```

#### Expected result:
User should be informed that the amount should be increased to proceed the transaction.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-30 at 13 24 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3a2718e1-819d-49ca-8dd3-fe6562900e70)

**Comment by AigaD** [comment]
This is also reproduced on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe445793-4aff-42a7-a6aa-3f1c643d9b9c

<img width="1335" alt="Screenshot 2023-06-28 at 09 32 39" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1e4b2117-6dc1-4ff3-84b1-4b570b6c981a">

**Comment by tsadovska** [comment]
Reproduced on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending 0.00000000000000001 WFTM from Base (Metamask) to Sui (Nightly). 
Error in Console: 
```
Error: invalid decimal value (argument="value", value="1e-17", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at l.throwArgumentError (index.ts:285:21)
    at h (fixednumber.ts:76:16)
    at Module.c (index.ts:80:12)
    at index.ts:165:21
    at Object.onClick (Send.tsx:104:26)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending assets to :
* Aptos (scenario: send 0.00000000000001 ETH from Goerli to Aptos)
* Sei (scenario: send 0.00000000000001 BNB from BSC to Sei)
* Sui (scenario: send 0.00000000000001 CELO from Alfajores to Sui)
* Base Goeli (scenario: send 0.00000000000001 FTM from Fantom to Base Goerli)
* Solana (scenario: send 0.00000000000001 CELO from Alfajores to Solana)
* Moonbase (scenario: send 0.00000000000001 AVAX from Fuji to Moonbase)

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending 9e-8 from Osmosis (Leap) to Goerli (Metamask).

- Warning message about minimal sending amount is not displayed.
- Warning message "Error sending transfer, please try again" is shown.
- Error is displayed for the user:
```
Error: invalid decimal value (argument="value", value="9e-8", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at f.makeError (main.aac608af.js:37:4463233)
    at f.throwError (main.aac608af.js:37:4463353)
    at f.throwArgumentError (main.aac608af.js:37:4463408)
    at h (main.aac608af.js:37:4345075)
    at Module.d (main.aac608af.js:37:4596665)
    at Lf.send (main.aac608af.js:110:153334)
    at xb.send (main.aac608af.js:110:198303)
    at Object.onClick (main.aac608af.js:137:24101)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6463262e-53a8-4bbf-a677-5e8f17da8c71)

**Comment by AigaD** [comment]
Tested OK. User can no longer type in more than 7 digits after comma in the amount section.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#
Improvement regarding showing small amounts that is being sent, reported here: https://github.com/wormhole-foundation/wormhole-connect/issues/1023

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5e6d1cda-e0b5-4a87-a35f-45b1f98e4fb4
