### ISSUE TITLE
[QA] Gas payment option should be “Pay with 2 transactions” when sending assets to Sei network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#653]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/   [Testnet]

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Keplr wallet in To section
3. Prepare to send 0.01 AVAX from Fuji to Sei
4. Observe “Gas payment” section

#### Actual result:
Gas payment option is “Pay with AVAX (one transaction)”.

#### Expected result:
Gas payment option is “Pay with AVAX & SEI (two transactions)”.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-30 at 13 45 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/447f3c22-295d-4c81-a308-cd54524f8f3f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenarios:
* Send ETH / WBNB from Goerli to Sei
* Send MATIC / WBNB from Mumbai to Sei
* Send BNB / WAVAX from BSC to Sei
* Send AVAX / WFTM from Fuji to Sei
* Send FTM from Fantom to Sei
* Send CELO from Alfajores to Sei
* Send CELO / GLMR from Moonbase to Sei
* Send SOL from Solana to Sei
* Send SUI from Sui to Sei
* Send SUI / APT from Aptos to Sei

Issues will be rechecked on mainnet after deployment.

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
This is reproducible. For transaction to Sei in Preview Total fee estimates are shown for both source and destination chain, should be only shown for source chain gas estimate
Tested from:https://wormhole-connect.netlify.app/
Attachment:
![Screenshot 2023-10-17 at 15 00 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6b889555-14d4-43cf-8209-7622ce195e42)
![Screenshot 2023-10-17 at 15 00 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf268010-8fd5-44b9-9743-c158aada0b31)

**Comment by tsadovska** [comment]
Latest observations added to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1455.

Ticket is closed.
