### ISSUE TITLE
[QA] Asset balance when selecting Sei Network is no longer loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#655]
Preconditions:
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Steps:
1. Connect Keplr wallet at sending From section
2. Select Sei Network
3. Click on assets
4. Observe balance

Actual result: Balance when selecting Sei Network is no longer loading, console throws `has been blocked by CORS policy: `

Expected result: Balance is loaded

Comments: Balance was loading before, but at one moment this error appeared and balance was no longer showing.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ce50407b-fe11-43e8-ad04-63bb7c5feee2

**Comment by M-Picco** [comment]
Closing this since it's an issue with the default testnet rpc node, which should now be more stable than by the time this tests were carried out.
