### ISSUE TITLE
[QA] Transactions from/to Sei Network are stuck in Step 2 for more than 24 hours

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#661]
Preconditions:
Metamask wallet connected ar sending From section
Keplr wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Steps:
1. Prepare to send FTM from Fantom to Sei
2. Click Approve and proceed with transaction
3. Observe

Actual result: Multiple transactions are stuck in Step 2 loading process for more than 24 hours either when sending to or from Sei Network

Expected result: Transaction is complete

Attachment:
Click on Resume Transfer and paste any of these transaction hashes
TX hashes:
Fantom: 0x7b359c2304d0faad248f5c53e1590631501b4f0e726268f2815172f8d7876fa2 (https://testnet.ftmscan.com/tx/0x7b359c2304d0faad248f5c53e1590631501b4f0e726268f2815172f8d7876fa2)
Fantom: 0xf956716ec6d052f814b32163a5f38f76fb2a138f40090ffd42eb3094e0bbface (https://testnet.ftmscan.com/tx/0xf956716ec6d052f814b32163a5f38f76fb2a138f40090ffd42eb3094e0bbface)
Alfajores: 0x287ccf8797b925c189f3cd0551da7c0f4e29ac397dd21e691c1245dbcc645f8e (https://explorer.celo.org/alfajores/tx/0x287ccf8797b925c189f3cd0551da7c0f4e29ac397dd21e691c1245dbcc645f8e )
Moonbase: 0xb46bbcdc23c17fa95583870d4745b2fe6a818bf25e1bae17eae6e7a94be3e720 (https://moonbase.moonscan.io/tx/0xb46bbcdc23c17fa95583870d4745b2fe6a818bf25e1bae17eae6e7a94be3e720)
Sei: 6A1E05272F2A972FF7FC88771732F81B884A7C62D538C83C1F2AAEE81B31917E (https://sei.explorers.guru/transaction/6A1E05272F2A972FF7FC88771732F81B884A7C62D538C83C1F2AAEE81B31917E)
Sei: 248C7FB78C89F8474158D01801C08A20A205821B5FE3EA449F7C4B6095B1A0D9 (https://sei.explorers.guru/transaction/248C7FB78C89F8474158D01801C08A20A205821B5FE3EA449F7C4B6095B1A0D9)

<img width="1334" alt="Screenshot 2023-06-01 at 16 15 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8e63e129-f557-4897-9670-b681633db431">

**Comment by tsadovska** [comment]
Rechecked transactions from the ticket description:

1) Transaction is completed, link to Sei explorer is not displayed ( ticket: #642 ):

* Fantom: `0x7b359c2304d0faad248f5c53e1590631501b4f0e726268f2815172f8d7876fa2` 

2) Transactions are still stuck in Step 2 (transactions started on May 30):
* Fantom: `0xf956716ec6d052f814b32163a5f38f76fb2a138f40090ffd42eb3094e0bbface`
* Alfajores: `0x287ccf8797b925c189f3cd0551da7c0f4e29ac397dd21e691c1245dbcc645f8e`
* Moonbase: `0xb46bbcdc23c17fa95583870d4745b2fe6a818bf25e1bae17eae6e7a94be3e720`

3) Transactions are not found ( ticket: #705 )
* Sei: `6A1E05272F2A972FF7FC88771732F81B884A7C62D538C83C1F2AAEE81B31917E`
* Sei: `248C7FB78C89F8474158D01801C08A20A205821B5FE3EA449F7C4B6095B1A0D9`

**Comment by tsadovska** [comment]
Transaction is stuck in Step 2 for more than 14 hours, loading does not finish. 
Build: https://wormhole-connect.netlify.app/ [Testnet].
Scenario: Send 0.05 AVAX from Fuji (Metamask) to Fantom (Metamask).
Sending from tx: [Snowtrace](https://testnet.snowtrace.io/tx/0x9c2b7bb8964efbe596439ad2004918c879ddca8b165fea93069466df5fbbc621), `0x9c2b7bb8964efbe596439ad2004918c879ddca8b165fea93069466df5fbbc621`

**Comment by AigaD** [comment]
Reproduced also from: https://base-relayer--wormhole-connect.netlify.app/#
Sending 0.02 FTM from Fantom -> Sei
TX https://testnet.ftmscan.com/tx/0xecb1160a988161d0c002fe4b5627028f4bc0e479bbd46d225e3735a67525ab3f

Sending 0.02 CELO Alfajores -> Sei
TX https://explorer.celo.org/alfajores/tx/0x5be78cab28feaf2862215a651bac901724b21dfd824cb5452ca776061d1ca0a4
Attachment:
<img width="1270" alt="Screenshot 2023-08-23 at 11 15 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9fd67ff0-e094-4796-b4e8-77807985eb1f">

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
This is reproducible.
Tested from: https://wormhole-connect.netlify.app/#
Transaction WAVAX from Fantom to Sei is not moving past Step 2.
Attachment:
TX hash: 0x1900f153d606f5f978d428d2ac10b1074fb94f6c55a56883e59d0cf103d985fb (https://testnet.ftmscan.com/tx/0x1900f153d606f5f978d428d2ac10b1074fb94f6c55a56883e59d0cf103d985fb)

![Screenshot 2023-10-17 at 09 58 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d5167603-68c7-4499-a0e1-1388fa71316d)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending assets from Sei. Transaction is stuck on Step 2 when sending 0.001 SUI from Sei (Fin) to Fuji (Metamask). Sei explorer link is not found, #671.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ac6361c2-1cfa-480e-8fdc-b8fc5cd1c9a9)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Transaction 0.01 WFTM from Cosmoshub to Sei stuck on Step 2 for more than a day. Mintscan - https://testnet.mintscan.io/cosmoshub-testnet/txs/AE7E781D92B255FE4A1BE5A04EEE454D40E14510FBDDCB73132F33D851D1EEB0
Attachment:

![Screenshot 2023-10-20 at 17 02 39](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8ff976a0-e8c4-4d81-890b-480029c75b17)

**Comment by AigaD** [comment]
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1371

**Comment by tsadovska** [comment]
Issue is split into https://github.com/wormhole-foundation/wormhole-connect/issues/762 and https://github.com/wormhole-foundation/wormhole-connect/issues/1152. 

Ticket is closed.
