### ISSUE TITLE
[QA]Internal JSON-RPC error, when sending CELO from Alfajores to Sei

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#667]
Preconditions:
1. Metamask wallet connected ar sending From section
2. Keplr wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.1 CELO from Alfajores to Sei
2. Click Approve and proceed with transaction
3. Observe

Actual result: Error in console: `MetaMask - RPC Error: Internal JSON-RPC error.` and "Error sending transfer, please try again" is shown when sending Celo from Alajores to Sei

Expected result: Transaction is complete

Attachment:
<img width="1292" alt="Screenshot 2023-06-06 at 10 28 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/06d9edf0-36d6-44e0-a396-0a29754c23cc">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c8e57381-ae8a-4c3b-b39d-c17351af076b

**Comment by M-Picco** [comment]
Closing it as it's related to issues with the Celo rpc node.
