### ISSUE TITLE
[QA] [Nightly wallet] User is not able to Claim token 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#669]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Keplr wallet in ‘From’ section
2. Connect Nightly wallet in ‘To’ section
3. Send 0.0001 SEI from Sei to Aptos
4. Click Claim button on Redeem screen

#### Actual result:

- “Your claim has failed, please try again” is displayed to the user
- Error is displayed in Console:

```
TypeError: Cannot read properties of undefined (reading 'data')
    at f.<anonymous> (NightlyWallet.ts:283:80)
    at Generator.throw (<anonymous>)
    at s (MsafeWallet.ts:34:1)
```

#### Expected result:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-06-06 at 22 18 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/18cbfb37-b1e5-4861-b63c-76ad1a89fae6)

**Comment by M-Picco** [comment]
@tsadovska Have you tried with other wallets than Nightly? I tried with Martian and had no issues.

The weird thing is that I could reproduce the error when using Nightly in the preview site, but I had no issues with a local setup. I'll have to look into it later.

**Comment by tsadovska** [comment]
@M-Picco Rechecked the scenario from the description. It is reproducible only with Nightly wallet. 

Issue is not reproducible with following wallets:
* Martian
* Rise Wallet
* Pontem
* Fewcha
* Spika

Couldn't check these wallets because of errors:
* Snap wallet (ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/646 )
* Petra wallet (ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/682)
* BitKeep (ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/683)

Build: https://feature-sei--wormhole-connect.netlify.app/

**Comment by tsadovska** [comment]
Issue **is reproducible** on https://wormhole-connect.netlify.app/ when:
* User sends WBNB / WAVAX  from Goerli (Metamask wallet) to Aptos (Nightly wallet)
* User sends WBNB from Mumbai (Metamask wallet) to Aptos (Nightly wallet)

Error is displayed in Console:
```
TypeError: Cannot read properties of undefined (reading 'data')
    at l.<anonymous> (main.f2ca49db.js:37:9983998)
    at Generator.throw (<anonymous>)
    at s (main.f2ca49db.js:37:9979271)
```
Wallets:
* Metamask: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
* Nightly: 0xa38d975411d11659cb322353a0403e537318d90b88d0f5b51fcf567429eda1e9

Send from transactions:
* [Goerli-WBNB](https://goerli.etherscan.io/tx/0x69fb495fea08715b0324f02230ba7c7b0b520f68018f8f6de8652247a42d4d43) 
* [Goerli-WAVAX](https://goerli.etherscan.io/tx/0x5ad4ef30b6dd19a5241313a48a6ce66e883cedc68caba6d8e6f3a8ca30bc7539)
* [Mumbai-WBNB](https://mumbai.polygonscan.com/tx/0xaa1bd26301de6437fafd9600e8595d90a488296e91e30afda805f9816e7dbf83)


<img width="1129" alt="Screenshot 2023-06-23 at 12 00 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ede4d6c5-5856-4c20-9827-a0f57152fa8c">


Issue **is not reproducible** when:
* User sends WBNB from Goerli (Metamask wallet) to Aptos (Spika wallet)
* User sends WBNB from Mumbai (Metamask wallet) to Aptos (Spika wallet)
* User sends WBNB from Goerli (Metamask wallet) to Aptos (Martian wallet)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ when user sends MATIC from Mumbai to Aptos. 
* Sending From tx: [Polygon](https://polygonscan.com/tx/0x7d82d8cc26e0426093e6cd64dd14f50dd566f7ba004f8fddfa2c112d4d02fc4a)
* Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
* Nightly wallet: 0x1a6db99037870ac64ec3ecf51c76895d10a6627a932a908ae4023e2df3a5efe3
* Error in Console:

```
TypeError: Cannot read properties of undefined (reading 'data')
    at l.<anonymous> (main.d13e45d0.js:37:7666098)
    at Generator.throw (<anonymous>)
```

<img width="1148" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/44efba27-ea55-4df4-996c-aeab89b5bd0f">

**Comment by tsadovska** [comment]
Rechecked scenarios from the ticket on https://wormhole-connect.netlify.app/ [Testnet]. Some of scenarios are not reproducible, but some of them are still present. 

- Send WBNB from Goerli (Metamask wallet) to Aptos (Nightly wallet) - [Goerli](https://goerli.etherscan.io/tx/0x967ea9cae087dd38684dcd8baa59250ea27c362e564d3b6751727b7b67386d80), [Aptos](https://explorer.aptoslabs.com/txn/0x83800b8612f596e10624c56c32984677f945e55cb49e2d9170be94edeab0c4e3?network=testnet) **Tested OK**
- Send WAVAX from Goerli (Metamask wallet) to Aptos (Nightly wallet) - [Goerli](https://goerli.etherscan.io/tx/0x83491c6c1dee60f776d894f42810fb3527129a519c343a1d4b36a64558625d36),  **Tested NOK** (“TypeError: Cannot read properties of undefined (reading 'data')” is displayed in Console when user clicks on "Claim" button)
- Send MATIC from Mumbai (Metamask wallet) to Aptos (Nightly wallet) - [Mumbai](https://mumbai.polygonscan.com/tx/0x4d391af762d30bbf968a3d8bdd98aace14c00e5bb0d7143abad262d03247ba9d), [Aptos](https://explorer.aptoslabs.com/txn/0x98c600c6f742dba200060a5e01165d0d4884dc03e38bca4b49e01b189e156b51?network=testnet) **Tested OK** 
- Send WBNB from Mumbai (Metamask wallet) to Aptos (Nightly wallet) - [Mumbai](https://mumbai.polygonscan.com/tx/0xf42938ecbc1d09b9b303bb86b742b1bb90b2ae0cc18b711252a4794dd4f773ee), **Tested NOK** (“TypeError: Cannot read properties of undefined (reading 'data')” is displayed in Console when user clicks on "Claim" button)
- Send SEI from Sei (Compass wallet) to Aptos (Nightly wallet) - [Sei](https://sei.explorers.guru/transaction/0ABF1701FAB0F32A345A5E5D153DF2C0EACAE5085828D8D791B2F224BA769360), **Tested NOK**(“TypeError: Cannot read properties of undefined (reading 'data')” is displayed in Console when user clicks on "Claim" button)

Rechecked scenario from the ticket on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. 

- Send MATIC from Polygon (Metamask wallet) to Aptos (Nightly wallet) - [Polygon](https://polygonscan.com/tx/0x95a4722a861a716d346f9df5e64908d57e754e43ddffc56f4796455a96cc82cd), **Tested NOK** (“TypeError: Cannot read properties of undefined (reading 'data')” is displayed in Console)

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect.netlify.app/ [Testnet].
Issue is not reproducible when sending AVAX from Fuji (Metamask) to Aptos (Nightly), tx ([Fuji](https://testnet.snowtrace.io/tx/0xd63d4df785798558ec43d2cf491da5e924dda8cd92ffd861cf443d9e3461aed8), [Aptos](https://explorer.aptoslabs.com/txn/0xf96fc0234833700ad69b4508cc6d20b15647aef410130899187a34f715b17c90?network=testnet)).


Can reproduced the issue with following scenarios:
* Send WAVAX from Goerli (Metamask) to Aptos (Nightly) - Tested NOK ([Goerli](https://goerli.etherscan.io/tx/0x00af993c151c4105f3770e40654b33e10e3ab3b002c3f1b26be670fe517a5ac6), TypeError: Cannot read properties of undefined (reading 'data') is displayed in Console when user clicks on "Claim" button)
* Send SEI from Sei (Compass wallet) to Aptos (Nightly) - Tested NOK ([Sei](https://sei.explorers.guru/transaction/7D60B983F31DF37419062F5B3B174046EF273BE74129BE0DDF70AE9720325610), TypeError: Cannot read properties of undefined (reading 'data') is displayed in Console when user clicks on "Claim" button)

**Comment by AigaD** [comment]
Issue is reproducible from https://base-relayer--wormhole-connect.netlify.app/# when sending assets from Base Goerli (Metamask) to Aptos (Nightly)

Attachment:

<img width="1340" alt="Screenshot 2023-08-10 at 16 24 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e1461df9-55d2-40c8-ab40-ce55711e3ed3">

**Comment by AigaD** [comment]
Also for transaction Fuji (Metamask) -> Aptos (Nightly), user cannot Claim tokens
Tested from: https://base-relayer--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/969663de-63e7-4377-86dd-da2d038eb86c

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/. See: https://github.com/XLabs/portal-bridge-ui/issues/368

**Comment by AigaD** [comment]
Issue reproducible from https://feat-cosmos-gateways--wormhole-connect.netlify.app/# when sending APT asset from Osmosis (Keplr) to Aptos (Nightly).
Attachment:
<img width="1336" alt="Screenshot 2023-09-06 at 17 16 56" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8e146013-05e2-468c-9a82-0f1ab8fb97e5">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WBNB from Goerli (Metamask) to Aptos (Nightly). Nightly wallet is connected to Testnet. User has some APT in the wallet. 

Error is displayed in Console:
```
TypeError: Cannot read properties of undefined (reading 'data')
    at l.<anonymous> (main.85265285.js:37:4387338)
    at Generator.throw (<anonymous>)
    at s (main.85265285.js:37:4382611)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a1eae289-8ede-4aae-9acf-e3672831d921)
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/21b64599-e4aa-4f41-8ed1-3cc043893e9a)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction fails at Claim. Reason `TypeError: Cannot read properties of undefined (reading 'data')`
Transaction: 0.01 WAVAX from Cosmoshub (Leap) to Aptos (Nightly)
Attachment:

![Screenshot 2023-10-19 at 11 45 44](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/709e2963-1d0a-475f-a4f4-e43a6a4e8ff4)

**Comment by AigaD** [comment]
Transaction Solana (Solflare) to Aptos (Nightly) fails at Claim. Reason `Cannot read properties of undefined (reading 'data')`
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1267" alt="Screenshot 2023-10-23 at 15 56 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/804bfdf9-67af-414c-b50f-6464e01032ae">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction Evmos (Leap) to Aptos (Nightly) fails at Claim, reason `TypeError: Cannot read properties of undefined (reading 'data')`

Attachment:
![Screenshot 2023-11-08 at 11 27 20](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bc65fc6a-6f04-4280-b0ac-d36046610666)

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/
Transaction Goerli (Metamask) -> Aptos (Nightly) fails at Claim, reason: `ypeError: Cannot read properties of undefined (reading 'data')`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/084c5eda-654c-40ca-abd7-a66323b15edb

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://portalbridge.com/# and https://wormhole-connect.netlify.app/#
Transaction from [Polygon](https://polygonscan.com/tx/0x5ea1795f28d91e1f25e9008e4f198b81537966b058a734437e6feb044127eaec) (Metamask ) to [Aptos](https://explorer.aptoslabs.com/txn/0x80319f028941346dbb8a0c61fd5687ceddcbc4a7cb711c4ba562635e78fbc152?network=mainnet) (Nightly) tested OK
Transaction from [Goerli](https://goerli.etherscan.io/tx/0x66c98916e982f35ef051e0efcbabe61ee3bff44586e78274aaa46c9aed5e9dd7) (Metamask) to [Aptos](https://explorer.aptoslabs.com/txn/0xea2729fd8d370ebe3706a4bad8fb46e39add1c73a0ee7116cd98c7b9da72823e?network=testnet) (Nightly) tested OK

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d8274cd5-904d-415d-87ce-7d8c6c556604


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2cf29312-874c-42de-8fda-321791fa953b
