### ISSUE TITLE
[QA] Sei Explorer link opens “No results found” error page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#671]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Metamask wallet in ‘From’ section
2. Connect Keplr wallet in ‘To’ section
3. Send 0.0001 WMATIC from Goerli to Sei
4. Click link to Sei Explorer on Redeem screen

#### Actual result:

- Sei Explorer link opens “No results found” error page
- Goerli tx:
https://goerli.etherscan.io/tx/0xc8f1920823fb371a04d167ae2aa9482f1859902c5cb0c7897a36bffdbbc71105 
https://goerli.etherscan.io/tx/0x4c157c25bbd6dc6d81d5b219f54761c329c939f53815b70dd784501c3b274b3e

#### Expected result:
Sei Explorer link opens Transaction Details page.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachments:
<img width="1577" alt="Sei-Explorer_1" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/053261b1-93e5-4a1b-b478-14e7e65a0b53">
<img width="1575" alt="Sei-Explorer_2" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0278f427-0329-4070-9c33-034539c79029">

**Comment by AigaD** [comment]
Same behaviour reproduced from: https://base-relayer--wormhole-connect.netlify.app/#
Sei explorer link opens page "No results found"
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f98ae7bf-81f2-4bc2-8005-81dc438cfc64

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
This is still reproducible.
Tested from: https://wormhole-connect.netlify.app/
https://sei.explorers.guru/not-found

**Comment by tsadovska** [comment]
Also noticed this issue today when sending 0.001 SUI from Sei (Fin wallet) to Fuji (Metamask). 
Build: https://wormhole-connect.netlify.app/ [Testnet]


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/84f63971-568b-474b-887e-f0dd64b79683

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet] when sending 0.1 SEI from Sei (Leap) to Solana (Phantom). Sei explorer link opens "No results found" error page.
