### ISSUE TITLE
[Tracking] New wallet sanctions screening methodology

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#673]
## Describe the issue in detail

The previous proposal for screening sanctioned wallets (#496) required using a free API endpoint that has low rate limits, which is likely to cause developer and end user friction when those rate limits are hit. Users could approach TRM for a paid API key, but that has high costs and introduces significant developer adoption friction.

## What is the expected/desired behavior

Alternatively, we propose a two-staged solution:

- [x] #674 - Fetch the OFAC sanctioned wallet list directly from the Treasury website, hard code those wallets (<300) into a config or const file, and screen connected wallets against that list
- [x] #675 - Add a CI or other job that pulls the OFAC list and updates the hard coded list on a regular basis

**Comment by heyitaki** [comment]
Closed by #688
