### ISSUE TITLE
[Enhancement] Add CI job to update OFAC block list

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#675]
## Describe the issue in detail

Part 2 of #673 

Add CI or other job that regularly pulls the OFAC list from the source of truth and updates hard coded list from #674 on a regular basis.

## What is the expected/desired behavior

- OFAC Treasury SDN site: https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schemas
- Pull `SDN.csv` file: https://www.treasury.gov/ofac/downloads/sdn.csv
- Filter for addresses (see #674)
- Update OFAC block list const file with any new addresses
- Build CI job that performs this on a regular basis - you could consider running this as part of a production build CI job, or alternatively on every CI run (which may cause flakey CI runs if the Treasury site is unavailable)

**Comment by heyitaki** [comment]
Closed by #688
