### ISSUE TITLE
[QA] [Sui] Asset list and Balance in wormhole-connect are different from Asset list and Balance in the wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#681]
#### Builds:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]
https://wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Sui wallet (my account details: 0xa4055514cc6ce87f54250bf954e0f5b9f5b3ce48bea3ff0af687a20e63b312b8)
2. Select Sui network in ‘From’ section
3. Open Assets list

#### Actual result:

- SUI Balance in wormhole-connect is different from Balance in Sui wallet
- tBTC and WMATIC assets are not displayed in wormhole-connect

#### Expected result:
Same assets should be displayed in wormhole-connect and in the wallet. Assets should have the same balance. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachments:
![Screenshot 2023-06-09 at 15 25 47](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/063fd958-8cc5-476a-b168-85d198af3140)
![Screenshot 2023-06-09 at 15 26 38](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/556c7cb6-8177-4da2-9ebe-216b97598113)

**Comment by M-Picco** [comment]
`tBTC` is not offered on wh connect testnet yet, so it won't be listed.

However, `WMATIC` should show up. Do you remember which network you transferred the tokens from?

**Comment by tsadovska** [comment]
Rechecked the issue on https://feature-sei--wormhole-connect.netlify.app/ and it is no longer reproducible. Same assets are displayed in wormhole-connect and in the wallet. 

* wormhole-connect
<img width="404" alt="Screenshot 2023-06-15 at 21 14 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9d878ecb-c2c9-40f1-93fb-cbb8a8b907d1">

* Sui wallet


<img width="358" alt="Screenshot 2023-06-15 at 21 15 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/30015a85-26e7-4526-8603-095d90fffd6a">
