### ISSUE TITLE
[QA] [Petra] Empty wallet notification is opened 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#682]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Preconditions:
* “Petra Aptos Wallet” extension is installed and is enabled
*  Petra wallet **is not created** in Petra extention

#### Steps:

1. Select Aptos network in ‘From’ section
2. Connect Petra wallet in ‘From’ section

#### Actual result:
Empty wallet notification is opened.

#### Expected result:
(need to be specified)

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-06-09 at 16 02 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/68affe2d-d6e2-47bc-98a1-c310064eaf73)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ with the scenario from the description.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dd85a45d-0874-4524-b1a1-11a5483ce34c

**Comment by AigaD** [comment]
Issue also reproducible on Mainnet - https://mainnet--wormhole-connect.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4982f077-fb23-4d83-97a6-a9d58dc027be

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Ticket is closed.
