### ISSUE TITLE
[QA] [Sei] Notification from BitKeep wallet is opened instead of Keplr wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#683]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Preconditions:

- “BitKeep: Crypto & NFT Wallet” extension is installed and is enabled
- “Keplr” extension is installed and is enabled

#### Steps:

1. Select Sei network in ‘From’ section
2. Connect Keplr wallet in ‘From’ section

#### Actual result:
“BitKeep Wallet” notification is opened.

#### Expected result:
Kepler wallet notification is opened.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9e951e94-16fb-487a-802b-1f775f22b26b

**Comment by AigaD** [comment]
The same behaviour noticed also when trying to connect Keplr wallet with Coin98 installed.
Preconditions: Keplr and Coin98 wallets are installed
Build: https://feature-sei--wormhole-connect.netlify.app/# 
Steps: 
1. At sending to section click connect wallet
2. Click Keplr
3. Observe

Actual result: Coin98 pop-up window is shown to Confirm the connection
Expected result: Keplr wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/552c68c1-4015-4832-b149-e1f0a03db6d7

**Comment by aadam-10** [comment]
investigated and the issue is with BitKeep wallet, and it only happens in the edge case where the person has a lot of wallets installed, which is not a very frequent usecase.
