### ISSUE TITLE
[QA] [Fewcha] “Error: Transaction issue” when sending assets from Aptos 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#684]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Fewcha wallet in ‘From’ section
2. Connect Metamask wallet in ‘To’ section
3. Select Aptos network in ‘From’ section 
4. Select Goerli network in ‘To’ section
5. Select SEI asset
6. Type Amount, in my case 0.001
7. Click “Approve and proceed with transaction”

#### Actual result:
Error is displayed in Console:

```
Send.tsx:141 Error: Transaction issue
    at c.<anonymous> (FewchaWallet.ts:240:15)
    at Generator.next (<anonymous>)
    at a (Coin98Wallet.ts:66:1)
```

#### Expected result:
Transaction proceeds without errors.

#### Note:
Issue is not reproducible when Martian or Spika wallet is connected in ‘From’ section. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-12 at 21 33 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cf359128-1774-46ea-a893-1ce4e1bee082)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ when sending APT from Aptos to Mumbai.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1c08fb3a-c9d2-41dd-9fc6-4d6d6069161a)

**Comment by AigaD** [comment]
Issue is also reproducible on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Scenario:
Send 0.001 APT from Aptos (Fewcha wallet) to Goerli (Metamask wallet)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a99ce0b7-4912-46fb-ace2-a2f18ab65736

**Comment by tsadovska** [comment]
Issue will be rechecked after #946 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 SEI from Aptos (Fewcha) to Goerli (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x7d76fa1bc1b934beea7a08197c5156ae4a392acfcd36832cb5bc00b462bffafb?network=testnet), [Etherscan](https://goerli.etherscan.io/tx/0x130e538e0745dec3b67c031cdaa985ce57c1fdd41302724322a6fb4043fd5de6).

Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 APT from Aptos (Fewcha) to Ethereum (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x3098c02d36c3db6352b06386854f95e062d8da28e45dead64603b878cba5a368), [Etherscan](https://etherscan.io/tx/0xe738db7f87dba768126e972386a51c2fd49316150ef017490491306a80d5bec8).

Ticket is closed.
