### ISSUE TITLE
[QA] Instead of Claim "Connect Wallet" was displayed, but the connection did not happen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#685]
Preconditions:
Metamask wallet is connected at sending From section
Keplr wallet is connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 Sei from Fantom to Sei
2. Click Approve and proceed with transaction

Actual result: Instead of Claim button Connect "wallet address" was shown to the user, was not able to connect to the wallet as the action was in a loop. (TX - https://testnet.ftmscan.com/tx/0x193b8c2e4b7c8d7a02f183c1c920b95faecb54e1f5d9c067c6a2bcf24722881e)

Expected result: Button Claim is displayed and transaction is complete.

Comments: Happened also during Sei transaction from Alfajores to Sei (TX - https://explorer.celo.org/alfajores/tx/0x3daf39abe40d6d4417ffc91665a99a8adea443e3605e58dc44c38bdd44d63f0b )
Solana->Sei (TX- https://explorer.solana.com/tx/wubve9G6z82LFoQnVPzGKKAUoJojSywpTYNRQ5NPB3ZqBBGB3wDCBoTPwcp7pbiGbjFStT8RoT8ga43L9FmN2CP?cluster=devnet)
Moonbase->Sei (TX-https://moonbase.moonscan.io/tx/0xedd7bca2fcf29031942b8d66025dc8415c002b237a92357470487e2f13cb721d )

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d0000434-855b-40e4-a865-3eed3b6fca29

<img width="879" alt="Screenshot 2023-06-13 at 12 10 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1559aabe-f584-441a-ab71-ec9850428335">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/93d217a6-8740-4d0e-a450-5fa91a0deedc

<img width="1326" alt="Screenshot 2023-06-13 at 14 58 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/779f45d9-cd9e-49a5-afc8-850d3fe5bd6e">

<img width="1158" alt="Screenshot 2023-06-16 at 12 33 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8ec150be-e47a-485e-afa4-f1435842cd53">

**Comment by AigaD** [comment]
Issue reproduced also from https://wormhole-connect.netlify.app/#
TX Solana -> Mumbai 2DCjS4ibdZ6VQQkFCwHFfFR9UAUkE2jVNUuDG4FmVpcJ4gfiJ7Z3fUUYdZwRPFxhYpsBAtjngoDo8skkyCg8h9Ek
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f443d648-605d-4d68-b9e5-44e9435c0fd0

**Comment by AigaD** [comment]
Tested OK for transaction Solana -> Mumbai
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf6c7dcf-5bff-4221-9df5-c034bff18036

Transaction with Sei will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/954 is closed

**Comment by AigaD** [comment]
Will be checked after https://github.com/wormhole-foundation/wormhole-connect/issues/661 is resolved.
Transaction is not moving forward Step 2
Attachment:
![Screenshot 2023-10-17 at 17 41 58](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/354d3a4f-6580-4d92-a0de-ea110f9d8d8b)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1152 is resolved.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Cannot reconnect to Sei Keplr wallet at resume transaction screen
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7bd4b95a-16f1-4f68-925f-76f96fe38e08

**Comment by tsadovska** [comment]
Remaining issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2394.
