### ISSUE TITLE
[QA] ApiError when sending assets to Aptos 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#686]
#### Builds:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]
https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/# [Testnet]

#### Steps:

1. Connect Metamask wallet in ‘From’ section
2. Connect Fewcha wallet in ‘To’ section
3. Select Goerli network in ‘From’ section 
4. Select Aptos network in ‘To’ section
5. Select ETH asset
6. Type Amount, in my case 0.001
7. Click “Approve and proceed with transaction”
8. Click “Claim” button on Redeem screen

#### Actual result:
Error is displayed in Console:

```
ApiError: Bad Request
at request.ts:367:15
at request.ts:403:17
```

#### Expected result:
Transaction proceeds without errors.

#### Notes:
Issue is also reproducible when:

- User sends MATIC from Mumbai to Aptos (Fewcha wallet)
- User sends CELO from Alfajores to Aptos (Fewcha wallet)

Issue is not reproducible with other wallets:

- Martian
- Rise wallet
- Pontem

Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/684 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-13 at 14 00 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/41dbb6a4-2678-4a8c-bb20-416d95f6b19a)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ when user sends ETH from Goerli to Aptos. 
Wallets:
* Metamask: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
* Fewcha: 0x181963ee82838c2dcb73de0fc69492f754b3c9d35132c964c78b5638ba3849e3

Error in Console:
```
ApiError: Bad Request
    at main.f2ca49db.js:37:7188835
    at main.f2ca49db.js:37:7188893
 
```
![Screenshot 2023-06-22 at 20 15 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/afbc6148-bf47-4664-b621-2c050d47cdb5)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending WFTM from Avalanche (Metamask wallet) to Aptos (Fewcha wallet).
* Sending From tx: [Avalanche tx](https://snowtrace.io/tx/0x2bad768ebce2df8156c87aa18d2e2e9230c54f2155ed044b8bcb42368588fb58)
* Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
* Fewcha wallet: 0xab1dee95e84919ae7735980e7311353b30501da28117ee72cd80eb8322d2c556

Error in Console:
```
ApiError: Bad Request
    at main.d13e45d0.js:37:4995794
    at main.d13e45d0.js:37:4995852
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d63a6a83-4ff4-4a75-a1a4-500a8448a0bb)

**Comment by AigaD** [comment]
Issue reproducible when sending ETH from Goerli to Aptos on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Attachment:
<img width="1340" alt="Screenshot 2023-06-27 at 12 55 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5db4ea15-c79f-4c68-a881-c6a6b9215511">

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect.netlify.app/ [Testnet].
Can reproduce the issue with following scenarios:

- Send ETH from Goerli to Aptos (Fewcha)- [Goerli](https://goerli.etherscan.io/tx/0x3a0e89fce6f94c8e0b8beaa544a0a9dd3155a70ee8853b7d0f8c7e1b9db09e3e), claiming fails with ApiError
- Send BNB from BSC to Aptos (Fewcha) - [BSC](https://testnet.bscscan.com/tx/0x6926924e0fa8aa8d2f32a041784d9f73f03da1becd50995a9fb8d7142817e338), claiming fails with ApiError
- Send AVAX from Fuji to Aptos (Fewcha) - [Fuji](https://testnet.snowtrace.io/tx/0x372559b52932604ab597064ef772a73b7dba3703e2c6786de5746358d6f37e40), claiming fails with ApiError
- Send CELO from Alfajores to Aptos (Fewcha)- [Celo](https://explorer.celo.org/alfajores/tx/0x12df5faba49751dcfee32bc58c5a4c0a3c5777f6c0333678895befc8537ceaa3), claiming fails with ApiError
- Send SOL from Solana to Aptos (Fewcha)- [Solana](https://explorer.solana.com/tx/2AWmL2xDNjvkc4AoRPG7Lq5avXTNuDVbrr6sHdAjUXTjvatLRwQ79jyjGUiT2HWBd7CVoX5166tCruSYHEUNLxXV?cluster=devnet), claiming fails with ApiError 

Scenario “Send MATIC from Mumbai to Aptos (Fewcha)” will be rechecked after #771 is resolved.
Scenario “Send SEI from Sei to Aptos (Fewcha)” will be rechecked after #762 is resolved.
Following scenarios will be rechecked after #648 is resolved:
- Send FTM from Fantom to Aptos (Fewcha)
- Send GLMR from Moonbase to Aptos (Fewcha)
- Send SUI from Sui to Aptos (Fewcha)

**Comment by tsadovska** [comment]
Issue will be rechecked after #648 is resolved.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when:
* sending 0.0001 ETH from Ethereum (Metamask) to Aptos (Bitget)
* sending 0.0001 ETH from Ethereum (Metamask) to Aptos (Spika)

Error is displayed in Console:
```
ApiError: Unauthorized
    at main.50df7c53.js:37:13270769
    at main.50df7c53.js:37:13270827
```

1) Bitget
Send from tx: [Etherscan](https://etherscan.io/tx/0x3c085121179daf34c5dc19e9efa01ee5679d3c2de0e84029c3333761190a9c57)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3ddf8f15-4cfb-484d-a852-c2f88635ee65)

2) Spika
Send from tx: [Etherscan](https://etherscan.io/tx/0xd769e6e96bb023a31f2430c2f5e9e081ab21c0e0307f3f1690d897ee008e7906)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/79c55651-d7cc-47ca-a87e-cfa4b333bcbf)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 MATIC from Polygon (Metamask) to Aptos (Fewcha). Send from tx: [Polygonscan](https://polygonscan.com/tx/0x387bb9a11ddc59b0937fabcd15a49463a71360651b6b853fb1c98d4d7a5f2c37).

**Comment by tsadovska** [comment]
Tested OK:
* Check that transaction from Goerli (MetaMask) to Aptos (Spika) is successful on [testnet](https://wormhole-connect.netlify.app/) (Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x41cda246440fcc373a4a75bce2efc0d30fa613d97cc6942ac78e78621b099dc1), Send to tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x43384da2a21df9c2974f54d834b23e6759bd652068fff59484f06dd6f0184ef7?network=testnet))
* Check that transaction from Celo (MetaMask) to Aptos (Spika) is successful on [mainnet](https://wormhole-connect-mainnet.netlify.app/) (Send from tx: [Celo Explorer](https://explorer.celo.org/mainnet/tx/0x2dae632561c986d78eb961d41689f076632d3414eee6bf5cfaff28d7ddea2e46), Send to tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0xb3ac57bfe736e58d7ddf68221271c1ffa2b82542509ff916511cac8118c66b91?network=mainnet))
* Check that transaction from Aptos (Fewcha) to Fantom (Metamask) is successful on [testnet](https://wormhole-connect.netlify.app/) (Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0x0817286d21409dfb01986a2d12d2edc3c71c8965fadc850b01812ca1c5b61f65?network=testnet), Send to tx: [FtmScan](https://testnet.ftmscan.com/tx/0x42b097f7c581d483562f213fb6aa9ba35dce232cebd1aca0e6e452384fbc979b))
* Check that transaction from Aptos (Fewcha) to BSC (MetaMask) is successful on [mainnet](https://wormhole-connect-mainnet.netlify.app/) (Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0xc25fd6edc6128afdce81afc7a13640a556842a3191a1bc5df9f3f0eea876292f?network=mainnet), Send to tx: [BscScan](https://bscscan.com/tx/0x4ea40635b8ad42e2cd14afa08bdc6fd927e8d1c30850a2df685e427fe1109727))

Tested NOK:
* Check that transaction from Mumbai (Metamask) to Aptos (Fewcha) is successful on [testnet](https://wormhole-connect.netlify.app/) (Send from tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x76d1283ec704a0a50aa88b82d878415162ea32bfd373990e13b2940f76b04d1e), transaction fails), ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1652
* Check that transaction from Moonbeam (MetaMask) to Aptos (Fewcha) is successful on [mainnet](https://wormhole-connect-mainnet.netlify.app/) (Send from tx: [Moonscan](https://moonscan.io/tx/0x491db51b5968a17e01ad5a912785d340a2f2b1d65b5cc329dc8a813df675bdc5), transaction fails), ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1602

Ticket is closed.
