### ISSUE TITLE
[QA] [Sui] Incorrect wallet icon

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#689]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Click “Connect wallet” button
2. Observe “Fewcha Move” wallet icon and select the wallet

#### Actual result:

- Sui wallet icon is displayed next to "Fewcha Move" wallet 
- Fewcha wallet is opened and successfully connected

#### Expected result:
Fewcha Move wallet icon is displayed next to the wallet. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachments:
<img width="533" alt="fewcha - 1" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3da1411a-a1c4-4d69-ae22-cdb5191fbb68">
<img width="1289" alt="fewcha - 2" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3e846d54-31fc-4b01-8e88-e97a1061404b">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is also reproducible with BitKeep for SUI wallet. BitKeep for SUI wallet has Sui wallet icon instead of BitKeep wallet. Original issue: #706.

**Comment by tsadovska** [comment]
Issue is reproducible with Coin98 for SUI wallet. Coin98 for SUI wallet has Sui wallet icon instead of Coin98 wallet.

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/#
Attachment:
![Screenshot 2024-01-31 at 10 38 12](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3bab6419-2204-4292-ad05-a095c632f5d7)

**Comment by tsadovska** [comment]
Issue is still reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2). Sui icons are displayed in place of wallet icons. 

![image](https://github.com/user-attachments/assets/e2428c5c-2fcb-433e-9b7a-d0a5690035e1)

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/b1f3c5115d/. 

Attachment:
<img width="327" alt="Screenshot 2024-09-16 at 17 35 56" src="https://github.com/user-attachments/assets/d0235b92-d9ca-44cc-aa4c-67de18be9fb4">

**Comment by agodlevska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/. 
Closing the ticket. 

Attachment: 
<img width="328" alt="Screenshot 2024-10-21 at 10 07 18" src="https://github.com/user-attachments/assets/21cc451c-72e2-4f69-aba4-ae70ec0f3e3d">

**Comment by tsadovska** [comment]
Please view https://github.com/wormhole-foundation/wormhole-connect/issues/2957.
