### ISSUE TITLE
[QA] Balance not loading for transactions to Aptos

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#696]
Preconditions:
Wallets are connected
During test, had these preconditions:
Backpack wallet is connected at sending From section
Nigthly wallet is connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/#

Steps:
1. Select Solana Network at sending From section
2. Select Aptos Network at sending To section
3. Click on Assets list
4. Observe the balance

Actual result: Balance is not loading in the asset list, error ` "Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com." ` is shown in the console

Expected result: Asset balance is shown to the user

Comments: Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/650#issue-1731694720 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/be8ebec0-3f87-40ef-beb4-f1f46f18e05b

**Comment by tsadovska** [comment]
- Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when user connects Phantom wallet and selects Solana network (or visa versa, selects Solana network first and then connects Phantom wallet).
- Issue is not reproducible on https://wormhole-connect.netlify.app/ [Testnet]


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/33f6900f-f074-4c89-849e-bf1263f1d9ff

**Comment by AigaD** [comment]
Closing, issue is not longer reproducible. Tested from https://deploy-preview-1015--wormhole-connect.netlify.app/ / https://mainnet--wormhole-connect.netlify.app/  and https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e30ff842-9236-419c-bedb-b71aa8c5c4c9
