### ISSUE TITLE
[QA] Wallet Coin98 for SUI is un-clickable and incorrect icon is used

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#697]
Preconditions:
Wallets are not connected
Coin98 wallet is installed

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/#

Steps: 
1. Click Connect Wallet
2. Find Coin98 for SUI
3. Observe it and try to connect to it by clicking

Actual result: Coin98 for SUI is not clickable also the image for the icon is used as for SUI wallet and not Coin98 wallet

Expected result: Coin98 for SUI wallet option somehow reacts to the click of the user and correct icon image is used

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b4c62a51-daf4-4882-abd3-7be6d2aa630a

<img width="1351" alt="Screenshot 2023-06-15 at 11 04 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/495cfbdb-7d55-4321-a243-b325460517d4">

**Comment by tsadovska** [comment]
Issue is also reproducible with wallet "Coin98 for SEI". Checked on https://feature-sei--wormhole-connect.netlify.app/. User is not able to connect wallet, clicking on "Coin98 for SEI" option has no effect.
Error is displayed in Console:
```
Uncaught (in promise) Error: Wallet coin98 is not installed.
    at connect.js:20:15
    at Generator.next (<anonymous>)
    at connect.js:8:71
    at new Promise (<anonymous>)
    at n (connect.js:4:12)
    at t.connect (connect.js:13:43)
    at ew.connect (index.ts:205:47)
    at WalletModal.tsx:214:18
    at WalletModal.tsx:262:17
    at Object.Be (react-dom.production.min.js:54:317)
```

![Screenshot 2023-06-19 at 11 33 40](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0aeb19f1-bf5f-49b6-8207-3e18f9767c9a)

![Screenshot 2023-06-19 at 11 34 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/67d8d46c-9b93-4c48-93a9-abc0e5f7dbf7)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when user clicks on "Coin98 for SEI" option.

![Screenshot 2023-07-13 at 13 42 46](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1d7630ec-8a61-42ef-ab97-46af0f6f012a)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e5590652-13c9-4192-a87d-7788a61e86f9)

**Comment by AigaD** [comment]
Coin98 wallet button is clickable for SUI Network, for Sei Coin98 will be rechecked after #954 is resolved
Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/37a9154d-95a1-473a-8929-886c7cca3c3e

**Comment by tsadovska** [comment]
User can successfully connect Coin98 (Sui), Coin98 (Cosmos) and Coin98 (Solana) wallets. Coin98 (Sei) wallet is no longer offered for connection. Checked on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Remaining issue: Incorrect icon is used when Coin98 (Sui) wallet is connected. Scenario is added to ticket  https://github.com/wormhole-foundation/wormhole-connect/issues/689.

Ticket is closed.
