### ISSUE TITLE
[QA] Install Falcon URL can not be reached

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#698]
Preconditions:
Wallets are not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/#

Steps:
1. Click Connect Wallet
2. Scroll through the wallet list and search "Install Falcon"
3. Click on it
4. Observe

Actual result: Site can not be reached

Expected result: User is taken to URL where Falcon wallet can be installed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6a29393-e13c-417c-a3f4-0a83d0574996

**Comment by AigaD** [comment]
Issue will be rechecked after #954 is completed

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/97383604-1b8a-431b-8346-861d3ee21209

**Comment by tsadovska** [comment]
"Install Falcon" option opens invalid URL https://https//www.falconwallet.app/. Correct URL is https://www.falconwallet.app/.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet].

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8a0fa721-3777-4955-89d6-db44a0dd9ad6

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by aadam-10** [comment]
the wallet seems abandonware, should be removed from the aggregator & connect

**Comment by sebastianscatularo** [comment]
closing it now

**Comment by AigaD** [comment]
Tested OK
Tested from: https://portalbridge.com/ / https://wormhole-connect-mainnet.netlify.app/#
Falcon wallet has been removed from wallet list.
Attachment:

![Screenshot 2024-03-05 at 08 37 24](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/378af92f-0e67-4d07-b7e0-b8caf79ad207)
