### ISSUE TITLE
[QA] Sei transactions are not found by the TX hash provided in Sei explorer, if more than 1 day old

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#705]
Preconditions:
Transaction hash for transactions that were started more than 1 day ago:
- https://sei.explorers.guru/transaction/70348F171642B0A74F75E67FD8043E9F9C41211462DC03C562D73AE563E10A59 - TX hash 70348F171642B0A74F75E67FD8043E9F9C41211462DC03C562D73AE563E10A59
- https://sei.explorers.guru/transaction/8D65896396E419E46AD8A099A0EEC5B75E50952524442B20D2B97464D2EAE5F8 - TX hash 8D65896396E419E46AD8A099A0EEC5B75E50952524442B20D2B97464D2EAE5F8
- https://sei.explorers.guru/transaction/2A6CC322088DCBE47146D39959502ABC771BAEEE436986B4DA9EE0C22E60E7AE - TX hash 2A6CC322088DCBE47146D39959502ABC771BAEEE436986B4DA9EE0C22E60E7AE

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/#

Steps:
1. Copy the transaction hash
2. Click on Menu
3. Open Resume Transfer
4. Paste in the search field the TX hash
5. From Network drop down list choose Sei
6. Click Search

Actual result: "Bridge transaction not found, check that you have the correct chain and transaction ID" is shown to the user for transactions that were started more than 24hours ago

Expected result: Transaction is found

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1e3106aa-ba6e-4d17-a61d-34af6890662b

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
This will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/671 is resolved

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/762 is resolved.

**Comment by tsadovska** [comment]
Issue will be re-rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/2372 is resolved.
