### ISSUE TITLE
[QA] Coin98 wallet is opened when user connects Metamask wallet

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#708]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Precondition:
“Coin98 Wallet” and Metamask extensions are installed

#### Steps:

1. Click “Connect wallet” button
2. Try to connect Metamask wallet

#### Actual result:
“Coin98 Extension” notification is opened.

#### Expected result:
Metamask wallet notification is displayed.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6ace47de-e178-4a0c-9bd6-d89607b5f4e5

**Comment by AigaD** [comment]
The same behaviour also reproduced on Mainnet - https://mainnet--wormhole-connect.netlify.app/

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f8cca529-f0f4-4884-b436-5523ed738bbc

**Comment by AigaD** [comment]
Closing. Issue is not reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/ / https://wormhole-connect.netlify.app/ and https://mainnet--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d3f88f5a-dcb6-4c70-b523-0ee8b1389c7c
