### ISSUE TITLE
[QA] “Error: Aptos send with payload not implemented” is displayed in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#711]
#### Build:
https://feature-sei--wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Martian wallet in ‘From’ section
2. Connect Compass wallet in ‘To’ section
3. Prepare to send 0.1 APT from Aptos to Sei
4. Click “Approve and proceed with transaction” button

#### Actual result:

- “Error sending transfer, please try again” is displayer for the user
- Error in Console:

```
Error: Aptos send with payload not implemented
    at p.sendWithPayload (index.ts:110:11)
    at b.send (wormhole.ts:212:22)
    at index.ts:167:25
    at Object.onClick (Send.tsx:113:26)
```

#### Expected result:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-22 at 11 13 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e54138ef-252b-4947-a12b-b4a1e44320fd)

**Comment by AigaD** [comment]
Issue also reproducible from: https://wormhole-connect.netlify.app/#
Send APT from Aptos (Pontem Aptos) to Sei (Keplr)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cac22768-fa6b-4322-b4e8-54a0e6e5c506

**Comment by AigaD** [comment]
Issue is reproducible from: https://base-relayer--wormhole-connect.netlify.app/#
When sending APT from Aptos -> Sei

Attachment:
<img width="1323" alt="Screenshot 2023-08-22 at 10 10 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b502e6c4-5fab-42c7-b6df-218d00cfb36e">

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] and https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending APT from Aptos (Spika wallet) to Osmosis (Leap wallet).

Error is displayed in Console when clicking on "Approve and proceed with transaction" button:
```
Error: Aptos send with payload not implemented
    at p.sendWithPayload (main.aac608af.js:37:18005310)
    at m.send (main.aac608af.js:37:18174932)
    at Lf.toCosmos (main.aac608af.js:110:152166)
    at Lf.send (main.aac608af.js:110:153410)
    at xb.send (main.aac608af.js:110:198303)
    at Object.onClick (main.aac608af.js:137:24101)
```

**Comment by tonyjin** [comment]
Updating to P0 since Wormhole assets are canonical on Aptos/Sui and Osmosis pools for these assets will be important for Gateway launch.

**Comment by AigaD** [comment]
User was able to Claim Aptos asset for transaction APT Aptos -> Osmosis
Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/

Attachment:
<img width="1307" alt="Screenshot 2023-08-29 at 15 34 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0e787733-2472-41ce-9ed0-0daca3a3a426">
