### ISSUE TITLE
[QA] “Cannot read properties of undefined (reading 'pubKey')” is displayed in Console

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#714]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet]

#### Steps:

1. Send 0.01 ETH from Goerli (Metamask wallet) to Aptos (Martian wallet)
2. Click “Claim” button on Redeem screen

#### Actual result:

- User is not able to claim tokens
- Error is displayed in Console:

`Cannot read properties of undefined (reading 'pubKey')`

#### Expected result:
User is able to successfully claim tokens.

#### Notes:

- Etherscan transaction: [Goerli](https://goerli.etherscan.io/tx/0xd2e65d9326561b6f0c0af3ab914456c71156bf4d59cf1985623b93d1b36f2a60)
- Metamask wallet: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
- Martian wallet: 0x736698582d8805d20f77e0176070fee4d7373426025beb7275133608c06cc1e6

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
<img width="1088" alt="Screenshot 2023-06-23 at 00 17 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fc8edd99-13f3-4fc9-b47d-f448cebdbcb9">

**Comment by AigaD** [comment]
Issue reproduced on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Console shows error: `"Account not found by Address(0x9135cc990c444f26dc70627c047e52910a6b9a5bf5f75412f8236e612b8f5cc1) and Ledger version(166896400)","error_code":"account_not_found","vm_error_code":null}`
Attachment:
<img width="1323" alt="Screenshot 2023-06-27 at 13 47 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ff0a2cb8-acca-425a-9d02-247c2b5d1abf">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. Closing the ticket.
- Testnet: [Goerli tx](https://goerli.etherscan.io/tx/0x615bf3231e4ccbef6064d66ee78e88779442fcf817972b8c218ad451f7cdfbf8), [Aptos tx](https://explorer.aptoslabs.com/txn/0xab88079d2bab1cd4c562057b7cb3165e545bd032c69e726e898ae3cfbc52b48e?network=testnet)  
- Mainnet: [Ethereum tx](https://etherscan.io/tx/0x0f0b5c53aa69579d2ad820c3f12a212de73d5d2affc7337c53f4654a6dc2e8a5) , [Aptos tx](https://explorer.aptoslabs.com/txn/0x535cf0763cf0d009271c2e530dab178c4ad5495235ab883597771eafeb6308a7?network=mainnet)
