### ISSUE TITLE
[QA] [Petra] Transaction error when claiming tokens

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#718]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet] 

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Petra wallet in To section
3. Send 0.01 MATIC from Mumbai to Aptos
4. Click “Claim” button on Redeem screen

#### Actual result:
Transaction error is displayed in Petra wallet: 

```
Transaction error
{"message":"Account not found by Address(0x893a77d87b0430b2c788118124bef9e1a810901b31e3658790e26a7601a415a2) and Ledger version(9361571)","error_code":"account_not_found","vm_error_code":null}

Payload
Function: 0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f::complete_transfer::submit_vaa_and_register_entry
```

#### Expected result:
User is able to successfully claim tokens.

#### Note:
Send from transaction: [Mumbai](https://mumbai.polygonscan.com/tx/0xa9a7762ef0c70219f67a21f772cb00acb1d288c0662cf05bd4c5fae1b073a626) 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-24 at 12 36 40](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b4b3bab1-b099-43ac-8829-bf1387b14a57)

**Comment by AigaD** [comment]
The same error appears when sending Celo from Alfajores (Metamask) to Aptos (Petra) and Solana (Phantom) -> Aptos (Petra) on https://wormhole-connect.netlify.app/ 
TX https://explorer.celo.org/alfajores/tx/0x3a80760bd91d9606f725a3db1db28d4c022520e289f411b7ef4d8b094dc63368
TX https://explorer.solana.com/tx/2uS21STy2fyWsMV3rQc91NKX5BSxet35BJTTv73Lk6hNrmmxKvVqhPAwvvMmAx2SSLpB9XkNPCJRmdxsz8RiggWF?cluster=devnet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6a3dc0c0-92e4-4d8f-9d84-8fb9619b8796


<img width="1327" alt="Screenshot 2023-06-29 at 09 42 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9792a350-8645-4bad-9428-8dd71403550f">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 BNB from BSC (Metamask) to Aptos (Petra). Claiming on Aptos fails. 

Error is displayed in Console:
```
main.12c4d986.js:190 Error: Waiting for transaction 0x2245556c7e86967c9d84222dd9912172f026d1e97814c176301310eae105e69e failed
    at Kr.waitForTransactionWithResult (main.12c4d986.js:37:13320265)
    at async Kr.waitForTransaction (main.12c4d986.js:37:13320564)
    at async cd (main.12c4d986.js:37:19931700)
    at async Yl.redeem (main.12c4d986.js:37:19995394)
    at async Object.redeem (main.12c4d986.js:37:20033146)
    at async Object.onClick (main.12c4d986.js:190:99030)
```
Send from tx: [BscScan](https://testnet.bscscan.com/tx/0x2eb7235b9079bde80600db3969d2954278b16747d33f5e06bf5f89b695316cf9)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4d307671-c4ae-4185-a843-f3699162c096)

**Comment by tsadovska** [comment]
Linked #1051.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 

Scenarios - Tested OK:
* Send 0.001 WMATIC from Mumbai (Metamask) to Aptos (Petra) - [Polygonscan](https://mumbai.polygonscan.com/tx/0xcc50fd0ac70a8a7dd00c9daee50c932eea954cccca76ceda257b334e3fda1d44), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xaebc7136bea0f4aeeb6f23192ddd4f96c6177356dc6cf413674fffe157e27905?network=testnet)
* Send 0.002 CELO from Alfajores (Metamask) to Aptos (Petra) - [Celo explorer](https://explorer.celo.org/alfajores/tx/0xeb8b0ab82e5effd85c874c9a596b871e39872155f6e0c98ee6467e660982141f), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xce16b65d99090092a18fd825cde483714d017b0c13a4685789953dce84133031?network=testnet)
* Send 0.003 BNB from BSC (Metamask) to Aptos (Petra) - [BscScan](https://testnet.bscscan.com/tx/0xac4fe3c2d497cbd5ecc36a2c421d7f513c353274b8916562ca64162b268f948b), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xdb5bffd709e7eb971e3b1d7b0082820de0509e04e90be63925af848f888862b2?network=testnet)

Ticket is closed.

**Comment by peebrainfreak** [comment]
Hello, I am having the same issue. Was it resolved? If so, I don't understand what to do
