### ISSUE TITLE
[QA] User is not able to send wrapped assets from Moonbase to Aptos

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#719]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet] 

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Rise wallet in To section
3. Preprare to send 0.01 WETH from Moonbase to Aptos
4. Click “Approve and proceed with transaction” button

#### Actual result:

- “Error sending transfer, please try again” is displayed for the user
- Error is displayed in Console:

```
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x955dad8eaa597d12e6f3250e6cd3afb5dfb49b2f85546c351ec03e8f2a49bbab", transaction={"hash":"0x955dad8eaa597d12e6f3250e6cd3afb5dfb49b2f85546c351ec03e8f2a49bbab","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","gasPrice":{"type":"BigNumber","hex":"0x62590080"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x62590080"},"gasLimit":{"type":"BigNumber","hex":"0x03394a"},"to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","value":{"type":"BigNumber","hex":"0x00"},"nonce":70,"data":"0x0f5287b0000000000000000000000000d27d8883e31faa11b2613b14be83ad8951c8783c000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000001697ce32b1110442fb3d2b024ccb3515a165f16347e80e08462d824805d6c1110b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064b70000","r":"0x7d206877bfa74717c01dcca39b771260e02d1d91c085d54b13761fc8d59c511e","s":"0x705364f7643908a227d32d42b8e7cccef2ffd8f6372e474a9d0766f030771615","v":0,"creates":null,"chainId":0}, receipt={"to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x033814"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x419198aec0df51214c31e16be1ab0160265bd99345157963512ca3be1f82f32c","transactionHash":"0x955dad8eaa597d12e6f3250e6cd3afb5dfb49b2f85546c351ec03e8f2a49bbab","logs":[],"blockNumber":4603807,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x033814"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x60db8840"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.f2ca49db.js:37:1803301)
    at l.throwError (main.f2ca49db.js:37:1803421)
    at u.<anonymous> (main.f2ca49db.js:37:1832841)
    at Generator.next (<anonymous>)
    at o (main.f2ca49db.js:37:1812171)
```

#### Expected result:
User is able to successfully send tokens.

#### Note:
Issue is also reproducible when:

- User sends WAVAX from Moonbase to Aptos (Rise wallet)
- User sends WETH from Moonbase to Aptos (Spika wallet)

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-24 at 18 16 10](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/11ad0bd2-e1a9-4843-aa7d-e4d642146c13)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when user sends WMATIC from Moonbeam (Metamask wallet) to Aptos (Spika wallet).
* Sending From tx: [Moonbeam tx](https://moonscan.io/tx/0x2b6d82b292cb0b3beb12d6c593c4f227ad25722155e3a0749e8c21a6ea10d886) 
* Metamask wallet: 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
* Spika wallet: 0x5a0eb6850f079f5b9f33c9c7e1de61264680e13eafa85228054ddf013bd85c7b

Error is displayed in Console:
```
main.d13e45d0.js:190 Error: Transaction failed
    at o.<anonymous> (main.d13e45d0.js:37:7709952)
    at Generator.next (<anonymous>)
    at o (main.d13e45d0.js:37:7706653)
```
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d5960488-46e3-4f08-83f8-61b405ca4ee4)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a3b53e41-20d7-43b2-91ed-9043c242876c)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on June 27 on https://mainnet--wormhole-connect.netlify.app/ [Mainnet].
User is able to send WMATIC from Moonbeam (Metamask wallet) to Aptos (Spika wallet).

- Sending From tx: [Moonbeam](https://moonscan.io/tx/0x133e1d4573e0905be07edc6624bdb030b22dc405989d1ebbd6e1bf3dd0cf4454)
- Sending To tx: [Aptos](https://explorer.aptoslabs.com/txn/0x4097f7ff2ce9615d8a223f896381ca41076bf2ed820b7ebf91df656f6793c05f?network=mainnet)

**Comment by AigaD** [comment]
Issue is also reproducible for transaction APT Moonbase -> Aptos
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

<img width="1390" alt="Screenshot 2023-07-05 at 12 53 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a86fd4f8-c87b-40f7-9bbf-3432b13bcf66">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7ffab33a-058c-46d9-a861-eb7617ff05ec

**Comment by tsadovska** [comment]
Issue is reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 SEI from Moonbase (Metamask) to Aptos (Spika). 

Error is displayed in Console after clicking the "Approve and proceed with transaction" button:
```
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x6c83ff69ab6e7ef7e288169ca012e819188ef5e955c5c20e4c9b9a1e1a5b9f3e", transaction={"hash":"0x6c83ff69ab6e7ef7e288169ca012e819188ef5e955c5c20e4c9b9a1e1a5b9f3e","type":2,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","gasPrice":{"type":"BigNumber","hex":"0x62590080"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x62590080"},"gasLimit":{"type":"BigNumber","hex":"0x020cb6"},"to":"0x1EdDe35B7e058194B457B8621285EaFA710f01ea","value":{"type":"BigNumber","hex":"0x00"},"nonce":113,"data":"0x095ea7b3000000000000000000000000bc976d4b9d57e57c3ca52e1fd136c45ff7955a960000000000000000000000000000000000000000000000000000000000000064","r":"0xfa839fb91681ee8d81f9aa9730fc8fd26cb8d945989f6a1804a3b165557fe239","s":"0x040346a2e96f069a4c567b9a8fa1aef7d9dc95f7c229b1f7ae0cf5ad5baa6304","v":1,"creates":null,"chainId":0}, receipt={"to":"0x1EdDe35B7e058194B457B8621285EaFA710f01ea","from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x020ad4"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x32b140415e3ffd549b6b69812a8feaacda9892e69344d6f28d5fa16270401a3e","transactionHash":"0x6c83ff69ab6e7ef7e288169ca012e819188ef5e955c5c20e4c9b9a1e1a5b9f3e","logs":[],"blockNumber":4967763,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x020ad4"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x60db8840"},"status":0,"type":2,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at u.<anonymous> (base-provider.ts:1549:24)
    at Generator.next (<anonymous>)
    at i (_version.ts:1:24)
```

**Comment by tsadovska** [comment]
Issue will be rechecked after #946 is resolved.

**Comment by AigaD** [comment]
Issue reproducible. Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.001 WETH from Moonbase to Aptos fails at Claim.
Attachment:


![Screenshot 2023-10-13 at 13 04 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dae26f49-34b7-47ca-be2a-9b46791d9100)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] when:
* sending 0.001 WETH from Moonbase (Metamask) to Aptos (Rise): [Moonscan](https://moonbase.moonscan.io/tx/0x383e10c51d4bbab9aae1c32b779ea38eeaeda8295c40b020244a5db991868fe8), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x6c5d63f619f4c3daa35a42d6d0554d8135129649925853da591f626c48e3969c?network=testnet)
* sending 0.0001 SEI from Moonbase (Metamask) to Aptos (Spika): [Moonscan](https://moonbase.moonscan.io/tx/0x56c22f141425a2816533417b89a80ea861e550904a1479c02e57eb19dd3c47ec), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xd77c41746db5fe6cdbcd98efbacec2792f8609f4d5596e75c9bd62e9e8308f49?network=testnet)


Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 WGLMR from Moonbeam (Metamask) to Aptos (Spika): [Moonscan](https://moonscan.io/tx/0xf010f58e75a568bf35e6d501ed9576627599d9cc1634777fd1c92257e354c73f), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x36e62bc29f1fbd792283b42b343579ee89a4095c5d11f266db3da3f02f7392be).
