### ISSUE TITLE
[QA] [Mainnet] User is not able to send APT from Aptos to Moonbase

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#721]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet] 

#### Steps:

1. Connect Spika wallet in From section
2. Connect Metamask wallet in To section
3. Send 0.01 APT from Aptos to Moonbase
4. Click “Claim” button on Redeem screen

#### Actual result:

- “Your claim has failed, please try again” is displayed for the user
- Error is displayed in Console:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xbc976D4b9D57E57c3cA52e1Fd136C45FF7955A96","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000010001000000000100360492ae68e06a8935ffd17ab234d4ef3d9c31bed479af22e301ad092dae155208998fefc0d14c1309ba9244da3c2a4d462134795b93e174e46d424373e3fd97006497ef4700006dbf001600000000000000000000000000000000000000000000000000000000000000010000000000000247000100000000000000000000000000000000000000000000000000000000000f4240a867703f5395cb2965feb7ebff5cdf39b771fc6156085da3ae4147a00be91b3800160000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc18500100000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"VM Exception while processing transaction: revert","data":"0x"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32603,\n    \"message\": \"VM Exception while processing transaction: revert\",\n    \"data\": \"0x\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:15154)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18094)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18704)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:94385)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:95384\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:22:58222\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:15154)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18094)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:18704)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:94385)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:95384\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:22:58222"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.f2ca49db.js:37:1803301)
    at l.throwError (main.f2ca49db.js:37:1803421)
    at g (main.f2ca49db.js:37:1860317)
    at u.<anonymous> (main.f2ca49db.js:37:1870501)
    at Generator.throw (<anonymous>)
    at s (main.f2ca49db.js:37:1859648)
```

#### Expected result:
User is able to claim tokens.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-25 at 10 50 31](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2a0bd498-3651-40c5-ac13-d1588a075b03)

**Comment by AigaD** [comment]
Issue also reproducible on Mainnet - https://mainnet--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/032548ee-11f2-4d9c-9e08-51e5b52eb301

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet].

Issue is not reproducible with the following scenarios:

- Send APT from Aptos (Martian) to Goerli ( [Aptos](https://explorer.aptoslabs.com/txn/0x25cc0494d0860b81dbb224c85dec933caeb5915df90c556ca1b761e9c48ef6b6?network=testnet), [Goerli](https://goerli.etherscan.io/tx/0xf0a2ff880d71b3dc4d35a087a38de7f35c18d16174c150b44cad73e094b7d391)  )
- Send APT from Aptos (Martian) to Mumbai ( [Aptos](https://explorer.aptoslabs.com/txn/0xf7265cdecbeb7ef3877bb12030073771a568ea43c476f358fb8579d9695f6bde?network=testnet), [Mumbai](https://mumbai.polygonscan.com/tx/0xd8f2019d1894fc5c9e990f9d7704ec483960de86bfc47c83f7a7894537caae7b) )
- Send APT from Aptos (Martian) to BSC ( [Aptos](https://explorer.aptoslabs.com/txn/0x7dbc05f296c494c55b5e481cd290cf029b63d2a40547a14e775afc6c52243473?network=testnet), [BSC](https://testnet.bscscan.com/tx/0x1e0346abbced2848de4eacaf42490c359cb8b406c93227c1a557be69c68dd3a9) )
- Send APT from Aptos (Martian) to Fuji ( [Aptos](https://explorer.aptoslabs.com/txn/0xcd665cd28798ab1e07094c78e23ba505157af75fea84fb051bb41496198539c0?network=testnet),  [Fuji](https://testnet.snowtrace.io/tx/0x01558c26a15b58964430f6aba0a3d186b22821eed8aa80bbdd314218c90dc7f5) )
- Send APT from Aptos (Martian) to Fantom ( [Aptos](https://explorer.aptoslabs.com/txn/0x148f15aa2ee5d36d994c864c271aa4dad305c7c907d2b6640c35759cef557ff3?network=testnet), [Fantom](https://testnet.ftmscan.com/tx/0x574c9c5907631b7fafb604fd0d8cc22d9438f572a691cdc24019ca7d035618d5) )
- Send APT from Aptos (Martian) to Alfajores ( [Aptos](https://explorer.aptoslabs.com/txn/0x49187fe13f0eb69d7f51ded10b025d617dc20e5aa77b7b95d03eaa2ab8545522?network=testnet), [Alfajores](https://explorer.celo.org/alfajores/tx/0x90506361acbeaacae11aa110179c348e3f5e2e373afd0953e8471d7abafd8d34) )
- Send APT from Aptos (Martian) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x2e6f7c2d3d315f9380f9dca13a6e4337934821f6011f83b0d27c1d80ee03e40f?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0x801567ee273e261e227f35028ad471cc4873b0bcafaf413a30929079b8c261d0) )
- Send APT from Aptos (Fewcha) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0xdce4c3aa2f7aa315f876c5e4d9be453d4f78ec1b00d63bc445985f7b36ffc9af?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0x3daba7a0e9ed8332563e6954e54a4c80d9ab9ac42b395814c50eb70f8e07c61f) )
- Send APT from Aptos (Nightly) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x01be9039741279a1f4d3a941dfa6500e6a07c4ca3e4a9b8375490fb2ca26c6ec?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0xa1c0770258b3410ab19c7b1dde4039ff59383baa4113289e1990c9909ff17e70) )
- Send APT from Aptos (Petra) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x93d4d342b256b4bda11e69d322d41cfa4c1a9b12a9cf979a92272b6ee9d4c79f?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0x693bc28639681fca7c21c9744b7b0fd8e1276d3167caa1e714aac3079131d341) )
- Send APT from Aptos (Rise) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0xe479040519f8191abd2f36f665f3e484fdf872743d802b664f5abce493e1f28b?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0xf61da5e5afb575b860ac708364682db22ed0fc28296a880244e8241bd839ba69) )
- Send APT from Aptos (Spika) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x2917f880724b941d0c7c77f4fd2e67049dedb53f5a069ce4d1dd8b6332c5ce12?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0xa6bb5e4405859ff809cce318ef741cd80c2635f1b1ba1fed2029f84184bad0f5) )
- Send APT from Aptos (Pontem) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x6a8719785a83a32481dc7bfd5b0c074963b46daea5a38b307e6700729d6560b4?network=testnet), [Moonbase](https://moonbase.moonscan.io/tx/0xc56d07dbd8aa00d941e518f7507c316084bedfe4153983211c8e8a5dfa6ca384) )


Not able to check on Testnet with following wallets:

- Snap wallet (ticket: [#646](https://github.com/wormhole-foundation/wormhole-connect/issues/646))
- BitKeep wallet (ticket: [#715](https://github.com/wormhole-foundation/wormhole-connect/issues/715))  

 

Issue is still reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] with following scenarios:

- Send APT from Aptos (Spika) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0x39b2c2a9c2816da2d4969bdd1d06ca2d3b55ee88369270bb580ca66f87fcfa49) , claiming fails )
- Send APT from Aptos (Martian) to Moonbase ( [Aptos](https://explorer.aptoslabs.com/txn/0xdaee817d463f3e42ad8e06981eee2047b1fc21ae200ea007f0692684dee92753) , claiming fails )

Error is displayed in Console:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xB1731c586ca89a23809861c6103F0b96B3F57D92","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000041801000000030d00c1db15e5bb96004e82273a88a710a3c70084e3df74cdcb38adbc347cc458efae5678aecd129c3497589de9b7ac64f3fb892c7c09d6970f8df6a67e787107fea80002121b9c834e79e89141bde95bc5b85dd3fffa6ab338af1b90b394b9bf4ec7de922617da4dbbd9cf9510d3341218b72213a326bb3d0bcf853b37126e42b74c6dcd0003869b6d3c67df5f2e527b1bee314d718c60585b83c33f45297d06cb275ae8e1e97ec0884e825f3cfdfe30dd0c553987cecdaaa0981c3cc9a762ddfaf24fc33d0d0004aa5b40375d18ab8d01c96e48da6679e7f1485e6de1884202a4d29437317b20567efc1716ab40cad566c5febc8b4b5fc0b7914ea16091eedf5adc35cd712483530106f8bbd772f836148d923d97302d89271603ab18a8246123b7bfceb29ea0b9b05817c7b0e98084b6658e2d6867b4eb0e81e8e7b73814645553a917a14df71f1f81010a0d1d56f1feaa15cf43ec4aba7b9c8faac06640c6b8da43a0c8deeba0d27961e412ed960934fbc4fef2832fb8d981dc1f76829b16b808dbe7891f7a24335d499a010b1aed2e963131f85d4b36425ba7e5399770f3ddec27a4bf646da550032e4ec2e20a19ef4258e088e750c8fc9ea38f0f13b8aa68ec6f3381ad3eaf7030b7dbfaae010c4666bd184eb07f97dd767ab249f38ee8f366cd69b9aa2f94b4a1c97986aa55080209af649f275f0539d6cf84c75749069176b2e3cdefa0ef08913b147b5c73e9000db0156fc3e3888b2c4afebe3809400991414a78c7c82e6b09a8d5993784ca585c6981d2a32a2257113adb4150e318155039a340ebdc7e2ef16f10caeff796ebdb010e5e341b3537e93a05f4967b7f14bddf7f824cc6819460943e8c4c86214247deb530bfadcec4fae65c31a1975b28f927874f90b536cea1f1a3c2f780f5be08665b001029874d869f80461b11d6762e0a62723d5e4acba7a8a165c258e378d5b80cd4c03cb753e3ab34a1c6849f3e2c62926192a94e947d3918a84bae745bd33455481401119a399ba9857dfe411e7605624be0390e1899a320a7c6c4f41619e6ea4feed87e754ee6444f9936eef0e1bb5d34d81a517ad486c15aa2ebcafe2bb8bb4cd97af601126133e446803f6b036c921bd46d326451dd06f985854a67a6988c50a0b03c047f5f6d4b30b76ab8c090aef14c9880e6bf7f9b5272e6e0189b858e2714f0f41a950064ad45ca00010bfe0016000000000000000000000000000000000000000000000000000000000000000100000000000063a500010000000000000000000000000000000000000000000000000000000000002710a867703f5395cb2965feb7ebff5cdf39b771fc6156085da3ae4147a00be91b3800160000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc7012001000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"VM Exception while processing transaction: revert","data":"0x"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32603,\n    \"message\": \"VM Exception while processing transaction: revert\",\n    \"data\": \"0x\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:31538)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:34478)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:35088)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:72700)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:73699\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:100465\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:31538)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:34478)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:16:35088)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:72700)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:73699\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:12:100465"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at y (json-rpc-provider.ts:66:16)
    at u.<anonymous> (json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at s (formatter.ts:523:1)
```

Attachment:
![Screenshot 2023-07-11 at 15 12 38](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b0c6bc6e-b8c7-42f3-bab4-0a6ffe3b6214)

**Comment by tsadovska** [comment]
Issue will be rechecked after #946 is resolved.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction from Aptos (Fewcha) to Moonbase (Metamask) fails, reason in console `Error: Transaction issue`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/370f99c0-128d-479a-b016-b8ecc9bc5d60

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when:
* sending 0.001 APT from Aptos (Spika) to Moonbeam (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x71d183572c7943ebc9e755ef70682a90ad9569fc2a17f8b1b1fcd0d5a5366f78), [Moonscan](https://moonscan.io/tx/0x51fe4383df879ae9a8ec00b98eb953a283176f0062e91d4eb18357d389933e79)
* sending 0.001 APT from Aptos (Martian) to Moonbeam (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x91afc3b6188d218a3f3189e3bfb9029aab167bd97d0852fba2ed405a0c89823c), [Moonscan](https://moonscan.io/tx/0x12a75a18f2a7303e30f9a2678783540afb3b6fc47b74224511421a02ab8e3fb7)


Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 APT from Aptos (Fewcha) to Moonbase (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0x6c8fbca4c549ce27476119f78a6d81a860c19ff15614506a2cdae5a1a979f0c3?network=testnet), [Moonscan](https://moonbase.moonscan.io/tx/0x693f656b028476aeeab098152f7b08ec307f07ec39e15f2d7c0756de981a2e1a).

Ticket is closed.
