### ISSUE TITLE
[QA] Page is reloaded when user changes BitKeep wallet account

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#724]
#### Builds:
https://wormhole-connect.netlify.app/  [Testnet]
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Preconditions:
User has 2 BitKeep accounts.

#### Steps:

1. Connect Metamask wallet in From section
2. Select Goerli network in From section
3. Select Aptos network in To section
4. Connect BitKeep wallet in To section
5. Open BitKeep wallet extension and change wallet account

#### Actual result:
Page is reloaded. User needs to fill fields again. 

#### Expected result:
Page is not reloaded when user changes wallet account in Extension. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5f2a3698-9ac8-4b27-973a-cdd79001df13

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Page is reloaded after user changes Bitget wallet account in extension.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88cce246-8b42-4d52-86b9-8f10d337cd60

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#
Page is reloaded when Bitget wallet (Previously Bitkeep) is changed.
(Broken Bitged icon reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/939 )
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3af77a7f-2c5c-41b8-aa5a-bae9a4698309

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/19486a47-5cb3-4dfc-9ca3-87c284b6ef7e

Ticket is closed.

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://portalbridge.com/ [Mainnet] when user changes BitKeep/ Bitget (Aptos) account. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5e4dbe45-b76d-47d2-9c1c-523a0238ae4a

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Page is re-loaded in case user creates new Bitget (Previously Bitkeep) wallet.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aee081cd-77e9-41e1-a692-a36c57242ac0

**Comment by tsadovska** [comment]
Issue is reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2). 

https://github.com/user-attachments/assets/b29920e0-38ee-4a11-bf84-1b14a8bf0fbd

**Comment by tsadovska** [comment]
Closing the ticket, because Bitget/ BitKeep wallet is no longer displayed in the Networks list. 
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.
