### ISSUE TITLE
[QA] Link to Aptos Explorer is not displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#726]
#### Builds:
https://wormhole-connect.netlify.app/ [Testnet]
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Steps:

1. Open Menu > Resume transaction
2. Search for transaction hash 0xa125566f3568e4f00f6b7fa735484cb832054c59682a7b78e1082af1a86be859 in Ethereum network
3. Observe if link to Aptos Explorer is displayed in “Send to” section

#### Actual result:
Link to Aptos Explorer is not displayed.

#### Expected result:
Link to Aptos Explorer is displayed: [Aptos tx](https://explorer.aptoslabs.com/txn/0xc7f6ce97d13dcbf9c8426753bae1fc677e653ae1571122af290d4a0724d9ad9f?network=mainnet )

#### Notes:
* Issue is reproducible on testnet and mainnet when user searches for Goerli/ Ethereum transaction
* Issue is reproducible on mainnet when user sends assets to Martian or Pontem wallets.
* Issue is not reproducible on mainnet when user searched for BSC transaction

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachments:
* Mainnet
![Screenshot 2023-06-26 at 12 55 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a49ca88f-e3a0-4630-b6fe-8b2ea76aab0a)

* Testnet
![Screenshot 2023-06-26 at 12 59 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/dfa559f5-6992-480b-8d28-35f54b2ee99b)

**Comment by AigaD** [comment]
Link was also not present for Goerli explorer for transaction Aptos -> Goerli.
Reproduced from - https://wormhole-connect.netlify.app/
Attachment:
<img width="710" alt="Screenshot 2023-06-30 at 09 32 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0f3e7a7a-1449-40de-bf0e-eb88a787d87f">

**Comment by tsadovska** [comment]
Issue will be rechecked after #1051 and #946 are resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] when:
* sending 0.001 ETH from Goerli (Metamask) to Aptos (Spika): [Etherscan](https://goerli.etherscan.io/tx/0x66b6814711d0544491352a3ccbaf64953b93154130a5bac9ffd487caefe91c2d), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xff04a2838d2bd711e7092311ac5439e2e21a6b486a92ec005c26920cccb1082f?network=testnet)
* sending 0.001 APT from Aptos (Spika) to Goerli (Metamask): [Aptos explorer](https://explorer.aptoslabs.com/txn/0xacbc455d71e97fc3643337f9f4038e06ad325f1d887e7f7bdbbfca1ca6005919?network=testnet), [Etherscan](https://goerli.etherscan.io/tx/0x822df0734348d8c837c49c3b1c1614fba557625e9f1e55d07ad53d4cd4279717)

Remaining issue: Link to transaction scan is not displayed in "Send to" section when transaction is resumed, #865.
Ticket is closed.
