### ISSUE TITLE
[QA][Mainnet] Icons for Wallet Connect are not fully visible when page zoom is set to 100%

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#727]
Preconditions:
Wallet is not connected 

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://mainnet--wormhole-connect.netlify.app/

Steps:
1. Click Connect Wallet
2. In the drop down list find Wallet Connect
3. Click on Wallet Connect option
4. Observe the Wallet Connect icon and "X" icon

Actual result: The top part looks cut in 100% zoom of the page

Expected result: UI elements fit in the screen without being cut

Attachment:
<img width="1439" alt="Screenshot 2023-06-26 at 14 59 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4aef0375-7ac7-447a-8f1f-2df1eca29923">

**Comment by AigaD** [comment]
This is also reproduced from https://base-relayer--wormhole-connect.netlify.app/#
Icons are partly covered when page zoom set to 100%
Attachment:
<img width="1366" alt="Screenshot 2023-08-18 at 10 28 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91f6c42c-0ab0-4915-9d54-5854a78490e4">

**Comment by tsadovska** [comment]
WalletConnect was upgraded, issue is no longer reproducible. 

![Screenshot 2024-01-17 at 15 14 21](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/68d2536b-4c47-40f3-ad60-2f9f1fc0e4d9)

Ticket is closed.
