### ISSUE TITLE
[QA] [Mainnet] User is not able to approve the transaction in Nightly wallet notification

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#729]
#### Build:
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Steps:

1. Connect Metamask wallet in From section
2. Connect Nightly for Aptos wallet in To section
3. Send 0.01 WGLMR from Fantom to Aptos
4. Click “Claim” button on Redeem screen

#### Actual result:
Nightly wallet notification is opened, but user is not able to approve the transaction. Clicking on “Approve” button has no effect. 

#### Expected result:
User is able to successfully claim asset.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-27 at 00 24 07](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/77c435eb-e291-48b0-921f-657aeed82da7)

**Comment by tsadovska** [comment]
Issue is reproducible on https://mainnet--wormhole-connect.netlify.app/ when user sends APT from Aptos to BSC.
1. Connect Nightly wallet in From section
2. Connect Metamask wallet in To section
3. Prepare to send 0.001 APT from Aptos to BSC
4. Click "Approve and proceed with transaction" button

<img width="1461" alt="Screenshot 2023-06-27 at 15 45 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0c2d8989-9366-478d-a5b6-038f14b492c1">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 WGLMR from Fantom (Metamask) to Aptos (Nightly). Clicking on "Approve" button has no effect. 

Send from tx: [FTMScan](https://ftmscan.com/tx/0x9e491e05b39cbac9be2cf81319ac6e51809a8ec4102ffc54885d7e0d6951cd69)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fec692fd-2b1e-450a-9003-88c2c4839038

**Comment by AigaD** [comment]
Issue still reproducible, tested from: https://wormhole-connect-mainnet.netlify.app/#
[Fantom explorer](https://ftmscan.com/tx/0x3f93fe08ee9e4446f449b838f23859fc83dbf33867a8d20aa1698f45fd669c0e)
Transaction 0.01 WGLMR from Fantom (Metamask) to Aptos (Nightly) fails at Claim
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e678ad48-bb38-4076-a114-4b6c380d6c22

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 APT from Aptos (Nightly) to Optimism (Metamask). 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/70fb14cb-9876-4114-b471-39cc31ea778b

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.1 APT from Aptos (Nightly) to Kujira (Leap). "Approve" button on Nightly notification is not clickable.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transactions tested OK:

- 0.01 APT from [Aptos](https://explorer.aptoslabs.com/txn/0x7c51b78f85b5343ce8721c03e7b395894866cedbd36fde5987b6bdc4d7ddc3de?network=mainnet) (Nightly) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/57FE3117A4778730BD6FACA53AEA6BED579D6BD48B78BADAFC93672ED06453E0) (Leap)
- 0.01 APT from [Aptos](https://explorer.aptoslabs.com/txn/0xf80c70d6447e986398bd41e70c058faa5c379353f51e00155767f64a117f87d9?network=mainnet) (Nightly) to [Evmos](https://www.mintscan.io/evmos/tx/628B8DD6D570ADFEDCF9C7E4C7E0EE8C0E4D61E8A401CFB560FE09C0584EAFF4) (Leap)
- 0.01 APT from [Aptos](https://explorer.aptoslabs.com/txn/0x209316230f2ac0fc53c87d57bbb172db9592f942b1524c42cf2206c401f1f73e?network=mainnet) (Nightly) to [Optimism](https://optimistic.etherscan.io/tx/0xbe90bd9a34544b266f1a63084bd4e1416ed68a4bc1ef57283cd3f38219fde9ad) (Metamask) 
- 0.1 WGLMR from [Fantom](https://ftmscan.com/tx/0xb35d99c462b654b8eb884992239cb9ecd9a217591e542c469740ab14d5c3722d) (Metamask) to [Aptos](https://explorer.aptoslabs.com/txn/0x122fbbf2107f76024380bbf0222c4ff576700633d991cb0eedc1b6d2dbaa4081?network=mainnet) (Nightly)


Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4c3d81e8-3814-46cd-8f9b-3d6383c7ce51

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when:
* Sending APT from Aptos (Nightly) to Kujira (Leap)
* Sending APT from Aptos (Nightly) to Avalanche (Metamask). 

"Approve" button is not clickable in Nightly extension. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aa554931-14d5-4ac1-8873-5dcf9d30858f


Issue is not reproducible on https://wormhole-connect.netlify.app/ [Testnet]. 
Scenario - Tested OK: Send APT from Aptos (Nightly) to Mumbai (MetaMask) ([Aptos Explorer](https://explorer.aptoslabs.com/txn/0xfc2a0a29322edcca7674dee5cbb2db08cd294467215211bcc45168118746272e?network=testnet), [Polygonscan](https://mumbai.polygonscan.com/tx/0x9a0af3f38bbb90d3328dc9c23a22da6733eb6bfabe6ed8d3291b6ae416ce448b)).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/

Attachment:
Transaction 0.001 APT from [Aptos](https://explorer.aptoslabs.com/txn/0xe21ef9edd4370c6f35762c0e0fa165997cd380d72a435986b8148250a330c2da) (Nightly) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/DDB04DF2B22F42336D26247D4C4A063F9BA05AF9E0ECA475A778AF271ADE781E) (Leap) was completed
https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/614f5a5c-182b-4e41-8ba0-2e559dedcd97

Transaction 0.001 APT from [Aptos](https://explorer.aptoslabs.com/txn/0x8b24c87c455ac050780d0539eac7e51237bd3c7f07f3ca0f72ee4c2271f23f6d?network=mainnet) (Nightly) to [Avalanche](https://avascan.info/blockchain/c/tx/0x7334913e370f088170a34a46d63fa55c79e8ee61de1f9ec0008d3a59dba9e38a) (Metamask) was completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/800d2589-2b53-477b-83ae-7b44b566cc5e

Closing the ticket
