### ISSUE TITLE
[QA] [Mainnet] Can not connect with Nightly wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#730]
Preconditions:
1. Wallet is not connected
2. Nightly wallet extension is enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://mainnet--wormhole-connect.netlify.app/

Steps:
1. Click on Connect Wallet
2. Find Nightly wallet in the drop down list
3. Click on it
4. Observe

Actual result: Nightly wallet is un-clickable

Expected result: Nightly wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3c524bbb-b93f-4656-8679-4cbcdba5694d

**Comment by AigaD** [comment]
Same behaviour also reproduced from https://wormhole-connect.netlify.app/#
Cannot connect to Nightly wallet, console shows error `'Wrong network. Please switch network!'}`

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6492ef0c-a018-4838-af9d-9bbfcc97079f

**Comment by Pawel-Szydlo** [comment]
Hey, I checked the link you sent and Nightly Wallet works with Aptos.

Please update Nightly wallet to the latest version. ( currently 0.5.1) 
@AigaD 
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/89639506/152a0c23-39ff-4016-b7c8-d069117c1a0c)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/89639506/ba868313-3e8f-4852-bc75-cad196369926)

**Comment by AigaD** [comment]
Retested the issue and it is no longer reproducible. Nightly wallet has version 0.5.1 and it can be connected to Wormhole-connect.
Tested from: https://mainnet--wormhole-connect.netlify.app/
https://wormhole-connect.netlify.app/#
https://base-relayer--wormhole-connect.netlify.app/#
Closing the issue.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a8b0d57-6c5f-4750-9df8-b5c10ec584c7
