### ISSUE TITLE
[QA] “TransactionExpiredTimeoutError” when user sends SOL from Solana 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#732]
#### Build:
https://mainnet--wormhole-connect.netlify.app/ [Mainnet] 

#### Steps:

1. Connect Phantom wallet in From section
2. Connect Martian wallet in To section
3. Prepare to send SOL from Solana to Aptos
4. Click “Approve and proceed with transaction”

#### Actual result:
Error is displayed in Console:

```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 29UnE6fKWv6NnwQNpsviQFP48KWgcNCmaKEwAFem1Fk2B4FZqEWAgNBW84bdYnT8XB9DLNhuKSfvU4Zj7h81gAFW using the Solana Explorer or CLI tools.
    at xa.confirmTransactionUsingLegacyTimeoutStrategy (main.d13e45d0.js:37:9817491)
    at async xa.confirmTransaction (main.d13e45d0.js:37:9813439)
    at async Ix.sendTransaction (main.d13e45d0.js:37:12466263)
    at async uk (main.d13e45d0.js:37:12647585)
    at async fk (main.d13e45d0.js:37:12647761)
    at async main.d13e45d0.js:137:24359
    at async Object.onClick (main.d13e45d0.js:137:24180)
```

#### Expected result:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-06-27 at 20 18 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2357c99b-1132-4d49-b1cf-a58e3a737ef1)

**Comment by tsadovska** [comment]
Issue is no longer reproducible with the scenario from the description. Checked on https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. 

Transactions: 
- [Solana tx](https://explorer.solana.com/tx/4KgJ4ZeeoVW38PakKmHbFepdPQxrpPL7PVPadNFKViuMpSPpLUK6WkcVReBpVS8rv46SJT52QUiV4pHEk4ZzvJoS) (Phantom wallet: 4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU)
- [Aptos tx](https://explorer.aptoslabs.com/txn/0xd0ed5ae76e5b4d236232faf5570a84deab9421144987fa02b584d65816a2f023?network=mainnet) (Martian wallet: 0xebbb42751860774b5251b57a44f82997418d4d054987f393fb092d55ea9ef2fc)

![Screenshot 2023-07-25 at 19 23 20](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/31ce73aa-0677-457b-a311-3aab807fd77c)

Ticket is closed.

**Comment by tsadovska** [comment]
Reopening the ticket. Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.001 SOL from Solana (Phantom) to Osmosis (Keplr). 

Error is shown in Console after user clicks on "Approve and proceed with transaction" button:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5o6Jr34ehkRLxpNTkMDFa8LMgXyXUvXRSoQisEvtoDwYxEAgqVSevxaH3YNXPpyi7gKGqjDZzQAJ6xDEjSpsi2k1 using the Solana Explorer or CLI tools.
    at Connection.confirmTransactionUsingLegacyTimeoutStrategy (main.js:443:345199)
    at async Connection.confirmTransaction (main.js:443:340581)
    at async SolanaWallet.sendTransaction (main.js:477:300050)
    at async signSolanaTransaction (main.js:477:313783)
    at async signAndSendTransaction (main.js:477:315225)
    at async Operator.send (main.js:483:65983)
    at async Object.sr [as onClick] (main.js:649:95511)
```

![Screenshot 2024-01-08 at 17 49 21](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b4a1baad-40b8-43b1-85c8-5b0fdaaa822c)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 SOL from Solana (Phantom) to Avalanche (Rabby wallet). Error is shown in Console after user clicks on "Approve and proceed with transaction" button:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature rdAzbBdMCjtaEoG7RK4XUpwinp7XyKD3KXvT5WD6YX7LYYhdSp2XusLckWfnVjbGsox14XeCMvHFrMTNyGihJNn using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61281)
    at async Connection$1.confirmTransaction (main.js:171:56723)
    at async SolanaWallet.sendTransaction (main.js:517:300050)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79338)
    at async Object.gr [as onClick] (main.js:691:95817)
```


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/35e29f88-d367-428a-bb3d-a6fc5171f156)

**Comment by AigaD** [comment]
Same behaviour observed when sending SOL from Solana to Kujira (OKX wallet)
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ef1b34ae-1c7e-4d1e-9b86-de372127933a

**Comment by AigaD** [comment]
Reproduced from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#
Transaction 0.1 SOL from Solana (Solflare) to Fantom (Rabby Wallet) timeouts after 60 seconds.
Attachment:
<img width="1157" alt="Screenshot 2024-01-24 at 14 24 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/25538b2d-f1ba-46f7-8769-24f9bc081494">

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#
User is able to send 0.1 SOL from [Solana](https://explorer.solana.com/tx/66qj3p2xvRAEkfsKANJpL6hRceg5pFfV9bLvaUBrAzH6BMfmjCHdxJ2gzYbGM8AhJuAaDQc8dV1AZuJMDZtwJaBs) to Fantom
Attachment:

Uploading Screen Recording 2024-01-25 at 12.15.07.mov…

<img width="1007" alt="Screenshot 2024-01-25 at 12 18 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3e35e747-d383-45c8-a984-a345e1c5a30b">


Tested from: https://wormhole-connect-mainnet.netlify.app/#
User is able to send 0.1 SOL from [Solana](https://explorer.solana.com/tx/mijukjY1wfowPiZM5x2Kn9GzpeT3ECjR98wpoopKp3hCbbtsBufboYWkP1UjZ7N4WbvAt9YL3NQ5We2tkWtaG6J) (Solflare) to [Avalanche](https://avascan.info/blockchain/c/tx/0xaac7d918b045330f25468996a461afd005bee1b67ad967e2945c008977e71515) (Rabby)
Attachment:

Uploading Screen Recording 2024-01-25 at 12.19.01.mov…


<img width="908" alt="Screenshot 2024-01-25 at 12 22 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f48ba18c-cb42-44f8-b908-c71576630830">

**Comment by tsadovska** [comment]
Reopening the issue, because noticed that sometimes it is still reproducible. Reproducibility: 1/5.
Issue was reproducible 3 times today. 

Checked on https://portalbridge.com/ [Mainnet]. 
Scenario: Send SOL from Solana (Phantom) to Evmos (Keplr). 

Actual result: Transaction fails and error appears in Console after clicking on "Approve and proceed with transaction" button.

```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5ZyJxYJ77LZNBbbRPAVQe1bKbUkg6DDanTfGHSUM44gJXqL8YLxUWdHMiK9yFWo8e2uT88WTv7GtVgxw3rLS5QLr using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61281)
    at async Connection$1.confirmTransaction (main.js:171:56723)
    at async SolanaWallet.sendTransaction (main.js:517:300050)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async Operator.send (main.js:525:79512)
    at async Object.gr [as onClick] (main.js:691:95817)
```

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/#
Transaction timeouts when sending SOL from Solana (Phantom) to Klaytn (Metamask)
Attachment:

![Screenshot 2024-02-01 at 10 42 17](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4052b464-e4bb-452f-a1d4-f3074ff6b3a3)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49615454-34e2-4403-aa4a-e7c5ebac4630

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] when sending 0.001 SOL from Solana (Phantom) to Aptos (Spika). 

Error:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 3rdPsR7MoF6C7Sh1VwQtZizq9WQ9Y9sMY2ssKH6r4o99dzWp5EWjZ6L4cZ2uzGU3knzRiiZ7MGbKKc2VeFZRnBYG using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61281)
    at async Connection$1.confirmTransaction (main.js:171:56723)
    at async SolanaWallet.sendTransaction (main.js:517:300050)
    at async signSolanaTransaction (main.js:519:14303)
    at async signAndSendTransaction (main.js:519:15745)
    at async BridgeRoute.send (main.js:523:22384)
    at async Operator.send (main.js:525:79512)
    at async Object.gr [as onClick] (main.js:691:95817)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/057b6cf7-53b5-41ad-9411-8f35862ec33d)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction timeout shows for transaction from Solana (Solflare) to Optimism (Rabby)
Attachment:

![Screenshot 2024-02-06 at 12 34 59](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2202e966-a358-4dbc-8d93-1ee91c145096)

**Comment by tsadovska** [comment]
Tested OK:
* Check that manual route transaction from Solana to EVM-based chain is successful on [mainnet](https://wormhole-connect-mainnet.netlify.app/) (Send from tx: [Solana Explorer](https://explorer.solana.com/tx/3hd21j9ndyuLfAnLBFwmt1emFXmBcCfM5gB1w28i1bqGtopn1cqfhkvZA7G4WNXS9fwkqQvABhnMNGUbthigGu4W), Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0xb83c2992111f10a4b3a240b1d5412720544ed5ae03e480aa38670ea0249a33ee))
* Check that manual route transaction from Solana to Cosmos chain is successful on mainnet (Send from tx: [Solana Explorer](https://explorer.solana.com/tx/5tc61e2mPUMpHd3NHVwDcLRF6DPZjhz1uc6NKB2Gtnh4oYPYHDFghW8k41RkSpWBDwigFaichRxqKrwXqqz99B27), Send to tx: [Kujira finder](https://finder.kujira.network/kaiyo-1/tx/CFB81B0E55BCEB12BA29593AE731FB3CED32869B7D298AB834CCA760A563FB22))
* Check that transaction to Solana is successful on mainnet (Send from tx: [Sui explorer](https://suiexplorer.com/txblock/5SZQkFbEAm5adz1qeajnyAL6RXijwfYPJkkGRQsWogT9), Send to tx: [Solana Explorer](https://explorer.solana.com/tx/424MtrkiVVJoj8GYwJTqw6khgCRdUa15mxvBtUDzYEdALFGWST93F9WmZ2V8k3woY6AqiKzB1Em6kNqidU7CW5HY))


Tested NOK:
* Check that transaction to/ from Solana is successful on testnet, https://github.com/wormhole-foundation/wormhole-connect/issues/1650

Ticket is closed.
