### ISSUE TITLE
[QA][Mainnet] Wallet is showing as connected after user revokes the connection from the wallet itself

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#733]
Preconditions:
Wallet is connected (in my test Spika wallet was connected)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://mainnet--wormhole-connect.netlify.app/

Steps:
1. Open the wallet extension
2. Search for Connected Sites
3. Delete the connection with Wormhole-connect
4. Observe Wormhole-connect app

Actual result: Wallet is still showing as connected in the Wormhole-connect app although connection was removed from wallet itself

Expected result: Wallet gets disconnected in the Wormhole-connect app if user removes the connection from wallet itself

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0ca4e32f-6ea6-41b8-9e29-1e79ebabe0cf

**Comment by AigaD** [comment]
Issue is still reproducible.
Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Tested OK when disconnecting from wallet itself - Metamask

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91ecdca9-fb62-46f8-a80b-e0070a42c0ff

Tested NOK when disconnecting the connection from Wormhole-connect from Petra wallet:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2aafbbd7-7e03-40ea-a2dc-4eca7a0f3eea

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Sui wallet is still showing as connected in the Wormhole-connect app although connection was removed from wallet itself. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/22a58ea8-ee41-431e-b250-fa61f3063240

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Spika and Solflare wallets are left connected although connection has been disconnected from wallet itself.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c09f0a7f-180f-4a9b-a555-cab75accaf81


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/00dd01c0-9334-4b9e-8768-d493ff51f3a6

**Comment by tsadovska** [comment]
Issue is no longer reproducible.Wallet is disconnected after user revokes the connection from the extension. Checked with MetaMask and Phantom wallets on [wormhole-connect-wallet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2) and https://portalbridge.com/. 

Ticket is closed.
