### ISSUE TITLE
[QA][Martian] Error "Account not found" after clicking on Claim button

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#738]
Preconditions:
1. Metamask wallet connected at sending From section
2. Martian wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 MATIC from Mumbai to Aptos
2. Click Approve and proceed with transaction
3. Wait till option Claim is available
4. Click on Claim
5. Observe

Actual result: Error `{"message":"Account not found by Address(0x9135cc990c444f26dc70627c047e52910a6b9a5bf5f75412f8236e612b8f5cc1) and Ledger version(565273447)","error_code":"account_not_found","vm_error_code":null}` is shown in the console after clicking on Claim button

Expected result: Transaction is completed

Attachment:
TX Goerli -> Aptos https://goerli.etherscan.io/tx/0x99b7a70ec6667e582ff44561ff37a8cbcb717ef2ad9f9b66a2bc411c9e5af7f2
TX Mumbai -> Aptos https://mumbai.polygonscan.com/tx/0xc4cf4eaf4dec262189b2692055ddebca435b5803b3be850128aa902e8058e25b

<img width="1333" alt="Screenshot 2023-06-30 at 15 00 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d53a35b7-fade-4a5e-b6b9-d8189d88c258">

<img width="1362" alt="Screenshot 2023-06-30 at 14 48 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bcd3424f-dfdb-41f3-9397-d48e7ddfbf61">

**Comment by AigaD** [comment]
Issue still reproducible.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1321" alt="Screenshot 2023-10-06 at 15 58 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/25e8f51f-6247-466c-9e76-6445771d4eca">

**Comment by tsadovska** [comment]
Linked to #718, #1051.

**Comment by AigaD** [comment]
Tested OK. Closing the ticket.
Tested from: https://wormhole-connect.netlify.app/#
TX - https://mumbai.polygonscan.com/tx/0x67eadcd76b69fa0b925848f60a79fff84eaacb2f07cf318ebcd9e1b082b84dab
Attachment:
<img width="1265" alt="Screenshot 2023-10-30 at 17 18 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0c0746a5-13ea-4299-902d-253ccd4ab46a">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/26939fa2-6dac-4e89-b031-a0cc259ef92a
