### ISSUE TITLE
[QA] Link “Add <asset> to your wallet” is not clickable

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#739]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet] 

#### Steps:

1. Connect Metamask wallet in From and To sections
2. Send  0.01 AVAX from Fuji  to Alfajors
3. Click “Add WAVAX to your wallet” link on Redeem screen

#### Actual result:
Error is displayed in Console:

`MetaMask - RPC Error: Invalid decimals "[object Object]": must be 0 <= 36. {code: -32602, message: 'Invalid decimals "[object Object]": must be 0 <= 36.'}`

#### Expected result:
Metamask notification is opened.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:
<img width="1288" alt="metamask-rpc-error" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/590ad3c4-0b2f-401c-9954-d659b5613f3b">

**Comment by tsadovska** [comment]
Issue is also reproducible on https://mainnet--wormhole-connect.netlify.app/ when sending 0.000001 WETH from Ethereum (Metamask) to Base (Metamask). 
Error is displayed in Console when clicking on "Add WETH to your wallet" link:
`MetaMask - RPC Error: Invalid decimals "[object Object]": must be 0 <= 36. {code: -32602, message: 'Invalid decimals "[object Object]": must be 0 <= 36.'}`

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending 0.001 USDC from Osmosis (Leap) to Goerli (Metamask).

**Comment by AigaD** [comment]
Issue is reproduced for transaction DAI from Osmosis to Ethereum from https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/#
user is not able to add DAI token to Metamask wallet
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4cdc58e9-b424-434f-a606-3c4585e5fd60

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet]. Ticket is closed.
