### ISSUE TITLE
[QA]"MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC" error is shown after clicking Claim

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#744]
Preconditions:
1. Rise wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 WMATIC from Aptos to Mumbai
2. Click Approve and proceed with transaction
3. Wait till option Claim is available
4. Click on Claim
5. Observe

Actual result: Error message `MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC` is shown in the console after clicking Claim, transaction fails

Expected result: Transaction is completed

Attachment:
<img width="1336" alt="Screenshot 2023-07-03 at 15 58 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6ac1ddeb-c567-4ad1-85cc-2569a131f254">

**Comment by tsadovska** [comment]
Issue is also reproducible on https://mainnet--wormhole-connect.netlify.app/# when claiming baseETH on Fantom for the first time. Was sending 0.0001 baseETH from Base (Metamask) to Fantom (Metamask). Issue is not reproducible when clicking on "Claim" button again. Error in Console: 
`MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"header not found"}}}' {code: -32603, message: [ethjs-query] while formatting outputs from RPC '{…":{"code":-32000,"message":"header not found"}}}'`

**Comment by AigaD** [comment]
Will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/946 is fixed

**Comment by AigaD** [comment]
Tested OK. Closing the ticket
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.001 WMATIC from Aptos (Rise) to Mumbai (Metamask) is completed

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a07c96be-7dfe-4da5-bdcf-ad10c013beae

Tested from: https://wormhole-connect-mainnet.netlify.app/
Transaction 0.0001 ETH (Base) from Base to Fantom is completed.
Comments: First Claim for transaction failed, this is reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/1115#issue-1942087209


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a789a89d-cf55-46c8-ad82-48f1b7b40769
