### ISSUE TITLE
[QA] Fin wallet option is not clickable on “Connect wallet” window when extension is installed but account is not created

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#746]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet] 

#### Preconditions:

- User has installed “Fin Wallet For Sei” extension 
- User hasn’t created Fin wallet account

#### Steps:

1. Click “Connect wallet” button
2. Select “Fin” option

#### Actual result:
Clicking on "Fin" option has no effect.

#### Expected result:
“Fin”  extension is opened. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3962011f-6e70-46b0-9d5c-c8c0035ea8d6

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
Closing, this is no longer reproducible.
Tested from: https://wormhole-connect.netlify.app/#
Fin Create account is opened when clicking on Fin wallet on Connect wallet.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f880ac9e-f4fb-427f-b9e0-587200f249e6
