### ISSUE TITLE
[QA] User is not able to connect WalletConnect wallet 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#747]
#### Builds:
https://wormhole-connect.netlify.app/ [Testnet] 
https://mainnet--wormhole-connect.netlify.app/ [Mainnet]

#### Scenario 1:

1. Click “Connect wallet” button and select “WalletConnect” option
2. Scan QR Code from mobile (iOS or Android)

#### Scenario 2:

1. Click “Connect wallet” button and select “Wallet Connect” option
2. Open Desktop tab
3. Select any wallet (in my case, Zerion)

#### Actual result:

- User is not able to Connect Wallet Connect wallet with QR Code or Desktop app
- Error is displayed in Console:

`WebSocket connection to 'wss://r.bridge.walletconnect.org/?env=browser&host=wormhole-connect.netlify.app&protocol=wc&version=1' failed: `

#### Expected result:
User is able to connect Wallet Connect wallet.

#### Devices:

- MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)
- Samsung S20 Android 12, MetaMask v6.6.0 (1114)
- iPhone 11 Pro, iOS 16.5.1, Binance 2.63.4
- iPhone 11 Pro, iOS 16.5.1, MetaMask 6.3.0

#### Attachment:
<img width="1586" alt="Screenshot 2023-07-05 at 15 20 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e8f941f3-ac72-4c84-86bb-87405ed7939a">

**Comment by tsadovska** [comment]
Issue is reproducible on mobile:

- Android
  - Samsung S20 Android 12, Chrome Version: 114.0.5735.196
  - Metamask version 7.1.0
  - KEYRING PRO version 2.7.0 - Error message “This QR Code is no longer available” is displayed for the user
  - Zerion version 2.38.1 - Error message “Close this window and try again” is displayed for the user

- iOS
  - iPhone 11 iOS 15.4.1, Chrome Version 112.0.5615.70
  - Metamask version 7.2.0 (1142)

Checked on https://wormhole-connect.netlify.app/ [Testnet].

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1f9130be-a310-4225-8c25-268e10ed8eb3

**Comment by tsadovska** [comment]
Rechecked the issue. It is still reproducible on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] when connecting Metamask wallet through WalletConnect with QR Code. 

Error in Console:
`WebSocket connection to 'wss://k.bridge.walletconnect.org/?env=browser&host=mainnet--wormhole-connect.netlify.app&protocol=wc&version=1' failed: `

Devices:
* macOS Monterey 12.6.5, Chrome Version 115.0.5790.102 (Official Build) (x86_64)
* iPhone 11 Pro, iOS 16.5.1, Metamask v.6.3.0 (1095)

**Comment by tsadovska** [comment]
Issue is reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet].
User is not able to connect:
* Metamask wallet through WalletConnect with QR Code
* Zerion wallet through WalletConnect with Desktop app

Checked on macOS Monterey 12.6.7 with Chrome Version 115.0.5790.170 (Official Build) (x86_64).

**Comment by tonyjin** [comment]
Downgrading since metamask QR + walletconnect isn't the most common path.

**Comment by tsadovska** [comment]
Also reproducible from:
- https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]
- https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet]
- https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet]

**Comment by tsadovska** [comment]
Also reproducible from:
- https://cctp--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1015--wormhole-connect.netlify.app/ [Testnet]. User can't connect Metamask wallet through Wallet Connect QR code.

**Comment by AigaD** [comment]
Issue is reproducible. Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b35ca24e-a592-474f-999d-9914ec94ea22

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet].

**Comment by AigaD** [comment]
Reproducible from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#
User is not able to connect using Wallet connect

**Comment by aadam-10** [comment]
will be fixed in https://github.com/wormhole-foundation/wormhole-connect/issues/1276

**Comment by AigaD** [comment]
User is not able to connect to Metamask wallet that is installed on the device through WalletConnect option.
Tested from: https://wormhole-connect.netlify.app/
Environment: iPhone 14, iOS 15.0, Safari

Attachment:
https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6aa3010f-10e9-4e2c-a41e-64a028c84e01

**Comment by M-Picco** [comment]
@AigaD @tsadovska Could you please try again on https://wormhole-connect.netlify.app/?

**Comment by AigaD** [comment]
Tested OK
Tested from: https://wormhole-connect.netlify.app/
Environment: iPhone 14, iOS 16
Metamask wallet v 7.12.2

Attachment:

![Screenshot 2023-12-12 at 09 35 51](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8e48023f-8b9e-499c-893f-1ff0d5fbb8af)

Environment:MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159
Zerion desktop app version 2.13.0
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/825daeaa-6000-4f6c-aca0-9564ca619788

**Comment by tsadovska** [comment]
Reopening the ticket.
Error appears in Console when clicking on WalletConnect option:
```
Uncaught (in promise) Error: No matching key. keychain: dc5d459d04eb169746b6fa8c89fc1b870288ae076584170db37cd6b48de7a23d
    at Li.get (main.9e6858c9.js:2:10813028)
    at Fi.getSymKey (main.9e6858c9.js:2:10817626)
    at Fi.encode (main.9e6858c9.js:2:10815450)
    at Ha.sendRequest (main.9e6858c9.js:2:10872800)
    at Ha.disconnect (main.9e6858c9.js:2:10870139)
    at async Wa.disconnect (main.9e6858c9.js:2:10891407)
    at async js.disconnect (main.9e6858c9.js:2:10982050)
    at async tc.disconnect (main.9e6858c9.js:2:10992708)
    at async UF.connect (main.9e6858c9.js:2:18668101)
    at async v4.evm.mO.walletConnect.connectorOptions.projectId.connect (main.9e6858c9.js:2:18659593) 
```
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7.1 and Google Chrome Version 120.0.6099.71 (Official Build) (x86_64). 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6141ed80-c743-4b77-9e81-9d35ce36522a

**Comment by AigaD** [comment]
No longer able to connect to Desktop app through WalletConnect.
Wallet itself shows that the connection is made, but in Wormhole-connect there is no identification that the wallet is connected.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/18df14a4-7ed2-442b-b1e3-7ce455c96277

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/ 
Environment: Samsing Galaxy S22+, OS12, Solflare app v1.35.0
When scanning QR code from Solflare mobile app, request shows as failed
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0b0a1a32-f287-489d-bdad-8aba76248bca

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Adding screenshots with observations of error messages that are received when trying to connect to Zerion desktop app through WalletConnect
Attachment:

![Screenshot 2023-12-20 at 16 49 37](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/16bf8400-3d2d-448c-b7a8-afea22af49b3)
![Screenshot 2023-12-20 at 16 50 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a3f4bb80-043f-43be-b2e4-9873fbe5baeb)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Metamask wallet is not connecting through WalletConnect mobile

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/87705fa4-18b5-4384-b234-41c9190ca789

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
It seems that connection to Zerion desktop app is created through WalletConnect, but it is not shown that the wallet is connected in Wormhole Connect app
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5fdee64c-4d78-466c-8d15-34ae3de700cd

**Comment by tsadovska** [comment]
Rechecked scenarios and split the ticket:
* User can connect WalletConnect (Ethereum) wallet with QR Code, Metamask - Tested OK
* User can successfully send assets when wormhole-connect is connected on Desktop and wallet is connected with QR Code - Tested OK
* User can connect WalletConnect (Ethereum) wallet on mobile, Metamask - OK
* User can connect WalletConnect (Ethereum) wallet with Desktop app, Zerion - Tested NOK, https://github.com/wormhole-foundation/wormhole-connect/issues/1495
* User can connect WalletConnect (Solana) wallet - Tested NOK, https://github.com/wormhole-foundation/wormhole-connect/issues/1508

Ticket is closed.
