### ISSUE TITLE
[QA] Typing more than 45 number in amount section pushes out the UI elements in "Sending to" section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#75]
When typing multiple numbers in the amount section for Sending from, the "Sending to" frame is affected as the Network UI gets smaller with each number added and eventually the Balance section is moved out the frame.

Preconditions:
Wallet is connected

Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on "Network" and click on any from the list (e.g. Goerli)
2. Choose a Token from the list (e.g. ETH)
3. Click on "Network" for "Sending to" and click on any from the list (e.g. BSC)
4. Go to amount section for "Sending from"
5. Type in >45 numbers
6. Observe the UI elements for "Sending to" section

Actual result: UI elements are squished and the balance value is pushed out the "Sending to" frame.

Expected result: Numbers should be restricted to go out the frame.

Attachments:
<img width="952" alt="Screenshot 2023-02-14 at 08 14 03" src="https://user-images.githubusercontent.com/91047061/218655136-9eed1711-b54d-4d22-be2e-4716968df5b8.png">
<img width="997" alt="Screenshot 2023-02-14 at 08 18 41" src="https://user-images.githubusercontent.com/91047061/218655251-4bf78533-647e-46b4-a37b-c3ccaa8c6ae2.png">

**Comment by anondev2323** [comment]
Checked on https://wormhole-connect.netlify.app/

<img width="696" alt="Screen Shot 2023-05-09 at 10 33 41 AM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/122566365/9b14050e-9b89-412a-a64a-aa75e6a6ba23">

**Comment by AigaD** [comment]
Tested OK.
Scenario: Verify that UI is not pushed out of its fields when typing >45 characters in Amount section.
Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/29103f78-6b6f-40bb-8006-cc722b1eef52
