### ISSUE TITLE
[QA] Failing to send wrapped asset to Sei 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#759]
Preconditions:
1. Metamask wallet connected at sending From section
2. Compass wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.01 WAVAX from Fantom to Sei
2. Click Approve and proceed with the transaction
3. Observe

Actual result: Error `Error: Attempting to use a disconnected port object` is shown in the console and user is not moving past Step 2

Expected result: Transaction is completed

Comments: TX - https://testnet.ftmscan.com/tx/0xf077aea17241f05e97f292604174601bf8ad3a6363e80dee19b7ccc3ca4be9bd

Attachment:
<img width="1350" alt="Screenshot 2023-07-12 at 12 26 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/39b10471-5eff-4191-a834-400eb23fcddf">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e0a56f84-15a6-4c8a-9a1c-6f76bc39b46b

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
Will be retested after https://github.com/wormhole-foundation/wormhole-connect/issues/1152 is closed

**Comment by tsadovska** [comment]
Scenario is mentioned in ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1152. 
Closing the ticket.
