### ISSUE TITLE
[QA] Transactions from Sei fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#762]
Preconditions:
1. Fin / Coin98 / Keplr wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 SEI from Sei to other Network (e.g. Fantom)
2. Click Approve and proceed with transaction
3. Observe

Actual result: Console shows error `'Wrong network. Please switch network!'}` and the transaction is not moving forward to the next screen

Expected result: Transaction moves forward 

Comments: Using Fin or Keplr wallet there were no visible error messages shown to the user, only endless loading

Attachment:
<img width="1336" alt="Screenshot 2023-07-13 at 10 34 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7f2cab09-426e-402e-907e-877e81408cbe">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9add5e5-df29-4d16-8959-c5cb359847fc

<img width="1335" alt="Screenshot 2023-07-13 at 10 41 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/07cd88c0-73f1-41d0-8c9b-09dafd20bb4f">

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect.netlify.app/ [Testnet]. It is also reproducible with Compass wallet.

`Error: Broadcasting transaction failed with code 13 (codespace: sdk)` appears in Console when user sends 0.001 SEI from Sei (Compass wallet) to Aptos (Spika wallet).

![Screenshot 2023-07-14 at 19 30 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d1f7e67b-1b67-4dbc-8e4d-fc9f46f3e213)

**Comment by tsadovska** [comment]
Rechecked scenario "Send SEI from Sei (Fin wallet) to Moonbase (Metamask)" on https://wormhole-connect.netlify.app/ [Testnet].

- Sometimes error appears in Console:

```
Error: Sei transaction failed with code 11. Log: out of gas in location: ReadFlat; gasWanted: 250000, gasUsed: 250126: out of gas
    at wallet.ts:235:11
    at async As (wallet.ts:281:13)
    at async index.ts:177:11
    at async Object.onClick (Send.tsx:104:13)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cd208038-1d8f-44e7-9c93-63379919d978)

- Sometimes transaction is displayed as loading for more than 15 minutes. Redeem screen does not open. 

Error in Console:
`Uncaught (in promise) {code: 4002, standard: 'EIP-1193', message: 'Wrong network. Please switch network!'}`


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1f4b0a26-8fe4-4546-821b-0a0b2b5bc532

**Comment by tsadovska** [comment]
Linked #789

**Comment by tsadovska** [comment]
Transaction fails with error code 29 when sending 0.001 SEI from Sei (Fin) to Base Goerli (Metamask).
Error:
```
Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 1: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-55) with status Expired: client is not active
    at wallet.ts:235:11
    at async ws (wallet.ts:281:13)
    at async index.ts:177:11
    at async Object.onClick (Send.tsx:104:13)
```
![Screenshot 2023-08-08 at 15 09 14](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e3d27194-b221-49b3-b7c1-316111e8ed53)

**Comment by AigaD** [comment]
Transaction from Sei -> Base Goerli fails with error code `Error: Sei transaction failed with code 29. `
Tested from: https://base-relayer--wormhole-connect.netlify.app/#
Tested using Keplr, Leap, Compass, FIN wallets
Observations: Transaction fails to start, but funds are deducted from the wallet #789 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cbd8deff-ed93-461b-add5-79194e5738bd

<img width="1337" alt="Screenshot 2023-08-10 at 09 03 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf7024df-9f51-4d81-a567-a1a86adfbff7">

**Comment by tsadovska** [comment]
Issue is also reproducible with Falcon and Coin98 wallets. Checked from https://base-relayer--wormhole-connect.netlify.app/ [Testnet]. 
* Error when sending 0.001 SEI from Sei (Falcon) to BSC (Metamask)
```
Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 1: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-55) with status Expired: client is not active
    at wallet.ts:235:11
    at async ws (wallet.ts:281:13)
    at async index.ts:177:11
    at async Object.onClick (Send.tsx:104:13) 
```
* Error when sending 0.001 SEI from Sei (Coin98) to Fuji (Metamask)
```
Error: Broadcasting transaction failed with code 5 (codespace: sdk). Log: 
    at s.broadcastTx (stargateclient.ts:449:9)
    at async dg.signAndSendTransaction (index.ts:260:11)
    at async wallet.ts:232:9
    at async ws (wallet.ts:281:13)
    at async index.ts:177:11
    at async Object.onClick (Send.tsx:104:13)
```

**Comment by tonyjin** [comment]
Sei is not officially supported yet, downgrading from P0 -> P1.

**Comment by tsadovska** [comment]
Linked #954

**Comment by tsadovska** [comment]
Linked #661.

**Comment by tsadovska** [comment]
Issue is also reproducible when sending assets from Sei. Transaction is stuck on Step 2 when sending 0.001 SUI from Sei (Fin) to Fuji (Metamask). Sei explorer link is not found, https://github.com/wormhole-foundation/wormhole-connect/issues/671.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9ade9c7a-d8f8-4782-9a3e-d760fffee1fd)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.009 SUI from Sei (Fin) to Fuji (Metamask). 

Error after clicking on "Approve and proceed with transaction" button:
```
Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-117) with status Expired: client is not active
    at signSeiTransaction (main.js:477:314620)
    at async signAndSendTransaction (main.js:477:315494)
    at async BridgeRoute.send (main.js:481:22384)
    at async Operator.send (main.js:483:79179)
    at async Object.Qn [as onClick] (main.js:649:95817)
```


![Screenshot 2024-01-15 at 16 14 31](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/31e84b5d-fd32-416b-8840-0606ad6b7fb0)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.01 SEI from Sei (Compass) to Arbitrum Goerli (Metamask) fails, reason `Error: Sei transaction failed with code 29.`

Attachment:
![Screenshot 2024-01-19 at 14 12 00](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/919c0f3c-f62f-4818-b4b3-2a24e9d7363d)
![Screenshot 2024-01-19 at 14 11 45](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dc33d62e-1aec-4aaa-97bf-76d8071d46b3)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Transaction from Sei (Leap) to Base Goerli (Rabby) fails.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ff90125a-4134-4518-8dd4-df7b7ea2e015

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Issue reproducible, transaction from Sei to Arbitrum fails, reason: `main.js:696 Error: Sei transaction failed with code 29.`
Attachment:

![Screenshot 2024-02-13 at 14 47 30](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9edab678-d16c-45ea-8dfc-98440e37c018)

**Comment by tsadovska** [comment]
Reproducible on [testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk6SBXyEIKYZJQz5ipmwBWqggLCa5MRQHUAsgEEAKgEkAwmogBfEJ6A%3D) when sending 0.0001 WMATIC from Sei (Leap) to Fuji (MetaMask). 
Error appears in Console after user clicks on "Approve and proceed with transaction" button:
```
Wormhole Connect: error completing transfer Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-117) with status Expired: client is not active
    at PL (sei-w-rbnmO_.js:100:82846)
    at async signAndSendTransaction (main-wban9g4X.js:484:781892)
    at async BridgeRoute.send (main-wban9g4X.js:486:23800)
    at async Operator.send (main-wban9g4X.js:489:132100)
    at async Object.er [as onClick] (main-wban9g4X.js:524:31299)
```

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 from Sei (Leap) to BSC (MetaMask). Error appears in Console after clicking on "Approve and proceed with transaction" button:
```
Wormhole Connect: error completing transfer Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 1: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-117) with status Expired: client is not active
    at mY (sei-CwHDmEwL.js:98:70392)
    at async signAndSendTransaction (main-Cubx2sfv.js:506:73252)
    at async BridgeRoute.send (main-Cubx2sfv.js:506:93108)
    at async Operator.send (main-Cubx2sfv.js:509:91731)
    at async Object.tr [as onClick] (main-Cubx2sfv.js:547:35185)
```

**Comment by tsadovska** [comment]
Issue will be re-rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/2372 is resolved.
