### ISSUE TITLE
[QA] Unable to send SEI from Sei to Moonbase

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#768]
Preconditions:
FIN wallet connected at sending From section
Metamask wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 SEI from Sei to Moonbase
2. Click Approve and proceed with transaction
3. Observe

Actual result: Error `Uncaught (in promise) ` is shown in the console, endless loading and user is not transferred to next screen of the transaction

Expected result: User is taken to next screen where transaction is completed

Attachment:
<img width="1337" alt="Screenshot 2023-07-17 at 16 25 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d71ac069-c18f-43e1-9021-f0818fac8ab0">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a82cb857-41f4-4fd1-a87f-f4e6d37161c0

**Comment by tsadovska** [comment]
Closing this issue. Scenario is included in ticket #762.
