### ISSUE TITLE
[QA] Error in creating associated account

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#770]
Preconditions:
Compass wallet connected at sending From section
Nightly wallet connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 SEI from Sei to Solana
2. Field "No associated token account exists for your wallet on Solana. You must create it before proceeding." should appear
3. Click on "Create account"
4. Click Approve on the wallet pop-up window
5. Observe

Actual result: Create account encounters an error

Expected result: Associated account is created user can continue with transaction

Attachment:
<img width="1344" alt="Screenshot 2023-07-18 at 08 36 06" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c7c5e0e-5ee9-4dbf-a949-cebae27de42f">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6702ce0d-37e4-49e0-b8f2-f15e68766fce

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
Tested OK. Closing the ticket.
Tested from: https://wormhole-connect.netlify.app/#
User is able to Create associated account for Sei ->Solana transaction
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/54a1561f-960b-4abf-b884-04329e460a08

**Comment by AigaD** [comment]
Re-opening the ticket, reproduced from: https://preview.portalbridge.com/df5df83982/#
Cannot create associated account for transaction 1 GLMR from Moonbeam to Solana
Attachment:

![Screenshot 2023-11-23 at 18 10 46](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9dd83e12-ba1f-43ee-b246-57f64cd79b2b)

**Comment by AigaD** [comment]
Closing, tested OK.
Transactions that are mentioned in ticket are not requiring to create associated account.
Tested from: https://wormhole-connect.netlify.app/#
Tested:
Sei (SEI, APT)-> Solana
Moonbase (GLMR) -> Solana
Aptos (APT, USDC) -> Solana
Arbitrum Goerli (USDC) -> Solana
