### ISSUE TITLE
[QA] Fails to switch from Mumbai to BNB Network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#771]
Preconditions:
1. Metamask wallet connected at sending From section
2. Martian wallet connected at sending To section
3. Console is open
4. Previously transaction from Mumbai (Polygon) to Aptos was made ( Linked issue - https://github.com/wormhole-foundation/wormhole-connect/issues/762#issue-1802409609 )

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 BSC from BNB to Aptos
2. Click Approve and proceed with transaction
3. Observe wallet pop-up window

Actual result: Wallet is trying to connect to Polygon Mumbai Network although BNB should be connected, the connection fails

Expected result: Network is switched to BNB

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/660740cc-10ad-4b78-ad0f-11146720c8d2

**Comment by tsadovska** [comment]
Issue is also reproducible when trying to connect to Polygon Mumbai network. Checked on https://wormhole-connect.netlify.app/.

Steps:
1. Prepare to send 0.01 MATIC from Mumbai (Metamask) to Aptos (Fewcha)
2. Click "Approve and proceed with transaction" button

Actual result: 
* Transaction is displayed as loading, wallet is trying to connect to Polygon Mumbai network
* "We can't connect to Polygon Mumbai" is displayed in Metamask wallet

![Screenshot 2023-07-26 at 19 48 13](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d02b7bd-7aba-4dd1-9ea2-763f29e054dc)

**Comment by tsadovska** [comment]
Linked #778

**Comment by tsadovska** [comment]
Issue is reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet] when sending MATIC from Mumbai (Metamask) to Goerli (Metamask). 

<img width="1484" alt="Screenshot 2023-08-11 at 10 55 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/11843f3f-4548-42b1-94df-d717aca33103">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. User can successfully switch between networks.  Ticket is closed.
