### ISSUE TITLE
[QA] User is not able to connect Keplr wallet when Coin98 wallet extension is enabled

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#772]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet]

#### Precondition:
“Coin98 Wallet” and Keplr extensions are installed and are enabled

#### Steps:

1. Click “Connect wallet” button
2. Try to connect Keplr waller

#### Actual result:

- User is not able to connect Keplr wallet
- Error is displayed in Console:

`Uncaught (in promise) {code: 4002, standard: 'EIP-1193', message: 'Wrong network. Please switch network!'}`

#### Expected result:
User is able to connect Keplr wallet.

#### Note:
Issue is not reproducible when Coin98 extension is disabled. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachments:

- wormhole-connect

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7c48ab53-8498-4dad-af27-5db4485e98d4

![Screenshot 2023-07-18 at 19 49 30](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0d13cf3d-8b26-419d-a47e-f5fe5a0ccc27)

- Coin98 wallet:

![Screenshot 2023-07-18 at 19 50 10](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/589f3106-054b-488c-93a5-4dc4d3b9eed3)

![Screenshot 2023-07-18 at 20 00 23](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/23394045-946d-4c69-80b9-0f1c7df670b5)

**Comment by AigaD** [comment]
Issue is also reproducible from: https://deploy-preview-1014--wormhole-connect.netlify.app/#
Coin98 wallet is opened instead of Keplr
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fc8e0136-7882-4e11-bc02-3606caed759e

**Comment by AigaD** [comment]
Issue is reproduced from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9384db2c-d167-4d1f-9930-004c8877b065

**Comment by tsadovska** [comment]
Issue was caused by "Override wallet" option in Coin98 wallet.

Ticket is closed.
