### ISSUE TITLE
[QA][Fewcha Move] cannot send SUI from Sui to Solana

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#773]
Preconditions:
1. Fewcha Move wallet connected at sending From section
2. Solflare wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 SUI from Sui to Solana
2. Click Approve and proceed with transaction
3. Observe

Actual result: Error sending transaction is shown, console shows error `Send.tsx:131 Error: RPC Error: Package object does not exist with ID 0x562760fc51d90d4ae1835bac3e91e0e6987d3497b06f066941d3e51f6e8d76d0`

Expected result: Transaction is moved forward to next screen and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b91098d-fa84-4085-b6b2-88768ef0e8c2

**Comment by tsadovska** [comment]
Transaction can be approved, but loading does not finish on Bridge screen. To complete the transaction, user needs to find it in the wallet and then resume it. Remaining issue is described in ticket #1054.
Ticket is closed.
