### ISSUE TITLE
[QA] Asset that is not present on "Select asset" screen is left connected when switching Network

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#777]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet]

#### Precondition:
User doesn’t have SUI on Alfajores network

#### Steps:

1. Select Sui network
2. Connect Sui wallet
3. Select SUI asset
4. Change network to Alfajores
5. Connect Metamask wallet
6. Open Assets list
7. Check if SUI asset is present

#### Actual result:
SUI asset is not present.

#### Expected result:
SUI asset is present. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0b71eca7-9b83-4f51-9bed-8d7e1a2ab41e

**Comment by AigaD** [comment]
The same behaviour also noticed if user from Sui Network switches to other Networks that does not have Sui balance. In attached example switching from Sui to Fantom Network.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6d0e8d2-a8a5-45b4-85de-1b5c7ebe868f

**Comment by AigaD** [comment]
The same behaviour also noticed if user from Sui Network switches to other Networks that does not have Sui balance. In attached example switching from Sui to Fantom Network.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6d0e8d2-a8a5-45b4-85de-1b5c7ebe868f

**Comment by AigaD** [comment]
Issue is reproducible. Tested from: https://wormhole-connect.netlify.app/#
User does not have any SUI available on Base Goerli Network, but asset is left connected when switching Network.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9b10cf8-3c6c-4f6b-8907-0e02ecc71949

**Comment by AigaD** [comment]
Reproduced also from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D)
SUI asset is left connected after changing to network where asset is not available
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f45630e-20f5-4b63-af0c-a04b7a1dbc0c

**Comment by tsadovska** [comment]
Token balance is displayed correctly, closing as not a bug.
