### ISSUE TITLE
[QA] Transaction is not starting

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#778]
Preconditions:
1. Metamask wallet connected at sending From section
2. Phantom wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 MATIC from Mumbai to Solana
2. Click Approve and proceed with transaction
3. Observe

Actual result: Console shows `'Wrong network. Please switch network!'}` and the transaction is not moving forward

Expected result: Transaction moves forward to next step and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/99f78d8e-bc60-423a-8742-48f827499313

<img width="1334" alt="Screenshot 2023-07-20 at 11 27 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/829238c5-708e-4620-8700-90111cb3ffa8">

**Comment by AigaD** [comment]
Also transaction Mumbai -> Moonbase is not moving forward.

Attachment:
<img width="1368" alt="Screenshot 2023-07-21 at 09 36 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/51f34bbc-fde5-4113-8a52-23c0a9061d7c">

**Comment by AigaD** [comment]
Also Mumbai -> Alfajores transaction is not moving forward.
Attachment:
<img width="1346" alt="Screenshot 2023-07-24 at 11 20 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cf82677d-8246-4bf8-a629-e80ecfa00b75">

**Comment by AigaD** [comment]
Transaction from Aptos to Base Goerli not starting. Tested from: https://base-relayer--wormhole-connect.netlify.app/#
Attachment:
<img width="1345" alt="Screenshot 2023-08-09 at 17 53 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1af65532-ff0c-4ab7-8c16-1634f8dcbf38">

**Comment by AigaD** [comment]
Transaction from Moonbase (Metamask) -> Osmosis (Keplr) is not starting, was left in this state for more than 1 hour.
Tested from https://feat-cosmos-gateways--wormhole-connect.netlify.app/
Attachment:

<img width="1327" alt="Screenshot 2023-08-30 at 13 47 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/daac55f0-459c-496a-a71b-3193884a2bdc">

**Comment by AigaD** [comment]
Transaction MATIC from Polygon to Osmosis is not starting.
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
Test did not start for around 15min.

Attachment:
<img width="1340" alt="Screenshot 2023-09-01 at 09 36 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cb0ffae6-2fe9-4e53-bfd4-6ed5960d360e">

**Comment by tsadovska** [comment]
Rechecked that transactions are started and Redeem screen is displayed.

1. Build https://wormhole-connect.netlify.app/.
   Scenarios - Tested OK:

  - Send MATIC from Mumbai to Solana
  - Send MATIC from Mumbai to Moonbase 
  - Send MATIC from Mumbai to Alfajores

2. Build https://base-relayer--wormhole-connect.netlify.app/ 
Scenario: Send APT from Aptos to Base Goerli

3. Build https://feat-cosmos-gateways--wormhole-connect.netlify.app/ 
Scenario: Send GLMR from Moonbase to Osmosis

4. Build https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ 
Scenario: Send MATIC from Polygon to Osmosis

**Comment by AigaD** [comment]
Reopening. Issue reproduced from: https://wormhole-connect.netlify.app/# for transaction 0.0001 WETH (Base) Osmosis - > Mumbai
Attachment:
<img width="1319" alt="Screenshot 2023-10-02 at 16 07 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5a160a3f-7525-4233-be45-b6a15d61240f">

<img width="1337" alt="Screenshot 2023-10-02 at 16 06 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/031b8742-8d42-4660-84ee-f16f4173270b">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/79f649f0-60d5-4496-b3d1-34391c961197

**Comment by AigaD** [comment]
Issue reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
Transaction DAI from Osmosis (Keplr: osmo1xd76p37ahas9danxf02vxsdskqt8xuugrsvlmq ) to Solana (Solflare: zdv8TPs7wQR216Gghrk7GafmgM5oRnoNt66Zjo936tf ) is not starting, funds are deducted.

Attachment:
<img width="1332" alt="Screenshot 2023-10-04 at 13 14 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b0620cfa-bbd9-4dfb-92cd-ef08405ad98e">


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b8de6bb5-dca7-4b0b-8a64-94575db5c992

**Comment by AigaD** [comment]
`Error: Chain is not cosmos chain` is shown in the console when starting a transaction WETH (Base) Osmosis -> Mumbai
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae141683-61e7-4d48-99b6-884273bf79f6

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction Sui from SUI -> Arbitrum Goerli is not starting. Transaction has been on Bridge screen on loading process for approximately 7min and has not moved forward.
Attachment:

![Screenshot 2023-10-13 at 11 33 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/17b563e5-eb30-4158-a3fa-0d801fbe2b84)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction Sui to Cosmoshub is not starting, user stays on the first screen for more than 10min
Attachment:
![Screenshot 2023-10-18 at 12 21 17](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9d3306ad-7b47-4666-839a-d65bec55265d)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.01 APT from Osmosis (Keplr) to Cosmoshub (Leap) is not starting.
Attachment:
![Screenshot 2023-10-19 at 12 55 13](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9d9d375b-c280-4a9f-b78f-be3d210dfaaa)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Transaction 0.001 USDC from Osmosis to base is not starting, reason in console `GET https://wormhole-connect-mainnet.netlify.app/manifest.json 401 (Unauthorized)`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/99004c4c-f0d9-4df8-8260-0ad4ede7e3c6

**Comment by kev1n-peters** [comment]
Have not been able to reproduce this case https://github.com/wormhole-foundation/wormhole-connect/issues/778#issuecomment-1781028204 - seems like it might be related to requests timing out in the wallet extension?

**Comment by AigaD** [comment]
Will be retested after https://github.com/wormhole-foundation/wormhole-connect/issues/1111 is closed

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.01 SUI from Sui to Cosmoshub is not moving forward to next screen
[Sui explorer](https://suiexplorer.com/txblock/FaVVA6cdCEzWfoPiRBs1RRPCEaMMcn633phx7B7pfpTX?deviceId=e0da162e-c591-4a16-bbe1-889b92358745&network=testnet)
 Attachment:

![Screenshot 2023-11-06 at 15 55 23](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a15b8657-546d-48b7-97f3-d5cd36061844)
![Screenshot 2023-11-06 at 15 54 15](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb242465-632c-4099-855a-335f12534f8c)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.1 SUI from Sui to Kujira is not starting. Transaction is not moving to the next screen for more than 25min

Attachment:
![Screenshot 2023-11-07 at 12 34 35](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/156745f0-8571-4617-93dd-7366536eb64c)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from Sui to Evmos is not starting.
Attachment:
![Screenshot 2023-11-07 at 17 40 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/68d51345-61bf-46f6-b47c-4f0a21dbfbb9)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.01 SUI from Sui (Sui wallet) to Osmosis (Keplr). Loading does not finish and Redeem screen does not open.

**Comment by AigaD** [comment]
Environment: MacBook Pro, macOS Ventura 13.0.1, Firefox Version 115.0
Tested from: https://wormhole-connect.netlify.app/#
Transaction from Mumbai not starting.
Metamask wallet to change Network is shown, but to confirm the transaction is not shown.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/813699ab-0d7e-4aa1-9fde-c91c7dbbafa2

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.01 USDC from Moonbase (Rabby wallet) to Alfajores (Rabby wallet) is not starting
Tested OK from https://wormhole-connect-mainnet.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e749eead-1684-4502-a5cb-68a7432eb36d

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction from [Osmosis](https://www.mintscan.io/osmosis/transactions/3A0CCE8047B42F581AD70323069C37C94FFFE5061A851E4159DE7DC0BEDAB02B) to [Solana](https://solscan.io/tx/4n6871N16QDN8TEVEj9UeKE2s4zLxytkxKNvAp4QYh2PvAXFNS3y9WWwHbXdBdZ62BKgp1UZswvTcfyJ26F5x6uw) was completed
Transaction from [Osmosis](https://www.mintscan.io/osmosis/transactions/51A0C97CC61DC932689143501409016977F7D998077313E6BBD7A921F0200373) to [Base](https://basescan.org/tx/0xc957d8ff57c40ed51ed3569858f120ad0e14e3eb1b0ce2c813abac54b72989e5) was completed
Transaction from [Aptos](https://explorer.aptoslabs.com/txn/0xae23605734516a0a1b7a6506486cf73eaec0905b15f9fde2853ca445be38ce54?network=mainnet) to [Osmosis](https://www.mintscan.io/osmosis/tx/752F988FED06B1377C2B6C83DC7618722CAE6B2481A77CF04233FF9EC873570A) was completed
Transaction from [Sui](https://suiexplorer.com/txblock/9tQsKFahqDeTDtQ44Rydn5JYSQyLLnTfowFnwsJzveuE) to [Kujira](https://finder.kujira.network/kaiyo-1/tx/7533298EB96DA1CE5B90D9011478ABAEF204C4034EB99CCEF53C2AD745127EB1) was completed
Transaction from [Moonbase](https://moonscan.io/tx/0x30d91ab0b802afde7e49748feda6c758b1bd4689df8c36c6019b6d46a02db79a) to [Alfajores](https://explorer.celo.org/mainnet/tx/0xfdfa9a7078bdde3977259cabacd3dcaa725e13f4099d57a853302fff4975525a) was completed
Tested from: https://wormhole-connect.netlify.app/#
Transaction from [Moobase](https://moonbase.moonscan.io/tx/0x0a6b1f3ceb4f92064a592b10dab6922727c3ba3af58c8a984d051ab6633a6570) to [Alfajores](https://explorer.celo.org/alfajores/tx/0x3548dc1bd2fb79f7848a683add3d3f36b98bef27478ce41e69716e88a62a53cd) was completed
