### ISSUE TITLE
[QA] ETH value changes to zero in “Native gas” section when slider is moved

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#779]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send 0.263 USDC from Fantom to Goerli
3. Expand “Native gas” section
4. Change slider position
5. Observe ETH value

#### Actual result:

- ETH value changes to zero
- USDC value is displayed correctly

#### Expected result:
ETH and USDC values are displayed correctly.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.198 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/377f399a-00c6-4746-a823-c667edb8cef1

**Comment by AigaD** [comment]
Same issue reproduced from https://base-relayer--wormhole-connect.netlify.app/# ETH Native gas changes back to 0 ETH when slider is moved.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e77a6b81-e251-49e6-a054-853d859fb26f

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Correct ETH value is displayed when slider is moved. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/57fee118-a6cf-474c-b00b-26b2628aeba5
