### ISSUE TITLE
[QA] Option pay with one transaction is given then disappears

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#782]
Preconditions:
Metamask wallet connected at sending From section
Phantom wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.001 FTM from Fantom to Solana
2. At sending To section switch Solana Network to Moonbase
3. Click on "Switch to manual claim transfer"
4. Connect sending To wallet to Metamask wallet
5. Observe Gas payment section
6. Click on pay with One transaction
7. Observe

Actual result: When switching to Moonbase and manual claim both options pay with one and pay with two transactions are present, but when clicking on pay with one transaction, the one transaction option disappears and there is a glitch where Native gas section shows for a short moment

Expected result: User should be warned regarding minimum amount for automatic claim

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b3731483-42db-45cc-a860-768745a74f4c

**Comment by tsadovska** [comment]
Remaining issues:
* #1052
* #942 

Ticket is closed.
