### ISSUE TITLE
[QA] Aptos assets are not received in the wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#786]
Preconditions:
Pontem Aptos wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.01 APT from Aptos to Fuji (Mumbai, BSC etc.)
2. Click Approve and proceed with transaction
3. Wait until transaction is finished
4. Copy Metamask wallet address
5. Open Avascan (https://testnet.avascan.info)
6. Paste the wallet address and search for the transaction

Actual result: Transaction from Aptos is not found

Expected result: Transaction with 0.01 APT should appear in the wallet transaction history

Attachment:
Wallet address - 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01
TX - https://explorer.aptoslabs.com/txn/0x1629bdbe07dd4314553a271b79c13c9bd26e108645efe61c83714720158a71c2?network=testnet

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a5bc6008-45f5-4e51-a1b4-47cc9b907a4a

**Comment by gmimnoah** [comment]
gm ser! So the Netlify app is more of an internal tool so it's changed and used for testing new things that might break. We think that in order to have the best testing environment, either build from our releases or use the NPM package in a new repo. Here's something I put together that you could use if you're trying to do something quick and dirty: [https://github.com/gmimnoah/lets-wormnect](https://github.com/gmimnoah/lets-wormnect)

**Comment by anondev2323** [comment]
@AigaD Could you please re-test this issue?

**Comment by anondev2323** [comment]
I'm not sure why it wouldn't show up on avascan, but I wouldn't consider that an issue with connect. We link to aptos labs explorer, where it can clearly be found.

**Comment by AigaD** [comment]
Closing the ticket as this is now fixed.
Asset is received in the wallet.

Attachment:
https://testnet.avascan.info/blockchain/c/tx/0x80a731082814a0f7c48220f8d41345acd32b44995ad9ce06a4dcf1e39a66ee4b

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/282dca5f-3770-46a7-a98f-e8f8550338c2

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f1c81bfd-38a8-483c-ab45-aef7e89787d9
