### ISSUE TITLE
[QA] [Fin] Transaction from Sei fails, but funds are deducted from the wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#789]
Preconditions:
1. Fin wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.0001 SEI from Sei to Fantom
2. Click Approve and proceed with transaction
3. Observe

Actual result: `Error: Sei transaction failed with code 11` is shown in the console, transaction fails and funds are deduced from the wallet

Expected result: Transaction continues to next screen

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/43e4c3bf-fd1c-43b9-9304-affacb62b5d0

**Comment by tsadovska** [comment]
Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
Tested OK. Transaction SEI from Sei to Fantom was completed
Tested from: https://wormhole-connect.netlify.app/
Attachment:

![Screenshot 2023-10-17 at 15 58 09](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6c6e4ad5-7892-455c-80b4-fd970fd1197b)

![Screenshot 2023-10-17 at 15 58 59](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/520a372b-763b-4536-aaa1-614b6dedf85e)
