### ISSUE TITLE
[QA] "Amount" written instead of "You will receive" at "Preview" section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#79]
Preconditions:
Wallet is connected

Tested from: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on "Network" and click on any from the list (e.g. Goerli)
2. Choose a Token from the list (e.g. ETH)
3. Fill in the amount
4. Click on "Network" for "Sending to" and click on any from the list (e.g. BSC)
5. Scroll down the page to section "Preview"

Actual result: Instead of "You will receive" it is written "Amount".

Expected result: By Sigma design instead of "Amount" at "Preview" section should be "You will receive".

Attachments:
Figma design:
<img width="592" alt="Screenshot 2023-02-14 at 13 53 07" src="https://user-images.githubusercontent.com/91047061/218735753-a483430a-d79f-4885-a594-ff6c1fab28bb.png">
Implemented:
<img width="723" alt="Screenshot 2023-02-14 at 13 53 01" src="https://user-images.githubusercontent.com/91047061/218736133-367c2981-1811-4163-b278-1c0ba7060c85.png">

**Comment by anondev2323** [comment]
Have had discussions with the designers about this.  "You will receive" is a bit misleading there because they also receive the native token amount.  Going to close this
