### ISSUE TITLE
[QA] Balance is not loading for Aptos wallets

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#790]
Preconditions:
Any Aptos wallet connected at sending From section (in attachment Pontem, Spika wallets are shown)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Connect any Aptos wallet (e.g. Spika)
2. Select Aptos Network
3. Open Asset list
4. Observe

Actual result: Balance is not loading for any of the assets

Expected result: Balance is shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0ebb2905-c2b3-4e8a-852a-e5ac25c298f2

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6cc46e5c-5fc3-46ca-8ee2-c82ee26f8e61

**Comment by tsadovska** [comment]
Can reproduce the issue on https://wormhole-connect.netlify.app/ [Testnet] with following wallets:
* Spika
* Fewcha
* Pontem
* Nightly
* Rise
* Martian
* Petra

Can't reproduce the issue on https://mainnet--wormhole-connect.netlify.app/ [Mainnet] with the same wallets:
* Spika
* Fewcha
* Pontem
* Nightly
* Rise
* Martian
* Petra

**Comment by AigaD** [comment]
Closing this as the issue is no longer reproducible. Aptos wallet balance are loading.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f54f485c-975a-4ad7-85d5-ce6499cc43b4
