### ISSUE TITLE
[QA] Keplr wallet option is not clickable

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#793]
#### Build:
https://wormhole-connect.netlify.app/ [Testnet]

#### Steps:

1. Try to connect Keplr wallet

#### Actual result:
Keplr wallet option is not clickable.

#### Expected result:
User can successfully connect Keplr wallet. 
#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 115.0.5790.102 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/66ed1053-f20b-466e-aaad-34c8cdcdffc3

**Comment by tsadovska** [comment]
Issue is also reproducible when Sei network is selected and then user tries to connect Keplr wallet.

**Comment by tsadovska** [comment]
Rechecked the issue. It is reproducible on:
- https://mainnet--wormhole-connect.netlify.app/ [Mainnet]
- https://wormhole-connect.netlify.app/ [Testnet]
- https://base-relayer--wormhole-connect.netlify.app/ [Testnet]

Chrome version: 115.0.5790.170 (Official Build) (x86_64)
Keplr version: 0.12.20

**Comment by tsadovska** [comment]
Keplr wallet option is not available. Issue will be rechecked after #954 is resolved.

**Comment by AigaD** [comment]
Issue reproduced from: https://wormhole-connect-mainnet.netlify.app/
Keplr wallet is un-clickable for Osmosis Network.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/60a4de37-7cab-4fc5-961b-dbc9617dd74a

**Comment by tsadovska** [comment]
Rechecked the issue after #954 is resolved. It is still reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Keplr wallet option is not clickable when Sei network is selected. Error is displayed in Console:
```
Uncaught (in promise) Error: There is no chain info for atlantic-2
    at r (injectedScript.bundle.js:2:51823)
```

**Comment by AigaD** [comment]
Tested OK. Keplr wallet is clickable, when Sei Network is selected
Tested from: https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0781ca60-db9b-4691-8242-477ddd94750a

Tested OK. Keplr wallet is clickable, when Osmosis Network is selected
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

<img width="1233" alt="Screenshot 2023-10-23 at 11 04 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/96ee0b78-b034-4b74-8db6-ba8d0b851795">

Closing the issue.
