### ISSUE TITLE
[Bug][QA]Cannot register Base token for transactions

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#796]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://mainnet--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.0001 ETH from Base to Polygon
2. Observe that message "This token is not registered, you must [register](https://www.portalbridge.com/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on Register
4. Confirm that https://www.portalbridge.com/#/register is opened
5. Click on Source section
6. Try to find Base

Actual result: Base Network is not present in the Source list

Expected result: Base Network is present, token is registered and user can continue with transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1057e6dd-68f1-4fe0-8e72-41c2ec164334

**Comment by AigaD** [comment]
Managing to register Base token by manually opening https://preview.portal-bridge-ui.pages.dev/18c38dbb6a/#/register

**Comment by aadam-10** [comment]
Portal recently went live with base support so now it's visible on https://www.portalbridge.com/#/register as well, can you verify with connect too?

**Comment by AigaD** [comment]
Confirming that Base asset is not available on https://www.portalbridge.com/#/register , but token Attest fails. Console shows error `Error: network does not support ENS`
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/86f2b177-ca65-4a38-97d9-dbf4577d7fec

**Comment by AigaD** [comment]
Closing. Issue is no longer reproducible. Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/# and https://wormhole-connect.netlify.app/
