### ISSUE TITLE
[QA] [Mainnet] Link to Polygonscan is missing

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#803]
## Describe the current behavior in detail
Link to Polygonscan is not displayed in "Send to" section on Redeem screen when sending WMATIC (in my case 0.00001) from Base (Metamask) to Polygon (Metamask). 

Tested from https://mainnet--wormhole-connect.netlify.app/ with macOS Monterey 12.6.5 and Chrome Version 115.0.5790.102 (Official Build) (x86_64).

Base tx: [BaseScan](https://basescan.org/tx/0x3ffe569c90328e332d4d1da46bdaa4e7198a2c45deeb6cf6dc14fde6c1a90804)

Steps:
1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send 0.00001 WMATIC from Base network to Polygon
3. Click "Approve and proceed with transaction" button
4. Observe if link to Polygonscan is displayed

![Screenshot 2023-08-04 at 15 29 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b8b1bf01-74e9-436d-8e31-7ee1649fc793)

## What is the expected/desired behavior
Link to Polygonscan is displayed.

**Comment by AigaD** [comment]
Closing. Tested OK from https://wormhole-connect.netlify.app/ and https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:
<img width="1197" alt="Screenshot 2023-09-22 at 16 17 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ceea9402-9556-4a70-8ea7-bad850cec22f">
