### ISSUE TITLE
[QA] [Testnet] Link to Bscscan is missing

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#811]
## Describe the current behavior in detail
Link to Bscscan is not displayed in "Send to" section on Redeem screen when sending ETH (in my case 0.0001) from Goerli (Metamask) to BSC (Metamask). 

Tested from https://wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallets in 'From' and 'To' sections 
2. Prepare to send 0.0001 ETH from Goerli to BSC
3. Click "Approve and proceed with transaction" button
4. Observe if link to Bscscan is displayed in 'Send to' section 

Notes:
* Issue is reproducible when searching for tx hash `0x8f7fefea257b5b9fee6d72a4a25166d29727e645702318165ddf25466f248e00` in Goerli network on 'Resume transaction' screen. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x8f7fefea257b5b9fee6d72a4a25166d29727e645702318165ddf25466f248e00)
* Similar issue: #803 

![Screenshot 2023-08-08 at 19 50 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f61390b7-ea4f-4563-a4b4-4f6425266102)

## What is the expected/desired behavior
Link to Bscscan is displayed.

**Comment by tsadovska** [comment]
Issue is reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WETH (Goerli) from Base Goerli (Metamask) to BSC (Metamask). "Pay with 1 transaction" option was selected in "Gas payment" section.

Send from tx: [BaseScan](https://goerli.basescan.org/tx/0xe4bc8888db0ae884447493d9ad3228117a8906073cc7bcbf6dd7accfaa8bf780)

![Screenshot 2023-08-10 at 11 18 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/db893ccb-68b5-4bd2-865c-78ae1eb714d4)

**Comment by AigaD** [comment]
Closing. Tested OK. Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/# and https://wormhole-connect.netlify.app/
Attachment:

<img width="1206" alt="Screenshot 2023-09-22 at 16 45 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/baf4c184-d0be-4522-899f-5fa671d2ac64">
