### ISSUE TITLE
[QA] Transaction fails sending Wrapped assets from Moonbase -> Base Goerli

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#820]
Preconditions:
Metamask wallet connected
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://base-relayer--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 WAVAX from Moonbase to Base Goerli
2. Click "Switch to a manual transfer"
3. Click Approve and proceed with transaction
4. Observe

Actual result: Transaction fails, error transaction failed is shown in the console

Expected result: Transaction is completed

Comments: Linking issue - https://github.com/wormhole-foundation/wormhole-connect/issues/719#issue-1772782633

Attachment:
WAVAX from Moonbase->Base Goerli
<img width="1344" alt="Screenshot 2023-08-11 at 10 10 25" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ebb8de23-7b59-42cc-8a87-6fa1bfe20713">

WFTM from Moonbase-> Base Goerli
<img width="1333" alt="Screenshot 2023-08-11 at 10 19 27" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b38caa35-821b-4e34-894e-36b4bfd449a8">

WBNB from Moonbase-> Base Goerli

<img width="1332" alt="Screenshot 2023-08-11 at 10 24 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/eba35d69-ea0f-4e71-8919-86f693899feb">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]:
Scenarios - Tested OK:
* Send 0.001 WAVAX from Moonbase (Metamask) to Base Goerli (Metamask) (Send from tx: [Moonbase](https://moonbase.moonscan.io/tx/0xecaf466e90775b4c15f62baebf8c04acb3087a9d6489c61e80a8dacd50707059), Send to tx: [Base Goerli](https://goerli.basescan.org/tx/0xa639bd9d82837266f84ddefc439f232f6feb6317846cf9907a1c2896e8d96fa9))
* Send 0.001 WFTM from Moonbase (Metamask) to Base Goerli (Metamask) (Send from tx: [Moonbase](https://moonbase.moonscan.io/tx/0x54372e361aec6253bf57738fcfee34ee34734b53d8d7bdf0f7661868d75885de), Send from tx: [Base Goerli](https://goerli.basescan.org/tx/0xa5971fb682369c6aa096eb53ae62715f21503790fb02d7b621ac497ff9308d75))
* Send 0.0001 WBNB from Moonbase (Metamask) to Base Goerli (Metamask) (Send from tx: [Moonbase](https://moonbase.moonscan.io/tx/0x0706cab276bead584f5277e9500ad7fd52954d957f338fbc4a43dcfd60848390), Send from tx: [Base Goerli](https://goerli.basescan.org/tx/0xee82b3fe3c673ec252bd590a55563bdff687a3ce70e0d567905cbd38b25b7882))
