### ISSUE TITLE
[QA] Transaction to Mumbai is not moving further than Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#822]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://base-relayer--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.3 FTM from Fantom to Mumbai
2. Select pay with one transaction
3. Open Native gas section
4. Move the slider in Native Gas section to convert some assets to native gas token
5. Click Approve and proceed with transaction
6. Observe

Attachment:
TX done on 11.08.2023 at 03:56 PM (GMT +3) Fantom-> Mumbai
https://testnet.ftmscan.com/tx/0x69f2537c537393b31b06412a92650b7712f51d0fac841cc5717d62900843f0a8

TX done on 14.08.2023 at 09:19 AM (GMT +3) Fantom -> Mumbai
https://testnet.ftmscan.com/tx/0x450638e0034ad53c40ac725c7d760b77bbec10e570124b849775177e77f1d0db

TX done on 14.08.2023 at 10:28 (GMT +3) Alfajores -> Mumbai
https://explorer.celo.org/alfajores/tx/0xfa52353668c1198de5c0ef8b3d338c6c2123c502898f1ee78aa592514c2c82b3

TX done on 14.08.2023 at 10:51 (GMT +3) BSC -> Mumbai
https://testnet.bscscan.com/tx/0x6bbec31ae6fd2e75efe37497e914155ee9f2179037f23fdc98700c6795db44ea

<img width="1336" alt="Screenshot 2023-08-14 at 09 34 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5591e88c-0e63-4612-8595-18d45ddec0a4">

<img width="1367" alt="Screenshot 2023-08-14 at 10 31 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/98d293e4-9795-4ee6-90f5-e1effc3d1a1b">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]:
* Send from tx: [FTMscan](https://testnet.ftmscan.com/tx/0xa741839c6e3d3e24f48f11ab07c96810c6d1382cfdbe4187353c9fbab2d2101b)
* Send to tx: [Polygonscan](https://mumbai.polygonscan.com/tx/0x76747e5898ef22a8be240221327903c10a3fede74968aac6c6739360d89f1202)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/95d1c8b7-5bc0-43a7-87ff-d66f688f11e2)
