### ISSUE TITLE
[QA] "MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC" when sending asset for the first time

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#824]
## Describe the current behavior in detail
 "MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC" error appears in Console when sending WGLMR from Moonbase (Metamask) to Goerli (Metamask) for the first time:
 
`
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":974614880704,"jsonrpc":"2.0","params":["0x02f8f98205076d8459682f0084625900808302b54394bc976d4b9d57e57c3ca52e1fd136c45ff7955a96872386f26fc10000b8849981509f00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000a370e7c5f7f944d451b48bc151a7bec454bc185000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4850100c001a0055aed26fcceb73dd6ea26422e23146fa3da459d88ee16bedccb6983523f4fd8a00e72e7c46fa873f88c19d68ec1ad399b53ce5d4a354265cfb6ac131e523735f1"],"method":"eth_sendRawTransaction"}}}}' 
`

Tested from https://base-relayer--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 GLMR from Moonbase (Metamask) to Goerli (Metamask)
2. Click "Approve and proceed with transaction" button

Note:
Issue is not reproducible when clicking on "Approve and proceed with transaction" button again.

![Screenshot 2023-08-14 at 14 28 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6bf1d6bd-a241-4ac0-9c58-70c32da568f0)

## What is the expected/desired behavior
An asset is successfully transferred from the first attempt.

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] when sending AVAX from Optimism (Metamask) to BSC (Metamask) for the first time. Asset is successfully transferred from the second attempt. 

Error is displayed in Console:
```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}' {code: -32603, message: `[ethjs-query] while formatting outputs from RPC '{…e":-32000,"message":"transaction underpriced"}}}'`}
{code: -32603, message: `[ethjs-query] while formatting outputs from RPC '{…e":-32000,"message":"transaction underpriced"}}}'`, stack: '{\n  "code": -32603,\n  "message": "[ethjs-query] wh…hfbeogaeaoehlefnkodbefgpgknn/common-3.js:19:37935'}
```


![Screenshot 2023-09-08 at 22 26 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/847a698a-2fca-47cb-be2e-4225bd805234)

**Comment by AigaD** [comment]
Transaction Optimis Goerli -> BSC tested OK from https://wormhole-connect.netlify.app/#
From https://wormhole-connect-mainnet.netlify.app/# will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1102 is resolved

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* https://wormhole-connect.netlify.app/ [Testnet] ([Moonbase](https://moonbase.moonscan.io/tx/0x1f9c41ae95782b3d57b664a0464bdd700b63026ec8100cb10eacb851821c464d), [Etherscan](https://goerli.etherscan.io/tx/0xfc857a786544e51700c1fffc25adcb53705bc318867d6cb0629f39c9d8ff490d))
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet] ([Optimism](https://optimistic.etherscan.io/tx/0xa3570163e0b04f231087c6c324f5febf88d7c9a4715c57ebcadd4689782eaf08), [Moonbase](https://moonscan.io/tx/0xe5665503d95f673204a527ee08db02cec40c19d304617e3d592d72e2911156b1))

Ticket is closed.
