### ISSUE TITLE
Investigate errors with no reason strings

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#828]
Originally reported in https://github.com/wormhole-foundation/wormhole-connect/issues/228

Steps:
Connect Solflare wallet in ‘From’ section
Connect [Crypto.com](http://crypto.com/) wallet in ’To’ section
Send 0.01 SOL from Solana to Mumbai
Click “Claim” button
```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x1F0F7C55E55E2F11006fC4F2E7601B1DAFCBB4bF","to":"0x377D55a7928c046E18eEbb61977e714d2a76472a","data":"0xaa4efa5b96eee13324d82a586c270d5998780b67ad2dcf1cc9f5d9d06d67ec7324e8eda5","accessList":null}, error={}, code=CALL_EXCEPTION, version=providers/5.7.2)
```

Steps:
Connect Metamask wallet through Wallet Connect in From section
Connect Spika wallet in To section
Prepare to send 0.01 MATIC from Mumbai to Aptos
Click "Approve and proceed with transaction"

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x377D55a7928c046E18eEbb61977e714d2a76472a","value":{"type":"BigNumber","hex":"0x2386f26fc10000"},"data":"0x9981509f00000000000000000000000000000000000000000000000000000000000000164e5be942eb4587f43931940a5a929268613a7586e226bdd32b097484b5ee62e8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000207a0000","accessList":null}, error={}, code=CALL_EXCEPTION, version=providers/5.7.2)
```

**Comment by tsadovska** [comment]
Tested OK:
* Send MATIC from Mumbai (MetaMask) to Aptos (Spika) on https://wormhole-connect.netlify.app/ [Testnet] (Send from tx: [PolygonScan](https://mumbai.polygonscan.com/tx/0x7eab0706a9b14113033beb9ea77bd445ff6ecca60615213a3adf5a10cb90fbff), Send to tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0xeac9093077c8e32c648b8c10c3c8681116483f4541d17268e47113447f0532c7?network=testnet))
* Send MATIC from Polygon (MetaMask) to Aptos (Spika) on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] (Send from tx: [PolygonScan](https://polygonscan.com/tx/0xf31233995352257cba7d1065610e8dbf7f6b01c3fe76c00c61a137bd73ca0172), Send to tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0xca9ffc6658ba799961c62b64a72846b4d777726cb1d6cb3903ac0fb865c8b1dd?network=mainnet))

Note: crypto.com wallet is no longer available through Wallet Connect > Desktop app. 

Ticket is closed.
