### ISSUE TITLE
[QA] Token name and wallet number overlap on “Select wallet” screen on mobile

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#83]
#### Preconditions:
* User opens https://wormhole-connect.netlify.app/
* Use device in Portrait mode

#### Steps:
1. Tap on “Select Token” 

#### Actual result:
Token name and wallet number overlap.

#### Expected result:
Token name and wallet number do not overlap.

#### Issue is reproducible on:
Samsung S20 (Android 12), Chrome Version: 110.0.5481.63

#### Issue is not reproducible on:
iPhone 11 Pro (iOS 15.6.1), Chrome Version 103.0.5060.63 

#### Attachment:
![Screenshot 2023-02-15 at 12 19 36](https://user-images.githubusercontent.com/10746654/219001922-3f976f55-98ce-4f9f-a6d0-2f8652171a9b.png)

**Comment by tsadovska** [comment]
Issue will be rechecked after #747 is resolved.

**Comment by AigaD** [comment]
Issue still reproducible.
Tested from: https://wormhole-connect.netlify.app/
Environment:  iPhone 14, iOS 16.0
Attachment:

![IMG-0106](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8a6e0aa4-a517-4ccf-872d-bc701602d790)

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect.netlify.app [Testnet]. 

![Screenshot 2024-06-10 at 14 54 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9636fa74-a644-47f8-a1a0-8eca88b2fbf4)

**Comment by tsadovska** [comment]
Closing the ticket because contract addresses are not displayed on the redesign.
