### ISSUE TITLE
[QA] Did not recieve assets that were sent to Moonbase

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#830]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://base-relayer--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.03 AVAX from Fuji to Moonbase
2. Click Approve and proceed with transaction
3. Wait until transaction in finished
4. Open https://moonbase.moonscan.io
5. Paste in your wallet number (Metamask: 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01 )
6. Search last transaction IN the wallet

Actual result: There are no incoming assets in Moonbase wallet, although transaction was completed

Expected result: Assets are received in Moonbase wallet

Attachment:
TX 0.03 AVAX from Fuji -> Moonbase
https://testnet.snowtrace.io/tx/0xdc7159e55536241be0f1ea43f9cfec76fd8185e871195720132a8f5867a867c5
TX 0.02 MATIC from Mumbai -> Moonbase
https://mumbai.polygonscan.com/tx/0x2f9503c61373199f3a6089e678227475730f814b2d2f12d74036fbf26a7d4d43

https://moonbase.moonscan.io/address/0xd493066498aCe409059fDA4c1bCD2E73D8cffE01#tokentxns

<img width="1378" alt="Screenshot 2023-08-17 at 12 18 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/36c1a240-5e11-4971-b6f6-3d0afd5232e1">
<img width="1332" alt="Screenshot 2023-08-17 at 12 18 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d6aa5ba0-ef91-4f2e-8c72-84940f920b03">

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect.netlify.app/ [Testnet].
Scenarios - Tested OK:
* Send 0.03 AVAX from Fuji to Moonbase w/o automatic deposit ([Snowtrace](https://testnet.snowtrace.io/tx/0x7c5818fab1b228fccd26a00da53306fd90aca9bf9fce652f9267ca85ba87901e), [Moonscan](https://moonbase.moonscan.io/tx/0x7157ffd50e8cd9549267d64de8d4dc3c8360a5b92a86bd7c1472f0d75a7099e2)) 
* Send 0.02 MATIC from Mumbai to Moonbase w/o automatic deposit  ([Polygonscan](https://mumbai.polygonscan.com/tx/0x18ab6205fb474bf758e58db1e2ae664454489f70f53d3c5db903c0cedc91421c), [Moonscan](https://moonbase.moonscan.io/tx/0xc79de7e67b28b54afd0bd1c02f06036e4e93ff686bef27566a6878afe598adde)) 

Following scenarios will be rechecked after #942 is resolved:
* Send 0.5 AVAX from Fuji to Moonbase with automatic deposit
* Send 0.5 MATIC from Mumbai to Moonbase with automatic deposit

**Comment by tsadovska** [comment]
Rechecked scenarios on https://wormhole-connect.netlify.app/ [Testnet]. 

Scenarios - Tested OK:
* Send 0.1 AVAX from Fuji to Moonbase with automatic deposit ([Snowtrace](https://testnet.snowtrace.io/tx/0xf5da44a61820177320934253a910218c34f9224fda62857d0f308909350482fb), [Moonscan](https://moonbase.moonscan.io/tx/0x8bceab2a3347a6589a87067994c144cbef7568f3745825950e9ca9a3349ae938))
* Send 0.01 AVAX from Fuji to Moonbase w/o automatic deposit ([Snowtrace](https://testnet.snowtrace.io/tx/0x1088d34217dd3a96eb550a61a298a197053afb6fac8290677cc05f52705078e7), [Moonscan](https://moonbase.moonscan.io/tx/0x2fde870f3244922c40a1c5c9d2e9da836dce8825f55064063e12421a42c867a8))
* Send 0.3 MATIC from Mumbai to Moonbase with automatic deposit ([Polygonscan](https://mumbai.polygonscan.com/tx/0xed320ed7898d3d7cca8957c8500c2b2b67465dcd05c700daa84163c363d94e9c), [Moonscan](https://moonbase.moonscan.io/tx/0x4b68e86d979d0baba1c611c28ae5d35adaaddcde7b4f0bff5f0f4d5509469743))
* Send 0.01 MATIC from Mumbai to Moonbase w/o automatic deposit ([Polygonscan](https://mumbai.polygonscan.com/tx/0x18a55059ed1370676c8ed232d10ecc0840e63a23159204b40055a27cced6cfc8), [Moonscan](https://moonbase.moonscan.io/tx/0x88154a0c268bd98b20b3526d35a5deae81319a3203d4a1a7d3caac240e6bd283))

Issue is no longer reproducible. Ticket is closed.
