### ISSUE TITLE
[QA] Error "invalid sender" when claiming asset

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#833]
## Describe the current behavior in detail
User is not able to claim WETH on Fuji when sending ETH from Goerli (Metamask) to Fuji (Metamask).

Tested from https://wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallets in 'From' and 'To' sections
2. Prepare to send 0.0001 ETH from Goerli to Fuji
3. Select "Pay with 2 transactions" in "Gas payment" section
3. Click "Claim" button on Redeem screen

Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x46807e3540865613aa8094dbf46b87679445e9b139f2101aab0e12fd1eafab8c)

Error in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid sender" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e696e76616c69642073656e646572000000000000000000000000000000000000", errorArgs=["invalid sender"], errorName="Error", errorSignature="Error(string)", reason="invalid sender", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at Object.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6b9f4ddd-3e81-48b3-b6ea-1d56dded552e)

## What is the expected/desired behavior
User can successfully claim WETH on Fuji.

**Comment by AigaD** [comment]
Closing, Tested OK.
Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/# and https://wormhole-connect.netlify.app/
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9685172e-cafd-421b-9b1d-75e2578dbc59
