### ISSUE TITLE
[QA] [Pontem] Cannot send Aptos assets

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#834]
Preconditions:
1. Pontem wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://base-relayer--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.02 APT from Aptos to Fuji
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Error: Waiting for transaction 0xb22da1691ed535250cba9673944a421d26e94964ae9bcc28437c3971ffc6521c failed`

Expected result: Transaction is moved to next screen with 3 steps and is completed

Attachment:

<img width="1337" alt="Screenshot 2023-08-17 at 16 16 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a9fa786f-b006-4636-8172-80150cf9e41d">
<img width="1358" alt="Screenshot 2023-08-17 at 16 29 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b38d76dc-aecf-4c27-bd16-d170d44e0a6b">

**Comment by tsadovska** [comment]
Issue will be rechecked after #946 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* https://wormhole-connect.netlify.app/ [Testnet]. Scenario "Send 0.1 APT from Aptos (Pontem) to Goerli (Metamask)": [Aptos explorer](https://explorer.aptoslabs.com/txn/0x3afa12f2ab073369f6f00257eb924bbbb149f9d620af056dae782ac757fbcae2?network=testnet), [Etherscan](https://goerli.etherscan.io/tx/0xfe20736cca4b5d708d4b4b578a8df050fdc79a221cfe0218eb6ab2ed00612eda)
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Scenario "Send 0.00001 WBNB from Aptos (Pontem) to Fantom (Metamask)": [Aptos explorer](https://explorer.aptoslabs.com/txn/0x783e6b4e29fb0c697751c40168811e5b27ac917fcb41ea0d61956ddcb5f951ad), [FTMScan](https://ftmscan.com/tx/0xfa9c7b1aee4399623543533fbd9700c1f62ee004ad3d05d801dc2c7e75adbb13)

Ticket is closed.
