### ISSUE TITLE
[QA] Balance is not loaded after rejecting the transaction and then clicking the "Terms of Use" link

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#840]
## Describe the current behavior in detail
Balance is not loaded after rejecting the transaction and then clicking the "Terms of Use" link. 

Tested from https://wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 116.0.5845.96 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallets in "From" and "To" sections
2. Prepare to send 0.1 AVAX from Fuji to Fantom
3. Click "Approve and proceed with transaction" button
4. Click Cancel button on Metamask notification to switch network
5.  Click "Terms of Use" link
6. Click Back button to return to Bridge screen
7. Select Fuji network in '"From" section
8. Open Assets list
9. Observe if Balance is loaded

Errors are displayed in Console:
```
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at E.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```

```
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="wrappedAsset(uint16,bytes32)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (index.ts:269:28)
    at l.throwError (index.ts:281:20)
    at A.decodeFunctionResult (interface.ts:427:23)
    at E.<anonymous> (index.ts:400:44)
    at Generator.next (<anonymous>)
    at i (hashes.ts:1:25)
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ccc335a4-137e-4a09-a9c6-5379dfa917bd

![Screenshot 2023-08-23 at 11 45 26](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0e2a8ee1-0e6a-40d6-83d1-6665aade0aa4)
![Screenshot 2023-08-23 at 11 14 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c925f236-1d40-4d3c-ad0a-c91c8b177593)

## What is the expected/desired behavior
Balance is loaded.

**Comment by tsadovska** [comment]
Issue is reproducible on:
- https://wormhole-connect.netlify.app/ [Testnet]
- https://base-relayer--wormhole-connect.netlify.app/ [Testnet]
- https://mainnet--wormhole-connect.netlify.app/ [Mainnet]

**Comment by AigaD** [comment]
Closing as issue is no longer reproduced.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0c6dfc35-1cda-48be-941e-546bb3f40233


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6528458b-2b6e-4c4a-ba1a-73633ec0a4a9
