### ISSUE TITLE
[QA] Search window for All Tokens does not work

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#844]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/ - Tested NOK
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Select Network (e.g. Fantom)
2. Click on Assets
3. Select All tokens
4. Click in Search window
5. Start typing in Asset name
6. Observe

Actual result: Assets are not filtered out by what is entered in search window

Expected result: Assets are filtered out by what is entered in search window

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/33366104-b38d-47fe-a7d9-d05aec6de1db

**Comment by M-Picco** [comment]
For the record: https://github.com/XLabs/portal-bridge-ui/issues/359

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#

**Comment by tsadovska** [comment]
Issue is reproducible on:
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

**Comment by AigaD** [comment]
Reproducible from: https://deploy-preview-1174--wormhole-connect.netlify.app/# and https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/#

Search option in All tokens tab is not working
Attachement:
![Screenshot 2023-11-16 at 12 55 26](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7c300cb0-926f-403d-bb86-193dc65bed5b)

**Comment by AigaD** [comment]
Issue is reproduced from: https://preview.portalbridge.com/df5df83982/
Search option in All tokens tab is not functioning
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8c588b44-aea8-409c-b2d7-8bb4afa2cf7f

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
All tokens section search function is not working
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/80162734-2e09-4a1b-bf99-29c8795d0cfd

**Comment by tsadovska** [comment]
Issue is also reproducible when searching by contract address. Checked on https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Search for USDC (Polygon) on Polygon. Contract address: 0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359.


![Screenshot 2024-03-21 at 19 08 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4bd1e4d6-8f93-430b-85ca-0a52f6e08dad)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/ac15114854/ [Mainnet] with osETH asset (contract address: 0xf7d4e7273E5015C96728A6b02f31C505eE184603)

![Screenshot 2024-06-04 at 13 54 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/740f8884-a671-4345-a46f-59dd5311d4ce)

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
All tokens section search function is not working for all tokens. 

Attachment: 
<img width="1411" alt="Screenshot 2024-08-26 at 11 53 00" src="https://github.com/user-attachments/assets/c40cde97-21b2-4cd3-bb05-97d681e3856e">

**Comment by tsadovska** [comment]
"All tokens" tab is no longer available after redesign. 
Ticket is closed.
