### ISSUE TITLE
[QA] Gas payment options are not shown

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#845]
## Describe the current behavior in detail
Gas payment options are not shown for transaction to and from Osmosis.

Builds - Tested NOK:
https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet]

Checked on macOS Monterey 12.6.7 with Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallet in "From" section
2. Connect Leap wallet in "To" section
3. Prepare to send 0.1 USDC from Goerli to Osmosis
4. Observe "Gas payment"

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b2e1fc21-905e-4f89-87a7-08617a351f8b

![Screenshot 2023-08-24 at 09 54 03](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88500da5-6b5c-4930-ae18-25619f0a6cb8)

## What is the expected/desired behavior
Gas payment options are shown.

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd62ceb8-dcca-4427-af2f-76554d059df4

**Comment by AigaD** [comment]
Closing. For Cosmos gateway route, there is no native gas mechanism. This is expected behaviour.

<img width="773" alt="Screenshot 2023-10-11 at 09 21 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/21afaf52-5785-4b49-b4b4-bd7efd070620">
