### ISSUE TITLE
[QA] Incorrect balance is shown in "All tokens" tab

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#846]
## Describe the current behavior in detail
Incorrect balance (10 instead of 0) is shown for ETH, MATIC, BNB, AVAX, FTM, GLMR, SOL, ETH (Base Goerli) assets in "All tokens" tab when Osmosis network is selected and Leap wallet is connected.

Builds: 
https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] - Tested NOK
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] - Tested OK 

Checked on macOS Monterey 12.6.7 with Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Connect Osmosis network in "From" section
2. Connect Leap wallet
3. Open Asset list
4. Open "All tokens" tab
5. Observe balance for ETH, MATIC, BNB, AVAX, FTM, GLMR, SOL, ETH (Base Goerli)

![Screenshot 2023-08-24 at 10 12 40](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c584784d-f7d4-4348-9a05-bc7493795dc5)

![Screenshot 2023-08-24 at 10 13 21](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eec73cc7-f3f1-40eb-964e-3d64ee083e68)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4e916941-9c72-4c06-beda-b83a522924b3)

## What is the expected/desired behavior
Correct balance is shown.

**Comment by AigaD** [comment]
USDC balance is shown in All Tokens tab but not in Available tokens tab for Osmosis Network.
Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8a257099-115d-4308-adb2-75952c4ed90c

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Balance for assets in All tokens tab is no longer showing as 10, where in reality, there is no available balance for selected token.

![Screenshot 2023-10-11 at 09 40 01](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aea145f0-b899-45ed-868e-f5f8d772dd6b)

But USDC asset still shows some available balance in All tokens tab, but not in Available tokens tab


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3bc7c604-cce5-4b65-9931-2644c404f539

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1111 is resolved.

**Comment by tsadovska** [comment]
Closing, because Osmosis network is not displayed in list of networks on https://wormhole-connect.netlify.app/ [Testnet].
