### ISSUE TITLE
[QA] Link to Osmosis transaction scan is missing 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#848]
## Describe the current behavior in detail
Link to Osmosis transaction scan is not displayed in "Send to" section on Redeem screen when sending USDC (in my case 0.01) from Goerli (Metamask) to Osmosis (Leap).

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version  116.0.5845.110 (Official Build) (x86_64).

Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x67655f1fcdc497831e9a780127ab49c0a0aa66d564622e707aa4354cde6758a6)

Steps
1. Connect Metamask wallet in "From" section
2. Connect Leap wallet in "To" section
3. Send 0.01 USDC from Goerli to Osmosis
4. Observe if link to transaction scan is displayed.

![Screenshot 2023-08-24 at 11 00 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4388b0d9-eeab-4cb4-a51d-0b6a9bb5ec60)

## What is the expected/desired behavior
Link to transaction scan is shown.

**Comment by AigaD** [comment]
Reproduced also from https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/
Link to Osmosis transaction scan is not shown when the transaction is finished.
Attachment:
<img width="1360" alt="Screenshot 2023-08-25 at 09 03 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9721d549-c82a-4a5f-a1d2-d1a4ae06a915">

**Comment by M-Picco** [comment]
Also see: https://github.com/XLabs/portal-bridge-ui/issues/360

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Link to Osmosis explorer missing at the end of transaction

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet]. Link to Osmosis scan is not displayed when sending 0.01 USDC from Ethereum (Metamask) to Osmosis (Leap). Send from tx: [Etherscan](https://etherscan.io/tx/0x7f8e3c36a1bbca079874d253ac66b68cdaaf4afaf8012f8a113b8ca3308550ad)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 USDC from Goerli (Metamask) to Osmosis (Leap). 

Issue will be rechecked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] after #1042 is resolved.

**Comment by tsadovska** [comment]
Issue will be rechecked after #1047 is resolved.

**Comment by tsadovska** [comment]
Issue will be rechecked after #1147 is resolved.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. AVAX transfer from Avalanche (MetaMask) to Osmosis (Leap) was completed successfully. Link to Explorer is displayed in "Send to" section. 
* Send from tx: [Avascan](https://avascan.info/blockchain/c/tx/0xfe178f6fb1de668d6a4ef29beff3adb9d61d53d71b6d547fe2ae5a93ebce821c)
* Send to tx: [MintScan](https://www.mintscan.io/osmosis/transactions/6861CC7DFA58FECD4423E7946D839361B0AF7F203691569F9938FFBE2E3B7B44)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xfe178f6fb1de668d6a4ef29beff3adb9d61d53d71b6d547fe2ae5a93ebce821c)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/86df9d02-5c79-40c2-a2f9-59e2fe95ce79)

Remaining issue on https://wormhole-connect.netlify.app/ [Testnet]: https://github.com/wormhole-foundation/wormhole-connect/issues/1147 

Ticket is closed.
