### ISSUE TITLE
[QA] Various tokens are not present in the Asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#849]
Preconditions:
Keplr Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/ - Tested NOK
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Select Osmosis network
2. Open Asset list
3. Observe if OSMO token is present

Actual result: OSMO token is not shown for the Osmosis Network

Expected result: OSMO token is shown in the asset list

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c0e9d92-f729-417b-93ef-dc2eb72ec435

**Comment by tsadovska** [comment]
USDT, WBTC, DAI, stETH, tBTC assets are present in Metamask wallet and are not present in Asset list.
Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]. 

Steps:
1. Connect Metamask wallet
2. Select Goerli network
3. Open Asset list -> "All tokens" tab
4. Observe if USDT, WBTC, DAI, wsETH, tBTC tokens are shown

![Screenshot 2023-08-24 at 11 25 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1de04fbf-2a0d-4ae6-ac46-bfe915ee3010)

**Comment by tonyjin** [comment]
@M-Picco to double check testnet asset config.

**Comment by AigaD** [comment]
Sei asset also is not showing in the asset list.
Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/60898505-8a69-4e0f-ba23-fe51015eca6b

**Comment by tonyjin** [comment]
Removing P0 as Sei is not supported in Connect yet.

**Comment by tsadovska** [comment]
USDC Ethereum asset is not shown in "Available tokens" list for Osmosis network. Checked on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet].

Steps:
1. Click Swap button (actual result: Osmosis network is in From section)
2. Select Leap wallet
3. Open Assets list

![Screenshot 2023-09-06 at 18 44 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3e284b15-5327-46ac-a130-207e9c49e14d)

![Screenshot 2023-09-06 at 18 45 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b5e6a2be-8d49-4ecc-b36d-b3f4e75ec5fa)

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet].
ARB and OP assets are present in Metamask wallet and are not shown in Assets list. 

![Screenshot 2023-09-07 at 14 55 53](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5b28b517-500a-457c-ac92-4b3e263fe703)

![Screenshot 2023-09-07 at 14 58 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fcd60363-6bd9-46d0-b4f7-9e4c529bca10)

**Comment by AigaD** [comment]
Also SEI / Osmo asset is not present in the asset list.
Tested from: https://cctp-testnet--wormhole-connect.netlify.app/ / https://cctp--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ddf6f3b4-d50e-4f91-b9b5-e2b0fb41c74d

**Comment by tsadovska** [comment]
Sent 1 USDC (Solana) from Solana (Phantom) to BSC (Metamask). Asset is received in Metamask wallet, but is not shown in wormhole-connect.
* Send from tx: [Solana explorer](https://explorer.solana.com/tx/2mUwT9QGf9ekUcaMw8G3WR2uDSCVArgp1UYoh43ZiWw8f4t4AKJk22TyMLSK2pkQmteg1w34SYZPhq7n5GRYVc9v?cluster=devnet)
* Send to tx: [BscScan](https://testnet.bscscan.com/tx/0xb6ff565c713cca9b8719c98bdd63a4e38abe2cf98d2cf5adf25b411673fa3407)

Wallets:
- Metamask: 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185
- Phantom: 7yEFBzgwqBHmEtPLvKcQgzPTpfcnrScAfrvenvnBJA5n


![Screenshot 2023-09-18 at 10 13 44](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a529cf50-329c-4f87-9d36-6b47b2c0dae0)

**Comment by AigaD** [comment]
This is reproducible.
Tested from: https://wormhole-connect-mainnet.netlify.app/
tBTC asset is not showing in Available tokens tab although there is balance in the wallet (For Arbitrum Network), also ARB, OP and OSMO assets are not shown

Attachment:
![Screenshot 2023-10-11 at 10 25 59](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/70f06d37-883a-4788-bc54-2dc293c62cf1)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
ATOM token for Cosmoshub Network are not shown in the asset list
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6a98c5c7-6f3f-4078-9727-a1b01f8238e9

**Comment by AigaD** [comment]
OSMO/ ARB/ EVMOS/OP/KUJI asset is not available from https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/
Attachment:
![Screenshot 2023-12-22 at 12 12 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/34eb4e3a-17ac-4066-906b-455ddfee0180)
![Screenshot 2023-12-22 at 12 12 12](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/328d8e25-c70d-4a6a-839a-02f86406a0c5)

**Comment by aadam-10** [comment]
cosmos gas tokens like OSMO are not supported by Gateway at all, and tokens that are not configured in Connect such as ARB won't show up. this is expected operation
