### ISSUE TITLE
[QA] User stays on Bridge screen until confirmations are loaded for Step 1

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#850]
Preconditions:
Metamask Wallet is connected at sending from section
Keplr Wallet is connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/ 

Steps:
1. Prepare to send 0.001 ETH from Goerli to Osmosis
2. Click Approve and proceed with transaction
3. Observe

Actual result: User is not taken to next, transaction, screen, instead loading is shown for more than 15min on the same Bridge screen. When Step 1 is at waiting for wormhole consensus on transaction screen then user is taken to the next screen and transaction is finished

Expected result: User is taken to next screen with three steps, with confirmations loading for Step 1

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e73cfe04-6b46-4116-ada1-e676b765897c

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] when:
* sending 0.1 USDT from Ethereum (Metamask) to Osmosis (Leap)
* sending 0.0001 tBTC from Ethereum (Metamask) to Osmosis (Keplr).

Actual result:
- Transaction is displayed as successful in Metamask wallet but Redeem screen doesn't open in wormhole-connect. 
- Transaction can't be found with Menu -> Resume transaction until confirmations are loaded for Step 1. 
- After confirmations are complete in Step 1, Redeem screen is displayed and transaction is successfully completed. 

Attachments:
* USDT transfer from Ethereum to Osmosis

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f6652be8-233c-4522-9753-af6d4fef3a86

* tBTC transfer from Ethereum to Osmosis 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88926ccf-1b65-4a80-9f94-54ce67a9def5

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when sending 0.0001 ETH from Ethereum (Metamask) to Osmosis (Leap wallet). Transaction is displayed as successful in Metamask wallet but Redeem screen doesn't open. 

Send from tx: [Etherscan](https://etherscan.io/tx/0x00045ce965ec760e0bab44436148fb2745bef545b2c85de97a284550dd2b54e5)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/63c5cd27-06ec-41ff-963b-4642ee020679

**Comment by M-Picco** [comment]
For the record: https://github.com/XLabs/portal-bridge-ui/issues/357

**Comment by AigaD** [comment]
Closing the ticket, as this is no longer reproducible.

Attachment:
https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ff55b179-2a1b-4602-ac2a-bca2b9305fbd
