### ISSUE TITLE
[QA] Cannot register asset for Osmosis transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#851]
Preconditions:
Sui Wallet is connected at sending from section
Keplr Wallet is connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.02 SUI from Sui to Osmosis
2. Observe that token needs to be registered
3. Click on Register
4. Observe that https://wormhole-foundation.github.io/example-token-bridge-ui/#/register is opened
5. Select Sui as source and SUI as asset
6. Connect wallet
7. Open Target asset list
8. Search for Osmosis
9. Observe

Actual result: Osmosis Network is not present in the list, token cannot be registered

Expected result: Osmosis asset is shown in the list and token can be registered

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/66e570e1-4af7-415b-bb02-fcb1285007f6

**Comment by tonyjin** [comment]
@nik-suri to attest SUI on testnet.

**Comment by nik-suri** [comment]
SUI has been attested to Gateway testnet. Testnet Tx hash on Gateway: 257AFCEBCB0A43D60045EB95B1F16FB1640822339C45E53BCAAE67E455DD753D

**Comment by tsadovska** [comment]
The same issue occurs when sending tBTC from Goerli to Osmosis via https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]. Unable to register asset for transaction because Osmosis network is not present in the list at https://wormhole-foundation.github.io/example-token-bridge-ui/#/register.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a781d328-28bf-4828-bc4f-9376b38abb58)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/225c732b-5ca5-421f-a0a7-3073e33f79d5)

**Comment by AigaD** [comment]
Also cannot register asset for transaction ETH Base Goerli -> Osmosis, 
Tested from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:
<img width="754" alt="Screenshot 2023-08-28 at 16 29 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b7b2dd90-eb7b-4e81-a934-b1ded1868ba9">

<img width="1237" alt="Screenshot 2023-08-28 at 16 30 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/64226011-25af-4029-a8e7-43834fe4ec2a">

**Comment by tsadovska** [comment]
Also reproducible on https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] when sending WETH (Base) from Ethereum (Metamask) to Osmosis (Leap wallet). Warning message is displayed "This token is not registered, you must [register](https://www.portalbridge.com/#/register) it before you continue. Newly registered tokens will not have liquid markets.", but Osmosis network is not present in https://www.portalbridge.com/#/register.

**Comment by tonyjin** [comment]
All mainnet tokens in https://github.com/wormhole-foundation/wormhole-connect/blob/feat/cosmos-gateways/wormhole-connect/src/config/mainnet.ts#L151 should now be attested.

It's possible we haven't attested the full set of supported assets on testnet yet.

**Comment by AigaD** [comment]
User is now able to send WETH (Base) from Ethereum to Osmosis from https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/#
Attachment:
<img width="1259" alt="Screenshot 2023-08-30 at 10 40 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bbccadaa-2e7b-4b0d-802c-26482e30b48c">

On testnet it is still not possible to register asset for transaction ETH Base Goerli -> Osmosis or wstETH Goerli -> Osmosis, so will leave this ticket open.

Attachment:

<img width="1258" alt="Screenshot 2023-08-30 at 10 35 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91350e1e-82e7-478c-bac5-d69ddc79c124">

**Comment by tonyjin** [comment]
Downgrading from P0 -> P1 since mainnet assets are all attested, and we're just missing a few on testnet.

**Comment by tsadovska** [comment]
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending WBTC, USDT, DAI, wstETH from Goerli (Metamask) to Osmosis (Leap).

**Comment by AigaD** [comment]
Cannot register asset for transaction ETH Base->Osmosis
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/# and https://www.portalbridge.com/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8360b947-6126-448d-96ca-8bab91e9a58e

**Comment by AigaD** [comment]
Reproducible from: https://wormhole-connect.netlify.app/#
Cannot register tokens for transaction to Osmosis.
Attachment:
![Screenshot 2023-10-10 at 16 45 45](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f82eaf73-36f3-47c8-8817-6444b1727f72)

**Comment by AigaD** [comment]
Cannot register USDC asset for transaction from Osmosis to Avalanche, as the Osmosis network is not present in the network list from: https://portalbridge.com/advanced-tools/#/register
Tested from: https://preview.portalbridge.com/7102d8ccad/
Attachment:
<img width="1148" alt="Screenshot 2023-12-18 at 15 51 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/09586812-3c47-47ba-b4b5-b96e625d0f2a">
<img width="1267" alt="Screenshot 2023-12-18 at 15 50 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91ac40e6-8498-4c04-b845-76129ad6c357">

**Comment by AigaD** [comment]
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1111 is solved

**Comment by tsadovska** [comment]
Created ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1734 for remaining issues.
Scenarios on mainnet are no longer reproducible. 
Ticket is closed.
