### ISSUE TITLE
[QA] [Osmosis] "Source chain gas estimate" value is not calculated

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#852]
## Describe the current behavior in detail
"Source chain gas estimate" is not calculated when sending USDC from Osmosis (Leap) to Goerli (Metamask).

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Connect Leap wallet in "From" section
2. Connect Metamask wallet in "To" section
3. Prepare to send 0.001 USDC from Osmosis to Goerli
4. Observe "Source chain gas estimate" value in Preview section

![Screenshot 2023-08-24 at 14 33 16](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/64576025-5a01-4fd8-9afb-e08fce03ea7d)

## What is the expected/desired behavior
"Source chain gas estimate" value is calculated.

**Comment by M-Picco** [comment]
See also https://github.com/XLabs/portal-bridge-ui/issues/361

**Comment by tsadovska** [comment]
Issue is also reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] when sending 0.1 USDC from Osmosis (Leap wallet) to Optimism (Metamask wallet). 

![Screenshot 2023-09-08 at 23 14 46](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/09de4c88-958e-4746-a1f1-949a2b03a5f4)

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet] when sending 0.01 WETH (Goerli) from Osmosis (Leap) to Arbitrum Goerli (Metamask).

**Comment by AigaD** [comment]
Issue is reproducible: https://deploy-preview-1015--wormhole-connect.netlify.app/# when sending 0.01 MATIC from Mumbai to Osmosis
Attachment:
<img width="1099" alt="Screenshot 2023-09-21 at 15 51 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/674b3ad3-e5b5-4769-a578-ca39c0660a3c">

**Comment by AigaD** [comment]
This is reproducible, Source chain gas estimates are shown as 0 OSMO
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
![Screenshot 2023-10-11 at 11 05 32](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3f517096-0e8b-40eb-a273-f09f70392d8a)
![Screenshot 2023-10-11 at 11 04 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/91219f99-1f9e-416e-a48f-a90be5b21df3)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1111 is resolved.

**Comment by tsadovska** [comment]
Osmosis network is no longer displayed on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D).
Source chain gas estimate is displayed as ~ 0 OSMO on https://portalbridge.com/. 

Ticket is closed.
