### ISSUE TITLE
[QA] [Improvement] Assets should be written instead of Tokens when opening asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#853]
Preconditions:
Coin98 Wallet is connected at sending from section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/ 
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/

Steps:
1. Select Osmosis Network
2. Click on Assets
3. Observe the naming for Available and All tokens

Improvement: Use the same naming Assets for Available _Assets_, All _Assets_ instead of Available _Tokens_, All _Tokens_

Attachment:
<img width="539" alt="Screenshot 2023-08-24 at 15 31 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0646ded2-fe9e-4ce3-b5ae-317bbac954fe">
<img width="584" alt="Screenshot 2023-08-24 at 15 31 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c968bce-ec2b-4efd-a7db-1143cbabd076">

**Comment by tsadovska** [comment]
Closing as expected behaviour based on WH Connect Redesign Q2 2024:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a8940f14-0ff4-4542-88f5-66261393a4d4)
