### ISSUE TITLE
[QA] [Mainnet] Coin98 wallet is opened when user selects Metamask in Connect Wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#855]
Preconditions:
1. Coin98 Wallet extension is enabled
2. Metamask extension is enabled
3. Wallets are not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/

Steps:
1. Click on Connect Wallet
2. Search for Metamask and click on it
3. Observe which wallet is opened

Actual result: Coin98 wallet pop-up to sign in is opened instead of Metamask

Expected result: Metamask sign in pop-up is opened

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49e5092d-8afd-484e-a313-2535a968e441

**Comment by tsadovska** [comment]
Duplicate #708
