### ISSUE TITLE
[QA] [Mainnet] Network stays connected when returning from resume transfer screen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#859]
Preconditions: Networks, wallets are not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/

Steps:
1. Click on Menu and select Resume transfer
2. Paste in TX hash (e.g 85720AD3225ED17FC9DB60D828FCB33B0C8989F366E0898235C34240054AB1B0 https://www.mintscan.io/osmosis/transactions/85720AD3225ED17FC9DB60D828FCB33B0C8989F366E0898235C34240054AB1B0 )
3. Click on Select Network and select Osmosis from the list
4. Click Search
5. Connect Wallet select Metamask (know issue - #858 )
6. Go back to Bridge screen
7. Observe

Actual result: Ethereum network is left connected when returning to Bridge screen

Expected result: Networks should be disconnected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/470d72ac-a330-4a9b-9aab-27805a88333c

**Comment by AigaD** [comment]
Reproduced from: https://cctp-only--wormhole-connect.netlify.app/# and https://latest--wormhole-connect.netlify.app/#
Network for the transaction that was searched at Resume Transaction is left connected when returning to Bridge screen.
TX - https://optimistic.etherscan.io/tx/0xe40d4f53a0450c85245a0cdb6ad5db2cddffd6ee8910aa043aa30b52ebf5329b (From Avalanche to Optimism)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4090c057-eff7-494c-b44b-f6a3064d8a78

**Comment by AigaD** [comment]
Issue is also reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8fdf0a9d-f085-4cf8-9df5-0d52bb3beae0

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#

**Comment by AigaD** [comment]
Issue is also reproducible from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/

**Comment by AigaD** [comment]
This is reproducible from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/

**Comment by AigaD** [comment]
Reproducible from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Network stays connected after returning from Resume transaction screen
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/62a9d4a1-9fd7-46a0-9afd-cb96641e3f48

**Comment by AigaD** [comment]
This is reproducible from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
Network at destination chain is connected when returning from Resume Transaction screen.
Transaction hash for Arbitrum - 0x7c4c3e6013db3579c930321bba984f87e0419cfa6849e6301410e0dd2fe8e20b
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d5e15d4a-9743-4bba-9709-41bd07a98a70

**Comment by tsadovska** [comment]
Issue is also reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Network remains selected and wallets remain connected when returning from Redeem screen. 

Steps:
1. Open Menu -> Resume transaction screen
2. Search for `2bz6abQQUuekSXYDvy9FxBpmNp3szoDPKVnmb7szJ57EjSkruNE6x9H7bkQoWn5sxB1NPt4wU5jiMem28Ke9aHgq` hash in Solana network
3. Click "Bridge more assets" button

**Comment by AigaD** [comment]
This is reproducible from: https://deploy-preview-1174--wormhole-connect.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/31024eb0-6b9b-45a0-a169-e6ad2bcf892b

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/
Network at sending To section is connected when returning fromResume Transaction screen.
TX hash Optimism: 0x2aae578034f1003276b0a6fb2fa8a53456ec3cd8bbba08da8d8c8d5a1510eb8c
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f7a697ed-4777-43fd-9435-828953e14d5b

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/
TX 0xf8ff42095547cfb89ce5d7893914a301b1cbc33df9402d939ec4f67ae00cbc97 from Ethereum to Sui

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/af258626-7611-4058-8e0c-ee95998ce3bf

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/
TX from Celo to Solana - 0x76ba62bd827402d2fe4c5b450f387a368c3430286797ffb15cf63fdbae552172
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/81d2716e-7f9f-4ecc-b836-c5cf67e22174

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/#
Network is connected when returning from resume transaction screen
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e73f8cae-8dc2-4f51-9fbc-fa4c27ce17be

**Comment by tsadovska** [comment]
Rechecked scenarios mentioned in the ticket, issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 

https://github.com/user-attachments/assets/3cd064c8-f2e7-4ce6-a043-c779cf650480

Closing the ticket.
