### ISSUE TITLE
[QA] Sei wallet is connected when Cosmos wallet is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#860]
## Describe the current behavior in detail
"Leap for Sei" wallet is connected instead of "Leap for Cosmos" wallet.

Checked from https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] with macOS Monterey 12.6.7 and Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Click "Connect wallet" button
2. Search for "Leap" wallet
3. Select "Leap for Cosmos" wallet
4. Observe wallet address

Note:
Issue is not reproducible when Osmosis network is connected first.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/647bd445-bc6d-402c-b55f-df6d5cc0ca6e

## What is the expected/desired behavior
Correct wallet is connected.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] and https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when "Compass for Cosmos" wallet is selected. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/922478a8-36f6-46b5-802c-16d0f6cdd103

**Comment by AigaD** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/954 is solved

**Comment by AigaD** [comment]
Tested NOK from https://wormhole-connect.netlify.app/

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/803f2a1f-802d-4729-b61b-9bb05fabf530


Issue on Mainnet https://wormhole-connect-mainnet.netlify.app/ will be rechecked when https://github.com/wormhole-foundation/wormhole-connect/issues/1119 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Ticket is closed.
