### ISSUE TITLE
[QA] Link to transaction scan is not displayed in "Send to" section when transaction is resumed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#865]
## Describe the current behavior in detail
Link to the transaction scan is not displayed in "Send to" section when searching for Osmosis transaction on "Resume transaction" screen.

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/  [Testnet] with macOS Monterey 12.6.7 and Chrome Version 116.0.5845.110 (Official Build) (x86_64). 

Steps:
1. Open Menu -> Resume transaction screen
2. Select Osmosis network
3. Search for transaction hash `82E203462B9666275EDD1EFE373E8917CFFFA2778CDD0EBCEBA2DD1F701D20F0`
4. Observe if link to the transaction scan is displayed in "Send to" section

Issue is reproducible when:
* Searching for transaction hash `82E203462B9666275EDD1EFE373E8917CFFFA2778CDD0EBCEBA2DD1F701D20F0` (Osmosis). Scenario: Send 0.01 WETH from Osmosis to Goerli.
* Searching for transaction hash `0074F9BF84107F4670D2214802909EE1C72774B9FC50CF2A95CE121E73659DEC` (Osmosis). Scenario: Send 0.01 WETH from Osmosis to Mumbai.
* Searching for transaction hash `2AC7D5EFEC017B1F2E79DAA218392E4F7A95A63BC30FB24E6F06EBC455E1A6AA` (Osmosis). Scenario: Send 0.01 WETH from Osmosis to BSC.

![Screenshot 2023-08-28 at 11 53 39](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/07f41c1e-08dc-4828-941c-1c830a71c54a)

## What is the expected/desired behavior
Link to transaction scan is displayed.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet].
Send from tx: [MintScan](https://www.mintscan.io/osmosis/transactions/0EE649F969674F76A5355E41415BF37A7E6613962D14446AA992D6558DBA80C0)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3e02c425-7134-4ae8-a94a-1ca882dd98f4

**Comment by tsadovska** [comment]
Issue is also reproducible on:

- https://cctp--wormhole-connect.netlify.app/ [Mainnet] when resuming BSC transaction (WBNB transfer from BSC to Arbitrum, Send from tx: [BscScan](https://bscscan.com/tx/0xac821af7bba8f68b8093442ce0332ac8733cf4bf7f6051ae56073d27736dbbf0))

- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet] when resuming Goerli transaction (USDC transfer from Goerli to Fuji, Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x413058e30902610909f9109e53ceb2853cd6208509cc1c423be06b35e356b38a))

Explorer link is no longer displayed in "Send to" section after transaction is resumed through Menu -> "Resume transaction".

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]. Explorer link is no longer displayed in "Send to" section after transaction is resumed through Menu -> "Resume transaction".

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet]. Explorer link is not displayed in "Send to" section when searching for tx hash `0x5e795c7f09cddb0d412192061ad2e875061dc41907a459c185e03550b339921b` in Ethereum network. 
* Send from tx: [Ethereum](https://etherscan.io/tx/0x5e795c7f09cddb0d412192061ad2e875061dc41907a459c185e03550b339921b)
* Send to tx: [Avalanche](https://snowtrace.io/tx/0xdf43e23cfdcd67036bb7c17beb6424d928904c0bbe36384e25b232787e067d81)


![Screenshot 2023-09-20 at 10 24 06](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8b9f626f-6b3f-4d34-a137-0fc47348b6b9)

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1014--wormhole-connect.netlify.app/
Explorer link at Sent To section is no longer displayed at Resume transfer screen

**Comment by AigaD** [comment]
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#

Steps:
1. Copy TX hash (C126577136816D58DE622E20F80E3F28D3C890813738EA244CA83E226ECDB049 )
2. Click on Menu and select Resume Transaction
3. Paste in the search window the TX hash
4. Select Osmosis Network
5. Click Search
6. Observe

Actual result: Explorer link for destination chain is no longer shown

Expected result: Explorer link for destination chain is shown

Attachment:
Bridge screen:

<img width="1082" alt="Screenshot 2023-09-27 at 11 48 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e5656b2e-c82d-45e6-b512-c8d3e4c52648">


Resume screen:

<img width="1214" alt="Screenshot 2023-09-27 at 11 33 41" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/48134f9e-b1f1-4852-a010-983a93ff7df8">

**Comment by AigaD** [comment]
Issue is reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
For transaction Sui -> Solana explorer link is no longer shown if the transaction is resumed.
Attachment:
<img width="1068" alt="Screenshot 2023-10-04 at 10 54 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/12e13beb-ddf3-4b3c-b387-945b8d688270">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Link to Moonscan is not displayed after transaction is resumed. 

Sent 0.001 WGLMR from Fantom (Metamask) to Moonbase (Metamask):
* Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0x6e1a3c1ca6664c1d675f900ff5c4eee9daf0fdc96e8cbccb2971306af27de231)
* Send to tx: [Moonscan](https://moonbase.moonscan.io/tx/0x549cc0cc89d5c7037c0a4fbcc6145b3541277356628f7bdf4b6a56965ac399d7)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet]. Link to Basescan is not displayed after transaction is resumed.

Sent 0.1 USDC from Avalanche (Metamask) to Base (Metamask):
* Send from tx: [Snowtrace](https://snowtrace.io/tx/0xb6157c0f94db993e817bd4222d85d3f7d6539dc464639d6f4f3c81b9f02caa5b)
* Senf to tx: [Basescan](https://basescan.org/tx/0xe2860152f65cd750c34b540017e0e2ce7c2402b7308c7a0911a020609812a595)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7d9e941c-3af6-4d06-bbf2-79df27647960

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Link to FTMScan is not displayed after transaction is resumed. 
* Send from tx: [Moonscan](https://moonscan.io/tx/0x2fa6b629edfa08abd28f6c11fd83c83c47127d157a33da01ddf76b6caa52b6b1) 
* Send to tx: [FTMScan](https://ftmscan.com/tx/0x72992ae0dc6585aae13eb24f0ef3052a0a20fa0c8a3c806a86ae0d81092f66b9)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Link to Polygonscan is not displayed after transaction is resumed. 

* Send from tx: [Etherscan](https://etherscan.io/tx/0xfe7275a766ebb2ebf4ccb495c30cad88c79467ef0b21487ad926bad0f9388f7a)
* Send to tx: [Polygonscan](https://polygonscan.com/tx/0x36bf30c7c89b7ef2632df0f9d3c93b12708f532b079fd0493ea80bf593797fb5)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect.netlify.app/# [Testnet]
[Etherscan](https://goerli.etherscan.io/tx/0x0036a8ec4312ba99b8864c1009e6e8c3a5d5fe8096f7051998fe48a473ee0c91)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1fc6a170-e9e0-434c-acc4-ef721ec90a8f

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/usdc-bridge/#
Link to transaction scan at Send to section is no longer present for transaction that is resumed
Attachment:
![Screenshot 2023-11-24 at 13 44 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9ed8d10a-f47a-431c-96f1-0e6d20af69ae)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://testnet.portalbridge.com/df5df83982/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet] when resuming tx 0xb7baf594fa78c7b9a73a05c37d8007e0c38527ec461c180bf6a76438d845ed89 (Arbitrum). Link to Polygonscan is missing.


![Screenshot 2023-12-15 at 19 29 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/79803ff1-dba8-48b8-a5ca-4c472ca78bca)

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/7102d8ccad/#
Transaction hash for transaction from Polygon 0x6f679e45d21e1f411f0a2ab84c624ea33229458443a6440751799be896a54ed4
Attachment:
<img width="1062" alt="Screenshot 2023-12-18 at 11 52 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e9bdb1ac-4543-4f1c-98f8-09ea0bd5a47b">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] after tx is resumed `0xef6bd1b1cc22363f9c503a4616ca0e00e131ae34aa5f099e9c0fe973dff30d0b` (BSC).

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] after tx is resumed `3r5QQLhs6X5HA5Pok76aXNubDJRYXQCYcEg7KT6R2BfcVEB6KtCyCt2zgcnzyTp6K6t9p7u8xnWmCvT8xua6KZKr` (Solana). Link to Etherscan is missing in "Send to" section.

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect.netlify.app/#
Transaction from [Solana](https://explorer.solana.com/tx/36TfDwwiPxw26gAPZJmgcU7wt9mzrN8KYyqh1kA9nnvK7hrU61a4Y7gE782kU1sQu7wKYkP4kfDYJsksf4P1emVy?cluster=devnet) (Solflare) to Arbitrum (Metamask) . TX hash - 36TfDwwiPxw26gAPZJmgcU7wt9mzrN8KYyqh1kA9nnvK7hrU61a4Y7gE782kU1sQu7wKYkP4kfDYJsksf4P1emVy

Attachment:

![Screenshot 2024-01-09 at 13 04 55](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c7f90e48-0143-4608-9b86-243f1abee8b0)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#
For testnet transaction that are resumed seems to be now displaying the explorer link at sent To section, for Mainnet if transaction is resumed explorer link is still missing.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32edd6a7-1389-4ced-ab9f-457cc9d9ce81

![Screenshot 2024-03-07 at 10 30 51](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2bf3727c-553a-42c4-8fa4-0084a4a7366d)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] when tx 0x17c02ed749e7dcc9e2a7b31c1bdef4cc54b121f65cbeab7a2ef84efdfa157172 (BSC) is resumed.  LInk to Solana explorer is not displayed. Link that should be dispalayed: [Solana explorer](https://explorer.solana.com/tx/6zYBzzzuBhKn5x14MHZpqqSa8QjN9dhnyi5cdeJPgCvd257jdy56ZSYCZUpuxbvr6bhnuEpuhrw4qx89eewUaeB).

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Missing Blast explorer link, when transaction [Polygon](https://polygonscan.com/tx/0x2ea050b07d09ee1af522523c5042a0e9c2ccb94ad0ec79f0c959953fa9cf6beb) -> Blast is resumed

Attachment:
<img width="1005" alt="Screenshot 2024-05-13 at 09 47 48" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7cb808d0-74df-46f6-960c-2c0170a34622">

**Comment by agodlevska** [comment]
Reproduced on https://preview.portalbridge.com/ac15114854/
Missing Ethereum explorer link, when transaction [Arbitrum](https://arbiscan.io/tx/0x57dc5cdf7e3380a5eeb960e2399c89ec16ddae0c793bc25a60bb31add1dd4b6e) -> [Ethereum](https://etherscan.io/tx/0x7f537fceb65f4eac7c4643ca7dc67ec439b59b294c0be9dcd8d0f033bb01a511) is resumed

Attachment:
<img width="1440" alt="Screenshot 2024-06-04 at 10 22 52" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b156af72-a721-4bee-b5ff-23fc5e1617f4">

**Comment by tsadovska** [comment]
Issue is still reproducible on https://portalbridge.com/. 
Link on destination chain is not displayed after transaction is resumed. 
Scenario checked: 0.000001 WETH transfer from Osmosis (Leap) to Ethereum (MetaMask). 
* Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/686955C89C4439DC06AFA7DE55E9F3A2A081518F41C08C1EBCD75C6AA122242B)
* Send to tx: [Etherscan](https://etherscan.io/tx/0x4075561adb1c99ca01040f6466f8ec7c83e4e574c4641257454d08e4e962c924)

**Comment by tsadovska** [comment]
Closing the ticket, because link on destination chain is no longer displayed after redesign.
