### ISSUE TITLE
[QA] [Phantom wallet] Transaction to Osmosis expired

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#867]
Preconditions:
Phantom Wallet is connected at sending From section
Keplr Wallet is connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.02 SOL from Solana to Osmosis
2. Click Approve and proceed with transaction
3. Observe the pop-up from wallet

Actual result: Wallet pop-up informs user that the transaction has been expired

Expected result: User approves transaction in the wallet pop-up message and transaction continues

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f122cce-3b49-4baf-909e-aba5bcbebc17

**Comment by AigaD** [comment]
The same message "Transaction expired" also shown when claiming 0.001 WSOL sent from Osmosis (Keplr) to Solana (Phantom)
Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ac9b741-c0fc-4a4a-9863-8e04a753ea7b

**Comment by anondev2323** [comment]
@AigaD Were you on Devnet or Mainnet network in the wallet when you tried to claim? You should be on Devnet

**Comment by AigaD** [comment]
Closing the ticket.
My Phantom wallet was on Solana Testnet, switched over to Solana Devote.
Transaction WSOL from Osmosis to Solana - Passed
Attachment:
https://testnet.mintscan.io/osmosis-testnet/txs/0F6AE6B48E8CC1A74C999E3D943B3FF1112243E173DB090FAA5C9B1512660D2E

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b5c47b1d-d1f1-4a92-9baa-e3ccccb5b6af

Transaction SOL from Solana to Osmosis - Passed
Attachment:
https://explorer.solana.com/tx/5ShjwZyeAPRyPbnJwTUV7oGZpzfkVsKSywfzH1wihYKzGBpY7yDWjpsatbNnRi4MDdf5C61HEGKVrrVCcWwS1xFH?cluster=devnet

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/368eb9b7-59b8-43e1-8831-cba32d5d2bfc
