### ISSUE TITLE
[QA] Neither Approve button nor token registration warning are present when transaction details are entered 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#868]
## Describe the current behavior in detail
"Approve and proceed with transaction" button is not present when sending asset from Osmosis to Sei.

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.110 (Official Build) (x86_64).
 
Steps:
1. Select Osmosis network in "From" section
2. Select Sei network in "To" section
3. Select Leap for Cosmos wallet in "From" section
4. Select Leap for Sei wallet in "To" section
5. Prepare to send 0.1 CELO
6. Observe if "Approve and proceed with transaction" button is present 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6be933ed-ef7e-49d5-b558-e3a5b47229ce

Note:
Issue is also reproducible when sending 0.01 WMATIC from Osmosis (Leap) to Sei (Compass).

 
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/094e640f-8b72-4229-ae11-c402b63a62ca)

## What is the expected/desired behavior
"Approve and proceed with transaction" button is present.

**Comment by tsadovska** [comment]
Issue will be rechecked on https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet] and https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] after Sei network is present in the Networks list.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]. Neither "Approve and proceed with transaction" button nor token registration warning are present when transaction details are entered.

Steps:
1. Select Sui network in From section
2. Select BSC network in To section
3. Connect Sui wallet in From section
4. Select Metamask wallet in To section
5. Select SUI asset
6. Enter Amount 0.1


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5c16b8db-b5a1-4a32-ad19-627c677d05dd

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Goerli network in From section
2. Select Alfajores network in To section
3. Connect Metamask wallets in From and To sections
4. Select WAVAX asset
5. Enter Amount 0.1 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5ec042d5-4f9e-46e6-835a-0c1b2d4a01d9

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
When sending assets to Sui Network

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1be723a0-363c-49a8-a4a1-9ed4354a3439

**Comment by tonyjin** [comment]
I've seen this issue before when switching source/destination chains after attempting an initial source/destination pair.

When we change source/destination, should we retrigger whatever flow tries to calculate the route? A separate issue I've noticed is if I change a source/destination chain from an EVM to another EVM, the transaction doesn't recalculate even if my token balances change.

e.g. I start from Base -> Sui and the change the source chain to Avalanche, the screen doesn't retrigger checks even if I no longer have a balance to submit the intended transaction.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] with following scenario:
1. Select Sui network in From section
2. Select Solana network in To section
3. Connect Sui wallet in From section
4. Connect Phantom wallet in To section
5. Select SUI asset
6. Enter Amount 0.01 


![Screenshot 2023-09-26 at 19 48 23](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2f7bf07a-864c-4be4-a12f-f635ae7fc2eb)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Mumbai network as source chain
2. Select Metamask wallet in From section
3. Select Evmos as destination chain
4. Connect Keplr wallet
5. Select MATIC asset
6. Enter amount 0.01


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a3e17192-5341-4e95-a34e-eee672f609e5

**Comment by tsadovska** [comment]
Reopening the ticket, because it is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Solana as source chain
2. Select Evmos as destination chain
3. Connect Phantom wallet in From section
4. Connect Keplr wallet in To section
5. Select SOL asset
6. Type Amount 0.1 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/83c381b9-097d-447c-be74-ebda9df929fb

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Solana as source chain
2. Select Kujira as destination chain
3. Select Keplr wallet in From section
4. Connect Phantom wallet in To section
5. Select SOL asset
6. Enter Amount 0.1

Neither Approve button nor token registration warning are present when transaction details are entered.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5090865e-b07a-4d0e-8130-a03a179e021d

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1263--wormhole-connect.netlify.app/ [Testnet] with following scenario: 
1. Select Sui network as source chain
2. Select Evmos network as destination chain
3. Connect Sui wallet in From section
4. Connect Leap wallet in To section
5. Select SUI asset
6. Enter Amount 0.001 

Neither Approve button nor token registration warning are present when transaction details are entered.


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c0c1ae61-ac6b-47a2-a90a-c65f3e7e4326)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Prepare to send 0.01 BNB from BSC (Metamask) to Solana (Phantom)
2. Select "Automatic deposit" option in Route section
3. Enable "Native gas" section
4. Change slider position
5. Change destination network to Fantom
6. Connect Metamask wallet in To section
7. Check if Approve button or registration warning is present

Neither Approve button nor token registration warning are present when transaction details are entered.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/72d6bc6b-2d7d-4c41-835a-6c2836abc0ec

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:
1. Prepare to send 0.01 PYTH from Solana (Phantom) to Celo (Metamask) (actual result: Warning to register token in shown)
2. Click Swap button
3. Click Swap button again

Actual result: Warning to register token is no longer displayed.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e8048880-1866-4f86-95da-7fd3dc523e4c

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Goerli network in From section
2. Select Osmosis network in To section
3. Connect Metamask wallet in From section
4. Connect Keplr wallet in To section
5. Select tBTC asset
6. Enter Amount 0.00001


![Screenshot 2023-12-27 at 12 54 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f48d7d5e-3e6b-404f-aab6-08036709608e)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/4adb101c39/ [Mainnet] with following scenario:
1. Send 0.0001 wstETH from Ethereum (Metamask) to BSC (Metamask)
2. Change destination network to Avalanche


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0700e325-86d7-4b0b-9bcf-f9e1b37238ce

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.0001 tBTC from Goerli (Metamask) to Evmos (Leap). Neither Approve button nor token registration warning are present when transaction details are entered.

Steps:
1. Select Goerli as source chain 
2. Select Evmos ar destination chain
3. Select Metamask wallet in From section
4. Select Leap wallet in To section
5. Select tBTC asset
6. Enter amount 0.0001


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/20aef9e7-67ed-4f82-a3f0-19c7b867c715

**Comment by AigaD** [comment]
Reproduced also for transactions to Osmosis/Kujira and Cosmoshub, fields are not shown after filling in the required fields.
Tested from: https://wormhole-connect.netlify.app/#

Attachment:
![Screenshot 2024-01-09 at 14 17 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e43550da-5aa4-42be-b099-6e9d772449a7)

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
For transaction wstETH from Optimism to Polygon, when all the required fields are entered Approve button is not shown.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f74dfd29-84b5-42ac-8bd1-8c1b6136c0f1

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
No Approve button or other fields shown for transaction from Alfajores (Rabby Wallet) to Optimism (Rabby wallet)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/08340385-8105-4ea3-af6c-c9768014d493

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1543--wormhole-connect.netlify.app/

Attachment:

![Screenshot 2024-02-02 at 13 13 33](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9d2354a3-01b2-40f8-afe3-82bea3628b4e)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1543--wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Klaytn as source chain
2. Select Evmos as destination chain
3. Connect Metamask in From section
4. Connect Keplr in To section
5. Select CELO asset
6. Enter Amount 0.001 
7. Check if warning to register token is shown
8. Check if "Approve" button is shown

Actual result: Neither Approve button nor token registration warning are present when transaction details are entered.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e200379a-3638-41ea-a5e1-687b50373949

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Reproduced when sending KLAY from Klaytn to Base Goerli, Approve button is not shown
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7d6e6bc3-8559-4727-950a-28d8b4a5b2a1

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Approve button is not shown for transaction to Kujira.
Attachment:

![Screenshot 2024-02-13 at 15 04 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/20f82ebb-5f3d-4d45-b033-2c543c493d83)

**Comment by tsadovska** [comment]
Scenarios have been rechecked and split to following issues:
1) Neither Approve button nor Token registration warning are present when sending asset to cosmos chains on [tesnet](https://wormhole-connect.netlify.app/), ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1666
2) Token registration warning does not appear after user swaps From/ To sections several times, ticket #1442.
3) Warning to register token does not appear after user disconnects and then reconnects wallet again, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1378.
4) Token registration message is shown when wallet is not connected, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1480.
5) Token registration message is not shown for second time after assets had been changed, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1619
