### ISSUE TITLE
[QA] Claiming fails when sending asset from Osmosis to Sui

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#869]
## Describe the current behavior in detail
Claiming fails when sending WMATIC from Osmosis (Leap wallet) to Sui (Sui wallet). 

Checked from https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] on macOS version 12.6.7 and Google Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 WMATIC from Osmosis (Leap wallet) to Sui (Sui wallet)
2. Click "Claim" button on Redeem screen

Errors are displayed in Console:
```
Uncaught (in promise) Error: invalid arrayify value (argument="value", value="010000000001005f62a20063151e459a12ec81ccf71522fd9cbf1db85ad1ef0eefe2ef01b9ea690ad9fa23fc76146f72acdbf969c5119e1960b14d25fadd2bad5e9093637d63070064eca00f000013370c20ef5251ea1e99ae48732800ccc7b83b57881232a73eb796b63b1d86ed2ea44e270000000000000020000100000000000000000000000000000000000000000000000000000000000f42400000000000000000000000009c3c9283d3e44854697cd22d3faa240cfb0328890005a4055514cc6ce87f54250bf954e0f5b9f5b3ce48bea3ff0af687a20e63b312b800150000000000000000000000000000000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at f.makeError (main.03f4324f.js:37:4463233)
    at f.throwError (main.03f4324f.js:37:4463353)
    at f.throwArgumentError (main.03f4324f.js:37:4463408)
    at c (main.03f4324f.js:37:4351796)
    at b.isTransferCompleted (main.03f4324f.js:37:18146902)
    at m.isTransferCompleted (main.03f4324f.js:37:18175893)
    at Of.isTransferCompleted (main.03f4324f.js:110:154395)
    at Lf.isTransferCompleted (main.03f4324f.js:110:160397)
    at xb.isTransferCompleted (main.03f4324f.js:110:202138)
    at AA.getTransferComplete (main.03f4324f.js:190:105226)
```

```
Error: Transaction failed with the following error. Dry run failed, could not automatically determine a budget: MoveAbort(MoveLocation { module: ModuleId { address: 562760fc51d90d4ae1835bac3e91e0e6987d3497b06f066941d3e51f6e8d76d0, name: Identifier("vaa") }, function: 5, instruction: 16, function_name: Some("assert_registered_emitter") }, 0) in command 1
    at dapp-interface.js:1:69314
    at dapp-interface.js:1:67463
    at a._next (dapp-interface.js:1:66771)
    at t.next (dapp-interface.js:1:64836)
    at dapp-interface.js:1:69230
    at a._next (dapp-interface.js:1:66771)
    at t.next (dapp-interface.js:1:64836)
    at dapp-interface.js:1:67456
    at a._next (dapp-interface.js:1:66771)
    at t.next (dapp-interface.js:1:64836)
```

Send from tx: [MintScan](https://testnet.mintscan.io/osmosis-testnet/txs/9911FDD1F2655D6258C6A982DB24C8DA6835B8DF18D61F57477C77098D3E1A84)

    
![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b9dc51c3-dc8a-4bfa-9cf6-513c348e5169)
    

## What is the expected/desired behavior
User can successfully send and receive assets.

**Comment by M-Picco** [comment]
Have you run into this issue again? Please try on https://wormhole-connect.netlify.app/ this time

**Comment by tsadovska** [comment]
Closing the ticket, issue is no longer reproducible. 

Checked on https://wormhole-connect.netlify.app/ [Testnet]. 
Send from tx: [MintScan](https://testnet.mintscan.io/osmosis-testnet/txs/0E4B92B6CF64E15EA72E7D870F3DBA6F5A1A3B6138A54852473624FA3EAF4439)
Send to tx: [Sui explorer](https://suiexplorer.com/txblock/FS4A1Gm4qgGeKnBJk4wmzWYPcnA2AEukFVVhNVEUP74N?network=testnet)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4e920d09-031b-411a-ab6a-7eb5ac48251a)
