### ISSUE TITLE
[QA] Token balance is not shown in the asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#872]
Preconditions:
Metamask Wallet is connected
USDT token has balance in the wallet

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/ - Tested NOK
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ - Tested OK

Steps:
1. Select Goerli Network
2. Click on Assets
3. Search for USDT, WBTC, DAI asset
4. Observe

Actual result: USDT / WBTC / DAI asset is present in the All Tokens tab, but not on Available Tokens tab, because balance is shown as 0 although wallet has balance for this token

Expected result: USDT/ WBTC / DAI balance is present

Comments: Linked issue - https://github.com/wormhole-foundation/wormhole-connect/issues/849#issue-1864627911

Attachment:

<img width="1354" alt="Screenshot 2023-08-29 at 10 56 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2f644a60-8bd9-4b81-aef3-471838febbc9">

<img width="1014" alt="Screenshot 2023-08-29 at 11 18 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2b2635aa-2b46-4c21-976f-9edc4a725d24">

**Comment by AigaD** [comment]
Adding token contract addresses:
USDT - 0x8BFA1e82Aa6FD7E51C57116A56979E45714379Dc
WBTC - 0xad0361A88378694c93727D56AfB5CDc6927f5649
DAI - 0x2D3538cEe9d0bfA387b20d307C40A95Ee314aAbD

**Comment by tsadovska** [comment]
We added following token contract addresses and balance for them are shown in "Available Tokens" tab:
* WBTC - 0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05
* USDT - 0xC2C527C0CACF457746Bd31B2a698Fe89de2b6d49
* DAI - 0x11fE4B6AE13d2a6055C8D9cF65c55bac32B5d844

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/93172dda-c1a1-4737-a1e3-a86cb5e85925)

**Comment by AigaD** [comment]
Closing this, as the tokens are shown in the asset list.
Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/
Incorrect balance that is shown for the assets is reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/892#issue-1875702386
Attachment:
<img width="1317" alt="Screenshot 2023-09-04 at 10 08 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/064a82d1-7fe9-47fa-b46c-ff7496d96b5a">
