### ISSUE TITLE
[QA] [Mainnet] Tokens are not shown for the second transaction in a row

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#873]
Preconditions:
One transaction completed (in my test wstETH from Osmosis -> Ethereum)

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from:
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/

Steps:
1. Click on Bridge more assets
2. Click on Select Network
3. Choose Osmosis
4. Click on Assets
5. Observe

Actual result: Assets that were present for the first transaction are no longer showing in the asset list for second transaction. User has to refresh the page in order to see the assets

Expected result: Available assets are shown

Attachment:
First transaction:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/411a1a46-1a69-4546-9321-e0052cadd322

Second transaction:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ef4ab409-27b4-4157-87e1-31494057d68f

**Comment by tsadovska** [comment]
Blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/778. Transaction is not starting, "Error: Chain is not cosmos chain" appears in Console when user sends 0.001 WETH from Osmosis (Leap) to Arbitrum Goerli (Metamask).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Issue is no longer reproduced. Asset balance is shown for second transaction in a row.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b511986e-c2b0-4399-bab4-da04ddd1ddd5

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Issue is no longer reproduced. Asset balance is shown for second transaction in a row.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b511986e-c2b0-4399-bab4-da04ddd1ddd5
