### ISSUE TITLE
[QA] Warning message "Amount cannot exceed balance" is not shown when an unavailable asset is selected 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#883]
## Describe the current behavior in detail
Warning message "Amount cannot exceed balance" is not shown when an unavailable asset is selected.

Checked on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] with macOS Version 12.6.7 and Google Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Precondition:
User doesn't have DAI asset on Osmosis. 

Steps:
1. Select Osmosis network in From section
2. Select Goerli network in To section
3. Select Leap wallet in From section
4. Select Metamask in To section
5. Open Asset list
6. Switch to "All tokens" tab
7. Select DAI asset
8. Type amount 0.1
9. Observe if warning "Amount cannot exceed balance" is shown on Bridge screen
10. Click "Approve and proceed with transaction" button
12. Observe if warning "Amount cannot exceed balance" is shown on Bridge screen

Errors are displayed in Console:
```
Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at f.makeError (main.0b4f4720.js:37:4720438)
    at f.throwError (main.0b4f4720.js:37:4720558)
    at c.<anonymous> (main.0b4f4720.js:37:4784994)
    at Generator.throw (<anonymous>)
    at s (main.0b4f4720.js:37:4776785)
```
    
```
main.0b4f4720.js:137 Error: Could not derive IBC asset denom
    at Lf.fromCosmos (main.0b4f4720.js:110:156021)
    at async xb.send (main.0b4f4720.js:110:201519)
    at async Object.onClick (main.0b4f4720.js:137:24093)
```

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/cde8b6f5-2d80-4781-878f-6914917730c9

    
## What is the expected/desired behavior
Warning message "Amount cannot exceed balance" is shown.

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Warning message "Amount cannot exceed balance" is not shown when an unavailable asset is selected.

Error:
```
Error: Cosmos transaction failed with code 5. Log: failed to execute message; message index: 0: spendable balance  is smaller than 1000ibc/898ACF6F5DEBF535103BBD52E3E5B70A311AD097B198A152483F69290B4210C0: insufficient funds
    at signCosmosTransaction (main.js:477:314970)
    at async signAndSendTransaction (main.js:477:315557)
    at async Operator.send (main.js:483:79282)
    at async Object.Qn [as onClick] (main.js:649:95817)
```

![Screenshot 2024-01-17 at 13 03 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fa136689-5388-4d86-ab85-c41be4c9b93d)

**Comment by AigaD** [comment]
Tested OK.
Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portalbridge.com/b05f4e9322/
Warning message `Amount cannot exceed balance` is shown if user selects unavailable token from All tokens tab and enters amount 
Attachment:
<img width="1124" alt="Screenshot 2024-03-27 at 09 10 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d354aa9-ece8-4751-b9bf-5e11974b8327">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f88ff918-98fd-4cf8-af03-6a30a73798bc
