### ISSUE TITLE
[Bug] Incorrect decimals/balance when adding a token to Metamask

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#892]
Original issue: https://github.com/XLabs/portal-bridge-ui/issues/364

**Comment by AigaD** [comment]
The same issue for other assets as well, in example when added token from transaction 0.001 WMATIC from Osmosis to Mumbai.
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/#
Attachment:
<img width="1320" alt="Screenshot 2023-09-01 at 11 47 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/35581858-eef2-4377-bcf7-969e60b9be02">

**Comment by tsadovska** [comment]
Balance is incorrectly shown in Metamask notification "Custom spending cap".
Tested from https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet].

Steps:
1. Connect Metamask wallet in From section
2. Connect Leap wallet in To section
3. Prepare to send 0.000001 WETH (Ethereum) from Ethereum to Osmosis
4. Click "Approve and proceed with transaction" button
5. Observe Metamask notification "Spending cap request for your WETH"

![Screenshot 2023-09-01 at 15 47 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2ecdb99d-13fe-4397-9a76-eb81198531a1)

**Comment by AigaD** [comment]
Reproducible also from: https://cctp--wormhole-connect.netlify.app/# and https://cctp-testnet--wormhole-connect.netlify.app/#
Incorrect number is shown when adding token to the wallet.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/83f46d44-4423-4cbd-bd2f-e045fe44f06f

<img width="1369" alt="Screenshot 2023-09-07 at 15 59 10" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/84ea1f0a-66d3-4f9e-b237-d7ad821f38a8">

**Comment by tsadovska** [comment]
Reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] for WFTM asset. 

- Scenario: Send FTM from Fantom (Metamask) to Arbitrum (Metamask).
- Send from tx: [Ftmscan](https://ftmscan.com/tx/0x9700fadb6eff3009f6f1a13e192a0db5117ba97299a56f6182f3c3f7326f3e02)
- Send to tx: [Arbiscan](https://arbiscan.io/tx/0xbec4f17b82f2562897406d9e0c4de5675126b29463056fe42d7e6bef25c66629)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f52e9f07-60a3-42c4-8f01-b921cefc5d70)

**Comment by tsadovska** [comment]
Reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] for WETH asset.

- Scenario: Send ETH from Ethereum (Metamask) to Optimism (Metamask)
- Send from tx: [Etherscan](https://etherscan.io/tx/0x82c53d4c5255f5a1f84780337a008d96a059c0cd9314a00a2700257b0f64c910)
- Send to tx: [Optimism](https://optimistic.etherscan.io/tx/0x80878b9149127b6dd4855822c147a2666bbeece72276eb7b25da5175edf5fe1b)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5b0a0de9-3d3f-40b1-ba42-1edd17388052)

**Comment by tsadovska** [comment]
Reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] with WAVAX asset.
* Scenario: Send AVAX from Avalanche to Optimism
* Send from tx: [Snowtrace](https://snowtrace.io/tx/0x29facbd3d55673eed9e1a4951035b37e33a198a936a6576c15ea483b024b120b)
* Send to tx: [Optimism](https://optimistic.etherscan.io/tx/0x1eb1c5d1be5d110fc8a171ddaed8a2daf87a267dda38464555244d871affcf88)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c6b50097-40a8-49c8-b18e-628e66ff5e68)

**Comment by AigaD** [comment]
Reproducible from https://feature-configurable-routes--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f5adf26c-2fa6-413a-89ef-66a43637a905

**Comment by tsadovska** [comment]
Issue was not reproducible on https://cctp-only--wormhole-connect.netlify.app/  [Mainnet] for following scenarios:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9ab52c27-5b4f-4bdd-8f77-aac454767fc0)


Issue was not reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet] for following scenarios:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aacb7e8f-c32f-4572-90df-b752d0d72941)
