### ISSUE TITLE
[Bug] User is able to choose the same To and From networks when bridgeDefaults settings are used

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#893]
Original issue: https://github.com/XLabs/portal-bridge-ui/issues/366

In this particular case, wh connect is configured to use `osmosis` as the default `toNetwork` and as the `requiredNetwork` as well.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when:
* User opens https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ and clicks on Swap button
* User clicks on "Bridge more assets" button to start new transaction and clicks on Swap button
