### ISSUE TITLE
[Bug] "View on Wormhole Explorer" link opens error page for cosmos chains

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#894]
Original issue: https://github.com/XLabs/portal-bridge-ui/issues/367

Transfers from gateway enabled cosmos chains (e.g. Osmosis) go through Wormchain, which is the actual chain that emits the VAA. Thus, using the source chain id (`20` for Osmosis) will yield a "not found" error.

Potential solutions:
1. Replace the source chain id with wormchain's chain id (`3104`) when redirecting to wormholescan
2. Talk with the wormholescan team on adding a "synthetic chain id/vaa" for these cosmos source chains

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] when sending USDT from Ethereum (Metamask wallet) to Arbitrum (Metamask wallet). "View on Wormhole Explorer" link opens error page. 

- Send from tx: [Etherscan](https://etherscan.io/tx/0x96107583bb91e04811c68496ce8b7eee5296668e834858c88e264ad616bc9d1c)
- Wormhole Explorer: [Wormholescan](https://wormholescan.io/#/search-not-found/?q=2/0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585/127511)

Error:
```
Search not found

Sorry! We traversed all space-time for you, however, this is likely an invalid search string because we can't find any items that match:

2/0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585/127511
If you think this is a problem with us,

[please tell us.](https://discord.com/invite/wormholecrypto)
```

Recording:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2af60ba0-c237-4711-a723-2d8ffe0b314d

**Comment by tsadovska** [comment]
Issue is reproducible on https://feature-configurable-routes--wormhole-connect.netlify.app/ [Testnet] when sending 0.11 ETH from Goerli (Metamask) to Arbitrum Goerli (Metamask). "View on Wormhole Explorer" link opens error page.
* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x6726e0aed2db4d74f415223673d3c2771ed665418d7b62907c0d5106267063ab)
* Wormhole Explorer: [Wormholescan](https://wormholescan.io/#/tx/2/000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7/182069?network=TESTNET)

Error:
```
Sorry! We traversed all space-time for you, however, this is likely an invalid search string because we can't find any items that match:

2/000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7/182069
If you think this is a problem with us,

[please tell us.](https://discord.com/invite/wormholecrypto)
```

Recording:


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f4d4ec52-5eeb-4dc7-bf78-be23c1dad5bd

**Comment by AigaD** [comment]
Tested OK from: https://deploy-preview-1015--wormhole-connect.netlify.app/#

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8f11b0cf-76a4-47e7-b53d-e6892238fea3

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000001 ETH from Ethereum (Metamask) to Base (Metamask).  "View on Wormhole Explorer" link opens error page.

Send from tx: [Etherscan](https://etherscan.io/tx/0x33fc5320a5a72d679ad9fc4275159d6503e29a460d245626e9276f9ba411abd7)
Wormhole Explorer: [Wormholescan](https://wormholescan.io/#/search-not-found/?q=2/0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585/129736)

Error: 
```
Search not found
Sorry! We traversed all space-time for you, however, this is likely an invalid search string because we can't find any items that match:

2/0000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585/129736
If you think this is a problem with us,

[please tell us.](https://discord.com/invite/wormholecrypto)
```

Recording:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e3ebe572-536b-4137-aa6d-7b28c9b4dc1c

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] when sending 0.1 USDC from Ethereum (Metamask) to Base (Metamask). "View on Wormhole Explorer" link opens error page.  "Two transactions" option was selected in Route section.

Send from tx: [Etherscan](https://etherscan.io/tx/0xedc9e4f72fc365a04201db840946fa4f442013a932e56f61ff281757c7256559)
Wormhole explorer: [Wormholescan](https://wormholescan.io/#/tx/0xedc9e4f72fc365a04201db840946fa4f442013a932e56f61ff281757c7256559)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f44dc8a1-5e7e-444f-9316-aededd5e8351

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 USDC from Avalanche (Metamask) to Base (Metamask). 

Send from tx: [Snowtrace](https://snowtrace.io/tx/0x79b7cb1b3a83fc55d0b6825da398ded2c8579a035f47410dfa4a78188f5211e6)
Send to tx: [BaseScan](https://basescan.org/tx/0xb960bfcceb5c0198b00fff8d6e7e7a285a643ea435a9b1312e9549dcaf8a2bb4)
Wormhole explorer: [Wormholescan](https://wormholescan.io/#/tx/0x79b7cb1b3a83fc55d0b6825da398ded2c8579a035f47410dfa4a78188f5211e6)

Error:
```
Sorry! We traversed all space-time for you, however, this is likely an invalid search string because we can't find any items that match:
0x79b7cb1b3a83fc55d0b6825da398ded2c8579a035f47410dfa4a78188f5211e6
```



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7fa35164-a285-49dc-84e5-abe43449afe1

**Comment by tsadovska** [comment]
Issue is no longer reproducible, "View on Wormhole Explorer" link opens transaction details page.
* https://wormhole-connect.netlify.app/ [Testnet]
  Scenario: Send ETH from Goerli to Arbitrum Goerli ([Goerli](https://goerli.etherscan.io/tx/0xc6e98d7d48ef79c89f9e2ed0b86368e6388c91b161c80dc3f7243786f73ca996),[Arbiscan](https://testnet.arbiscan.io/tx/0x6b248cce9d5f6752479d10de674aa26487a2aa96092eb34e2cb0cb709a77f522))
 * https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
   Scenario: Send USDT from Ethereum to Arbitrum ([Ethereum](https://etherscan.io/tx/0x7ffcb2e37403c37ad8130727ab58fd476744f43fee0b075ed68b033076ebe37d), [Arbiscan](https://arbiscan.io/tx/0xf5691ddbf57dee878434641eea56e0db0862f19f28694a502296f69db08180b5))
   Scenario: Send USDC from Avalanche to Base ([Avascan](https://avascan.info/blockchain/c/tx/0x0f852ec1ee78f40790fb5b71063b4a0b47532e21d3f551e0a9909d00a9c5aa56), [Basescan](https://basescan.org/tx/0x3f52f4bb8703f3842d05f5c96091e31f79c86b17b47340f6436931039559524b))
   
Ticket is closed.
