### ISSUE TITLE
[QA] Transaction details are cleared when user clicks “Terms of Use” link when transaction is already started

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#906]
## Describe the current behavior in detail
Transaction details are cleared when user clicks “Terms of Use” link when transaction is already started.

Checked on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] with macOS Version 12.6.7 and Google Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps
1. Prepare to send 0.000001 WBTC from Ethereum (Metamask) to Osmosis (Leap wallet)
2. Click "Approve and proceed with transaction" button
3. Clicks "Terms of Use" link
4. Click Back button

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/52cc0728-a626-4085-8662-1d4c407a9ca5

## What is the expected/desired behavior
Transaction details are shown.

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] with following scenario:
1. Prepare to send 0.01 AVAX from Avalanche (Metamask) to Optimism (Metamask)
2. Click "Approve and proceed with transaction" button (actual result: Metamask notification to confirm transaction is displayed)
3. Click "Terms of Use" link 
4. Click Back button to return to Bridge screen (actual result: transaction details are cleared and only wallets are connected)
5. Click "Confirm" button on Metamask notification
6. Wait until Redeem screen is opened



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9e47916c-ea60-46b3-99e1-d234baa04fce

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/# , transaction details are cleared when clicking on "Terms of service", but transaction is finished.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/544502d8-abff-46a1-ab2f-510d9d6680b3

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 AVAX from Fuji (Metamask) to Fantom (Metamask).

**Comment by tsadovska** [comment]
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7f08c07c-872b-4793-8d7e-0f48447ff914

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/ [Mainnet]. 

Steps:
1. Prepare to send 0.001 USDC (Base) from Base (MetaMask) to Polygon (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click "Terms of Use" link on wormhole-connect
4. Click on Back button to return to main screen
5. Check if transaction details are displayed

Actual result: Transaction is started after user confirms transaction in MetaMask. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c0a46eff-e8c6-4bb7-8316-7e359e9f7905

**Comment by agodlevska** [comment]
Checked on https://wormhole-connect-mainnet.netlify.app/. 
Issue is still reproducing the same scenario from the previous comment.

Attachment: 

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/72e33b92-556e-4f9e-80f1-9d1ac8945446

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign, “Terms of Use” link is not displayed on Confirm transaction screen. 
Closing the ticket.
