### ISSUE TITLE
[QA] Failed to fetch wstETH from Osmosis to Goerli

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#911]
Preconditions: 
1. Keplr wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Osmosis Network has wstETH balance
4. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.0001 wstETH from Osmosis to Goerli
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, error `TypeError: Failed to fetch` is shown in the console

Expected result: Transaction moves forward to next screen and is completed 

Attachment:
<img width="1368" alt="Screenshot 2023-09-04 at 11 03 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c3c0fa5b-e266-4c41-8140-b9db366ac1a7">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6cfb7a4a-ed4b-42e8-8bfa-888df05fb11e

**Comment by AigaD** [comment]
The same error `TypeError: Failed to fetch` also reproduced for transaction APT from Osmosis to Aptos.
Linking to issue https://github.com/wormhole-foundation/wormhole-connect/issues/857#issue-1866610749 because when selecting APT asset the balance disappears 
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/70af8643-c187-4940-8ec8-89399758bf85

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Cannot send wstETH from Osmosis to Goerli.
Console: `Error: Chain is not cosmos chain`

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ed71c8c-93f7-43ea-bf6d-999d504afc87

**Comment by AigaD** [comment]
Will be re-checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1111 is closed

**Comment by tsadovska** [comment]
Remaining issue on Osmosis: https://github.com/wormhole-foundation/wormhole-connect/issues/1111.

Arbitrum Goerli, Optimism Goerli and Base Goerli balances are not loading on https://wormhole-connect.netlify.app/ [Testnet].

Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.
