### ISSUE TITLE
[QA] Redeem screen does not open in 40 min although transaction is successful

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#912]
## Describe the current behavior in detail
Redeem screen does not open in 40 min although transaction is successful.

Checked from https://wormhole-connect.netlify.app/ [Testnet] on macOS version 12.6.7 with Google Chrome Version 116.0.5845.140 (Official Build) (x86_64)

Steps:
1.  Connect Metamask wallets in From and To sections
2. Prepare to send 0.01 WFTM from Base Goerli to Moonbase
3. Click "Approve and proceed with transaction" butoon
4. Observe if transaction is displayed as successful in Metamask wallet
5. Observe if Redeem screen is opened

Send from tx: [BaseScan](https://goerli.basescan.org/tx/0xebacb1587689bf239c5e0d8fd7cd7789e675f3453cf50634415c878bbfada946)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/20e9777e-70ff-4bb6-a414-c1f3975c9359

## What is the expected/desired behavior
Redeem screen is opened.

**Comment by evan-gray** [comment]
Related to #903 #909
