### ISSUE TITLE
[Bug] Missing explorer link on destination chain for gateway transfer

### ISSUE THREAD

**Issue by M-Picco** [wormhole-foundation/wormhole-connect#913]
Currently there's no logic to retrieve the final tx on the destination chain (e.g. osmosis)

**Comment by AigaD** [comment]
Missing explorer link at Send To section from https://cctp-testnet--wormhole-connect.netlify.app/ transactions
Attachment:
<img width="1323" alt="Screenshot 2023-09-07 at 11 18 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b97a7cc9-8296-4565-bf47-391bcc0ff098">

**Comment by tsadovska** [comment]
Also reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet]. Explorer link is not displayed in "Send to" section on Redeem screen.

Steps:
1. Connect Metamask wallets in From and To sections
2. Prepare to send 1.06 USDC from Avalanche to Arbitrum
3. Select "Pay with one transaction" in Route section
4. Click "Approve and proceed with transaction" button
5. Observe if explorer link is displayed in "Send to" section

Send from tx: [Snowtrace](https://snowtrace.io/tx/0xab293ec1387e8994a20f0188c72db6358f3b8bf3348e05cfe5de9bfd3eebe7dd)

**Comment by AigaD** [comment]
Issue reproducible from: https://feature-configurable-routes--wormhole-connect.netlify.app/#
In attachment transaction from Alfajores to Osmosis

Attachment:
<img width="1310" alt="Screenshot 2023-09-12 at 13 35 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c5edef42-836e-4d1a-aff7-237d445ce8e8">

**Comment by tsadovska** [comment]
Issue is reproducible from https://cctp-only--wormhole-connect.netlify.app/ [Mainnet] when sending 1.5 USDC from Avalanche (Metamask) to Arbitrum (Metamask). One transaction option was selected in Route section.

Send from tx: [Snowtrace](https://snowtrace.io/tx/0x1c6dfd0dda2a80f17129241d13cc0307ad6d3609aedaeb39eff091a80f02333a)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/18d3eb6f-a9e2-44ad-bf84-c803e51e3636)

**Comment by AigaD** [comment]
Issue reproduced from https://deploy-preview-907--wormhole-connect.netlify.app/# 
Attachment:
<img width="1053" alt="Screenshot 2023-09-15 at 13 01 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8454d3cb-ad3d-4cd8-815d-d7bf1cf5de5c">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] when sending 0.5 CELO from Fuji (Metamask) to Solana (Phantom). One transaction option was selected in Route section.

* Send from tx: [Snowtrace](https://testnet.snowtrace.io/tx/0xe69e1145e1349f8e071e88a5704fefb2d2f83d6774fbe4fc7a1206bbc10aee54)
* CELO token on Solana Explorer: [Solana Explorer](https://explorer.solana.com/address/84F2QX9278ToDmA98u4A86xSV9hz1ovazr8zwGaX6qjS?cluster=devnet)

![Screenshot 2023-09-15 at 21 07 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/eba49218-2087-4c25-87a7-ed9883a538ae)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet] when sending SOL from Solana (Phantom) to Osmosis (Leap). 
* Send from tx: [Solana explorer](https://explorer.solana.com/tx/KfKApT2D5JWwhQTKgGNkESNEkVorQXU99gQfbBGV1B1SNkf9EvYanM7PzKpbUNDvZnj6LZ2eAXa1WVtiqEhedY8)
* Wormhole Explorer: [Wormhole Explorer](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/315273)

![Screenshot 2023-09-19 at 21 22 27](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8d35ca16-9300-4182-85ee-b12907414a15)

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1014--wormhole-connect.netlify.app/#
For transactions to Osmosis explorer link is not shown

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 USDC (Goerli) from Goerli to Osmosis (Leap). Explorer link is not displayed on the destination chain. Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x8f907dedbad4abe8bdea7d66e18b58fffcb07b63b3ab73b064732fcbcd8fb135)

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:

<img width="1140" alt="Screenshot 2023-09-26 at 16 58 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1f73f71c-ef9d-4946-b644-92d2b9c58c5f">
