### ISSUE TITLE
[QA] A negative number of confirmations is displayed

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#918]
## Describe the current behavior in detail
A negative number of confirmations is displayed.

Checked from https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] on macOS version 12.6.7 with Google Chrome Version 116.0.5845.140 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallet in From section
2. Connect Leap wallet in To section
3. Prepare to send 0.2 MATIC from Polygon to Osmosis
4. Click "Approve and proceed with transaction" button

Send from tx: [PolygonScan]( https://polygonscan.com/tx/0xc22f197977cf357be265959e708738fc922fd75a6e4efca27e9598515c69d3cf)

![Screenshot 2023-09-05 at 11 03 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4d2c20d2-6db7-4ceb-8951-e223f4dcdfcf)

## What is the expected/desired behavior
Correct number of confirmations are shown.

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when sending AVAX from Avalanche (Metamask) to Osmosis (Leap).
Send from tx: [Snowtrace](https://snowtrace.io/tx/0x7063f98e8e8f1e0a454723672f6af81f26faf285eff4bffe8876efadc4f38bec)

![Screenshot 2023-09-06 at 19 52 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/840267ce-1484-4934-a849-ed2ce4f5d2bf)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet] when:
* sending USDC from Ethereum (Metamask) to Avalanche (Metamask)
* sending USDC from Ethereum (Metamask) to Arbitrum (Metamask)

A negative number of confirmations is displayed for a brief moment.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8c36c0d0-6cb6-4bf6-b898-8bf26d0a1dc4)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. A negative number of confirmation is displayed for a brief moment. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f3a95a18-1be2-407c-bd84-dc44d958fd10

**Comment by AigaD** [comment]
Reproduced for transaction MATIC from Mumbai to Cosmohub, a negative number for confirmation stayed for few seconds.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
![Screenshot 2023-10-18 at 09 26 16](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c8889a1d-43e1-4ee7-8abf-bfec2761c34f)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when resuming transaction. 
Tx hash: 0x85339f35e88e9ca17bd6287ba798285af2361fcbbde309a0a545a2a06a3c7efd (Polygon), [Polygonscan](https://polygonscan.com/tx/0x85339f35e88e9ca17bd6287ba798285af2361fcbbde309a0a545a2a06a3c7efd)


![Screenshot 2023-11-03 at 18 06 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8ee14ef9-1ad9-429c-8c0b-212f2c6729c0)

**Comment by AigaD** [comment]
Tested from: https://testnet.portalbridge.com/df5df83982/
Negative number of confirmations is displayed for a moment for transaction Goerli -> Aptos.
Attachment:
<img width="1048" alt="Screenshot 2023-11-27 at 11 08 02" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2da29420-0893-49d8-830e-7c363342f2b9">

**Comment by AigaD** [comment]
Reproduced for transaction tBTC from Fuji (Metamask) to Fantom (Metamask)
Tested from: https://wormhole-connect.netlify.app/#
Attachment:


![Screenshot 2024-01-09 at 10 21 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d87ba225-0c84-4ab2-b736-84ab689d4801)

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] v0.2.12-396d07288d when sending BONK from [BSC](https://bscscan.com/tx/0xd73a3628885d1cc30c4393dfc32aab547cfd42466e2ec6fcfa2ac0acba3ce756) (MetaMask) to [Injective](https://explorer.injective.network/transaction/1C6E0C362C2B4A6233F244B1C46C6C0D76DB5829A8D9F12BB770958DE8F5B20F/) (MetaMask). 

![Screenshot 2024-03-13 at 12 54 02](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9fec0ac2-9fb7-403e-9833-2feac81e9a0e)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/ 
Transaction 0.2 ETH from Ethereum to Base has negative confirmation count.

Attachment:

<img width="846" alt="Screenshot 2024-03-28 at 08 34 18" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/62b77551-e91c-4699-a34c-b403997801d5">

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-1674--wormhole-connect.netlify.app/ [Testnet] when sending 0.01 USDC from Fuji (Brave wallet) to Alfajores (Brave wallet). A negative number of confirmations is briefly shown. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bf34357b-d8b6-4359-8b09-6dff1728aac6

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.001 ETH from Ethereum (MetaMask) to Optimism (MetaMask). Send from tx: [Etherscan](https://etherscan.io/tx/0x0a6df47b4ce8590ca6643b2d287c12e5ac9fba56165087d68a21206e978409cd).


![Screenshot 2024-04-30 at 18 37 22](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/04b1341a-cf69-4127-8d01-7fdd777f2b3f)

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0005 wstETH from Ethereum (Rabby) to Polygon (Rabby). Send from tx: [Etherscan](https://etherscan.io/tx/0x2cfe70f82287fc2cb951c7366da72ebd579a63cae07adf35d4b4dee3facabf5c). One tab is opened. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/caeb3f14-c733-474e-86b8-abe240d22299)

**Comment by agodlevska** [comment]
Reopening the issue. 
Reproducible on https://preview.portalbridge.com/3365c86aff/ when sending 5.5 USDT from Ethereum (MetaMask) to BSC (MetaMask). 

Attachment: 
<img width="713" alt="Screenshot 2024-07-18 at 10 31 12" src="https://github.com/user-attachments/assets/dd769f2a-c326-4e35-8448-269fe4f9ec53">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/c6532d9b17/ [Mainnet] when sending wstETH from BSC (MetaMask) to Ethereum (MetaMask). One tab was open. 


![Screenshot 2024-07-29 at 07 48 48](https://github.com/user-attachments/assets/aadfd788-f41c-4025-83cd-ec192d683103)

**Comment by tsadovska** [comment]
Following scenarios are no longer reproducible on https://portalbridge.com/:
* 0.01 USDT transfer from [Ethereum](https://etherscan.io/tx/0xe5e32ca34f5fd7c648e2e54b9bee791b13c8b03cf9305d78ee5d22170bb0aabc) (MetaMask) to [BSC](https://bscscan.com/tx/0x22227338ebb35b78a8747236e6c052c86cb9bfc1c609bec980344c142a3d6260) (MetaMask)
* 0.00001 wstETH transfer from [BSC](https://bscscan.com/tx/0x6ab45e53226fc8de66964eb3ccb5b2167de9c345921d2a6c66df21c49628da25) (MetaMask) to [Ethereum](https://etherscan.io/tx/0x54c3373820d06e4438a291c3055297cb1f678c5661df3a2930653dc6d5f97c47) (MetaMask)

Closing the ticket.
