### ISSUE TITLE
[QA] Incorrect amount is shown in One transaction option until user selects it

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#923]
## Describe the current behavior in detail
Incorrect amount is shown in One transaction option until user selects it.

Builds - Tested NOK:
https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]
https://cctp--wormhole-connect.netlify.app/ [Mainnet]

Checked from macOS version 12.6.7 and Google Chrome Version 116.0.5845.140 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallets in From and To sections 
2. Select Goerli/Ethereum network in From section
3. Select Arbitrum Goerli/Arbitrum network in To section
4. Prepare to send 1.12 USDC (Goerli)/USDC (Ethereum) 
5. Expand Route section
6. Observe Amount value in "Pay with one transaction" option **(actual result: 1.02 USDC)**
7. Select "Pay with two transactions" option in Route section 
8. Observe Amount value in "Pay with one transaction" option **(actual result: 1.12 USDC)**
9. Select "Pay with one transaction" option in Route section 
10. Observe Amount value in "Pay with one transaction" option **(actual result: 1.02 USDC)**

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b4c726b1-e09f-4841-9dcb-24193b9036d1

## What is the expected/desired behavior
Correct amount is shown in One transaction option when option "Pay with two transactions" is selected in Route section.

**Comment by AigaD** [comment]
Reopening issue as this is still reproducible from https://feature-configurable-routes--wormhole-connect.netlify.app/ and https://cctp--wormhole-connect.netlify.app/
Also if user first enters different amount and the changes it, the previously entered value still shows at One transaction and Preview sections (See attachment 1)

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/828a7ae9-df09-4428-9a2c-c91c2f0a29c1



https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/de26cfc2-d026-4b5c-860e-4acaeab7e07f


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b71dd5cd-4352-4120-a02b-f345f76fb94c

**Comment by tsadovska** [comment]
Tested OK on:
- https://cctp-only--wormhole-connect.netlify.app/ [Mainnet]
- https://latest--wormhole-connect.netlify.app/ [Mainnet]

**Comment by tsadovska** [comment]
Tested OK on:
* https://deploy-preview-1014--wormhole-connect.netlify.app/ [Testnet]
* https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]

Correct amount is shown in One transaction option when option "Pay with two transactions" is selected in Route section.
