### ISSUE TITLE
[QA] Balance for asset is not showing in the asset list

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#929]
Preconditions:
Nightly wallet connected
Nightly wallet for testnet has balance for Aptos token

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-testnet--wormhole-connect.netlify.app/ - Tested NOK
https://cctp--wormhole-connect.netlify.app/# - Tested NOK

Steps:
1. Select Aptos Network
2. Open Asset list
3. Observe

Actual result: APT asset is not showing in the Available Token list, although testnet tokens for APT are available in the wallet

Expected result: APT asset is shown in the Available token list with available balance

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/821c91dc-ec06-4176-b2c9-af432b51734b

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1405c5be-acd3-4956-b9c9-921582ab7ade

**Comment by tonyjin** [comment]
Reducing to P2 - known issue with flakey testnet RPCs

**Comment by tsadovska** [comment]
Issue is reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] with following scenario:
1. Connect Phantom wallet in From section
2. Connect Metamask wallet in To section
3. Select Solana network in From section
4. Select Arbitrum network in To section
5. Open Assets list and check available tokens (in my case: SOL and BONK)
6. Click Swap button several times to change From/To wallets and networks
7. Open Assets list when Solana is selected in From section
8. Observe available tokens (BONK asset is missing)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8515eb6a-0e34-4709-b487-def74563a46a

**Comment by AigaD** [comment]
Aptos balance is not showing.
Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/273aa790-b47c-4e95-9e9f-240f0b526e5f

**Comment by AigaD** [comment]
Aptos balance is not showing.
Tested from: https://latest--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e95ffcad-a199-4745-94bc-0b04a6689c4c


<img width="1147" alt="Screenshot 2023-09-14 at 18 05 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b45013ea-ade8-4c15-b07d-95bacd5b690a">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet]. "No balance detected" message is shown when user has assets in Spika wallet.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/299ef515-9187-4ff1-a646-b89584b36fee)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b79157f2-04d9-4570-a97a-dd0364530658)

**Comment by AigaD** [comment]
Issue reproduced from: https://deploy-preview-1014--wormhole-connect.netlify.app/
Nightly wallet connected shows no balance available for Aptos asset
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4f3e87bc-2ab0-4edf-af95-91e60052ff81

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Aptos balance is not showing in token list.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7a3d88a0-61ea-4456-8101-358bfdb9746c

**Comment by AigaD** [comment]
Issue is reproducible.
When Aptos Network is selected balance for assets are not loaded.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/de9832f3-3e7c-4915-9ce8-f3681cb98203

**Comment by AigaD** [comment]
Closing. Tested OK.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Tested Nightly (Aptos), Spika (Aptos) and Solflare (Solana) wallets and assets are shown in the asset list with correct balance.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/81402199-1d32-485f-8745-6ce76d71b86d


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f39f21f5-ba65-4080-b0e7-6421b31dfc0b
