### ISSUE TITLE
[QA] [Mainnet] Sei wallets should not be shown on "Connect wallet" screen if chain is not configured

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#931]
## Describe the current behavior in detail
Sei wallets are present on "Connect wallet" screen, but Sei network is not configured.

Builds:

- https://cctp--wormhole-connect.netlify.app/ [Mainnet] - Tested NOK
- https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] - Tested NOK
- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet] - Tested OK

Checked on macOS version 12.6.7 with Google Chrome Version 116.0.5845.140 (Official Build) (x86_64).

Steps:
1. Click "Select network" in From section and check if Sei network is present
2. Click "Connect wallet" button in From section and check is Sei wallets are shown

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/633148ac-8b95-4dbf-832d-53a0fe059058

## What is the expected/desired behavior
Sei wallets should not be shown on "Connect wallet" screen if chain is not configured.

**Comment by tonyjin** [comment]
Sei not supported officially in Connect yet

**Comment by tsadovska** [comment]
Issue is also reproducible on:
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
* https://preview.portalbridge.com/df5df83982/ [Mainnet]

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Sei wallets are not shown on "Connect wallets" screen.

Ticket is closed.
