### ISSUE TITLE
[QA] User can select an asset that is not available for the route

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#932]
## Describe the current behavior in detail
User can select an asset that is not available for the route.

Builds - Tested NOK:

- https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]
- https://wormhole-connect.netlify.app/ [Testnet]

Steps:
1. Connect Metamask wallets in From section
2. Connect Leap wallet in To section
3. Select Fuji network in From section
4. Select Osmosis network in To section
5. Prepare to send 3 AVAX
6. Click on Asset in To section
7. Switch to "All tokens" tab
8. Change asset to WBTC

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d78a4984-2b20-4d23-add6-9a748afa032b

## What is the expected/desired behavior
User shown not be able to select an asset that is not available for the route.

**Comment by tonyjin** [comment]
Will be addressed by @anondev2323's incoming PR

**Comment by AigaD** [comment]
Reproducible from https://feature-configurable-routes--wormhole-connect.netlify.app/ 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/07987fa3-231e-47c5-921d-30a74bbd07e8

**Comment by tsadovska** [comment]
Issue is reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet] with the scenario from the description.


![Screenshot 2023-09-14 at 23 03 52](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2df2383b-e544-4d64-83c8-d38fac2fe73c)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with the scenario from the description.

**Comment by AigaD** [comment]
Issue is reproduced from: https://deploy-preview-1014--wormhole-connect.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9ee4a081-4ea6-49ba-badd-79d92c847b5c

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when with the following scenario:
1. Prepare to send 0.2 CELO from Alfajores (Metamask) to Osmosis (Leap)
2. Change CELO to WBTC

**Comment by AigaD** [comment]
Issue is reproducible from: https://preview.portalbridge.com/7102d8ccad/
Attachment:

![Screenshot 2023-12-19 at 11 55 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e455251c-0659-4f39-a99c-cb3a3a5ea439)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] with the scenario from Oct 10, 2023:

1. Prepare to send 0.2 CELO from Alfajores (Metamask) to Osmosis (Leap)
2. Change CELO to WBTC in "To" section
3. Click "Approve and proceed with transaction" button

![Screenshot 2024-02-29 at 19 17 34](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e155d896-b291-4e96-9c6b-66853fab5871)

**Comment by tsadovska** [comment]
Reproducible on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ikdxQWM3PYLCG5MRQEEAai4AadsAF8QvkA) with following scenario:
1. Prepare to send 0.001 AVAX from Avalanche (MetaMask) to Osmosis (Leap)
2. Click on Asset field in 'To' section
3. Switch to 'All tokens' tab
4. Select WBTC
5. Check if WBTC asset is displayed in 'To' section
6. Check if 'Approve and proceed with transaction' button is displayed

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6f6db340-d1ff-4ecd-b653-e3de2d03bcb3)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZEQL5A%3D%3D) (Connect v2). User can't select an asset that is not available for the route.
* Portal Bridge: Asset is automatically changed to the previously selected asset.
* Wormhole-connect: "All tokens" tab is not displayed and user can select asset only from "Select a token" list. 

Ticket is closed.
