### ISSUE TITLE
[QA] "View on Wormhole Explorer" link is not displayed on Redeem screen

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#936]
## Describe the current behavior in detail
"View on Wormhole Explorer" link is not displayed on Redeem screen.

Builds - Tested NOK:

- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]
- https://cctp--wormhole-connect.netlify.app/ [Mainnet]

Steps:
1. Open Menu -> Resume transaction
2. Search for transaction hash `0x1f5b4c0227fad84c7a136e6372cf93cc709d933e554bbf54addf98a24567f593` in Ethereum network
3. Observe if "View on Wormhole Explorer" link is shown

![Screenshot 2023-09-08 at 17 07 07](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a9627ad3-ddba-4406-a194-9b7275e04e5e)

Issue is also reproducible when:
- Sending USDC from Avalanche to Optimism, (Send from tx: [Snowtrace](https://snowtrace.io/tx/0x7da468562b310723b54cc8d4a89b3cd7a77b9339186f4c5203e42b78a051b6b1), pay with two transactions option was selected in Route section)
- Sending USDC from Arbitrum to Avalanche, (Send from tx: [Arbitrum](https://arbiscan.io/tx/0xd0bb3590e272aa9e036289bcd6498cca08ff803aa9baa27bc6b15b1e3b8c3335), pay with two transactions option was selected in Route section) 
- Sending USDC from Goerli to Fuji, (Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x413058e30902610909f9109e53ceb2853cd6208509cc1c423be06b35e356b38a), pay with two transactions option was selected in Route section) 

Issue is not reproducible when sending USDC from Avalanche to Optimism, (Send from tx: [Snowtrace](https://snowtrace.io/tx/0xf8bbdf0802e59e98566c094bc15ffa69da16af9a67b701f74441bef69f98fdfa), pay with one transaction option was selected in Route section)

## What is the expected/desired behavior
"View on Wormhole Explorer" link is displayed on Redeem screen.

**Comment by derpy-duck** [comment]
Oh this is intentional - there is no 'Wormhole VAA' to be shown in the wormhole explorer for this transaction since it is entirely done through Circle
