### ISSUE TITLE
[QA] Asset disappears in "To" section after asset is changed in "From" section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#938]
## Describe the current behavior in detail
Asset disappears in "To" section after asset is changed in "From" section.

Builds - Tested NOK:

- https://cctp--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]

Checked from macOS version 12.6.7 with Google Chrome Version 116.0.5845.140 (Official Build) (x86_64).

Steps:
1. Connect Metamask wallets in "From" and "To" sections
2. Prepare to send 0.1 CELO from Celo to Arbitrum
3. Change Asset in "From" section to APT
4. Observe if Asset in "To" section is displayed

 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3f7556df-c959-4c0e-a992-69323a6de5bf

 
## What is the expected/desired behavior
Asset in "To" section should be displayed after user changes asset in "From" section.

**Comment by AigaD** [comment]
The same issue is reproducible also if Network is being changed.
Tested from: https://cctp-testnet--wormhole-connect.netlify.app/# and https://cctp--wormhole-connect.netlify.app/#
In the attachment:
1. Prepare to send AVAX from Fuji (Metamask) to Arbitrum (Metamask)
2. Change Network from Avax to Moonbase
3. Observe Asset section
4. Select GLMR asset at sending From section
5. Observe asset section at sending To section

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/224e2ccf-b4c2-48d2-80f9-ecf79b3ba26f

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1005--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ddc596a7-0332-43ac-b408-e2e749509c86

**Comment by AigaD** [comment]
Issue is also reproducible from: https://deploy-preview-1014--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9f4d6f0-d336-478b-bf53-24e1d7df6c18

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Asset disappears in To section after it is changed in From section.

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] with following scenario:
1. Prepare to send 0.06 GLMR from Moonbeam (Metamask) to Base (Metamask)
2. Change GLMR asset to WMATIC
3. Observe if WMATIC asset is present in To section

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Asset disappears in To section after it is changed in From section.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet].


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ac84b980-6935-4ac5-b5b5-5ec7a3f12adc

Ticket is closed.
