### ISSUE TITLE
[QA] Bitget wallet icon is missing

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#939]
## Describe the current behavior in detail
BitKeep/ Bitget wallet icon is missing.

Builds - Tested NOK:
- https://cctp--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet]
- https://wormhole-connect.netlify.app/ [Testnet]

Checked from macOS version 12.6.7 with Google Chrome Version 116.0.5845.140 (Official Build) (x86_64)

Steps:
1. Connect Aptos network in From section
2. Click "Connect wallet" button 
3. Observe BitKeep wallet icon

![Screenshot 2023-09-08 at 20 03 29](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d16bc1ca-5498-41a7-ae25-b77a9f9fbc82)

## What is the expected/desired behavior
BitKeep/ Bitget wallet icon is displayed.

**Comment by AigaD** [comment]
Reproduced from https://feature-configurable-routes--wormhole-connect.netlify.app/ and https://cctp--wormhole-connect.netlify.app/
Bitkeep icon is "broken" and Install (Sei) and Install (Aptos) missing wallet icon and full name of the wallet
Attachment:
<img width="1132" alt="Screenshot 2023-09-12 at 09 15 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/488c0e0d-b401-40b7-b1ae-7d7e83e407d8">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet]. BitKeep wallet icon is not displayed.


![Screenshot 2023-09-15 at 11 12 28](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1f2ca2b5-4bf3-435c-a9d3-6f0497acf2b1)

**Comment by AigaD** [comment]
Issue still reproducible from: https://deploy-preview-1005--wormhole-connect.netlify.app/
Attachment:
<img width="1028" alt="Screenshot 2023-09-19 at 08 34 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/543bf269-fd16-40d6-bbac-1407a093102d">

**Comment by AigaD** [comment]
Same reproduced from: https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/#

Attachment:
<img width="996" alt="Screenshot 2023-09-20 at 16 57 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3f9b8f4b-2514-426a-acb1-ff15e0d9537d">

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1014--wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet].

**Comment by AigaD** [comment]
Issue is reproducible from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/

**Comment by AigaD** [comment]
Environment: MacBook Pro, macOS Ventura 13.0.1, Firefox Version 115.0
Tested from: https://wormhole-connect.netlify.app/#
Bitkeep wallet icon is missing, the naming overlaps with each other under wallet list
Attachment:
![Screenshot 2023-12-04 at 10 55 33](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3129bf54-463f-4be9-904b-d3a9df439753)

**Comment by AigaD** [comment]
Closing.
Tested OK.
Bitget wallet icon is shown.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/#

Attachment:

![Screenshot 2024-02-14 at 10 36 03](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fdf51f0d-50b1-4af7-93bb-39bafbf81367)
