### ISSUE TITLE
[QA] User cannot switch to One transaction in Route section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#942]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-testnet--wormhole-connect.netlify.app/ 

Steps:
1. Prepare to send 0.01 GLMR from Moonbase to Goerli
2. Expand the Route section
3. Try to select "One transaction"
4. Observe

Actual result: User is not able to select One transaction, it switches back to Two transactions

Expected result: User is able to select One transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/eb6f8fab-1597-41b9-9bab-28a7b4674cd7

**Comment by AigaD** [comment]
The same behaviour also reproduced for SUI -> Goerli transaction

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e0897c7d-663a-4122-8cb7-76dcd84e01d0

Cannot test from Mainnet due to high minimum amount 
<img width="1133" alt="Screenshot 2023-09-11 at 14 03 07" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0e7f6abd-8c0c-4336-b0bb-ebe43649e3a0">

**Comment by AigaD** [comment]
Reproducible from: https://feature-configurable-routes--wormhole-connect.netlify.app/# 
For transaction 0.02 AVAX from Fuji-> Moonbase user cannot select One transaction option

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bd754250-5230-45c1-85fd-fbffce3f22fd

**Comment by tsadovska** [comment]
Tested OK on https://latest--wormhole-connect.netlify.app/ [Mainnet]. One transaction option is not displayed or it can be selected. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e9c09895-530d-4d9d-9f07-235ad9ef21e6

**Comment by tsadovska** [comment]
Tested OK on https://cctp-only--wormhole-connect.netlify.app/ [Mainnet] one transaction option can be successfully selected when user prepares to send 30 USDC from Ethereum (Metamask) to Optimism (Metamask) and switches between Route options. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/90e3c909-dc14-418f-ba39-d7d0b9c83f2d

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] when sending 0.49 SOL from Solana (Phantom) to Sui (Sui wallet). User is not able to select One transaction, it switches back to Two transactions.

Error is displayed in Console:
```
Uncaught (in promise) Error: Unable to calculate nativeSwapAmountOut
    at t.SuiRelayer.calculateNativeSwapAmountOut (main.6f254be4.js:37:18209934)
    at async p.calculateNativeTokenAmt (main.6f254be4.js:37:18204363)
    at async oa (main.6f254be4.js:37:19684907)
    at async main.6f254be4.js:110:33160
```


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d273871f-ba6f-4b33-ae59-340379c803e7

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
When sending 0.1 MATIC from Mumbai to Moonbase, user tries to select One transaction under Routes
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5d8a640f-d85c-4572-b1e1-78f9f2ea813b

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.01 AVAX from Fuji (Metamask) to Moonbase (Metamask). User is not able to select "Automatic Deposit, One transaction" option in Route section. It switches back to "Bridge, Two transactions". Error is displayed in Console:

```
Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x9563a59C15842a6f322B10f69d1dD88b41f2E97B","data":"0x8e151dd10000000000000000000000002e8afecc19842229358f3650cc3f091908dcbab40000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"VM Exception while processing transaction: revert swap rate not set\",\"data\":\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000\"},\"id\":159}","error":{"code":-32603,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x9563a59c15842a6f322b10f69d1dd88b41f2e97b\",\"data\":\"0x8e151dd10000000000000000000000002e8afecc19842229358f3650cc3f091908dcbab40000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":159,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.api.moonbase.moonbeam.network"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at l.makeError (main.624ce4e7.js:37:3857993)
    at l.throwError (main.624ce4e7.js:37:3858113)
    at y (main.624ce4e7.js:37:3915009)
    at c.<anonymous> (main.624ce4e7.js:37:3925193)
    at Generator.throw (<anonymous>)
    at s (main.624ce4e7.js:37:3914340)
```

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.5 SUI from Sui (Sui wallet) to Alfajores (Metamask). User is not able to select "Automatic Deposit, One transaction" option in Route section. It switches back to "Bridge, Two transactions". Error is displayed in Console:
```
Uncaught (in promise) Error: call revert exception; VM Exception while processing transaction: reverted with reason string "swap rate not set" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="calculateNativeSwapAmountOut(address,uint256)", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011737761702072617465206e6f7420736574000000000000000000000000000000", errorArgs=["swap rate not set"], errorName="Error", errorSignature="Error(string)", reason="swap rate not set", code=CALL_EXCEPTION, version=abi/5.7.0)
    at l.makeError (main.85265285.js:37:3857993)
    at l.throwError (main.85265285.js:37:3858113)
    at A.decodeFunctionResult (main.85265285.js:37:3719894)
    at E.<anonymous> (main.85265285.js:37:3756107)
    at Generator.next (<anonymous>)
    at i (main.85265285.js:37:3751594)
```

**Comment by evan-gray** [comment]
I think this relay contract might be misconfigured - that aside, the front-end should be indicating this to the user.

**Comment by aadam-10** [comment]
on error messages:

1. we should map as many errors as we can to human readable strings and show them on the frontend when that error happens
2. errors that are not mapped to a specific string should be mapped to a default one such as "An unexpected error occurred, please contact [support](https://discord.gg/wormholecrypto)", **and** in those cases the banner should also show the console error string in small font somehow

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Cannot switch to One transaction Route for transaction SUI from Sui to Base Goerli

Attachment:

![Screenshot 2023-10-12 at 10 42 22](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/10fa05b4-2f3a-4175-b090-9b1b6474eab8)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d7c585ae-1f46-4761-89fd-cf89a81a23f5

**Comment by tsadovska** [comment]
The following scenarios are no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet], user can switch to one transaction option in Route section:
* Send GLMR from Moonbase to Goerli - Only "Two transactions" option is available in Route section
* Send SUI from Sui to Goerli 
* Send AVAX from Fuji to Moonbase 
* Send SOL from Solana to Sui 
* Send MATIC from Mumbai to Sui
* Send SUI from Sui to Alfajores
* Send SUI from Sui to Base Goerli 

Checked following scenarios on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* Send AVAX from Avalanche to Moonbeam - Only "Two transactions" option is available in Route section
* Send USDC from Ethereum to Optimism - User can switch to One transaction option

Ticket is closed.
