### ISSUE TITLE
[QA] Received asset is not shown in TX explorer link

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#943]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-testnet--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.02 FTM from fantom to Arbitrum
2. Click Approve and proceed with transaction
3. Wait till transaction is finished
4. Click on Arbitrum Goerli Explorer link
5. Observe if the value for received asset is shown
6. Open https://testnet.arbiscan.io/ and paste in your wallet address ( 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01 )
7. Observe last transactions received in the wallet

Actual result: Link to Arbitrum scan TX hash could not be located for first transaction, for second transaction amount received is not showing. If searched through https://testnet.arbiscan.io/address/0xd493066498ace409059fda4c1bcd2e73d8cffe01#tokentxns values that were received are shown as 30,000,000,000,000,000 (screenshot attached)

Expected result: TX link to explorer is opened and received values are accurately shown

Attachment:
TX link to first transaction: https://testnet.arbiscan.io/tx/0xc35315eccdc724f5d1e473af2258d4071c0dfa5b7b99ce01d207d14e66d1a685

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d46bf2a9-af40-40e0-8dec-1317dd632133

TX link to second transaction: https://testnet.arbiscan.io/tx/0xbe0ed8e97e1c1a857494b2b376d6671a474daad694daa73789649caec1833a05

<img width="1407" alt="Screenshot 2023-09-11 at 10 35 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c98e8e76-9e27-466c-82fb-8b0e8b4c5f82">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]:
* Link to Arbitrum Goerli Explorer is opened
* Correct amount and asset are shown 

Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0xf506748701b925400ad319f55d94ed342f55f649813116382151a9f0ce60736d)
Send to tx: [Arbiscan](https://testnet.arbiscan.io/tx/0xfadf6e69fc10c67ff85e2dabb8ca12837d75051017a27126eb8c72d9f267d5ec)

![Screenshot 2023-10-10 at 19 14 56](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a8c3a81b-73c7-4c12-af58-448edc1f6c75)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a582567f-a113-4dd1-8c42-8a0b2db9fe59)

Ticket is closed.
