### ISSUE TITLE
[QA] Claiming fails with "invalid emitter" error

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#944]
## Describe the current behavior in detail
Claiming fails when sending WETH from Osmosis to Arbitrum Goerli.

Checked on https://cctp-testnet--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Connect Leap wallet in From section
2. Connect Metamask wallet in To section
3. Prepare to send 0.0001 WETH (Goerli) from Osmosis to Arbitrum Goerli
4. Click "Approve and proceed with transaction" button
5. Click Claim button on Redeem screen

Send from tx: [Mintscan](https://testnet.mintscan.io/osmosis-testnet/txs/4ABD2E68752B52E8FA9BE400957C24C9D51116DBBC5DB77CD0EF91A18FBD6654)

Error is displayed in Console:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000", errorArgs=["invalid emitter"], errorName="Error", errorSignature="Error(string)", reason="invalid emitter", code=CALL_EXCEPTION, version=abi/5.7.0)
    at f.makeError (main.14eb17a0.js:37:4721120)
    at f.throwError (main.14eb17a0.js:37:4721240)
    at A.decodeFunctionResult (main.14eb17a0.js:37:4583021)
    at Object.<anonymous> (main.14eb17a0.js:37:4619234)
    at Generator.next (<anonymous>)
    at a (main.14eb17a0.js:37:4614721)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/946ec431-fc83-4f43-bb8c-cd611d2ed71a)

Note: Issue is not reproducible on https://cctp--wormhole-connect.netlify.app/ [Mainnet] with the same scenario. User can successfully send and receive WETH (Ethereum) asset ([Osmosis](https://www.mintscan.io/osmosis/transactions/F43461B7E12BEB6D7BF92D92A2842D101B1EE0D0B3FD462DE230959A44E541F1), [Arbitrum](https://arbiscan.io/tx/0x407a2eb9cecd238a0fe493d602308da98eb8f49986896742f642ec1ffc343f75)).

## What is the expected/desired behavior
Asset is successfully sent and received.

**Comment by tsadovska** [comment]
Blocked by #778. Transaction is not starting, "Error: Chain is not cosmos chain" appears in Console when user sends 0.001 WETH from Osmosis (Leap) to Arbitrum Goerli (Metamask).

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
For transaction 0.01 USDC (Arbitrum) from Cosmoshub to Arbitrum Goerli, transaction fails at Claim. Error in console indicates `Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" `

Attachment:
![Screenshot 2023-10-18 at 17 04 55](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/857c8254-1715-45ca-8678-896aacd2b16c)

Transaction 0.001 WETH (Optimism) from Cosmoshub to Optimism

![Screenshot 2023-10-18 at 17 21 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9bc0bfa0-5e38-4768-84e3-bc008aeaf19f)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction 0.0001 WETH (base) from Cosmoshub to Base Goerli, transaction fails at Claim, reason `main.3e3e9754.js:190 Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" `

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6138265d-a6aa-4f32-be4d-9259aec928fd

**Comment by tsadovska** [comment]
Original scenario will be rechecked after #1111 is resolved.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/7102d8ccad/ [Mainnet] when sending 0.011 USDC from Polygon (Metamask) to BSC (Metamask). Claiming fails with error:
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000", errorArgs=["invalid emitter"], errorName="Error", errorSignature="Error(string)", reason="invalid emitter", code=CALL_EXCEPTION, version=abi/5.7.0)
    at f.makeError (main.js:2:2341430)
    at f.throwError (main.js:2:2341550)
    at A.decodeFunctionResult (main.js:2:2203556)
    at Object.<anonymous> (main.js:2:2239544)
    at Generator.next (<anonymous>)
    at a (main.js:2:2235031)
```
Transaction is successfully completed after user clicks on Claim button again. 

![Screenshot 2023-12-18 at 18 52 38](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f953b201-1ca7-4182-b669-fe15dc889053)

**Comment by AigaD** [comment]
Blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/1111 / https://github.com/wormhole-foundation/wormhole-connect/issues/1238 / https://github.com/wormhole-foundation/wormhole-connect/issues/1143
