### ISSUE TITLE
[QA] Transaction from Solana fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#945]
Preconditions:
1. Metamask wallet connected
2. Solflare/Phantom wallet connected
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-testnet--wormhole-connect.netlify.app/ - Tested NOK
https://cctp--wormhole-connect.netlify.app/# - Tested OK

Steps:
1. Prepare to send 0.02 SOL from Solana to Goerli
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xbc0`

Expected result: Transaction moves forward and is completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ce5472f7-112b-4b6f-a9cb-f4d4cde5f932

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1b3871d0-5249-4694-b62d-cf9b4eb209f8

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-907--wormhole-connect.netlify.app/#
Transaction from Solana (Nightly) to Mumbai (Metamask) fails, reason `WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4`
Nightly wallet was tested both when switched to Testnet and Devote
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b89d1a3-36a9-43c1-9798-1945ec584443

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]. 
Scenarios - Tested OK:
* Send SOL from Solana to Ethereum ([Solana](https://explorer.solana.com/tx/4zCEVyXvM93iQsGfKuk2WUFHRyj3T2Gx9oMRnwbN815FGfS6tYVBbucy971T6hzoWKUwDwDg8zeZEvgFpXJX7kCN), [Ethereum](https://etherscan.io/tx/0xe522db2609997793ab791f4e357f36857de04bc02d7eb91765a4db11cf3ce419))
* Send SOL from Solana to Polygon ([Solana](https://explorer.solana.com/tx/5pvxTjjA2DTmM9KXCRp3c5Snq3bgyszcWW1a7XKwvpdA4w6yFK4RLyLoL1ATAjo3XuRVh4J4z9TCBYSgq2gGntnF), [Polygon](https://polygonscan.com/tx/0xc6c3a67ba063ff368150bd5cf154000b9659be7e9cda352a3c862d1ee56cfc51))
* Send BONK from Solana to BSC ([Solana](https://explorer.solana.com/tx/4MCfFG6TVJpyiZV4ViWihBy3T8YghAVVYE3U8fgsW5wqn7uKVaPzknTE4Mk6zChcbH1uus1QBEyyShSa6a4SxMVN), [BSC](https://bscscan.com/tx/0xb2eea93c6f57731ab524afaec356eb589358debd40920b8e4276524eecd3ba97))

**Comment by AigaD** [comment]
Reopening the ticket.
Issue is reproducible from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Steps:
1. Send 0.06 SOL from Solana to BSC/Moonbeam
2. Select One transaction route
3. Add some Native gas
4. Click Approve and proceed with transaction

Attachment:
<img width="1356" alt="Screenshot 2023-09-26 at 17 57 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/87303e67-93a2-49e7-ab9e-9e35c5cc0928">


<img width="1314" alt="Screenshot 2023-09-26 at 17 50 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c86539b4-2850-499e-8697-98bbea0ec6c2">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4d4648b7-2960-40f0-a51a-15c314f49a96

**Comment by kev1n-peters** [comment]
I was not able to reproduce this issue: 

solana -> celo (phantom wallet): https://explorer.solana.com/tx/2x1HP58teKmEYEZNTvQ9wnQEB3XLA8cD5phAqzuQKd6YHzdhkuMo16za6EQKsrB6a2G3s3QhxRh52qnhcFeT34xK

solana -> moonbeam (solflare wallet):
https://explorer.solana.com/tx/5SfLa8LGDReWM3pGWNXCpEzcodnW4KtGQW3yMe5VgG67veK53L2uPJqjVy3nmeLnd8jDtqqegcyEoKMpv1XZkFEb

**Comment by AigaD** [comment]
Closing. Transaction failed, because there were not enough funds for the receiving network for gas payment.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/40db5841-7740-49fd-9c99-6b54d0505425
