### ISSUE TITLE
[QA]Tokens are not shown when Aptos Network is selected

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#946]
Preconditions:
Aptos supported wallet available

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-testnet--wormhole-connect.netlify.app/# - Tested NOK
https://cctp--wormhole-connect.netlify.app/# - Tested NOK

Steps:
1. Click on Select Network
2. Select Aptos
3. Connect Aptos supported wallet
4. Open asset list
5. Observe Available and All Tokens sections

Actual result: None of the tokens are showing in either Available tokens or All Tokens

Expected result: Tokens are showing in the asset list

Comments: Linking this issue to show that previously tokens were present in the asset list when Aptos was selected - https://github.com/wormhole-foundation/wormhole-connect/issues/929#issue-1885753456

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aa73ed65-a576-43b6-b273-5b33f7c10e08

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a172008-42cf-40f9-abc0-7a6422b7e51d

**Comment by AigaD** [comment]
Same behaviour reproduced from: https://deploy-preview-1005--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/de0efd4b-6299-4d08-ae8a-12b1e107b301

**Comment by AigaD** [comment]
Issue is also reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/ and https://wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/39a92508-ab05-4d64-8b23-400f62dd026f

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet]. Tokens are not shown in "Available tokens" and in "All tokens" tab. 

![Screenshot 2023-09-26 at 15 16 16](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3e6819e1-3b26-45e2-9b72-3c682f24762c)

**Comment by AigaD** [comment]
Balance for assets when Aptos network is selected are not loading.
Tested from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/57e5bbaf-5342-4b03-a0ef-6cb76be2e1d5

**Comment by AigaD** [comment]
Closing. Tested OK.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb829dc6-7a8a-41ba-a941-34b76e0e80bd


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9c0f462d-4e6c-4fec-a368-7641ea88fcc9
