### ISSUE TITLE
[QA]Cannot move slider for Native Gas

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#950]
Preconditions:
Metamask walet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/ - Tested NOK
https://cctp--wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Prepare to send 0.106 MATIC from Mumbai to BSC
2. Select One Transaction
3. In Native Gas section try to change the sliders position 
4. Observe

Actual result: User cannot move the slider at Native Gas section

Expected result: Slider can be moved to any position 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4ece04a4-1892-4cd5-9f27-0aad63a2f643

**Comment by tsadovska** [comment]
Issue is also reproducible on https://feature-configurable-routes--wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select Goerli network in From section
2. Select Arbitrum Goerli in To section
3. Connect Metamask wallets in From and To sections
4. Prepare to send 0.11 USDC (Goerli) 
5. Open Native gas section and change slider position
6. Change Amount value to 0.001 USDC
7. Change Amount value to 0.11 USDC again
8. Change slider position in Native gas section


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9f210c9e-31c1-482b-bcc5-08e8de258f42

**Comment by tsadovska** [comment]
Tested OK on builds:
- https://latest--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-only--wormhole-connect.netlify.app/ [Mainnet]

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with following scenario:
1. Select BSC in From section
2. Select Solana in To section
3. Connect Metamask in From section
4. Connect Slope in To section
5. Select WSOL asset
6. Enter Amount 0.01
7. Change slider position in Native gas section

Note: Warning "No bridge or swap route available for selected tokens" was shown for a brief moment. 




https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b1bf26fb-da6e-408c-8de4-ee5f51d57766

**Comment by AigaD** [comment]
Issue is reproducible from: https://deploy-preview-1005--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7230e1d5-80c7-4c8c-9532-ed476a8d5fc4

**Comment by AigaD** [comment]
Cannot move slider for Native gas if amount entered is the minimum needed for One transaction in Routes
In example minimum amount needed for One transaction is 2.1 USDC - The Native gas slider cannot be moved. If the amount is changed to 2.2 USDC, the Native Gas slider can be moved.
Tested from: https://deploy-preview-1005--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5bcfd83a-db14-4c6d-b4f2-0ff2040c7541

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/#
Cannot move slider if minimum amount needed for One transaction is 2.1 USDC 
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/081da81b-2ad7-4795-ab71-f31f50db56ad

**Comment by derpy-duck** [comment]
Note on this - the reason that the slider can't move is that it is determined that the 'max swap amount' in this scenario is 0 (which I believe it is supposed to be). 

A fix would look like probably auto-hiding + disabling the native gas slider in such scenarios

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1014--wormhole-connect.netlify.app/ [Testnet] when sending 0.105 MATIC from Mumbai (Metamask) to BSC (Metamask). 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/de00a909-de43-49f1-907a-eee1e761b925

**Comment by aadam-10** [comment]
> Note on this - the reason that the slider can't move is that it is determined that the 'max swap amount' in this scenario is 0 (which I believe it is supposed to be).
> 
> A fix would look like probably auto-hiding + disabling the native gas slider in such scenarios

confirmed that this should be the behavior, should be implemented

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] when sending 0.053 SOL from Solana (Phantom) to Base (Metamask).

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.000649 ETH from Ethereum (Metamask) to Solana (Phantom).

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/afc11596-65cb-4051-9541-b375c6042e40

Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when trying to send 0.0000009 ETH from Goerli (Metamask) to Solana (Phantom).


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8c43d651-5574-44c9-b8b9-5a215e07bf21

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/#
User cannot move slider when sending 1.2 USDC till 1.6 USDC from Base to Arbitrum,
If the amount entered is 1.9 USDC, user can change the Native gas slider and if then the amount is lowered till 1.2 USDC the the Native gas slider can be also changed
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/425880c5-c689-4344-91a6-125cfaeae17a

**Comment by AigaD** [comment]
No longer reproduced. Closing.
Tested from: https://wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect.netlify.app/#
Attachment:

<img width="1030" alt="Screenshot 2023-10-30 at 16 16 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/30ffff8e-02f2-45a5-a1aa-a74648c2fbf4">

<img width="1072" alt="Screenshot 2023-10-30 at 16 15 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0985e24f-ce2e-4324-8b25-c64dfba55544">

<img width="1022" alt="Screenshot 2023-10-30 at 16 06 02" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9e42fa10-dc30-4234-885b-123ccaad8283">
