### ISSUE TITLE
[QA]Page goes white if user searches for wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#951]
Preconditions: No fields are filled in

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/ - Tested NOK
https://cctp--wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Refresh the page
2. Click on Connect Wallet
3. Start typing e.g. Metamask in search window
4. Observe

Actual result: Page goes white when searching wallet

Expected result: Wallet is found

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d5df9579-c1c2-4603-817e-61ba252d7004

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a59bcbbd-f717-47f6-8397-030635f58bea

**Comment by tsadovska** [comment]
Reproducible from https://cctp-only--wormhole-connect.netlify.app/ [Mainnet].


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e835bfc9-f475-4a1e-b996-d1d2ed5936c0

**Comment by AigaD** [comment]
Reproducible from: https://latest--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/258caea5-ca70-40b2-a7cb-689565d0156f

**Comment by tonyjin** [comment]
<img width="1710" alt="Screenshot 2023-09-14 at 4 08 41 PM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/689351/22827ea7-4be4-4d28-95e7-5461adad211b">

I can also reproduce on https://cctp-only--wormhole-connect.netlify.app/. Attached screenshot of JS error.

I cannot reproduce on https://mainnet--wormhole-connect.netlify.app/, so I'd consider this a regression.

**Comment by AigaD** [comment]
Reproducible from: https://deploy-preview-907--wormhole-connect.netlify.app/

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/79c03c82-ab03-47b6-896d-433d7feb2f00

**Comment by tonyjin** [comment]
Confirmed #980 resolved tested via https://deploy-preview-980--wormhole-connect-builder.netlify.app/
