### ISSUE TITLE
[QA]User cannot open Native gas section on first try

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#953]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.01 ETH from Goerli to Mumbai
2. Observe that One transaction is active
3. Navigate to Native gas section
4. Try to open the section

Actual result: Native gas section cannot be opened even if user is on One transaction Route. User has to switch to Two transactions and back to One transaction in order to be able to access Native gas

Expected result: Native gas section is available when user is on One transaction Route

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e5555b2d-c5c4-42f8-a541-be8eff495467

**Comment by tsadovska** [comment]
Issue is not reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet].


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/662b566e-2e09-404c-a797-551311aa2612

**Comment by tsadovska** [comment]
Tested OK on https://cctp-only--wormhole-connect.netlify.app/ [Mainnet] with a similar scenario. 

Steps:
1. Prepare to send 30 USDC from Ethereum to Optimism
2. Observe that One transaction is active
3. Navigate to Native gas section
4. Try to open the section

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7282ce64-3a7b-4e9c-9167-23fc22ffc5a8

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Ticket is closed.
