### ISSUE TITLE
[QA]Sei wallets are not shown in Connect Wallet although Sei Network is available

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#954]
Preconditions:
Sei wallets enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/

Steps:
1. Click on Select Network
2. Select Sei
3. Click on Connect Wallet
4. Observe

Actual result: Sei wallets are not shown in the list although Wallets are enabled

Expected result: Sei should be removed if it is not supported yet - https://github.com/wormhole-foundation/wormhole-connect/issues/931#issue-1885929961 "Sei not supported officially in Connect yet" 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/73e3441b-9ac2-4c7b-859a-009eef63c74f

**Comment by AigaD** [comment]
Reproduced also from: https://deploy-preview-907--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cfb2ef6b-5aa7-4e83-8430-a00d79d5a608

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Sei Network is present, but wallets are not

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet].

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Sei wallets are shown on Connect wallet screen.

Remaining issue: [Mainnet] Sei wallets should not be shown on "Connect wallet" screen if chain is not configured, #931. 
Ticket is closed.
