### ISSUE TITLE
[QA] Can not switch to manual claim transfer

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#956]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp--wormhole-connect.netlify.app/# and https://feature-configurable-routes--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.0001 USDC (Arbitrum Goerli) to Goerli
2. Observe that message "Minimum amount is 1.05 for single transaction automatic transfers
3. Switch to a manual claim transfer?" is shown
4. Click on "Switch to a manual claim transfer?"
5. Observe

Actual result: User cannot switch to manual claim transfer

Expected result: User can switch to manual claim transfer

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8c39620f-26d8-4fd6-aa09-8c5bf53d4894

**Comment by tsadovska** [comment]
Tested OK on:
- https://latest--wormhole-connect.netlify.app/ [Mainnet]
- https://cctp-only--wormhole-connect.netlify.app/ [Mainnet]

Minimum amount warning message is no longer displayed.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Minimum amount warning message is no longer displayed.
Ticket is closed.
