### ISSUE TITLE
[QA] Page glitch when Automatic Deposit-One transaction is chosen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#963]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.001 MATIC from Mumbai to Moonbase
2. Go to section Routes
3. Expand the Routes section
4. Select Automatic Deposit - One transaction
5. Observe

Actual result: Whole page starts to glitch

Expected result: User is able to select Automatic Deposit - One transaction and continue with transaction

Comments: Perhaps this could be connected with the warning message glitch - https://github.com/wormhole-foundation/wormhole-connect/issues/952#issue-1892054223

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a925a44-0cdd-4ec8-beac-8bcba75fc11e

**Comment by tsadovska** [comment]
Tested OK on https://latest--wormhole-connect.netlify.app/ [Mainnet] and https://cctp-only--wormhole-connect.netlify.app/ [Mainnet]. Minimum amount warning message is no longer displayed in these builds. User can successfully select "One transaction" or "Two transactions" option in Route section and switch between them.
