### ISSUE TITLE
[QA] Incorrect amount is shown in 'To' section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#964]
## Describe the current behavior in detail
Negative amount is shown in 'To' section.

Checked from https://feature-configurable-routes--wormhole-connect.netlify.app/ [Testnet] with macOS 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Goerli network in From section
2. Select Arbitrum Goerli in To section
3. Connect Metamask wallets in From and To sections
4. Prepare to send 5 USDC 
5. Change slider position in Native gas section
6. Change Amount to 1 USDC
7. Observe Amount value in To section

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f7f11eb4-6aec-4cf2-93ac-4ce9cf434507

<img width="639" alt="Screenshot 2023-09-13 at 12 35 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2fac5524-24a9-4c6f-99b4-494fadfb58f1">

## What is the expected/desired behavior
Correct amount value is shown.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet]. Correct amount is shown in To section.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/90ff1b1c-cbd1-41ea-8a01-8493909602bf

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with the scenario from the description.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f2a8a77e-06bf-4a91-a94a-7067d181cf67)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet]. A negative amount is shown in "To" section after user changes amount.

Scenario:
1. Prepare to send 6.6 USDC from Avalanche (Metamask) to Optimism (Metamask)
2. Expand native gas section
3. Change slider position
4. Change Amount to 3 USDC
5. Observe


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/abf2802c-ca69-45b0-ab15-a2498e79b5f7

**Comment by tsadovska** [comment]
Issue is also reproducible when amount that exceed balance is entered. Checked on https://preview.portalbridge.com/a220b5e9bf/usdc-bridge/ [Mainnet].

Steps:
1. Prepare to send USDC from Arbitrum (Metamask) to Ethereum (Metamask)
2. Enter Amount 42 USDC
3. Observe Amount value in "To" section


![Screenshot 2023-09-20 at 14 55 11](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c578f2c1-55b9-4a76-b2c1-1bced4ea1a45)

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet]. A negative amount is shown in "To" section after user changes amount.

Steps:
1. Select Ethereum as source chain
2. Select  Base as destination chain
3. Connect Metamask wallets in From and To sections
4. Select USDT asset
5. Enter Amount 7 USDT
6. Change slider position in Native gas section
7. Change amount to 4 USDT


![Screenshot 2023-09-26 at 13 16 17](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/255e60a7-bc2f-40b9-81d6-60b6e3343658)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when following scenario:
1. Prepare to send 5 USDC from Goerli (Metamask) to Arbitrum Goerli (Metamask)
2. Chage slider position in Native gas section
3. Change amount to 1 USDC


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/55bf0d1a-7915-4103-b097-f2f22d3c18b7)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] with following scenario:
1. Prepare to send 5 USDC from Ethereum (Metamask) to Base (Metamask)
2. Move slider to right most position
3. Change amount to 4 
4. Observe Amount in To section (actual result: -0.75)
5. Click "Switch to a manual claim transfer" link on Minimum amount warning message
6. Expand Route section
7. Observe Value after fees for "One transaction" option (actual result: -0.75)


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3eb31d49-48ab-4aea-83c0-0c446df140d4

**Comment by AigaD** [comment]
Reproduced for transaction 23 USDC from Goerli to Optimism with the steps from the main ticket.
User enters 23 USDC and then changes the amount to 1
Tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="934" alt="Screenshot 2023-11-02 at 11 23 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bcfc13b5-cf41-43a4-a6a1-dab98710322c">

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/
Negative amount is shown for a brief moment when changing the amount in from section
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0a6f9f4c-f99f-40ed-b440-4ba701084f2f

**Comment by artursapek** [comment]
also reproduced this. assigning to myself.

https://github.com/wormhole-foundation/wormhole-connect/assets/897596/8a8ab873-4d1f-43bb-83b0-24dc08d898b4

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with following scenario:
1. Prepare to send 2.625 USD (Arbitrum) from Arbitrum (MetaMask) to Base (MetaMask)
2. Change amount to 7.02 (can be copy-pasted)
3. Change slider position (in my case to right most position)
4. Change amount back to 2.625
5. Check amount in "To" section and in "Route" section



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/603cd22c-2acf-4e9f-ba56-8d1ba2ae4d90

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Managed to reproduce for transaction USDC from Base to Arbitrum

Attachment:

<img width="1045" alt="Screenshot 2024-04-12 at 12 46 48" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7b81ee73-a35a-4e71-9557-1f321338e5ce">

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ [Mainnet] with following scenario:
1. Prepare to send 4 USDC from Avalanche (MetaMask) to Optimism (MetaMask)
2. Change slider position to right most position
3. Change Amount to 2 
4. Check Amount in "To" section and in Preview section

Actual result: Negative value is shown, -1.799999. 

![Screenshot 2024-07-23 at 16 21 19](https://github.com/user-attachments/assets/ae2a4563-70ef-41f6-91c4-60e2a061d677)

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign, Amount is no longer displayed in "To" section. 

![image](https://github.com/user-attachments/assets/0fd4dfad-105e-44ed-88bc-4d795fc0d4f3)

Ticket is closed.
