### ISSUE TITLE
[QA] Asset is not received

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#965]
## Describe the current behavior in detail
USDC asset is not received.

Checked from https://feature-configurable-routes--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Open Menu -> Resume transaction
2. Search `0x4d9bd6d5ea77d74b5cca3a92c509861727ce5fe820c6a952fd60a2d477f0137a` in Goerli network (tx: USDC transfer from Goerli (Metamask) to Osmosis (Leap))
3. Click "Bridge more assets" button
4. Click Swap button
5. Connect Leap wallet
6. Open Asset list
7. Observe if USDC asset is received

* Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x4d9bd6d5ea77d74b5cca3a92c509861727ce5fe820c6a952fd60a2d477f0137a)
* Wormhole Explorer: [Wormholescan](https://wormholescan.io/#/tx/2/000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7/182166?network=TESTNET)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/30a1b697-6883-403b-89c0-f391e834ea62

## What is the expected/desired behavior
USDC asset is received.

**Comment by M-Picco** [comment]
@tsadovska Could you please check again? Sometimes there might be delays on testnet due to an inestable component.

**Comment by tsadovska** [comment]
@M-Picco Rechecked again the same transaction and still have not received USDC on Osmosis. 

Send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x4d9bd6d5ea77d74b5cca3a92c509861727ce5fe820c6a952fd60a2d477f0137a)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/29a5a248-289c-47b2-9467-0fcfc10329ae

**Comment by tsadovska** [comment]
Issue is not reproducible on https://cctp-only--wormhole-connect.netlify.app/  [Mainnet] for following transactions:

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ac0c82e3-d8f1-433b-a17e-9f4184768725)


Issue is not reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet] for following transactions:


![Screenshot 2023-09-15 at 00 01 18](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1fba3360-af84-4153-8383-b419c2faac46)

**Comment by tsadovska** [comment]
Rechecked issue on https://wormhole-connect.netlify.app/ [Testnet]. 
Scenario - Tested OK: Send 0.001 USDC from Goerli (Metamask) to Leap (Osmosis), send from tx: [Etherscan](https://goerli.etherscan.io/tx/0x8f907dedbad4abe8bdea7d66e18b58fffcb07b63b3ab73b064732fcbcd8fb135)

Remaining issues:
* Missing explorer link on destination chain, ticket #913
* Received asset is not displayed in "Available tokens" tab, ticket #1002 

Ticket is closed.
