### ISSUE TITLE
[QA]View on Wormhole Explorer link is present for route provided by Circle

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#977]
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-only--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.3 USDC from Ethereum to Avalanche
2. Click Approve and proceed with transaction
3. Wait until transaction is finished

Actual result: There should not be View on Wormhole explorer, if transaction is done through Circle - https://github.com/wormhole-foundation/wormhole-connect/issues/936

Expected result: View on Wormhole explorer link is not shown

Attachment:
TX - https://etherscan.io/tx/0xca31e7b5a139ab399ff68b3110beedf961eb7997dcce33ef6ec961536c101a43

<img width="1286" alt="Screenshot 2023-09-14 at 15 31 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bbf5c17a-0d79-4cde-b13d-4fd784b1140b">

<img width="1112" alt="Screenshot 2023-09-14 at 15 40 23" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/93a76941-7f06-416e-838c-f70cb69e7e4a">

**Comment by derpy-duck** [comment]
This is intended - for this route (automatic redeem CCTP), even though the transfer is a Circle transfer, there is a wormhole VAA powering the 'automatic redeem / gas dropoff' part - and this is the VAA shown in the explorer

**Comment by AigaD** [comment]
Closing as per comment
