### ISSUE TITLE
[QA] Contract address instead of wallet address was shown for the received asset in Step 2

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#978]
Preconditions:
Sui wallet connected at sending From section (0x94e1012fedb84ff3831e0ad94503efce6ea9f1650e2bdce3ccbdcaa65c0d53ed )
Metamask wallet connected at sending To section ( 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01 )

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from:  https://latest--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 1.94 SUI from Sui to Fantom
2. Select One transaction
3. Approve and proceed with the transaction
4. Wait until transaction is finished and observe wallet shown at Step 2

Actual result: Contract address was shown instead of Metamask wallet address (0xd493066498aCe409059fDA4c1bCD2E73D8cffE01) at Step 2

Expected result: Wallet address where asset is sent to should be shown

Attachment:
https://ftmscan.com/tx/0x258ca3388eeb94990995e7979e393484bff4364aa2ed67b5c79f0d00e2597b74

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7cae0397-f5f2-43be-bed5-43765dad0361

<img width="1177" alt="Screenshot 2023-09-14 at 17 17 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2adc7ce8-3c7a-49f4-9a96-a6ae633800a2">

<img width="1290" alt="Screenshot 2023-09-14 at 17 25 49" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/71a6fb60-b2c2-468a-b58e-4cea51bd1bb5">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/
Incorrect wallet address is shown at Sent To section.
Attachement:
<img width="1235" alt="Screenshot 2023-10-03 at 16 46 51" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c8203c45-cb5f-4d22-90f9-1e76681940a6">

**Comment by tsadovska** [comment]
Issue is also reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending WBNB from Sui (Sui wallet) to Polygon (Metamask) with automatic deposit.

Send from tx: [Sui explorer](https://suiexplorer.com/txblock/FkiGnE6DjNksaFFLM5bkS36KunFRcZYUDbJWcrhCSj6F)
Send to tx: [Polygonscan](https://polygonscan.com/tx/0xe941dcba0a77b16f7f25c2d7af762191162e26e0a7b7bf7cd8d4f2136d759e73)

![Screenshot 2023-10-03 at 17 29 55](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/47d3cb13-ce0c-4453-892a-9226dd41003d)

Correct account (0x9631...7012) is shown in "Send to" section on Redeem screen when sending WBNB from Sui (Sui wallet) to Polygon (Metamask) with "Two transactions" option.

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1057--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending SUI from Sui (Sui wallet) to Fantom (Metamask) with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/DAtEnPnFkE2TTtct88mcshAyAUXQipdnGUS65WXwyHVL), [FTMScan](https://ftmscan.com/tx/0x2f213447bbb798b939e2ba369c8af2edd82bbe8f5a4e7d600f90cffbf1acab23)).
Scenarios that are not checked yet due to insufficient SUI balance on Sui:
* Send SUI from Sui (Sui wallet) to Solana (Phantom) with automatic deposit
* Send WBNB from Sui (Sui wallet) to Solana (Phantom) with automatic deposit

**Comment by tsadovska** [comment]
Issue is not reproducible on https://deploy-preview-1057--wormhole-connect-mainnet.netlify.app/ [Mainnet]. Wallet address is displayed correctly in "Send to" section on Redeem screen. 

Scenarios - Tested OK:
* Send SUI from Sui (Sui wallet) to Solana (Phantom) with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/3H1yvP2sjXYYiZEpX72F6CkdZAkzCWaPH2aWcHK8Z5wy), [Solana explorer](https://explorer.solana.com/tx/3XHXmJN729aXHPX96q6vNNs2tgRTAeJPg3gbLSvtJy28UQHUcF3RrvLWVYPRZS4QxnJmQcEWVDJjtgEZBGR8XmcF))
* Send WBNB from Sui (Sui wallet) to Solana (Phantom) with automatic deposit ([Sui explorer](https://suiexplorer.com/txblock/HP8LmP88bZXWiZQpBH8jnMsoxq6xVP9vmzxaGakB1LMw), [Polygonscan](https://polygonscan.com/tx/0x59c3411e9ac31d2155e8c86df36d6488aa328d43623542e29abaa60702e6c707))
