### ISSUE TITLE
[QA] Many extra decimals are shown in amount in To section

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#985]
## Describe the current behavior in detail
[QA] Many extra decimals are shown in amount in To section.

Checked from https://cctp-only--wormhole-connect.netlify.app/ [Mainnet] with macOS 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Ethereum in From section
2. Select Arbitrum in To section
3. Connect Metamask wallets
4. Enter amount 1.12
5. Observe Amount in To section (actual result: 0.1200000000000001)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3c0a6fb2-b4e4-4bd9-b836-a3f8e2b7c705

## What is the expected/desired behavior
Correct Amount is displayed in To section.

**Comment by derpy-duck** [comment]
I believe this is correct - the fee is '1' so the amount received is '0.12'

**Comment by tsadovska** [comment]
@derpy-duck Just to double check, is it correct that 0.1200000000000001 amount is shown instead of 0.12?

**Comment by derpy-duck** [comment]
Ohh - no haha - I see, thought you were referring to the amount being incorrect, but fully agree that that many decimals should not be shown!
