### ISSUE TITLE
[QA]Internal JSON-RPC error for transaction from Torus wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#989]
Preconditions:
1. Torus wallet connected at sending From section
2. Metamask wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://deploy-preview-907--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 SOL from Solana to Fuji
2. Click Approve and proceed with transaction
3. Click Approve on wallet pop-up
4. Observe

Actual result: Error `WalletSendTransactionError: Internal JSON-RPC error.
    at Gc.solana.torus.sendTransaction` is shown in the console and transaction fails

Expected result: Transaction moves to the next window and is completed

Attachment:

<img width="1330" alt="Screenshot 2023-09-15 at 15 39 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d630e9a7-4e6b-4173-9677-56b25f70980b">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6cc98378-f1cd-45bc-9442-421dff103156

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet] when sending 0.0001 BNB from BSC (Metamask) to Solana (Torus). Error is displayed in Console:
```
WalletSendTransactionError: Internal JSON-RPC error.
    at Kc.solana.torus.sendTransaction (main.599bb233.js:37:19843126)
    at async Fc.sendTransaction (main.599bb233.js:37:19794049)
    at async ed (main.599bb233.js:37:19875935)
    at async Object.createAssociatedTokenAccount (main.599bb233.js:137:106922)
    at async onClick (main.599bb233.js:137:105697)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e4d39804-8218-48c3-a1a4-b8b36679e9c2)

**Comment by tsadovska** [comment]
Loading doesn't end when trying to connect Torus wallet. 

<img width="791" alt="image" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7f2ecf8d-3286-4bb7-b016-13e7873c5de5">

**Comment by AigaD** [comment]
Will be checked after https://github.com/wormhole-foundation/wormhole-connect/issues/1192 is resolved

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/.
Scenario checked: 0.00001 WSOL transfer from Solana (Torus) to Avalanche (MetaMask).
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/JhNTtqWLduGhfTqz4EthVsqB7YNL72p5NFLYEG1o9CYDRZ2sVaWdWyj9gW4Po1FPUNiLvu25DTgJM44V3ChA5UJ)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x1495bf553c08b6383e8cfd2f9b033f28e38d1312fb779caa80028ae71cf943b8)

Ticket is closed.
